datalad/datalad

datalad/core/local/status.py, datalad/support/annexrepo.py, datalad/utils.py
=> Fix minor status issues 

datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_uninstall.py, datalad/interface/rerun.py, datalad/interface/tests/test_annotate_paths.py, datalad/interface/tests/test_rerun.py, datalad/plugin/tests/test_addurls.py, datalad/support/gitrepo.py, datalad/support/repodates.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_repodates.py, datalad/support/tests/utils.py
Prompted by renewed interest in `git worktree` compatibility (gh-3528), this is a second round of GitPython pruning (following gh-2902).  It removes all uses of `repo.git.CMD` outside of `{git,annex}repo.py`.  It also does a few other easy replacements of things like `.hexsha`, but there are still places that GitPython is used outside of the repo classes.  I'll update the checkboxes at gh-2879.
=> Remove repo.git.CMD usage outside of repo modules

datalad/cmdline/main.py
For example, extensions that provide metadata extractors or dataset
procedures only.
Such extensions can now declare this in setup.py
```
setup(
...
entry_points = {
'datalad.extensions': [
'extname=extmodule:spec',
],
},
```
with `spec` being:
```
spec = ('My Extension Name', [])
```
=> ENH: Support DataLad extensions that do not provide commands

CONTRIBUTING.md
The upstream fix has been available since v0.3.
=> DOC: CONTRIBUTING: Remove rev-parse workaround for 'asv compare'

CHANGELOG.md
<details>
<summary>Changes reviewed</summary>
```
#
#
-  DOC: sshconnector: Fix docstring typos from bacaefa27
af2ffe29a^-1
-  MNT: Update changelog placeholders for latest rc
8dca03a43^-1
-  Merge pull request #3426 from mih/rf-diediediemydarling
b59bcb080^-1
-  Merge remote-tracking branch 'origin/0.11.x'
cddb04c3c^-1
-  RF: Remove dead and incomplete code (ls-remote) (#3437)
13039b685^-1
+  Merge pull request #3429 from mih/enh-subdatasets
95d2c0eba^-1
+  Merge pull request #3435 from mih/rf-paths
851426873^-1
-  CLN: wtf: Adjust spacing around _describe_python()
011a14339^-1
-  Merge remote-tracking branch 'origin/0.11.x'
dbc3aaa0a^-1
+  Merge pull request #3444 from kyleam/move-run
ce9c8b1ec^-1
+  NF: `create_sibling_gitlab` (#3447)
afdaca25b^-1
-  Merge branch '0.11.x' into …
```
=> CHANGELOG: Add entries for 0.12.0rc5

datalad/support/annexrepo.py
`AnnexRepo`, in particular `_run_annex_command_json`  didn't handle an INFO response from a special remote (see https://git-annex.branchable.com/design/external_special_remote_protocol/#index5h2).
Fixed that.
FTR: I won't implement an entire special remote just to fake some test herein. However, it will at least be implicitly tested by https://github.com/datalad/git-annex-ria-remote.
Meaning: I think it's fine if I didn't break anything ;-)
=> BF: AnnexRepo to deal with INFO response from annex special remotes

datalad/core/local/create.py, datalad/core/local/tests/test_create.py, datalad/distribution/tests/test_dataset.py
For top-level datasets, --force can be used to ignore the "is
empty directory?" check.  Make --force also disable the "is
subdataset?" check because this is consistent with the non-subdataset
behavior and was the behavior before the "rev-create -> create"
rewrite.
Fixes #3549.
---
I'm not sure that `create --force <existing subdataset>` is something we need to support, but I also don't see any harm in supporting it.
=> create: Allow forcibly creating a subdataset

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
This series addresses the subdataset issues we hit on the last call.
The remaining issue discussed on that call was that it seemed like a subdirectory needed to exist for `annex addurl --file <subdir>/file`, but that's not the case when I test locally (either with `git annex addurl` or `datalad addurls`) and I don't see anything in annex's history that suggests that it was a recent change.  I think that might have actually been related to one of the issues here, but please provide details here if you can trigger it on your end.
=> addurls: Fixes to subpath handling

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
This allows callers to perform arbitrary configuration of the
generated datasets.
---
=> ENH: addurls: Add --cfg-proc option that is passed to create()

datalad/support/tests/test_annexrepo.py
Will fail first on travis, then whenever https://github.com/datalad/datalad/pull/3541 passes and I upload new annex to neurodebian proper, rerun the tests and should get green, and then we merge
=> ENH(TST,BK): test_v7_detached_get to excercise a fixed in recent (7.20190708+git36-g32d526164-1) annex

datalad/distribution/tests/test_clone.py, datalad/distribution/utils.py
Matching by the name is not sufficient, since when we just clone such
repository it would get an arbitrary (by default "origin") name which
would not match the one git-annex calls it by.  Checking by annex UUID
seems to be the best way to proceed
FOI: test takes 1.7sec on my laptop (on network close to the datasets.datalad.org)
=> BF: check special remotes of type git by uuid to (not) inform if they are not enabled

datalad/interface/annotate_paths.py, datalad/interface/tests/test_annotate_paths.py
Otherwise there is a rediscovery of subdatasets for EVERY path provided to annotate_paths even when they all belong to the same parent dataset.
Closes: #3567 
TODOs:
- (not here) we really should add a benchmark suite operating on a set of paths within a bigger dataset across a variety of commands
=> OPT: maintain cache of discovered subdatasets in the loop of annotate_paths

datalad/support/annexrepo.py
Originally found while timing effects of a PR:
https://github.com/datalad/datalad/pull/3570#issuecomment-517084987
Similar change is now done also on git-annex level in
d1a0c7b16fcd41f74def394a55c32f67340670b7
but to not wait for its new release, adjusting our
find invocations
TODOs
=> OPT: use find --in ., not --in here to gain 3x speed up on some cases

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
Fixes gh-3577 and another gh-3577-inspired issue.
=> addurls: Provide better handling of invalid and empty input

datalad/support/gitrepo.py
a chaser for https://github.com/datalad/datalad/pull/3508 before we forget.
If there is a known use case where we shouldn't warn, please let me know.  I just hate chasing bugs when reason was obvious and we didn't throw a message into the face
=> RF: log a warning, not debug msg if .gitmodules contains unexpected record

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
Fixes #3553 
Plus bonus reformatting of imports.
=> Fix `siblings` crash with missing --name

datalad/interface/utils.py
Original OPT issue: https://github.com/datalad/datalad/issues/3575 . This PR addresses only one aspect, and doesn't touch upon relatively slow `.config` and `.is_installed` which are yet to be figured out and probably should be properly "lazied" at the dataset level since  we are doing this over and over for every decorated function in the same dataset!
Those added debug statements seems to have no cost but could help determining unexpected
slow downs
For me it is cutting down time for a dummy `datalad run` from 2.9 to 2.2 sec (so ~20% boost! ;))
```
~datalad/datalad > time DATALAD_LOG_TIMESTAMP=1 datalad run --explicit --input benchmarks echo nothing todo 2>&1 | tools/dtime 
1280 2019-08-01 11:40:50,695 [INFO] Making sure inputs are available (this may take some time) 
- nothing todo
3 …
```
=> OPT+ENH: determine config to query for procedure once, add more "log(2," to eval_func

datalad/distribution/remove.py
rev_save() has been promoted to save(), but there are still a few
places where the obsolete save() is used.  One of these spots is
remove.py, where 1c49a1f2a (MNT: interface.save: Demote and mark
obsolete, 2019-05-14) claimed the old save() is needed because
annotated paths are passed as arguments.  But instead of punting until
annotate_paths() use is dropped from remove.py (gh-3368), we can make
the call compatible with the new save() by pulling out the paths from
the annotated paths record.
In addition to dropping the internal use of an obsolete command, this
avoids spurious warnings about removed files not existing.
Closes #3441.
---
I didn't find any failures with selective testing locally.  Let's see how the full Travis build goes.
=> RF: remove: Replace interface.save with core.local.save

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
Follow conventions (different on master and 0.11.x) for taking URL-FILE as relative to the specified dataset.
This PR is against master, but it has a 0.11.x component.  I've pushed that 0.11.x-based branch to a scratch branch so that we can check [its Travis build][tb].  If all looks good, I'll merge the 0.11.x-bits to 0.11.x after this PR is merged to master.
[tb]: https://travis-ci.org/datalad/datalad/builds/567119012
Closes #3580.
=> addurls: Fix handling of relative URL-FILE

datalad/support/annexrepo.py
Otherwise long lists of full paths quickly cause "too long" crash.
Closes #3585 
TODOs
=> BF: pass "paths" as "files" argument to _run...command for proper chunking

datalad/core/local/create.py, datalad/core/local/tests/test_create.py
When a dataset is explicitly specified together with a --cfg-proc
procedure, the created subdataset shows up as modified in the
reference dataset because cfg_* procedures create a commit with their
changes.  Save the reference dataset after running procedures so that
we register the up-to-date version of the subdataset.
Fixes #3591.
=> BF: create: Run cfg procedures before saving reference dataset

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
Replace a KeyError like
'_url_hhostname' [string.py:get_value:252] (KeyError)
with a more helpful
Unknown placeholder in file name: '_url_hhostname'. Did you mean any of these?
_url_hostname
_url_basename
_url_basename_ext
=> ENH: addurls: Suggest close matches for placeholders

datalad/support/tests/utils.py
Revert 4698fda6b's changes to `check_repo_deals_with_inode_change` so that the test checks the intended GitPython failure.
This PR should bring master to a failing state :)
Re: #3598
=> Restore use of GitPython in inode check

datalad/distribution/dataset.py, datalad/distribution/tests/test_create.py, datalad/distribution/tests/test_dataset.py, datalad/plugin/tests/test_plugins.py, datalad/plugin/wtf.py, datalad/support/gitrepo.py, datalad/tests/test_utils.py, datalad/utils.py
These were all discovered when looking into gh-3563.  I've only run a subset of the tests, so I'm crossing my fingers that the changes don't trigger failures elsewhere.
Fixes #3563.
=> A few py2 Unicode fixes

datalad/support/tests/utils.py
test_{Git,Annex}Repo_flyweight_monitoring_inode started failing with
GitPython v3.0.0.  The problematic commit has been reverted in
GitPython's d5cc590.  Let's get Travis back to green by skipping these
tests if GitPython v3.0.0 is installed.
Re: #3598
=> TST: repo: Skip inode tests when latest GitPython is detected

datalad/core/local/create.py, datalad/core/local/status.py, datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_save.py, datalad/interface/utils.py
This series has a few py2 unicode fixes spurred by gh-3597.  It relies on a fix from that PR (temporarily applied here as the tip commit), so I'll mark this PR has a draft until that gh-3597 lands in master.
=> A few py2 unicode fixes (master-specific)

datalad/distribution/tests/test_create_github.py, datalad/support/vcr_.py
Since we are providing fake token they have no chance to work correctly
if there is no vcr library.  So better to skip those tests if no vcr library.
I have ran into it while running  datalad test  on datalad installed in
conda, but without having all test requirements installed
=> RF+BF: make github tests skip if there is no vcr library

datalad/support/sshconnector.py, datalad/support/sshrun.py, datalad/support/tests/test_sshrun.py
This PR adjusts sshrun and sshconnector to fix the failure from gh-3596.  This was originally observed with datalad-neuroimaging's nipype_workshop_dataset.sh example on Travis.  As mentioned in gh-3596, I don't understand why our create_sibling() tests don't trigger the same failure in the Travis/Xenial environment.  I've started a -neuroimaging [build][0] that uses this PR branch, and that appears to fix the failure ([example 1][1], [example 2][2]).  Note that there are other (hopefully unrelated) failures on python 2.
[0]: https://travis-ci.org/datalad/datalad-neuroimaging/builds/575614640
[1]: https://travis-ci.org/datalad/datalad-neuroimaging/jobs/575614641#L1441
[2]: https://travis-ci.org/datalad/datalad-neuroimaging/jobs/575614643#L1445
=> sshrun: Provide all expected GIT_SSH_COMMAND parameters

datalad/support/cookies.py, datalad/support/tests/test_cookies.py
While running tests under some conda environment, there were errors while closing
cookies DB. Could not reproduce in the native Debian environment with similarishish
Python.  With these changes, cookies_db is a property so it gets properly
loadded before setting any value. And also we catch exceptions upon
close and report them as a warning if there were some cookies to store.
Unfortunately Python in conda env still prints directly the entire traceback, and
on Debian some error message even before throwing the exception so you could see something like
$> DATALAD_LOG_LEVEL=INFO python -m nose -s -v datalad/support/tests/test_cookies.py
datalad.support.tests.test_cookies.test_no_blows ... [WARNING] Failed to save possibly updated 1 cookies (best): [Errno 2] No such file or directory: …
=> RF+BF: make cookies db access/closing more robust

datalad/customremotes/datalad.py, datalad/downloaders/base.py, datalad/downloaders/http.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_http.py, datalad/support/third/loris_token_generator.py
Pretty much just moving the affected code (see #3621). Plus replacement of `import *` usage.
Fingers crossed...
=> Fix gh-3621 broken error handling under PY3

datalad/interface/run_procedure.py
Stay within the same Python version to avoid crash or undesired behavior
when PY2 is called from PY3 with missing or outdated PY2 versions of
datalad.
=> BF: run_procedure: do not hardcode python executable (fixes gh-3623)

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_external_versions.py, datalad/tests/test_direct_mode.py, datalad/tests/utils.py
This series updates annexrepo.py and the test suite for git-annex's removal of direct mode (gh-3627).  It resolves issues that I've caught from running the test suite locally with a git-annex built from d6e1f09ed, but we'd of course want a run on Travis before merging this.
=> Prepare for git-annex's removal of direct mode

datalad/downloaders/base.py, datalad/downloaders/tests/test_http.py, datalad/interface/tests/test_download_url.py
download_url() doesn't check that leading directories for a target
exist, resulting in a failing .download() call, but it's reasonable
for a download_url() caller to expect that directories will be created
if needed, especially given `git annex addurl --file ...` does so.
Ensuring target directories exist seems desirable for all .download()
callers, so handle it within downloaders/base.py rather than in
download_url().
Fixes #3642.
=> ENH: downloaders: Ensure directories for target exist

Makefile
In Debian, where python will be a taboo soon, there is still a patch from
Steve Langasek which hardcodes to use python3.  With this change we still
would be able to switch quickly between python 2 and 3, but I also wanted to
keep default python to be used by default since it might be just the python
(even if 3.x) available
=> ENH: use $(PYTHON) instead of hardcoded python in all invocations in Makefile

datalad/interface/rerun.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_rerun_merges.py
Tagging as WIP because I want to test it out a bit more.
~- [ ] how should we handle cases where a merge is in the revision range but only one of the parents is?~
~- [ ] handle merges of unrelated branches~
Update: Lots to do in a reroll.  See https://github.com/datalad/datalad/pull/2754#issuecomment-412226197
=> ENH: Teach rerun how to handle merges

datalad/support/annexrepo.py, datalad/tests/test_direct_mode.py
I failed to adjust one test on master for a git-annex without direct mode support, as shown by the failing test here: https://travis-ci.org/datalad/datalad/jobs/581799658
=> TST: Skip part of test_direct_cfg when direct mode is unsupported

datalad/tests/test_cmd.py
test_runner_heavy_output() is parameterized by log_online value, but
one call hard codes log_online to True.
=> TST: cmd: Fix call that hard codes parameterized test value

datalad/cmd.py, datalad/tests/test_cmd.py
Now that we have a branch that drops Python 2, I've been looking into using asyncio in the runner.  Much of that so far has been trying to wrap my head around how the different parameters of Runner.run() interact.  While doing this, I realized that some output lines were being lost.
---
```
When the Runner is called with log_online=True and we're logging
either stdout or stderr, the readline() call for the stream happens
under a `while proc.poll() is None`.  After that block, we may have
uncaptured output, either because the process was already finished by
the time we got to the proc.poll() condition or because each iteration
reads only a single line.  To collect this output, communicate() is
called.
However, communicate() may return an empty string even when there is
uncaptured output …
```
=> BF: cmd: Don't leave unread lines on stream when logging online

datalad/interface/tests/test_run_procedure.py, datalad/resources/procedures/cfg_yoda.py
Before it would save the entire state of a dataset. Fixes #3666
Adjust and extend tests to cover the new behavior.
=> ENH+TST: cfg_yoda will commit selectively and fail on dirty

datalad/support/annexrepo.py
When the git-annex version used on AppVeyor went from git-annex
7.20190731-gc131c0f0c to 7.20190912-g05bc37910,
test_update.test_multiway_merge started to fail.  The failure occurs
in _run_simple_annex_command(), which asserts that it gets no more
than one line.  The unexpected extra lines seem to be coming from
empty lines:
https://ci.appveyor.com/project/mih/datalad/builds/27446423#L684
_run_simple_annex_command() already filters the output lines to remove
some informational messages from git-annex.  Update that condition to
remove empty lines as well.
Fixes #3675.
---
Note that the failing test from #3675 is skipped on AppVeyor for 0.11.x because it is incompatible with direct mode.  To make sure this failure is resolved on master, I've pushed a scratch branch that sits on top of …
=> BF: annexrepo: Skip empty lines when expecting one output line

_datalad_build_support/formatters.py
This workaround makes this possible without having to wrap the entire
statement in 
```
``...``
```
(which looks weird), and without having to turn
off smart quotes in general (which looks bad elsewhere).
=> BF: Ensure double-dashes in RST manpages show up as such (fixes gh-3672)

datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py
To prevent us from shooting ourselves in the foot. Without
this change, we could have specified section-less variables
that our own ConfigManager cannot handle, and don't seem to
be supported by Git either.
=> ENH: Config override spec sanity checks (fixes gh-3451)

datalad/support/sshconnector.py
This quoting should be unnecessary (and counter-productive), because the
command arg list is not evaluated by a shell.
Given that SSH on windows is more broken than that, there is no real
test for this on windows yet, but I manually confirmed that this works.
Also fixes
=> BF: Do not quote path in cmd arg list (fixes gh-3637)

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> Remove obsolete code, trim deps on GitPy

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
This also introduce slight changes in the API semantics, by removing
needless flexibility (ie. specifying a to-be-updated dataset either
via -d or as a path). Multi-seed recursive operation is also no longer
supported, in line with previous changes.
The PATH arg is now only used to constrain the updating of subdatasets
in recursive mode.
ping gh-3368
=> RF: update() no longer uses AnnotatePaths

datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/utils.py, docs/examples/3rdparty_analysis_workflow.sh
This PR fixes test failures that I found locally when running with a git-annex built from annex's v7-default branch (b421004d75).  I'm marking it as a draft because before merging we should have a Travis run with a git-annex version that auto-upgrades v5 repositories.
On a throw-away merge of this PR's branch into master, the datalad/core tests passed for me, but master's tests may need additional fixes elsewhere.
Closes #3628.
---
=> TST: Don't assume default annex repo version is v5

.travis.yml, tools/ci/prep-travis-devel-annex.sh
I found this change lingering in the bf-annex-devel-run branch (e.g. used in #3466 ) intended to test
development version of annex from debian-devel of neurodebian.  It was to solve
the ambiguity of tools/ci/prep-travis-devel-annex.sh exiting with non-0 for other
reasons and thus us just skipping the run (marking it green)
=> ENH: exit with dedicated 99 exit code if installed annex is newer than -devel

datalad/distribution/tests/test_publish.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This merely lifts the implementation from https://github.com/datalad/git-annex-ria-remote/blob/09a3eec05d89e2bb26f7ea2038d3e1aedd1ffe48/ria_remote/tests/utils.py#L32
and adds some docs.
A smoke test will come, likely infused into existing tests. I have no immediate plans to test the more exotic parts (scheduled incremental, etc).
=> ENH: (More) comprehensive AnnexRepo.fsck() (fixes gh-3514)

datalad/core/local/status.py
This can make an essential performance difference in datasets with a large number of files.
Demo:
```
% git annex info | grep '^annexed'
annexed files in working tree: 20054
% time datalad status -t eval
datalad status -t eval  79.15s user 1.51s system 98% cpu 1:21.53 total
% time datalad status -t raw
datalad status -t raw  2.13s user 0.64s system 100% cpu 2.765 total
```
Ping https://github.com/datalad/datalad/issues/3342 @yarikoptic
=> ENH: Expose status() file type inspection mode switch

datalad/support/gitrepo.py, datalad/support/repodates.py
Work towards gh-3703
km: 477e23a85 fixes the test_repodates.py:test_check_dates failure.
It seems that the present code doesn't conveniently handle things like annotated tags that point to an actual commit we are interested in, but actually have a separate `objectname` (or SHA1).
=> NF: GitRepo.for_each_ref_()

datalad/distribution/create.py, datalad/distribution/tests/test_create.py, datalad/interface/tests/test_run_procedure.py, datalad/resources/procedures/cfg_text2git.py
As noted in #3663, in a dataset configured with ``cfg_text2git``, empty files are being annexed. This PR adds the additional rule to not regard empty files (mimetype ``inode/x-empty``) as a largefile to the ``.gitattributes`` configuration ``cfg_text2git`` provides.
Additionally, it adds a small test for this.
It's WIP because I want to see whether any test fail as @kyleam noted in #3663:
> I suppose one tricky part about testing cfg_text2git is that the behavior depends on git-annex being built with the MagicMime flag. But assuming MagicMime support should be fine because neurodebian's git-annex has it and it looks like conda's does now too. If it ends up being a problem down the road, we can skip the test based on the git annex version output.
=> don't annex empty files after cfg_text2git,  fixes #3663

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
```
Prior to the for_each_ref_() series (gh-3705), get_tags() returned
tags sorted by the committer date.  For annotated tags, this means
they were sorted by the object pointed to rather than the tagger date.
Following gh-3705, the sorted value is by for-each-ref's "creatordate"
field (which exists so that lightweight and annotated tags can be
sorted together), and annotated tags are now sorted based on the
tagger date.
This change seems harmless enough.  No current callers in the code
base rely on annotated tags being sorted by committer date, and it
seems unlikely that outside callers rely on this behavior.  But it
does mean that test_get_tags needs to patch GIT_COMMITTER_DATE when
creating annotated tags so that the tagger date is not affected by the
environment of the test run.
If we …
```
=> DOC+TST: gitrepo: Document get_tags() order change from eed2ca6f6

datalad/interface/utils.py
=> BF: path_is_under() could not handle win paths from different drives

datalad/core/local/save.py, datalad/support/tests/test_annexrepo.py
According to my current logic and assessment, the `status()` run done in
top-level `save()` does not need to inspect filetypes. The tests will show
if that is true.
If true, performance gains of the same magnitude as shown in
https://github.com/datalad/datalad/pull/3701 for `status()` also become
available for `save()`.
=> RF: Blind attempt to relay status() performance boost possibility on to save()

.github/workflows/benchmarks.yml, .github/workflows/docbuild.yml, .github/workflows/test_win2019.yml
Running them on 'push' will cause actions to run in the repo
that has been pushed into. However, in almost all cases we
want to see the result in the base repo.
Moreover, I feel better to not kick of users of computing
for each push that doesn't happen in a PR.
=> TST: Let actions run on 'pull_request' events

datalad/distribution/dataset.py, datalad/distribution/get.py, datalad/local/subdatasets.py, datalad/local/tests/test_subdataset.py
Sorting paths (for locally present content, and unavailable stuff) into
containing (present) datasets is a key task for helper code such as
annotate_paths(). This change equips `subdatasets()` with the ability
to make similar reports by including a 'contains' property in its
results whenever a respective set of paths has been provided.
Such a result looks like this:
```
{
"action": "subdataset",
"contains": [
"/tmp/datalad_temp_test_get_in_unavailable_subdatasetdzceqobr/sub1/sub2"
],
"gitmodule_datalad-id": "1b1e4b70-e472-11e9-9214-f0d5bf7b5561",
"gitmodule_name": "sub1",
"gitmodule_url": "./sub1",
"gitshasum": "15428154a3573488503151ddc42051281221e8f8",
"parentds": "/tmp/datalad_temp_test_get_in_unavailable_subdatasetdzceqobr",
"path": …
```
=> ENH: subdatasets(contains=...) will report matching paths in result

datalad/distribution/remove.py, datalad/distribution/tests/test_uninstall.py, datalad/distribution/uninstall.py
(fixes gh-3661)
processing of large numbers of subdatasets (fixes gh-3655)
was:
datalad uninstall -r --nocheck */*  301.58s user 131.57s system 99% cpu 7:15.19 total
is:
datalad uninstall -r --nocheck */*  111.21s user 48.07s system 105% cpu 2:31.61 total
=> RF: uninstall

datalad/core/local/create.py, datalad/core/local/tests/test_create.py
Now with a more comprehensive test.
=> BF: create() path semantics (fixes gh-3748)

datalad/interface/common_cfg.py, datalad/interface/utils.py
Setting this will cause messages included in command results (which are independently rendered as part of a result) to go to the identified log level (debug, info, warning, error). This can be used to alter the default behavior to have 'impossible' results cause a 'warning' log message and 'error' results yield an 'error' log message.
The default setup leads to cluttered output and double messaging. Setting this switch to 'debug' hides all result logging and emphasizes final results over intermediate events (where an 'error' may or may not be an indication of a problem in the big picture of a command execution).
Exemplary impact:
was
```
% datalad install http://example.com/nothere
[INFO   ] Cloning http://example.com/nothere [1 other candidates] into '/tmp/nothere' 
[ERROR  ] Failed to …
```
=> Introduce datalad.log.result-level config switch

datalad/core/local/run.py, datalad/core/local/tests/test_run.py, datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_uninstall.py, datalad/interface/results.py, datalad/interface/tests/test_annotate_paths.py, datalad/interface/tests/test_rerun.py, datalad/metadata/aggregate.py, datalad/metadata/metadata.py
This sits on top of gh-3746 and should fix the run failures (including hopefully the Windows one; edit: that was [too hopeful][1]).  Here's the [restricted diff][0].  This series could be merged into that PR or merged into master following that PR.  Or, if desired, I can separate this series from that one, though there will end up being at least be some minor conflicts to deal with.
This fixes gh-3551.  The added test, based off of the examples in that issue, will run on Windows, so it might need a compatibility fixup.
[0]: https://github.com/datalad/datalad/compare/89467b9c4ef12bba69e8212941fb9df6ea53091c...kyleam:run-go-unbound
[1]:  https://github.com/datalad/datalad/pull/3747/checks?check_run_id=248506600#step:8:374
=> run: Fix path handling for gh-3746 and for subdirectory runs

datalad/core/local/run.py, datalad/core/local/tests/test_run.py, datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_uninstall.py, datalad/interface/results.py, datalad/interface/tests/test_annotate_paths.py, datalad/interface/tests/test_rerun.py, datalad/metadata/aggregate.py, datalad/metadata/metadata.py
This tries to be a gentle RF that doesn't change (much) of the original
behavior (see test diff). However, a change in-line with #3742 is
unavoidable (see removed test).
This is bringing path semantics in line with status/subdatasets, and is
a precondition to fixing #3469
Ping #3368
=> RF: get() without annotate_paths()

datalad/interface/utils.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py
Turns this:
```
% datalad save
add(error): that3 (file)
```
into
```
% datalad save
add(error): that3 (file) [  that3: setFileMode: permission denied (Operation not permitted)]
```
hence fixes gh-3685
Note that this does not fix the same issue in `add()`, because different code is used (see gh-3714).
=> Capture error messages from git-annex's JSON output

datalad/core/local/create.py
This uses ``assure_list`` to ensure that ``cfg_proc`` is a list. Else, something like this happens when using the Python API and ``cfp_proc='<proc_name>'``
```python
create(path='/tmp/t8', cfg_proc='text2git')                                                     
[INFO   ] Creating a new annex repo at /tmp/t8 
[WARNING] Cannot find procedure with name 'cfg_t' [run_procedure(cfg_t)]                                
```
=> ENH: create: assure cfg_proc is list

datalad/support/tests/test_annexrepo.py
detected in #3763 and #3762 test runs
git annex changelog says
```
+  * Fix bug in handling of annex.largefiles that use largerthan/smallerthan.
+    When adding a modified file, it incorrectly used the file size of the
+    old version of the file, not the current size.
```
=> BF: reflect in our test the change in behavior (fix) in annex 7.20191009

datalad/local/subdatasets.py, datalad/support/gitrepo.py
This addresses some aspect of gh-3766
It also removes an unused feature to limit the check to remote branches.
Even the crawler doesn't use it.
It also removes an explicit check for a direct mode related branch name,
that doesn't seem to be relevant, even for direct mode repos, and
@bpoldrack oldrack also had no memory on when exactly this could happen. Given
that we do not support it anymore, I decided to remove the additional
complexity.
Here is the updated profile (compare to https://github.com/datalad/datalad/issues/3766#issuecomment-540937940)
```
before           after         ratio
[6ad8d02f]       [91bc32fa]
<bm/merge-target>       <bm/pr>   
1.75±0.07s       1.46±0.05s    ~0.83  api.supers.time_createadd
-      2.78±0.06s       1.89±0.04s     0.68 …
```
=> OPT: Half the number of for-each-ref calls in GitRepo.is_with_annex()

datalad/distribution/clone.py, datalad/distribution/tests/test_clone.py
A very common reason for such an error is a simple typo in a URL. This change turns:
```
$ datalad install http://github/datalad/datalad-neuroimaging.git
install(error): /tmp/datalad-neuroimaging (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('http://github/datalad/datalad-neuroimaging.git', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v http://github/datalad/datalad-neuroimaging.git /tmp/datalad-neuroimaging [cmd.py:wait:418]"), ('http://github/datalad/datalad-neuroimaging.git/.git', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v …
```
=> ENH: More human readable error on clone failure

datalad/support/exceptions.py, datalad/support/sshconnector.py
Changes the return value semantics (see inside) and raises `CommandError` when no ControlMaster can be started. This enables to act on error on the caller side without causing spurious
warnings.
It turns the output given in gh-3450:
```
% datalad publish --to bareremote --transfer-data all
mih@datalad-test: Permission denied (publickey,password).
[WARNING] Failed to run cmd ['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/c5820c82', 'datalad-test']. Exit code=255
| stdout: None
| stderr: None
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git fetch --progress -v bareremote
|   stderr: 'fatal: Could not read from remote repository.
|
| Please make …
```
=> RF: Make SSHConnection.open() errors actionable for callers()

datalad/interface/base.py
This should be the last use outside of code that isn't obsolete already.
Towards: https://github.com/datalad/datalad/issues/3778
=> RF: `resolve_path()` -> `rev_resolve_path()` in `Interface`

datalad/customremotes/tests/test_archives.py, datalad/tests/test_archives.py
Python issue: https://bugs.python.org/issue38449
Closes #3769 
TODO:
=> BF(TST,workaround): do not use ; in the test archive filenames

datalad/distribution/clone.py, datalad/distribution/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/distribution/utils.py
=> Light RF of `clone()`

datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/support/gitrepo.py
Fixes gh-3356 gh-3795
For the new usage of `rev_get_dataset_root()` see #3796
=> BF: Be able to get *two* files from an uninstalled subdataset

datalad/interface/run_procedure.py, datalad/interface/tests/test_run_procedure.py
Closes #3792
We used to discover a directory at the configured procedure location as an actual procedure based on its executable flag.
=> BF: Don't discover directory as procedure

datalad/cmdline/helpers.py
Due to an earlier change the version is now located in a different position in the header.
Fixes gh-3151
=> BF: Adjust version extraction from manpage for proper test

datalad/core/local/create.py, datalad/core/local/diff.py, datalad/core/local/status.py, datalad/distributed/create_sibling_gitlab.py, datalad/distribution/clone.py, datalad/distribution/dataset.py, datalad/distribution/install.py, datalad/distribution/tests/test_dataset.py, datalad/interface/annotate_paths.py, datalad/interface/base.py, datalad/interface/tests/test_annotate_paths.py, datalad/interface/unlock.py, datalad/local/subdatasets.py, datalad/plugin/addurls.py
Fixes gh-3778
Old function is now an internal helper of `annotate_paths()`, and the tests have moved their as well. A more extensive test suite for the "new" function was already in place.
=> RF: rev_resolve_path() -> resolve_path()

datalad/__init__.py
This is following the advice from https://github.com/datalad/datalad/pull/2832#issuecomment-421403674 and substituting a completed https://github.com/datalad/datalad/pull/2832 that hasn't come yet.
In some sense fixes gh-2461
=> BF: Add basic import failure on `python -O` execution

datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_update.py, datalad/interface/rerun.py, datalad/interface/tests/test_add_archive_content.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_rerun_merges.py, datalad/interface/tests/test_save.py, datalad/interface/tests/test_unlock.py, datalad/local/subdatasets.py, datalad/support/gitrepo.py, datalad/support/repodates.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_repodates.py
This is a draft PR with the initial implementation of the methods mentioned in gh-3789.  There's a lot of wiggle room in terms of how to lump or split (you'll notice that I merged a couple of the methods from gh-3789 together), so any feedback on that would be welcome.
=> gitrepo: Expose methods for direct git calls

datalad/cmd.py, datalad/support/exceptions.py
Otherwise it was observed (#3613) that batched parallel `git annex get` instances might still remain
running consuming bandwidth and resources.
I have added try/except around .terminate() call itself, although it might be
an overkill since in normal scenarios I do not expect that to fail.
I have tested locally by interrupting `datalad get` invocations, and it seems to do the trick!
Closes #3613
TODOs
=> BF: explicitely terminate the Popen process if exception (e.g. KeyboardInterrupt)

datalad/core/local/save.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
i.e. pass arbitrary command options
=> ENH+NF: Better `git tag` support

datalad/__init__.py, datalad/config.py, datalad/support/gitrepo.py, datalad/tests/test_base.py
Also considers standard environment variables now.
Importantly, the check is no down without dedicated extra calls to git
config, saving two calls (that were pretty much always performed).
Fixes gh-3750
=> BF: Move Git identity check into ConfigManager and make more valid

datalad/distribution/get.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> RF: Remove unused and untested GitRepo.get_file_content()

datalad/core/local/create.py, datalad/core/local/diff.py, datalad/core/local/status.py, datalad/distribution/dataset.py, datalad/distribution/get.py, datalad/utils.py
A `rev_get_dataset_root` symbol remains in place to allow for peaceful transition of code that was already using it.
Fixes gh-3796
=> RF: Standardize on rev_get_dataset_root() -> get_dataset_root()

datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/distribution/utils.py, datalad/metadata/aggregate.py, datalad/metadata/search.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This fixes gh-3827, while also tweaking a little bit on the sides -- this is rather old code.
This is technically ready. Once agreed on, there will be a use case description in the handbook on feature.
=> More flexible clone URL generation for submodules

datalad/cmdline/main.py, datalad/core/local/create.py, datalad/core/local/run.py, datalad/core/local/save.py, datalad/core/local/status.py, datalad/distribution/drop.py, datalad/distribution/get.py, datalad/distribution/install.py, datalad/interface/base.py, docs/source/designpatterns.rst
Following up on #3757, I'm drafting a standardized way to include examples into the docstrings or help messages of commands, and I would appreciate critical feedback.
My idea was to mimick the current way in which `_params_` within each command class holds the commands parameters and has custom functions to add them to the parser or the docstring.
I propose to have `_examples_` as a list of dictionaries, with each dictionary being one command example. The key `text` holds a description of the example, and `code_py` or `code_cmd` keys holds code snippets.
```python
_examples_ = [
dict(text="""Apply the text2git procedure upon creation of a dataset""",
code_py="create(path='mydataset', cfg_proc='text2git')",
code_cmd="datalad create -c text2git mydataset"),
```
Based on `_examples_`, …
=> ENH: Standardized way to add examples to commands

datalad/plugin/addurls.py, datalad/support/s3.py
=> BF/ENH: pass through already versioned s3:// urls while requesting them being versioned

datalad/distribution/get.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This implements a long-standing TODO. It was originally part of https://github.com/datalad/datalad/pull/3828 but I moved it out, because it may need more work.
=> RF: Move tracking branch update functionality into GitRepo.update_submodule()

datalad/support/annexrepo.py
E.g. was happening during
$> rm 100206_3T_Diffusion_unproc.json; datalad download-url s3://hcp-openaccess/HCP_1200/100206/.xdlm/100206_3T_Diffusion_unproc.json
[INFO   ] Downloading 's3://hcp-openaccess/HCP_1200/100206/.xdlm/100206_3T_Diffusion_unproc.json' into '/tmp/testds'
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication
download_url(ok): /tmp/testds/100206_3T_Diffusion_unproc.json (file)
add(ok): 100206_3T_Diffusion_unproc.json (file)
[WARNING] Registering /tmp/testds/100206_3T_Diffusion_unproc.json with s3://hcp-openaccess/HCP_1200/100206/.xdlm/100206_3T_Diffusion_unproc.json failed: AnnexBatchCommandError: command 'addurl'
Error, annex reported failure for addurl (url='s3://hcp-openaccess/HCP_1200/100206/.xdlm/100206_3T_Diffusion_unproc.json'): …
=> ENH: swallow exceptions in __del__ if lgr or os.fdopen already unbound

datalad/cmd.py, datalad/support/annexrepo.py
@yarikoptic This resolves master's conflict with gh-3835 by relocating your recently added `SafeDelCloseMixin` to cmd.py.  Is that OK with you?
I'm marking this as "do not merge" because a merge via github would result in a needless merge commit.
```
0.11.x's c031806c6 (ENH: swallow exceptions in __del__ if lgr or
os.fdopen already unbound, gh-3851) defined a SafeDelCloseMixin class
in annexrepo.py and used it as a base class for BatchedAnnex and
BatchedAnnexes.  On master, 9d714f520 (2019-04-08) relocated much of
the core functionality for BatchedAnnex to cmd.py as BatchedCommand.
SafeDelCloseMixin is relevant for BatchedCommand (which is used in a
spot other than annexrepo.py), so move SafeDelCloseMixin to cmd.py and
drop BatchedCommand's __del__() method.
Conflicts: …
```
=> Resolve conflicts to bring gh-3835 into master

datalad/support/tests/test_gitrepo.py
So it fails with `7.20191017+git2-g7b13db551-1~ndall+1` available from neurodebian devel and passes with `7.20190819+git2-g908476a9b-1~ndall+1` available from neurodebian proper. So I expect tests to pass here and I will merge it then. TODO will be checkmarked "post-merge" if I fix it later
TODO
=> TST(BK): demonstrates that current git-annex-standalone fails to clone from https:// urls

datalad/interface/rerun.py, datalad/interface/tests/test_rerun.py
When we started storing the diff() results in 168c49e23 (NF: rerun:
Add --report, 2018-05-22), the results didn't include unchanged files.
However, the new diff() command---merged with 50beb3bca (RF: Aborb
rev-diff, 2019-04-30)---returns an entry for all files in the working
tree, with unchanged files having a state of "clean".
Filter these out to restore the original behavior and avoid dumping a
large amount of uninteresting information to `rerun --report` callers.
=> BF: rerun --report: Restore diff value to original form

datalad/interface/unlock.py
it should not be necessary determine the actual file type for unlock's internal need. So all those cycles can be saved.
Discovered in the context of https://github.com/datalad/datalad/issues/3869
=> ENH: Speed-up initial status() run in unlock()

datalad/distribution/siblings.py
This patch prevents a spurious warning from an `update` call in `siblings`.  I noticed it when calling `create-sibling`:
$ datalad create-sibling -r -s sm smaug:scratch/sib
[INFO   ] Connecting ...
[INFO   ] Considering to create a target dataset /tmp/dl-5RhTQQG at scratch/sib of smaug
[WARNING] path constraints for subdataset updates ignored, because `recursive` option was not given
[INFO   ] Fetching updates for <Dataset path=/tmp/dl-5RhTQQG>
.: sm(+) [smaug:scratch/sib (git)]
[INFO   ] Adjusting remote git configuration
[INFO   ] Running post-update hooks in all created siblings
create_sibling(ok): . (dataset)
=> RF: siblings: Do not call update() with 'path' argument

datalad/cmdline/helpers.py
Logic did not consider the situation of no subcommand list being
present in the help string.
I will merge this quickly!
Fucked up by myself in https://github.com/datalad/datalad/pull/3862
=> BF: All subcommand shorthelps crashed

datalad/plugin/wtf.py
Dunno why we didn't have this since the start. But being able to
identify a dataset without having to fall back to Git (hoping that we
never move that file):
git config --file .datalad/config datalad.dataset.id
seems like a good thing:
datalad -f '{infos[dataset][id]}' wtf -S dataset
=> ENH: wtf() reports dataset ID

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
=> BF: Tolerate dead annexes, git-annex reports no description

datalad/interface/download_url.py, datalad/interface/tests/test_download_url.py
This patch fixes gh-3847.
```sh
#!/bin/sh
set -eu
cd $(mktemp -d --tmpdir dl-XXXXXXX)
datalad create
mkdir out
url=http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip
datalad -C out download-url --archive $url
tree --charset=asci out | head
```
```
[...]
add (ok: 1)
download_url (ok: 1)
save (ok: 1)
out
`-- data
|-- inflammation-01.csv -> ../../.git/annex/objects/Kg/60/MD5E-s5365--d5a838342924a0806eeeea0e4adaba0a.csv/MD5E-s5365--d5a838342924a0806eeeea0e4adaba0a.csv
|-- inflammation-02.csv -> ../../.git/annex/objects/zp/qF/MD5E-s5314--0551caa3e8a0ef3a53e99a4a01c27a65.csv/MD5E-s5314--0551caa3e8a0ef3a53e99a4a01c27a65.csv
|-- inflammation-03.csv -> ../../.git/annex/objects/2Q/Fj/MD5E-s5127--671c1563d3bd76538dab97537c370623.csv/MD5E-s …
```
=> download-url: Fix archive path handling when in subdirectory

datalad/auto.py
Ran into while trying to do `python -m datalad `which heudiconv` ...` . For some reason it was querying `/.git/` and `get` would return `[]` and then kaboom.  May be will craft a test for it later
=> BF: auto - if empty list is returned by get, do not try to treat it as dict record

datalad/core/local/tests/test_diff.py, datalad/support/gitrepo.py
```
save_() calls 'ls-files -o' on a list of untracked directories to
determine which directories correspond to untracked submodules.  If
the directories remain unexpanded in the 'ls-files -o' output, they
are taken as submodules.
This method of identifying untracked submodules breaks [0,1] with the
latest release of Git (v2.24.0) due to an unintentional change in the
'ls-files -o' output [2]: when given _multiple_ pathspecs, 'ls-files
-o' recurses into untracked submodules and lists the files from the
submodule (even the tracked ones).  save_() filters the output to
directories, so most of the additional entries are removed, but when
the submodule itself has submodules (untracked or tracked) these and
those from any deeper levels are included in the output.  save_()
passes these deeper …
```
=> BF: gitrepo: Work around change in 'ls-files -o' output

datalad/interface/utils.py
Otherwise we might not be able to act on error results (depending on 'on-failure' setting), and also will not get them to a result renderer.
This is a surprisingly old problem.
=> BF: Perform result rendering prior error handling

datalad/distribution/get.py
The underlying issue was discovered in https://github.com/datalad/datalad/pull/3903
=> BF: Make sure to not issue an install-ok result, before the repo state is final

datalad/distribution/tests/test_clone.py, datalad/distribution/tests/test_siblings.py, datalad/distribution/utils.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
This series fixes gh-3816 (cloning of annex repos with special remotes that were set up with `--sameas`).
Some notes:
* When merging to master, there will be a merge conflict because `_handle_possible_annex_dataset` was moved to clone.py in 8f9ae55fb (RF: Move clone-internal helper to clone.py, 2019-10-14).
* This handles the clone case, but other places in DataLad (in particular `publish`) may need an update for git-annex's sameas functionality.
* If the user is running a git-annex version that doesn't support sameas special remotes, we're informing them about a remote that they can't actually enable.  If others feel this is worth handling, I can rework the code to check the annex version.
=> Adjust special remote handling for sameas remotes

datalad/downloaders/base.py, datalad/downloaders/tests/test_http.py, datalad/interface/download_url.py, datalad/interface/tests/test_download_url.py
This implements the [trailing slash solution][0] to gh-3848.  It sits on top of the unmerged gh-3850.  I'm marking it as a draft because more extensive testing should be added to test_download_url.py.
[0]: https://github.com/datalad/datalad/issues/3848#issuecomment-548436256
=> ENH: download_url: Use trailing separator to signal directory target

datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py
However, instead of reverting to the behavior prior 0.12rc6 (blind duplicate reporting of dataset results for subdataset install and annex-get of its root directory, this patch compromises and actually inspects if there already was a report on a dataset, and only silences follow-up duplicate reports. This impacts the result composition of large-ish operations (recursive install of a dataset with data), but AFAICS it should have now actual impact on logic and actionability of the results.
This fixes gh-3836
Alternative to https://github.com/datalad/datalad/pull/3841 @bpoldrack
=> BF: Reintroduce 'notneeded' results for existing datasets in get()

datalad/config.py, datalad/interface/tests/test_run_procedure.py, datalad/interface/utils.py, datalad/support/gitrepo.py, datalad/tests/test_config.py
The issue was raised in https://github.com/datalad/datalad/pull/3903#issuecomment-562979754 but is in fact a long-standing issue in DataLad. Hence this comes as a separate PR, and https://github.com/datalad/datalad/pull/3903 will need to be adjusted, once this is merged.
We may want to have an override that re-enables this feature -- but I think we should wait if an actual use case materializes. Otherwise not supporting it seems like the better way.
=> ConfigManager can be limited to local config; prevent remote changes of hooks

datalad/config.py, datalad/core/local/resulthooks.py, datalad/core/local/tests/test_resulthooks.py, datalad/interface/utils.py
This is aims to be a more flexible alternative to --proc-pre/post and its proposed successor of command hooks (#3264).
The key idea is that we have DataLad's results that all pass through the main event loop, and we can define ad-hoc hooks that run custom actions whenever a matching result is observed.
Key differences to what we already have:
- can act more than once per command execution
- no "pre" action anymore
- informed by the actual result itself
- runs dataset procedures, but also any proper datalad command
To define a hook, two config variables need to be set:
- `datalad.result-hook.<name>.match`
- `datalad.result-hook.<name>.proc`
where `<name>` is any Git config compatible identifier.
`match` contains a JSON-encoded dict that is used to match a result against in order to test …
=> NF: Result hooks

datalad/interface/download_url.py
This is the least-cost path that made it work for me. Here is the compact use case:
```
datalad remove -d bf2849 --nocheck ; datalad create bf2849; datalad -C bf2849 download-url https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css
```
The dataset deletion is critical for the demo, as otherwise git-annex seems to use prior knowledge about the key and doesn't fail on second attempt, even with a `git reset --hard HEAD~1`.
Fixes gh-2849
=> Fix download-url breakage reported in #2849

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py, docs/source/basics.rst
It is often desired to reference current dataset. E.g. to add an existing
dataset as subdataset to the current dataset somewhere not at the top of the
dataset directories tree. Especially in quite nested hierarchies it
becomes a burden to figure out where is the boundary of the dataset to specify
it in -d option.  -d .  would point to the (not installed, and possibly illegit
see #3211) subdataset in current directory, whenever actual need is to specify
smth like -d ../../..  .
With -d^. it becomes possible to say "refer to the current dataset I am in".
The only gotcha I am aware of is that shell might like to use "^" as
a quick substitution for previous command, that is why I specified it
as -d^., i.e. without space - then seems to work as intended -- running
"datalad add -d^. ./subds" …
=> ENH: -d^. to point to the top of the current dataset

.zenodo.json
=> ENH: zenodo - unified affiliations and keywords (to handbook), added new NSF grant

datalad/plugin/tests/test_plugins.py, datalad/plugin/wtf.py
This fix conflicts with a prior test condition (now flipped). Please check.
I consider a defined top-level (non-alphanum) sorting a needless complication.
=> BF: Sort keys in wtf() result renderer (fixes gh-3915)

datalad/utils.py
Apparently .level is not even a property and I guess starting from
3.7 treatment has changed, or broke.  May be smth like (scheduled for 3.9
with backport requests for 3.8) https://github.com/python/cpython/pull/16325
was intended to fix it, I did not investigate deep enough -- just fixed
the issue we started to experience (Closes #3545)
After merged into 0.11.x, will send PR against master
=> BF: lgr - use .setLevel() instead of .level =

datalad/interface/results.py
Such information is now extracted from the annex report, and used
preferentially as 'message' when competing with a simultaneously
present 'note'. While this may hide some information, the omitted
parts are arguably less important and obfuscate any error. Without
this omission, a 'disk full' error may look like:
```
get(error): sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_bold.nii.gz (file) [  not enough free space, need 31.04 MB more (use --force to override this check or adjust annex.diskreserve); Unable to access these remotes: mddatasrc; Try making some of these repositories available:;     2f51364e-815a-4ad9-b380-617c682b1680 -- [mddatasrc];    40809380-c618-4801-bb8d-81320474c9da -- studyforrest phase2 original source repository]
```
Also: …
=> BF: annexjson2result() did not report 'error-messages' (fixes gh-3870)

debian/control
Given the draft stage of the prev. PR lots of conflicts accumulated. It would be good to have this change merged. It makes the control file compatible with `cme` and minimizes the diff to its output.
- python-six no longer has versioned dep (was only relevant for jessie)
- standard order
- whitespace standardization
=> Debian packaging update

datalad/consts.py, datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_save.py, datalad/distribution/install.py, datalad/interface/tests/test_ls_webui.py, datalad/interface/tests/test_rerun.py, datalad/metadata/tests/test_aggregation.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
This brings us closer to gh-1424
=> ENH: Record the active branch of a subdataset in the parent

datalad/distribution/tests/test_clone.py
Started to hang, someone needs to troubleshoot.
Sample job
https://ci.appveyor.com/project/mih/datalad/builds/29552658
So that travis does not bother:
[ci skip]
=> BF(workaround): mark test_clone.test_autoenabled_remote_msg as known to fail

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
The first patch adds a basic test for `siblings(..., inherit=True)`.  The second prevents `siblings(..., inherit=True)` from crashing when the parent dataset doesn't include a remote of the same name (reported by @dorianps in gh-3950).
=> siblings: Check for remote before inheriting annex settings

datalad/distribution/get.py, datalad/distribution/tests/test_dataset.py, datalad/local/subdatasets.py
or if there is no dataset to query. But retain the previous behavior when called as a bound method of a Dataset instance. The compromise is made to avoid gh-3938 while retaining internal assumptions about the behavior of the command.
Fixes gh-3938
=> BF: Complain if a nonexistent dataset is given to subdatasets()

datalad/interface/run_procedure.py
Before it would report relpaths if operating on a dataset, leading to
the issue at hand.
I considered relpaths for dataset internal procedures, and abspaths for
others. However, when not invoked at the root of a dataset these would
again be somewhat confusing. So full abspath it is.
Fixes gh-3619
=> BF: Always report absolute location of discovered procedures

datalad/interface/run_procedure.py, datalad/interface/tests/test_run_procedure.py
[Sits on top of https://github.com/datalad/datalad/pull/3959 to avoid conflicts]
Before, only "absent" (but configured) procedures were marked up in the 'state' field of their result record. Now this is extended with two more states:
- 'executable': all criteria for an active procedure are fulfilled
- 'overridden': like 'executable', but there is a higher-priority procedure with the same name
These additional states are also reflected in the renderer, where only active/executable procedures are renderer as before, and any other's are de-emphasized and annotated.
Fixes gh-3614
Example output before
% dl run-procedure --discover
**cfg_inm7** (/etc/xdg/datalad/procedures/cfg_inm7.py) [python_script]
**cfg_inm7** (/home/mih/hacking/datalad/inm7-datalad/inm7_datalad/resources/procedures/cfg_inm …
=> BF: Provide indication which procedure is (to be) execut(ed/able)

datalad/metadata/search.py
This fixes the following bug (too minor to open a github issue?)
$ cd ~/datalad/openneuro
$ datalad search -f json --show-keys short
...
bids.CogAtlasID
in  17 datasets
has 15 unique values: u' ', u'trm_4c8a84f20dde2', u'http://www.cognitiveatlas.org/task/id/trm_4c8a83 ....
[ERROR  ] 'ascii' codec can't encode character u'\u200b' in position 15: ordinal not in range(128) [search.py:show_keys:804] (UnicodeEncodeError)
=> Patched unicode issue for python2

datalad/cmdline/main.py, datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_resulthooks.py, datalad/interface/base.py, datalad/interface/common_opts.py, datalad/interface/run_procedure.py, datalad/interface/tests/test_base.py, datalad/interface/tests/test_run_procedure.py, datalad/interface/utils.py, datalad/utils.py
This became a little more elaborate than desired, but I think it is useful nevertheless.
=> Refurbish eval_func()

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
=> BF: Store path URLs for remotes in POSIX (fixes gh-3972)

appveyor.yml, datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_clone.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py, datalad/distribution/tests/test_uninstall.py, datalad/distribution/tests/test_update.py, datalad/interface/tests/test_unlock.py, datalad/local/tests/test_subdataset.py, datalad/support/network.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_network.py, datalad/tests/test_auto.py, datalad/tests/test_testrepos.py, datalad/tests/test_utils_testrepos.py, datalad/tests/utils.py, datalad/tests/utils_testrepos.py
...as much as feels feasible right now. In any case, this is a huge step forward in terms of critical test coverage on windows. We are now in the position to investigate individual tests, instead of facing global failure.
There is still an open issue with `get_local_file_ur l()` https://github.com/datalad/datalad/issues/3977, but given that this is needed for #3966 it will have to come in a separate PR.
=> Enabled testrepo-based tests on Windows

datalad/support/tests/test_annexrepo.py
```
As of git-annex 7.20191024, test_AnnexRepo_dirty has started to
intermittently fail [0] due to the repository being in an unexpectedly
dirty state, with content that was previously tracked by git converted
to annexed content.  The failure happens due to the combination of two
things:
1) Calling `git -c annex.largefiles=anything annex add -- FILES` can
in some cases result in git running git-annex's clean filter on
files that are _not_ part of FILES.  Importantly the clean filter
runs within the `-c annex.largefiles=anything` context.
2) As of 7.20191024, git-annex's clean filter remembers the inode for
annexed content, leading git-annex to conclude that the regular
git file in the working tree (file1.txt in this test) should be
annexed, because the content was tagged as such in 1.
See …
```
=> TST: annexrepo: Ignore racy "is clean?" failure

datalad/distribution/clone.py, datalad/support/gitrepo.py, datalad/support/network.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_network.py, datalad/tests/utils_testrepos.py
The new 'compatibility' argument of get_local_file_url() is relatively
painless and the workaround implementation can be removed (and the
argument rendered into a no-op) if there should be a compatibility
fix at the git-annex end.
Fixes gh-3639
=> BF: Implement workaround for file:// URL compatibility on Windows

datalad/distribution/tests/test_create_sibling.py
This addresses one of the failures from gh-3890.
---
```
A check in test_target_ssh_simple assumes that executing the
post-update hook will change the modification times of .git/info/refs
and .git/objects/info/packs.  In test runs with more recent Git
versions, this check has started to fail because the modification
times of the files are not updated [0].  This change in behavior is
likely due to Git's f4f476b6a1 (update-server-info: avoid needless
overwrites, 2019-05-13), which was part of the v2.23.0 release.
We could condition the check on the Git version, but, as the now
failing check demonstrates, this check is much too concerned with
internal implementation details of git.  To avoid the test starting to
fail due to another change within .git/ that we do not control, let's
instead …
```
=> TST: create-sibling: Loosen check's assumption about Git's behavior

datalad/config.py, datalad/tests/test_config.py
This brings the same (and actually more) configuration override
flexibility to the Python API that the cmdline API offers via
`datalad -c key=val`.
This feature is a necessity for being able to rely on one-off
configuration (changes) to alter command behavior, whenever
a dedicated command option is not absolutely needed or shall be
avoided.
A dedicated test for overrides is also included.
Fixes gh-3970
=> NF: ConfigManager.???(where='override')

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py
See https://github.com/datalad/datalad/issues/3973 .   I am not really sure why it was
intended to be an AttributeError, but I feel that ValueError is a better fit here.
lgr.debug message might be of help in some cases to identify the reason which lead
to crash, but because args and kwargs are modified by the code above, not sure really
if it would be very informative.  but I do not think that it would somehow negatively
effect the performance so I added it
Looking at the code I see that we have duplicated functionality across `_flyweight_id_from_args` implementations.  I will look into unifying it in a separate PR (on top)
=> RF: Attribute -> Value Error + provide an informative message for the exception

datalad/distribution/create.py, datalad/distribution/tests/test_add.py, datalad/distribution/tests/test_create.py, datalad/interface/tests/test_run_procedure.py, datalad/resources/procedures/cfg_text2git.py, datalad/support/annexrepo.py
Also extends the test to test some structured text files to guarantee that there would be no change in behavior (from git-annex or libmagic changes).
I was a bit not sure if it is worth introducing in 0.11.x since it would demand minimal git annex boost.  But since I use ATM both versions interchangeably and older annex would not support (crash) mimeencoding - I have decided that it is worth adding it to 0.11.x first.
I also was not sure if we shouldn't detect "old" line in `.gitattributes` and warn the user and may be even suggest (in interactive sessions) to adjust that gory statement.  But if we do so, we would need to mark somewhere to not pester user about it again in that dataset if they say "nah"... so - pain. I guess we are just doomed to look forward.
Closes #3361
=> BF: use mimeencoding not mimetype for text2git

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py, datalad/support/gitrepo.py, datalad/support/repo.py
We had to almost identical copies of the code for `_flyweight_id_from_args`.
That can breed bugs having fixes in one copy but not another.  I have decided
to go superclass subclassing path so we could also "modularize" the logic for
handling aliases (ATM only for the datasets).
I have taken implementation from  Dataset, which did not explicitly
"realpath" the path.  Not sure yet if such difference in behavior (Dataset vs *Repo)
was intended/desired, tests might show
- Sits on top of #3986 
- TODO: For the merge in master, conflict resolution should add handling of yet another piece of seems duplicate path handling/conversion:
```diff
+        # mirror what is happening in __init__
+        if isinstance(path, ut.PurePath):
+            path = str(path)
```
=> RF: bring common (?) functionality under PathBasedFlyweight

docs/source/conf.py
I noticed that the copyright notice on [docs.datalad.org](http://docs.datalad.org/en/latest/index.html) says 2016-2019. This change automatically adds the current year.
While I did this, I noticed an unused import (shlex), and removed it as well.
=> DOC: Automatically add current year to copyright notice

datalad/distribution/tests/test_uninstall.py, datalad/distribution/uninstall.py
It is sufficient to pass a dataset arg as-in to achieve that.
=> BF: Maintain path arg semantics when passing from update-> subdatasets

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
`refds_path` could be empty if dataset is not specified but path (to subdataset) is provided
Note that it would change existing behavior -- apparently we could have been saving some prior changes if there were some before running `update`.  I would consider that also to be a bug fix
Fixes #3097 
ref: https://github.com/templateflow/templateflow/issues/5
TODOs (after merge)
- merge/adjust for `master` way of things
=> BF: update -- do not save if no --merge, use save instead of Dataset(refds_path).add

datalad/interface/base.py
Closes #3203 
Or there could be a flag without `action="store_..."`, or some `store_` wouldn't be a flag?
I  found no other conveniently available unittesting setup to test this change.  Any pointers or assistance would be appreciated
=> BF: do not add [Default: ...] for --help if it is a flag (action="store_...")

datalad/core/distributed/tests/test_clone.py, datalad/support/gitrepo.py
When git clone is called with a local relative path as the URL, it
will prepend the current working directory to the URL to get an
absolute path.  "../" components are retained.  In common DataLad
scenarios (see gh-3538), installing a subdataset using a local path
source can lead to .git/config URLs such as
url = /tmp/super/../source
A downside of these absolute paths is that they become invalid for
URLs that point within a dataset hierarchy (e.g., "../../source") if
the hierarchy is moved to a different location.  With relative URLs,
the URLs would remain valid as long the relative relationships are
retained.  (On the other hand, absolute paths provide a better
stability when moving datasets if the URLs point outside of the
hierarchy.)
Two recent commits from gh-3966, 02e2b4c46 (BF: …
=> BF: clone: Revert incorrect relative path adjustment to URLs

.github/PULL_REQUEST_TEMPLATE.md
The instructions for choosing a PR base are stale.  The 0.12.* series
has been released, and we do not plan to continue to extend the 0.11.*
series.  At this point, there's not a maintenance branch for 0.12.*,
so drop the item entirely rather than updating it.
=> MNT: Drop "Choose a base" item from PR template checklist

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/distribution/utils.py
- `datalad create test`
- `datalad -d test create-sibling-ria storedataladorg`
Result now sitting at `http://store.datalad.org/76b/6ca66-36b1-11ea-a2e6-f0d5bf7b5561`
- for now I had to manually run `git update-server-info` on the server, would a smart http setup on the server help @yarikoptic ?
- only works with additional client-side configuration (see below), because the actual location on the server cannot be inferred from the identifier. This is not a problem, because only people with write access will need to have this, and they already need that for `ria-remote`.
=> Towards supporting access to RIA stores in clone()

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
As of 367454e0b (NF: Auto-configure local origin of local origin to
make annex available, 2019-12-29), we check whether origin's URL for a
newly cloned annex dataset points to a local dataset.  If it does, we
add _that_ dataset's origin (if any) to the newly cloned dataset.  And
as of d2a25d090 (ENH: Make configuration of local origin siblings work
recursively, 2020-01-05), we continue walking up the chain of local
origin's until we hit an origin that is not a local path.
However, we create the corresponding dataset instance with the wrong
path when origin is a _relative_ path: it should be relative to the
cloned repository, not the current working directory.  The incorrect
path means that there's no "origin of origin" to find, and an
"origin-N" remote isn't added.
Note that this bug …
=> BF: clone: Account for relative paths when inheriting local origins

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/support/gitrepo.py
`GitRepo.clone()` is enhanced to accept arbitrary additional options
that are passed on to `git-clone`. We use the `--branch` option
(that, despite its name, can handle any relevant version identifier)
to let `git-clone` do all the work.
`datalad-clone` is now set up to acknowledge a request for a particular
version, for any kind of source URL where `decode_source_spec()`
yields a non-None `version` property.
At the moment this is only the case for `ria+http|ssh://` URL, but
future additions only need to alter/enhance `decode_source_spec()`
to extend this functionality for other types.
This change also sets the stage for gh-4035
The user experience of this new feature is negatively impacted by #4038.
=> NF: Support cloning of specific repository versions (fixes gh-2109)

datalad/support/archive_utils_patool.py, datalad/support/archives.py, datalad/tests/test_archives.py
This shall make providing an alternative but API compatible
implementation easier to place and test alongside of this existing
one.
Towards #4019
=> RF: Move all patool code into a dedicated code file

datalad/core/local/run.py, datalad/core/local/tests/test_run.py, datalad/interface/run_procedure.py, datalad/interface/tests/test_run_procedure.py, datalad/interface/utils.py, datalad/support/sshconnector.py, datalad/utils.py
This enables more appropriate command-line argument quoting on
windows, and will retain the previous behavior on any other platform.
This could potentially improve SSH support on Windows substantially,
because shlex.quote() was often inappropriately and unconditionally
used in associated code.
=> Replace shlex.quote() with quote_cmdlinearg()

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/interface/common_opts.py
If `--reckless` is given, the label is stored verbatim under config
variable `datalad.clone.reckless`. `clone()` consults this variable
whenever `--reckless` is None.
As a consequence of this change, subdatasets will inherit any reckless
mode.
Obviously, this also makes it possible to provide global configuration
to force a particular reckless mode for any cloned dataset.
=> NF: Clone of subdatasets uses reckless mode of superdataset (fixes gh-4030)

datalad/cmd.py, datalad/interface/add_archive_content.py, datalad/interface/run_procedure.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/sshrun.py, datalad/tests/test_cmd.py, datalad/utils.py
shlex.split() is kept for any non-Windows platform, as custom
implementation for Windows was added. All use of shlex.split()
was replaced by the new helper.
Fixes gh-4049
=> NF: split_cmdline() platform-appropriate shlex.split()

datalad/core/distributed/clone.py
1a2e9e4ca (2020-01-17) added a condition that effectively results in
two consecutive "if reckless" conditions.  Drop the inner one.
=> CLN: clone: Drop repeated condition

datalad/core/local/tests/test_diff.py, datalad/support/gitrepo.py
ca234631a (BF: gitrepo: Work around change in 'ls-files -o' output,
2019-12-06) and a4a6e2955 (TST: diff: Skip an assertion that fails
with Git v2.24.0, 2019-12-07) worked around a `git ls-files -o` bug.
The upstream fix is part of the Git v2.25.0 release.
=> MNT: Set upper bound on `ls-files -o` workarounds

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
When GitPython raises a GitCommandError, whether the exception's
stderr attribute actually contains the standard error depends on
whether progress reporting is enabled.  With progress enabled, the
standard error is stored in RemoteProgress.error_lines instead of the
exception [0].
As of 3ecc68a82 (2018-09-27), we assign RemoteProgress.error_lines to
our GitPythonProgressBar._last_error_lines.  In the case of clone(),
we consider _last_error_lines to some extent, but it's not included in
the errors messages that we show the clone call fails with all
candidates.  In the specific cases of an unknown version, this means
that we report that cloning failed without any indication that the
unknown version was the issue.
Make the standard error visible to the caller by replacing the
exception's …
=> clone: Store stderr so it is displayed on clone failure

.github/workflows/docbuild.yml, .travis.yml, appveyor.yml, datalad/interface/download_url.py, datalad/interface/tests/test_download_url.py, datalad/support/archive_utils_7z.py, datalad/support/archives.py, datalad/support/external_versions.py, datalad/tests/test_archives.py
Sitting on top of #4039 
This is a complete draft implementation of a 7z-based file compression/decompression that should be as capable as the patool-based one.
TODO
Further related TODOs (for subsequent PRs) surfaced by this PR:
- #4048 -> #4050
- add `p7zip` as dependency/recommends to Debian package
=> 7z-based (optional) replacement for patool

datalad/support/archive_utils_7z.py, datalad/support/external_versions.py
* Fix use of undefined variable from 7fb806abd.
* Simplify newly added `_get_system_7z_version`, as well as the nearby `_get_system_ssh_version`.
* Fix message for `external_versions.check` call from d674922b8.
=> A few touch-ups for the recent 7z additions

datalad/config.py, datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/tests/test_config.py
With this helper (and its use in the relevant places), we can make
DataLad acknowledge URL rewrite instructions by supporting Git's own
mechanism: `url.<base>.insteadof`
With this move we should be able to avoid custom configuration for
the purpose of mapping locations (like needed for the RIA support
code). The included test contains the desired mappings.
As suggested by @kyleam this should set us up better for eventually
supporting custom protocols like `ria+ssh://` in a proper Git remote
helper.
=> NF: Helper to support Git-style URL rewriting

datalad/config.py, datalad/distribution/tests/test_create_github.py, datalad/support/gitrepo.py, datalad/tests/test_config.py
This series is adapted from gh-4072 and prompted by [this discussion][0].  It replaces the core fix of that series with an approach that doesn't rely on explicitly passing `--global` and `--system` to `git config`.  The main commit of interest is the final one.  Here's the range-diff between gh-4072 and this PR:
```
1:  19e7a83cf = 1:  19e7a83cf TST: Demo some flavor of gh-4071
2:  58f13ad7a = 2:  58f13ad7a BF: Make git-config dump parser aware of CWD
3:  1895b0558 = 3:  1895b0558 TST: Adjust test to show config leak
4:  2332d5e30 ! 4:  6d9c2ae59 ENH: ConfigManager(source='dataset-local')
@@ Commit message
Be able to ignore global and system configuration.
+    Modified-by: Kyle Meyer <kyle@kyleam.com>
+      Absorb the "dataset is None and 'dataset-local'" guard from
+      gh-4072's …
```
=> Fix unintentional reading/writing of repo configuration (approach 2)

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/get.py, datalad/distribution/tests/test_get.py
[ this is sitting on top of #4072 and hence inherits its issues]
This makes it possible to have large collections of datasets put in
some dataset store, without any of them carrying knowledge about their
hosting location, even if they have super-sub-dataset relationships
among themselves. The only requirement to make any of these datasets
accessible, is a single top-level superdataset with a source candidate
configuration that is point to the store. Everything else will be
handle with on-clone configuration in `.git/config` of each subdataset.
=> BF: Make sure source candidate configs for submodules are inherited

datalad/core/distributed/tests/test_clone.py
Otherwise `assert_status()`runs on a dataset instance.
Unclear why this hasn't been spotted by the tests before...
=> BF: Adjust test for clone default return value setup

datalad/cmdline/helpers.py
Our help text has lots of spots where the first word in a line is
incorrectly capitalized when the line ends with a colon.  The code
that does this has a comment that says this is to capitalize the first
word of all "headings", but it's not clear what those headings are.
Without this code, the help output of all of our current commands only
differs in cases of incorrect capitalization, so it looks like this
code is no longer serving its original purpose while causing issues
elsewhere.  Drop it.
Re: https://github.com/datalad/datalad/pull/4091#discussion_r371312477
---
Here is the difference in help output before and after this command:
<details>
<summary>diff</summary>
```python
from itertools import chain
import subprocess as sp
import sys
import datalad.interface.base as di …
```
=> BF: cmdline: Don't capitalize first word of lines ending with ":"

datalad/core/local/create.py, datalad/core/local/diff.py, datalad/core/local/status.py
- DOC: diff: Touch up grammar/typos in --help text
- DOC: Prefer "working tree" to "worktree" in --help text
=> A few command documentation touch-ups

datalad/core/local/create.py, datalad/core/local/diff.py, datalad/core/local/run.py, datalad/core/local/save.py, datalad/core/local/status.py, datalad/distribution/drop.py, datalad/distribution/get.py, datalad/distribution/remove.py, datalad/distribution/uninstall.py, datalad/distribution/update.py, datalad/interface/base.py, datalad/interface/download_url.py, datalad/interface/rerun.py, datalad/interface/run_procedure.py, datalad/interface/unlock.py
- I've added a few examples to `update`, `uninstall`, `remove`, `download-url`, `diff`, and `run-procedure`. 
- For `drop`, I removed duplicate examples that were still present in the docstring. 
- For `rerun`, I transferred examples from the docstring into the `_examples_` list and added Python translations when possible. 
I deemed one of the examples of `rerun` as not very suitable for the Python API help:
```
Re-execute all previous commands and compare the old and new results:
% # on master branch
% datalad rerun --branch=verify --since=
% # now on verify branch
% datalad diff --revision=master..
% git log --oneline --left-right --cherry-pick master...
```
Therefore, I modified `build_example` to only include an example in the help text of an API if a code snippet exists for this API, …
=> DOC: examples for more commands

datalad/config.py, datalad/core/local/create.py, datalad/distribution/dataset.py
surprisingly, benchmarking locally it only shows that things got slower:
```
(git)lena:~datalad/datalad-master[opt-smart]git
$> asv compare -m hopa master HEAD | grep -v failed
All benchmarks:
before           after         ratio
[c741a5b1]       [9db20858]
<master>         <opt-smart>
1.20±0.2s        1.35±0.1s    ~1.12  api.supers.time_createadd [hopa/virtualenv-py3.7]
1.49±0.2s        1.67±0.1s    ~1.12  api.supers.time_createadd_to_dataset [hopa/virtualenv-py3.7]
4.66±0.04s       5.59±0.01s    ~1.20  api.supers.time_installr [hopa/virtualenv-py3.7]
118±2ms         126±10ms     1.06  api.supers.time_ls [hopa/virtualenv-py3.7]
1.51±0.2s        1.69±0.4s    ~1.12  api.supers.time_ls_recursive [hopa/virtualenv-py3.7]
1.84±0.2s        1.99±0.2s     1.08 …
```
=> OPT: tried to be "clever" AKA "smart" and reuse .repo (and .config)

datalad/core/distributed/clone.py, datalad/core/local/create.py, datalad/core/local/run.py, datalad/core/local/save.py, datalad/core/local/status.py, datalad/distribution/install.py, datalad/interface/base.py, datalad/interface/download_url.py
This series follows up on the recent improvements that Adina brought in with gh-4091.  Patches 1-5 are more or less clear-cut fixes.  Patches 6-9 are more subjective, and I'd be fine with dropping any of those if there are objections.
[1/9] DOC: interface: Don't write empty example section to docstrings
[2/9] DOC: run: Don't use string for inputs/outputs in Python examples
[3/9] DOC: download-url: Drop repeated example
[4/9] DOC: install: Drop stray quote from example
[5/9] DOC: interface: Use same indentation for pre-crafted examples
[6/9] DOC: examples: Format multi-line command-line snippets consistently
[7/9] DOC: examples: Break more snippets across multiple lines
[8/9] DOC: examples: Consistently use unbound Python commands
[9/9] DOC: examples: Resolve some command-line/python …
=> Fixes and tweaks to command example handling

datalad/core/local/status.py
Follow up on a report by @dorianps considering no output confusing. `status`
now follows `git status` in wording.
Fixes gh-3916
```
(datalad3-dev) mih@meiner ~/hacking/datalad/git (git)-[bf-3916] % datalad status
nothing to save, working tree clean
```
=> BF: Don't be silent in default renderer when everything is clean

datalad/core/distributed/clone.py, datalad/interface/base.py, docs/Makefile, docs/source/conf.py
Demo link is included. All rendered references are version to match the
current "major" release.
Looks like this: `--help` output and `help(clone)` in Python
```
handbook:3-001 (http://handbook.datalad.org/symbols)
More information on Remote Indexed Archive (RIA) stores
```
The given URL points to a dedicated index section in the handbook, where
we can maintain any number of references that point to arbitrary
locations. The name 'symbols' is used, because this is how sphinx lists
numeric references. The ?-???? scheme aims to mimic manpage sections
(where we can come up with some categorization, if needed, and
incremental integer IDs).
- 1: commands
- 2: concepts
- 3: use cases
Ping @adswa for awareness (I have pushed a corresponding change to the
handbook; directly, no PR).
=> NF: Intersphinx mapping to link to handbook content (fixes gh-4034)

appveyor.yml, datalad/cmd.py, datalad/core/distributed/clone.py, datalad/log.py, datalad/support/exceptions.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_witless_runner.py
=> WitlessRunner() to replace gitpy.Repo.clone_from() with plain `git-clone` call, but keep progress reporting

datalad/cmd.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
- rename to `run_gitcommand_on_file_list_chunks`
- move to `cmd.py` next to the runners it can work with
- avoid intermediate str concatenation
- add debug message
- more detailed docstring
=> RF: Turn GitRepo non-method into standalone function

datalad/cmd.py, datalad/support/gitrepo.py, datalad/tests/test_witless_runner.py
Previous implementation had deadlock issues that I could not resolve.
This code is inspired by the highly informative
https://pymotw.com/3/asyncio/subprocesses.html
Reimplementations for the previous output processors are provided too.
They are now using "protocols" that are natively provided by asyncio,
and offer a conceptually similar, but extremely superior and more
flexible approach to the problem.
A no longer relevant test case was removed.
TODO:
=> RF: WitlessRunner reimplemented with asyncio 

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Suck in implementation from git-annex-ria-remote.
Former implementation couldn't correctly deal with chunks for example.
See https://git-annex.branchable.com/internals/key_format/ for specification.
=> BF/ENH: get_size_from_key to match specification

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/interface/common_opts.py, datalad/tests/utils.py, datalad/utils.py
Introduce reckless mode 'ephemeral' for throw-away clones, symlinking their .git/annex to origin's .git/annex.
In addition declare 'here' dead to not propagate availability info from it when publishing captured changes back.
=> NF: clone: --reckless='ephemeral'

datalad/plugin/export_to_figshare.py, datalad/plugin/tests/test_export_to_figshare.py
Decided not to expose title specification in API since the whole experience is interactive, but I guess it could be added.
Closes #4138
=> BF: export-to-figshare - make default title include #id@version, ask for the title in UI

datalad/core/distributed/clone.py, datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Sit on top of #4080 to show that implementation can generalize, but is kept as a separate PR, because discussions might be needed.
Logic stays largely the same. Differences are:
- no longer returns "fetch_info" structures, which are internal to
GitPython -- unclear of a replacement is actually needed. Will be done
once it becomes necessary.
- additional progressbar wrapping the fetch of multiple remotes
- kwargs are ignored for the moment. Needs discussion on which ones are
needed, or if all should be attempted
TODO
=> GitRepo.fetch/pull/push() without GitPython

datalad/distributed/create_sibling_gitlab.py, datalad/distribution/create_sibling_github.py
...but useful. This addresses some users' assumption that any such
linkage needs to be established through these commands, even if
there already is a corresponding project available.
Fixes gh-4120
=> DOC: Make explicit that create-sibling-git(hub|lab) are optional

datalad/distribution/update.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Based on discussion in gh-4148, I'm in the process of reworking the second half of the series in gh-4118.  The first half of that series consisted of miscellaneous fixes and clean-ups.  This PR splits those off, with an additional trivial clean-up on top.  Given that I think these are uncontroversial and that they were already proposed as part of gh-4118, I'll to merge this once the tests pass.
Here's the range-diff with gh-4118.
```
1:  3485886ddb =  1:  12b1045125 ENH: repo: Teach get_tracking_branch() to optionally ignore "."
2:  6ee5b663a3 =  2:  a231fbcce6 BF: update: Don't consider "." as an upstream remote
3:  422b904806 =  3:  4a5cc193de BF: update: Query intended branch.*.remote variable
4:  996cddb958 =  4:  351f65d24e RF: update: Cosmetic changes to _update_repo() helper
5: …
```
=> update: Minor fixes and clean-ups extracted from gh-4118

datalad/tests/utils.py
When working with `assert_in_results` failures, I noticed that I often end up pasting them somewhere and reformatting them because I have a hard time digesting long lines like
```
AssertionError: Found no desired result ({'action': 'get', 'status': 'ok'}) among [{'action': 'get', 'path': '/tmp/datalad_temp_test_reobtain_datawmb8reri/load.dat', 'type': 'file', 'refds': '/tmp/datalad_temp_test_reobtain_datawmb8reri', 'status': 'notneeded', 'message': 'already present'}, {'action': 'update', 'path': '/tmp/datalad_temp_test_reobtain_datawmb8reri', 'type': 'dataset', 'refds': '/tmp/datalad_temp_test_reobtain_datawmb8reri', 'status': 'ok'}]
```
`assert_result_count`, on the other hand, formats the records with `json.dumps`, which I find much more helpful.
This series applies the same approach …
=> tests: Improve display of results in assertion messages

datalad/core/local/create.py, datalad/tests/test_config.py
Bare-mode repositories frequently come up as a problem/use case:
- #4035
- #3855
- #2820
- #2819
- #2425
TODO:
=> Bits to make bare repositories a more recognized use case

.travis.yml, datalad/core/distributed/clone.py, datalad/distributed/create_sibling_ria.py, datalad/distributed/ria_utils.py, datalad/distributed/tests/test_create_sibling_ria.py, datalad/distribution/publish.py, datalad/interface/__init__.py, docs/source/cmdline.rst
This is the code that was used to push the HCP datasets to store.datalad.org -- written by @bpoldrack (see https://github.com/datalad/git-annex-ria-remote/pull/38). It is one of the last pieces of RIA functionality to move into -core (the actual special remote implementation being the very last one). It is being proposed as a separate PR, because it can function without it (HCP doesn't use the ria-special remote), and to keep the complexity of the PR more manageable.
Feedback is very much welcome! Thanks!
Related:
- #4068 consolidation on common operations with `create_sibling`
- UX issues:
- https://github.com/datalad/git-annex-ria-remote/issues/44
- https://github.com/datalad/git-annex-ria-remote/issues/45
Update by @bpoldrack :
From my point of view, this is ready. Above mentioned UX …
=> NF: create-sibling-ria command

datalad/__init__.py, datalad/tests/test_config.py
We change /home/ben from within setup_package, therefore we
need to consider the correct global git config file. This
used to be wrong, since datalad.cfg is instantiated on import
hence before setup_package is executed.
(Closes #4153)
=> BF: Reload datalad.cfg for test environment

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Previous (positive) API and behavior are maintained, except for the lack
of 'protocol' support which is only available in the traditional runner.
In addition, when multiple calls to git-commit need to be made, --amend
is now used from the second call onward to avoid leaving multiple
commits behind for technical reasons, when conceptually there is only
as single changeset. Fixes gh-3914
This is a trimmed down changeset from a previous attempt to enable
interactive commit messages. Compare to
aa86a8d0df2af95399418f771f592aedbb848df1 to recover the discarded diff.
Replaces #4121 for the time being...
=> RF: GitRepo.commit() based on WitlessRunner

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py
A safe guard to Close #4145 
If remote directory contains some files/directories, we would ask user whenever session is interactive or just raise an exception if not interactive
edit 1: I have been thinking about it and I maintain the opinion that `--existing=replace` is already an explicit indication from the user of the intent to replace (remove, recreate) a possibly existing remote dataset.  Adding the interactive question or raising an exception (if not interactive) goes against the explicitly expressed desire to "replace".  So, what if we do that (question or exception) only if remote location does not already have `.git` and `.datalad/config`?  This way we would safe guard against some possible erroneous invocations, but would allow for automated (no interaction) and **explicitly** …
=> ENH: safe-guard --existing-replace for cases of populated directories

datalad/support/annexrepo.py, datalad/support/gitrepo.py
This PR sits on top of #4168, but is kept separate to not block it due to a potential issue with this changeset.
`GitRepo.get_changed_files()` still used the GitPy diff interface, its last and only usage
was replaced by GitRepo.call_git_items_()
This furthers gh-2970
=> CLN: Remove GitRepo.get_changed_files() and its last usage

datalad/distribution/publish.py, datalad/distribution/tests/test_create_test_dataset.py, datalad/distribution/tests/test_publish.py, datalad/interface/tests/test_add_archive_content.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
This is sitting on top of gh-3833. And aims to be another step towards #2970 by fixing #3813
Sibling PR in the crawler is https://github.com/datalad/datalad-crawler/pull/66
=> Non-GitPy GitRepo.get_branch_commits()

datalad/distribution/publish.py, datalad/distribution/tests/test_create_test_dataset.py, datalad/distribution/tests/test_publish.py, datalad/interface/tests/test_add_archive_content.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
Sits on top of https://github.com/datalad/datalad/pull/3834 because it needs `get_branch_commits()` to return string hex SHAs.
=> RF: No GitPython use in publish

datalad/support/gitrepo.py
=> RF: Reimplement GitRepo.merge_base() without GitPython

datalad/interface/__init__.py
So a user would get a hint when he uses the command without datalad-container
extension being installed:
```
$> datalad containers-list
datalad: Unknown command 'containers-list'.  See 'datalad --help'.
Hint: Command containers-list is provided by (not installed) extension datalad-container.
```
=> ENH: list datalad-container extension provided commands

docs/source/customization.rst, docs/source/glossary.rst
a user complaint was that it was not clear what to do even if you discover the command in the docs which comes from an extension.  So probably all extensions should refer to the ```:term:`DataLad extension` ```, where they would be instructed to proceed to user-facing documentation (handbook) which hints on installing them.  Still a wild chase, but imho better than no term ;)
=> ENH: add "DataLad extension" to terms glossary

datalad/distribution/tests/test_create_sibling.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/utils.py
Also strips an unused function with such code.
=> RF: Use ConfigManager instead of GitPython config classes

datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
Was only ever used to fake a GitPython error, but was nowhere acted
upon, specifically. It is now replaced with ValueError, as it is done
in other places when inappropriate arguments are given (here a non-empty
directory).
Also discontinue the practice of logging a warning about a situation
that will unconditionally raise an exception on the next line. If that
exception is caught anywhere, it is the responsibility of the caller to
decide if and how to log this event.
=> RF: Discontinue use of GitCommandError

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
This series is based on the discussion in gh-4148.  On top of the existing "merge in the chosen branch from the sibling" mode, it adds a "follow parent" mode for merging in the registered revision for updated subdatasets. It replaces the approach proposed in gh-4118, which was a hybrid approach that merged in the subdataset revision directly only if the to-be-merged sibling branch didn't contain the registered revision.  It think the approach here is simpler and will make it easier for the caller to anticipate the result.
Also, `--merge` is expanded so that `--merge=ff-only` limits the allowed merges to fast-forwards, while `--merge` retains the same behavior (and is now a shorthand for `--merge=any`).
Patch 1-4 follow patches from gh-4118 pretty closely.
```
[ 1/10] RF: update: Break …
```
=> update: Support ff-only merges and merging parent revision

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py
This PR resurrects @yarikoptic's patch from gh-2615 that added local path support to `create_sibling`.  The (rebased) commit from that PR sits as the first commit of this series.  The final patch extends the existing `create_sibling` tests to go through the local path case.  The patches in between are various tweaks and fixes.
When this was initially proposed in gh-2615, the main objection, raised by @mih, was that `create_sibling` should be reworked to not assume a local or remote shell.  That is, put some abstraction layer over the calls to `{SSHConnection,_RunnerAdapter}.__call__`.  On top of that, there was the idea that such an abstraction could lead to dissolving `create_sibling_github`.
The command abstractions being worked on in gh-4068 are bringing us closer to the first part …
=> create-sibling: Add support for local paths (v2)

datalad/distribution/get.py, datalad/distribution/tests/test_get.py
Subdataset clone code already filters it out, because of that, but it should never be reported, and the test falsely expected it.
This is simplifying the work on #4180 which will also remove the double-filter again.
=> BF: Current/target location of a submodule is not a sensible clone source

datalad/support/tests/test_annexrepo.py
`AnnexRepo` does not manage to cleanup pending `annex --batch` processes
in time for the test cleanup code to wipe out the respective repository.
This only happens in this one test, that explicitly starts a batched
`find`. Hence I decided to make the symptom go away, instead of figuring
out how `AnnexRepo` could always make sure this can never happen.
The code in `AnnexRepo.__del__` aiming to achieve that does not seem to
be sufficient (anymore).
Fixes gh-4190
=> BF: Prevent test cleanup breakage on Windows

datalad/distribution/create_sibling.py
Adds no information.
Fixes gh-4188
=> ENH: Disable `siblings` output for freshly created sibling

datalad/core/distributed/clone.py
Previous code looked at two datasets simultaneously per iteration.
This could result in making a fetch attempt to a non-local repository,
because it would no check whether the second dataset was actually local.
The new code focuses on a single dataset at a time, and all checks are
performed on each one.
=> RF: Decomplexify configure_origins()

datalad/support/annexrepo.py
Issue filed within annex: https://git-annex.branchable.com/bugs/--debug_is_not_in_effect_if_precedes_-c/
verified that works, no dedicated test
=> BF(workaround): position --debug AFTER other annex_options

datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_publish.py, datalad/metadata/tests/test_aggregation.py, datalad/plugin/tests/test_plugins.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This series includes a few git-annex-related updates.  Most importantly, it deals with the removal of `--include-dotfiles` in git-annex 8.20200226 ~and switches to using `add --force-{small,large}` when available (7.20200202.7 and later)~ (update: should do, but put off for now).
=> Update for latest git-annex

datalad/cmd.py, datalad/support/exceptions.py, datalad/support/gitrepo.py, datalad/tests/test_witless_runner.py
Changes:
- parameterized protocols are instrumental for passing handles to a protocol that can be used for specific communication via callbacks, or access to information that changes while the protocol is operating.
- move output stream decoding into Protocol class
- make WitlessRunner more ignorant of the actual nature of the Protocol return value, and allow for alternative implementations that are still compatible with WitlessRunner.
The Protocol result is now always a dict that is expected to have keys 'code', 'stdout', 'stderr', matching the semantics of the CommandError exception.
- enhance CommandError to carry arbitrary additional results that may be reported by a protocol (e.g. stdout->parsed JSON), to avoid having to keep duplicates of the raw output strings
- taken together …
=> NF: Parametrized Protocols with non-stdout/err return values for WitlessRunner

datalad/cmd.py, datalad/config.py, datalad/support/external_versions.py
Since CI is too busy, decided to just bundle in a single PR.  If needed -- could split into two or three if needed (ideally should have added a test for the `DATALAD_LOG_OUTPUTS` env var actually having an effect).
See individual commits for possibly more info ;-)
=> BF+ENH+OPT: @memoize, correct config target for logging outputs

datalad/cmd.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_cmd.py
Inspired by the attempt to mitigate stalling git-annex in https://github.com/datalad/datalad/pull/4116 . Unfortunately it did not help, but it could be a beginning to RFing AnnexRepo to use new async'ed WitlessRunner.
Also it relates to #4194 which fixes `Runner` to actually use `datalad.log.outputs` config variable (instead of `datalad.log.cmd.outputs`)
TODOs:
=> RF+ENH: introduce WitlessRunner to AnnexRepo

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py
This is an alternative solution to https://github.com/datalad/datalad/pull/4199
which is lfs specific.  In this solution which would probably behave "correctly" for any
special remote which has URL and for which we never managed to fetch HEAD.
=> BF: allow for fetch to fail due to HEAD not yet been available on a remote for annex

datalad/cmd.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
that returns parsed JSON. No attempt is made (yet) to replace `_run_annex_command_json()`
`--json-progress` type messages are acted upon immediately (like in GitProgress), and are subsequently excluded from the normal JSON record reporting.
Split from #4206
=> NF: WitlessProtocol for `annex ... --json` commands

datalad/core/local/diff.py
This make a faster diff with `eval_file_type=True` accessible to
internal users (like `push()`).
`reporting_order` enables more flexible applications. While the past and
current default `depth-first` is most suitable for human-readable
reporting, the alternative `breadth-first` enables straightforward
consolidation of all diff reports for a dataset (incl. all submodule
records) into an uninterrupted series of results. This simplies client
code that needs to investigate a complete changes set of a dataset, and
aims to yield its conclusions immediately, in order to kick of further
processing (generator-style) -- useful for effective parallelization.
Split from #4206 
TODO:
=> ENH: Expose diff_dataset() and add reporting_order parameter.

datalad/tests/test_utils.py, datalad/utils.py
Rational in the diff. We would need to budget ~1min per call to
get_open_files. This isn't worth it, given that this is only an
occasionally used test helper.
The test is now cut short on windows, only performing the timing
insensitive parts. It still runs for almost 3min...
Fixes gh-4233
=> TST: Relax get_open_files() test on Windows due to performance issues.

datalad/downloaders/s3.py, datalad/downloaders/tests/test_s3.py
See first commit (cc7dbd5ac0f2722a6056e1ce4149d535d1bb080a ATM) for details
=> BF: Allow to explicitly specify host to aws-s3 resource

datalad/distribution/publish.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Per request in https://github.com/datalad/datalad/pull/4206#discussion_r387201686
To consolidate corresponding branches and sync 'git-annex' branches of
one or more given, or all remotes. Does not leave behind 'synced/...'
branches, unless they existed prior calling the method.
=> RF: Dedicated method to perform a local annex sync

.github/workflows/test_crippled.yml
This aims to disentangle detection of issues with Windows and issues
with adjusted branch operation. There is no expectation that a run
would initially succeed... even on Linux.
Appveyor and Travis runs will be canceled.
TODO
This seems to be a great success. In 8min we get to see that a large chunk of tests don't work out:
```
Ran 117 tests in 481.873s
FAILED (SKIP=6, errors=43, failures=5)
```
The most popular error is
```
'git annex sync --no-commit --no-push --no-pull' failed with exitcode 1 under /crippledfs/datalad_temp_check_create_path_semantics1p3hq_fs [err: 'fatal: entry '<imagine subdataset path here>' object type (blob) doesn't match mode type (commit)
```
which I feel has been reported before.
=> TST: Add Github CI workflow to run core tests on a crippled FS

.github/workflows/benchmarks.yml, .github/workflows/docbuild.yml, .github/workflows/test_extensions.yml, .github/workflows/test_win2019.yml
I was confused to not see any "master" builds in the github actions.  That
precluded to see what last state of master was ok on windows.
=> ENH: run github workflows on push as well

datalad/distributed/create_sibling_ria.py, datalad/distributed/tests/test_create_sibling_ria.py
Remove entirely when not necessary. If necessary 'ria' refers to the
concept of a store, whether the datasets are addressable by their
dataset ID.
A further renaming will happen as part of gh-4164, where 'ria-remote'
(the special remote implementation) is replaced by 'ora-remote'.
Together, this changes disambiguate the term 'ria'.
This change also removes TODOs from the documentation.
=> RF: Reduce use of "ria" label

datalad/distribution/siblings.py
=> ENH: Complain like Git if to-be-removed sibling is unknown

datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_status.py
Those are particularly noisy and blow up the logs.
=> TST: Disable result renderer for diff() and status() tests

datalad/support/annexrepo.py
(effective) because apparently we had 2 set_remote_url definitions.
Earlier (in time and in the code) was located among other methods dealing
with remotes (thus I kept that location, which also invoked
self._set_shared_connection.
And later one, which added custom to AnnexRepo handling  of annexurl, but
lacked invocation of self._set_shared_connection.  I took later version,
placed it inplace of the older (earlier in the code) one, while maintaining
the self._set_shared_connection invocation.
This now causes ssh call to have socket defined for target2, so later
enableremote has a better chance to reuse it.
Closes #4195 and has resolved regression/difference in behavior of the recent git-annex-standalone build in #4116
=> BF+RF: AnnexRepo - add set_shared_connection to (effective) set_remote_url

.github/workflows/test_win2019.yml, appveyor.yml
Version was picked, because it happened to have been installed on @mih debug win10 box.
As expressed elsewhere, datalad+git-annex on windows is moving to fast as a target for me to ever catch up. I'd rather have some things working reasonably well with a particular annex version that nothing with the latest version. Also, the noise contributed by the windows tests is hurting, because they make devs more likely to ignore actual failures caused by regressions.
Will cancel Travis run.
=> TST: Pin git-annex version to 7.20191107 for windows CI runs

datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_save.py
- Two tests needed a workaround for an annex.dotfiles-related failure on adjusted branches.  This has been fixed upstream, so limit the workaround to versions of git-annex that need it.
- For older git-annex versions, skip failing cases of `check_save_dotfiles` on adjusted branches.  This failure became apparent when the windows ci runs were pinned to 7.20191107 (gh-4264).
=> Test updates for git-annex dotfiles fix 

datalad/support/annexrepo.py
AnnexRepo checks whether the git-annex version is at or below
7.20200226 to decide whether the installed git-annex has
--include-dotfiles.  That was a poorly chosen check because the
annex.dotfiles/--include-dotfiles change happened with the transition
to v8 (currently git-annex's master), which means DataLad will need a
compatibility fix if another release is cut for v7.  (This is
particuarly relevant given that 7.20200309 has been tagged in the
git-annex repo.)
Make this check use the v8 boundary.
=> BF: annexrepo: Future-proof "has --include-dotfiles" check

datalad/distribution/tests/test_update.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py
When dealing with managed branches, one frequently has to switch
behavior depending on their presence. With this change the return value
of `get_corresponding_branch()` carries the information whether there is
such a branch or not, and immediately allows decision making based on
it.
Previously, it required an additional call to `is_managed_branch()`
(that is duplicated in `get_corresponding_branch()` in order to determine
this condition.
This cost reduction is minimal, but the code complexity goes down.
The previous behavior is easily achieved via
`get_corresponding_branch(branch) or branch`
and seem to communicate more direct what is intended.
A `GitRepo.get_corresponding_branch()` that always returns `None` has been
added to further simplify decision making and avoid type-based …
=> RF: AnnexRepo.get_corresponding_branch() -> None without a managed branch

datalad/core/local/repo.py, datalad/distribution/dataset.py
And RF Dataset.repo to use it.
This is needed for work in GitRepo, where type-specific prcoessing of
submodules is needed.
=> NF: Factory function to get Repo instances from a path

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/interface/__init__.py, datalad/support/annexrepo.py, docs/source/cmdline.rst, docs/source/modref.rst
Approach is similar as before:
- do not attempt to build a 1:1 replacement of `publish`
- see what makes sense for the scope of a "plumbing" command
- focus on correct operation, not feature-wealth
- keep parallelization in mind
- hide as little as shallow as possible
Note that the tests here are affected (probabilisticly) by #4279 
Status quo:
annex JSON comminucation. Results are directly reported after normalization without intermediate inspection and decision making. Fixes gh-3412
=> datalad.core.distributed.push

datalad/support/annexrepo.py, datalad/support/gitrepo.py
Switch over to using `--force-{large,small}` instead `-c annex.largefiles={anything,nothing}`.  The last commit gives background on why we should avoid one-off `annex.largefiles` overrides.
---
This may help with the intermittent failures mentioned in gh-4218.
=> Use annex-add's --force-{large,small} when available

datalad/support/tests/test_annexrepo.py
Situation is not yet clear either it is purely our Runner (which did
reveal possible situation where it would hang, see
https://github.com/datalad/datalad/pull/4265) or there is something
really new worth considering in how git-annex process "behaves".
This commit is intended for 0.12.3 (maint branch).
When merging to master, this commit changes should first be RFed to
see if using GitWitlessRunner (instead of the old one as here)
mitigates the issue.
=> BF(TST,workaround): skip test which checks that git-annex creates ssh socket

datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_status.py, datalad/distribution/dataset.py, datalad/interface/download_url.py, datalad/interface/run_procedure.py, datalad/interface/tests/test_unlock.py, datalad/metadata/search.py, datalad/metadata/tests/test_base.py, datalad/metadata/tests/test_search.py, datalad/plugin/wtf.py, datalad/support/exceptions.py
This exception is now (since 0.12) is frequently shown to users due to breakage
of behavior as discussed in https://github.com/datalad/datalad/issues/3759 .
As it is worded minimally, it provides no instructions to the users and just
brings frustration.  This commit extends message to provide instructions on how
to mitigate the error they start to observe
=> ENH: extend message for a NoDatasetArgumentFound in require_dataset

datalad/core/local/save.py
Closes gh-1974
CI canceled, only doc change.
=> DOC: Rephrase save(to_git=) docs to indicate lack of choice persistence

datalad/support/gitrepo.py
When the GitProgress protocol receives a line like
Receiving objects:  32% (22269/69588), 7.98 MiB | 7.98 MiB/s
it extracts anything after (M/N) as the message.  This message is used
to detect when a particular action is done, but it's also used as the
"message" parameter to log_progress().
The latter is problematic when running non-interactively---where the
messages are shown with standard logging rather than progress
bars---because many lines have an empty message, leading to many lines
of uninformative output (as in this example [0]).
Prevent this by using the entire matched line as the message.  This
leads to the non-interactive logging closely matching what the caller
would see from the command line.
[0]: https://github.com/datalad-handbook/book/issues/390
---
This changes …
=> ENH: gitrepo: Use matched line as message for log_progress()

datalad/log.py, datalad/support/gitrepo.py, datalad/tests/test_log.py
This sits on top of gh-4293 and is meant to solve the problem of `log_progress` producing overly verbose non-interactive logging for the default INFO-level configuration.
It changes
```
[INFO] Cloning dataset to <Dataset path=/tmp/dl-nqnScvV> 
[INFO] Attempting to clone from https://github.com/datalad/datalad.git to /tmp/dl-nqnScvV 
[INFO] Start enumerating objects 
[INFO] Finished enumerating objects 
[INFO] Start counting objects 
[... 416 lines ...]
[INFO] Finished resolving deltas 
[INFO] Completed clone attempts for <Dataset path=/tmp/dl-nqnScvV> 
install(ok): /tmp/dl-nqnScvV (dataset)
```
into
```
[INFO] Cloning dataset to <Dataset path=/tmp/dl-nJ2rgU2> 
[INFO] Attempting to clone from https://github.com/datalad/datalad.git to /tmp/dl-nJ2rgU2 
[INFO] Start enumerating objects …
```
=> gitrepo: Restrict non-interactive log_progress() output 

datalad/support/gitrepo.py, datalad/support/network.py, datalad/support/repo.py, datalad/tests/utils.py, datalad/utils.py
This might be an issue in other places too!
The behavior of `resolve()` conflicts with its [documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve) that claims:
> Make the path absolute, resolving any symlinks.
=> BF: resolve() does not imply absolute() on Windows for non-existing paths

.github/workflows/test_crippled.yml, datalad/distributed/tests/test_ria_data_transfer.py, datalad/local/tests/test_subdataset.py
=> TST: Expand testing on crippled FS to all modern API

datalad/tests/test_utils.py
=> TST: Remove superfluous tzset() call and enable on windows

datalad/interface/common_cfg.py
The description for `datalad.log.outputs` says that the output is logged at DEBUG, which isn't the case.  Fix that and make a few other minor changes.
=> common_cfg: Tweak log.outputs entry

datalad/distribution/siblings.py
I have reworded the warning and info messages related to adding siblings without an annex. Mostly, I've removed the word "failed". I've played around with "downgrading" the message from "warning" to "info", but I guess the color coding as a warning helps to not miss a problem should there ever be one. The text should make sure that this Warning is no need for worry if the remote is a pure Git remote. 
I think its better than the previous messages, but I'm not yet 100% satisfied. Here is how the message looks like for the situation described in #4322 
```sh
datalad siblings add --name bitbucket --url https://testing_ittacc@bitbucket.org/testing_ittacc/mydataset.git
[INFO   ] Could not enable annex remote bitbucket. This is expected if bitbucket is a pure Git remote, or happens if it is not …
```
=> DOC: make warning on absent annex appear less like an error

datalad/cmdline/main.py, datalad/interface/__init__.py
Now message would look like:
datalad: Unknown command 'add'.  See 'datalad --help'.
Did you mean any of these?
addurls
Hint: Command 'add' was deprecated in favor of 'save' command.
thus giving enough information to not dig through CHANGELOG.md to
proceed
=> ENH(UX): provide a hint on a deprecated add command

datalad/log.py
```
The tqdm progress bars created by log_progress() have two related
issues:
* Following the first log_progress() call, a bar does not show up
until after the next call to log_progress() (i.e. the first
update).  This is because log_progress() does not call
tqdmProgressBar.start(), so the tqdm class isn't initialized until
._create() gets called within .update().
* At that point, the bar shows up at the initial value.  On the
second update, it jumps from the initial value to the correct
value (say, 0 -> 2 if incrementing by 1).  The first update isn't
displayed because tqdm has logic to skip updates that happen at
too fast of a rate, so the first .update() call that creates the
bar gets its update skipped.
Fix these issues by calling .start() on the first call to
log_progress().
```
--- …
=> BF: log_progress: Start progress bar

datalad/core/distributed/tests/test_push.py, datalad/core/local/create.py, datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_create_test_dataset.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_update.py, datalad/interface/base.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_unlock.py, datalad/metadata/extractors/tests/test_base.py, datalad/plugin/tests/test_addurls.py, datalad/plugin/tests/test_export_archive.py
This avoids double-negative thinking when using the Python API, and fixes gh-4207
There is no change wrt the command-line API.
A warning is emitted if, and only if, using the Python API `no_annex=True` is given in conflict with the value of `annex`.
In order to make this a smooth transition (but possibly with further future benefits), it is now possible to have Python-only arguments for our commands.
This can be achieved by setting the `args` of a `Parameter` instance to be an empty tuple. The value `None` continues to indicate that a default argument name should be derived from the
parameter name. Example:
```
some_param=Parameter(args=tuple(), ...)
```
=> create(no_annex=False) -> create(annex=True)

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/interface/common_opts.py, datalad/support/constraints.py
Makes it possible to set up datasets for collaborative write access
on install. This is implemented as a reckless mode, because it bypasses
the standard annex write protection feature (see gh-1893).
- rewrote the `reckless` option docs
- added example to the clone docs
- add test of permission setup validity
This fixes gh-1146 although it doesn't implement a dedicated `--shared`
option. And it mitigates gh-1893, by providing a dedicated, documented mode
that marks the effected datasets as untrusted.
=>  NF: clone/install --reckless shared-{group|all|...}

datalad/support/exceptions.py
Detected while trying to build package in Debian which has now git
2.26.0.rc2 which lead to the following failure
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_gitignore
File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
File "/build/datalad-0.12.4/.pybuild/cpython3_3.7_datalad/build/datalad/tests/utils.py", line 559, in newfunc
return t(*(arg + (d,)), **kw)
File "/build/datalad-0.12.4/.pybuild/cpython3_3.7_datalad/build/datalad/support/tests/test_gitrepo.py", line 1235, in test_GitRepo_gitignore
gr.add('ignore.me')
File …
=> BF: match "hint: " prefix for ignored files message by git

datalad/support/annexrepo.py, datalad/support/tests/test_fileinfo.py
Passing init=None fails with
rec.update({'{}{}'.format(key_prefix, k): j[k]
AttributeError: 'NoneType' object has no attribute 'update'
Set `rec` to an empty dict when init=None.
=> BF: get_content_annexinfo: Fix init=None handling

_datalad_build_support/formatters.py
They were introduced to avoid rendering of typographic m-dashes instead
of double-dashes in the HTML version. This change limits this escaping
to the HTML version.
Fixes gh-4032
=> BF: Avoid spurious backslashes in manpage double-dash option listings

datalad/plugin/wtf.py
it now says:
```sh
datalad wtf -d ../nada                                                                       1 ↵
[WARNING] No dataset found at /tmp/nada. Reporting on the dataset is not attempted. [wtf(/tmp/nada)] 
- full_version: 0.12.3.dev547-g6a60c
- version: 0.12.3.dev547
```
fixes #4100
=> ENH: Warn when provided dataset to wtf does not exist

datalad/cmd.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py
@yarikoptic mentioned that `git annex init` could take some time on the "scanning for unlocked files" phase.  This series teaches `AnnexRepo._run_annex_command` to take a custom protocol and switches `AnnexRepo._init` over to using a `WitlessProtocol` that logs this at the info level.
---
Example output:
```
$ datalad install ///openneuro                  
[INFO   ] Scanning for unlocked files (this may take some time)                         
install(ok): /tmp/dl-vwEPXnr/openneuro (dataset)   
```
=> annexrepo: Tell caller that annex is scanning for unlocked files

datalad/plugin/tests/test_plugins.py
I merged 6a60cc230c (ENH: Warn when provided dataset to wtf does not
exist, 2020-03-24) without doing a proper check of which tests failed.
Do the minimum fix to get the now failing `test_wtf` into a passing
state.
=> TST: wtf: Adjust test for gh-4331

datalad/interface/utils.py
Saving a dataset with a 1000 files will now look like this:
```
% datalad save
add(ok): 1 (file)
[999 similar messages have been suppressed]
add (ok: 1000)
save (ok: 1)
```
Failing to get a 1000 files looks like this (with `datalad.log.result-level=debug`)
```
% datalad get .
Total (0 ok, 1000 failed out of 1000):   0%|                     | 0.00/3.89k [00:01<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1000 failed
get(error): 1 (file) [Unable to access these remotes: origin; Try making some of these repositories available:;      2cc06516-5731-43a5-88e9-39499f2114e9 -- mih@meiner:/tmp/massive [origin]]
[999 similar messages have been suppressed]
get (error: 1000)
```
Without the config switch, the second …
=> RF: Suppress similar repeated messages in the default result renderer

benchmarks/api.py, datalad/interface/ls_webui.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/test_direct_mode.py
bea8551d76 (RF: gitrepo: Rewrite get_submodules() to avoid GitPython,
2019-07-30) switched get_submodules() over to using the recently added
get_submodules_() method, adding a `compat` parameter to
get_submodules() that is true by default and leads to a return value
that mimics the old GitPython-based one for backward-compatibility.
That commit left a good number of spots in our internal code base
using the deprecated interface.  Clean up all remaining uses of
get_submodules(..., compat=True).
=> MNT: tree-wide: Avoid use of deprecated get_submodules(compat=True)

tools/changelog-todo
In the past, I've shared the command that I use to prepare a to-do
list for updating the changelog (e.g., gh-3774).  The log command is
the important part, but on top of that I have a convenience wrapper
that generates the output, automatically selecting the range based on
the last commit to touch the changelog.  That wrapper is written in
elisp, but here's a shell script translation that can more easily be
used by others.
Suggested-by: @yarikoptic
=> tools: Add script to generate changelog to-dos

datalad/core/local/create.py, datalad/distribution/dataset.py, datalad/utils.py
Also includes the helper decorator in the first commit (`@collect_method_callstats`) -- see that commit for an example use.
Let's see what benchmarks run would say ;-)
=> OPT: use locally bound variables instead of dataset.repo and .config

datalad/core/distributed/push.py, datalad/interface/utils.py, datalad/support/gitrepo.py
Sometimes, Git has "hints" why pushing fails. 
For example, if I attempt a push without integrating remote changes, it says
```
error: failed to push some refs to 'git@github.com:datalad-handbook/DataLad-101.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
`datalad push` swallowed these hints. In this PR I'm attempting to catch them and report all hints at the end of the result rendering.
```
datalad push --to blubb43
publish(error): . (dataset) [refs/heads/git-annex->blubb43:refs/heads/git-annex [rejected] (fetch first)]
Potential hints to solve encountered errors: 
1: …
```
=> ENH: Capture hints from Git

datalad/tests/test_direct_mode.py
test_direct_cfg checks that DataLad errors appropriately if direct
mode is requested.  The second half of the test depends on a git-annex
that supports direct mode, which isn't the case as of git-annex
7.20190912.  Our minimum git-annex version is currently 7.20190503 and
we test with 7.20190819+git2-g908476a9b on Travis, so this test could
still be considered worth keeping around.
Leave a comment so that grepping for GIT_ANNEX_MIN_VERSION will turn
up this spot for a future cleaner that is looking to prune no longer
needed git-annex version conditions.
=> TST: direct_mode: Add comment flagging part of test for removal

.travis.yml, datalad/cmd.py
That should ensure that error messages are hints are in English so
we could still parse them and react accordingly.
Closes #4340
TODO:
- [DID NOT WORK] test - should we set LANG in some of the travis runs?
=> BF: set LC_ALL=C while running git

.gitmodules
I think it kept causing more pain than gain with commits of changed .asv to git etc.
.asv/ already in .gitignore.  I am yet not sure how/if it would impair my benchmarking
setup - will deal with it later
Positioning against `maint` so we do not get into issues while switching between maint and master if one has it and another one doesn't (although I guess git might handle it just fine)
=> RF: Remove .asv as a submodule

datalad/distribution/tests/test_update.py
An update() test expects a failure when fetching an unadvertised
object, but this failure no longer happens by default with Git
v2.26.0, specifically 684ceae32d (fetch: default to protocol version
2, 2019-12-23).  v2 unconditionally supports fetching unadvertised
objects.
Trigger the desired failure with the latest Git by instructing the
client to use v0.  This is the same approach that Git uses for its own
tests that expect fetching an unadvertised object to fail: ab0c5f5096
(tests: always test fetch of unreachable with v0, 2019-02-25).
---
update: [passed](https://travis-ci.org/github/datalad/datalad/builds/668917060)
=> update: Adjust test for v2 wire protocol default

datalad/interface/tests/test_utils.py, datalad/interface/utils.py
Patches 2 and 3 resolve the issues demonstrated in gh-4352.
```
[1/5] TST: interface: Extend TestUtils with result_fn parameter
[2/5] BF: interface: Elide after 10, not 11, similar results
[3/5] BF: interface: Drop spurious messages about suppressed results
[4/5] RF: interface: Move "suppressed similar messages" display to helper
[5/5] ENH: interface: Handle singular case in "suppressed messages" message
```
Fixes #4352.
---
<details>
<summary>Cases from gh-4352</summary>
```
There are 10 files to save
add(ok): foo-001 (file)
add(ok): foo-002 (file)
add(ok): foo-003 (file)
add(ok): foo-004 (file)
add(ok): foo-005 (file)
add(ok): foo-006 (file)
add(ok): foo-007 (file)
add(ok): foo-008 (file)
add(ok): foo-009 (file)
add(ok): foo-010 (file)
add (ok: 10) …
```
=> Fixes for recent "suppressed similar messages" feature

datalad/core/local/tests/test_save.py, datalad/support/gitrepo.py
As of v0.12.0, specifically 2fda83e2ca (ENH: Record the active branch
of a subdataset in the parent, 2019-10-20, gh-3817), we record the
current branch in the _parent_ repository as the value for
`submodule.<name>.branch` in .gitmodules when saving a new submodule.
There are a few problems with this:
* The current branch in the parent is recorded.  It seems unlikely
that that was the intent because there is no reason to assume a
branch with that name exists in the submodule repository or, if it
does, to assume that the parent and submodule branches are
necessarily coupled.  2fda83e2ca mentions gh-1424
(`Datalad.recall_state()` -> `load` command) as the motivation,
which makes it seem likely the current branch in the submodule,
not the parent, was supposed be recorded.
This was mentioned …
=> BF: gitrepo: Revert changes to store branch in .gitmodules

_datalad_build_support/setup.py, docs/source/conf.py, docs/source/config.rst
As mentioned at gh-4382, the docbuild workflow is now failing due to warnings that are new to the recent Sphinx release. This first commit deals with a deprecation warning (that wasn't actually causing the failure), and the second commit eliminates the "duplicated glossary entry" warnings that were triggering the failure.
=> Fix failing docbuild workflow 

datalad/metadata/tests/test_search.py
This test depends on the state of the external resource -- http://datasets.datalad.org,
and that is why can become "outdated".
Similar to testing extensions - I will move this and possible some others later into
that (///) dataset itself under http://datasets.datalad.org/.datalad/tests/ (already
has some).  Enabling their testing in datalad-extensions is WiP.
Became independent from #4398
=> RF: completely stripping skipped test_our_metadataset_search

datalad/metadata/search.py, datalad/metadata/tests/test_search.py
Fixes #4393 
So now we would get something like
```
$> datalad search -d /// path:*bu
[ERROR  ] regular expression '(?i)*bu' (original: '*bu') is incorrect: nothing to repeat at position 4 [search.py:_compile_query:934] (ValueError)
```
instead of
```
[ERROR  ] nothing to repeat at position 4 [sre_parse.py:_parse:645] (error)
```
While at it -- completely removed skipped test. It was disabled for a while, and it depends on the external resource (our `///`) so could be flaky without our code changes, and takes awhile.
=> ENH: Make exception thrown by re a bit more informative

datalad/interface/common_cfg.py, datalad/support/annexrepo.py
git-annex has an annex.retry option that instructs it to retry on
transfer failure, but it defaults to 0.  Add a datalad.annex.retry
option that defaults to 3 and is used as the value for annex.retry in
our calls to git-annex, taking care to not override annex.retry if the
user has configured it.
This implements @yarikoptic's proposal from gh-2896 and will hopefully
help resolve some flaky test failures (e.g., gh-3653 and gh-4371).
Closes #2896.
=> annexrepo: Set annex.retry=3 when calling git-annex

datalad/core/distributed/tests/test_clone.py
Two of the tests added in 8f5cc450c2 (ENH: clone: Try to switch away
from an unborn branch, 2020-04-01) fail on the crippled file system
run.  The easy part to fix is to write assertions about the
current branch using get_corresponding_branch (written a bit oddly for
compatibility with the changed return value in master).
The more involved part is changing the setup in test_clone_unborn_head
to account for the fact that, while setting up, we may be on an
adjusted branch.  This means we can't use empty commits, because
git-annex diffs to decide whether things need to be propagated back.
And we need to sprinkle in calls to adjust() followed by save() to
sync state.
---
This should resolve the CrippledFS failures mentioned in gh-4405.  Note that this is branched from maint, but the initial …
=> clone: Tweak unborn head tests for adjusted branch compatibility

datalad/support/tests/test_annexrepo.py
Two [failing tests][0] in the datalad-extensions repository caught a not-yet-released regression in git-annex.  That was fixed on git-annex's side, but one of the tests (`test_AnnexRepo_always_commit`) still fails due to making unwarranted (IMO) assumptions about git-annex's behavior.  The first patch brings the test into a passing state with the latest git-annex (a7840c0e0).  The following two are small tweaks that I think are improvements but would be fine dropping.
```
[1/3] TST: annexrepo: Loosen assumptions about alwayscommit=false behavior
[2/3] TST: annexrepo: Handle alwayscommit set/restore with patch()
[3/3] TST: annexrepo: Don't assume initial number of git-annex commits
```
[0]: https://github.com/datalad/datalad-extensions/pull/9#issuecomment-613545934
=> test_AnnexRepo_always_commit: Update for unreleased git-annex changes

datalad/config.py, datalad/tests/test_config.py
In our case these changes will
- result in `None` being the value
- `getbool` returning `True` (really adhoc, not part of any2bool since
makes little sense generally)
Without this fix our code would simply crash while reading a legit (to
git) .git/config with
File "/home/yoh/proj/datalad/datalad-maint/datalad/config.py", line 301, in reload
log_stderr=True
File "/home/yoh/proj/datalad/datalad-maint/datalad/config.py", line 96, in _parse_gitconfig_dump
kv_match = cfg_kv_regex.match(line)
AttributeError: 'NoneType' object has no attribute 'groups'
A little more on this messy issue of boolean values could be found
in a recent discussion on git-annex:
https://git-annex.branchable.com/bugs/does_not_understand___34__yes__34___as_boolean_true_value_for_autoenable/
=> BF: config - become consistent with git in treating key without any value as True

datalad/interface/tests/test_utils.py, datalad/interface/utils.py
This resolves the confusing silence that can occur during the suppression of similar results (described in gh-4413).  As a needed piece, it addresses gh-4416 as well.
I played around with the "jump out of suppression after N seconds" idea.  It's not too complicated code-wise, but it's more complicated than just emitting/overwriting a message about suppressed results for each result.  And I think more importantly overwriting the line leads to output that is easier for the caller to digest.  This matches (at least in spirit) one of @yarikoptic's proposals in gh-4413.
=> interface: Provide more timely feedback when suppressing results

datalad/distribution/dataset.py
__repr__ of a dataset always uses the 'path=' prefix to the path, but a
dataset is also always and only identified by a path. Hence the prefix
is superfluous, and only takes space. On any platform an absolute path
is easy to recognize as such.
This change removes the 'path=' prefix.
=> RF: <Dataset path=...> -> <Dataset ...>

datalad/interface/common_cfg.py, datalad/interface/common_opts.py, datalad/support/annexrepo.py
The previous default behavior `(max(8, min(3, nCPUs)))` could cause
issues (crashes, system stalls) due to the large number of child
processes spawned and file descriptors opened.
This change introduces a new config switch
`datalad.runtime.max-annex-jobs` that can be used to tailor
parallelization behavior, and effectively replaces the previously
hard-coded maximum value of `8`. Moreover, it drops the default to `1`
to disable parallel annex jobs by default to ensure a potentially
slower, but more robust behavior out of the box.
The config switch is specific to annex jobs in order to leave room for
an anticipated parallelization of some functionality in DataLad itself.
This will likely need separate configuration to be able to handle the
multiplicative impact of parallelization on two …
=> RF: Make default number of annex jobs configurable and 1 by default

datalad/tests/test_utils.py, datalad/utils.py
This is the message:
`[WARNING] realpath of PWD=</some/path/to/symlinked/file> is </resolved/path/to/symlinked/file> whenever os.getcwd()=<path/to/dataset>`
Questions about it have motivated a dedicated "please ignore it" PR
in the handbook: https://github.com/datalad-handbook/book/pull/438
I think this message is pointless (but still unconditionally shown) if
everything works. When something doesn't work, it is likely caused by
a bug in DataLad. Hence there is no need to bother users with this
warning that they can or should do nothing about.
Fixes gh-4425
=> RF: Demote symlinked CWD related log message to debug-level

datalad/support/annexrepo.py
Ideally git-annex should not modify paths - not sure yet if there are other places
where we have an assumption of matching file name.
But this is a candidate to resolve failures of our tests -- do not rush to merge it.  Let's first see 
Closes #4431
=> BF(workaround): normpath while asserting if annex returned entry for correct path

datalad/consts.py, datalad/support/github_.py, datalad/support/tests/test_github_.py
Without it we immediately might fail if there is a known token which
does not have necessary permissions.  Typically this would lead to just
a failure like
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'
now we will just go to the next credential while also providing an
informative log message on either we succeeded or not.  So the interaction
would look like
$> datalad create-sibling-github --github-organization datalad-collection-1 testds
[WARNING] Having authenticated using token, we failed (401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}) to access information about organization datalad-collection-1. We will try next authentication method (if any left …
=> BF: github - cycle to the next credential when we fail to obtain organization

datalad/support/annexrepo.py, datalad/support/gitrepo.py
Continuing where 226bee866d9fa89147c3bbc87a54f3f882108ba3 stopped,
this compacts `__repr__` for the Repo classes. Turning
`<GitRepo path=/home/mih/hacking/datalad/git (<class 'datalad.support.gitrepo.GitRepo'>)>`
into
`GitRepo(/home/mih/hacking/datalad/git)`
There is little (if any) practical benefit for reporing the class name.
=> RF: Uniform __repr__ for Repo classes

datalad/log.py, datalad/ui/progressbars.py
This PR enhances the existing progress bars with the ability to
1) set an initial value for the progress bar
```
log_progress(lgr.info, '3',  'whee!', total=400, initial=20)                  
5%|██▊                                                     | 20.0/400 [00:00<?, ?/s]
```
and 2) update the total of an existing progress bar
```
log_progress(lgr.info, '3',  'whee!', update=0, increment=True, total=1000)   
2%|▉                                              | 20.0/1.00k [00:00<00:00, 154k/s]
```
This is hopefully some ground work towards #4390.
=> ENH: A bit more flexibility for progress bars

datalad/plugin/wtf.py, datalad/support/external_versions.py, datalad/support/tests/test_external_versions.py
Use case: datalad-neuroimaging started to fail tests.  Preliminary
check seems to point toward newer dcm2niix.
It would be nice if extensions, where matters, could check for their
externals and possibly even register them within our "central"
ExternalVersions checker.  This is what `add` effectively does.  Also
for regular python modules, it would pretty much just allow to add
them to "INTERESTING" list - displayed by dumps.
I have positioned it against maint for now since it would allow extensions to use this feature sooner than later, and it is largely a minor enhancement which should not have negative side-effects (I hope ;)).  But if there are objections, I am ok to change it to go to master.
=> ENH: ExternalVersions.add - for extensions etc to add custom checkers

datalad/distribution/get.py
I have not done full archeological expedition to figure out how it
came about, but I spotted that message
$> datalad --version ; datalad get -r openneuro/ds000017/sub-1/ses-timepoint1/
datalad 0.12.6.dev1
[INFO   ] Installing <Dataset path=/home/yoh/datalad/openneuro> underneath /home/yoh/datalad/openneuro/ds000017/sub-1/ses-timepoint1 recursively
[INFO   ] Installing <Dataset path=/home/yoh/datalad/openneuro/ds000017> underneath /home/yoh/datalad/openneuro/ds000017/sub-1/ses-timepoint1 recursively
made no sense.  If anything -- it should have been "containing" not
"underneath".  But I have decided to not state any relationship but rather just
state the purpose (I believe we had it like that at some point),  So now it
would look
$> datalad --version ; datalad get -r …
=> BF: fix get INFO msg to not state "underneath" relationship

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distributed/create_sibling_ria.py
`clone()` can now handle URLs of the format
`ria+<protocol>://<storelocation>#~<aliasname>`
in addition to those containing UUIDs (examples inside).
A future addition should likely equip `create-sibling-ria()` with the ability
to establish those aliases too. But for now it is not clear to me how to
do that best (in particular how to perform properly on reconfigure).
Given time-pressure this needs to wait for another time.
Fixes gh-4424
=> ENH: Support dataset aliases in RIA stores

datalad/core/local/diff.py, datalad/core/local/run.py, datalad/core/local/save.py, datalad/core/local/status.py, datalad/distribution/drop.py, datalad/distribution/get.py, datalad/distribution/install.py, datalad/distribution/remove.py, datalad/distribution/update.py
DOC: examples: shortened opts for all code_cmds Closes #4105
This accompanies previous few commits..
Where I mostly just changed the obvious options:
--input -> -i
--output -> -o
--dataset -> -d
--recursive -> -r
maybe a few others (?)
the ones that I deemed non-obvious can be seen using
Something like that below
bash-3.2$ pwd
/Users/andy/Projects/datalad
bash-3.2$ pyfiles=`ls *py`; for pf in $pyfiles; do  cat $pf | grep code_cmd -A 2 | grep " --"; done
bash-3.2$ pyfiles=`ls */*py`; for pf in $pyfiles; do  cat $pf | grep code_cmd -A 2 | grep " --"; done
bash-3.2$ pyfiles=`ls */*/*py`; for pf in $pyfiles; do  cat $pf | grep code_cmd -A 2 | grep " --"; done
code_cmd="datalad drop <path/to/content> --nocheck"),
--source='https://github.com/datalad-datasets/longnow-podcasts.git'"""),
datalad …
=> Doc examples opts 4105

datalad/interface/base.py, datalad/interface/tests/test_base.py
Since 8e7950d5f0 (ENH: Add the ability for custom result summary
rendering, 2018-12-05), command-line calls that request tailored
output from commands with a custom_result_summary_renderer() method
show repeated lines:
$ datalad -f tailored status --annex
1 annex'd file (4.0 B recorded total size)
1 annex'd file (4.0 B recorded total size)
With that commit, there are three custom_result_summary_renderer()
calls:
* one in setup_parser(), added by f558ada4dd (NF: Result summary
renderer [...], 2017-03-21)
* another in the return_type!="generator" path of eval_func(), again
added by f558ada4dd.
* a newer one in the return_type="generator" path of eval_func(),
added by 8e7950d5f0
While the latest addition exposed the issue from the command line, it
is actually the older call in setup_parser() …
=> BF: interface: Drop repeated custom_result_summary_renderer call

datalad/distribution/get.py
The custom_result_summary_renderer for get() was added back in
f558ada4dd (NF: Result summary renderer (more or less useful demo in
`get`), 2017-03-21).  At that time, a caller had to specify "tailored"
as the output format to see the custom summary output.  As of
b8b282d842 (ENH: enable custom summary result rendering also for
default rendering, 2020-03-24), the custom summary is now triggered
for the default renderer as well.
Here's an example of the custom summary when get() is called with two
files that are already present:
Tried to get 2 files that had no content yet. 2 (failed).
/tmp/dl-SckMiLB/two [file] ... notneeded
/tmp/dl-SckMiLB/one [file] ... notneeded
As pointed out in gh-4455, there are a few problems with this
output: 1) the files do have content, 2) a "notneeded" result …
=> RF: get: Delete custom_result_summary_renderer

datalad/cmdline/main.py
The optimization in fb38c7098 (OPT/RF: create only the subparser
needed for the command, offer "closest" choices, 2018-05-17) sped up
datalad, but it (would have [*]) broken the argcomplete-based
command-line completion due to the spots in setup_parser() that raise
an exception rather than returning the parser that argcomplete needs
to inspect.
To make completion work again, add a flag to setup_parser() that
signals that datalad is being called by argcomplete.  In this
scenario, avoid failing early so that argcomplete can do its thing.
Closes #4473.
[*]: When I tried from fb38c7098^, completion still didn't work
because an exception is raised in config.py due to cfg_kv_regex
not matching when datalad is run under argcomplete (for reasons I
haven't looked into).  But, when I worked around …
=> BF: cmdline: Restore argcomplete functionality

Makefile
This PR encloses the shell-substitution for PATH and PYTHONPATH in the test-code target of the Makefile in double-quotes. That prevents errors where the original PATH or PYTHONPATH environment variables contain whitespaces.
=> BF: fix handling of environment variables that contain whitespace

datalad/distributed/create_sibling_ria.py, datalad/distributed/tests/test_create_sibling_ria.py
`create-sibling-ria` didn't adjust dataset record for results with recursive invocation.
Closes #4484
=> BF: Fix results from create-sibling-ria --recursive

datalad/customremotes/tests/test_ria_utils.py
The parameterized tests in test_ria_utils that are SSH-dependent wrap
the inner test function in skip_ssh(), but the tests may still error
in cases where skip_ssh() would skip the test (*) because SSHRemoteIO
instance is created within the top-level generator function.  Delay
creating the instance until inside the main test function.
(*) https://github.com/datalad/datalad-extensions/runs/648105587
=> TST: ria_utils: Delay instantiation of IO class to allow SSH skip

datalad/core/distributed/push.py, datalad/support/annexrepo.py
Until now it would only create individual progress bars for items that
git-annex would report progress about. This change adds an additional
global progress bar that counts the number of results, if a total number
of expected results was provided.
This fixes gh-4501
Or rather, it fixes the underlying desire to see something happen, it
won't change how and when results are emitted.
=> ENH: Overall progressbar for AnnexJsonProtocol

datalad/distributed/tests/test_ria_basics.py
Use binary data from github
prior version of test depends on accessibility of an
annex remote hosted in Jülich. Seems to have some kind
of connection issue. Data for this test, however, is
completely irrelevant as long as it's binary.
- Closes #4371
=> Fixing issue 4371 (fragile test case)

README.md
The Handbook URL anticipates a change in the handbook that will come
shortly. https://github.com/datalad-handbook/book/pull/484
Fixes gh-4490
=> DOC: Strip outdated extension list and refer to handbook

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
As described in d46846716 (DOC: addurls: Clarify what filename format
is relative to, 2019-08-02) and the tests, the file format is intended
to be taken relative to the dataset.  However, when the file name
format begins with "./", we keep "./" on the relative name, while
constructing the absolute file name without the subdirectory as
documented.  The relative file name is passed to AnnexRepo.addurl(),
causing the file to be treated as relative to the current working
directory and downloaded there.
Achieve the documented behavior by applying the same handling to the
top-level dataset as we use for subdatasets.
Note that there is mention of changing this relative path handling in
gh-4498.  Even if we decide that this change in behavior is
worthwhile, it still makes sense to fix this bug, …
=> addurls: Don't trip over "./" in the file name format

datalad/tests/test_archives.py
All of the checks of the test generator fail on a system without
p7zip.  Before gh-4041 (in particular, before beb5d045e), the subset
of checks that existed at that time was skipped with (see gh-3176):
SKIP: cmd:7z is missing. (Not) Funny enough but ATM we need p7zip
installation to handle .gz files extraction 'correctly'
However, with the change to the archive file name in 05e9353d7 (TST:
Expand test coverage to additional relevant compression formats,
2020-01-17), the MissingExternalDependency exception that led to the
skip for gzip formats is no longer triggered.  And even if it were,
the other file formats tested would fail.
Mark these tests as known failures when p7zip isn't available.
=> TST: archive: Skip tests that depend on p7zip

datalad/downloaders/base.py
I think this is Closes #4532 unless we decide to implement some actual change in behavior.
=> ENH: debug log about lock before getting it

datalad/support/network.py, datalad/support/tests/test_network.py
this should be sufficient to address https://github.com/datalad/datalad/issues/4489
to avoid treating such RIs as ssh addresses.  Current implementation of
GitTransportRI simply splits apart transport and underlying RI attributes.
Since directed toward maint I have refrained from doing any code refactoring, such as
in RI().__init__ and in the tests check() to avoid using "ri" (and other) arguments
which might collide with fields provided in **kwargs.  May be in some next sweep
those all could become prefixed (or suffixed) with  _ to avoid such collisions.
We could also make this GitTransportRI immediately turn underlying RI into an
instance (ATM it is just a string), and also expose .path as all other RIs
apparently do.  But again, for the sake of the quick fix for now to not cause
hard …
=> BF: introduce GitTransportRI - a basic implementation only

datalad/core/distributed/push.py
```
% datalad push --to mike
[ERROR  ] Unknown push target 'mike'. No targets configured in dataset. [push.py:__call__:200] (ValueError)
% datalad push --to mike
[ERROR  ] Unknown push target 'mike'. Known targets: 'localtmp'. [push.py:__call__:200] (ValueError)
```
Fixes gh-4506
=> BF: Fail early on push to unknown target.

datalad/downloaders/http.py, datalad/downloaders/tests/test_http.py, setup.py
absorbs #4540 . 
Individual commits provide more info but here is two major summaries:
commit d366600f04c3f9739e75a6ba66a9feae76cfb651
ENH: reenable testing using httpretty (and other tests)
Apparently we had the entire test_http disabled due to httpretty not supporting
python3 in the past.  That masked some bugs in our code which need to be fixed up
(done in prior commit) and minimal compatible version of httpretty
verified.
0.9.4 seems to work fine for me in conda environments with python 3.6
and 3.8.
The only leftover inconvenience (does not cause failed tests) is a
complaint from cookies upon exit:
https://github.com/datalad/datalad/issues/4542
commit 3b55eb4e9d23fc22d175b0cfa9f1a8320b2258be
BF(TST): http - compare content to bytes not string
In …
=> BF: http - fix handling of fetched in bytes content, re-enable testing using httpretty

datalad/core/local/diff.py
In all such cases the comparison is made with respect to a recorded
state, so that any worktree inspection can be completely avoided.
This can lead to substantial speed-ups in large dataset hierarchies,
and helps to mitigate the needs for alternatively tailored `diff`
implementations, such as the one proposed in gh-4507.
=> ENH: Disable full submodule evaluation for diff(to=!None)

datalad/core/distributed/push.py
Previously this was done in the initial `diff()`. This is often not
needed (e.g. `--force no-datatransfer`), and it is also too expensive,
because diff will obtain annex info twice (for 'from' and 'to' state of
the diff, while `push()` only cares about the 'to' state).
Now it is done only once, and at the latest possible stage.
The change includes a TODO note with further optimization possibilities
that need further investigation.
=> ENH: Delay query of `get_content_annex_info()` in `push()`

datalad/distribution/tests/test_create_sibling.py, datalad/interface/tests/test_unlock.py, datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
test_failon_no_permissions() is failing on master's 'sudo -E' cron
build (*) because, not surprisingly, the "no permissions" error that
the test looks for is not raised.  The entire purpose of this test
isn't relevant when running under sudo, so skip it.
Note that this failure is specific to master.  Before 154e22281 (TST:
create-sibling: Extend some existing tests to test local paths,
2020-02-24), the test was restricted to an SSH target, and all
SSH-based tests are already disabled for the 'sudo -E' build.
(*) https://travis-ci.org/github/datalad/datalad/jobs/684799579#L1117
=> create-sibling: Skip permissions test when running under sudo

datalad/core/distributed/push.py, datalad/log.py
It makes it more obvious what is happening, and also exposes the
processing of publication targets.
This could also be a model for other commands, where presently
`lgr.info()` calls serve this purpose -- which annoyingly interfere
with progressbars and result rendering.
In combination with #4544 and #4545 it looks like this:
=> ENH: Give insight in push progress with a step-based progress bar

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
This implements the conclusion in the issue discussion of gh-4508 and thereby fixes gh-4508.
This PR sits on top of #4545 (essential) and #4546 (to limit unavoidable conflicts).
In all cases with no `path=` argument given to `push()` this change avoids an expensive content availability check that can make the difference between minutes and hours of processing large N datasets.
The relevant commit is https://github.com/datalad/datalad/commit/ef04b1e50d8418eb001329d19c578ef2040e9df3
=> ENH: Only evaluate and warn about content availability with explicit paths

datalad/interface/base.py
```
containers-run builds ContainersRun._params_ from Run._params_ to
extend run's interface with container-specific parameters.  In doing
so, it (presumably unintentionally) populates ContainersRun._params_
with parameters from eval_params because build_doc() modifies
Run._params_ in place.
Having eval_param keys in ContainersRun._params_ doesn't currently
cause any issues because build_doc() does a blanket update of _params_
with eval_params, but a proposed change to build_doc() in gh-4480
shows how this can fail.
Explicitly document this behavior to make it clear to callers that
they can rely on it and to prevent future build_doc() tweakers from
unknowingly changing it.
```
Supersedes datalad/datalad-container#119.
---
This will likely create a conflict with whatever eventually lands …
=> DOC: build_doc: Document eval_params/_params_ override behavior

datalad/core/distributed/push.py, datalad/core/local/diff.py, datalad/core/local/tests/test_diff.py
`diff` treats `fr=None` as a diff-from-scratch. However, when recursing
into subdatasets it breaks this paradigm by translating this into
`fr=PRE_INIT_COMMIT_SHA`. This can lead to a needless call to
`AnnexRepo.get_content_annexinfo()`. This changes rectifies that by
using `None` also for subdatasets.
Moreover, `push` uses `diff(fr=since)`, which can also be `None`. This
change also avoid an equivalent needless call for a top-level dataset.
=> ENH: Avoid needless calls with diff(fr=None, annex=!None)

datalad/customremotes/base.py, datalad/customremotes/tests/test_datalad.py, datalad/distribution/tests/test_install.py, datalad/interface/tests/test_add_archive_content.py, datalad/support/annexrepo.py
I just saw it in https://github.com/datalad/datalad-extensions/runs/665491656?check_suite_focus=true
which I believe failed for other reasons (but may be not), that there was a traceback
to this line.  And indeed above we might ask for a 'key' or a 'file', so hypothetically
there might be no 'key' field.  I have not really analyzed situation on how we have not
hit it before and how it really emerges in that failure while testing against
bleeding edge git annex
=> BF: use '' as default (not None) while checking for a key not to be a test key

datalad/ui/dialog.py, datalad/ui/tests/test_dialog.py
It is hard to impossible to troubleshoot failures of datalad in automated
deployments where we want to ask some question for some reason, but UI simply
does not support that since it is rightfully silent/non-interactive.
See e.g. https://github.com/templateflow/templateflow/issues/50 .
With this PR we would still fail but with a little more informative RuntimeError,
instead of obscure AttributeError stating what was actually asked.  We will not
disclose possible present other fields other than question and title if it was a
question asking for secret information ("hidden").  AFAIK in our use of the dialogues
we do not disclose any sensitive information in title or the question but I could be
proven wrong.
I did position this one on top of maint since might benefit people using released …
=> RF: throw dedicated RuntimeError with information about question in case of SilentConsoleLog

datalad/log.py, datalad/ui/dialog.py
This is an excerpt from gh-4444 that solely addresses the suboptimal interaction of result reporting and progress reporting that is presently evident in `push()` usage.
The idea is to clear any progressbar(s) before rendering a result with `ui.message()` and afterward refresh the progressbar(s). With this approach results will appear above any active progress bar in the terminal and do not get half-swallowed by a progress update.
https://github.com/datalad/datalad/pull/4444#issuecomment-620285637 outlines an additional improvement that addresses the analog issue for the interaction of log messages and progress reporting, also pointed out by (but unaddressed in) gh-4444. However, that solution can be seen as an incremental step that should not delay the fix contained herein.
@kyleam this …
=> BF: Prevent ugly interaction or result and progress reporting

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py
publish() fetches the sibling before pushing, and has done so for a
long time (f07fc5194, 2017-08-26).  If the fetch brings down a
recorded submodule commit that is not yet present locally, by default
git also fetch in the submodule with the missing commit.
This is problematic because, as explained in dbd84e5662 (ENH: update:
Try to fetch submodule commit explicitly if needed, 2020-02-07),
submodule.c hard codes 'origin' as a fallback to fetch from, so the
fetch will fail unless there's a remote named 'origin'.  Also,
conceptually, the goal of this fetch seems to be to obtain up-to-date
information on the current repository, not its submodules, which
publish() will handle itself if called with --recursive.
Fetch with --recurse-submodules=no.
=> BF: publish: Tell git-fetch to not recurse into submodules

datalad/support/tests/test_sshconnector.py
test_ssh_git_props() asserts that the ssh://localhost git-annex
version is equal to the version in external_versions.  However, those
versions don't necessarily match.  For example, the local user could
be running a git-annex from conda while the git-annex used by
ssh://localhost is from NeuroDebian.  And if in the future we move
away from a localhost target (e.g., gh-4514), there is no reason to
expect the versions to match at all.
Replace the more specific version assertion with a check that some
output is produced, as is already done for the SSH git version.
Fixes one part of gh-4554.
=> TST: sshconnector: Loosen assertion about SSH annex version

datalad/support/tests/test_sshrun.py
```
As mentioned in the comment, this test assumes the target has
`AcceptEnv LC_*` configured.  Instead of failing when that's not the
case (or dropping the test entirely), skip the test if the output is
an empty string, which probably means `AcceptEnv LC_*` isn't set.  (It
could also be an indication that things aren't wired up correctly in
sshrun, but this probably isn't worth worrying about given our test
environments have are configured to accept LC_ variables.)
Fixes one part of gh-4554.
```
---
There is also a commit that cleans up an unintentional comment.
Pointing the test to a docker target configured to _not_ accept `LC_` variables, I've confirmed that the test is skipped (and that it fails with the same error as shown in gh-4554 before this change).
=> TST: sshrun: Don't fail if target doesn't accept LC_* variables

datalad/support/due_utils.py, datalad/support/tests/test_due_utils.py
Grave problems (exception raised) would still be logged but now at DEBUG not WARNING level if needed to debug.  The other warnings etc would be completely swallowed (FWIW - tried but decided to not over-complicate code there to try to log them after being swallowed).
Closes #4562
=> ENH(UX): silence datalad's metadata while querying for possible metadata for duecredit

datalad/distributed/ora_remote.py
`annexremote` changed two things in most recent 1.4.2:
- special remote protocol's LISTCONFIGS is now supported and yields an actual response rather
the former UNSUPPORTED REQUEST. If we don't declare configs we use w/ `initremote`, annex
will now retrieve an empty list
- `annexremote.Master.protocol` turned ~private~ protected
In addition git-annex 8 (used in github Action workflow) apparently now requires configs for `initremote` to be listed, if the response isn't UNSUPPORTED REQUEST. In combination with above change in `annexremote` this currently leads to all `initremote` calls for ORA to return non-zero "Unexpected parameter: url".
This PR fixes those failures (without changing dependencies).
=> Fix ORA for recent annex/annexremote

datalad/ui/dialog.py, datalad/ui/tests/test_dialog.py
b7e57dfa2 (BF: Prevent ugly interaction or result and progress
reporting, 2020-05-20) taught message() to clear progress bars before
showing its message, refreshing them after.  For non-interactive
operations (e.g., piping datalad output), that dumps a lot of these
irrelevant messages to the caller.
Hide these away by using noninteractive_level to filter them out
unless the logging level is a very noisy 5.
Closes #4570.
=> ENH: ui.message: Hide non-interactive log_progress output by default

datalad/distribution/publish.py
A very small RF, decided just to have it done while spotted.
There should be no change in behavior or log output.  Minor additional OPT is not
doing string interpolation for lgr.info
=> RF: publish - remove code duplication for publishing data to dependencies and target repo

datalad/core/distributed/clone.py, datalad/customremotes/ria_utils.py, datalad/distributed/ora_remote.py, datalad/distributed/tests/test_ora_http.py
Implements HTTP support for the ORA special remote (read-only for now).
Closes #4410
In opposition to local and SSH, everything is supposed to happen server-side. ORA sends a request to e location of a key. This location is based on resolved RIA URL to the dataset and assumes dirhashmixed with its `annex/objects` tree. Remapping based on a different layout and archive access needs to be done by the server (That is what PR #4572 is for).
=> ENH: HTTP for ORA special remote

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/interface/common_cfg.py
Rename push(force='all') -> push(force='pushall')  to better forward-compatibility.
This also adds the implementation of the conclusion of a discussion on this topic. Follow-up to gh-4541.
Add --auto to `git annex copy` if `datalad.push.copy-auto-if-wanted` is set, and `--force datatransfer` isn't given.
Fixes gh-4550: --auto is never added, unless requested via config
Fixes gh-4551 and fixes gh-4483: now obeys distribution-restrictions in a "default"  `datalad push --to target` if configuration says so (not the default (yet?))
TODO:
<details>
<summary>Script to play with the changes</summary>
```sh
#!/bin/bash
export PS4='> '
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
set -x
datalad create src
(
cd src
echo -e '\x00' > data.0
echo -e '\x01' > secure.1
echo -e '\x02' > secure.2 …
```
=> Finishing touches to `push` for 0.13

datalad/core/distributed/tests/test_push.py
`create-sibling`'s way of enabling post-update hook fails on
crippled FS/Windows. Test itself is about testing wanted
configuration, so no apparent need to run it on crippled FS
anyway.
=> BF: Disable test_push_wanted on crippled FS

docs/source/metadata.rst
The metadata section of the manual describes using the
distribution-restrictions field to mark files that shouldn't be shared
publicly. As described at gh-4605, this setup depends on the caller
not configuring numcopies to a value above the default of 1 (or, less
likely, configuring required content in a way where the public remote
would want the file).
=> DOC: manual: Warn about distribution-restrictions interactions

.github/workflows/test_crippled.yml, datalad/interface/common_cfg.py, datalad/tests/test_utils_cached_dataset.py, datalad/tests/utils_cached_dataset.py
Inspired by discussion in https://github.com/datalad/datalad-extensions/pull/12 and internal chat.
This allows to use remote datasets in tests via a cache, in order to reduce time and network traffic.
The goal is to replace the original remote repository (specified by a URL) by a local clone in a caching location. From the point of view of a test, this is kind of transparent - the cached dataset simply replaces the actually remote one. It introduces a config variable `datalad.tests.cache` to specify the caching location or disable caching entirely. Default location is `<user's cache dir>/datalad/tests`, which would result in datasets used by tests that way being persistent across test *runs*, not only across tests! This should be convenient for ourselves and irrelevant in CI builds, where …
=> ENH: dataset cache for tests

datalad/support/exceptions.py
Someone recently had asked me why we are not having "multiline" exception renderings... and I forgot what actually was the reason for us (may be if only for logging) why we leaned toward one liners.
I think the change is trivial enough to be submitted against maint.
ENH: Use pprint.pformat for IncompleteResultsError str
Those are are now more rare but when they come, they become hard to parse visually,
see e.g. one in https://github.com/datalad/datalad/pull/4581#issuecomment-636239700 .
With pprint they become much more human friendly/informative even though might occupy
considerable amount of terminal output space.
E.g. here is the exception from that issue pprinted
ERROR: test.test …
=> ENH: (+minor DOC fix) pretty print IncompleteResultsError

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
Implements the decision made in gh-4582 to use this character as a more
intuitive alternative than an empty string.
Fixes gh-4582
=> RF: `push since=''` -> `push --since='^'`

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/get.py, datalad/distribution/tests/test_get.py
This is achieved by prefixing their existing label with three digits and sorting them before processing them.
This implementation makes no change to the previously established order, it just makes that order explicit in the labels.
The default setup uses the priorities in the second half of the spectrum:
- 500 for remote URL + submodule path
- 600 for the configured submodule URL
- 700 for any unprioritized 'datalad.get.subdataset-source-candidate' config
- 900 for the local subdataset path
The first half of the spectrum and the spaces inbetween are available for re-prioritizing clone attempts. The idea is to be able to configure
`datalad.get.subdataset-source-candidate-000takemefirst = http://some`
and have this be processed first.
I have confirmed manually that this solution enables …
=> ENH: Give clone candidates a priority

.travis.yml
The `npm install grunt-contrib-qunit` call has started to fail (e.g.,
<https://travis-ci.org/github/datalad/datalad/jobs/699391908>).  This
is presumably due to the v4.0.0 release today.  Pin it to the previous
release.
Re: #4635
=> TST: travis: Pin grunt-contrib-qunit version to avoid failure

datalad/core/distributed/tests/test_clone.py
test_clone_unborn_head() is supposed to set up a scenario where the
freshly cloned repo has a master branch with no commits and three
non-master remote tracking branches, including origin/git-annex.  As
of 8f5cc450c (ENH: clone: Try to switch away from an unborn branch,
2020-04-01), clone() handles this situation by checking out the
non-git-annex ref with the most recent committer date.
With Git v2.27.0, specifically 7c5045fc18 (ref-filter: apply fallback
refname sort only after all user sorts, 2020-05-03), this test fails
intermittently.  The failure is due to a bad approach in the test: it
commits a change to the abc branch and then one to the chooseme
branch, with the hope that chooseme will have the later committer
date.  Given the resolution of Git time stamps, though, both refs can …
=> TST: clone: Fix clock-dependent test

datalad/support/external_versions.py
This is useful information to include in the wtf output, especially
since 1.4.2 required some adjustments on our end (gh-4573).
---
I noticed this was missing when glancing at the wtf output in gh-4643.
=> ENH: external_versions: Consider annexremote interesting

datalad/ui/progressbars.py
As of c9a066c49 (ENH: Enable changing the total of an existing
progress bar, 2020-04-22), our tqdmProgressBar.update() relies on tqdm
having reset(), but reset() didn't exist until v4.32.0 (c7015f4,
2019-05-10).  Debian Buster currently has v4.28.1.
For compatibility with older versions, copy over the logic to
tqdmProgressBar and fall back to it when tqdm.reset() isn't available.
All of the attributes adjusted in reset() appear to be in v4.28.1 and
manual testing with v4.28.1 didn't reveal any issues.
There is of course some older version that this won't work for, but it
looks like we'll hit other problems before that point.  We rely on
refresh() throughout tqdmProgressBar, and all of the other attributes
used in _reset_kludge() appear to have been around before refresh()
was added …
=> BF: progressbar: Add reset() kludge for older tqdm versions

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/interface/common_cfg.py
This is an implementation for #4604 .
Notes:
- it is not harmonized with `publish` or `get` (see #4604 for notes on that)
- from Python programming side perspective I do dislike that we cannot say `data=True` or `False`. `data='nothing'` is not worse IMHO though than `force=['no-datatransfer']` though.
-  `--force=checkdatapresent`  (resolves #4603) in b20ed1379da540621e48a1515191a9ea32ae258f
- `--force=all` instead of `--force=pushall` in 65aae48ef0cee708a7e0fee89f076b152b64eef2 since IMHO forces should be orthogonal and could all be combined
- Closes #4602 which was an alternative proposed solution (`--force=onlywanteddatatransfer`)
- Removed `datalad.push.copy-auto-if-wanted` config adding a mode `auto-if-wanted` (1be419f0483dde6db939b2263bdbcf3d355dafb5) and making it to be default …
=> ENH: specify `push` --data modes; keep `--force` to only force git push and checkdatapresent

datalad/support/gitrepo.py
#2054 made me look into this code path.
Possible changes to consider
- make `._get_dot_git` public so it could be used instead of `.get_git_dir`, thus not requiring an instance if that seems needed; but I think it better be delayed until we know that such functionality is really desired
For now I just position it against master (thus for 0.13) but if we feel that better be delayed, I will reassign milestone and finally produce `next` branch ;)
=> RF: Make .get_git_dir to use .dot_git logic, prepare for possible deprecation of .get_git_dir

datalad/core/local/run.py, datalad/interface/run_procedure.py, datalad/support/annexrepo.py, datalad/support/archive_utils_7z.py, datalad/support/exceptions.py, datalad/tests/test_utils.py, datalad/utils.py
Spotted the need while reviewing #4586 
from the 2nd commit message:
Also includes a change to output produced by
def _format_cmd_shorty(cmd):
"""Get short string representation from a cmd argument list"""
which used to join then without quoting
cmd_shorty = (' '.join(cmd) if isinstance(cmd, list) else cmd)
I thought that quoted would be more correct, especially when it is not
going to get shortened.
I think the name `join_cmdline` is Ok, but could have been `join_argvs` or `join_commands`.  Let me know if you feel it better be renamed.  Originally I thought to make it `quote_cmdlineargs` but it doesn't fit semantically since it also joins them into a string
=> ENH: join_cmdline to complement split_cmdline which uses quote_cmdlinearg

.travis.yml, datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_save.py, datalad/distribution/tests/test_update.py, datalad/support/annexrepo.py, datalad/support/exceptions.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/test_config.py, tools/ci/install-minimum-git.sh
This series sets a minimum Git version (currently v2.19.1, as suggested in gh-4636), and adds a cron build to test against it.
---
v2.19.1 will hopefully pass because [v2.13.0 fared okay][0], though the tests needed a couple of skips for behavior that changed with v2.13.2.  The idea with that test is to get an idea of what our functional minimal version is at this point, regardless of whether we choose a higher floor.  I chose v2.13.0 because it is the earliest version that I didn't find issues with when testing locally.
https://travis-ci.org/github/datalad/datalad/builds/701074711
My current thinking is that we should target this series for 0.13.1.  Instead of aborting if an unsupported version is detected, we should just tell the user via `warnings.warn` that v2.19.1 (or whatever …
=> Declare minimum supported Git version

datalad/distributed/tests/test_ria_basics.py
See the bugreport
https://git-annex.branchable.com/bugs/testremote_breeds_way_too_many_instances_of_the_externals_remote/?updated
for more information.
=> BF: skip running testremote with recent not yet fixed up git-annex

datalad/distributed/tests/test_ria_basics.py, datalad/tests/test_utils_cached_dataset.py
Since they all rely on access to a github repository ATM.
See https://github.com/datalad/datalad/issues/4653 for a possible RF to avoid that
=> BF: annotate tests in test_utils_cached_dataset with @skip_if_no_network

datalad/core/distributed/clone.py, datalad/distribution/get.py, datalad/distribution/tests/test_get.py
```
Cloning a subdataset is supposed to inherit the parent's
`datalad.clone.reckless` value.  This works as intended when using
install() to get an existing dataset or using clone() to create a new
subdataset, but the parent's configuration is ignored when the clone
is triggered by get().
The "inherit reckless" logic is handled in Clone.__call__(), but
that's upstream of clone_dataset(), where get() hooks into.  Move the
handling into clone_dataset() to avoid repeating it in get().
Note that we don't have access to the parent dataset in
clone_dataset(), but we need to query its configuration.  We could add
the parent dataset as a parameter.  However, there's already a cfg
parameter, and Clone.__call__()---the only caller that specifies
cfg---passes the parent's configuration.  So instead …
```
=> BF: get: Inherit reckless configuration when cloning subdatasets

datalad/tests/test_utils.py
This is the only test left failing after adding `distro` (see #4659)
=> ENH(TST): use assert_equal to see why conda python 3.8 tests fail

datalad/interface/utils.py
Example use case: credential query
(datalad/datalad-osf#105)
There is nothing on the file system that such credentials are (or have
to be) associated with.
Before this change, the default result handler would crash on results
without a `path` key. After this change, it merely doesn't report a
path at all. Spacing is adjusted be
`<action>(<status>): [<message>]`
in this case.
=> ENH: Let default result renderer tolerate non-path results

.travis.yml, datalad/tests/test_utils.py
* gh-4659 pointed to a failure in the conda py3.8 runs.  Before Python 3.8 was released, we tested against 3.8 on Travis and fixed up the issues at the time, but we didn't add as a regular job.  Add it now, demoting the 3.6 job to a cron job so we don't increase our testing time.
* ~Restrict the cron builds to `_DL_CRON=1` jobs.~
=> travis: Add job for python 3.8, restrict cron

datalad/support/gitrepo.py
Previous setup assumed that any `git-push` error is an orderly
report that could be forensically analyzed. However, in particular
with custom remote helpers, `git-push` can also just crash, and
there is no guarantee that we can inspect anything.
This is a minimal change that makes sure the `CommandError` bubbles
up, when we know that something is fundamentally not right, because
there was an error, but the expected error message channel is empty.
In all likelihood that is still far from comprehensive, but still better
than before.
=> BF: Do not hide `git-push` crashes

datalad/core/distributed/push.py, datalad/interface/utils.py
The employed `relpath` call cannot handle it.
Also remove the condition that triggered the specific observed crash
that prompted this change -- push was not reporting the dataset path
in question for one of its errors.
=> BF: Do not fail result rendering with no `path` but `refds`

datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
Most of the hanging we were seeing with recent git-annex versions was recently fixed by git-annex's [8.20200617-134-gf912f8e5f](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=f912f8e5f) (refix bug in a better way, 2020-07-02, [bug report][0]).  That affected a good number of SSH tests.  This series should avoid the remaining stalls.
```
[1/4] CLN: test_annexrepo: Prune unused imports
[2/4] CLN: test_annexrepo: Merge a near-duplicate test
[3/4] TST: annexrepo: Clear repo instances when testing shared connections
[4/4] TST: with_sameas_remote: Skip on older systems
```
The first two commits are test_annex cleanups, followed by a commit that fixes our connection handling in `test_annex_ssh` and removes the skip added in gh-4288.
The final commit deals with a remaining [hang][1] …
=> Avoid SSH-based stalling with recent git-annex versions

datalad/core/distributed/push.py
This change adds the required conditionals to re-use the results
of an identical `push --dry-run` that figures out which refs to push
-- that always did already happen, when the remote itself was discovered
via a dry-run.
=> OPT: Avoid unnecessary `push --dryrun`

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
URL-FILE can be a csv file or a JSON file with an array of records.
To allow the user to supply records on stdin, avoiding an intermediate
file in some cases, read from stdin when URL-FILE is "-".
There are two main options for the JSON input on stdin: JSON lines or
a JSON array.  Go with an array, which has the advantage that it
matches what addurls expects for a JSON file, which is good for both
user expectations and not introducing divergent code paths.  It also
makes it clearer that addurls slurps all the records into memory
rather than working with them as they come in. The disadvantage is the
need for another intermediate reformatting step, though it's trivial
to reformat JSON lines as an array with jq or similar tools.
The --input-type default value is "ext", which means to infer …
=> ENH: addurls: Support reading records from stdin

.travis.yml
This PR unpins `grunt-contrib-quint` dependency, allow TravisCI pulling the latest version of the aforementioned package.
Fixes #4635
Please also note, that instead of reverting to
```bash
$ npm install grunt-contrib-quint@>=2.3
```
This PR currently modified it to
```bash
$ npm install grunt-contrib-qunit@^4.0.0
```
This should install latest minor version (similar to grunt-contrib-qunit>=4.0.0 < 5.0.0), which would hopefully reduce the flakiness of tests should a major version arrives in the future.
This PR supercedes #4686
=> Bugfix unpin grunt contrib qunit

appveyor.yml
ATM it fails unconditionally, and obscures the reporting of actual test
failures. Until this can be investigated there is no point in keeping it
fail.
=> TST: Disable coverage submission on appveyor

datalad/core/distributed/push.py, datalad/support/gitrepo.py
As noted in gh-4667, `GitRepo.push()` can actually do all at once.
It just claimed not to be able to. Fixed the docs, and adjusted
the call to the method in the `push()` command.
=> OPT: Avoid multiple calls to `git-push` with multiple refspecs

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/support/gitrepo.py
Instead of splitting between regular branches and the git-annex branch, in order to improve efficiency -- in particular with expensive operations in custom git-remote-helper implementations.
Fixes gh-4667
This PR includes #4692 which is a related, but more focused optimization that was proposed for inclusion into `maint`.
=> OPT: Consolidate on a single `git-push` call in `push()`

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
I had forgotten that it got a new magical `^` to operate since the last published state, so ran it (`datalad push --data auto --since= --to=datalad-public -r`) and was confused with all the progress bars (about to transfer 140G etc... disappeared quickly though... some separate issue probably to demonstrate/file) and only then remembered:
```
--since SINCE         specifies commit-ish (tag, shasum, etc.) from which to
look for changes to decide whether pushing is
necessary. If '^' is given, the last state of the
current branch at the sibling is taken as a starting
point. Constraints: value must be a string
```
but I wonder if we should explicitly check if value is not an empty string (not `None`) and fail
Positioned against `maint` since an empty string doesn't match documented allowed …
=> ENH(UX): explicitly disallow empty string for --since in push

datalad/cmd.py
Instead, adjust the current environment, as needed, at the time of
each `run()` invocation -- like `GitRunner()` does it.
This avoids silently ignoring changes in the process environment
after a `GitWitlessRunner` instance was created.
Fixes gh-4702
I will try this out in the context of #4699, which is an ideal testbed, due to the long-running `ConfigManager` instance.
=> BF: Do not maintain an environment copy in GitWitlessRunner

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/utils.py
Those are too expensive to assign a proper value on recent Pythons where
we have to use distro (see https://github.com/datalad/datalad/issues/4690).
on_debian_wheezy was not used anywere in this code base and cannot be True these days
anyways since wheezy EOLed 2 years back, and we do not even provide backports of datalad
for it from neurodebian.
The other variables were used only for a better git-annex installation
suggestion message -- we might want to get away from that and just refer to
installation instructions anyways, but or now I just kept it around.
Even though these changes can possibly considered a "breakage", I think the
actual breakage of anything is very unlikely since code should not really rely in any
critical functionality on what distribution and its release it is …
=> RF/OPT: just assign None to linux_distribution*, and False to on_debian_wheezy

datalad/support/tests/test_annexrepo.py
test_annex_ssh used to be skipped for newer git-annex versions, but
that skip was just recently removed in 760c8075f (TST: annexrepo:
Clear repo instances when testing shared connections).  That commit
pointed to a passing build [0].  Checking that build again, it does
look good: it gets through the entire test suite, including
test_annex_ssh, *on Xenial* with a very recent git-annex.
Nevertheless, test_annex_ssh has since shown a failure on Xenial but
not on Bionic [1].  Based on a few runs, the stall is consistent, so
it's not clear what's going on.
In a Xenial VM, I bisected the stall to git-annex's 75059c9f3 (better
error message when git config fails to parse remote config,
2020-01-22).  I've opened a git-annex report about that commit [1],
though it's possible that the reproducer …
=> test_annex_ssh: Skip with older SSH versions

datalad/tests/test_config.py
otherwise we manipulate the env for other tests, too,
which at least leadds to confusing observations when
debugging other tests.
=> BF/TST: Patch env for test only

datalad/support/sshconnector.py
Do not stringify what doesn't need to be -- we have more clever
rendering now, than we had when this was written.
Turns
```
ConnectionOpenFailedError: ''['"'"'ssh'"'"', '"'"'-fN'"'"', '"'"'-o'"'"', '"'"'ControlMaster=auto'"'"', '"'"'-o'"'"', '"'"'ControlPersist=15m'"'"', '"'"'-o'"'"', '"'"'ControlPath=/media/mih/Samsung_T5/tmp/datalad_temp_ml_70qcw/.cache/datalad/sockets/6258b3a7'"'"', '"'"'localhost'"'"']'' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]']
```
into
```
ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/media/mih/Samsung_T5/tmp/datalad_temp_01cz4bxi/.cache/datalad/sockets/6258b3a7 localhost' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster …
```
=> BF: Readable SSH error messages

datalad/__init__.py, datalad/core/distributed/tests/test_clone.py, datalad/core/distributed/tests/test_push.py, datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_run.py, datalad/core/local/tests/test_save.py, datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py, datalad/distribution/tests/test_update.py, datalad/interface/tests/test_ls.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_rerun_merges.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/utils.py
This draft series prepares our tests for an in-flight series in Git that makes the default branch name configurable.  ~Locally I ran specific tests with v2.27.0-92-gb5081fbf16, but I didn't do a full test sweep.~ The temporary tip commit sets up a [Travis job][0] with 2.27.0.92.g0068f2116e, the corresponding git.git series.  Anyway, this of course needs to wait for things to land on Git's end, but it gives a sense of the spots that will likely need to eventually change.
The first commit (c4578fc6a) contains for more information about the plans on Git's side.
[0]: https://travis-ci.org/github/datalad/datalad/jobs/704052356
=> TST: Avoid hard coding the default branch

datalad/utils.py
Rational: We are using TMPDIR in quite a few places to direct where
tests do IO (to have pathnames with spaces, symlinks, different
filesystems, etc.). However, setting TMPDIR did not affect
paths created by our own test helpers. For example:
```
TMPDIR=/tmp/dltest DATALAD_TESTS_TEMP_KEEP=1 python -m nose -s -v datalad
[INFO   ] Keeping temp file: /tmp/datalad_temp_get_most_obscure_supported_name4v4gmbdq
[INFO   ] Keeping temp file: /tmp/datalad_temp_e3h1pw_e
...
```
This change rectifies this (and with it might reveal other issues):
```
TMPDIR=/tmp/dltest DATALAD_TESTS_TEMP_KEEP=1 python -m nose -s -v datalad
[INFO   ] Keeping temp file: /tmp/dltest/datalad_temp_get_most_obscure_supported_namej5wa186s
[INFO   ] Keeping temp file: /tmp/dltest/datalad_temp_pf8hschp
```
=> TST: Honor TMPDIR if DATALAD_TESTS_TEMP_DIR is not defined

datalad/tests/test_tests_utils.py
I'd argue that the test remains about as useful as it was before.
Fixes gh-4723
=> BF: Test inferred filesystem properties from platform name

datalad/tests/test_tests_utils.py, datalad/tests/test_utils.py
Use actual failure to create on as the indicator that it isn't possible.
Inference based on platform name, or `os.symlink` availability isn't
reliable enough.
Fixes gh-4719
Fixes gh-4718
Fixes gh-4715
=> TST: Robustify tests that rely on symlinks

tools/ci/install-annex.sh
In addition to release-timed snaphots, https://downloads.kitenet.net
also hosts autobuilds that are frequently built from the tip of
master.
---
=> TST: install-annex.sh: Add support for git-annex autobuilds

datalad/distribution/create_sibling.py
The post-update hook installed by `create-sibling --ui ...` constructs
a log file name using a second-resolution `date` call.  For normal
use, consecutive updates are unlikely to result in a file name
collision, but it can very easily happen in a test setting.
These collisions are very likely behind the intermittent failures that
have been happening in test_replace_and_relative_sshpath, where the
number of log files is coming up one short of the expected number
after a call to publish().
Check if the target file exists and, if needed, append a number.
Fixes #4741.
=> BF: create-sibling: Avoid overwriting existing web log file

datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
The hang of test_annex_ssh with older OpenSSH versions is addressed by
git-annex's cb74cefde (Fix a hang when using git-annex with an old
openssh 7.2p2, 2020-07-21).
The SSH-related hang of the rsync remote that led to
test_sibling_enable_sameas stalling is, for mysterious reasons,
resolved by 4c9ad1de4, which was a part of the 8.20200720 release.
And, if it resurfaces, it should be taken care of by the changes in
aa492bc65 (Fix a hang when using git-annex with an old openssh 7.2p2,
2020-07-22).
---
Passing build: https://travis-ci.org/github/datalad/datalad/builds/710837937
=> TST: Add upper git-annex version bound for two resolved SSH hangs

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py
Raise `NoDatasetFound` exception immediately, instead of letting
subsequent code fail in cryptic ways.
Fixes gh-4758
=> BF: Error handling when magic Dataset identifiers '^' and '^.' do not resolve

datalad/support/sshconnector.py, datalad/support/tests/test_sshconnector.py
`.close(ctrl_path=<str>)` hasn't closed the connection for the specified control path since the switch to using pathlib in the sshconnector module.
=> sshconnector: Fix regression in closing specified control path

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
These quick alternative checks yield invalid result on crippled FS.
Moreover, they are not used in non-test code.
Consequently, their removal should improve validity of tests without
impacting the performance of user-facing code.
Fixes gh-4714
=> RF+BF+TST: Discontinue "quick" annex (availability) checks

datalad/core/local/create.py
This applies the description improvements @kyleam and I discussed in  #4754.
Fixes  #4754.
=> DOC: Emphasize PATH in parameter descriptions of create

datalad/core/local/status.py, datalad/core/local/tests/test_status.py
This change avoids the [two failures][0] in the _DL_TMPDIR="/var/tmp/sym link" job that were triggered by running with a recent git-annex (gh-4756).
[0]: https://travis-ci.org/github/datalad/datalad/jobs/710485450#L7806
Passed: https://travis-ci.org/github/datalad/datalad/builds/710746293
=> status: Pass repo.pathobj-based paths to get_content_annexinfo()

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
Otherwise, such configuration could not be inherited to annex subdatasets, even if a plain-git superdataset may not be directly
affected by a particular reckless mode.
Fixes gh-4749
Also:
- RF'ed test to run on windows
=> BF: Store reckless config in no-annex superdatasets

datalad/core/distributed/clone.py
Witnessed: https://github.com/datalad/datalad/issues/4772#issuecomment-664821539
=> BF: Make error handling robust against stderr being None

.travis.yml, CONTRIBUTING.md, appveyor.yml, datalad/core/distributed/tests/test_push.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py, datalad/metadata/tests/test_aggregation.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_sshconnector.py, datalad/support/tests/test_sshrun.py, datalad/tests/utils.py, tools/ci/appveyor_ssh_config, tools/ci/prep-travis-forssh-sudo.sh, tools/ci/prep-travis-forssh.sh
This series adjusts the SSH-dependent tests to facilitate using a target other than localhost and switches Travis over to using a Docker target.  The motivation for this is to make it easier to run our SSH tests outside of Travis without requiring that the localhost allows SSH connections and maps datalad-test to localhost.  The new setup here can hopefully be adapted easily for use in the testing at datalad-extensions (right now those builds skip SSH tests).
I've been using an earlier iteration of this Docker container for a while to run our SSH-based tests locally, replacing "localhost" if present with "datalad-test" temporarily.
---
Things to do:
I thought I blindly worked around it in the commit marked with "[maybe]", but I've seen it since, so I guess that was a fluke.
This failure …
=> travis: Use a Docker target for the SSH tests

.zenodo.json, datalad/distribution/create_sibling_github.py, datalad/support/github_.py, datalad/support/tests/test_github_.py
This PR adds a new `--private` flag to the `datalad create-sibling-github` command that result in a GitHub repo being created that is only viewable by members that have been given access.
Created both public and private repositories successfully using the following
`datalad create-sibling-github --github-organization $TEST --access-protocol ssh --name $TEST --private  $TEST`
=> NF: create GitHub sibling as private repo

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
Otherwise `datalad get` fails to get content that is only in the
special remote and not known to the other remotes.
Fixes #2897.
=> clone: Fetch autoenabled type=git special remotes

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
This resolves gh-4780 by cherry picking a commit from @mih's gh-4693 and adding a regression test.
=> push: Transfer the git-annex even when --data=nothing

.travis.yml, datalad/__init__.py, datalad/core/distributed/tests/test_clone.py, datalad/core/distributed/tests/test_push.py, datalad/core/local/tests/test_run.py, datalad/distributed/tests/test_create_sibling_ria.py, datalad/distributed/tests/test_ria_basics.py, datalad/distributed/tests/test_ria_git_remote.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_publish.py, datalad/distribution/tests/test_update.py, datalad/interface/common_cfg.py, datalad/interface/tests/test_add_archive_content.py, datalad/interface/tests/test_ls_webui.py, datalad/interface/tests/test_rerun_merges.py, datalad/interface/tests/test_unlock.py, datalad/local/tests/test_copy_file.py, datalad/local/tests/test_subdataset.py, datalad/metadata/tests/test_aggregation.py, datalad/plugin/tests/test_addurls.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_fileinfo.py, datalad/support/tests/test_repo_save.py, datalad/tests/utils.py
Inspired by #4766 but took me too deep down the rabbit hole... with this PR I hope to "encourage" (well -- force) proper annotation of @slow tests:  I have provided an ad-hoc rule of thumb description for `@slow` tests -- those which exceed 10 seconds.  I have annotated the majority of those which exceed that timing on my laptop ATM. 
Travis run would fail if any test exceeds 30 seconds when ran in the matrix run which says "not slow". After we annotate all `@slow` and merge this PR, it could happen due to
- PR introduced changes making corresponding test considerably slower.  So either changes should be analyzed to avoid adding slow-down or the test annotated as `@slow`.  If a change caused **many** tests to exceed 30 sec, need even more seriously reconsider OPT **or** boost our …
=> ENH+OPT(TST): annotate more of @slow tests, provide rule-of-thumb doc for @slow/turtle/..., fail if any non @slow exceeds 30 sec on travis

datalad/downloaders/http.py
If a download of an ftp:// URL fails and `requests_ftp` is not installed, mention `requests_ftp` in the error message, as suggested by @nicholsn in gh-4787.
=> ENH: downloaders: Recommend requests_ftp on ftp failure

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
This fixes the test failure that @mih reported in gh-4727.  The first commit is the main fix.  It updates the test itself, which was setting up an unintended and bizarre repo state that happened to pass before Git 2.27.  The second commit prevents `postclone_check_head` from checking out adjusted branches.  Either of these commits on their own avoid the failure.
I've confirmed that the test passes when executed under `tools/eval_under_testloopfs` both before and after the git commit mentioned in that issue.
=> Fix test_clone_unborn_head_sub on a managed branch

datalad/core/local/create.py
Until now the dataset ID encoded the time of dataset creation, and  a machine-identifying MAC-address (which may or may not be a reliable/persistent identifier).
DataLad neither used, nor advertised this encoded information in the ID. Moreover, having such information unconditionally encoded can counteract other features (e.g. "fake dates").
I'd argue that if identifying information of this kind is desired, it should be placed explicitly into a dataset. If UUIDs with encoded content are desired, the UUID of a dataset can be altered (right after creation) to match such needs.
Fixes gh-4785
This issue is related to https://github.com/datalad/datalad-metalad/issues/30 and impacts the suitability of an identifier for use in anonymous metadata on personal data.
This PR goes against `maint`, …
=> Use a fully random UUID as dataset ID

CONTRIBUTING.md, MANIFEST.in
This PR adds a `MANIFEST.in` file to the project so that `_datalad_build_support/` (et alii) will always be included in sdists regardless of whether the sdists are built in an environment with `setuptools_scm` installed or not.  The file is written so that building an sdist should give the same results with & without `setuptools_scm` (until someone adds a new top-level file or directory, at least).  Read more about `MANIFEST.in` [here](https://packaging.python.org/guides/using-manifest-in/).
Closes #3808.
The decisions about what files to include & exclude in the sdist were based on my own personal packaging policies.  Rough rationales are as follows:
- Included files:
- `_datalad_build_support/` is necessary for building the project.
- `COPYING` and `CONTRIBUTORS` are included for legal …
=> Add MANIFEST.in to include _datalad_build_support

datalad/support/gitrepo.py, datalad/support/tests/test_fileinfo.py
get_content_info() relies on ls-tree showing an entry for a submodule
when given a path _within_ the submodule:
$ git ls-tree HEAD sub/file
160000 commit 05b9a93e327b959cd6ead46debf5f67cabab3a2a	sub
However, that longstanding behavior appears to be unintended
consequence of a fix to make 'ls-tree sub' and 'ls-tree sub/' return
the same result.  As of Git's 35a9f1e99c (tree-walk.c: don't match
submodule entries for 'submod/anything', 2020-06-05), the output for
the above command is empty.
That commit makes ls-tree match ls-files in how it treats paths within
submodules [*].  get_content_info() uses ls-tree when ref=None, so it
already has logic to map from sub-paths to submodules.  Reposition
that logic outside so that it can also be applied to paths destined
for ls-tree.
Closes #4681.
[*] …
=> BF: get_content_info: Account for change in ls-tree output

.travis.yml, CONTRIBUTING.md
8397bde59 (RF+ENH: unify and extend CMD execution logging - ENV, CWD,
STDIN now are options, 2017-04-07) added options for logging several
other aspects of command execution in addition to stdout and stderr.
_get_log_setting() was updated to look at datalad.log.cmd.<name>, and
the DATALAD_LOG_OUTPUTS environment variable in .travis.yml and
CONTRIBUTING.md was renamed to DATALAD_LOG_CMD_OUTPUTS to match the
new DATALAD_LOG_CMD_* variables.  However, the datalad.log.outputs
option in common_cfg was not renamed.  (None of the new variables were
added to common_cfg, though they arguably should be mentioned there if
datalad.log.outputs is worth including.)
Noticing the datalad.log.outputs was not being picked up, 1a578f478
(BF: it is datalad.log not datalad.log.cmd section to decide destiny
of …
=> TST: Fix documentation and use of LOG_ environment variables

datalad/support/tests/test_annexrepo.py
The assertion that FileNotInRepositoryError is raised recently started
failing intermittently (gh-4773).  The reason is unknown, but it is
happening frequently enough that the Travis build for most PRs needs
to be manually inspected.
=> TST: Skip known failure in test_AnnexRepo_commit

.travis.yml, datalad/distribution/tests/test_install.py, datalad/support/tests/test_gitrepo.py
network tests can delay due to network speed etc, so we cannot really impose time limit on them.
=> BF(TST): a few more @slow tests annotations + also place network tests into "slow" group

datalad/support/gitrepo.py
The previous `git-show` can be slow with more complex commits (e.g.
octopus merge commit, see
https://github.com/datalad/datalad/issues/4801)
Switch to `git-rev-parse` instead as suggested by @kyleam in
https://github.com/datalad/datalad/issues/4801#issuecomment-669480561
Behavior of `GitRepo.get_hexsha()` should stay constant for all
observed usage patterns. In particular raising a ValueError when
querying for a specific, but non existent commitish is critical
for subdataset handling.
Fixes gh-4801
I will tackle an analog change (using `git-log`)  in `GitRepo.format_commit()` in a separate PR.
=> OPT: Faster approach to GitRepo.get_hexsha()

datalad/__init__.py
Since no GitPython is used any longer, no need to tune env variables for it
=> ENH(TST): remove from a setup_package a fixture needed for GitPython

datalad/interface/download_url.py
6c59334d4 (RF: Avoid batch mode for a single file in download-url,
2019-12-10) made the add_url_to_file() call use batch=False if only
one URL is given.  In this case, a failed addurl call will result in a
CommandError rather than a AnnexBatchCommandError, which is derived
from CommandError.
=> BF: download-url: Widen exception around add_url_to_file call

.travis.yml
I got tired of scrolling logs all the way down + some amount up to get
to the most often failing tests -- our unittests ran by nose.
With this change   nose failures should be at the bottom making it much
easier to jump to them
=> RF(TST): travis - run nose tests last

datalad/support/tests/test_annexrepo.py
The `test_annex_ssh` failure in gh-4781 is turning many PRs red.  Skip the failing assertion.
Add a comment to this test and the recently skipped failure in `test_AnnexRepo_commit` so that it can be discovered by someone grepping for the known failure decorator (as discussed in gh-4798).
=> Skip known failure in test_annex_ssh

datalad/distributed/ora_remote.py
Trivial fixes for sentence spacing issues I noticed when debugging gh-4825.
=> DOC: ora: Fix sentence spacing in two error messages

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
When calculating the size of annex data to be transferred (which is
used as the total in the progress bar), avoid counting the bytes of a
key more than once when multiple files point to the same key.
Fixes #4800.
=> BF: push: Correct reported estimate of transfer size

datalad/cmd.py, datalad/support/tests/test_annexrepo.py
These patches hopefully work around the `WitlessRunner` failing to capture the output of quickly exiting commands.
https://github.com/datalad/datalad/issues/4773#issuecomment-676839674
<details>
<summary>datalad-based reproducer mentioned in second commit</summary>
```python
import sys
import tempfile
import datalad.api as dl
from datalad.support.exceptions import CommandError
from datalad.support.exceptions import FileNotInRepositoryError
ntimes = int(sys.argv[1]) if len(sys.argv) > 1 else 40
ds = dl.Dataset(tempfile.mkdtemp(prefix="dl-dropped-stderr-"))
ds.create()
print(ds)
for i in range(ntimes):
print(i)
try:
ds.repo.commit(files="not-existing")
except FileNotInRepositoryError:
pass   # expected result
except CommandError as e:
print(f"\n\nError on iteration {i + 1}\n\n"
f"e.stdout …
```
=> run_async_cmd: Work around dropped output of speedy commands

datalad/distributed/ora_remote.py, datalad/distributed/tests/ria_utils.py, datalad/distributed/tests/test_create_sibling_ria.py, datalad/support/gitrepo.py, datalad/tests/test_utils.py, datalad/tests/utils.py, datalad/tests/utils_cached_dataset.py, datalad/utils.py
All the generators and "newfunc"s in the traceback complicate
troubleshooting etc.  I think we got used to this bad practice and
should abandon it and give wrapped functions names reflecting of the
decorator name.  I chose `_wrap_`, since first I chose just `_` and
ran into a conflict interfering with outside `_normalize_path`.
So decided to be more explicit.
If someone now gives me a one liner which could have just been used, my pride will be scarred forever!
=> RF: replace wrapped "new_?func" with meaningful "_wrap_<wrappedfunction>"

datalad/cmd.py, datalad/config.py, datalad/core/local/resulthooks.py, datalad/interface/run_procedure.py, datalad/interface/tests/test_ls_webui.py, datalad/interface/utils.py, datalad/support/gitrepo.py, datalad/tests/test_config.py, datalad/tests/utils.py
This includes the changes from #4808 (I will rebase this PR, once it is merged).
Primarily, this PR fixes #4813. Along the road various RFs have led to optimization that reduce the number of calls to git-config and hopefully led to more readable code.
=> Big overhaul of ConfigManager

benchmarks/core.py
They showed to be too unreliable.  although some did reveal significant regressions when looking historically:
http://datalad.github.io/datalad/#core.runner.track_overhead_heavyout_online_process
their values still jump in `[-15, 35]` range thus not reliable predictors.
Alternative could be just exclude them just while running on CI.  Let me know what you think
=> Benchmarks: disable track overhead

datalad/metadata/metadata.py, datalad/plugin/addurls.py, datalad/utils.py
Our minimal Python version is 3.5.
=> MNT: Drop compatibility kludge for collections.abc imports

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
=> addurls: Support tsv input

datalad/tests/utils_testrepos.py
But use `call_git*()` methods instead.
Follow-up to gh-4841 to eventually fulfill gh-4689
=> RF: Test helpers no longer use GitRepo._git_custom_command

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This PR completes the puzzle (with #4847 and #4848) to get to where #4689 wanted to be (minus the transition to a CoreRepo/Dataset class set)
Given the severity of this change, it would be good to get additional comments (thx @bpoldrack already). This takes a previous key behavior (normalize_paths) out of the equation for a large number of git-calls (if not most).
We also have to decide what to do with `_git_custom_command()`. Its intended internal helper status would call for immediate removal, but defacto we have to accept that it may have been considered as a part of a more public API.
=> Remove GitRepo._git_custom_command usage from call_git() methods

datalad/cmd.py, datalad/config.py, datalad/support/external_versions.py, datalad/support/tests/test_external_versions.py
Includes 109ac04 from #4703 that exposed a critical flaw in `GitWitlessRunner` and a limitation in `WitlessRunner`
=> RF: Use WitlessRunner for config manager

datalad/config.py, datalad/support/gitrepo.py, datalad/tests/test_config.py
Instead go manual, avoiding various checks, because we already
know inside `save` that a particular directory is considered untracked
by Git.
This approach is substantially faster. Already with 50 subdatasets
the speed-up is 2x.
Quick'n'dirty benchmark:
```
% rm -rf * .git* .datalad; datalad create . && \
( for i in $(seq 50); do datalad create $i; done ) && \
time datalad save && datalad status
```
Current master
```
datalad save  3.70s user 1.50s system 103% cpu 4.998 total
```
This PR
```
datalad save  1.68s user 1.02s system 108% cpu 2.499 total
```
It may well be that it needs more safety checks that would eat up that
margin. But in the context of
https://github.com/datalad/datalad/issues/2880#issuecomment-667041918
(save thousands of new subdatasets) even much smaller benefits would …
=> OPT: Bypass `submodule add` when adding subdatasets

datalad/config.py, datalad/distribution/tests/test_dataset.py, datalad/interface/tests/test_ls_webui.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/repo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
Closes #4827
Opposed to what was suggested in the issue, what we need is not a helper, but have our clean up of *Repo instances (in particular `AnnexRepo` and its potential `BatchedAnnexes`) be more reliable.
- Switch from `__del__` methods to `weakref.finalize`-registered callbacks for Flyweight classes, which should be called more reliably than `__del__`. 
- Improve testing of those objects behavior regarding (re-)creation and deletion and proof they are properly destroyed once `gc` picks them up.
Note, that there's a failure on crippledFS (config-related) that is unrelated and happens in master, too!
=> Address issue with correctly deleting *Repo instances

benchmarks/plugins/addurls.py, datalad/plugin/addurls.py
I have been running addurls with `-x '*'` to not bother with adding metadata for this datasets with a notable amount of files (will endup with 2M files across subdataset(s)).  In the "batch" it seems to be only 20k files, and actual adding urls completed quite fast.  Now I had been staring at slowly growing `Adding metadata (10240 skipped):...` so majority were skipped but not due to "no metadata" I think but because `.add` was not needed would be my guess (`with_result_progress` maps "notneeded" into "skipped" and does nohow filters by record).
PR is now a collection of small changes intended to optimize (although didn't test yet either there is a real advantage) `addurls` while running on large(r) number of files and not bothering to add metadata.
One change in behavior would be that I …
=> OPT: addurls - no add per file, mock.patch once per dataset

.github/workflows/benchmarks.yml
It always takes time and cursing to get to the actual comparison within
the long output of "Run benchmarks".  This is the simplest (and quick -
no benchmarks should be reran) way to get a dedicated action step which
would show the comparison.
PS I will cancel travis run since not relevant
=> ENH: Add separate  asv compare  step within Benchmarks

datalad/interface/rerun.py
I do not exactly like increasing verbosity here, but DEBUG level would
be not appropriate -- at that level we display already much more of details
effectively forbidding tracking ongoing activities.
Here is the result of rerunning on some ad-hoc repo (sorry - I have not
scripted it, here is tarball: http://www.onerussian.com/tmp/test-rerun.tgz) which has a merge and some cherry picks
$> datalad rerun --since=
[INFO   ] run commit d4a55bb (md5)
[INFO   ] Making sure inputs are available (this may take some time)
unlock(ok): /home/yoh/proj/datalad/trash/test-rerun/MD5SUMS (file)
[INFO   ] == Command start (output follows) =====
[INFO   ] == Command exit (modification check follows) =====
add(ok): /home/yoh/proj/datalad/trash/test-rerun/MD5SUMS (file)
[INFO   ] run commit 66a4fee (md5)
[INFO …
=> ENH: provide INFO level logging for an action about to be reran

datalad/downloaders/configs/nda.cfg, datalad/downloaders/credentials.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_s3.py, datalad/interface/common_cfg.py, datalad/support/s3.py, datalad/support/third/nda_aws_token_generator.py
- Uses new version of NDA authenticator to obtain S3 credentials for download
- Makes it possible to download from NDA bucket(s) which are quite "locked down"
- default boto3 access to a bucket with verification would fail, so upon that specific error we would try to connect without validation
- getting a key for which versionId is known is not possible while specifying that versionId.  And default boto behavior is to do so.  In this PR I change behavior to "kill" version_id from the key we are requesting if original url requested did not have versionId.
Although it is bug fix in nature, I am ok to reposition it against `master` if so deemed better.
=> BF: fix authentication + download from S3 for NDA

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py
Positioned against `maint` since 
- previous code should still work, we will just announce (well, DeprecationWarnings are not shown! by default, heh) deprecation
- it would improve my UX while switching from `publish` to `push` (although #4682 would also help) so I could just use `--since=^` in both
Who knows, may be in 0.15 the entire `publish` would be gone...
=> RF: make publish understand --since=^ and deprecate --since=

datalad/distribution/get.py, datalad/distribution/tests/test_get.py
Doing it with config settings has two advantages.
- benefits from interprocess locking of datalad ConfigManager, such that
we can "get" in parallel without running into locking issues.
(`datalad -f '{path}' subdatasets | xargs -n 1 -P10 datalad get -n`)
- we can set the real source URL of the successful clone, whereas
`GitRepo.update_submodule()` is what cause a guess to be made.
For example, cloning a superdataset from
git@github.com:datalad-datasets/human-connectome-project-openaccess.git
would lead to invalid submodule URLs like:
git@github.com:datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100307
whereas the actual clone came from
http://store.datalad.org/8fd/bc694-2c2b-11ea-b467-0025904abcb0
This change has a high potential for missed corner-cases. It would be good …
=> RF: Bypass `git-submodule update --init` when getting subdatasets

datalad/support/archive_utils_7z.py, datalad/tests/test_archives.py
I am not aware of any other common extensions that indicate compressed tarballs in a single suffix. There is now a dedicated function to normalize such suffixes to make them detectable with the existing approach -- without affecting the actual filename.
Fixes #4875
=> ENH: Add support of .tgz archives

.github/workflows/test_crippled.yml, .travis.yml, CONTRIBUTING.md, appveyor.yml, datalad/utils.py, setup.py, tox.ini
PY35 will come to its end-of-life (EOL) in a week from now.
https://devguide.python.org/#status-of-python-branches
Fixes gh-4878
TODO
=> RF: Require Python >=3.6

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py
This should avoid lengthy annotatepath in heavy hierarchies while trying to
look for possible changes in the wortree.
I think this would not be entirelly correct in case if subdataset is
progressed forward but change was not recorded in the superdaset yet, but it
might work as desired (publish modified in its forwarded on remote end as well)
which might be current behavior as well anyways (did not test).
Might be that it Closes #4446 ;-)
=> ENH: add ..HEAD to since statement if defined upon publish

CONTRIBUTING.md
If needed - can split into two PRs (or just merge first commit into master directly) -- first commit is kinda obvious.  
2nd one is aiming to establish some formalization of the workflow so we could reach 1.0 (#4585)  and is largely based on current workflow and ideas in (closed) #4238. It might not yet be complete, and not as detailed as #4238 but I think it would be valuable to agree on these basic items first before expanding/formalizing it further.
=> CONTRIBUTING.md: tune up to section formatting + release etc workflow draft

datalad/support/annexrepo.py, datalad/tests/test_direct_mode.py
That is its only purpose. Any chance to reduce clutter in this monster class should be used.
=> RF: Strip AnnexRepo._set_direct_mode() from class and make test helper

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
Story is in the commit messages. Big change is the push of the active branch.
Fixes #4888
=> Make push work with push.default=matching repos

datalad/distribution/tests/test_dataset.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
In light of (unresolved) issue #4862, it seems necessary to adapt the tests for now.
Since the issue is neither happening for me locally nor on Travis, I need you, @kyleam and @mih to confirm, that these tests are passing for you with this patch.
If so, I'll need to dig out #4849 in addition (and find a better solution for that one).
=> TST: Refcount is unreliable ATM

datalad/support/archive_utils_7z.py
Another small step.
Went for a dedicated subshell to implement the pipe, rather than an exploration how to connect two runners. Not worse than what it was before.
=> RF: Make archive (de)compression use WitlessRunner

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distributed/tests/test_ria.py, datalad/interface/common_opts.py
Somehow we managed to ignore the intial usecase leading to the development of RIA stores and ephemeral clones! *facepalm*
This fixes `clone` to symlink an ephemeral clone's annex correctly, if `origin` is a bare repo.
Tests are enhanced in two ways:
1. Test merely the right link in `test_clone.py` as this is all `clone` itself is concerned with.
2. Add a new test file for usecases/workflows involving RIA stores and add the first one, which is an enhancement of what @dickscheid described in #4893 in that it writes to the unlocked file in the clone and propagates everything back to origin via the store.
Ping @mih
=> BF+TST: ephemeral clone to account for bare repo

datalad/customremotes/base.py
Otherwise it make annex puke since it does not expect multiple lines in a
single command message/content.
E.g. seeing (thanks to #4925 )
datalad.cmd     [Level 5] stderr| datalad.customremotes [Level 4] Sending 'DEBUG Failed to check url s3://NDAR_Central_2/submission_23229/sub-XXX/ses-baselineYear1Arm1/fmap/sub-XXX_ses-baselineYear1Arm1_dir-AP_run-01_epi.nii.gz: Cannot connect to any (originally requested NDAR_Central_2) S3 bucket. Exception: S3ResponseError: 400 Bad Request\n [s3.py:_handle_exception:75]'
datalad.cmd     [Level 5] stderr|   external special remote protocol error, unexpectedly received " [s3.py:_handle_exception:75]" (unable to parse command)
datalad.cmd     [Level 5] stderr| datalad.customremotes [Level 4] Sending 'CHECKURL-FAILURE'
datalad.cmd     [Level 5] stderr| …
=> BF: custom remotes - replace os.linesep with an explicit \n in messages to annex

datalad/downloaders/credentials.py, datalad/support/network.py, datalad/support/tests/test_network.py
with time.localtime() we are getting local time without any time zone, calendar.timegm
then produces seconds since epoch for that in GMT thus again - no zone.
With time.time() we seems to be getting seconds since epoch properly.
I kept running into S3 downloads failing while credential reported to
be expiring in some hours to come
=> BF: use time.time (no timezone offset) while checking expiration for AWS credentials

datalad/config.py, datalad/core/local/run.py, datalad/core/local/tests/test_resulthooks.py, datalad/interface/run_procedure.py, datalad/resources/procedures/cfg_metadatatypes.py, datalad/support/github_.py, datalad/tests/test_config.py
Before this change, the values of all specifications of an identical key
were returned as a tuple. Now only the last value is returned, and
`get_all=True` has to be set to get the previous behavior.
Rationale: That a single value is returned is a sensible default
expectation. Valid use cases for multiple values are few, and require
custom handling in consuming code. The previous behavior would require
protection against the multi-value-return possibility all throughout
the code base. This switch is disruptive, but makes overall operation
more robust.
Fixes gh-2628
Fixes gh-4919
=> RF: Change ConfigManager.get() behavior for multiple identical key specs

datalad/customremotes/datalad.py
It was introduced in 15ecbb78a86f36b353e763273577dd369671e61b (`0.9.2~76^2~6`) as a part of https://github.com/datalad/datalad/pull/1870
with a purpose according to description of not pollutting stdout used by
special remote for communication.  BUT logs go to stderr and do not interfer
anyhow with the communication, so the reason for the change is not clear to me.
I have been trying to figure out why the heck I am still seeing failures after
https://github.com/datalad/datalad/pull/4931 .  I kept adding more logging but
nothing appeared in the logs!  I finally was brought to this piece of code,
thus the motivation and argumentation for the change.
Let's see -- if CI is happy, it means that my argumentation above that there should be no interference is correct and it should be safe to …
=> RF: remove disable_logger in customremotes/datalad.py

setup.py
In master, 3ab5a14689d6575f841a05d450e2676e855d6035, added use of InterProcessLock
with providing our logger.  That feature was added only in 0.14 according to
https://github.com/harlowja/fasteners/blob/master/ChangeLog
and stable Debian (and NeuroDebian ATM) has only 0.12.0 which causes
errors.
We could have checked on version of fasteners and provided only if recent enough,
but for now (hoping that backport builds succeed) I am just establishing minimal
version
=> BF: declare minimal version of fasteners to be 0.14

tools/ci/prep-travis-forssh.sh
This change causes `prep-travis-forssh.sh` to wait for the SSH containers to be ready by repeatedly checking whether connections can be made to their SSH ports.  This should be more robust than just sleeping for a fixed number of seconds.
=> prep-travis-forssh.sh: Check SSH readiness with nc instead of sleeping

datalad/cmd.py, datalad/support/annexrepo.py
- add `--debug` option to `annex CMD --batch` invocation when level <= 8, analogously to what we do in main AnnexRepo "good old runner"
- incorporate and supersede #4925 - log all stderr lines if logging of outputs was requested and log level <= 5
- 100 is just often is not enough to troubleshoot some issue which has happened some time before (crash of special remote etc) the batch process actually finished
I hope these two changes would make debugging of annex and started by it external remotes more manageable.  ATM it is either pain or just impossible.
=> ENH: make it possible to debug batched annex

.github/workflows/test_macos.yml, datalad/core/distributed/tests/test_push.py, datalad/tests/utils.py
=> Workflow for testing on macOS

datalad/tests/test_tests_utils.py, datalad/tests/utils.py
previous explicit listing tries to do combinatorics manually. Well -- we cannot
actually try all possible combinations of tricky filename components, but we can
assume that we could test adding each tricky part individually to arrive at the
trickiest one.  That is what this PR does -- replaces static list with generation
from parts.
Also it adds commented out "%b5" identified to trigger issues with datalad-archive
special remote (#4950).  It is the motivation for this RF -- it was virtually impossible to figure out where in the chain of hardcoded candidates I should stick it in. With this commit/PR I just want to RF to see if no side-effect and then
we can see what else breaks if "urlencode" like component is added to the filename.
And then I will build another PR on top to fix (if …
=> RF+ENH: incrementally grow  obscure filename

datalad/downloaders/base.py, datalad/downloaders/credentials.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_credentials.py, datalad/downloaders/tests/test_s3.py, datalad/support/annexrepo.py, datalad/support/exceptions.py, datalad/support/s3.py, datalad/utils.py
I think this is an alternative (as a better solution to the underlying issue) to the https://github.com/datalad/datalad/pull/4928 -- I kept hitting a `400` error from S3 while `addurls` ABCD.  I believe in the course of DANDI project we had similar occasions whenever S3 would fail with 400 without apparent reason: well, there are many reasons why 400 could be returned - https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList and some of them are "legit", i.e. retry probably should not 'fix' that.  But I do not want to sift through all of them ATM.  IMHO it would be perfectly fine to retry a few times.
I have also added other codes (with comments in the code) which I think are legit to retry with sleep upon hitting.
Also `@try_multiple_dec` was enhanced and …
=> ENH+RF: @try_multiple_dec_s3 to retry interaction with S3 upon "retriable" errors

datalad/interface/base.py, datalad/interface/tests/test_utils.py, datalad/interface/utils.py, datalad/support/archives.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py
To address #4950 , but also introducing `%b4` into an obscure filename used by tests. Sits on top of #4949 .  The actual fix in the last commit in the series was trivial and to the one of the most ancient pieces of code in the archive (current commit is f080379e8ae6faf61c0927662940399be9aa5543 ).  Let's now just see if tests pass to signal that there were no some hidden assumption somewhere ;-)
=> Tollerate %xx in filenames

datalad/downloaders/base.py, datalad/downloaders/http.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_http.py, datalad/utils.py
Some downloaders need to read-in the actual downloaded content to see if it may be a "login error" message since portals do not return a proper 403 etc.  If content is not utf8 - it was causing a puke (#4951) .
This is likely a tip of an iceberg and there could be more of places in datalad where we read some content assuming it to be utf-8, whenever it is not.  Introduced here `read_file` (I am ok to rename if desired, initially `read_file_ensure_unicode` - generalized into one to use without decoding as well) would be of help.  May be you know a better way? but I thought it would be nice to centralize all such logic on encoding discovery via `ensure_unicode` which we do use already quite a bit throughout the code.
edit 1 after more pushes: One functionality change/fix is for S3 …
=> downloader: handle non-utf8 files being downloaded

datalad/utils.py
We use swallow_outputs across many tests. Total swallow forbids figuring out what
has possibly gone wrong.  DATALAD_LOG_OUTPUTS is typically used for debugging
of problems and I thought that it would make sense to apply also to swallow_outputs,
instead of inventing a new config setting like DATALAD_UNSWALLOW_OUTPUTS and
or alike
=> ENH(DX): Make DATALAD_LOG_OUTPUTS trigger logging of swallowed ouputs as well

.github/workflows/shellcheck.yml
I find `shellcheck` really handy!
I thought to make this workflow conditioned on changes to those files, but IMHO too much hassle for what it is worth since shellcheck run should be quite fast
=> ENH: add shellcheck run on shell scripts which ATM are shellcheck kosher

datalad/customremotes/archives.py, datalad/customremotes/base.py, datalad/customremotes/datalad.py
Ref: #4954 
I do  not think it would be of tremendous performance boost (since most of the time is likely to be spent in interaction with external resources) but it can cut interactions between git-annex and `datalad` special remote significantly, and will pollute log less.
I think the change is quite straightforward and I would not mind to rebase it against `maint`, but I am also ok to keep it in master.
=> OPT: gen_URLS (to replace get_URLS) - query schemes in order of prior "successes"

datalad/support/annexrepo.py, datalad/support/exceptions.py
I misspelled a remote name when calling `datalad get --source` and saw this message, which by itself I'd take to mean a remote named 'annex get' is not available.
```
RemoteNotAvailableError: ''annex get''
```
That's a regression that came with v0.13.0 and affects all `CommandError` subclasses.  The final commit of this series restores the display to
```
Remote 'DO-NOT-EXIST' is not available. Command failed:
RemoteNotAvailableError: 'annex get'
```
The three commits before that are cleanup commits in surrounding areas, and any of them can safely be dropped.
=> exceptions: Restore CLI rendering of CommandError subclasses

datalad/core/distributed/clone.py
There's no actual handling of those URLs involved here. It's simply
passing it on to requests. Simply don't let clone swallow it.
=> BF: Accept ria+https URLs in clone

datalad/plugin/wtf.py
Would look something like this (paths truncated):
```
% datalad wtf -S credentials
- keyring:
- active_backends:
- SecretService Keyring
- PlaintextKeyring with no encyption v.1.0 at ...keyring_pass.cfg
- config_file: ....config/python_keyring/keyringrc.cfg
- data_root: ....local/share/python_keyring
```
If got tired of looking up the code snippets in the keyring docs to
run when switching machines, and discovering the left-overs of previous
configuration attempts.
Related to gh-4981
=> ENH: Show info on credential setup in wtf()

datalad/interface/run_procedure.py, datalad/metadata/metadata.py, datalad/tests/utils.py, datalad/utils.py
Also refactors a bit how obscure file name is generated so trailing white spaces are PARTS now thus code is simplified.
Also removed ad-hoc windows skipping of a name with trailing space -- testing now `mkdir` as well.  Let's see if that would allow those previously failing tests to pass and what would be the name on windows.
The most obscure filename one my laptop now is ``` "\';a&b&cΔЙקم๗あ `| ```.
I have done only a limited sweep over local tests.
note FTR: in conda python 3.5 I have two ria tests failing but it seems unrelated to this (`datalad/core/distributed/tests/test_push.py:test_ria_push datalad/core/distributed/tests/test_clone.py:test_ria_postclonecfg`)
=> ENH: more obscurity - add ', ", and {} to obscure filenames

datalad/plugin/add_readme.py, datalad/plugin/tests/test_plugins.py
I saw that hirni uses ``add_readme.py`` to populate studydatasets with a placeholder README (within ``cfg_hirni``). This change makes the README reference the handbook as documentation instead of docs.datalad.org.
=> DOC: Reference handbook documentation in add_readme

datalad/customremotes/archives.py, datalad/customremotes/base.py, datalad/support/annexrepo.py, datalad/tests/test_cmd.py
On a Windows machine, while ``git-annex`` and ``git annex`` invocations work fine from an Anaconda prompt, a "git-annex" command invoked via ``run_annex_command`` fails to find the git-annex executable.
When using 'git annex', though, commands seem to work just fine. This change fixes #4892. I lack an in-depth understanding of why that is, yet, but I also figured that this change doesn't do harm to anything else.
=> Win/BF: don't invoke 'git-annex' but 'git annex'

datalad/core/local/run.py, datalad/core/local/tests/test_run.py
Fix a bug in `datalad-run`, where sidecar files weren't saved, when outputs are specified w/ `--explicit`.
A caller of `run` can't know the to be saved path and shouldn't need to care for a builtin feature to be functional. Can't see an argument why this wouldn't be a bug.
=> BF: always save run sidecar files 

datalad/cmdline/main.py
I just embedded it into the message we already have for CLI parsing, because
that is effectively the first log line printed if log level is changed
(as most commonly done) via -l debug .
This should help to avoid possibly asking for WTF when we ourselfves or others provide at least this information "by default" along with `-l debug` output
Looks like
```
$> datalad -l 1 install -s /// /tmp/dddd
[DEBUG  ] Command line args 1st pass for DataLad 0.13.4.dev15-g84ba1-dirty. Parsed: Namespace() Unparsed: ['install', '-s', '///', '/tmp/dddd'] 
...
```
=> ENH: display datalad version in the first log message out there  when running in cmdline

datalad/cmdline/main.py, datalad/customremotes/main.py
we stopped showing license for --version output for the main process,
but still were showing it for special remotes.  I see no reason for
the difference and maintaining another place where we would need to
tune up copyright years, so just removing it altogether
=> RM: remove _license_info and use in customremotes/main.py

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_publish.py
Use a 2-stage approach (subdatasets(recursive) + diff()) to avoid the
runtime cost of a full diff(recursive).
Ping gh-3368
=> RF: Strip `AnnotatePaths` from `create_sibling()`

datalad/cmd.py, datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/core/local/tests/test_diff.py, datalad/distributed/ora_remote.py, datalad/distributed/tests/test_ria_basics.py, datalad/distribution/create_sibling.py, datalad/distribution/tests/test_publish.py, datalad/interface/diff.py, datalad/interface/tests/test_base.py, datalad/interface/tests/test_diff.py, datalad/interface/tests/test_ls_webui.py, datalad/interface/tests/test_run_procedure.py, datalad/plugin/tests/test_addurls.py, datalad/plugin/wtf.py, datalad/support/annexrepo.py, datalad/support/archive_utils_7z.py, datalad/support/gitrepo.py, datalad/support/sshconnector.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_sshrun.py, datalad/tests/test_installed.py, datalad/tests/test_testrepos.py, datalad/tests/test_utils.py, datalad/tests/test_witless_runner.py, datalad/tests/utils.py
All Runner code is now hanging on a thin thread. The remaining connections are:
- `GitRepo._run_git_custom_command` is still on life support but already brain dead
- `run` still uses `Runner` -> #5002
Significant changes:
- WitlessRunner now supports shell-based execution https://github.com/datalad/datalad/pull/4996/commits/df4f782bd8a30693cb5a28665ad4e41eb82c9907
=> Runner -- shot of mercy

.travis.yml, tools/coverage-bin/datalad
That should bring back coverage reporting from nested special remotes of datalad,
and avoid requirement of setting a special COVERAGE env var
Closes #4956 .
=> BF: Just use -m coverage instead of some debian specific python*-coverage

.github/workflows/test_macos.yml
The set-env workflow command is deprecated in favor of environment files: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Use environment file instead of set-env

datalad/cmd.py
PATH modification in Runner classes is meant to make sure we use
bundled w/ annex git executable (except when instructed otherwise
by DATALAD_USE_DEFAULT_GIT). However, don't mess with PATH when
what we find to be bundled is the same thing that is found with
unmodified PATH anyway. This is particularly important when the
"bundeled" location is /usr/bin and we are running in a virtual
environment, leading to that PATH overruling the venv.
Closes #5030 and by extension #5024  (when combined with #5026)
=> BF: Don't modify PATH if not necessary

datalad/distribution/create_sibling.py, datalad/distribution/create_sibling_github.py, datalad/support/github_.py
I created a reproducer for #4997 and wanted to look into "default branch" situation, so positioned on top of maint, but really wanted automation to help deleting test repo from github, so derailed into this one.  I am ok to rebase for master if deemed desired.
=> ENH: create-sibling-github --existing=replace

datalad/downloaders/configs/indi.cfg
The `datalad-test-s3` credentials are configured as the default for indi-s3, which prevents the ability to connect anonymously. This change fixes #5038
=> BF: indi-s3 credentials

datalad/ui/dialog.py
Otherwise might interfere with progress bars
I have not "observed" wrong behavior but change looks logical to me.
=> BF: UI - .error also should go through .message to handle pbars

.travis.yml, datalad/__init__.py, datalad/interface/common_cfg.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/sshconnector.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_sshconnector.py, datalad/tests/utils.py
A new switch `datalad.ssh.multiplex-connections` is introduced (off by default on windows).
A leaner manager and a different SSHConnection object are used in the non-multiplexed mode.
Manager and Connection classes have been RF'ed substantially.
Also streamlined the handling of SSH args. Instead of keeping individual ones, let the constructor(s) lump them into categories "for opening" and "for any call". This seems to be sufficient.
ATM this is targeting `maint` to have a chance to get SSH cloning working on windows prior 0.14.0 (e.g. #5031). but the necessary changes are substantial. So this will have to be more than a "fix".
TODO
Related https://github.com/datalad/datalad/issues/4166
Fixes #2575
Fixes #5031
=> NF: Make multiplexed SSH connections an optional feature

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py
Discovered by chance while troubleshooting failing
https://github.com/datalad/datalad/pull/5022
which due to "out of order" completion of get swapped datasets between
noannex and annexed.  Was fund to debug (so added descriptive temp dirs suffixes) .... heh ;)
While at it spotted unused kwarg in `_push`.  Removed - no need to keep and must not break anything
=> BF: push - do not call localsync unless annex

datalad/core/local/save.py, datalad/core/local/tests/test_save.py
After collecting the status information, save() adds a status record
for any subdatasets between the reference dataset and the target
dataset.  Here's an example that shows when these extra records are
needed:
$ datalad create
$ datalad create -d. a
$ datalad create -d. a/b
During the last step, create() calls save() with "a/b" as the path.
After save() collects the status() information in paths_by_ds, the
value looks like this:
{'{top}/a': {PosixPath('{top}/a/b'): {'state': 'untracked',
'type': 'directory'}}}
Before calling GitRepo.save_(), save() adds another record for "a":
{'{top}': {PosixPath('{top}/a'): {'state': 'untracked',
'type': 'dataset'}},
'{top}/a': {PosixPath('{top}/a/b'): {'state': 'untracked',
'type': 'directory'}}}
If it didn't tack on the first entry, "a" would be left …
=> save: Fix handling of explicit paths for nested new subdatasets

datalad/core/distributed/clone.py, datalad/downloaders/tests/test_http.py, datalad/support/network.py
This PR essentially removes a custom HTTP GET request handling and uses a new (but pretty trivial) download helper.
Fixes gh-5023
... although it could be made better by supporting git-credentials as a credential sources in DataLad. This, however, would only make internal changes and no have consequences for the proposed change in `clone`.
A significant annoyance is that low-level code insists on reporting INFO level log messages that will no report URL to be downloaded to short-lived temporary files with cryptic names. But at least it is functioning properly for now.
=> BF: RIA clone HTTP403 handling and support authenticated access

datalad/core/distributed/clone.py, datalad/distributed/ora_remote.py, datalad/downloaders/tests/test_http.py, datalad/support/network.py
This sits on top of #5025 (to be able to make use of the `download_url()` helper), and replaces a custom HTTP GET that is unaware of error response codes (#4980) and necessary credentials (#5024).
ATM this solution is only working for `git annex get`, but not `datalad get`. No idea why.
https://github.com/datalad/datalad/issues/5024#issuecomment-707541179
Fixes #4980
Fixes #5024
=> BF: ORA authenticated HTTP access

datalad/config.py, datalad/core/distributed/clone.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py, datalad/tests/test_config.py
This PR aims to add minimal support for bare repositories to `GitRepo`. We should now be able to properly create one (not just pass `--bare` to `git-init`, which is insufficient) and instantiate on an existing bare repo. Added `bare` property, so `GitRepo` is aware and we can enhance it to react to that knowledge from within its methods. That property does not only check the config but also does an additional consistency check on `pathobj` and `dot_git` (should be cheap enough, I think).
Please have a look, @datalad/developers
=> Towards (minimal) support for bare repos

datalad/metadata/indexers/base.py, datalad/metadata/search.py, datalad/metadata/tests/test_search.py, datalad/plugin/wtf.py
This PR introduces an infrastructure for specialized indexers, which means indexers, that are specifically built to generate an index from metadata of a given format (the metadata format name is the same as the name of the extractor that generated the metadata). If datalad search needs to build an index for metadata it will now check whether a matching specialized indexer is installed. If a matching indexer is found, it will be called to generate the index, i.e. the set of key-value pairs that represents the metadata in the search context (this is done for all four search modes, i.e.: autofield, blobtext, egrep, and egrepcs).
If no specialized indexer is found for a metadata-format, the generic indexer that was used before will be used for this format.
This PR closes issue #4944
=> NF: add infrastructure for specialized indexers

datalad/support/gitrepo.py
GitRepo.get_content_info() calls ls-files with --modified and
--deleted.  When combined with --stage, those flags don't add any
information, just duplicate lines in the output.  In addition to
redundant processing, these flags result in a slower ls-files call
because the working tree needs to be considered.  Without --modified
and --deleted, the execution time of `ls-files --stage` is comparable
to that of `ls-tree -r`.
$ git clone https://datasets.datalad.org/openneuro/.git .
$ git version
git version 2.29.0.311.g38ddec7408
$ git status # warm cache
$ multitime -n 5 -q git ls-files --stage
===> multitime results
1: -q git ls-files --stage
Mean        Std.Dev.    Min         Median      Max
real        0.005       0.001       0.003       0.006       0.007
user        0.001       0.002 …
=> OPT: get_content_info: Speed up ls-files by dropping unneeded flags

datalad/interface/tests/test_utils.py, datalad/interface/utils.py
Updating it for each result is the cause of the slow-down reported in
https://github.com/datalad/datalad/pull/4868#issuecomment-688417401
With this change we only update at max 2Hz. For the original scenario
this results in a ~30% speed-up:
```
datalad subdatasets -d .  4.30s user 1.99s system 101% cpu 6.225 total
datalad subdatasets -d .  6.33s user 2.27s system 100% cpu 8.538 total
```
=> OPT: Rate limit result suppression message update

datalad/distribution/dataset.py, datalad/distribution/update.py, datalad/local/subdatasets.py, datalad/local/tests/test_subdataset.py, datalad/support/gitrepo.py
Speeds up the rejection of non-containing subdatasets. For the UKB dataset with 42k subdatasets, this shaves of 1s of the previous total runtime of 2.5s.
Related to gh-4859
This also removes a backward compatibility kludge that we put in place over a year ago (`revision` instead of the present `gitshasum` property in the submodule records).
Edit: This also ups the plain reporting performance (same 42k subdatasets):
Before: `datalad subdatasets  9.49s user 3.41s system 57% cpu 22.284 total`
After: `datalad subdatasets  9.81s user 2.49s system 74% cpu 16.399 total`
and with a twist: `datalad subdatasets -d .  6.95s user 2.14s system 66% cpu 13.622 total` (see TODO)
TODO:
```
datalad subdatasets -r --contains sub-3507513  2.76s user 0.33s system 103% cpu 2.973 total …
```
=> OPT: Speedup of per-subdataset "contains?" matching

datalad/support/tests/test_annexrepo.py
test_annex_ssh() does not stall with the git-annex version used in
regular Travis jobs (7.20190819).  test_annex_ssh(), among other
SSH-related tests, used to stall with newer git-annex versions.  This
appeared to have something to do with the old SSH version on Xenial,
and a workaround was applied on git-annex's end [1].  test_annex_ssh()
skips from 7.20191230 to 8.20200720.1 to avoid this stall.
However, test_annex_ssh() also stalls in the cron job that tests
against git-annex 7.20190708 [2].  The build succeeds if
test_annex_ssh() is skipped [3].  It looks like the stall started with
the switch to the Docker SSH target [4].
I cannot trigger this locally on a Debian Buster system with the
Docker SSH target, so perhaps there's an interaction with the Xenial
environment.  Until someone …
=> test_annex_ssh: Extend skip to older git-annex versions

appveyor.yml, datalad/tests/test__main__.py, datalad/tests/test_auto.py, datalad/tests/test_cmd.py, datalad/tests/test_log.py, datalad/tests/test_protocols.py, datalad/tests/test_utils.py, datalad/tests/test_utils_cached_dataset.py, datalad/tests/utils.py
This is an effort to enable more testing on windows. In particular the aim is to have some testing working with a windows datalad installation that a user following the handbook would have -- rather than just within the somewhat twister appveyor setup.
All changes are cross-verified manually on a win10 box with an installation as described in https://github.com/datalad-handbook/book/pull/588
- Remove testrepo setup special case on windows https://github.com/datalad/datalad/pull/5069#issuecomment-715013343
- run all `datalad.tests` tests, mark individual ones as failing or skip them, if there is no hope -- this will help further breakage from creeping in #5074
=> More windows testing

datalad/local/subdatasets.py
Results in substantial speedup for recursive processing, as datasets
without any submodules are rejected prior any Repo instantiation.
For a dataset with 42k subdatasets this means going from
```
datalad subdatasets -r  270.45s user 615.64s system 104% cpu 14:07.22 total
```
to
```
datalad subdatasets -r  5.82s user 0.69s system 101% cpu 6.422 total
```
Fixes gh-5075
=> OPT: Delay Dataset.repo access until necessary

datalad/core/distributed/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py, datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
A good number of test modules no longer show up in the appveyor logs,
including those that test very basic and important functionality
(e.g., GitRepo, save, get, and clone).  It looks like these were lost
starting with gh-3975 (2020-01-02), in particular the last commit of
that series (715be1f786).
One change of that commit was to decorate with_testrepos() with
known_failure_appveyor().  (Before the series, the function returned
by with_testrepos() raised a SkipTest if on Windows.)  Based on
replacing the decorator with a plain SkipTest [*], it seems that any
module that uses with_testrepos() isn't executed on appveyor (for
reasons that I don't understand).
Drop the known_failure_appveyor() decorator and instead raise a
SkipTest if on appveyor to restore the execution of tests modules. …
=> TST: appveyor: Restore execution of modules that use with_testrepos

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
Rationale - to make commit message "portable" happen someone needs to
redo it. Ideally the urlfile should be either "-" or relative within dataset
path.  I decided to not inforce it but merely store the original specification
of the user.
Also decided to just adjust/reuse existing test to not add more time to setup
a dedicated one
NB positioned against master since changes the record/behavior, unless there is consensus that it is appropriate for `maint` ;)
=> ENH: addurl - store original urlfile, not resolved full path

datalad/distributed/create_sibling_ria.py, datalad/distributed/tests/test_create_sibling_ria.py
- add support for `storage_sibling='only'` which triggers the mode
desired in gh-5077
- add an additional parameter `disable_storage__=None` which is
used as a destination for the previous `--no-storage-sibling` cmdline
option. Whenever it is used, as deprecation warning is issued
- introduce `--storage-sibling {on|off|only}` cmdline argument handling.
This opens up straightforward handling of further storage sibling
modes (different special remote types/configs) in the future -- in
contrast to an alternative approach along the lines of a dedicated off
switch for the repository sibling part.
From the perspective of the cmdline interface this deprecates
`--no-storage-sibling` in favor of `--storage-sibling`.
From the perspective of the Python API, an additional argument value of …
=> NF: create-sibling-ria --storage-sibling only

datalad/cmd.py, datalad/interface/common_cfg.py
This reverts commit 383819eafc77e604c9cea2977820dcd299ea2902.
That workaround, introduced in #4829, just hides away the problem, possibly
leading to data loss (e.g. batched process would not finish its processing by
then and we proceed to eg save or alike), and makes it hard to impossible to
spot/debug in real life cases where it manifests itself.
This is unlikely to fix the issue, but I want to see if it still
reproduces (I failed to reproduce it in the past 2 days).
More references:
- datalad issue https://github.com/datalad/datalad/issues/4998
- git-annex report https://git-annex.branchable.com/bugs/some_annex_addurl_--fast_--with-files_--json_--json-error-messages_--batch__do_not_quit/
I do not think of any reasonable "timeout" we could specify and be "correct", since in some cases …
=> Revert "ENH: When closing batched processes avoid waiting forever"

datalad/dochelpers.py, datalad/interface/download_url.py, datalad/interface/results.py, datalad/tests/test_dochelpers.py
And for demonstration of utility - added to a single sample invocation within download_url.
One of the main use cases is to be able to troubleshoot failed travis runs, where
at most we see only the last location in the traceback due to exc_str being used.
Like
'message': "'ConsoleLog' object has no attribute 'yesno' "
'[__init__.py:__getattribute__:101]',
Due to all the generators for results status messages processing etc, there is no
idea about original stack which lead to the failure :
File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 271, in _wrap_skip_ssh
return func(*args, **kwargs)
File …
=> ENH: add exception_traceback ("unlimited") to the status dict if exception is passed into get_status_dict

datalad/support/repo.py
Fixes gh-5112
No idea how to programatically create a network mount on appveyor, hence fixing without a test for now. Left extensive note to prevent accidental removal.
=> BF: Prevent Repo to resolve network mount to UNC paths on windows

datalad/customremotes/tests/test_archives.py, tools/which.py
No real fixes since should be done either on git-annex level (misbehaving locking when path is too long) or us RFing tests to rely on capabilities of the TMPDIR instead of `if on_windows`, so might even start failing where was working before.
BUT with today's git-annex (soon to be built on CRON job, will upload to packages/ tomorrow) `datalad/customremotes/tests/test_archives.py` tests all pass for me on windows VM.
also I gift you the mighty `which.py` which you might love in a moment of despair.
=> BF: workarounds to tests on Windows

datalad/core/local/tests/test_results.py, datalad/interface/utils.py
Changes:
- avoid spurious whitespace when results carry no path
- prevent crash when path relpath'ing is not possible (fixes gh-5116)
- make missing `action` and `status` declarations more obvious in the
output (before it was just `None`)
- add test to verify a bunch of corner cases
Once released with 0.13.6, this could bring piece to the win2019 tests of datalad-osf @adswa
=> BF+TST: Robustify default_result_renderer()

appveyor.yml, datalad/core/distributed/clone.py, datalad/core/local/tests/test_status.py, datalad/customremotes/tests/test_ria_utils.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_utils.py
=> ENH: appveyor -- use newer git-annex + try to re-enable codecov submission

datalad/core/distributed/tests/test_clone.py, datalad/support/gitrepo.py
Force-treating a to-be-added submodule as a GitRepo prevented the
detection of a corresponding branch to the active branch, in order to
determine the true tracking branch. Which is necessary to discover
the effective clone URL from a repository (when it is in adjusted
mode).
This is an alternative to 901c8fd4eaf8070fa632f03d9428eceba3c0c97c but
reworked to be applicable to the 0.13 series.
Fixes gh-5107
=> Avoid repo type assumptions to enable proper tracking branch detection (maint)

datalad/core/distributed/tests/test_clone.py, datalad/support/gitrepo.py
This is the same as #5127 but we the fix ported to master.
Fixes gh-5107
=> Avoid repo type assumptions to enable proper tracking branch detection (master)

datalad/tests/test_direct_mode.py
Most of test_direct_mode() is no longer executed because it requires a
git-annex version that supports direct mode, and the version used for
most CI jobs does not.  test_direct_mode() failed in master's most
recent cron job with git-annex 7.20190708+git9-gfa3524b95-1~ndall+1
due to two undefined names [*].  These came from a faulty conversion
in 595443c5b6 (RF: Strip AnnexRepo._set_direct_mode() from class and
make test helper, 2020-09-06).
Note that this failure didn't have a chance to surface until
relatively recently because the job stalled before aafebc819a (TST:
test_annex_ssh: Extend skip to older git-annex versions, 2020-10-20)
[*] https://travis-ci.org/github/datalad/datalad/jobs/741950931
---
No time or effort should be spent on direct mode at this point, but this fix is simple …
=> TST: test_direct_mode: Fix two name errors

datalad/core/distributed/tests/test_clone.py, datalad/distributed/ora_remote.py
This fixes #5085 but it does not make the relevant test complete due to #5134. However, with these changes, I can manually create RIA siblings, push them, clone them, and get data from them -- on windows.
```
(base) C:\Users\mih\TMP>datalad create someds
[INFO] Creating a new annex repo at C:\Users\mih\TMP\someds
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\mih\TMP\someds (dataset)
(base) C:\Users\mih\TMP>datalad -C someds create-sibling-ria -s store …
```
=> Fix path and URL handling in ORA remote and associated tests

.github/workflows/test_macos.yml, datalad/distribution/create_sibling.py, datalad/support/tests/test_locking.py
=> Fix test failures on macOS

datalad/core/local/run.py
Instead of switching to `subprocess.run()` (original plan), I still use a runner in order to retain the CommandError raise that might be important to consumers, and simultaneously avoid having to duplicate the CommandError construction logic.
This used to be part of #4996, but has been placed into a standalone PR due to the complications of https://github.com/datalad/datalad-container/pull/131 -- and caused by a no-log behavior of `run` introduced by this PR. Executed commands communicate directly with the terminal.
=> RF: Stop using old-Runner in `run`

datalad/support/archive_utils_patool.py
=> RF: Use WitlessRunner in patool wrapper

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
Turns:
```
$> datalad siblings -s github --publish-depends githubobjects configure
[ERROR  ] expected str, bytes or os.PathLike object, not NoneType [subprocess.py:_execute_child:1453] (TypeError)
```
into
```
% datalad -f json siblings -s github --publish-depends githubobjects configure
{"action": "configure-sibling", "name": "github", "path": "/tmp/gintest", "refds": "/tmp/gintest", "status": "error", "type": "sibling"}
```
However, the default result renderer does not care about such error
results and produces no output. But at least it doesn't crash anymore.
With the default `datalad.log.result-level=info` there is at least an
INFO log message with the error.
However, in general I'd say we discontinue the custom result renderer of
`siblings()` -- it is cryptic without providing a …
=> BF: Prevent a sibling URL from being added when there is none

datalad/core/distributed/push.py, datalad/support/annexrepo.py
Key commit is https://github.com/datalad/datalad/commit/7e27a1d6280df1a24f91f00a7aeacd0a47194374
Exploration is in #5143 and this PR fixes #5143
=> BF: make `datalad push` not fail to push data on first try to Gin

datalad/customremotes/archives.py, datalad/customremotes/base.py
309878904 (RF: Replace old-style custom runner calls in customremotes,
2020-11-11) switched _get_key_path() over to using repo.call_git(),
but it left 'git' in the arguments, leading to a broken 'git git annex
...' call.
Rather than fix the call, just drop AnnexCustomRemote._get_key_path()
because it hasn't had a caller in the code base since 096e2f3ec
(NF+RF: really sketchy initial interface/add_archive_content.py +
swarms of tunes around, 2015-11-09).
---
Sorry, I missed this when reviewing gh-5142.  Spotted it today when thinking about gh-5161 (and gh-4406).
=> RF: customremotes: Remove unused _get_key_path() method

datalad/interface/common_cfg.py, datalad/support/gitrepo.py
Concept: Run a follow-up `git commit --amend` in a runner session that doesn't capture any output, hence can drive any editor properly. This approach allows us to maintain any error message inspection, because these commit calls are unchanged. The interactive edit is a pure add-one, that is only attempted if anyhow possible. It should also not fail in ways that it would not have failed in the previous commit call.
Based on the feedback in gh-4121, the default (non-interactive) behavior
is unchanged. Trigger the interactive behavior via:
`datalad -c datalad.save.no-message=interactive save`
Fixes gh-5004
The primary purpose of this change is to allow enabling in dev environments, in order to get practical experience with the interactive behavior in various scenarios (simple one-dataset …
=> ENH: Allow experimenting with interactive commit-message entry

.github/workflows/benchmarks.yml
As requested [here](https://github.com/con/fscacher/pull/16#issuecomment-729761695).
=> Make benchmark workflow fail if a benchmark slowed down too much

datalad/plugin/tests/test_plugins.py, datalad/plugin/wtf.py
I find our default WTF output great BUT too long/verbose. It makes it actually
hard to cut/paste and/or locate relevant information.  With --flavor short
I aim to provide a shortened/faster version with most important information
Sample output:
- datalad: version=0.13.3.dev230 full_version=0.13.3.dev230-g4f8fe-dirty
- dependencies: cmd:git=2.24.0 cmd:annex=8.20200810+git143-gdee38c54d-1~ndall+1 cmd:bundled-git=2.24.0 cmd:system-git=2.27.0 cmd:system-ssh=8.1p1 cmd:7z=16.02 annexremote=1.4.3 appdirs=1.4.3 boto=2.49.0 exifread=2.1.2 git=3.1.0 gitdb=4.0.2 humanize=2.3.0 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.4.0 msgpack=0.6.2 mutagen=1.40.0 requests=2.23.0 scrapy=1.7.3 wrapt=1.11.2
<details>
<summary>All sections with -S*</summary> 
- configuration<SENSITIVE, report disabled by …
=> Enh wtf short

datalad/interface/common_cfg.py, datalad/interface/run_procedure.py, datalad/interface/tests/test_run_procedure.py
This could be useful to point to extra locations for procedures which might
reside in some subdataset, or an alternative to system/user-wide locations.
E.g. it provides a solution IMHO to https://github.com/datalad/datalad/issues/4802 (alternative to #4803) which avoids need for some new semantic of --dataset in "create" command, thus keeping it possible to do
datalad -c datalad.locations.extra-procedures=$PWD/procedures create  -d . -c mine sub/
as well as
datalad -c datalad.locations.extra-procedures=$PWD/procedures create  -d ^ -c mine sub/
if current dataset is a subdataset within hierarchy.  Or point that location to any other arbitrary location (within subdataset, directory, anywhere).
Some inconvenience for use through Python API, for which I filed …
=> ENH: datalad.locations.extra-procedures to provide extra location(s) for procedures

datalad/distribution/tests/test_create_sibling.py, datalad/support/tests/test_network.py
fails detected while building for ubuntu 18.04 with python 3.6 but also replicate in conda env with `LANG=C`.  I think that later pythons are Ok. I might add more skips later on if we agree that such ugly workaround is ok
=> BF(TST): skip some tests which would fail to Encode a unicode (or just read a unicode file?) with python 3.6

.github/workflows/update-contributors.yml
The last allcontributors-auto-detect build [1] failed with
The `set-env` command is disabled. Please upgrade to using
Environment Files or opt into unsecure command execution by
setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable
to `true`. For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Switch to using environment files.
[1] https://github.com/datalad/datalad/actions/runs/391938310
=> MNT: update-contributors.yml: Avoid deprecated set-env

datalad/distribution/drop.py, datalad/distribution/tests/test_drop.py
Calling `datalad drop` on a file that has too few copies will
confusingly propagate a message from `git annex drop` suggesting to
use --force, an option `datalad drop` does not have.  Replace --force
with --nocheck.
The new message may still be confusing to Python callers of drop()
because it suggests --nocheck rather than check=False, but that's not
a problem unique to this spot and is preferable to reporting the
completely wrong option.
Fixes #5135.
=> BF: drop: Adjust annex's "use --force" message to avoid confusion

datalad/config.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
old description which got it going:  While looking at py-spy stack from long running status I noticed that majority
of time is spent on git config call, triggered by checking for fake dates
config setting. AFAIK for read-only operations, which cannot produce a commit,
it might benefit to skip that check. And _call_git already has that kwarg,
but it is not proxied by "higher-level" helpers.  To avoid breeding workarounds
(like the one RFed within this commit) I decided that we might benefit from
exposing that option in higher-level helpers as well. Then "read-only" invocations could set it to False and we might avoid needless  config read in some cases (I have not done any timing on any prototypical use case which might benefit from this, but I would assume that status or diff might).
What …
=> OPT+BF: annotate read_only git/annex invocations, thread lock read-write git/annex and git-config invocations

datalad/distribution/get.py
I am trying to assess feasibility for using parallelization "by default" by having
[datalad "runtime"]
max-jobs = 6
max-annex-jobs = 6
in my ~/.gitconfig.  To my surprise this had  no effect on  datalad install -r ///openneuro
so I had to dig this hardcoded mapping out, which is done before we consult configuration
for datalad.runtime.max-jobs within parallel.py .  Looking at git log, I had this hardcoded
from the beginning (of adding parallelization to get) and probably never re-considered even
after we added safety measures to ssh connector which now would lock to prevent multiple
password prompts -- an issue which should be resolved at that level and not here for "auto".
=> RF: remove hardcoded mapping to jobs=0 in get._recursive_install_subds_underneath

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
This draft series extends `addurls` with a mode of operation along the lines of what was proposed in gh-5150: using keys specified by the caller, build the tree and register the associated URLs without downloading any content.
=> addurls: Support creating content-less tree from known checksums

datalad/utils.py
shutils ``rmtree()`` [fails to remove file paths that exceed the 260 character limit](https://stackoverflow.com/questions/1365797/python-long-filename-support-broken-in-windows). This led to a testfailure in the removal phase of a temporary annex repo with sha256 backend (see https://github.com/datalad/datalad/pull/5199#issuecomment-737902114).
This change preprends paths under Windows with the magic prefix ``\\?\`` to hopefully enable the removal regardless of path length:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces
=> TST/Win: enable removal of long paths on windows via path prefix

datalad/downloaders/base.py, datalad/downloaders/tests/test_http.py
This PR aims to fix a test failure that surfaced when a re-download attempts to overwrite an existing file (https://github.com/datalad/datalad/pull/5199#issuecomment-737973537). On Windows systems, an ``os.rename()`` will always raise a FileExistsError
if the file exits, while on Unix systems the existing file is replaced silently if the user has permissions, see https://docs.python.org/3/library/os.html#os.rename.
``os.replace()`` appears to be a cross-platform compatible solution, but let's hope that this doesn't break something else - then I could just do it ``if on_windows``.
=> TST/BF: enable overwriting downloads under Windows

datalad/plugin/tests/test_addurls.py
This is a left-over from #5202 that does not apply to maint (https://github.com/datalad/datalad/pull/5202#discussion_r535426621).
The change proposed here fixes one assertion of the test (the changes proposed in #5202 should fix the remaining failure). Instead of testing the commit body of the most recent commit, it tests the most recent commit on the ``DEFAULT_BRANCH`` to make the test pass also in repos that are in adjusted(unlocked) mode.
=> TST: test commit body in the default branch

appveyor.yml, datalad/plugin/tests/test_addurls.py, datalad/plugin/tests/test_plugins.py
Another set of Windows adjustments that should fix the failures that occurred in #5199.
I'm not convinced I did it in the most clever way, in particular, I used Path() to convert hardcoded Posix paths to something that fits to the given operating system. If there are better alternatives, please let me know :)
=> Adjust more tests to work on Windows

datalad/core/distributed/tests/test_clone.py, tools/ci/prep-travis-forssh.sh
See individual commits for descriptions.  I decided to leave the `ls` in the helper script to avoid need to debug in the future (we never look at that output typically anyways)
=> BFs: bug fixes for testing picked up from #5203

appveyor.yml
On maint, all of the plugin tests are now passing on appveyor
(gh-5202), so 7d01545eb1 moved the plugin tests out of the known
failures block.  Unfortunately tests for master's `addurls --key`
feature bring things back to a failing state (gh-5213).
Until this is resolved, move the plugin tests back to the known
failures block in master's appveyor.yml so that every appveyor run
doesn't need to be checked manually.
[ci skip]
---
cc @adswa 
Sorry for partially undoing your hard work, Adina :<
=> TST: appveyor: Move plugin tests back to known failures block

.travis.yml
I am not sure how much we benefit from testing against elderly version 5, and 6 is also
not "current".  Depending on version of git-annex installed we would have older or newer
version used by default, so I decided to instead switch to
- test by default against recently found to be "good" recent version of git-annex
- instead of explicit repo version 6, just use older version in those 2 split runs
this way I think we would just gain better coverage of annex versions without dropping
code/logic coverage (yet to be seen)
I have positioned it against `maint` since I feel it could only benefit from testing against more recent annex, but we might want to make it for `master` instead
Closes #4000
=> RF+ENH: travis - do not explicitly test for annex v 5 vs 6 - rely on default of annex

datalad/downloaders/credentials.py
I failed to find an issue but I know that it annoyed many people, me included,
whenever long secrets such as tokens and keys for AWS were asked to be repeated.
There is IMHO no reason for that since they are never typed in and validation
of correct entry is beyond human capabilities without much straining
A followup to #5218
=> ENH(UX): do not repeat entry for token and aws key/secret

datalad/cmd.py
This approach is copied from IPython. It prevents the crash reported in
gh-5064 by not leaving behind a closed event-loop, but rather any
previously existing one, or `None`.
Fixes gh-5064
=> BF: Save and restore existing asyncio event-loop

appveyor.yml, datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
This series addresses the `addurls --key` issues described in gh-5213.  It uses `git annex examinekey`s recently added `objectpointer` field, which means that `addurls --key` isn't supported on adjusted branches with git-annex versions below 8.20201116 (which includes AppVeyor).
I tested this via `tools/eval_under_testloopfs`; under that, the addurls tests related to `--key` fail before this series.
cc @adswa
=> addurls --key: Use newer examinekey to support adjusted branches

datalad/interface/common_cfg.py, datalad/support/sshconnector.py
Instead of putting sockets into the cache dir. This makes it possible to
place sockets specifically, rather than all cache content. This will
make it easier to workaround filesystem limitations (gh-4075), and
path length issues (gh-5232).
Keep default location unchanged `<cachedir>/sockets`
However, using this location seems suboptimal. $HOME (which contains `cachedir` typically), may be mounted from another machine. `/tmp` is much more commonly used for this on Linux (X Server, KDE, ...), and more likely to be a local drive.
Using this new config makes things work on OSX re pathlength https://ci.appveyor.com/project/mih/appveyor-datalad/builds/36771014/job/r7yif4oct81baee7
=> RF: Use datalad.locations.sockets as dedicated configuration

datalad/plugin/tests/test_addurls.py
The --key functionality added in 45915917f4 (NF: addurls: Support
creating content-less tree from known checksums, 2020-11-25) has two
code paths, batch and non-batch, because batch commands are avoided
when fake dates are enabled [1].  However, as pointed out by @mih in
gh-5163, the non-batch code path is not covered in the CI runs.
Extend test_addurls_from_key() to cover datasets create with
fake_dates=True.
[1] 4d7ada2675 (RF: annexrepo: Disable batching when fake dates are
enabled, 2018-04-13)
=> TST: addurls: Explicitly test --key with fake dates enabled

datalad/distribution/create_sibling.py
There are a range of issues with create sibling (see #5211) and I'm not sure if it is possible possible to make it work, but I at least wanted to start.
=> BF/Win: Towards a working creating sibling command

datalad/install.py
=> datalad/install.py: neurodebian-devel: If git-annex-standalone is not installed, install it

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
For example fix the leaking of git-annex debug output that makes the travis run error. All pulled from #5229
=> Few fixes that address runner behavior

datalad/core/local/tests/test_save.py, datalad/support/gitrepo.py
This is a key piece of decision making, but it is notoriously hard to read and not well designed (all blame on me). Here I am trying to dissect it and put it back together in a more accessible fashion.
The focus is on being more gentle to humans, but it should not suffer a performance-loss.
The diff will look like a rewrite, but I tried to make the individual commits tell a story.
=> Make diffstatus decision making more accessible

datalad/tests/utils.py
a7ecad3af8 (RF: old-Runner test usage reduction, 2020-10-08) dropped
the Runner() import, but it is still used in get_ssh_port().  Use
WitlessRunner() there too.
Fixes #5249.
=> TST: utils: Adjust get_ssh_port() for dropped Runner import

datalad/distributed/tests/test_create_sibling_ria.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_uninstall.py, datalad/distribution/tests/test_update.py, datalad/distribution/update.py, datalad/metadata/tests/test_aggregation.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
As discussed in [gh-5202][1], a good number of ``get_annexed_files`` call sites (all but one in test code) don't account for the returned paths being POSIX paths.  This series hopefully addresses all of the problematic spots.
Here are the potentially affected tests.  I haven't yet tried to remove any of the skip windows decorators.  I think most if not all of them will still fail on windows because of `with_testrepos` or other issues.  @adswa, when you have a chance, would you mind testing these on your windows machine?
- `test_aggregate_with_unavailable_objects_from_subds`
- `test_annex_remove`
- `test_create_simple`
- `test_install_noautoget_data`
- `test_install_recursive_with_data`
- `test_install_recursive`
- `test_reobtain_data`
- `test_uninstall_subdataset`
[1]: …
=> Audit get_annexed_files use

datalad/distributed/tests/test_ria_git_remote.py
test_ria_git_remote.test_bare_git_version_{1,2} create a store with a
dataset and check git-annex operation with both the git remote and ora
special remote.  As of git-annex's 75acf5f44 (improve some edge cases
around partial initialization, 2020-12-14) [1], the operations with
the git remote fail because git-annex has a safety check that aborts
when it encounters a repo that has an annex/objects/ directory but no
annex.version or annex.uuid configuration.
The annex/objects/ directory is created by create_ds_in_store().  This
works fine in the context of the create-sibling-ria command: the git
remote has annex-ignore set to true as the intention is for git-annex
to only operate with the store via the ora special remote.  The above
tests, on the other hand, explicitly check git-annex …
=> TST: ria: Work around new git-annex check

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/clone.py
Fixes #5186 
Sits on top of PR #5254 due to #5253, which is not the same but a somewhat related issue.
Despite @mih's hesitance, I'd like to support RIA stores without any ORA remote. Since an ID based structure for standard, bare annex repos is perfectly valid and requires all the same stuff (URL resolution for example). In such a case this fix would not fix but sabotage the intended behavior. With that in mind, this one-liner is a function, that can be enhanced to first query the store for a to be introduced dataset level layout, that would disable the `annex-ignore` setting.
=> BF: RIA cloning

datalad/local/copy_file.py, datalad/local/tests/test_copy_file.py, datalad/support/gitrepo.py, datalad/support/tests/test_fileinfo.py
This last commit in this series fixes the git-version-dependent `test_copy_file_prevent_dotgit_placement` failure reported in gh-5248.  The first three commits are changes related to `copy-file`s `.git/` guards.
=> Fix recent test_copy_file_prevent_dotgit_placement failure

datalad/core/distributed/tests/test_clone.py, datalad/customremotes/tests/test_base.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py
... if already known to fail on appveyor, I just made it into known_failure_windows
These seems to be the only ones which are erroring or failing in a run against
fresh git annex within datalad/git-annex.  master has some of those and some additional
(would be in a follow up PR after this is merged), but here are the listings for the record
$> grep '\(FAIL\|ERROR\): ' win-maint.txt | grep -e 'datalad\.' | awk '{print $2  $3;}' | sort | nl
1	ERROR:datalad.core.distributed.tests.test_clone.test_ria_postclone_noannex
2	ERROR:datalad.customremotes.tests.test_base.test_get_contentlocation
3	ERROR:datalad.distribution.tests.test_publish.test_publish_fetch_do_not_recurse_submodules
4	ERROR:datalad.distribution.tests.test_publish.test_since_empty_and_unsupported
5 …
=> TST: announce known failure 7 tests on windows github or just generaly windows

datalad/distribution/get.py, datalad/distribution/tests/test_get.py
As of 46d78a8353 (2020-11-18), AnnexRepo.get() uses
_call_annex_records(), which unlike _run_annex_command_json(), raises
a CommandError when git-annex exits with a non-zero status (gh-5163).
Update `datalad get` to catch the exception, extract the json records,
and yield them as results.
Thanks to @adswa for the test case.
Fixes #5260.
=> BF: get: Fix recent regression in error propagation

datalad/config.py, datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/core/distributed/tests/test_push.py, datalad/core/local/save.py, datalad/core/local/tests/test_save.py, datalad/distribution/get.py, datalad/distribution/tests/test_update.py, datalad/metadata/tests/test_base.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
Towards a fix of gh-5137 and various underlying issues.
This is a simplistic dataset workflow that must work across all platforms, as otherwise invalid datasets are being published and consumed.
The included test works on proper filesystems, but fails on crippled ones.
The goal here is to be as unimpacted from test-battery issues as possible. Hence I am going through the cmdine API, not using any testrepos, and only make use of non-highlevel API for querying to-be-tested properties.
Issues:
```
AssertionError: Desired result
{
"gitshasum": "22bcba3c3b058df33d12870782d3cd4d91c8aa94",
"path": "/media/mih/Samsung_T5/tmp/datalad_temp_test_nested_pushclone_cycle_allplatformswdj92o8g/super/sub"
}
not found among
[
{
"action": "subdataset",
"gitmodule_datalad-id": …
```
=> Proper handling of nested datasets in save/push/clone cycle

datalad/distribution/create_sibling.py
So works also on OSX
could be seen among fails against released version on https://github.com/datalad/git-annex/runs/1638321268?check_suite_focus=true#step:12:2515
=> BF: create_sibling cp -- use -R for --recursive and -p for --preserve

datalad/support/annexrepo.py
Key might be relaxed, so there would be no size information.  Example could be found in
https://github.com/datalad-datasets/machinelearning-books
dataset for  H.DaumeIII-A_Course_in_Machine_Learning.pdf  file
Closes #5266
Might not be the best (re)solution but should make code more robust even if total progress indicator would no longer report correct total whenever it is not known.
Also fixed up that https://github.com/datalad-datasets/machinelearning-books dataset for `G.James_D.Witten_T.Hastie_R.Tibshirani-An_Introduction_to_Statistical_Learning_with_Applications_in_R.pdf` file URL for which no longer worked, so updated to new one.
=> BF: filter out Nones while estimating total size to download + safeguard dict access

datalad/distribution/install.py, datalad/distribution/tests/test_install.py
As it is of no effect for awhile -- I have not done investigation when it
started to be of no effect, but it was reported on the matrix forum that
it has no effect in 0.13.5-0.13.7
Since 0.14.0 seems to be not "revolutionary" enough , and option is of no effect, I think it would be ok to just kill it
=> RM: install - remove --nosave/save=False

datalad/core/distributed/tests/test_push.py, datalad/tests/test_install.py
to finally establish a green baseline in datalad/git-annex builds on windows (master is the only one red ATM)
ref: #5271
=> Skip two tests on windows (github CI in particular for one)

datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_save.py, datalad/distributed/tests/test_ora_http.py, datalad/distributed/tests/test_ria_basics.py, datalad/distribution/tests/test_update.py, datalad/distribution/update.py, datalad/support/gitrepo.py, datalad/support/repodates.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_repodates.py
Move the description of the `read_only` parameter to `call_git`, avoid some repetition across `_call_git` and the `call_git*` docstrings, and use `read_only=True` more.
=> gitrepo: call_git*(read_only=True) follow-up

datalad/config.py, datalad/tests/test_config.py
See individual commits for more details/reasoning.
If tests pass (I have not run them locally in full, only local interesting ones) -- I would consider myself done with it, although ideally at least the first commit (actual BF) should ideally be adopted for `maint` as well.
Closes #4644 
most likely it could also "close" #4363 but I failed to reproduce it locally even after reverting #4365 workaround.  Ideally someone might want to go through those explicit `.reload`s we have in the tests and kill them
=> BF+OPT: config - compare full stat records, for "gone" files too, do not bother with 2 sec rule

datalad/downloaders/configs/dockerio.cfg, datalad/downloaders/http.py, datalad/downloaders/providers.py, datalad/downloaders/tests/test_docker_registry.py
An upcoming PR for datalad-container will add a skopeo/OCI-based
adapter for tracking images in a dataset (as an alternative to the
already available docker-save-based adapter).  When the source of the
image is Docker Hub, the layer blobs tracked in the dataset can be
reobtained via a query to the docker.io registry endpoint.
Add a docker-registry:// link type and wire up the datalad special
remote so that datalad-container can assign links to layers.
---
=> NF: downloaders: Support downloading Docker registry blobs

datalad/log.py, datalad/support/parallel.py
Building the handbook based on the current master currently intersperses command outputs with the wrappers of progress bars (``[INFO] Total: starting``, ``[INFO] Total: processed result for ...`` and ``[INFO] Total: done``).
Here is an example:
```
$ datalad download-url http://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-Guide.pdf \
--dataset . \
-m "add beginners guide on bash" \
-O books/bash_guide.pdf
[INFO] Downloading 'http://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-Guide.pdf' into '/home/me/dl-101/DataLad-101/books/bash_guide.pdf' 
download_url(ok): /home/me/dl-101/DataLad-101/books/bash_guide.pdf (file)
[INFO] Total: starting 
[INFO]  
add(ok): books/bash_guide.pdf (file)
[INFO] Total: processed result for /home/me/dl-101/DataLad-101  …
```
=> BF: add a non-interactive mode also to progress bar wrappers

datalad/distribution/create_sibling.py
=> RF(BF?): remove unneded use of quote_cmdlinearg while passing runner a list for cp

datalad/distribution/tests/test_update.py
This series brings test_update.py to a state where all the tests except one pass for me under `tools/eval_under_testloopfs`, dropping three `known_failure_windows`s.  Two of those should be confirmed with the appveyor run here, while one of them depends on a git-annex fix that isn't yet in a release (gh-5290).
The first three commits work when applied to maint as well (i.e. the tess pass under `tools/eval_under_testloopfs`), but the test fixed on the fourth commit requires master-specific handling of submodules on adjusted branches.  I've decided to make a single PR against master for simplicity, given these are test fixes, but I can split off a PR for maint if desired.
=> test_update: Adjusted branch fixes

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
The urlfile argument takes records via a file, but when addurls is
called from the python interface, specifying an iterable of records
can be more convenient.  Add support for that.
Using urlfile as the name for the positional argument doesn't fit for
this particular use case, but leave it as is to avoiding breaking
existing python callers that use it as a keyword argument.
Closes #4906.
---
https://ci.appveyor.com/project/mih/datalad/builds/37138665/job/49lq604vukvu6x69
=> NF: addurls: Support passing list of records

datalad/interface/__init__.py, datalad/local/configuration.py, datalad/local/tests/test_configuration.py, datalad/ui/dialog.py, docs/source/cmdline.rst, docs/source/modref.rst
This closes a long-standing feature gap: a command that can
query and modify configuration across all scopes that are
relevant for DataLad, and also works recursively.
Importantly, it can render an annotated configuration dump,
as a convenient way to determine available configuration options
and effective settings.
try running: `datalad configuration`
The choice of name is somewhat forced by the presence of `.config`
object in every Dataset instance.
Fixes gh-4359
=> NF: `configuration` command

datalad/distributed/create_sibling_ria.py
`git annex trust` requires for `--force` as of git-annex's 6a0030a11
(Behavior change: git-annex trust now needs --force, 2021-01-07),
Fixes #5318.
=> MNT: create_sibling_ria: Call 'git annex trust' with --force

tools/ci/prep-travis-forssh.sh
This should make it first download our tarball export of the docker container
and load it, thus avoiding docker pull AFAIK
Corresponding changes were directly pushed to https://github.com/datalad-tester/docker-ssh-target and mirror of that repository with the actual tarball was shared at http://datasets.datalad.org/?dir=/datalad/docker-ssh-target from which now `setup` script would fetch the tarball
If works, Closes #5288 , and similar changes (just removing `--from`) should be introduced in other CI setups
=> RF(TST): invoke setup-docker-ssh without explicit --from

datalad/distribution/get.py
So far this information is only available in the docstring of an
internal helper, and in the handbook
http://handbook.datalad.org/en/latest/beyond_basics/101-148-clonepriority.html
However, it is an important piece of info that should be easily
accessible, especially when the `get` of a subdataset has just failed.
This specific use case also motivates, in part, the placement of this
information in the `get` documentation.
I will cancel travis and appveyor due to the nature of the diff.
=> DOC: Include information on subdataset clone sources in `get` docs

datalad/customremotes/tests/test_archives.py
Test is about getting system env correctly. So, instead of relying on
PWD being there, set an artificial one and see it passed on.
Closes #5315
=> BF: PWD doesn't exist on windows

datalad/core/distributed/tests/test_clone.py, datalad/core/distributed/tests/test_push.py, datalad/distributed/tests/test_ora_http.py, datalad/distributed/tests/test_ria_basics.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_update.py, datalad/support/tests/test_annexrepo.py, datalad/tests/utils.py
A repeated pattern in the tests is to create a dataset with a path
generated via with_{tree,tempfile} and then raise a SkipTest if the
dataset is on an adjusted branch.  Aside from being a bit harder to
grep for, a problem with this pattern is that it's wasteful.  A
dataset is created for each test, but the temporary directory's file
system isn't changing out from under us, so we can use the same answer
across tests.
Add a skip_if_adjusted_branch() decorator that caches the result,
paying the cost of an additional create() call for file systems that
do not default to adjusted branches.
Another advantage of this new decorator is that, when we realize a
test marked with skip_if_on_windows() actually failed due to more
general adjusted branch issues, we can simply switch the decorator.
=> TST: Add skip_if_adjusted_branch decorator

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
It removes a programmatic assesment of the platform in order to
build a targeted message to be displayed whenever git-annex
cannot be found.
Now the message is generic and saved 1.5s for a wide range of
datalad command executed on the cmdline.
For example, a `datalad create` on Debian drops from 2.5s to 800ms.
now:
```
(datalad3-dev) mih@meiner /tmp % time datalad create s1
[INFO   ] Creating a new annex repo at /tmp/s1 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/s1 (dataset)
datalad create s1  0.59s user 0.27s system 104% cpu 0.833 total
(datalad3-dev) mih@meiner /tmp/s1 (git)-[master] % touch this
(datalad3-dev) mih@meiner /tmp/s1 (git)-[master] % time datalad save
add(ok): this (file) …
```
=> OPT: Speed up _check_git_annex_version()

datalad/interface/rerun.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_rerun_merges.py
This series was prompted by gh-4335.  It tweaks `rerun` and several tests in test_rerun.py to be compatible with adjusted branches in scenarios that don't involve `--onto` and `--branch`.  The remaining scenarios are skipped, and `rerun` now aborts with an informative message.
test_rerun.py no longer shows any failures when I execute it under `tools/eval_under_testloopfs`.
=> rerun: Adjusted branch tweaks

datalad/core/distributed/tests/test_push.py
test_push_recursive() aborts midway through due to unresolved
save/status issues with adjusted branches.  While there are those (and
they've at least been partially addressed on master with gh-5241), the
only change needed to make this test pass for me on maint under
tools/eval_under_testloopfs is switching a --since value away from
using "HEAD" (which is of course off-by-one on a synced adjusted
branch).
=> TST: test_push_recursive: Make rest of test work on adjusted branch

datalad/core/local/tests/test_run.py, datalad/customremotes/tests/test_datalad.py, datalad/support/annexrepo.py
In gh-5333, @mih fixed a case where an assertion was made in the `assert_raises` context, leading to it having no effect.  This series is the result of a wider audit, but I only found two other cases.  The first one (in `datalad.customremotes.tests.test_datalad`) is a bit more involved, and the proposed fix makes changes to master-specific non-test code.  The second one (in `datalad.core.local.tests.test_run`) is a simple fix.  As with the case in gh-5333, both these assertions were silent failures.
=> Audit incorrect assert_raises use

datalad/support/exceptions.py, datalad/support/tests/test_annexrepo.py
Not doing that leaves users largely clueless as to why a JSON-based annex
command might have failed, without interactively debugging it.
This change turn the previous
```
CommandError:
'"git" "annex" "drop" "--json" "--json-error-messages" --" "test-annex.dat"'
failed with exitcode 1 under C:\Users\...\datalad_temp_testrepo_08ix2heg
[err: 'git-annex: drop: 1 failed']
[info keys: stdout_json]
```
into
```
CommandError:
'"git" "annex" "drop" "--json" "--json-error-messages" --" "test-annex.dat"'
failed with exitcode 1 under C:\Users\...\datalad_temp_testrepo_08ix2heg
[err: 'git-annex: drop: 1 failed']
[errors from JSON records: [['git-annex: content is locked']]]
[info keys: stdout_json]
```
The markup is a bit convoluted, but there could be any number of error messages
per result and also …
=> ENH: Report error messages from JSON records in str(CommandError)

.appveyor.yml, tools/ci/appveyor_env_setup.bat
Broaden the coverage of older Pythons, without going orthogonal across, platforms.
- Windows 3.9 (hard to see why anything other than the latest would make more sense here)
- Mac 3.8
- Ubuntu 3.6, 3.7, 3.8 (because CI workers have max performance on this platform)
Also introduce a small debug setup helper to ease interactive sessions on windows.
=> Expand appveyor setup

datalad/core/distributed/tests/test_clone.py, datalad/distribution/tests/test_install.py
In some cases a few test runs end up comparing uuids that fail to exist in the first place, leading to a comparison that evaluates to `None == None`. Make the assumption that there actually is an uuid explicit in order to fail in the spot where it's going wrong rather than a much less telling point later on.
- Closes #4621
=> TST: Test uuids to exist before comparison

datalad/core/local/create.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Note: no other uses of DeprecatedError exception ATM
=> RM: remove url from GitRepo.__init__ -- was deprecated in 0.5.0

datalad/cmdline/helpers.py
The argument for -h/--help/--help-np is wired up with a custom
argparse.Action class, HelpAction.  For an interactive call with
--help and a subcommand, this class looks for a corresponding manpage
file and tries to shell out to man(1), falling back to printing the
help string.
This means that for several common install scenarios, output isn't
displayed with a pager, and there is no distinction between --help and
--help-np.  Given that the help text of most subcommands probably
exceeds common terminal heights, callers need to either scroll up or
do something like `datalad <subcommand> --help | less`.
Make a pager available in these situations by using pydoc.pager() to
display the --help output.  Two notes:
* guarding the use of pydoc.pager() with datalad's is_interactive()
isn't essential …
=> ENH: cmdline: Use pydoc pager for --help

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/get.py, datalad/local/subdatasets.py
Record original URL when creating a subdataset by cloning and let `get`
consider it before submodule's url. This makes a difference, if the
datalad URL contains pieces to be interpreted by datalad rather than git
like a "ria+" prefix, which is supposed to trigger post clone routines.
Closes #5256
=> NF: datalad-url in .gitmodules

datalad/distributed/ora_remote.py
Used to be optional, but recent git-annex will not accept parameters to
initremote that are not listed in its response to LISTCONFIGS if there
was a response to begin with.
=> BF: All params in ORA's response to LISTCONFIGS

datalad/cmd.py, datalad/tests/test_witless_runner.py
If BlockingIOError remains an issue, this change might have it resurfaced in
those use cases where datalad is used within some other asyncio app/script.
But at least it seems to mitigate current complete inability to use datalad
within asyncio scripts such as the minimal one provided by @djarecka:
import asyncio
asyncio.get_event_loop()
import datalad.api as datalad
datalad.clone(path='/tmp/afni', source="https://github.com/afni/afni_data.git")
asyncio.get_event_loop()
Was not sure if not too radical for `maint` but let me know ;)
Alternative to #5314 
TODOs (if we decide that it is a way forward):
<details>
<summary>FWIW -- benchmarks are suggesting some speedups</summary> 
```shell
before           after         ratio
[6945d71d]       [7c34a334]
<bm/merge-target>       <bm/pr> …
```
=> RF: cmd - reuse asyncio loop if there is one, start/close new one otherwise

datalad/metadata/search.py
Fixes #5349
Missing indexers are now reported on DEBUG level instead of INFO level. In addition,
each missing indexer is reported only once.
To support reduced reporting without changing the existing signatures too much and
without carrying unrelated objects into functions, the InstanceStorage class was created.
It provides singleton storage objects, addressed by their purpose, i.e. an entry in an
Enum, that exist for the duration of the datalad invocation, i.e. as long as the
current python process is executed.
=> BF: Flooding INFO log with messages non-consequential to users

datalad/distributed/ora_remote.py, datalad/distributed/tests/test_ria_basics.py
Special remotes being set up via --sameas don't have a 'name' config to
query but only a 'sameas-name'.
(Closes #4259)
=> BF: make ORA aware of sameas

datalad/cmd.py, datalad/support/tests/test_parallel.py, datalad/tests/test_witless_runner.py, datalad/tests/utils.py
To overcome a problem with unruly super processes, ref: https://github.com/ReproNim/testkraken/issues/95 may be just on OSX.
We will track if we are trying to run in a new PID, and if new - we will first test if we can run a command in the default loop, if not -- we revert to "old ways" for that PID to start loop for each process
@djarecka please check if works for you.  Tried on OSX with 3.7  on testkraken -- seems to be "good as old" ;)
Also adds a known failure for parallel on osx, closes #5309
Checked on a local VM, it also seems to Closes #5362 (although I am not yet 100% sure why/how since we are not catching NotImplementedError ;))
=> BF: in a new process, test first if we can run any command, and if not - old ways

datalad/tests/test_witless_runner.py
First it was failing because paths strings on windows contain \ so I had
to announce those strings as r(aw).
But then test still fails since apparently on windows (with 3.7, not
3.8) there is no event loop for some reason, and get_event_loop() would
just raise RuntimeError.  Since "tuning" the reproducer might actually
change the use case we are trying to test (which works on other
environements), I decided to just announce it a skip.
First observed during datalad/git-annex  repo daily tests against master (this should be the last one -- otherwise all clear!)
=> BF(+skip): r- path strings, skip test_asyncio_loop_noninterference1 on windows for python < 3.8

datalad/metadata/search.py
0cd1635c05 (MNT: Avoid invalid escape sequences in strings,
2019-05-17) did a tree-wide clean up to avoid "DeprecationWarning:
invalid escape sequence" warnings, but another case was introduced
since then.
=> DOC: search: Fix an invalid escape sequence

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
This is a to be discussed proposal.
The issue is that `clone` - if ordered to checkout a particular version and fails to find that commit - fails, but leaves the cloned repo as is. Arguably that might be okay-ish when called directly, but if `clone` is called from within `get` to retrieve a subdataset we get the wrong thing, leave it (modified) and in the recursive case even start to get its subdatasets.
This approach would always kill such a failed attempt. Probably needs a switch or config. The alternative to only let the caller do that seems rather difficult if I look into `get`.
What do you think, @datalad/developers?
Closes #5387
=> Don't leave failed clone behind

datalad/__init__.py, datalad/core/distributed/tests/test_clone.py, datalad/tests/test_base.py, datalad/tests/test_config.py, datalad/utils.py
Windows brings us many joys, including also having not just USERPROFILE but also HOMEDRIVE and HOMEPATH, so resetting USERPROFILE itself is not totally kosher alone.  Also, we could have PATH (e.g. in git shell) defined too even on Windows, so it is not sufficient to just reset USERPROFILE.
So in the first commit I have added a function to set only the variables known to current os.environ, and use of that one instead of hardcoded use of USERPROFILE vs HOME in test_clone seems to make that test pass for me for both py 3.7 and 3.8 on windows.  If confirmed that other Windows gurus are happy, then Closes #5338 (merge conflict will be minimal when merging into master for that test, didn't check overall though).   I have tuned up a few other tests where I found `HOME` to be used without …
=> BF+RF: Consistent and more "thorough" handling of fake HOMEs (including Windows)

.appveyor.yml
A recent AppVeyor run [*] failed with
bash <(curl -s https://codecov.io/bash)
/dev/fd/63: line 2: syntax error near unexpected token `<'
/dev/fd/63: line 2: `<html><head>'
Command exited with code 2
Presumably that was due to a transient connection error.  Extend the
curl call with -f so that the failure is mapped to a non-zero exit
rather than reporting HTML on stdout.  Also add -S so that a
meaningful error is shown on stderr:
$ curl -sfS https://codecov.io/bashh
curl: (22) The requested URL returned error: 404
$ echo $?
22
[*] https://ci.appveyor.com/project/mih/datalad/builds/37574008/job/ja1eg9dbv2jhwmfr
---
I've canceled all builds aside from the appveyor one.
=> TST: appveyor: Improve error reporting of codecov.io download

datalad/auto.py
Closes: #5379
Not yet sure how it was not triggered before or why not triggered with other pythons, so did not come up with some new dedicated test.
Also may be there is more levels of inception here and a single `bool` would not be enough (or I might somehow enter multiple times and thus better keep a counter or alike), but at least it resolve the hanging I replicated on my laptop.
=> BF: auto - do not proxy anything while trying to establish an AnnexRepo instance

datalad/downloaders/tests/test_docker_registry.py
This test has started to occasionally fail, presumably due to rate
limiting.  Execute it only for cron jobs to hopefully avoid that.
Closes #5405.
=> TST: docker_registry: Restrict test to CI cron jobs

datalad/log.py, datalad/tests/test_log.py, datalad/utils.py
get_initialized_logger() used to add two handlers to the logger for
interactive calls:
* a plain log handler with a filter to remove dlm_progress records
* a ProgressHandler with a filter to keep dlm_progress records
Since 8f776d396e (ENH: make ProgressHandler emit via default handler
if not a progress record, 2020-10-12), only ProgressHandler is added
as a handler, and its .emit() relays non-dlm_progress records to the
plain handler.
This change causes `test_log.test_filters` to fail when executed with
--nocapture:
AssertionError: 'log3' unexpectedly found in
'[DEBUG] log1\n[INFO] log2\n[INFO] log3\n
The non-test aspect to the failure is that the target name filter that
is added to the plain logger isn't honored in the new arrangement.
Fix that by adding those filters to …
=> log: Add target name filters to ProgressHandler

datalad/support/annexrepo.py
This series makes two changes to AnnexJsonProtocol:
* corrects a bug in the progress bar ID calculation that resulted in using the same ID across concurrent operations on different files
* adds the file name to the progress bar
Together these fix gh-5419.
=> AnnexJsonProtocol progress bar fixes

datalad/core/local/run.py, datalad/core/local/tests/test_run.py, datalad/interface/rerun.py, datalad/interface/tests/test_rerun.py
Provide a way to avoid the cost of preparing specified inputs and
outputs.
Closes #3005.
Closes #3206.
=> NF: run, rerun: Add --assume-ready option

datalad/resources/procedures/cfg_metadatatypes.py, datalad/resources/procedures/cfg_text2git.py, datalad/resources/procedures/cfg_yoda.py
There might be an issue with the server I'm using, but I have been getting the following error when trying to create a datalad dataset with -c text2git. Using datalad 0.14.0
```
(base) [xcpdev@cubic-login1 production]$ datalad create -c text2git -c yoda --description "${PROJECTNAME}" . 
[INFO   ] Creating a new annex repo at /cbica/projects/xcpDev/testproj/production 
[INFO   ] Scanning for unlocked files (this may take some time) 
[INFO   ] Running procedure cfg_text2git 
[INFO   ] == Command start (output follows) ===== 
/cbica/projects/xcpDev/testproj/miniconda3/lib/python3.8/site-packages/datalad/resources/procedures/cfg_text2git.py: line 1: Procedure to configure Git annex to add text files directly to Git: command not found
import: unable to open X server `' @ …
```
=> Add python interpreter path to cfgs

datalad/tests/utils.py
When writing a test recently, I noticed that the error message for `assert_not_in_results` is empty.  This PR makes it more like `assert_in_results`:
```
AssertionError: Result
{
"action": "unlock",
"path": "/tmp/datalad_temp_tree_test_unlock_directory9n0g56ut/dir/b"
}
unexpectedly found among
[
{
"action": "unlock",
"path": "/tmp/datalad_temp_tree_test_unlock_directory9n0g56ut/dir/b",
"refds": "/tmp/datalad_temp_tree_test_unlock_directory9n0g56ut",
"status": "ok",
"type": "file"
}
]
```
=> assert_not_in_results: Make failure message more helpful 

datalad/ui/progressbars.py
Original odd experience was reported in https://github.com/datalad/datalad/pull/5421#issuecomment-784316274 and it was
due to interplay of two factors:
1 - Total is updated only after git-annex verifies the checksum.
Total progress bar is updated only upon the final "ok" from git-annex
that we got the file.  That also involves validation of the checksum by
git-annex. So, even though file is finished downloading, and its progress bar
disappeared, Total would not be updated until that file is "ok"ed by annex.
That takes time, so perceptually to the user  (me) it was odd that Total shows
only some little total although a good number of files already "downloaded"
Good news: since Joey implemented "on the fly" checksumming (at least for
built in "special remotes") -- with e.g. …
=> ENH(UX): set "smoothing=0" for any progress bar with "total" in its label

.appveyor.yml, .github/workflows/test_macos.yml, .travis.yml
Without --sudo ok  it now will ask user to confirm sudo operations by default.
We do have 1 matrix run which installs a .deb so it would need sudo.
Without eval it is impossible to pass  -e  options like I needed in a
https://github.com/datalad/datalad/pull/5442  so I decided to just have it
by default here
OSX tune up might have not been needed -- did not check. but better be safe than sorry ;)
PS resubmitting now against `maint`
=> BF: need to eval debian_installer call, and now we have --sudo option to allow sudo ops

.appveyor.yml, .github/workflows/test_macos.yml, .travis.yml
In order to not be forced to adapt CI scripts whenever datalad-installer changes its interface, respect DATALAD_INSTALLER_VERSION env var that specifies a version to install and use it with pip-install. Default to latest pypi release.
That variable is currently set to the current release `==0.2.0` for datalad.
ping @mih
=> RF: Parameterize installer download

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
Setting the publication dependency for 'origin' on an ORA remote in
postclone routine didn't properly account for multiple accessible ORA
remotes or the fact that none of them may be associated with the RIA
store we are cloning from.
Now, first check for an ORA remote with the same store URL registered
and if there is none check whether the store has a remote's uuid stored
in the .git/config of the dataset. If we have that remote enabled, set
the dependency on it.
=> Fix RIA/ORA publication dependencies

datalad/distributed/create_sibling_ria.py, datalad/distributed/ora_remote.py, datalad/distributed/tests/test_create_sibling_ria.py
Expose ORA's new `push-url` in `create-sibling-ria`. This is used to configure the ORA special remote as well as to create the sibling in store.
=> ENH: optional push-url for create-sibling-ria

datalad/core/distributed/tests/test_clone.py, datalad/core/local/tests/test_save.py, datalad/support/gitrepo.py
Prevent a `save` failure when `diff.ignoreSubmodules` is configured to a non-default value.
Fixes #3462.
=> gitrepo: Call git with '-c diff.ignoreSubmodules=none'

datalad/log.py, datalad/tests/test_log.py
I have ran into a use case where external library logs an exception, but then
our logger starts puking.  Default formatter tollerates them just fine, so we
better do too.
=> BF: log - accept non-str (but str()-able) instances

datalad/interface/tests/test_unlock.py, datalad/interface/unlock.py
This destroys the logic within status that is based on "raw" input. In the particular case triggering this PR, `status` wouldn't realize the original call was passing `.` as the `path` argument.
Closes #5456
=> BF: Unlock used to pass resolved paths to status

datalad/__init__.py, datalad/cmd.py, datalad/interface/common_cfg.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py
This series addresses gh-5382.  The first commit fixes a test bug that was revealed by the `datalad-sshrun` switch, the second does the actual switch, and the rest are non-essential tweaks on top.
=> Tell git-annex to go through datalad-sshrun

datalad/core/local/save.py, datalad/core/local/tests/test_save.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Looking into a resolution of #3244 (and subsequently #5412).
Introducing `--amend` for `save`. By default this keeps the previous commit message if none was passed to save. `--amend` can not be applied recursively for now (see #5455 ).
- minor fix: `GitRepo._call_git` didn't respect its `env` parameter
- minor fix: `save` exited zero w/o a result when called on empty repo (no commit or empty commit only). Now: either `notneeded`     or proceeds in case of `--amend`.
- minor enh: `GitRepo.update_ref` now optionally takes `oldvalue` parameter
=> ENH: Amending commits

datalad/core/local/tests/test_create.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
DataLad still uses the annex.backend**s** option, but since git-annex 6.20170510, annex.backend is the preferred name.  annex.backends was kept for compatibility and offers no additional functionality.  This series switches to using annex.backend.  It also changes `set_default_backend(..., persistent=True)` to no longer set a shadowed backend value in `.git/config`.
=> Don't use old annex.backends option

datalad/distributed/ora_remote.py
Still using `io` instead of `push_io` when checking for whether or not
we can write was an oversight when introducing push-url to ORA remote.
Closes #5471
=> BF: use push_io to check ability to write

.github/workflows/test_extensions.yml
This extension is undergoing a substantial change. There is no point
in testing it. Given that the list of tested extension here is
also an abitrary subset of existing extension, there is also little
point in changing the workflow to use the latest extension release.
Targeting `maint`, but needs pickup in `master` too.
=> Tst nometalad

.github/workflows/test_extensions.yml
As suggested in PR #5479, test against datalad-hirni, which became more vital to do with metalad being gone from the list for now.
=> TST: Add datalad-hirni extension

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
This is #5415 but against `maint`
=> Fix publish-depends for ORA remotes in clone (in maint this time)

datalad/support/keyring_.py
Before one would need to spend 10-15min to discover how exactly this is
working. Now `--log-level 5` will give a hint:
```
[Level 5] Credentials lookup attempt DATALAD_webdav.4shared.com_password
[Level 5] Credentials lookup attempt DATALAD_webdav.4shared.com_user
```
Should not hurt anyone. Isn't beautiful either, but having to override
credentials is a relatively frequent task in development, but also in
environments without credentials stores (HPC...). Knowing the names of
the variables is key here.
=> Leave a log trace which env vars are queried for credentials

.appveyor.yml
Decided to use stock debian build instead of ours on datasets.datalad.org
since those are standalone and thus slower
=== Do not change lines below ===
{
"chain": [],
"cmd": "sed -i -e s,ftp.us.debian.org/debian/,snapshot.debian.org/archive/debian/20201228T023115Z/,g .appveyor.yml",
"exit": 0,
"extra_inputs": [],
"inputs": [
".appveyor.yml"
],
"outputs": [
".appveyor.yml"
],
"pwd": "."
}
^^^ Do not change lines above ^^^
=> [DATALAD RUNCMD] BF: use snapshot repo url for git-annex for .deb

datalad/support/sshconnector.py
This should prevent race condition between testing if socket path
already exists and establishing it.
Closes: #5460
Related issues discovered while troubleshooting for this one are
https://github.com/datalad/datalad/issues/5465
https://github.com/datalad/datalad/issues/5464
=> BF: interprocess lock for checking/opening ssh socket connections

CONTRIBUTING.md, datalad/cmd.py, datalad/core/distributed/tests/test_clone.py
This PR updates the runner's "Async run ..." debug-level logging messages to include current working directory (taking care of gh-5487, though not through the requested `DATALAD_LOG_CWD`) and removes `DATALAD_LOG` options that were only relevant for the old runner.
=> WitlessRunner: Log current working directory

datalad/core/local/run.py, datalad/core/local/tests/test_run.py
If outputs aren't present (and thus can't be unlocked), run() removes
them so that the command doesn't need to provide special handling of
annex links.  This is done with `datalad remove`, which calls git-rm
underneath. `git rm path/to/file` deletes the leading directories when
they are otherwise empty.
That behavior can be surprising for commands that don't ensure
outputs' directories exist.  Instead unlink the file directly so
leading empty directories stick around.  Unlike git-rm, this doesn't
remove the file from the index, but the end result is the same after
the save (even if the command ends up not recreating the output).
Note, however, that ideally commands should be written to not assume
that the output directory exists in HEAD's tree.  This makes them
better suited to be used …
=> run: Don't remove leading empty directory when removing outputs

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
update(..., recursive=True) calls git-fetch in every subdataset.  When
using follow=parentds to follow the commit registered in the parent
dataset, this can lead to many unneeded fetches, especially when only
a few subdatasets need to be updated.
Add another --follow value, "parentds-lazy", that is like "parent-ds"
but fetches only if the commit isn't already present and avoids
processing the dataset entirely if the registered commit is already
checked out.  Keep "parentds" around because, as mentioned in gh-4452,
the caller may still want to fetch from the sibling to, e.g., bring in
updates to the git-annex branch.
Note that in cases where the registered commit is already checked out
in a subdataset and the subdataset is unmodified, we could
conceptually skip descending into deeper …
=> update: Add minimal fetching --follow=parentds mode

datalad/__init__.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Protocol's buffer could get filled up before the entire json line is
actually received, so the AnnexJsonProtocol could then receive only a
part of it, and fail to parse such a partial json entry.
The patch is a bit overdone: in principle I think
not data.endswith(os.linesep.encode())
condition could be dropped, but I think it should not hurt since we are not
expecting new lines in the output within records, thus if the trailing symbol
in the entire data is a newline, it would mean that we did read the entire line
and thus we should not try to join it with the next one.
I am not sure if similar "I care about lines" behavior is relevant to other
WitlessProtocols and might need to be adjusted similarly.
Closes #5393
TODO:
individual commits (adjusted more while crafting the tests) might have …
=> BF: AnnexJsonProtocol - memoize the last line which failed to json load

datalad/config.py, datalad/support/gitrepo.py, datalad/tests/test_config.py
This PR (in order of importance):
- fixes handling of multi-line values (all but the first line were ignored before)
- introduces a unit test for this function
- adds more documentation
- robustifies the parser to be able to work with contaminated output (fixes #5502)
Although this series slightly complicates the processing in this critical function, I do not observe a performance impact (see commit message).
=> Test, documentation, fixes and public introduction of parse_gitconfig_dump()

datalad/support/archives.py, datalad/utils.py
Inspired by #5507 this aimed to removed the usage of `mktemp()`, deprecated since Python 2.3 (or in other words: deprecated already before any of this code was writen).
While this PR removed some cases, in others things are too intertwined to anyhow consider the necessary effort justifiable for inclusion in `maint`.
Fixing a bunch of log message calls with needless unconditional string formatting on the side, and complaining about the general behavior of `make_tempfile()`, too. The `resolve()` done in there could be one of the reasons for slowed performance of the test battery -- it is executed *a lot* and resolve can be slow, depending on the file system conditions.
=> Reduce usage of mktemp()

datalad/plugin/tests/test_addurls.py
Following @mih's efforts from gh-5511, TestAddurls.setup_class() is
one of the remaining spots that use mktemp().  This call could be
switched to mkstemp/NamedTemporaryFile, but setup_class() already
creates a temporary directory with mkdtemp() to use for HTTPPath
content.  Place the JSON file under this directory, moving the content
to a subdirectory.
Note that teardown_class() should have taken care of removing the
temporary JSON file but didn't.  It will now be handled with the
removal of the temporary directory.
=> TST: addurls: Avoid deprecated/racy tempfile.mktemp

datalad/metadata/extractors/tests/test_rfc822.py, docs/source/metadata.rst
This provides an unambiguous and machine readable way to reference licenses.
I am not sure if this way of specificaing the license is the right way (see https://github.com/datalad/datalad/issues/5496), but switching to SPDX is a quick win.
=> DOC: Use SPDX License Identifiers/Expression for License metadata

datalad/dataset/__init__.py, datalad/dataset/gitrepo.py, datalad/dataset/repo.py, datalad/dataset/tests/__init__.py, datalad/dataset/tests/test_gitrepo.py, datalad/distribution/dataset.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
This replaces #5335 with an even less ambitious goal of simply having a class and a set of tests to extend later. The reason for the continued downscaling are two previous attempt to wanted more, but achieved nothing.
In contrast to #5335 there is not functionality on state reporting or comparison in this PR anymore. It is merely the code needed to point to a local repo and run `call_git*()` methods.
As discussed before, this is no-longer targeting `.core` until more complete and more stable.
=> 3rd attempt to establish a core GitRepo class

datalad/config.py, datalad/distribution/create_sibling_github.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This is a central place for logic of pushing refspecs used by push and publish,
so I decided to fix in a single spot instead of duplicating logic or providing
yet another additional wrapper, and thus possibly of help to any other code which
uses .push().
Note:
- logic is in effect only if remote and refspecs are provided. So it will be
of no effect if either of those not provided, but most likely there would be
no relevant use case since it would require manual configuration first of the
refspecs and default remote for a branch within config before submitting a push
Qs:
-  may be logic should move even deeper into  push_ generator?
-  ideas on how to establish testing for this, without interacting with github, since it seemed we encountered such behavior on pushing multiple refspecs at …
=> BF/RF: GitRepo.push -- push first refspec separately first for github (or if remote.{remote}.datalad-push-default-first is set)

datalad/config.py, datalad/interface/tests/test_run_procedure.py, datalad/tests/test_config.py, docs/source/config.rst
ConfigManager allows setting options via environment variables, where
the option name is constructed from the environment variable by
mapping two underscores to a hyphen and one underscore to a dot.  With
this system, some options aren't accessible.  Taking the example from
gh-5503: `datalad.procedure.NAME.call-format` cannot be set with
`DATALAD_PROCEDURE_NAME_CALL__FORMAT` when `NAME` (based on the
procedure file name) includes an underscore or an upper case
character.
Lift this restriction by adding support for a DATALAD_CONFIG_OVERRIDES
environment variable whose value is a JSON record with configuration
values.  These values have a precedence just below values set directly
via DATALAD_ environment variables.
Fixes gh-5503.
---
cc @bpoldrack
From the datalad standpoint, this is …
=> config: Allow options to be set via DATALAD_CONFIG_OVERRIDES

datalad/cmdline/helpers.py, datalad/cmdline/main.py, datalad/interface/base.py, datalad/interface/tests/test_base.py, datalad/plugin/addurls.py
This series updates the argument parsing logic so that parameter names for positional options can use underscores.  The third commit contains a fix for a type bug that I ran into while testing this.  The last commit contains the main fix.
Closes #2269.
cc @christian-monch
=> interface: Allow positional arguments with underscores 

datalad/interface/download_url.py
Since de9d692318 (ENH: download_url: Use trailing separator to signal
directory target, 2019-11-01), the path value is treated as a
directory if a trailing separator is given and as a regular file
otherwise.  --path's description mentions this, but the behavior can
be surprising/confusing, so add examples to highlight the behavior.
Closes #5528.
---
The example section in `datalad download-url --help` now includes
```
Append a trailing slash to the target path to download into a
specified directory::
% datalad download-url --path=data/ http://example.com/file.dat
Leave off the trailing slash to download into a regular file::
% datalad download-url --path=data http://example.com/file.dat
```
The Python help now includes
```
Append a trailing slash to the target path to download into a …
```
=> DOC: download-url: Add examples of path's trailing slash behavior

datalad/distributed/create_sibling_ria.py, datalad/distributed/tests/test_create_sibling_ria.py
create-sibling-ria missed out on calling `git update-server-info` after
setting up the remote repository. This would result in an unsuccessful
fetch at the end and would need a push to be fixed (since post update
hook is enabled).
Closes #5530
=> BF: Sibling setup missed update-server-info

datalad/interface/tests/test_add_archive_content.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This series fills in the `batch=True` functionality of `AnnexRepo.whereis`, replacing the noop to-do warning from when the `batch` parameter was introduced in v0.3 (2016).
Note that this PR's base is master, but the branch is on top of maint.  That is so that the bug fix in the first commit can be merged to maint (if desired).
Closes #5457.
=> annexrepo.whereis: Implement batch=True

datalad/interface/utils.py
When rendering results as json, the message and logger fields are
dropped.  Information about the logger seems unlikely to be useful,
but filtering out the message can lose information that's not
available elsewhere, particularly for commands that put a caught
exception in the message field of status=error results.
The message has been filtered out since result handling was introduced
in v0.6.0.  2747ed1928 (RF: Centralize logging in result evaluation,
2017-03-02) doesn't give an explicit reason for this, but it's likely
because the message can be a `(<format string>, <value>, ...)` tuple,
and those values aren't necessarily JSON serializable.  However, this
should no longer be an issue as of v0.11.0 because json.dumps() is
called with a default=str.
Retain the message in the json …
=> interface: Include message in json{,_pp} output

datalad/core/local/run.py, datalad/interface/add_archive_content.py, datalad/interface/tests/test_add_archive_content.py
When 'datalad add' was deprecated, a few spots in the documentation
slipped past the tree-wide `s/add/save/` update.
(Aside from the changelog, it looks like the only remaining use of
'datalad add' is in a generated file,
docs/source/basics_nesteddatasets.rst.in.)
=> DOC: Replace leftover 'datalad add' with 'datalad save'

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/core/local/diff.py
Remote repositories must exist for push already, and might have hooks enabled to process the "clean" state of the repository. In hooks we deploy with web-ui e.g. we "aggregate" information about sizes within submodules.  For that to work correctly, submodules should be pushed first, and not after their "superdatasets".
No reason/use case comes to mind why we might want to push super datasets first (besides that they are more "readily" analyzable, so `push` might start pushing sooner), and original commit 9796a5ff seems to not state specific choice for the breadth-first behavior.
Closes #5410
TODOs:
- ~~fix up the test (or code) which I marked to be skipped to do the sweep~~ magically "Fixed" itself and @yarikoptic wonders if may be related to git-annex version boost
=> BF/RF: push - get diff depth-first not breadth-first

datalad/core/distributed/tests/test_clone.py
test_expanduser() is failing in the Conda build for 14.1 with
fatal: unable to auto-detect email address (got 'conda@9bc15aa8a5d2.(none)')
It's not clear why this issue has only just shown up, but
test_expanduser() can't rely on user.name and user.email being set
because it switches away from the test home set up by
datalad.setup_package().  Set up user.name and user.email in the new
home to ensure that there is a usable identity.
Re: https://github.com/conda-forge/datalad-feedstock/pull/55
---
=> TST: clone: Ensure valid identity when patching HOME

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
* Update `GitRepo.add_` to use `annex.gitaddtoannex` instead of `annex.largefiles` to direct files to Git.  See the message of second commit for the background.
* Update the associated regression test for a change in git-annex's behavior.
=> gitrepo: Direct files to git with annex.gitaddtoannex

datalad/cmdline/common_args.py, datalad/cmdline/helpers.py, datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py, datalad/core/local/tests/test_run.py, datalad/customremotes/main.py, datalad/interface/tests/test_base.py
I might have went a little too wild, but I felt that having clean output
of datalad --version is nice -- it could facilitate use by scripts since
would no longer need parsing etc (but also might break them now).
So here is how it would look now with these changes:
$> datalad --version
0.14.1.dev129
$> datalad install --version
datalad 0.14.1.dev129
$> datalad containers-list --version
datalad_container 1.1.2
$> git-annex-remote-datalad --version
datalad 0.14.1.dev129
Closes #5527
edit: a side effect, it also addresses #3067 which was worked around via adding `--` to separate out command for `datalad run`. Now would even work in the `datalad run whatever --version` without `--`
=> ENH: Make --version output just version, and CMD --version output module and its version

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py
When --name isn't specified, create-sibling will use the hostname for
an SSH URL and "local" for a local path.  At the default logging
level, however, the caller isn't told what the selected name is.  And,
for scripting purposes, the name can't be easily determined because
it's not available in the result record.
Promote the debug-level message about the default sibling name to an
info-level message, and add a "sibling_name" field to the result
record.
Closes #1986.
=> ENH: create-sibling: Make default sibling choice more accessible

datalad/support/gitrepo.py
They are either trivial, unused, or obsolete.
https://github.com/datalad/datalad/issues/4873#issuecomment-687629687 called for a deprecation cycle. This change starts that cycle.
=> RF: Deprecate GitRepo.*_submodule() methods

datalad/api.py, datalad/cmdline/main.py, datalad/distribution/dataset.py, datalad/interface/common_cfg.py
Calling get_interface_groups() with include_plugins=True was marked as
deprecated in gh-5554.
Update: And also remove `datalad.locations.{system,user}-plugins` options.
=> MNT: Don't call get_interface_groups with include_plugins=True

datalad/tests/test_api.py
echoing the meetup discussion
I took liberty of removing MIH comment, but we could bring it back if so desired
=> RF: test that ex-plugins have "dataset" as the first posarg

datalad/distribution/create_sibling_github.py, datalad/distribution/tests/test_create_github.py, datalad/interface/base.py, datalad/support/github_.py, datalad/support/tests/test_github_.py
Primarly turns the command into a normal DataLad command that emits result records.  But it also changes a number of other small bits and pieces. I tried to keep the individual commits sensible and reasonably well described in their messages.
Fixes #5548
=> Bring create-sibling-github to the modern age 

datalad/__init__.py, datalad/tests/utils_testrepos.py
git-annex is having issues with those:
https://github.com/datalad/datalad/issues/5277
But even if that is fixed, it is still suboptimal to use a URL scheme as
primary testing target that not only needs to be specifically enabled
first, but is also explicitly advised against.
From https://git-annex.branchable.com/git-annex:
> List of URL schemes that git-annex is allowed to download content from. The default is "http https ftp".
> Think very carefully before changing this; there are security implications. For example, if it's changed to allow "file" URLs, then anyone who can get a commit into your git-annex repository could git-annex addurl a pointer to a private file located outside that repository, possibly causing it to be copied into your repository and transferred on to other remotes, …
=> TST: Stop using file:// URLs in test repo annex setup

datalad/plugin/tests/test_plugins.py
test_no_annex() has started to fail frequently on the CrippledFS runs.
I can trigger it with `tools/eval_under_testloopfs` locally.
The underlying issue is that if a file is added to the annex but the
annex.largefiles configuration would send it to git, that file will be
sent to git the next time the clean filter runs on it.  In the context
of this test, the test failure is sporadic because the clean filter
runs on the file ("code/inannex") only when its mtime matches
.git/index's.
I don't know why the above failure has started to happen much more
frequently, and, as mentioned in the git-annex link below, I'm not
sure what expectations here should be.
Avoid the intermittent failure by forcing the mtimes to be the same,
and updating the assertion to expect a dirty tree.  That should lead …
=> TST: no_annex: Avoid racy failure on adjusted branches

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
This is a work-in-progress series that extends `update` with the `reset --hard` functionality proposed in gh-5498.  It needs more tests, at the very least.  I'd be interesed in feedback on the names, the addition of two options, and keeping `--merge` around.
=> update: support `reset --hard` action

datalad/__init__.py, datalad/support/tests/test_annexrepo.py
Was broken by https://github.com/datalad/datalad/pull/5332
=> BF: Pre-population of testrepos already needs HTTP test server setup

datalad/interface/results.py, datalad/interface/tests/test_results.py
In this case, there should be no 'path' property at all.
Established a place to have any tests for the result utility code.
Far from being comprehensive...
Closes #5490
=> BF: annexjson2result() could not handle file=null results

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This method is used nowhere in the code, and its obsoleteness
was put in an issue more than a year ago.
Closes #4132
=> RF: Remove GitRepo.pull()

datalad/support/annexrepo.py
Infected with normalize_paths(), only used by `publish()`. Can be removed together with the already deprecated publish().
Closes #4884
and helps with #4595
=> RF: Deprecate AnnexRepo.copy_to()

datalad/core/local/run.py, datalad/core/local/tests/test_run.py, datalad/interface/tests/test_rerun.py, datalad/support/globbedpaths.py, datalad/support/tests/test_globbedpaths.py
This series fixes two glob-related issues with run:
* Output patterns are now re-globbed to capture changes when needed (first commit).
#3448
* If an input glob doesn't match, an error result is now returned (last commit).
#5583
The commits in between are mostly focused on preparing the `GlobbedPaths` helper and tests for the last commit.
=> run: Two --input/--output glob fixes

datalad/support/github_.py, datalad/support/tests/test_github_.py
A few spots in the code base instantiate GithubException with two
arguments, but in PyGithub v1.55 (released today) GithubException and
its subclasses require an additional argument (`headers`).
Add a helper that tries to create an exception with three arguments,
falling back to two arguments for compatibility.  Note that using None
for the headers follows what was done in the upstream commit,
ddd437a7c (Export headers in GithubException).
Closes #5602.
=> MNT: github: Add compatibility wrapper for GithubException

datalad/support/external_versions.py, datalad/support/tests/test_external_versions.py
Inspired by https://github.com/datalad/datalad/pull/5603#pullrequestreview-645080883
Positioned against `maint` since it addresses us returning non-informative UNKNOWN for `github` module version whenever it can be discovered.
=> ENH: external_versions - add lookup table for github -> pygithub
