bin/datalad, datalad/cmdline/helpers.py, datalad/cmdline/main.py, datalad/db.py, datalad/tests/test_cmdline_main.py
Well -- this one is contingent on the previous PR (#46) since I simply was lazy to also 1 line for mock into requirements.txt here as well ;)
=> Make main cmdline datalad tool logic part of the module for testing + basic tests

datalad/tests/utils.py
instead of localhost (on wheezy only)
Discovered on our buildbot wheezy docker images and troubleshooted by Joey.  Having
127.0.0.1 localhost
::1 localhost
confuses that old haskell and it tries then to fetch our tests data via ipv6 and fails.  To mitigate, we will use
127.0.0.1 on those elderly boxes.  Later on we might need to enumerate more of similarly defect systems or just use
127.0.0.1 on all linuxes ;)
=> BF: workaround for buggy haskell network layer on wheezy -- use 127.0.0.1

.travis.yml
so that we could all live happily with needing fresh git-annex on travis
=> BF: use neurodebian repo and git-annex-standalone package

CONTRIBUTING.md, datalad/tests/test_log.py
This is a suggestive workflow from Yarik
=> We don't have bin/ any more + elaborate workflow for having origin and gh-* clones

datalad/api.py, datalad/cmd.py, datalad/cmdline/cmd_get.py, datalad/cmdline/cmd_install.py, datalad/support/annexrepo.py, datalad/support/dataset.py, datalad/support/gitrepo.py, datalad/support/handle.py, datalad/tests/test_annexrepo.py, datalad/tests/test_gitrepo.py, datalad/tests/test_handle.py, datalad/tests/utils.py
Enhances repository classes in order to refactor PR #52.
=> ENH: Enhancements to repo classes 

datalad/__init__.py, datalad/cmdline/main.py, datalad/crawler/main.py, datalad/log.py, datalad/support/configparserinc.py, datalad/support/network.py, datalad/support/repos.py, datalad/tests/test_cmd.py, datalad/tests/test_cmdline_main.py, datalad/tests/test_kraut.py, datalad/tests/test_main.py, datalad/tests/test_tests_utils.py, datalad/tests/test_utils.py, datalad/tests/utils.py, requirements.txt, setup.py, testkraut/__init__.py, testkraut/config.py, testkraut/lookup.py, testkraut/pkg_mngr.py, testkraut/spec.py, testkraut/testcase.py, testkraut/utils.py, tools/testing/make_test_repo, tools/testing/make_test_repos
I had a moment of weakness... hopefully I haven't disturbed our PRs too much... I can promise to pay the price and update them ;-)
=> Rf some pep8

datalad/support/annexrepo.py, datalad/support/handle.py, datalad/tests/test_annexrepo.py, datalad/tests/utils.py
Commits from earlier, not yet merged changes included. 
Topic is about last commits starting with: 
https://github.com/datalad/datalad/commit/85db7423db0c75a5afcb19c6b31ac76325e08f1b
=> NF: Choose backend

datalad/tests/test_customremotes_archive.py
an obvious fix -- I will merge as soon as tests pass
=> BF: adjust for the recent annex_whereis change

datalad/support/gitrepo.py
=> BF: Avoid passing empty strings as 'paths' to GitPython

datalad/tests/test_tests_utils.py, datalad/tests/utils.py
=> NF+RF: improvement for ok_*_symlink funcs and added unittests (Closes #92)

datalad/tests/test_cmd.py, datalad/tests/test_utils.py, datalad/utils.py
TODOs
~~1.  catch real exceptions (pass real exceptions in)~~
~~2.  properly restore orig settings (attrs) for sys.excepthook, pdb.post_mortem, utils.is_interactive~~
~~3.  provide testing for non-interactive mode of operation~~
=> WIP NF setup hook test

datalad/utils.py
Trying to solve #147 
Question remains: How to test this is an actual solution? (issue doesn't always occur)
=> BF: gc is slow on windows

datalad/cmd.py, datalad/crawler/main.py, datalad/customremotes/base.py, datalad/support/protocol.py, datalad/support/repos.py, datalad/tests/test_cmd.py, datalad/tests/test_protocols.py
Adresses #150 
Note: Occasionally fails on windows, due to issue #147
=> NF: Runner protocols

datalad/tests/test_annexrepo.py, datalad/tests/test_cmd.py, datalad/tests/test_gitrepo.py, datalad/tests/test_handle.py, datalad/tests/test_kraut.py, datalad/tests/test_testrepos.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py
As detected by @jgors tests on "installed" datalad didn't work, so this is a workaround
=> BF testrepos --allow to run tests by cloning repos from online

datalad/interface/crawl.py, datalad/interface/install.py
so doing the action for install
I will cook up tests now
=> BF: forgotten self for __call__ and Interfaces should perform the action

.travis.yml, tools/eval_under_testloopfs, tox.ini
also removed py33 from tox.ini since not generally present etc
=> ENH: allow to test under crippled file systems

datalad/customremotes/archive.py, datalad/customremotes/base.py
for which I just reply with the failure ATM.
=> BF provide handling for WHEREIS custom remotes API

.travis.yml, datalad/tests/test_annexrepo.py, datalad/tests/test_basic_functionality.py, datalad/tests/test_gitrepo.py, datalad/tests/test_handlerepo.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py, tools/testing/travis_ifdown_nonlo.sh
some tests simply needed also a 'network' source being present
in another -- removed public url -- use locally created/served
=> Tuning up tests (and travis) so they still work without network connection

.travis.yml
=> ENH: set to empty http*_proxy vars while testing without network on travis

datalad/cmdline/main.py
Just enough to get basic completion working with bash (plus some install logic in the Debian packaging).
=> ENH: Basic support for cmdline arg completion

datalad/cmdline/main.py
Need created input on where to put a test.
=> ENH: Implement git-style '-C' option for more cmdline convenience

datalad/tests/test_basic_functionality.py, datalad/tests/test_utils.py, datalad/utils.py
TODO: tests on windows (in best traditions of windows neglect)
=> BF: urlquote filename in get_local_file_url + do not add #target to filename but to the url

datalad/cmdline/main.py, datalad/interface/get.py, datalad/interface/tests/__init__.py, datalad/interface/tests/test_get.py, datalad/tests/test_gitrepo.py, datalad/tests/test_tests_utils.py, datalad/tests/test_utils.py, datalad/tests/utils.py, datalad/utils.py
fixing my abomination of submitting this fix on top of #199 for no good reason ;)  It still resides on top of #228 though
=> BF for get operation

datalad/tests/utils.py
Otherwise failing tests on truly German machines ;-)
=> Don't forget about other locales

datalad/interface/__init__.py, datalad/interface/drop.py
it is based on 'get' but with some additional reporting
=> BF: datalad drop  to complement  get (tests: TODO)

datalad/interface/__init__.py, datalad/interface/add_handle.py, datalad/interface/describe.py, datalad/interface/import_metadata.py, datalad/interface/install_handle.py, datalad/interface/publish_collection.py, datalad/interface/search_handle.py, datalad/interface/tests/test_upgrade_handle.py, datalad/support/collectionrepo.py, datalad/support/gitrepo.py, datalad/support/handlerepo.py, datalad/support/metadatahandler.py, datalad/tests/test_basic_functionality.py, datalad/tests/utils.py
More on metadata.
Additionally minor fixes, I stumble over
- #252 should be fixed herein
- addresses #244 
- fixed #255 
For now, I think that's it, what was important to get ready. So, as far as I'm concerned, ready to merge.
=> ENH: Metadata

datalad/interface/publish_collection.py
=> BF: missed to get stdout, stderr on failure

datalad/interface/publish_collection.py, datalad/resources/git_ssh.sh
so easy to work without tests but so painful ;-)
=> BF: can't concatenate None to str... do not assume that port is 22 ;-)

datalad/support/annexrepo.py
If cloning partially fails, don't break, but run annex init and annex fsck.
This addresses issue #258 .
=> BF: Try to fix things, in case cloning appears to fail.

datalad/api.py
Added 3320fe5 and looks like a merge leftover
=> Remove unecessary import

datalad/auto.py, datalad/tests/test_auto.py
there was too much of undue messages about trying to open non-existing files
=> ENH: auto mode -- do not even try to get a file which is not there

datalad/interface/list_handles.py
I wish I could make a reasonable unittest but I think we better address #234, etc for that
=> ENH: -r/--remote for list-handles (Closes #269)

datalad/support/gitrepo.py
to be a part of normal operation
=> ENH: specify expect_stderr for those commands where we do expect stderr

datalad/cmdline/helpers.py, datalad/cmdline/tests/test_helpers.py, datalad/interface/tests/test_upgrade_handle.py, datalad/support/collectionrepo.py
=> BF: get_repo_instance

datalad/interface/tests/test_describe.py, datalad/interface/tests/test_import_metadata.py, datalad/interface/tests/test_search_collection.py, datalad/interface/tests/test_search_handle.py, datalad/support/annexrepo.py, datalad/support/collectionrepo.py, datalad/support/gitrepo.py, datalad/tests/test_basic_functionality.py, datalad/tests/test_gitrepo.py
=> RF: Use getpwd, chpwd instead of os.getcwd, os.chdir

datalad/log.py
Borrowed from duecredit as of 0.4.5-1-ga35d613
Closes #308
=> ENH: DATALAD_LOGTRACEBACK=collide or any other non empty value enables it

datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/openfmri_collection.py, datalad/downloaders/configs/openfmri.cfg, datalad/interface/crawl.py, datalad/interface/tests/test_crawl.py, datalad/interface/tests/test_get.py, datalad/support/cookies.py, datalad/support/s3.py, datalad/tests/test_utils.py, datalad/utils.py
I will merge whenever tests pass
=> Various fixes and enhancements which came about while crawling first openfmri datasets

.travis.yml, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/tests/test_annexrepo.py
=> ENH: annex_whereis(output="full") returns a dict with a dict of remotes

datalad/interface/publish_collection.py, datalad/tests/test_cmd.py, datalad/tests/test_collectionrepo.py, datalad/tests/test_utils.py, datalad/utils.py
To test running of failing git-annex command we don't need to check against all types of repos
=> WiP: a pass over tests to make them not spit out error msgs and possibly fasten them up

datalad/downloaders/tests/utils.py, datalad/tests/test_s3.py, setup.py
debian/ branch will be pushed later whenever this one is merged
=> BF: few minor fixes and tune ups while preparing/testing building new debian pkg

datalad/crawler/nodes/annex.py, datalad/crawler/nodes/tests/test_annex.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/support/annexrepo.py, datalad/tests/test_annexrepo.py, datalad/tests/utils.py, datalad/utils.py
We also should think about somehow making it more permanent since in the clones annex will not have it as a default one ... 
https://github.com/datalad/datalad/issues/358
actually with 5d16d08 did a quick attempt at that
=> By default initiate handle's backed to be MD5

datalad/support/annexrepo.py, datalad/tests/test_annexrepo.py
CPed from another branch primarily to see if our buildbot works fine after multitude of reboots
=> ENH: annex_repo_info

datalad/version.py
I will accept PR if tests pass
=> just merged current master since apparently otherwise PRs couldn't be merged into master

datalad/crawler/nodes/s3.py, datalad/downloaders/s3.py, datalad/interface/ls.py
the same logic was within ls whenever provided s3cmd config file but was not
yet adopted into downloaders
=> BF: S3 - while connecting to S3 bucket also go through the list before throwing exception

datalad/support/digests.py, datalad/support/tests/test_digests.py
Had it lingering around, time to push to the main code base
=> Digester to "compute" digests (md5, sha, ...) in one go

datalad/__init__.py
otherwise it does not make sense to override hook unconditionally
was added in e66be92
=> BF: I think this added setup_exceptionhook in __init__.py was temp for troubleshooting

datalad/__init__.py, datalad/config.py, datalad/interface/add_archive_content.py, datalad/interface/tests/test_add_archive_content.py, datalad/support/annexrepo.py, datalad/support/stats.py, datalad/tests/utils.py
added more log lines to ease timing of the execution
=> ENH: delete_after, drop_after for add_archive_content + various small ENHs

CONTRIBUTING.md, datalad/tests/test_tests_utils.py, datalad/tests/utils.py
I am not sure why I still some times develop against master branch, but wanted to have content option in ultimatedb branch so decided to make one against master + fix for it from duecredit... will merge if tests still pass
=> With tempfile content master

datalad/tests/test_tests_utils.py, datalad/tests/utils.py
now with a test (laziness costs!)
=> BF: apparently patch.dict needs clear=True to replace entire dict

datalad/tests/test_utils.py, datalad/utils.py
Implementation may change in the future, but we need one now (for
install).
=> NF: Central implementation of URL detector

Makefile, datalad/api.py, datalad/cmdline/main.py, datalad/distribution/install.py, datalad/distribution/modify_subhandle_urls.py, datalad/distribution/tests/test_install.py, datalad/interface/base.py, datalad/tests/test_interface.py, datalad/tests/test_utils.py, datalad/utils.py
So we could test whether that local thing exists
Closes #456 
edited by yoh: Closes statement for the string interpolation issue
=> Robustify `install`

datalad/distribution/install.py, datalad/distribution/tests/test_install.py, datalad/tests/test_annexrepo.py
=> RF: Standardize submodule .git to be like a standalone .git

.travis.yml, datalad/tests/utils.py, datalad/ui/dialog.py, datalad/ui/progressbars.py, datalad/ui/tests/test_dialog.py, requirements.txt, setup.py
this should eliminate demand for pip to install from https://github and hopefully resolve nd80 headache
=> NF+RF: prefer tqdm progressbar over more flexible but unmaintained prorgressbar

datalad/support/sshconnector.py
=> ENH: Report that closing SSH connections only if there were any

datalad/distribution/install.py, datalad/distribution/tests/test_install.py
Also refactored code so it is less of a spaghetti conditioning and extensible happen we would like to try more than 2 possible candidate urls
Closes #488
=> BF+RF: cleanup unsuccesful install attemp before retrying with .git/

datalad/distribution/create.py, datalad/distribution/dataset.py, datalad/distribution/install.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_install.py, datalad/interface/__init__.py, datalad/support/annexrepo.py
Closes #487 
edit(yoh): replaced towards with closes -- when we merge it, it should close the #487
=> NF: `create` command

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
will merge right away if tests pass
=> ENH(TST): test that version is passed to git init, removed some empty lines

datalad/distribution/add_sibling.py, datalad/distribution/create_publication_target_sshwebserver.py, datalad/distribution/install.py, datalad/distribution/modify_subhandle_urls.py, datalad/distribution/publish.py, datalad/distribution/uninstall.py, datalad/distribution/update.py, datalad/interface/add_archive_content.py, datalad/interface/clean.py, datalad/interface/crawl.py, datalad/interface/download_url.py, datalad/interface/ls.py, datalad/interface/pull.py, datalad/interface/push.py, datalad/tests/test_interface.py
=> DOC: fixing format, PEP compliance

datalad/distribution/install.py, datalad/distribution/modify_subhandle_urls.py, datalad/distribution/publish.py, datalad/distribution/uninstall.py, datalad/interface/__init__.py
it is all non-english but at least a bit more uniform this way
Move is not implemented so why bother listing it?
=> ENH: try to bring interface descriptions to some commonality

datalad/crawler/nodes/misc.py, datalad/crawler/nodes/tests/test_misc.py
=> NF: fix_permissions node 

datalad/distribution/create_publication_target_sshwebserver.py
Ordered creation of subdatasets, log inside loop, doc changes.
=> Misc improvements for create-publication-target-sshwebserver

docs/examples/3rdparty_analysis_workflow.sh
Detected issues:
- `publish` doesn't use ssh connection manager properly #544
=> DOC: Extend the demo

datalad/distribution/publish.py, datalad/distribution/tests/test_install.py, datalad/interface/save.py, datalad/interface/tests/test_save.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/network.py, datalad/support/sshconnector.py, datalad/tests/test_network.py, docs/examples/3rdparty_analysis_workflow.sh
Also combination with 'store_true' didn't make sense.
=> RF: save() in line with #546

CONTRIBUTING.md, datalad/cmd.py
Added more environment vars, removed HELP2MAN
Also Improved docstring language in cmd.py. 
Work related to issue #513
=> WiP: DOC: Describe in CONTRIBUTING.md our env variables

datalad/cmdline/helpers.py, datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/crcns.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/tests/test_openfmri_collection.py, docs/datalad-metadata.rst
I will need to manually adjust existing/published superdatasets crawling
configuration to point to renamed functions
=> RF: replace those few of collection mentionings with superdataset

datalad/distribution/create.py
=> RF: -D for --description in create

datalad/distribution/create.py, datalad/distribution/tests/create_test_dataset.py
=> BF: goes boom when incompatible values

datalad/distribution/publish.py, datalad/support/gitrepo.py
Closes #597 
Simple first version of output for `push` operation.
How to make it nice depends on other decisions.
=> UI: publish

datalad/interface/base.py, datalad/interface/tests/test_docs.py, datalad/support/param.py
This is the stuff that is unrelated to the API changes.
=> Documentation-related code bugfixes from #598

datalad/interface/base.py, datalad/interface/tests/test_docs.py
=> Few minor tweaks to make the docs look better

datalad/api.py, datalad/distribution/dataset.py, datalad/tests/test_api.py
=> BF+RF: pass created docstrings into @datasetmethods, use functions to hide away temp vars

datalad/cmdline/main.py, datalad/tests/test_utils.py, datalad/utils.py
inspired by nipype ;)  thanks @satra
=> ENH: --idbg for IPython shell debugging session (and RF how to handle interactive)

datalad/support/sshconnector.py, datalad/support/tests/test_sshconnector.py
(Re-)Use ssh control path to scp source file/dir to destination
=> NF: Add scp capability to SSHConnection

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
useful for extracting on-disk size, total repository size, object count etc
=> ENH: Add count_objects property to GitRepo class

datalad/crawler/dbs/tests/test_files.py, datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/downloaders/base.py, datalad/downloaders/http.py, datalad/downloaders/providers.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_http.py, datalad/downloaders/tests/test_providers.py, datalad/interface/crawl.py, datalad/interface/tests/test_crawl.py, datalad/support/gitrepo.py, datalad/support/status.py, datalad/support/vcr_.py, datalad/tests/utils.py, setup.py
TODOs:
Investigated -- possible, but not yet implemented upstream (https://github.com/Lukasa/requests-ftp/issues/24), i.e. would need to be implemented (later if demand is high enough)
=> NF: rudimentary Q&D support for ftp: via requests_ftp

datalad/crawler/nodes/matches.py, datalad/crawler/pipelines/fcptable.py, datalad/crawler/pipelines/tests/test_fcptable.py, datalad/crawler/pipelines/tests/utils.py, datalad/downloaders/base.py, datalad/downloaders/http.py
TOPURL: http://fcon_1000.projects.nitrc.org/fcpClassic/FcpTable.html 
Working towards closing: #578
=> NF: pipeline for FCP Classic Data Table

datalad/customremotes/archives.py, datalad/customremotes/base.py, datalad/support/archives.py, datalad/tests/utils.py
should now first check if an archive is extracted (also stamping introduced to guarantee that we don't pick up on partially extracted ones), or available locally in annex, and then the rest
=> ENH+BF: dealing with archives - should be a bit more smart about which archive to consider first

.travis.yml, datalad/dochelpers.py, datalad/downloaders/configs/nitrc.cfg, datalad/downloaders/http.py, datalad/support/keyring_.py, datalad/ui/progressbars.py, requirements.txt
apparently encodes content of pages with gzip, so we do need to decode even when downloading into a file 
initial setup for authentication, now we need to figure out what to do with all the "send email" agreements dialogs and optional authentication ( #661 )
=> Various ENH came up while trying NITRC

datalad/cmdline/helpers.py, datalad/tests/test_cmdline_main.py, formatters.py, setup.py, setup_support.py
=> Refined #667 with handling of MANPATH and get_version

datalad/interface/crawl.py, datalad/interface/tests/test_crawl.py, datalad/support/stats.py, datalad/tests/utils.py, datalad/utils.py
=> ENH: basic --recursive for crawl

datalad/interface/crawl_init.py, datalad/interface/tests/test_crawl_init.py
=> NF: Error msg when crawl-init with no args

datalad/downloaders/tests/test_credentials.py, datalad/downloaders/tests/test_http.py, datalad/support/keyring_.py, datalad/tests/utils.py
=> TST: User prompted if auth set, credential not set

datalad/interface/crawl_init.py, datalad/interface/tests/test_crawl_init.py
=> WiP: NF: --save option implemented for crawl config file

datalad/distribution/add_sibling.py, datalad/distribution/create_publication_target_sshwebserver.py, datalad/distribution/publish.py, datalad/distribution/tests/test_target_ssh.py, datalad/support/annexrepo.py
Closes #463 
Closes #432 
also few stylistic changes along the way
=> BF: create_...sshwebserver -- annex init  and enable new remote

datalad/distribution/install.py, datalad/distribution/tests/test_install.py, datalad/tests/test_utils.py, datalad/utils.py
thought to solve #693 but the bug managed to escape :-( so this one includes some minor enhancements
=> ENH: misc while trying to troubleshoot install

datalad/distribution/tests/test_install.py
Recent PRs all show the same network-related issue. Let's test master....
=> BF: Recently added DataladRI use in tests requires network

datalad/crawler/nodes/annex.py, datalad/crawler/nodes/misc.py, datalad/crawler/pipelines/crcns.py, datalad/crawler/pipelines/openfmri.py, datalad/distribution/create.py, datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_install.py, datalad/interface/add_archive_content.py, datalad/interface/tests/test_add_archive_content.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/tests/test_utils.py, datalad/utils.py
Overall it is a cocktail of changes while dealing with openfmri datasets and playing in cmdline with datalad commands
Closes #709
=> ENH+BF: make crawled super-datasets not annexes, custom treatment of some openfmri datasets

datalad/distribution/create.py, datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py, datalad/support/annexrepo.py
Couldn't convince myself why the ID should stay the same even when
important events happen in the lifetime of a dataset, hence deviated
from the plan layed out in #701.
=> NF: Dataset.id property (closes gh-701)

.travis.yml
if first test pass, I will also add a space into its path for a good measure ;)
=> ENH: travis -- add a run with symlinked TMPDIR

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Adds fast flags to info, repo_info.
closes #728
=> ENH: Add fast flag to info, repo_info of AnnexRepo

datalad/crawler/pipelines/balsa.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/simple_with_archives.py, datalad/crawler/pipelines/tests/test_balsa.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/crawler/pipelines/tests/test_simple_with_archives.py, datalad/downloaders/configs/kaggle.cfg, datalad/downloaders/http.py
+ disabled ad-hoc README generation for openfmri
=> ENH: downloaders (support kaggle) + simple generic pipeline to crawl a page and download stuff

datalad/interface/save.py
=> ENH: prefix with [DATALAD] if save came without msg

datalad/distribution/dataset.py, datalad/distribution/tests/test_uninstall.py, datalad/distribution/uninstall.py
=> RF: Radical reimplementation of `uninstall`

datalad/distribution/add.py, datalad/distribution/tests/test_add.py, datalad/distribution/tests/test_uninstall.py, datalad/interface/save.py
Had to revert the use of `api.add()` in `save` to avoid infinite loops
=> ENH: Add `if_dirty` option to `add`

datalad/support/gitrepo.py
=> RF+ENH: GitRepo.clone to wrap around clone operation and provide workarounds

datalad/distribution/tests/test_uninstall.py, datalad/interface/save.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This addresses some of the topics brought up in #824
=> Bunch of changes to deal with missing subdatasets on `save`

datalad/distribution/create_test_dataset.py
So here is what it does ;)
$> datalad create-test-dataset --spec 2-3/-2 BUGA
2016-09-16 18:28:01,983 [INFO   ] Generating repo of class <class 'datalad.support.gitrepo.GitRepo'> under /tmp/BUGA (create_test_dataset.py:85)
2016-09-16 18:28:01,999 [INFO   ] Generating repo of class <class 'datalad.support.annexrepo.AnnexRepo'> under /tmp/BUGA/d0/d1/d2/r0 (create_test_dataset.py:85)
2016-09-16 18:28:02,196 [INFO   ] Installing /tmp/BUGA/d0/d1/d2/r0 from ./d0/d1/d2/r0 (install.py:372)
2016-09-16 18:28:02,239 [INFO   ] Generating repo of class <class 'datalad.support.annexrepo.AnnexRepo'> under /tmp/BUGA/d0/d1/d2/r0/r0 (create_test_dataset.py:85)
2016-09-16 18:28:02,437 [INFO   ] Installing /tmp/BUGA/d0/d1/d2/r0/r0 from ./r0 (install.py:372)
2016-09-16 18:28:02,566 [INFO   ] Generating repo of …
=> DOC: docstring for _makeds in create_test_dataset

datalad/crawler/nodes/tests/test_misc.py, datalad/downloaders/tests/test_http.py, setup.py
Let's see if coverage drops since some lines of code might be missed and then I would need to do proper test
=> BF: do not reach out to brain-map.org to test the node, just mock output of a function

datalad/distribution/tests/test_uninstall.py, datalad/distribution/uninstall.py
quick feedback @bpoldrack and @mih would be appreciated!
=> ENH: uninstall --kill (just wipes it out) (Closes #876)

datalad/crawler/nodes/tests/test_misc.py, datalad/distribution/install.py, datalad/distribution/tests/test_install.py, datalad/tests/test_cmd.py, datalad/tests/test_network.py, datalad/tests/test_utils.py, datalad/utils.py
upon playing with merged #631 found that it started to spit out errors while trying to clone from http and testing without `/.git`.  so this one brings swallowing back and also enhances it to log loglevel so we could quickly test if e.g. any ERROR was logged
please review/improve/merge @datalad/developers 
ah nah -- will merge -- please whine @datalad/developers  ;)
=> BF silent install

datalad/support/gitrepo.py
Saves only about 2 seconds running all the tests, but still ...
=> OPT: Quick fix to not instantiate gitpy.Repo twice when we clone

datalad/distribution/add_sibling.py, datalad/distribution/create_sibling.py, datalad/distribution/dataset.py, datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py, datalad/distribution/tests/test_target_ssh.py, datalad/support/annexrepo.py
should resolve issues 
Closes #869 
Closes #835
=> ENH+BF: more logging while dealing with siblings, fixes incorrect logic due to misleading var names, fetch sibling upon creation

datalad/interface/ls.py, datalad/log.py, datalad/metadata/search.py, datalad/support/ansi_colors.py
Example:
and should have none color/bold/underlying decoration  in non-interactive mode
=> ENH(RF): initial RFing to bring control over colors/formatting, add highlighting to search results

datalad/distribution/create_sibling.py, setup.py
I don't think this is critical enough to force this dependency.
=> ENH: Be able to cope with absent jsmin

datalad/resources/website/assets/js/main.js
=> BF: Remove '..' row in UI of root dataset

datalad/metadata/__init__.py, datalad/metadata/parsers/__init__.py, datalad/metadata/parsers/base.py, datalad/metadata/parsers/bids.py, datalad/metadata/parsers/frictionless_datapackage.py, datalad/metadata/parsers/tests/test_bids.py, datalad/metadata/parsers/tests/test_frictionless_datapackage.py
That can report which files they require for basic and comprehensive
meta data reporting.
=> RF: Pave the way to more sophisticated meta data parsers

datalad/distribution/install.py, datalad/distribution/tests/test_install.py, datalad/support/gitrepo.py, datalad/utils.py
Adresses #883
Additionally, since I'm at it anyway:
=> ENH: install can install an existing dataset

datalad/distribution/install.py
=> BF: Do not forget source (episode 345)

datalad/distribution/install.py, datalad/distribution/tests/test_install.py
=> NF: install --reckless (fixes gh-946)

.travis.yml, CONTRIBUTING.md, datalad/__init__.py, datalad/api.py, datalad/config.py, datalad/customremotes/base.py, datalad/customremotes/main.py, datalad/customremotes/tests/__init__.py, datalad/interface/common_cfg.py, datalad/log.py, datalad/metadata/tests/test_search.py, datalad/support/archives.py, datalad/support/vcr_.py, datalad/tests/test_archives.py, datalad/tests/test_config.py, datalad/tests/test_installed.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py, datalad/utils.py, docs/examples/3rdparty_analysis_workflow.sh, docs/source/conf.py, docs/source/config.rst, docs/source/index.rst, readthedocs.yml, setup.cfg, setup.py, setup_support.py, tools/eval_under_testloopfs, tools/testing/run_doc_examples, tools/testing/travis_ifdown_nonlo.sh
http://docs.datalad.org/en/docs/
http://docs.datalad.org/en/docs/config.html
Example of a properly formatted variable description:
http://docs.datalad.org/en/docs/config.html#term-datalad-api-always-render
=> Better docs: config variables and easier build

setup.py
Closes #960 
will merge if tests pass
=> RF: make core metadata (simplejson, pyld) required dependencies

requirements.txt, setup.py
that is how it will look:
https://testpypi.python.org/pypi/datalad
=> ENH: use pypandoc for README as a long description on pypi

datalad/config.py, datalad/metadata/__init__.py, datalad/metadata/search.py, datalad/metadata/tests/test_base.py
yoh: while at it, should resolve issues with PY3 compatibility of meta-data support. At least according to the current limited set of tests  (Closes: #756 ) ;)
=> BF+RF: metadata related

datalad/cmdline/helpers.py, datalad/crawler/nodes/tests/test_annex.py, datalad/metadata/__init__.py, datalad/metadata/search.py, datalad/metadata/tests/test_base.py, datalad/metadata/tests/test_search.py, datalad/support/cookies.py, datalad/support/external_versions.py, datalad/version.py
- to avoid possible crashes etc because of conflicting pickle format -- I have separated them out into different files for cached meta, and forced protocol 2 for cookies db
=> BF+ENH: few more tune ups for Python3 support

.travis.yml, CONTRIBUTING.md, datalad/cmd.py, datalad/config.py, datalad/interface/common_cfg.py, datalad/log.py, datalad/tests/test_cmd.py, datalad/tests/test_config.py, datalad/tests/test_log.py
Closes #971 
Might fail the tests since some commands etc might have been relying on catching that output! So I bet more work to be done.
=> Enhance logging -- no output from commands by default, not file:lineno in log msgs, specify limit for traceback

datalad/distribution/dataset.py
I think it should Closes #1012
=> ENH (tiny): decide that dataset not-installed if path does not even exist

datalad/cmdline/main.py, datalad/distribution/install.py
while playing "in real-time"
sorry -- no dedicated tests... getting late here.  Just played around with install and get while providing bogus targets ;)
=> BF: catch possible crashes  in except handlers + few more minor fixes

datalad/distribution/install.py
=> Use install in log and add space

datalad/distribution/dataset.py, datalad/distribution/publish.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_get.py, datalad/interface/common_opts.py, datalad/interface/save.py, datalad/interface/tests/test_save.py, datalad/support/gitrepo.py, datalad/tests/utils.py
=> ENH+BF: save --super-datasets, save subds, save [files] avoiding saving index etc

datalad/metadata/search.py, datalad/metadata/tests/test_search.py
````
% datalad search bids
No DataLad dataset found at current location
Would you like to search within DataLad meta-dataset under '/home/mih/datalad' and search within it? (choices: yes, no): 
````
=> Convoluted question

datalad/__init__.py, datalad/config.py, datalad/interface/common_cfg.py, datalad/interface/tests/test_add_archive_content.py, datalad/log.py, datalad/support/keyring_.py, datalad/tests/test_log.py
At present only for once switch, but many additional switches are
conceivable
=> RF: Sacrifice a few log lines to be able to configure logging via config

datalad/resources/website/assets/js/main.js
Closes #1055
Already deployed (without minimization) - works as desired
=> ENH: web - Move install text description to be filled in first 

datalad/cmd.py, datalad/config.py
Alternative to #1067 
Closes #1060
=> Choice 2  BF+RF:  do not log outputs at all for git config calls

datalad/distribution/create.py, datalad/distribution/tests/test_create.py, datalad/interface/common_opts.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
@agramfort maybe you can past the log from your server? Thanks!
=> When `add` failed due to insufficient permissions it reports ("unknown reason")

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
=> BF: update -- care only about install (sorry -- fulfilled) repos, fetch anything not just git-annex

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This is a quickfix for what @mih requested.
=> ENH: Allow to look up keys for lists of files (Closes #1076)

datalad/__init__.py, datalad/crawler/nodes/annex.py, datalad/crawler/nodes/s3.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/openfmri_s3.py, datalad/interface/ls.py
Includes a number of enhancements around in the code
=> ENH openfmri - crawl also extracted datasets where available

datalad/auto.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_auto.py
it might be resolving #1112 , @mih -- could you check?
=> BF: if relative path provided to auto -- make it abs before passing into a repository handling

datalad/distribution/uninstall.py
=> specify what cannot uninstall and do not ask None of being installed

datalad/support/annexrepo.py, datalad/support/archives.py, datalad/support/external_versions.py, datalad/support/tests/test_external_versions.py
=> RF: robustify logic in version deducing and comparison -- use only LooseVersion

datalad/crawler/pipelines/openfmri_s3.py, datalad/crawler/pipelines/simple_s3.py, datalad/crawler/pipelines/simple_with_archives.py, datalad/crawler/pipelines/tests/test_simple_s3.py, datalad/crawler/pipelines/tests/utils.py, datalad/downloaders/configs/indi.cfg, datalad/interface/crawl_init.py
Was working to provide crawling of indi datasets... still somewhat WiP.  Submitting to test if our buildbots came back up ok after power outage
=> ENH: INDI, s3 etc

datalad/interface/ls.py
While making sure that uninstall replaces deinited subdatasets with an empty dir I noticed this:
````
/tmp/some/deep (git)-[master] % datalad ls -r
.  unknown
/tmp/some/deep (git)-[master] % cd ..
/tmp/some (git)-[master] % datalad ls -r
.      [annex]  master  - 2016-11-17/17:42:41  OK
deep   not installed
````
In the first case it doesn't even acknowledge to be in a dataset, and gives the same output as for a directory that is not even under git. I think it should give some indication of being in a dataset (minimum), and better say that it is at an uninstalled subdataset.
=> datalad ls should test for uninstalled subdatasets

datalad/support/gitrepo.py
Stumbled upon this incorrect description.
=> DOC: Clarify docstring

datalad/support/exceptions.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Closes #1149 
Implementation shows the direction, I want to go with these kind of exceptions. But not within this PR. This is just about what @mih apparently needs atm.
=> ENH: Introduce GitIgnoreError

datalad/resources/website/assets/js/main.js, datalad/resources/website/index.html, datalad/resources/website/tests/test.html
Fix #988 to prevent breadcrumbs overflowing into the search bar.
Refactor js file to follow consistent styling (based of google js style guide)
=> BF+RF: Breadcrumbs UI Overflow

datalad/consts.py, datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/interface/clean.py, datalad/interface/tests/test_add_archive_content.py, datalad/interface/tests/test_clean.py
slightly related to https://github.com/datalad/datalad/issues/444
=> RF+ENH: clean to clean up .git/annex/tmp, do recursive traversal, use -d

datalad/distribution/uninstall.py, datalad/interface/base.py, datalad/interface/tests/test_utils.py, datalad/interface/utils.py, datalad/utils.py
As promised, here is the RF that I already had wrt homogenizing the interface procedures.
=> RF Interface

datalad/metadata/__init__.py, datalad/metadata/tests/test_base.py, datalad/support/annexrepo.py, datalad/support/network.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_utils.py, datalad/utils.py
needed for ultimatedb branch but kinda independent
=> ENH: pass options into AnnexRepo.whereis, such as  --all to get information about all the keys

datalad/cmdline/helpers.py, datalad/cmdline/main.py, datalad/interface/__init__.py, formatters.py
Could be done in many different ways, but this does it in a minimal way
=> BF: Nicer manpages (fixes gh-1187)

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This is part of a fix for #1238.
Will merge as soon as tests pass.
=> BF: [].extend() performs in-place mod (just as a reminder)

datalad/__init__.py, datalad/cmd.py, datalad/cmdline/common_args.py, datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py, datalad/distribution/add_sibling.py, datalad/distribution/create_sibling.py, datalad/distribution/create_sibling_github.py, datalad/distribution/publish.py, datalad/distribution/tests/test_add_sibling.py, datalad/distribution/tests/test_publish.py, datalad/distribution/tests/test_target_ssh.py, datalad/interface/__init__.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/sshconnector.py, datalad/support/sshrun.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py, datalad/support/tests/test_sshconnector.py, datalad/tests/test__main__.py, datalad/tests/test_cmd.py, docs/source/cmdline.rst
=> Continuation of #1232, focus on add-sibling, create-sibling*, publish interaction

datalad/distribution/tests/test_create_sibling.py, datalad/interface/utils.py
Thus Closes #1273 as not reproduced
also fixed few typos and PEP8ing along the line of sight ;)
=> ENH(TST): for sub-dataset create-sibling, seems to show no problem

datalad/support/gitrepo.py
=> BF: No active branch when HEAD is detached 

datalad/support/sshconnector.py, datalad/support/tests/test_sshconnector.py
=> BF: Don't try to close connections without an existing socket 

tools/testing/start_website_in_docker
Tested on Ubuntu 16.04, Debian Jessie
=> BF: Fix package dependencies in docker script

datalad/distribution/install.py, datalad/interface/utils.py, datalad/support/annexrepo.py
Stumbled upon a bug in `save_dataset`, which led to swallowing all exceptions raised by git commit.
Does this ring a bell in relation to other issues, @datalad/developers ?
PR is intended to show the issue and find the implications. Need to fix this outside of PR #1277 , since otherwise there are too many different things at once to solve ...
=> BF: fix what's wrong with save_dataset

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py
Also adjusted logging a bit to not be misleading and more informative
Closes #1297
=> BF: while creating remote sibling, first try to rmdir if exists

datalad/tests/test_testrepos.py, datalad/tests/utils_testdatasets.py
This should help playing with this monster in the context of #923
The first comment there requests a URL for `datalad install -r ...`. This is to better evaluate what that would mean without any significant file load.
Below is a demo of the result (public facing datasets only). Note that 3 layers of datasets are sufficient, but no more than 2 layers are actually installed in each case. Going full recursive install should yield 4 layers for the present setup (actual studyforrest.org should be no more then 5 layers ATM). The vast majority of all subdatasets would be copies.
Complete publication would be solved by publishing datasets in the first layer only, and all versions of all files in all revisions of these.
The function produces a cartoon representation of the project evolution too -- …
=> TST: Helper to generate a mockup DS tree resembling studyforrest.org

datalad/support/exceptions.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> BF+ENH(DOC): fill in the blank, DeprecatedError for clone invocation of GitRepo

datalad/support/tests/test_annexrepo.py
=> ENH(TST): test annex meta-data manipulations with trickier values

datalad/distribution/tests/test_uninstall.py, datalad/distribution/uninstall.py
=> BF: Invalidate Dataset.config when uninstalled

datalad/distribution/dataset.py, datalad/distribution/update.py, datalad/support/annexrepo.py
Minor RF'ing proposed in PR #1304
Just wondered, what went wrong when @mih did it.
See https://github.com/datalad/datalad/pull/1304#issuecomment-280927556
=> RF: update

datalad/distribution/tests/test_publish.py
=> BF: Correct assertion to check what we are actually interested in.

datalad/distribution/add_sibling.py, datalad/distribution/tests/test_add_sibling.py
=> RF: make AddSibling API similar to CreateSibling (dataset + url should be sufficient

datalad/distribution/add_sibling.py, datalad/distribution/create_sibling.py, datalad/distribution/publish.py, datalad/distribution/tests/test_create_sibling.py, datalad/interface/common_opts.py, datalad/interface/ls.py, datalad/interface/tests/test_ls.py, datalad/support/annexrepo.py, datalad/support/network.py, datalad/support/tests/test_annexrepo.py
=> ENH: --inherit for add/create-sibling, RF: publish --missing=fail|skip|inherit; wanted for annex; apparently some BF for ls

.travis.yml
also adjusted to run all possible tests
=> ENH: trying to skip many matrix definitions if requested from PR

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py, datalad/interface/utils.py
WAS: fetch fails when ran during the test but works fine if I run manually after... am I doing smth wrong or a bug?  testing also if our buildbot back online
Now -- delays decision making on dataset availability (also part of the #1349), tests for that, and improves error msg reporting in case of wrong since value
=> BF: delay decision making on dataset availability for --since [Was Question: what am I doing wrong?  non-reproducible]

datalad/api.py, datalad/distribution/tests/test_update.py, datalad/interface/common_cfg.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> BF: do not fetch remotes without url (with warning unless special remote

CHANGELOG.md
initiated to collect even for my own good all the goodness since when the world was still round
I am switching to another task atm , so feel welcome to push directly into this branch... but buzz me when you are done just in case ;)
Closes #1270
=> initiated changelog for 0.5

datalad/interface/utils.py
Same as #1350. Read conversation there instead.
=> Return value revolution (#1350 continued)

CHANGELOG.md, datalad/distribution/add.py, datalad/distribution/tests/test_add.py
Closes #1412 
if this one merged, I might even cut a tiny bugfix release later this week... having #1388 addressed would also be handy
=> BF: add - set to_git to None by default, not False  to allow annex to decide where to add files

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py
=> RF: Wipe stale code from Dataset()

docs/source/metadata.rst, docs/source/related.rst, formatters.py
will merge if builds fine to see it online (need to reference), feel free to improve/fixup later on
=> DOC: high level comparison, intro to search in metadata section, references to manpages

datalad/metadata/__init__.py, datalad/metadata/tests/test_base.py, datalad/utils.py
=> BF: remove status and local remote name from annex description

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py
may it be  it???
Closes #1514
edit: if passes -- would need to restart that matrix run few times to make sure ;)
=> BF: quote all paths in the vars definitions in the hook

.travis.yml, datalad/distribution/tests/test_create_sibling.py
For now just provided a workaround to not run sphinx doctests in that heavy debug mode.  Still not clear to me what sphinx is whining about (probably some output sneaks through the cracks) -- does not replicate locally and shouldn't affect coverage AFAIK
=> BF troubleshooting sphinx failure

datalad/interface/diff.py
=> Some bugfixes for `diff`

CHANGELOG.md
@mih -- please check if I have forgotten anything and tune to your liking if you like... I will merge later on today to "release" ;)
=> changelog for upcoming 0.6.0

datalad/distribution/clone.py, datalad/distribution/drop.py, datalad/distribution/remove.py, datalad/distribution/uninstall.py, datalad/interface/annotate_paths.py, datalad/interface/save.py, datalad/interface/tests/test_annotate_paths.py, datalad/interface/utils.py
Importantly, an actual test for the joint issues leading up to #1573 isn't yet available. The one posted by @yarikoptic in #1573 passes now, but adds a runtime of ~25s.
Moreover, I paid no attention to efficiency -- it might well be that there is some slowdown.
=> Fix for gh-1573

.travis.yml, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_uninstall.py, datalad/interface/tests/test_add_archive_content.py, datalad/interface/tests/test_utils.py, datalad/metadata/tests/test_base.py, datalad/tests/test_testrepos.py, datalad/tests/utils.py
=> ENH: tag some tests as slow/usecase/integration and skip them in generic runs

README.md, docs/source/background.rst, docs/source/basics.rst, docs/source/index.rst, docs/source/modref.rst, docs/source/related.rst
Minor bits and pieces trying to get to an (intermediate) level of comprehensiveness regarding the more recently established principles (and some older). Feedback welcome.
Rendered version visible at http://docs.datalad.org/en/docs/
=> Some love for the docs

datalad/distribution/create_sibling.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_publish.py, datalad/interface/annotate_paths.py, datalad/interface/base.py, datalad/interface/tests/test_unlock.py, datalad/interface/unlock.py
Attempt to slim PR #1544 down to be able to locate cause of segfault.
=> Some (standalone) parts of #1544

CHANGELOG.md, Makefile, docs/source/changelog.rst, docs/source/index.rst
Converted file is commited to Git to have the docs be self-contained and easily build on readthedocs...
=> DOC: Auto-conv. RST version of changelog for the docs

datalad/cmd.py, datalad/support/annexrepo.py, datalad/support/sshconnector.py, datalad/support/sshrun.py, datalad/version.py
Saw python3-debug complaining that there are non-closed files, and found a few spots where we possibly didn't close files properly and could potentially leak/exhaust resources.
=> Close opened files and PIPEs

datalad/support/sshconnector.py
````
[DEBUG  ] Closing 0 SSH connections...
````
=> Pointless SSH connection closing message

datalad/api.py, datalad/distribution/drop.py, datalad/distribution/remove.py, datalad/distribution/uninstall.py, datalad/interface/ls.py, datalad/metadata/aggregate.py, datalad/metadata/search.py, datalad/plugin/__init__.py, datalad/support/param.py, datalad/tests/test_interface.py
Results can be seen on readthedocs
Also fixes #1614
=> DOC: Removed duplicate constraints description from API docs (fixes gh-602)

datalad/distribution/create.py
Thanks to @djarecka for the report!
=> BF: Incorrect `nargs` spec for --annex-backend option (fixes gh-1617)

datalad/__init__.py, datalad/interface/utils.py, datalad/support/ansi_colors.py
Please see the two commits for details.
=> Intensified and cross-platform handling of colored terminal output

datalad/distribution/tests/test_clone.py
addressing my whining in https://github.com/datalad/datalad/pull/1624/files#r125349246
=> BF: do not try to clone in / and skip if su

datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/tests/test_balsa.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/distribution/tests/test_add.py, datalad/distribution/tests/test_publish.py, datalad/plugin/tests/test_tarball.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Not yet sure if completely "kosher" especially with all the migration interactions
Closes #1636
=> BF: set backend persistently (.gitattributes) if provided

datalad/customremotes/tests/test_archives.py, datalad/distribution/publish.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py
=> ENH+BF: is_special_annex_remote + remove with_refs_only option/functionality (not used)

docs/source/gettingstarted.rst
Hey wizards,
I've read the doc a little and and as a first attempt revised the gettingstarted.rst.
What I have done:
- added the command to install git-annex; the official debian repositories offer an outdated version so I consider it worthwhile to mention it and how to get a current version.
- The usual case in the doc is to give a mysterious line of code and then explaining it. It would mimic the regular train of thought better to first make clear a problem and its solution in plain English and _then_ providing the line of code followed by detailed technical description. In this case, the reader gets primed on what he will read as code and it avoids the reader jumping back and forth between code and explanation.
If required, I can revise the whole doc similarly.
Winter is coming... …
=> DOC: little cleaning of gettingstarted.rst

datalad/crawler/nodes/annex.py, datalad/downloaders/s3.py, datalad/support/gitrepo.py
ran into while crawling openneuro
=> ENH: allow for "recursive" flag for remove (needed while crawling s3 where prefix is a directory)

datalad/distribution/create_sibling.py, datalad/distribution/publish.py, datalad/distribution/tests/test_create_sibling.py, datalad/support/annexrepo.py
=> BF: use relative dspath in the hook , dead/remove remote upon replace

CHANGELOG.md, datalad/distribution/tests/test_update.py, datalad/distribution/update.py
good fix is the fix right after a release... heh
=> BF: skip with "updating" a subdataset which is not installed

datalad/support/annexrepo.py
very minor but thought to get tests ran first
=> ENH: minor -- no need for explicit --json since we run json command

datalad/interface/base.py
See #1692 
There's no additional test, just checking it doesn't break anything.
This is about a hardcoded transition list we forgot about. Testing for this would just include another list of this kind. Makes sense only, if the list is gone and we can test for all commands to respect common parameters.
=> BF: publish wasn't fully converted to new-style

docs/source/gettingstarted.rst
Hey sorcerers,
I incorporated the suggestions made in pull request #1645 (DOC: little cleaning of gettingstarted.rst) and Issue #1647 (Improve installation instructions).
=> DOC: revised gettingstarted.rst

datalad/distribution/tests/test_install.py, datalad/interface/results.py
=> BF: install's default result filter to respect Dataset instances

datalad/interface/save.py, datalad/interface/tests/test_save.py
This documents the issue with save_super hinted on in #1700, hence the
test is currently broken.
Now fixed!
=> TST+BF: More tests on how and when subdatasets get saved

datalad/consts.py, datalad/interface/annotate_paths.py, datalad/interface/diff.py, datalad/interface/tests/test_diff.py
=> TST: Document gh-1733

CHANGELOG.md, datalad/resources/website/assets/js/main.js, datalad/resources/website/index.html, docs/source/changelog.rst
Compressed the header of the web ui page: 
Also includes updated generated changelog.rst and few minor doc things
=> Tune up web ui appearance tiny bit

docs/casts/heudiconv_dicom_to_bids.sh
result: https://asciinema.org/a/TZXI2HIJWLxd5h11Xcx8Nin5Z
=> A initial cast file for the heudiconv->datalad demo

datalad/interface/save.py
=> BF: report OK when tagging (fixes gh-1749)

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py, datalad/support/sshconnector.py
=> BF: run update-server-info if copying data to "http" remote with annexurl

datalad/customremotes/base.py
To prevent possibly incorrect splitting whenever a key contains a space.
Not sure yet if it could happen for our custom remotes at all since they
are only for "consumption" direction, so unlikely to contain space in the
last argument, but just to be on a safe side..
Fixes #1727
=> ENH: custom remotes - split only to up to the desired number of arguments

datalad/utils.py
Just a minor change. Stumbled upon this one when looking at #1804
=> RF: Don't reinvent the wheel

datalad/metadata/search.py, datalad/metadata/tests/test_search.py, datalad/utils.py
=> BF: allow search arguments be unicode (well, utf-8?)

datalad/support/gitrepo.py
=> RF: add '--' automatically within GitRepo_git_custom_command 

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Reduce unnecessary trials for git-add --dry-run in direct mode
=> RF: AnnexRepo.add

datalad/metadata/aggregate.py
not 100% sure if it wasn't left intentionally to really blow... but then better raise exception
=> BF: remove errorneous "code"

datalad/distribution/remove.py, datalad/distribution/tests/test_uninstall.py
- ENH: Added  --nosave and --message to  remove cmd   Closes #1822
- BF: make remove not fail if operated without a specified dataset  Closes #1821
=> ENH: remove fixups

datalad/support/annexrepo.py
Relax matching condition for failing git-status in direct mode submodule
edit Closes #1843
=> BF: AnnexRepo.add

datalad/dochelpers.py, datalad/tests/test_dochelpers.py
A little enhancement also added to #1630 to get some sense of what is going on
=> ENH: for exc_str include repr in case no str, provided

datalad/customremotes/base.py, datalad/customremotes/tests/test_base.py
=> BF: support EXPORTSUPPORTED

.travis.yml, tools/ci/prep-travis-devel-annex.sh
=> ENH(TST): test on travis (allow to fail) against -devel version of annex

datalad/support/external_versions.py, datalad/support/tests/test_external_versions.py
=> BF: do not blow while testing externals version if non ImportError is thrown

datalad/tests/test_base.py
Just to avoid stumbling on the same shovel again
This pull request fixes #1908
=> ENH(TST): test to verify that current environment does not have git repo above tempdir

datalad/crawler/pipelines/tests/test_crcns.py
I don't see any other way for now
=> TST(workaround): datacite is broken for crcns atm

datalad/distribution/remove.py, datalad/distribution/tests/test_uninstall.py
This pull request fixes #1912 
Couldn't push into your branch, @mih (permission denied), so here's a new one.
We passed something on to the call to `Save`, that was as well invalid and constant across all paths involved. That way, save got one of the files twice and subsequently this was the only thing to be committed.
=> BF: remove multiple files

setup.py
ref: https://github.com/digitalbazaar/pyld/issues/69#issuecomment-339193989
=> BF: Thanks to @davidlehn pyld works again with version >= 0.8.2

datalad/auto.py, datalad/tests/test_auto.py
This pull request fixes #1884 for those particular use cases (needs 1 more commit in that branch, will push together with this one): lzma.LZMAFile and io.open
=> ENH: make AutomagicIO proxy also io.open and lzma.LZMAFile

datalad/distribution/get.py, datalad/distribution/tests/test_install.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This pull request fixes #1905 
This pull request proposes to try all remotes which have that commit somewhere in the history
=> BF: try more remotes upon install

datalad/metadata/definitions.py, datalad/metadata/search.py
=> Small term definition related fixes

datalad/metadata/parsers/__init__.py, datalad/metadata/parsers/image.py, datalad/metadata/parsers/tests/test_image.py, setup.py
Basic stuff like
- size
- dpi
- format
- bits per pixel
- color mode
=> Have metadata parser for generic image files

datalad/metadata/parsers/bids.py
=> Two minor tuneups

datalad/metadata/parsers/nifti1.py, setup.py
=> Fixes to nifti parsing

datalad/crawler/nodes/annex.py, datalad/crawler/pipelines/tests/test_openfmri.py, datalad/interface/run.py, datalad/interface/tests/test_run.py, datalad/support/annexrepo.py, datalad/tests/utils.py
There were some conflicts -- hopefully I resolved them correctly ;)
=> Merge 0.9.x - absorbing some fixes from 0.9.x branch

datalad/metadata/parsers/__init__.py
=> BF: hide all vars under _ prefix, fix up the debug msg

datalad/interface/add_archive_content.py, datalad/interface/tests/test_add_archive_content.py
Also add more informative error message if archive is not under annex yet
This pull request fixes #1997 
=> DOC: clarify that archive must be already under annex for add-archive-content

.travis.yml, tools/ci/install-annex-snapshot.sh
if passes -- then I will revert last commit and be ready for merge
=> WIP Add to matrix (alongside with upstream GitPython) to test against snapshot of annex (in master only)

datalad/interface/ls.py
will merge if it didn't break anything somehow (if tested ;) )
=> BF+ENH: ls s3:// do not overload "e" var with exception, tollerate having no version_id available for some reason

datalad/support/gitrepo.py, datalad/support/sshconnector.py, datalad/support/tests/test_sshconnector.py
This pull request fixes #2009 
Should fix travis build in 0.9.x (and then master) branches
=> ENH/BF: do not do anything in SSHManager upon its construction. Also guard around permission changes

.travis.yml, datalad/auto.py, datalad/crawler/pipelines/tests/test_simple_s3.py, datalad/downloaders/s3.py, datalad/downloaders/tests/test_s3.py, datalad/interface/ls.py, datalad/interface/tests/test_run.py, datalad/support/gitrepo.py, datalad/support/s3.py, datalad/support/sshconnector.py, datalad/support/tests/test_sshconnector.py, datalad/tests/test_auto.py, datalad/tests/utils.py, setup.py, tools/ci/install-annex-snapshot.sh
I guess this should be done every week now, or we rename 0.9x to master...
I now have a dedicated slide in my talks that explains why the examples I am showing do not work with any datalad release ;-)
https://gph.is/24RzXvw
=> Merge the accumulated diff from 0.9 into master

datalad/interface/ls.py, datalad/interface/tests/test_ls.py
This pull request fixes the fix for #1888.
=> BF: ls -- Don't try to close absent repos

datalad/plugin/tests/test_plugins.py
Tests whether commands can be configured to auto-run plugins. Test
wasn't possible before #2014, as they interfered with user config.
=> TST: Bring back disabled test

datalad/distribution/add.py, datalad/interface/ls.py, datalad/interface/tests/test_ls.py, datalad/support/gitrepo.py
=> 0.9x -> master

.travis.yml, CONTRIBUTING.md, datalad/__init__.py, datalad/consts.py, datalad/distribution/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/support/network.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py, docs/examples/nipype_workshop_dataset.sh
=> ENH: use http://datasets-tests.datalad.org for /// while running tests

setup.py
=> require GitPython >= 2.1.8 to assure compatibility with git 2.15

.travis.yml, CONTRIBUTING.md, datalad/__init__.py, datalad/consts.py, datalad/distribution/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/support/network.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py, docs/examples/nipype_workshop_dataset.sh, setup.py
- use datasets-tests.d.o
- require GitPython 2.1.8
=> merge 0.9.x

datalad/cmdline/main.py, datalad/interface/base.py
Wanted to troubleshoot #2052 
edit 1: was supposed to go against 0.9.x ... will merge manually there later on
=> ENH: reraise exception (and thus get into dbg) in case of --dbg mode and Ctrl-C interruption

after1.txt, after2.txt
This reverts commit 2ed29f8b591bad7751d67aca962ce7bd68e07737.
Revert "[DATALAD] added README"
This reverts commit 8dbb940ef6c18c8bd41e3405dd970b9a67f53655.
=> Cleanup cruft that accidentally made it into the master branch

datalad/auto.py, datalad/crawler/pipelines/openfmri.py, datalad/crawler/pipelines/tests/test_crcns.py
Found on smaug in my "deployment" state of datalad -- includes few fixes picked up from master and customization for one of the openfmri dataset -- nothing major.
Added 1a66e7202266a1ab46218e37edc8ae20302bf69a from #2076 to pass through that datacite failure. we should merge this into 0.9.x and then 0.9.x into master
=> Some tuneups to 0.9.x branch

datalad/interface/run.py, datalad/interface/tests/test_run.py
This pull request closes #2104.
=> Restore `datalad run --rerun`

datalad/support/annexrepo.py, datalad/tests/test_auto.py, datalad/tests/test_interface.py
Fixing grammar and spelling errors
=> rf-grammar-check

datalad/cmdline/main.py, datalad/interface/add_archive_content.py, datalad/interface/tests/test_add_archive_content.py, datalad/plugin/tests/test_plugins.py, datalad/support/annexrepo.py, datalad/support/archives.py, datalad/support/network.py, datalad/tests/test_auto.py, datalad/tests/test_interface.py, docs/source/gettingstarted.rst, setup.py
I was going through merged PRs and assigning them between 0.9.2 and 0.10 milestones...
was not yet fully done, hope to finish later/tomorrow
I hope to kick out 0.9.2 during weekend -- local datalad-blessed mortals start to hit issues we fixed since 0.9.1
=> Fixes picked up from master into 0.9.x

datalad/customremotes/archives.py, datalad/customremotes/base.py, datalad/customremotes/datalad.py, datalad/customremotes/tests/test_archives.py, datalad/customremotes/tests/test_base.py, datalad/customremotes/tests/test_datalad.py
This pull request fixes #2124 
=> BF: avoid sending ERROR to annex if we can still continue

datalad/interface/common_cfg.py, datalad/metadata/aggregate.py, datalad/metadata/extractors/bids.py, datalad/metadata/extractors/tests/test_bids.py, datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/metadata/tests/test_aggregation.py, datalad/metadata/tests/test_search.py
- #1971 (fixed)
- test for #1987
=> BF+TST: Can re-aggregate with unavailable object files (fixes gh-1971)

.mailmap, CONTRIBUTORS, datalad/cmd.py, datalad/customremotes/archives.py, datalad/customremotes/base.py, datalad/customremotes/datalad.py, datalad/customremotes/tests/test_archives.py, datalad/customremotes/tests/test_base.py, datalad/customremotes/tests/test_datalad.py, datalad/distribution/get.py, datalad/interface/run.py, datalad/interface/tests/test_add_archive_content.py, datalad/interface/tests/test_run.py, datalad/interface/utils.py, datalad/support/annexrepo.py, datalad/tests/heavyoutput.py, datalad/tests/test_cmd.py, datalad/ui/progressbars.py, datalad/utils.py
a good number of commits picked up from master
=> Sync 0.9.x into master

datalad/metadata/metadata.py, datalad/metadata/search.py
re .auto - see https://github.com/datalad/datalad/issues/2137
This pull request fixes #2136
=> OPT: remove unused import, delay import of datalad.auto

datalad/cmdline/main.py, datalad/interface/utils.py
This one is frequently used and quite long to type.
Please merge @datalad/developers
=> ENH: Alias --output-format with -o

datalad/interface/common_cfg.py, datalad/metadata/aggregate.py, datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/metadata/tests/test_aggregation.py, datalad/metadata/tests/test_base.py
=> Various small improvements to metadata aggregation

datalad/metadata/aggregate.py, datalad/metadata/extractors/bids.py, datalad/metadata/extractors/tests/test_bids.py, datalad/metadata/tests/test_aggregation.py, datalad/metadata/tests/test_search.py, datalad/tests/test_utils.py, datalad/utils.py, setup.py
This pull request fixes #2147
It seems that we need a bit more robust operation while reading those files which might contain unicode.
Ref: https://github.com/datalad/datasets/issues/17
Please have a look @datalad/developers even if it is still WiP
=> Various bugfixes addressing some corner cases while parsing datasets.datalad.org with new extractors

datalad/metadata/metadata.py, datalad/plugin/__init__.py, datalad/plugin/extract_metadata.py, datalad/plugin/tests/test_metadata.py
Allow for quick invocation of any of datalad's extractors. (DOCs inside)
Thanks to @yarikoptic for the activation energy to write this.
=> NF: Plugin `extract_metadata`

datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py, datalad/config.py, datalad/distribution/update.py, datalad/interface/utils.py
some recent fixes picked up into 0.9.x + a typo fix
will do a quick merge if no tests got broken
=> BFs master to 0.9.x

.travis.yml, CONTRIBUTING.md, datalad/tests/utils.py
=> RF: specify obscure filename prefix via env var for some travis matrix runs

CONTRIBUTING.md
There is magical ways @mih knows, but I do not remember.  Please add a sentence or two to CONTRIBUTING.md on that
1. Become @yarikoptic
2. just let time pass by
=> Add HOWTO on Michael's way "issue -> PR" into CONTRIBUTING.md

datalad/interface/tests/test_utils.py, datalad/interface/utils.py, datalad/metadata/aggregate.py
=> BF of #2182

datalad/crawler/nodes/misc.py, datalad/crawler/nodes/tests/test_misc.py
This pull request fixes #2097 
This pull request proposes replace spaces in url with correct syntax
=> Bf spaced url failure

CONTRIBUTING.md, datalad/cmd.py, datalad/distribution/tests/test_clone.py, datalad/support/gitrepo.py, datalad/tests/test_cmd.py
This pull request proposes to merge 0.9.x into master again (but might be one of the last ones of the kind ;) )
=> Enh merge 0.9.x

datalad/metadata/extractors/tests/test_bids.py, datalad/metadata/tests/test_search.py, datalad/plugin/tests/test_bids2scidata.py, datalad/plugin/tests/test_plugins.py
This pull request partially addresses #2199
=> ENH(TST): skip tests which would require pybids or pandas if those N/A

datalad/metadata/aggregate.py, datalad/metadata/tests/test_aggregation.py
https://codecov.io/gh/datalad/datalad/src/master/datalad/metadata/aggregate.py#L439
```python
if not objs2add and not refds_path == ds_path:
to_save(dict(path=ds_path, type='dataset', staged=True))
```
pycharm alerted me that to_save is a list and thus not callable.  codecov said that the line is not tested.
=> `aggregate-metadata` doesn't handle subdataset removal correctly

datalad/distribution/get.py, datalad/distribution/subdatasets.py, datalad/interface/annotate_paths.py, datalad/interface/diff.py, datalad/interface/results.py, datalad/interface/utils.py, datalad/metadata/aggregate.py, datalad/metadata/metadata.py, datalad/metadata/tests/test_search.py, datalad/tests/test_tests_utils.py, datalad/tests/test_utils.py, datalad/tests/utils.py, datalad/utils.py
=> Merges and adjusts for use of path_startswith from 0.9.x

datalad/interface/annotate_paths.py
=> RF: Remove obsolete code

datalad/crawler/pipelines/simple_with_archives.py
This pull request fixes #
Implements fix url method to ensure correct URL format.
=> implemented fix URL method

.travis.yml
As per analysis in #1528. Let's see if we loose anything with this
change.
=> Drop --doctest-tests from nose args

tools/Singularity-devmaster, tools/Singularity.fullmaster
The image behaves like the main datalad entrypoint.
%test could be added...
=> NF: Singularity recipe for a full datalad installation from current master

datalad/interface/rerun.py, datalad/interface/run.py
This pull request fixes import errors for `datalad {run,rerun}`.
Re: #2218
=> BF: run/rerun: Adjust imports for API change

.travis.yml, tox.ini
since gods say that 3.6.1 is the one!
=> drop python 3.4 and aim for 3.5 and 3.6

datalad/distribution/uninstall.py
=> BF: Fix missing import

CHANGELOG.md, CONTRIBUTING.md, datalad/tests/test_base.py, datalad/version.py, setup.py
=> ENH merge 0.9.2 into master

tools/Singularity.fullmaster
[will cancel the tests, nothing that runs changes)
Still running tests within the new image locally...
=> BF: Make UTF-related functionality work in Singularity

.github/issue_template.md, .travis.yml, datalad/api.py, datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py, datalad/distribution/tests/test_create.py, datalad/interface/__init__.py, datalad/interface/base.py, datalad/interface/utils.py, datalad/metadata/aggregate.py, datalad/plugin/__init__.py, datalad/plugin/add_readme.py, datalad/plugin/addurls.py, datalad/plugin/bids2scidata.py, datalad/plugin/export_archive.py, datalad/plugin/export_to_figshare.py, datalad/plugin/extract_metadata.py, datalad/plugin/no_annex.py, datalad/plugin/tests/test_addurls.py, datalad/plugin/tests/test_bids2scidata.py, datalad/plugin/tests/test_export_archive.py, datalad/plugin/tests/test_metadata.py, datalad/plugin/tests/test_plugins.py, datalad/plugin/wtf.py, datalad/utils.py, docs/source/cmdline.rst, docs/source/customization.rst, docs/source/modref.rst
It is basically figured out. Fate of `--run-before/after` is uncertain at this point (keep and RF or let die). If RF, it needs a way to store a command call in the config. Most likely using cmdline syntax and then shlex the beast and feed it to `main()` -- not sure if it is worth it. ATM I think it is not, but a beer or two might change my mind.
=> No plugins -> plug-able commands 

.travis.yml, CONTRIBUTING.md, datalad/__init__.py, datalad/distribution/create.py, datalad/interface/tests/test_run.py, datalad/support/tests/test_gitrepo.py
This pull request fixes nothing, but could help in generating reproducible test and casts runs (see eg. #2296)
=> DATALAD_SEED

datalad/metadata/search.py
Largely to make it usable by default on  our super-dataset.
As a possible resolution to #2262
With this change:
```shell
$> time datalad search '.*haxby.*'     
search(ok): /home/yoh/datalad-meta6-4/hbnssi (dataset)
search(ok): /home/yoh/datalad-meta6-4/labs/gobbini/famface/data (dataset)
search(ok): /home/yoh/datalad-meta6-4/labs/haxby (dataset)
search(ok): /home/yoh/datalad-meta6-4/labs/haxby/attention (dataset)
search(ok): /home/yoh/datalad-meta6-4/labs/haxby/life (dataset)
search(ok): /home/yoh/datalad-meta6-4/labs/haxby/raiders (dataset)
search(ok): /home/yoh/datalad-meta6-4/openfmri/ds000105 (dataset)
search(ok): /home/yoh/datalad-meta6-4/openfmri/ds000233 (dataset)
search(ok): /home/yoh/datalad-meta6-4/openfmri/ds000241 (dataset)
search (ok: 9)
datalad search …
```
=> ENH: for a dummy egrep search to not search via "unique content properties"

README.md
This pull request fixes #(None)
This pull request proposes grammar edits for README.md.
- [Fixed grammar mistakes ] This change is complete
=> Edited for grammar correctness

tools/Dockerfile.fullmaster
This pull request adds a Dockerfile for datalad
=> enh: added Dockerfile for datalad

tools/Dockerfile.fullmaster
Otherwise, every command will be accompanied by "[WARNING] It is highly recommended to configure git first [...]".
=> Configure git user name and email in Dockerfile

datalad/metadata/aggregate.py, datalad/metadata/extractors/__init__.py, datalad/metadata/extractors/annex.py, datalad/metadata/extractors/datalad_core.py, datalad/metadata/extractors/tests/test_base.py, datalad/metadata/extractors/tests/test_nidm.py, datalad/metadata/search.py, datalad/metadata/tests/test_search.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
This is also the way that I see info like #763 get incorporated.
=> Pimp the datalad_core extractor to expose more of datalad's internal/implicit metadata

datalad/support/annexrepo.py
This pull request tries to help to fix #2330.  Depending on what we discover we might want to retry few times, or just accept "crash" as an indication of some result, and/or report to git-annex
=> ENH: batched annex -- read/log stderr output if there was any

datalad/interface/rerun.py, datalad/interface/run.py
It's only a test dependency.
Re: #2321
---
=> BF: run/rerun: Don't use ok_clean_git

datalad/interface/test.py, datalad/interface/utils.py, datalad/metadata/extractors/__init__.py, datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/metadata/tests/test_search.py, datalad/plugin/tests/test_metadata.py, datalad/tests/test_utils.py, datalad/utils.py, formatters.py, setup.py, setup_support.py
in SYNOPSIS which is IMHO is not 100% correct
see e.g. http://docs.datalad.org/en/latest/generated/man/datalad-metadata.html
=> DOC: generated docs use "datalad-COMMAND" instead of "datalad COMMAND"

.travis.yml
Apparently noone missed it for 2 days
=> BF:  fixing coverage collection/reporting

datalad/support/json_py.py
This pull request proposes to be able to write and read JSON streams compressed as well as uncompressed.
This PR was supported by funds from the
German federal state of Saxony-Anhalt and the European Regional Development
Fund (ERDF), Project: Center for Behavioral Brain Sciences, Imaging Platform
=> ENH: Uncompressed JSON streams

CHANGELOG.md
We need high level description for ourselves and everyone else
Initiated in d82b34c5143844416751ddb4b3dc2cf10e4f3bff
=> 0.10.0 Release notes

datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/tests/test_utils.py, datalad/utils.py
=> RF+NF: as_unicode

datalad/metadata/search.py
This pull request makes a few fixes to the doc changes from #2455.
=> DOC: search: Revise

docs/source/gettingstarted.rst
=> Typo fixed

datalad/metadata/extractors/tests/test_base.py
First ran it within datalad-crawler installation, so thought it is specific to it, but seems to be generic (I am using virtualenv if that is relevant):
```shell
(git)hopa:~datalad/datalad-master[master]git
$> python -m nose -s -v datalad.metadata.extractors.tests.test_base      
datalad.metadata.extractors.tests.test_base.test_api_git(True,) ... FAIL
datalad.metadata.extractors.tests.test_base.test_api_annex(False,) ... FAIL
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180510+gitg500f7ea78-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.17.0 cmd:system-ssh=7.6p1 exifread=2.1.2 git=2.1.8 gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 msgpack=0.5.1 mutagen=1.40.0 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0 …
```
=> Failing test: Should have managed to find at least the core extractor extractor

datalad/interface/run.py
... so that datalad containers-run can use it.
https://github.com/datalad/datalad-container/pull/25
---
=> RF: run: Move command pwd logic to a function

datalad/distribution/tests/test_create_sibling.py
since might be shortnened if under $HOME
=> BF(TST): do not test full path in annex description

appveyor.yml, datalad/distribution/tests/test_dataset.py, datalad/tests/utils.py
While avoiding having to deal with the systemic breakage of our test battery on windows.
=> Enable a whole bunch of additional distribution tests on windows

datalad/interface/rerun.py, datalad/interface/run.py, datalad/interface/tests/test_run.py, datalad/utils.py
As discussed in #2512
---
No, it is on top of an open PR (#2591).  The new subset of commits is shown [here](https://github.com/kyleam/datalad/compare/bf-run-subdir...kyleam:nf-run-io-fields).
=> run: Add inputs/outputs placeholder to command

datalad/interface/run.py
This will be used in datalad-container.
---
=> RF: run: Extract command processing to a function

datalad/interface/run.py
=> Minor cleanup for run.py

datalad/distribution/create.py, datalad/distribution/tests/test_add.py
Presently unresolved discussion is https://github.com/datalad/datalad/pull/2552
=> BF+TST: Alternative fix to gh-2552 (with test)

datalad/cmdline/main.py, datalad/cmdline/tests/test_formatters.py, datalad/interface/run_procedure.py, datalad/resources/procedures/setup_yoda_dataset.py, formatters.py
- proper NAME section (uses first line of description, worked for all
commands but the main datalad entrypoint, needed update)
=> DOC: Better manpages (fixes gh-2608)

datalad/utils.py
will be merged quickly if no quick feedback or it fails the tests...
=> BF(PY3.5.1): import pkg itself before importing submodules

datalad/downloaders/tests/test_http.py, setup.py
will be a quick merge if fixes and doesn't break more ;-)
=> Mutagen and httpretty fixups

datalad/metadata/extractors/tests/test_base.py
still require the core one
Closes #2646
=> ENH(TST): Skip (do not fail) testing extractors if they fail to load

datalad/auto.py, datalad/cmdline/main.py, datalad/cmdline/tests/test_main.py, datalad/support/annexrepo.py, datalad/support/json_py.py, datalad/support/lzma.py, datalad/tests/test_auto.py, datalad/ui/utils.py, setup.py
See e.g. https://circleci.com/gh/conda-forge/datalad-feedstock/6
=> BF: terminal size could be reported 0, thus causing the breakage due to -5 below in the code

datalad/interface/run.py, datalad/interface/tests/test_run.py
=> BF: run: Avoid unlocking on an empty list

datalad/interface/run.py, datalad/interface/tests/test_run.py
=> NF: run: Support user-configured placeholder values

datalad/interface/run.py
=> DOC: run: Describe effect of command form on inputs/outputs formatting

.travis.yml, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
This pull request fixes #2716
Thanks @simon-dube for the report, hopefully this fixes it!
=> BF: guard conversion from % complete better

datalad/metadata/extractors/annex.py, datalad/metadata/extractors/base.py, datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/metadata/tests/test_search.py
See individual commits please for the summaries
=> A variety of enhancements and fixes for metadata search

.travis.yml
The issue has been fixed in v3.0.1.
Re: #2742
=> TST: travis: Unpin grunt-contrib-qunit

.travis.yml
The issue has been fixed in v1.7.8.
Closes #2774.
=> TST: travis: Unpin Sphinx

docs/source/basics.rst
Info lifted from issue comment by @yarikoptic
=> DOC: Info on IDs (fixes gh-2801)

docs/source/customization.rst, docs/source/metadata.rst
=> More docs on metadata handling in DataLad

datalad/distribution/tests/test_update.py, datalad/distribution/update.py
Fixes #2858, and makes the state of `update` and particularly its tests a bit nicer.
=> Some love for `update`

datalad/metadata/search.py
Required to be able to handle proposal in gh-2753
Good to go, and useful -- regardless of the outcome of gh-2753.
=> `search` updates for improved metadata layout

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
=> Fix path handling in annex error output

datalad/interface/rerun.py, datalad/support/gitrepo.py
=> Add cherry-pick method to GitRepo; use in rerun.py

datalad/interface/utils.py
=> RF: Exclude 'notneeded' messages in the default renderer

datalad/metadata/metadata.py
Running as a PR for the sake of testing
=> Minor spotted typo

.travis.yml, README.md
For travis, to not have things randomly break.
=> TST: -revolution extension test run

datalad/support/gitrepo.py
Eases customization in derived classes.
=> RF: repo creation into a dedicated helper

CHANGELOG.md, datalad/distribution/install.py, datalad/distribution/tests/test_install.py
=> BF+TST: do not pass "dataset" kwarg into a bound .get call

datalad/interface/run_procedure.py, datalad/interface/utils.py
=> ENH: run-procedure

datalad/support/tests/test_annexrepo.py, datalad/tests/test_utils.py, datalad/utils.py
=> BF: assure reasonable CMD_MAX_ARG

appveyor.yml, datalad/distribution/tests/test_install.py
=> BF(workaround,Win): skip testing of installation with not yet fixed annex

datalad/interface/run.py
=> ENH: run: Add short flags for --input and --output

docs/source/index.rst, docs/source/publications.rst
Please contribute anything relevant. Thx!
=> DOC: Start publications page

datalad/cmd.py, datalad/customremotes/archives.py, datalad/customremotes/tests/test_archives.py, datalad/plugin/wtf.py, datalad/tests/test_cmd.py
Goes along with https://github.com/datalad/datalad-crawler/pull/30
This is done, but the crawler PR resulted in a complete nervous breakdown of its tests. Looks unrelated, but hard to tell.
=> Bunch of minor cleanup's

datalad/cmdline/helpers.py
=> ENH: datalad --help   uses no man(page)

datalad/interface/add_archive_content.py, datalad/interface/rerun.py
=> Clean up two stale comments

datalad/distribution/add.py
=> BF: get stderr if present, otherwise just use str(e)

datalad/downloaders/tests/test_http.py
=> BF(TST): Disable problematic (on generator) use of @use_cassette

datalad/core/local/save.py
* Replace `save` with `rev-save`.
* Add `-u` flag to make a command work as described.
=> Fixups to rev-save's help description

appveyor.yml
=> TST: Enable core tests on appveyor

CHANGELOG.md, tools/link_issues_CHANGELOG
Also fixed up a bug for being unable to catch multiple issues in the same line (now should be space or comma separated)
=> BF: tune up tools/link_issues_CHANGELOG for changes in #3271

datalad/support/json_py.py
Analog to `load()`
Needed for https://github.com/datalad/datalad-revolution/pull/84
=> ENH: Compression auto-detection for load_stream()

datalad/cmd.py
Thanks to @kyleam 's recent merge of 0.11.x into master, the https://github.com/datalad/datalad/pull/3322 is the only thing to be brought as well.
=> Bring Runner OPT into master

datalad/core/local/diff.py, datalad/core/local/tests/test_diff.py, datalad/support/exceptions.py, datalad/support/gitrepo.py
Closes #3375 
So my comment was nothing really "tricky" but may be I have missed the point.
=> RF: Use a dedicated new exception InvalidGitReferenceError

CHANGELOG.md, datalad/version.py, docs/source/changelog.rst
Final changelog touch-up after #3387, plus version bump, and RST changelog update.
=> Prep for 0.12.0rc3 release

CHANGELOG.md, CONTRIBUTING.md
Post-RC3-release chores
No test runs for this one.
=> Update placeholders to please new machine lords

datalad/core/local/tests/test_diff.py, datalad/core/local/tests/test_save.py, datalad/support/constraints.py
Spotted in rev_create -> create PR
=> RF: no need for import X as X - just import X

datalad/core/local/tests/test_save.py
When an unlocked annex file is added by 'git annex add' to git rather
than back to the annex (e.g., because its size now falls under the
annex.largefiles threshold), git-annex's pre-commit hook will fail
with a partial commit error on 'git commit -- FILE'.  See
1a609d4be (BF: annexrepo: Avoid typechange when using temporary index,
2019-04-30) for a more complete description.
AnnexRepo.commit() (and thus add/save) work around this by dropping
the pathspec from the commit call, using a temporary index if needed
to avoid committing staged changes that weren't in the specified
pathspec.
On the other hand, rev-save, which doesn't use AnnexRepo.commit(),
partially works around this by calling 'git commit' with no
pathspec (after updating the specified paths in the index) only if
there initially …
=> TST: rev-save: Demonstrate partial index failure

CHANGELOG.md, datalad/version.py
Anticipates a merge of #3402 before the release.
=> DOC: Changelog and version bump for 0.12rc4

datalad/plugin/addurls.py, datalad/support/annexrepo.py
One step closer to a complete removal of this broken code.
Please give feedback on test bit below. Thx.
https://youtu.be/dmxCA03DJ04?t=90
=> RF: Drop use of `add` in `addurls(save=False)`

datalad/support/gitrepo.py
Found in the desert....unused, untested, incomplete
=> RF: Remove dead and incomplete code

datalad/interface/rerun.py, datalad/interface/tests/test_rerun.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
to bring in
NF: rerun: Add --explicit flag
BF: annexrepo: Adjust overly selective is_special_annex_remote()
=> Enh merge 0.11.x to master

datalad/support/s3.py
=> ENH(TST): code to produce s3://datalad-test1-manydirs-versioned/ for testing

.travis.yml, tools/ci/benchmark-travis-pr.sh
Just for my personal pleasure (fixes #3539). Example: https://travis-ci.org/datalad/datalad/jobs/560509048#L1246
- appveyor intentionally not ran
=> TST: Add travis run that compares PR benchmarks against current master

datalad/core/local/create.py, datalad/core/local/diff.py, datalad/core/local/status.py
See https://github.com/datalad/datalad/pull/3366#discussion_r280289780
Closes: #3382
=> BF: replace "no cover" with "more cover" for cases where a dedicated testing was not implemented

README.md
=> DOC: list extensions with their names, remove revolution (now that it is in master)

setup.py
This adds an opinionated selection of PyPi classifiers that I am happy to debate and alter as you see fit.
This change touches upon an issue related to the upcoming removal of PY2 support that was brought up in https://github.com/datalad/datalad/pull/3629#issuecomment-527197881
=> DOC: PyPi classifier proposal

appveyor.yml, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
fixes gh-3635 
Tests enabled on appveyor now, too.
=> TST: gitrepo on windows

datalad/interface/clean.py
=> RF: `clean()` no longer uses AnnotatePaths

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> RF: Remove obsolete helper functions

datalad/core/local/diff.py, datalad/core/local/run.py, datalad/core/local/save.py, datalad/core/local/status.py, datalad/distribution/get.py
Avoids a number of redundant checks gh-3711
=> RF: Reduce access to Dataset.repo in a few places

appveyor.yml, datalad/distribution/tests/test_get.py, datalad/interface/results.py
Fixes #3634 by fixing two path handling issues.
=> Make `get` run on windows

.github/workflows/main.yml
=> Github workflow to run benchmarks against master

.github/workflows/docbuild.yml
Canceled all CI runs except for the new one to save on carbon footprint.
=> Workflow to build docs in a dedicated CI run

.travis.yml
=> Travis setup changes after introduction of GitHub actions

.github/workflows/test_extensions.yml, .travis.yml
Disable corresponding functionality on travis. This should reduce the total runtime of the tests.
Fixes gh-3760
=> TST: GitHub action to test compatibility with extensions

datalad/distribution/dataset.py, datalad/distribution/tests/test_dataset.py
=> Make Dataset('^') work with CWD not being a dataset root

datalad/distribution/install.py
=> RF: Delete some cruft and reformat

datalad/core/local/tests/test_create.py
Just adding the test posted in the bug -- nothing to fix.
=> TST: Ensure gh-2927 never happens again (fixes gh-2927)

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
=> BF: Don't run isdir on a relative path

datalad/support/gitrepo.py, docs/source/designpatterns.rst, docs/source/index.rst, docs/source/modref.rst
This is by no means comprehensive, but it is a start. It is also no competition for CONTRIBUTING.md -- there is no overlap.
Please feel encouraged to contribute the patterns that you are following in a dedicated PR. For now I only tried to write up the two aspects that we recently discussed and reconfirmed in https://github.com/datalad/datalad/pull/3791
=> Start documenting design patterns

datalad/distribution/publish.py, datalad/distribution/tests/test_publish.py
Yield 'impossible' result in this case.
Fixes gh-1811
Now looks like this:
```
mih@meiner /tmp/clone (git)-[9995911...] % datalad publish --to origin
publish(impossible): . (dataset) [Cannot determine remote branch name from HEAD]
```
=> BF: Detect a detached HEAD that prevents publication of HEAD

datalad/core/local/run.py, datalad/core/local/tests/test_create.py, datalad/distribution/clone.py, datalad/distribution/dataset.py, datalad/metadata/search.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py, datalad/support/repo.py
This is a long due follow up to PR #2946.
=> PERF/RF: Dataset.repo and friends

datalad/distribution/get.py, datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
=> RF: Remove obsolete GitPy-based GitRepo._get_files_history()

datalad/support/gitrepo.py
=> RF: Reimplement GitRepo.get_commit_date() without GitPy

.github/workflows/test_win2019.yml
Previous powershell snippet stopped working
=> BF: Try using Python to download git annex on windows

.github/workflows/test_extensions.yml
Unclear why they were not enabled already.
=> TST: Enable crawler extension tests

datalad/cmdline/helpers.py
- sort commands alphabetically (there is no point in maintaining a
semantic structure within a single line)
- wrap to 70 chars line length to match option display
- introduce spaces between commands to improve readability
Was:
```
Usage: datalad [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version]
[--dbg] [--idbg] [-c KEY=VALUE]
[-f {default,json,json_pp,tailored,'<template>'}]
[--report-status {success,failure,ok,notneeded,impossible,error}]
[--report-type {dataset,file}]
[--on-failure {ignore,continue,stop}]
[--proc-pre <PROCEDURE NAME> [ARGS ...]]
[--proc-post <PROCEDURE NAME> [ARGS ...]] [--cmd] [-h]
{create,install,get,add,publish,uninstall,drop,remove,update,create-sibling,create-sibling-github,create-sibling-gitlab,unlock,save,search,metadata,aggregate-metadata,extract-metadata, …
```
=> ENH: Improve readability of short help

datalad/distribution/get.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py
=> Fix broken error message

datalad/utils.py
This implements step 1-2 of @kyleam's proposal from
https://github.com/datalad/datalad/pull/3786#issuecomment-541885786
to a brighter future.
I will close #3786 in response to this.
=> RF: 'assure_*()' -> 'ensure_*()'

datalad/tests/utils.py
=> BF: More precise error message (fixes gh-2459)

.zenodo.json
Until know I had forgotten to put my name to the ``.zenodo.json`` file...
=> DOC: add adina to contributors

datalad/support/network.py, datalad/support/tests/test_network.py
Salvages this bit from https://github.com/datalad/datalad/pull/3918 and adds a test for it.
=> PathRI from Path object

datalad/distribution/tests/test_clone.py
* Correct comment
* Replace `known_failure_windows` with `known_failure_appveyor`
=> gh-3934 touch-ups

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
Closes #3951
If anyone has recommendations to improve, submit as suggestions or push directly.
=> BF: do not define pushurl for subdataset if there is no pushurl provided

datalad/distribution/siblings.py, datalad/distribution/tests/test_siblings.py
original one is db3d78506e2ab20b08a51f3c6294c0731e6c6313
=> CP of BF #3951 (pushurl) into 0.11.x

datalad/core/local/tests/test_create.py, datalad/core/local/tests/test_run.py
=> TST: Enable more core tests on windows

datalad/core/local/tests/test_diff.py, datalad/support/gitrepo.py
=> BF: gh-3997, never use the worktree as reference when diffing against a commit

datalad/interface/tests/test_add_archive_content.py
However, the test is also affected by gh-2572
=> BF: Proper windows-compatible test expression (fixes gh-2534)

datalad/distribution/tests/test_update.py, datalad/distribution/update.py, datalad/interface/base.py
Merges into master #4002 (Closes #3203) and #3996 (Closes #3097)
=> BF: merge 0.11.x - 2 PRs

datalad/ui/progressbars.py
But it is not clear to me, if this variable is used at all.
Going through a PR for feedback and safety.
=> BF: Looks like a typo

docs/casts/seamless_nested_repos.sh, tools/cast2asciinema
=> Update screen cast for 0.12

docs/casts/datalad_convenience_vs_git.sh, tools/cast2asciinema
It would be instrumental to get feedback on whether I am missing a more elegant approach for Git. Thx!
Recorded asciicast at https://raw.githubusercontent.com/datalad/talk-fosdem-2020/master/asciicast/datalad_convenience_vs_git.json
=> DOC: Cast to compare git vs datalad for a common submodule workflow

datalad/cmd.py
Prev. state used very similar variable names, and had (documented)
issues of scope confusion. This is an attempt to make things a bit
clearer.
=> RF: Make runner code (subjectively) more readable

.github/workflows/test_extensions.yml
Not every change in an unreleased master here, should require an extension release.
=> TST: Make GitHub CI test master of extensions and not releases.

datalad/support/gitrepo.py, datalad/support/tests/test_gitrepo.py
Also imported its tests and modified them for our use.
=> RF: Import GitPython code used for to_options()

datalad/support/exceptions.py, datalad/support/gitrepo.py
=> Two minor improvements

datalad/core/local/diff.py, datalad/core/local/tests/test_diff.py
When called with a trailing slash in a path argument matching a subdataset,
`diff()` will report on the content, not only on the subdataset record in
its superdataset -- even with `recursive=False`.
While this is not universally loved, it makes sense to not limit this
behavior to a single trailing slash.
When `subds/` reports on the entire subdataset, `subds/subdir` will now
only report on the content within `subdir` of `subds`.
Split from #4206
=> ENH: Extend rsync-like diff(path='subds/') to path constraints within the subds

datalad/support/annexrepo.py
=> BF: Protect against multiple JSON records being read at once

datalad/support/annexrepo.py
I am not sure how many more bugs can be in these 6 lines.
=> Reversed conditional in AnnexRepo.localsync()

.github/workflows/test_win2019.yml, appveyor.yml
When they say "jump!", we ask "how high?" ;-)
=> TST: Update annex version for windows tests

.github/workflows/test_win2019.yml
=> TST: Attempt to avoid short path reporting in GitHub Windows CI

appveyor.yml, datalad/distribution/tests/test_create_test_dataset.py, datalad/distribution/tests/test_uninstall.py, datalad/distribution/tests/test_utils.py, datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_globbedpaths.py, datalad/support/tests/test_locking.py, datalad/support/tests/test_sshrun.py
- bunch of legit fixes
- avoid running some tests twice on appveyor
- enable all of support, distribution tests
- fix #4297 #4299 #4300
=> Expand testing on windows

datalad/core/distributed/clone.py
=> DOC: examples of cloning specific ds versions from RIA stores

datalad/support/json_py.py, datalad/support/tests/test_json_py.py
Fixes #4360
I think once discovered this is quite obvious, but you changed that line last, @kyleam, so you might want to have a quick look.
=> BF: Actually decode JSON

datalad/metadata/tests/test_base.py
Fixes #4363 
Alternative to #4364
=> BF(TST): Reuse dataset instance and explicitly reload config upon external changes

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
=> BF: clone doesn't always annex-init

datalad/support/network.py, datalad/support/tests/test_network.py
This is an alternative to gh-4414 based on the discussion there.  If this is seen as an acceptable resolution, that's great.  But I'm completely okay with us closing this and seeing that PR to completion in one way or another.
=> RI: Avoid spurious message for pathlib objects and avoid unnecessary work

datalad/utils.py, datalad/version.py
Extracted from #4447 
If desired, could rebased against maint
=> Two minor RFs

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py, datalad/distribution/get.py
=> BF: Anticipate a plain Git repo in RIA post clone processing

datalad/distribution/publish.py
=> DOC: Announce deprecation of `publish`

datalad/support/gitrepo.py
I found no reason for a separate _diffstatus to exist, especially pretty much
remapping what is visible outside as eval_submodule_state into eval_state.
May be there was a reason and diffstatus was not just a proxy to _diffstatus.
=> RF: dissolve GitRepo._diffstatus by absorbing into diffstatus

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/log.py, datalad/support/annexrepo.py
Sit on top of #4547
Fixes gh-4521
Relevant commit: https://github.com/datalad/datalad/commit/ed5254789f61e0e54be7b92066861c64f1ec194b
=> BF: Make overall push progress report in bytes

datalad/distributed/ora_remote.py
Trying to address #4563
This should reduce the per-file overhead by avoiding to query annex for DIRHASH twice during `git annex copy --to` and have that effect with a local RIA store as well as over SSH.
=> PERF: Reduce per-file overhead by ORA remote

CHANGELOG.md, datalad/distribution/publish.py
per weekly hangout discussion.
individual commit msgs might provide more reasoning
=> ENH: un-deprecate publish

datalad/support/tests/test_annexrepo.py
=> BF: Use appropriate test for an annexed file

datalad/support/tests/test_annexrepo.py
=> TST: Adjust test for inappropriate platform assumptions

datalad/support/tests/test_annexrepo.py
=> TST: Adjust test assumptions to be more robust

datalad/support/tests/test_annexrepo.py
=> BF: Use standard filename obscurity

datalad/support/tests/test_sshconnector.py
Tested filename not supported by filesystem (see gh-4728)
Test also failed due to the inability to use SSH control master
based connections, but the actual functionality works.
Arguably, SSH tooling should be able to handle that, and this particular
test should not test whether some internal connection mechanism worked.
Fixes gh-4726
=> TST+BF: SSH test assumptions invalid on windows/*FAT

datalad/support/gitrepo.py
The previous git-show can be slow with more complex commits (e.g.
octopus merge commit, see gh-4801)
Switch to `git-log` as suggested in #4801.
Companion of https://github.com/datalad/datalad/pull/4806
=> OPT: Faster approach to GitRepo.format_commit()

pyproject.toml
Should close #4812, but explicit manual testing is likely needed
=> BF: require "wheel" at package build time

datalad/cmdline/tests/test_main.py
As of d40822340 (Use console_scripts entry points, 2020-07-12), the
scripts may contain "EASY-INSTALL-ENTRY-SCRIPT" and an import from
pkg_resources when installed with `pip install -e`.
@yarikoptic: if merged, Closes gh-4812
=> TST: test_script_shims: Update for use of console_scripts

.travis.yml
CPed from https://github.com/datalad/datalad/pull/4804
=> BF(TST): Define NOSE_OPTS as an array to start with

datalad/core/distributed/push.py, datalad/core/distributed/tests/test_push.py, datalad/distribution/publish.py, datalad/distribution/tests/test_create_sibling.py
These are trivial typo fixes.  Will merge if tests pass.
=> BF: push, publish: Fix "specific => specify" typos in results

datalad/support/gitrepo.py
This is recovering the first set of changes from the stale gh-4689
The main reason for not redoing #4689 is the lack of time to handle the complexity. So here is something simpler that doesn't reach the finish line, but is more comprehensible.
=> RF: Replace trivial usage of _git_custom_command with call_git*()

datalad/support/annexrepo.py
Follow-up to gh-4841 to eventually fulfill gh-4689
Diff looks complicated but it is basically moving the function body into
the `try` block to be able to use `call_git_items_()`
=> RF: Remove last usage of GitRepo._git_custom_command from AnnexRepo

datalad/cmdline/helpers.py, datalad/cmdline/tests/test_main.py, datalad/core/distributed/tests/test_clone.py, datalad/core/local/tests/test_create.py, datalad/distribution/tests/test_create_sibling.py, datalad/distribution/tests/test_install.py
=> RF: Replace Runner->WitlessRunner in some tests and helpers

datalad/support/gitrepo.py
I cannot think of a reason why the (previously two) would need to be
configured differently (which could have been the case before). Having
only one runner prevents this possibility -- for better or worse.
Fixes gh-4890
=> OPT: Re-use ConfigManager._runner for an associated Repo instance

datalad/plugin/addurls.py
Just `addurls` since I was there at the moment, but I guess there could be many other spots which could benefit from a similar RF
=> RF(PY3): addurls - use "yield from"

datalad/core/distributed/push.py, datalad/support/annexrepo.py, datalad/support/gitrepo.py
Now GitRepo itself provides one.
=> RF: Avoid multiple GitWitlessRunner instances

.github/workflows/test_macos.yml
=> Submit coverage report for macOS to Codecov

.travis.yml
=> Don't move .coverage out of __testhome__

.github/workflows/test_macos.yml, tools/ci/download-latest-artifact, tools/ci/install-annex.sh
=> install-annex.sh: Support installation on macOS

datalad/distribution/get.py
gh-4853 reworked get() to avoid using repo.update_submodule().
_install_subds_from_flexible_source() now has logic that
* tries a direct fetch if the target commit isn't available locally
* unconditionally checks out the target commit
* tries to avoid a detached HEAD by moving the originally checked
out branch back to HEAD if the branch contains HEAD
It does all of these even if the starting commit matches the target
commit.  The unconditional checkout means that we always end up in a
detached HEAD, leading to confusing messages like
[INFO ] Reset subdataset branch 'master' to b292d7e3 (from
b292d7e3) to avoid a detached HEAD
Make all of the above logic happen only when the current commit
doesn't match the target.
---
Note: This is just adds an `if` condition and indentation.  A larger …
=> ENH: get: Avoid unnecessary checkout in subdataset update

datalad/distribution/drop.py
=> RF: Strip `AnnotatePaths` from `drop()`

datalad/support/gitrepo.py, datalad/ui/progressbars.py
ENH(UX): make tqdm react on changes in the terminal width
Discovered in https://github.com/tqdm/tqdm/issues/631 and version identified via
$> git describe --contains 1392025c4948f44ad6f2befc3a26b0403732abae
v2.1.0^2~3
verified to work quite nicely on a parallel addurls example (see #5022)
=> ENH pbar + typo fix

datalad/downloaders/http.py, datalad/downloaders/tests/test_http.py
=> ENH: added pragma to allow for no test coverage in case of ftp downloader on url which at times 503s

datalad/interface/utils.py
=> BF: Ensure result path is a string before string operations

datalad/core/distributed/tests/test_clone.py, datalad/distribution/tests/test_install.py, datalad/distribution/tests/test_publish.py, datalad/downloaders/http.py, datalad/downloaders/tests/test_http.py, datalad/interface/utils.py, datalad/support/tests/test_annexrepo.py, datalad/tests/test_tests_utils.py, datalad/tests/utils.py
Manually resolved a trivial import conflict.
=> Merge maint->master

CONTRIBUTING.md
=> DOC: add note to CONTRIBUTING.md on --traverse-namespace on windows

tools/downgrade-annex
Could have gone probably directly without PR but I do not to
disturb the force ;)
[ci skip]
=> ENH(tool): downgrade-annex helper

.github/workflows/test_macos.yml, .travis.yml, datalad/install.py
=> Convert install-annex.sh to Python

datalad/distributed/ora_remote.py
git-annex's shutdown process for external remotes was tweaked in
7245a9ed5 (Improve shutdown process for external special remotes and
external backends, 2020-11-02), part of the 8.20201103 release.  With
that commit, git-annex waits for stderr rather than closing it at
shutdown of the external remote program.
This is reported to fix a stall on Windows, but it also triggers one
with the ora remote (seen on the github actions with Ubuntu and for me
locally on Debian Buster).  All of the initremote failure checks in
test_initremote_basic() against an SSH target trigger a stall.  This
can be easily triggered outside of the tests by using a non-existing
SSH target:
$ git annex initremote --debug ria-remote \
encryption=none type=external externaltype=ora autoenable=true \ …
=> BF: ora: Trigger SSH cleanup on failure to prevent stall

.travis.yml, datalad/install.py, datalad/tests/test_install.py
=> Add "miniconda" install scheme, --batch and --path-miniconda options

datalad/install.py
[As requested](https://github.com/datalad/datalad/issues/5078#issuecomment-730549628) in #5078
=> install.py: Add "datalad" schema for installing Miniconda with datalad

datalad/install.py
=> install.py: Enable INFO logging when run as script

.travis.yml
Paid for 5 concurrent jobs plan, let's see if it works anyhow
=> ENH: travis -- remove cron run with bad scrapy (of no concern here any longer)

.github/workflows/update-contributors.yml
=> Prevent update-contributors from running on forks

.travis.yml
Closes #5189.
Docs references:
* https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
* https://docs.travis-ci.com/user/conditions-v1
=> Prevent cron-only Travis builds from starting on non-cron events

appveyor.yml
not yet sure what to be done
TODOs
=> Reincarnate appveyor coverage

datalad/install.py
=> Incorporate download-latest-artifact into datalad/install.py

datalad/install.py
=> datalad/install.py: Don't crash when called without arguments

datalad/core/distributed/clone.py
It helps to mitigate but does not 100% resolve the
https://github.com/datalad/datalad/issues/4644 -- it still might fail once in a rare while
=> BF: reload config of the cloned dataset whenever finished "cloning"

datalad/distributed/tests/test_create_sibling_ria.py, datalad/support/tests/test_annexrepo.py
=> BF(TST): declare two known tests fails on windows (on github ci or windows total)

datalad/core/distributed/tests/test_clone.py, datalad/support/gitrepo.py, datalad/support/tests/test_annexrepo.py, datalad/support/tests/test_gitrepo.py
This is a tuned and trimmed spin-off from #5303
=> Less with_testrepos for a more test running on all platforms

datalad/distribution/publish.py
=> MNT: publish: Announce deprecation

tools/ci/download-latest-artifact
See https://github.com/datalad/datalad-extensions/pull/77 for more information.
I'm not actually sure if the script in this repository is actually used, but just in case...
=> download-latest-artifact: Match "Location:" header case-insensitively

README.md
This PR fixes some minor mistakes in the README.
(The primary motivation is to test an aspect of the Travis API.)
=> Minor proofreading of the README

tools/ci/prep-travis-forssh.sh
This change is necessary in order for the script to work when used by datalad/git-annex on GitHub Actions' macOS environments.
cf. https://github.com/datalad/git-annex/issues/42
=> prep-travis-forssh: Support Docker installations using Docker Machine

datalad/distributed/ora_remote.py, datalad/distributed/tests/test_ria_basics.py
Introduce push-url config for ORA remotes. Like git itself `url` is the
required config, that is used for read and write operations by default,
while push-url is optional and only used for write operations.
Since a special remote can't tell what annex command it is being called
from, we don't know whether to use `url` or `push-url` during PREPARE.
Therefore always start using the (fetch-) url. However, whenever we
first encounter a request from annex suggesting a write operation to the
remote (TRANSFER-STORE and REMOVE for now), switch underlying IO class.
- Closes #5273
=> ENH: Support push-url with ORA special remotes

datalad/distributed/ora_remote.py
Non-functional PR. Separating it out to not pollute other PRs' diff.
=> PEP-8 and comment cleanup in ora_remote.py

datalad/distributed/ora_remote.py
Configuring ssh-host and base-path for an ORA remote predates ria+ URLs
and the consideration of git's URL rewrites. Those configs are also not
capable of specifying an HTTP connection let alone a separation of `url`
and `push-url`. Respect them for now if we don't find a URL, but issue a
deprecation warning. Will be removed entirely eventually.
=> Deprecate old ORA configs

datalad/interface/tests/test_run_procedure.py
now that windows builds are built with libmagic support
=> ENH: do not skip text2git test on windows

datalad/support/tests/test_annexrepo.py
and only on Travis and only the stalling run
=> BF(TST,workaround): skip stalling on travis NFS test

datalad/distribution/update.py, datalad/support/annexrepo.py
=> RF: Remove last use of AnnexRepo.sync() and deprecate method

.appveyor.yml
Curious if it will impact the report in this PR...
=> TST: Make appveyor codecov submission functional across all platforms

datalad/core/local/create.py
I consider those useful, even when no longer going forward with #5390
=> Minor beautifications salvaged from #5390

datalad/interface/run_procedure.py, datalad/interface/tests/test_run_procedure.py
=> BF: reload config in run-procedure

docs/source/index.rst
=> DOC: Update links to extension docs

.travis.yml
idea was to test against S3, but we never gone forward with it.
Even though those secrets are "encrypted", and most likely already not active/available iam, I do not think we
should keep them visible.
=> ENH: remove a shadow from an attempt to have secrets in travis CI

.mailmap
I'm using this now for GitHub commits and would like to remove the others that are not in use. Thank you!
=> Updating mailmap

datalad/core/local/status.py, datalad/distribution/dataset.py, datalad/interface/utils.py
I kept those in various throw away branches while looking at redoing #5576, but I guess they might better be committed on their own first.  I am ok to drop `TODO(OPT)` comments if so desired
=> A collection of a minor OPT, typo fixes, and extra TODO(OPT)? comments

datalad/core/local/create.py
=> DOC: - not _ in command name

datalad/distributed/ora_remote.py
With PR #5673 closed, address #5668 by improving error message.
Ping @mih
=> Enhance permission error message for ORA

README.md
=> DOC: Add JOSS paper badge

docs/source/cmdline.rst, docs/source/modref.rst
=> DOC: Move man pages for push from 'plumbing' into 'dataset operations'

datalad/plugin/addurls.py, datalad/plugin/tests/test_addurls.py
Desired to help figure reason out.  Ref: https://github.com/ReproNim/datalad-nda/issues/1
=> addurls Formatter - provide value repr in exception

.appveyor.yml, docs/source/design/index.rst, docs/source/design/log_levels.rst
This is not comprehensive, but a mere start and invitation to
contribute.
Work towards datalad/datalad#5831
=> Log level design -- a start

.gitignore, .travis.yml, CONTRIBUTING.md, datalad/__init__.py, datalad/consts.py, datalad/tests/test_tests_utils.py, docs/casts/basic_search.sh, docs/casts/publish_on_github.sh, docs/casts/reproducible_analysis.sh, docs/source/basics.rst, docs/source/changelog.rst, docs/source/metadata.rst, tools/ci/appveyor_install_git-annex.bat
Closes #5885
also added some extra ignores to .gitignore
=> RF: use https:// for datasets*.datalad.org

datalad/core/local/create.py, datalad/core/local/tests/test_save.py
To be merged ASAP to bring `master` back to life.
=> Fixup after #5441 which only removed half of `no_annex`

docs/source/design/index.rst, docs/source/design/python_imports.rst
This is a clearly subjective write-up that documents my personal
practice for the past years.
Such a write-up has been requested repeatedly in the past.
=> Write down implicit rules for import statements in the code base

datalad/distribution/siblings.py
Follow up to https://github.com/datalad/datalad/pull/5921/files#r692337399
discussion/suggestion
=> RF: minor - define only common worker kwargs in a reused dict

CHANGELOG.md
The proposed format is a mix of what Kyle did and what `auto` does.
Please do not argue with individual phrasing and other aspects, simply suggest a concrete change.
FTR: I will get officially angry should any automated procedure replace this work of art! ;-)
The release subtitle is non-negotiable.
=> 0.15.0 Changelog

datalad/cmdline/common_args.py, datalad/cmdline/helpers.py
=> Deprecate --pbs-runner

datalad/distribution/update.py, datalad/support/constraints.py
See individual commits for details.
=> Tuned `EnsureChoice` rendering and `update` doc tuning

_datalad_build_support/formatters.py, docs/source/cmdline.rst
Introduce the notion of core commands, remove the notion of 'plugins'.
It is now also no longer a plain list of command names.
=> Restructure cmdline API presentation

docs/source/design/credentials.rst, docs/source/design/index.rst
This fills a vacuum, but certainly does not answer all questions.
If you would like to see changes, please suggest commitable suggestions.
=> Coarse description of the credential subsystem's functionality

datalad/core/distributed/clone.py, datalad/core/local/resulthooks.py, datalad/core/local/run.py, datalad/distributed/create_sibling_gitlab.py, datalad/distributed/export_archive_ora.py, datalad/local/addurls.py, datalad/local/check_dates.py, datalad/local/copy_file.py, datalad/local/subdatasets.py, datalad/local/tests/test_wtf.py, datalad/local/wtf.py
that is `core/`, `local/`, `distributed/`, and `dataset/`
Ping datalad/datalad#5975
=> Discontinue exc_str() in all modern parts of the code base

.appveyor.yml, datalad/metadata/tests/test_extract_metadata.py
In response to my observation that the set of tests executed by travis and appveyor is not the same.
=> Align installation setup with Travis

datalad/core/local/tests/test_run.py, datalad/distribution/tests/test_dataset.py, datalad/distribution/tests/test_get.py, datalad/distribution/tests/test_install.py, datalad/interface/tests/test_rerun.py, datalad/interface/tests/test_rerun_merges.py, datalad/interface/tests/test_run_procedure.py
#5126 had a list of to-be-reenabled-under-Windows tests. Since the CI's seem to be idle atm, I've re-enabled them to see which of them still fail.
=> TST: Enable all disabled tests listed in  #5126 and more

datalad/core/distributed/tests/test_clone.py, datalad/support/tests/test_gitrepo.py, datalad/tests/test_testrepos.py, datalad/tests/utils.py, tools/testing/make_test_repo, tools/testing/start_website_in_docker-Dockerfile.in, tools/testing/test_README_in_docker-Dockerfile.in
GitHub stopped support for git://
https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> git://github.com -> https://github.com

datalad/core/distributed/clone.py, datalad/core/distributed/tests/test_clone.py
=> BF: clone tried to save new subdataset despite failing to clone 

docs/source/design/file_url_handling.rst, docs/source/design/index.rst
My recent reimplementation effort (#6165) maneuvered me into the
position to be able to provide this high-level description.
Fixes datalad/datalad#5891
Please suggest concrete changes/addition using the reviewing functionality of by pushing the this branch. Given the documentation-nature of this PR, I will merge this tomorrow, unless objections are expressed.
[skip ci]
=> Design document on the datalad/datalad-archives special remotes

.travis.yml, datalad/cmd.py, datalad/interface/common_cfg.py
=> Clean up inactive BatchedCommands

CODE_OF_CONDUCT.md, README.md
As discussed during today's call, here is an updated COC. Thanks all!
I've cancelled all checks.
=> DOC: Adopt the Contributor Covenant COC v2.1

docs/source/design/index.rst, docs/source/design/pos_vs_kw_parameters.rst
This is a satellite to #6176 to first (before resolving conflicts and updating that PR) establish agreed upon design specification.
=> DOC: positional vs kwargs design doc

.github/workflows/test_macos.yml
Same as PR #6286, but against `maint`
=> bump the python version used for mac os tests

datalad/support/gitrepo.py
=> Free GitRepo.bare of its ConfigManager-dependency

datalad/_version.py
=> Make version detection robust to GIT_DIR specification

datalad/config.py
=> Warn just once about incomplete git config

datalad/support/constraints.py
This is primarily done to test the code climate config. It removed a reported code duplication.
=> Remove code duplication

datalad/cmdline/tests/test_main.py, datalad/distributed/ora_remote.py, datalad/distributed/tests/test_ora_http.py, datalad/utils.py, tools/coverage-bin/git-annex-remote-ora
Includes https://github.com/datalad/datalad/pull/6355
=> Merge origin/maint '0.15.4-18-gf6c35c4fe'  into master

.codeclimate.yml
[skip ci]
Need not be mentioned in the changelog.
=> Import codeclimate config from extension template

.appveyor.yml
=> Appveyor update

docs/source/modref.rst
a quick fix for #6410, hopefully.
(no changelog entry needed)
=> DOC: include status in Python API overview

datalad/local/configuration.py
=> Update `configuration()` in the spirit of #6461

datalad/local/foreach_dataset.py, datalad/local/no_annex.py, datalad/local/remove.py, datalad/metadata/aggregate.py
=> Update foreach-dataset|no_annex|remove|aggregate-metadata() in the spirit of #6461

datalad/local/addurls.py
=> Update `addurls()` in the spirit of #6461

datalad/local/subdatasets.py, datalad/local/tests/test_subdataset.py
=> Update `subdatasets()` in the spirit of #6461

datalad/distributed/create_sibling_ghlike.py, datalad/distributed/create_sibling_gitlab.py, datalad/distributed/create_sibling_ria.py, datalad/distributed/tests/test_create_sibling_ria.py
=> Update `create_sibling*()` in the spirit of #6461

datalad/cli/tests/test_main.py, datalad/customremotes/archives.py, datalad/customremotes/datalad.py, datalad/customremotes/main.py
- Fixes #6460 
No changelog needed, this rectifies a diff introduced in the 0.16 dev series.
=> Bring back the standard CLI interface for special remotes

datalad/metadata/aggregate.py, datalad/metadata/extractors/datalad_core.py, datalad/metadata/metadata.py, datalad/metadata/search.py, datalad/metadata/tests/test_search.py
This PR contains keyword unification work (issue #6461) of the metadata modules
- ensure that internal datalad command calls do write results to stdout
=> Unify interface keyword args of metadata commands according to issue #6461

datalad/cli/tests/test_main.py
This is necessary, because the UI holds its own handle of `sys.stdout`
that was not affected by the previous patch approach.
With this change, the same StringIO instance is used for both
`sys.stdout` and the `UI.message()` outlet.
With this change, `run_main()` is no suitable for testing more CLI
aspects, such as result renderer output in response to CLI calls.
The resulting three context manager calls have been collapsed into
a single statement, rather than continuing the pattern from before.
- The `run_main()` test helper is now able to capture `UI.message()` output too. Fixes #6561
=> Make `datalad.cli.tests.test_main.run_main()` also capture UI output

datalad/support/sshconnector.py
Besides providing some convenience to developer to see docstring right by
the signature
- they are duplicate
- make harder to see code between all the docstrings
- they are duplicate (copy pasted) and thus at times incorrect/not
adjusted for the subclass (e.g. nomultiplex one was claiming to get a singleton
for a shared ssh connection
pydoc and pycharm are just fine without docstrings in subclasses -- they pick
them up from the base class, so we do not even need an explicit
@borrowdoc I thought we would need
Closes #6536 
- Remove duplicate docstrings in subclasses of sshconnector
=> DOC: sshconnector - remove duplicate docstrings in subclasses

datalad/distribution/tests/test_dataset.py
=> Modernize test

datalad/distribution/tests/test_siblings.py
=> Remove testrepo usage from `siblings` test

datalad/distribution/tests/test_get.py
=> Discontinue with_testrepos in `get` tests

datalad/distribution/tests/test_update.py
=> Remove with_testrepos from update tests

datalad/tests/utils.py
There is nothing windows specific there any longer
=> DOC: fixup of docstring for skip_ssh

CONTRIBUTING.md
=> DOC: Add git-annex bug report tips to contributing

datalad/core/local/tests/test_status.py
=> BF(TST): do proceed to proper test for error being caught for recent git-annex on windows with symlinks

datalad/support/gitrepo.py, datalad/support/tests/test_repo_save.py
Namely:
- https://github.com/datalad/datalad/pull/6793
- https://github.com/datalad/datalad/pull/6784
=> Merge `maint`, resolving conflicts between typechange-related PRs

datalad/support/annexrepo.py, datalad/support/tests/test_annexrepo.py
Since 10.20220724-5-g63cef2ae0 git-annex started to upgrade to v10 even though
v8 is still supported.  Our hard-coded mapping we relied on to report to the
user that upgrade is too happen would not allow for neede flexibility so
I removed it and ajusted INFO message to report what we know -- that upgrade
would be to at least the first supported version.  Test also was adjusted accordingly
while still testing prior behavior
Fixes #6900
=> BF: do not pretend we know what repo version git-annex would upgrade to

datalad/distributed/create_sibling_ria.py
=> Explain purpose of create-sibling-ria's --post-update-hook

.appveyor.yml
https://github.com/datalad/datalad/pull/6915 has done that for Travis
Should cut tests run time by considerable %
=> Run pytests in parallel (-n 2) on appveyor

docs/source/design/github_actions.rst, docs/source/design/index.rst
Broken in 5bf357a2c20500b741f7c98a02d2c6c7becdfb6f
=> RST syntax fix

.github/workflows/test_crippled.yml, .github/workflows/test_extensions.yml
=> Revert back to non-devel neurodebian in crippledfs/extensions, add testing against -next

.github/workflows/test_extensions.yml, changelog.d/pr-7136.md, datalad/__init__.py, datalad/conftest.py, datalad/support/annexrepo.py, docs/source/design/python_imports.rst, docs/source/modref.rst, setup.py
Addressing  #7100
(Need to figure how to deal with `py.path.local`s)
=> Removing traces of nose

changelog.d/pr-7142.md, datalad/downloaders/base.py, datalad/downloaders/http.py, datalad/support/exceptions.py
=> BF: HTTP Downloader treated 429 as authentication issue

CHANGELOG.md, changelog.d/pr-7111.md, changelog.d/pr-7112.md, changelog.d/pr-7117.md, changelog.d/pr-7118.md, changelog.d/pr-7119.md, changelog.d/pr-7123.md, changelog.d/pr-7125.md, changelog.d/pr-7126.md, changelog.d/pr-7130.md, changelog.d/pr-7136.md, changelog.d/pr-7142.md, docs/source/changelog.rst
=> Fix 0.17.9 release

datalad/cmd.py
I don't think this needs a changelog.
=> Fix for type checking

changelog.d/pr-7155.md, datalad/runner/nonasyncrunner.py, datalad/runner/runner.py
=> Fix runner not dealing with str as stdin

.github/workflows/test_extensions.yml
Taken from https://github.com/datalad/git-annex/pull/147/commits/42dae559175daad27ace21e62b30ce4428613244
=> Install Singularity 3 from official DEB

datalad/tests/test_cmd.py
Fixes #7229 
This PR moves the timeout processing in ThreadedRunner out of the `Empty`-exception handler. This is done to prevent raising a `TimeoutError`-exception while handling an `Empty`-exception.
=> Move timeout processing out of exception handler processing

CHANGELOG.md, docs/source/changelog.rst
I do not think we need changelog entry for this change
=> Harmonize 0.18.0 changelog sections without icons into the ones with icons

setup.py
I don't really think it is worth changelog
=> Add scriv to devel-utils

changelog.d/pr-7327.md, datalad/support/globbedpaths.py, tox.ini
=> Type-annotate `datalad/support/globbedpaths.py`

changelog.d/pr-7339.md, datalad/support/annex_utils.py, datalad/support/ansi_colors.py, datalad/support/cookies.py, datalad/support/digests.py, tox.ini
=> Type-annotate some more files in `datalad/support/`

changelog.d/pr-7489.md, datalad/core/distributed/tests/test_clone.py, datalad/tests/utils_pytest.py
To make daily runs clearer to not mask some real issue.
ref:
- https://github.com/datalad/datalad/issues/7485
=> Announce test_clone_datasets_root xfail on github osx

datalad/distribution/update.py
Closes #7524
Thanks @William-N-Havard for taking time to report
=> Add a missing space into example code_cmd

.github/workflows/release.yml, CONTRIBUTING.md, changelog.d/pr-7553.md
Ref: https://github.com/datalad/release-action/pull/51 for more info
=> Add manual triggering support/documentation for release workflow

changelog.d/pr-7690.md, datalad/support/tests/test_parallel.py
Got there while working on 
- #7686
=> test: refactor test_parallel.py to be abit more pytest'y

changelog.d/pr-7716.md, docs/source/acknowledgements.rst
Updated acknowledgements.rst to include additional grants and funding sources from the JOSS paper and README.md. This keeps documentation in sync across different parts of the project.
Motivation: https://github.com/datalad/datalad/pull/7697
PS mostly done by `claude code`
=> enh: update acknowledgments with additional grants
