datalad/datalad

- datalad/__init__.py
- datalad/cmdline/cmd_test.py
Needs
- probably drop using numpy's shim but just run nose tests using
directly nose
- needs to pass at least some nosetests cmdline  options (e.g. -s -v)
- it seems that fails tests if ran as if installed
- also, in installed form we would lack the testrepo submodules.
Default operation of with_repos now is to raise and expection (instead 
of Skip) if no repositories were found -- may be we should rethink that
But in general we should aim to provide such a functionality
> ENH: a rudimentary stub for a 'datalad test' command

- datalad/cmdline/__init__.py
- datalad/cmdline/cmd_get.py
- datalad/support/annexrepo.py
- datalad/support/dataset.py
- datalad/support/gitrepo.py
- datalad/tests/heavyoutput.py
- datalad/tests/test_annexrepo.py
- datalad/tests/test_cmd.py
- datalad/tests/test_cmdline_main.py
- datalad/tests/test_dataset.py
- datalad/tests/utils.py
Actual command is present.
Globbing is supported, anything else only if the shell itself expands it, for now.
More tests are needed, but this is a matter of creating fancy testrepos from my point of view and therefore not a topic of this PR.
> NF: command "get"

- datalad/tests/test_annexrepo.py
- datalad/tests/test_dataset.py
- datalad/tests/test_main.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
This way we can more easily chain decorators without getting lost which then
argument gets embedded into the test function list of arguments.  Before this,
some were pre-pending, or using **kwarg, making it all messy and inconsistent.
Additional tests now very correct operation and double-decoration with e.g.
with_tempfile.  Closes #60
> BF/ENH: test helper decorators should pass new arguments as "additional" ones

- datalad/tests/test_cmd.py
atime might change on systems with atime mount, thus comparing it causes
problems at times:
https://travis-ci.org/datalad/datalad/builds/54880683
mtime -- should be the same but we still keep that check disabled for now
> BF: do not compare atime/mtime for a copy

- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
we lost our custom tempfiles prefix a while back without noticing
and in part because of some obnoxious swallow -- I dont really see a reason for it, thus removed try/except
also introduced two new checkers
Q: should we adopt having "nok_" prefix for negated asserts? or may be some other?
> BF: bring back our custom tempfiles prefix and do not swallow exception

- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
Conflicts:
datalad/tests/test_tests_utils.py -- I was picking up from another branch.
Took the state of other branch and removed imports which are not present
here
> BF,TST: return back to original cwd if test brings us somewhere else (Closes #96)

- datalad/tests/test_main.py
just saw that we still have this one -- viva warnings
left logic/variable available altogether for the record and happen we run into this again
> ENH: #79 was addressed so we can test with empty load now

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/tests/test_annexrepo.py
- datalad/tests/test_gitrepo.py
- datalad/tests/test_handle.py
`+` refactor file_has_content to work for a single or multiple files reliably.
This way coding becomes easier and more "logical", since you don't get lists back even if you ask about a single file.  I still fill though that we might simply need additional option for this normalize_paths for cases if function can't operate on multiple files -- then we shouldn't may be even wrap into a list -- just provide normalization.
As for `file_has_content`, and `get_file_key` - they are outcasted in the API where everything else starts with `annex_` so we might want to unify
> RF: normalize_paths to return a single output if a single input filename is provided

- datalad/customremotes/archive.py
- datalad/customremotes/base.py
- datalad/support/annexrepo.py
- datalad/tests/test_cmd.py
Testing this solution to see if it helps to reduce number
of zombie git processes on buildbot dockers
> RF: call git-annex directly (not git annex) where possible

- Makefile
Due to popular demand: a `make test` that doesn't need pip or other fancy Python foo to run the tests on a mortal's machine.
> ENH: Make 'make test' work

- datalad/tests/test_annexrepo.py
- datalad/tests/utils.py
test helper ok_annex_get used to always check the output of wget/curl. In case retrieving a file's content doesn't involve a remote clone but a locally available one, this test failed.
> BF: ok_annex_get always assumed a download was needed.

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/tests/test_annexrepo.py
- datalad/utils.py
As proposed herein, always_commit works as a mode of operation. Set to false to not instantly commit changes by git-annex calls.
Note: windows fails due to issue #147
> NF: Introduce always_commit option

- .gitmodules
- CONTRIBUTING.md
- datalad/support/annexrepo.py
- datalad/tests/__init__.py
- datalad/tests/test_testrepos.py
- datalad/tests/test_tests_utils.py
- datalad/tests/test_utils_testrepos.py
- datalad/tests/utils.py
- datalad/tests/utils_testrepos.py
- tools/testing/make_test_repo
So, testrepo should be generated whenever with_testrepos is used.
> RF testrepos -- generate testrepos locally (but only once per run) + allow for use of network "clone"

- .travis.yml
- Makefile
- datalad/cmdline/helpers.py
- datalad/cmdline/main.py
- datalad/interface/add_handle.py
- datalad/interface/crawl.py
- datalad/interface/create_collection.py
- datalad/interface/create_handle.py
- datalad/interface/get.py
- datalad/interface/install_handle.py
- datalad/interface/list_collections.py
- datalad/interface/list_handles.py
- datalad/interface/publish_handle.py
- datalad/interface/pull.py
- datalad/interface/push.py
- datalad/interface/search_collection.py
- datalad/interface/search_handle.py
- datalad/interface/sparql_query.py
- datalad/interface/uninstall_handle.py
- datalad/interface/update.py
- datalad/tests/test_cmdline_main.py
misc:
- spit out version in the bottom
- custom short usage
- "Command summary" instead of "Positional arguments"
now --help looks like
```
Usage: datalad [global-opts] command [command-opts]
DataLad provides a unified data distribution with the convenience of git-annex
repositories as a backend.  datalad command line tool allows to manipulate
(obtain, create, update, publish, etc.) datasets and their collections.
Commands for collection handling
- create-collection:  Create a new collection
- register-collection:  Register a collection with datalad
- unregister-collection:  Unregister a collection with datalad
- list-collections:  List all collections known to datalad
Commands for handle operations
- create-handle:  Create a new handle
- add-handle:  Add a handle to a collection
- …
```
> ENH: make global --help fit some screens + misc

- datalad/support/constraints.py
- datalad/tests/test_constraints.py
e.g. look at  `python -c 'import datalad.api as dlapi; print(dlapi.sparql_query.__doc__)'` before this fix
also simplified some conditions: isinstance(x, (t1, t2)) is equiv to isinstance(x, t1) or isinstance(x, t2)
> RF/BF: avoid having "<type ...>" in docstrings generated from constraints

- datalad/tests/__init__.py
That should allow to set them empty in debian/rules to make pybuild
not redefine them:
```
export http_proxy=
export https_proxy=
```
> ENH: remove empty http{,s}_proxy from the env while running tests

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/tests/test_annexrepo.py
Extracted from #205 to ease review etc.  Main goal here is to "sense" existing repositories without anyhow causing any changes in them.  It is not only about create or not create, but also about init or not init.
*whining:* I think part of the problem is actually due to decision to allow *Repo constructors to create repositories (i.e. having `create`).  E.g. now "constructor" might not only create and intialize a repository but also modify existing one (e.g. set backend, switch mode) etc, even if create is False.  But should it?  IMHO such actions should be done explicitly only when repository is explicitly created, or explicitly requested via corresponding methods. And imho ideally there should be a classmethod  `create` which would take that role while constructor at most would do …
> BF+RF AnnexRepo

- .travis.yml
- setup.py
It is listed under datalad_pkgs, and with listed in modules
in current sid then setup.py build fails while looking for
some obnoxious reason for datalad.py
Sending this minor one as a PR to get tests ran
> BF: do not list datalad under py_modules

- datalad/cmdline/main.py
- datalad/tests/test_gitrepo.py
- datalad/tests/test_tests_utils.py
- datalad/tests/test_utils.py
- datalad/tests/utils.py
- datalad/utils.py
The reason is that there is no bloody way to return
to original directory if original directory had
symlinked directories in its path.  The only way is to
cd PWD as in the environment.  BUT that one is set by the shell
and not but os.chdir.  So -- those functions become PWD
aware and adjust it upon chdir
This will be needed for carrying out unittests which would
need to change CWD/PWD to a specific directory
> NF+RF: os.{chdir,getcwd} -> utils.{chpwd,getpwd}

- datalad/interface/install_handle.py
- datalad/interface/tests/test_install_handle.py
- datalad/support/network.py
- datalad/tests/test_network.py
- datalad/tests/test_utils.py
- datalad/utils.py
Not sure if all of those checks/functionality should be within interface or the corresponding handle.
This PR also includes some utility additions/changes
whenever decided/acted upon #236, tests should be extended
whenever #234 is addressed, test should mock less, and we might even make a dedicated fixture e.g. @with_fake_localcollection
> BF+TST: "user-friendly" early error messages + rudimentary functionality test for install-handle Closes #223

- datalad/cmd.py
- datalad/tests/test_cmd.py
logging NullProtocol provides no information
Protocol: BlahProtocol  is duplicative since class name indicates it already
> ENH: do not log NullProtocol + report others within {}

- datalad/interface/uninstall_handle.py
Uninstalling handle, that was deleted before, led to exception and thus was not removing it from local master collection.
> BF: Uninstall non-existing handle

- datalad/tests/utils.py
If git-annex misbehaves, it would error out the runs which don't even use
our testrepos
> BF: no need to instantiate test repo every time we run any test importing utils

- datalad/__init__.py
- datalad/tests/__init__.py
- datalad/tests/test_main.py
- datalad/tests/utils.py
- datalad/utils.py
it required moving test fixtures all the way to `datalad/__init__.py` which is kinda not nice, but I guess that is the only way
> BF remove stale tempdirs which started to appear again

- datalad/support/gitrepo.py
- datalad/tests/test_gitrepo.py
I left original commits where I have tried to add more magic to the magical normalize_paths in the history.  IMHO we should review all the other functions and probably disable matching in many if not all of them.  
What if some glob which git understands is given?
> git remove -- should not match_return_type

- datalad/crawler/nodes/tests/test_annex.py
- datalad/dochelpers.py
- datalad/interface/add_archive_content.py
- datalad/support/annexrepo.py
- datalad/support/cookies.py
- datalad/tests/test_annexrepo.py
- datalad/tests/test_dochelpers.py
you would need 20160126 annex, avail from neurodebian now and all buildbots were updated -- we would need to merge this one asap for that reason
> ENH+BF: annex compatibility, use of --json ouput of addurl, minor cookies tune up etc

- datalad/crawler/pipelines/openfmri.py
- datalad/customremotes/tests/test_archives.py
- datalad/customremotes/tests/test_datalad.py
- datalad/downloaders/providers.py
- datalad/downloaders/tests/test_aws.py
- datalad/downloaders/tests/test_providers.py
- datalad/downloaders/tests/utils.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/tests/test_tests_utils.py
- datalad/utils.py
- tox.ini
this bug lead to reloading all the configs and reinitiating connections over and over again
e.g. during crawling
> BF+ENH: do not use redefined files for lazy evaluation in Providers.from_config_file, adjust mtimes for both link and file

- .travis.yml
- README.md
That service provides browser extension to display coverage right while browsing github -- real handy
> ENH: Enabling codecov support in travis

- CONTRIBUTING.md
- README.md
- datalad/downloaders/tests/test_http.py
- datalad/support/network.py
- datalad/tests/test_tests_utils.py
- requirements.txt
- tools/testing/.gitignore
- tools/testing/conf/etc/apt/apt.conf.d/99apt-cacher
- tools/testing/test_README_in_docker
- tools/testing/test_README_in_docker-Dockerfile.in
Today was a day of upload of a bunch of backports to neurodebian so we should be closer to be able to approach snapshot release and debian packages for it ;)
The only somewhat missing is recent release of HTTPretty, but looking toward updated package I have listed it as apt-get'able (it is, but old/broken in particular for python3)
There is a new cruel helper:  install docker and run e.g. `tools/testing/test_README_in_docker nd80` to see it deploy docker, install everything listed apt-get'able in README.md (but for bother python2 and python3), and run tox using system libraries.  This way we could become more or less sure that README has a complete listing.
Also there is few minor code cleansings
Please review and merge
> DOC+DOCTEST:  more exhaustive list of dependencees

- datalad/crawler/nodes/annex.py
- datalad/crawler/pipelines/openfmri.py
- datalad/support/tests/test_versions.py
- datalad/support/versions.py
to make it work again due to recent changes upload to openfmri
> ENH: improve catching versions (in openfmri in particular default to have 1.0.0 version)

- datalad/version.py
So we could easily include in our troubleshooting reports, e.g.:
```
$> datalad --version 2>&1 | head -1 
datalad 0.1.dev629-g75a6d
```
`-dirty` suffix would be added if there are uncommitted changes
> ENH: if running from under git __version__ will be based on git-describe

- datalad/api.py
- datalad/cmdline/main.py
- datalad/interface/__init__.py
This doesn't implement a clever lazy-importing scheme, but it
nevertheless removes all static interface imports. In a nutshell:
Static imports are replaced with definitions of what needs importing,
plus an optional definition of target names for Python API and cmdline
interface.
This moves us into a position to make import more clever/leaner/lazier
if needed in the future.
Closes #408
> No static interface imports anymore (closes: gh-408)

- datalad/distribution/create_publication_target_sshwebserver.py
- datalad/distribution/publish.py
- datalad/distribution/tests/test_target_ssh.py
partially addresses #464 (at least can reinvoke the same command again to create new needed target directories on the remote server)
also upgraded one log msg to .info since generally we want to see what is going on at least at the highest level
> ENH/RF: Allow for incremental publishing by --force -> --existing=skip

- datalad/distribution/install.py
I could swear I have had this change as a part of another PR but currently can't locate it... I guess I dreamed it up.  Anyways -- when installing, especially with --recursive, it would be nice if at least at INFO level we would have got some feedback about ongoing activities.
> ENH: upgrade .debug to .info for install API cmd to depict what is going on

- datalad/downloaders/credentials.py
- datalad/downloaders/providers.py
- datalad/downloaders/tests/test_credentials.py
- datalad/downloaders/tests/test_http.py
- datalad/support/keyring_.py
- datalad/support/s3.py
- datalad/tests/utils.py
- datalad/ui/__init__.py
- datalad/ui/base.py
- datalad/ui/dialog.py
- datalad/ui/tests/test_base.py
- datalad/ui/tests/test_dialog.py
also mark private credential fields explicitly (before everything was considered private since only getpass could have been used so that our prompts appeared from under the annex)
> ENH(TEMP workaround): monkeypatch getpass to echo its input + RF (Credentials)

- datalad/__init__.py
- datalad/customremotes/archives.py
- datalad/customremotes/base.py
- datalad/customremotes/main.py
- datalad/log.py
- datalad/support/tests/test_vcr_.py
- datalad/support/vcr_.py
- datalad/tests/test_misc.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
- datalad/utils.py
Inspired by whining against adding import of sshmanager into the top init -- apparently it wasn't the "worst" of our sins ;)
Primarily OPT was done through identifying heavy imports in few spots which we import from all around (e.g. vcr in utils).
It seems to shave off seconds from total run time of some tests (e.g. of customremotes)
I wonder how we could add some tests to somewhat 'establish' baseline import / execution times?
I though that may be (with all those added tracing imports debug lines) we could at least verify that some imports do not happen when we e.g. just execute 'datalad --help' etc.  what do you think?
BTW -- everyone is optimizing imports today !!! ;)  see e.g. https://github.com/tqdm/tqdm/pull/179
> OPT minimize initial import times and starttime of various cmdline entry points

- .travis.yml
That prevent coverage report tools to report back since they ended up
running from under docs/
@bpoldrack so it was my bad
> BF: do not cd under docs while running doctests etc

- datalad/support/constraints.py
- datalad/tests/test_interface.py
Should make error messages by argparse for misspecified arguments
a bit more user-friendly and informative.
Relates to #445 discussion on --recursive
> ENH: use short_description for constraints repr

- datalad/crawler/pipeline.py
- datalad/crawler/pipelines/crcns.py
- datalad/customremotes/archives.py
- datalad/customremotes/tests/test_archives.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/downloaders/credentials.py
- datalad/support/network.py
- datalad/tests/test_network.py
- datalad/tests/test_utils.py
- datalad/tests/utils.py
- datalad/tests/utils_testrepos.py
- datalad/utils.py
Whatever I thought would be a quick thing, ended up a monster which needs RFing, but I wanted first to run by you the idea.of having a URL class, which would expose pretty much all attributes which named tuple ParseResults return, but which
- supports ssh "urls", or possibly other "implicit"ly defined schemes (e.g. host:: for rsync?)
- supports our ad-hoc perspective '//[remote]/[dataset]' urls
`is_url` now should report ssh urls as urls as well
please look at `test_url` functions either you would agree with such behavior... or may be ':implicit' suffix should just migrate into 'implicit' attribute of URL?
Aims to close #440, #493, #441 
TODO:
> ENH: prototype for centralized URL handler

- datalad/cmd.py
- datalad/customremotes/base.py
- datalad/customremotes/tests/test_archives.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
Created a GitRunner subclass that inherits from Runner class in datalad/cmd.py. sets the required environment variables to point to git_root before running git annex based commands.
The chdir error seems to be gone after setting environment variable GIT_WORK_TREE and GIT_DIR. 
Still can't git annex drop from subdirectory.
git annex drop doesn't let you remove as it can't find other instances of the file to be dropped.
> BF: annex from subdir

- datalad/crawler/nodes/matches.py
- datalad/crawler/nodes/tests/test_crawl_url.py
- datalad/crawler/nodes/tests/test_matches.py
- datalad/crawler/pipelines/tests/__init__.py
- datalad/crawler/tests/__init__.py
- datalad/crawler/tests/test_pipeline.py
- datalad/tests/utils.py
So we could still build packages on 14.04 although the scraping wouldn't really be functional since available "installable" scrapy is too old
Should help to address #533
> BF: skip the tests which rely on newer scrapy so we build on 14.04

- .travis.yml
- datalad/cmdline/helpers.py
- datalad/crawler/pipelines/openfmri.py
Locally for me fails anyways with
```
Warning, treated as error:
/home/yoh/proj/datalad/datalad/docs/source/usecases/index.rst:5: WARNING: toctree contains reference to nonexisting document u'generated/examples/3rdparty_analysis_workflow'
```
but I am not sure yet who/when should've generated those
> Apparently master is broken due to some docs failures -- fixing up

- datalad/crawler/nodes/annex.py
- datalad/crawler/nodes/tests/test_annex.py
- datalad/crawler/pipelines/crcns.py
- datalad/crawler/pipelines/openfmri.py
Minor RF which I will merge if tests pass
To stay uniform with default behavior of add_archive_content itself
> RF: by default do not delete original archives durin Annexificator.add_archive_content

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/uninstall.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
Even though `uninstall` is neither well defined yet nor fully functional, I'd vote for merge.
There is a (drafted) `uninstall` in master already and this one is nonetheless an improvement to it.
Until further discussion during OHBM I'd like to stop working on that and focus on ironing the lower level things.
It currently should work for uninstalling files and subdatasets. `recursive` probably is not ready yet and uninstalling a dataset, that is not part of a superdatasets is not implemented yet. But from my point of view, core functionality is available and everything else is up to getting to an agreement on what it should behave like.
> ENH: uninstall

- .travis.yml
- datalad/crawler/nodes/matches.py
- tools/testing/bad_internals/_scrapy/scrapy.py
I think all our cases are covered and #583 actually does not demonstrate
some tests failing due to absent scrapy - it skips them but with this PR
we would be able to assure that.  scrapy is just an optional dependency
needed for some scraping pipelines
> ENH: run tests under condition of absent scrapy (Closes #583)

- datalad/consts.py
- datalad/distribution/dataset.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_install.py
- datalad/support/network.py
- datalad/tests/test_network.py
So we could do something like
```shell
datalad install ///openfmri/ds000001
```
no support of specifying the siblings name yet since we don't have discussed how we will 'register' them really yet
> ENH: make  install  understand DataLadRI

- datalad/interface/ls.py
- datalad/interface/tests/test_ls.py
Implementation of `ls` should be adjusted to return something meaningful
in Python world too, and print via a renderer.
> ENH: Make argument-less `datalad ls` work

- datalad/support/param.py
- datalad/tests/test_interface.py
otherwise only when dealing argparse misspecification would be caught
> ENH: catch misspecified parameter early

- datalad/distribution/create.py
- datalad/distribution/dataset.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_install.py
- datalad/interface/common_opts.py
- datalad/interface/tests/test_unlock.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/tests/test_protocols.py
New implementation of `create`.
Note, that it now needs `force` in order to create a dataset in a non-empty directory.
General usage in python:
create a dataset:
`Dataset("/where/to/create").create()`
or
`datalad.api.create("/where/to/create")`
create a subdataset (not just inside another but including registering it as a submodule):
`Dataset("/super/sub").create(add_to_super=True)`
or
`Dataset("/super").create_subdataset("sub")`
Please note, that creation of a subdataset requires the superdataset to already exist, of course.
> RF: Implement new API (create)

- datalad/interface/base.py
- datalad/interface/tests/test_docs.py
This is kinda ugly, because we need to save and restore the original
docs. Otherwise the entire search/replace setup needs to be redone
to be able to cope with indented blocks -- giant time sink....
> BF: In-line conditionals were not honored for parameter docs

- datalad/downloaders/base.py
- datalad/downloaders/http.py
- datalad/downloaders/tests/test_http.py
- datalad/tests/utils.py
> ENH: if 404ing download, but content provided - check content for "failed" messages

- datalad/distribution/create_test_dataset.py
- datalad/distribution/tests/test_create_test_dataset.py
- datalad/interface/__init__.py
otherwise requires nose to run it... detected after trying to use datalad
installed under singularity container with no recommends installed
tests pointed out few hidden bugs ;-)
> RF: move create_test_dataset outside of tests/

- datalad/support/external_versions.py
- datalad/support/tests/test_external_versions.py
- datalad/tests/utils_testrepos.py
- datalad/version.py
Since 
```shell
$> git shortlog -sn duecredit/versions.py
3  Yaroslav Halchenko
```
I am just re-releasing this code also under DataLad's copyright/license terms
> external_versions  to centralized dealings with versions of external modules and cmdline tools

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
Somewhat undertested but should be all covered ;)
Named `is_available` although original annex call is `checkpresentkey` which IMHO is a misleading name especially if no remote is provided.  `is_available` imho is cleaner.
Needed to improve archive remotes, so they could ask annex either key (archive) is available in general.  made possible after annex allowed to query without asking specific remote name
> NF+ENH: annex.is_available, get_urls, +serialize mode for @normalize_paths

- .travis.yml
- datalad/__init__.py
- datalad/crawler/nodes/tests/test_s3.py
- datalad/customremotes/tests/test_archives.py
- datalad/support/tests/test_annexrepo.py
- datalad/tests/test_tests_utils.py
Merged from #649 "so the idea is that tests should stay VERY silent unless explicit DATALAD_LOGLEVEL env variable instructs to maintain some level of reporting"
Closes #182 
Just fixed up a few of the tests left behind
> ENH: silence logs during tests with new_level

- datalad/customremotes/archives.py
- datalad/tests/test_utils.py
- datalad/utils.py
which might be available from multiple files within the same archive
> OPT: go only through unique archive keys when requesting content

- datalad/crawler/pipelines/fcptable.py
- datalad/crawler/pipelines/tests/test_fcptable.py
Temp workaround until redirect_url is complete- certain datasets have links which redirect to different url that must be crawled in order to grab tarballs rather than that original url being a tarball download itself.
Other datasets (Durham_Madden) have no links at all.
For now, will just skip those problematic datasets.
Working towards closing #655.
> BF: Skip datatsets in fcptable pipeline

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
not sure if that is how it should be, but at least it is working
anyways imho output of publish should be more about what was published, i.e. for which datasets anything (and what in particular) was pushed -- which branches, and tags... but that is a separate topic I guess
> ENH: publish --skip-failing

- datalad/distribution/add_sibling.py
- datalad/distribution/install.py
- datalad/distribution/publish.py
- datalad/distribution/uninstall.py
- datalad/interface/save.py
- datalad/interface/unlock.py
- datalad/tests/test_api.py
Moved everywhere positional args to be the first BESIDES in `save` where message is the first argument, used already in docs, and kinda makes sense but may be then we should make it really the first arg of cmdline interface?  cons -- divergence from git cmdline api
Closes #675
> RF+BF: Move positional args to be the first in __call__ signature

- datalad/crawler/pipelines/crcns.py
- datalad/crawler/pipelines/tests/test_crcns.py
- datalad/crawler/pipelines/tests/test_fcptable.py
- datalad/crawler/pipelines/tests/utils.py
- datalad/interface/add_archive_content.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/support/archives.py
- datalad/support/exceptions.py
- datalad/support/gitrepo.py
quick one -- will merge if it  doesn't break anything somehow
actually now includes also solution for #685 which was detected while looking at the crawled crcns datasets.  It changes the behaviour that tarballs extracted by default along side the tarball.  from memory -- shouldn't effect other existing crawling pipelines since tarballs usually are crawled in incoming within the root directory of the repository
Closes #685
> crcns - provide option to crawl data straight from dataset page (tarballs) instead of nersc

- datalad/__init__.py
- datalad/crawler/nodes/annex.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_add_sibling.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_publish.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_sshconnector.py
- datalad/tests/test_testrepos.py
- datalad/tests/utils_testrepos.py
Should probably close #673 and #691, #696
The best way to test that most of the commands can tolerate spaces, was to make our tests repos (submodules) have spaces in their names.  Also made them somewhat unique so later we could quickly RF possibly to add more obscurity etc
> BF+RF: tollerate spaces (and probably other interesting characters) in filenames

- datalad/__init__.py
- datalad/auto.py
- datalad/cmdline/main.py
- datalad/distribution/dataset.py
- datalad/interface/ls.py
- datalad/support/network.py
- datalad/support/sshconnector.py
- datalad/ui/__init__.py
- datalad/ui/dialog.py
added also bunch of log lines to simplify timing of the imports
atm good portion happens somewhere during initial logging setup or just finding the entry point or smth like that -- see that there is 200ms until first log line:
```
$> date --rfc-3339='ns'; time DATALAD_LOGLEVEL=1 datalad; date --rfc-3339=ns        
2016-08-11 21:27:02.994538754-04:00
2016-08-11 21:27:03,207 [Level 5] Instantiating config (__init__.py:16)
2016-08-11 21:27:03,208 [DEBUG  ] Reading files: ['/etc/datalad/datalad.cfg', '/etc/xdg/datalad/config', '/home/yoh/.config/datalad/datalad.cfg', '.datalad/config'] (configparserinc.py:144)
2016-08-11 21:27:03,208 [Level 5] Instantiating ssh manager (__init__.py:20)
2016-08-11 21:27:03,235 [Level 5] Done importing main __init__ (__init__.py:109)
2016-08-11 21:27:03,235 …
```
> OPT: startuptime - shave off at least (probably more) 50ms

- datalad/tests/utils.py
This helps poor people on Debian systems that want to use python3, but
would like to avoid messing with pip.
> RF: import compress_files locally; allows to run most tests without patool

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
- datalad/support/gitrepo.py
- datalad/utils.py
For me it is needed from usability perspective. Publishing current crawled collection is already a matter of minutes even if only 1 sub-dataset has changed.  So I have decided to suggest this approach of publishing only what has changed since last time
Not sure yet on the interplay with all the additional logic there with publishing specific files/paths.  It might just work since those would be added explicitly for pushing while analyzing paths, so might just work  ;-)
cons:
- it checks only current branch so nohow checks for those refs which were possibly set in .git/config to be pushed.   But we can't check AFAIK anyways if e.g. tags are present on the remote, so explicit pushing (`--since=`) would be needed
- relies on assumption that super-datasets got properly updated/committed if …
> ENH: publish --since . By default publish only subdatasets what has changed

- datalad/distribution/install.py
- datalad/support/network.py
This is not complete.  I was aiming to fix more of install logic (check for submodules should happen even for annex repos etc), but then also got hurt by remaining "creativism" of install uses in test_install and non-uniform handling of paths to datasets if they contain symlinks (I have TMPDIR=$HOME/.tmp  which is a symlink to /tmp, to reveal all kinds of gory failures).  So let's see first how these fixes hold, and they might resolve issues for @debanjum trying to 'install -r datasets ///' (another culprit found was using proxy -- don't use it for this call).  I will try to get a fresher look into it tomorrow as well
Should at least partially address https://github.com/datalad/datalad/issues/693
> BF: few fixes (spaces in submod names + submodules treatment) install

- datalad/distribution/dataset.py
- datalad/tests/utils_testrepos.py
I believe this creates more headache than it helps. But it seems like an
assumption that is baked in deep. This is to start figuring out
how deep.
> HELPNEEDED: Do not resolve symlinks to realpath

- datalad/distribution/create.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_dataset_config.py
- datalad/support/dsconfig.py
- datalad/support/tests/test_dsconfig.py
> RF: Make Dataset.id independent of annex.UUID and also for non-annex datasets

- .travis.yml
- datalad/crawler/nodes/annex.py
- datalad/crawler/pipeline.py
- datalad/crawler/pipelines/crcns.py
- datalad/crawler/pipelines/tests/test_balsa.py
- datalad/crawler/pipelines/tests/test_openfmri.py
- datalad/distribution/create.py
- datalad/distribution/create_test_dataset.py
- datalad/downloaders/base.py
- datalad/downloaders/http.py
- datalad/downloaders/tests/test_credentials.py
- datalad/downloaders/tests/test_http.py
- datalad/downloaders/tests/test_s3.py
- datalad/interface/add_archive_content.py
- datalad/interface/common_opts.py
- datalad/interface/ls.py
- datalad/support/annexrepo.py
- datalad/support/exceptions.py
- datalad/support/gitrepo.py
- datalad/support/keyring_.py
- datalad/support/s3.py
- datalad/support/strings.py
- datalad/tests/test_s3.py
- datalad/tests/utils.py
- added "private" argument to .commit to add our `[DATALAD] ` prefix which now used in many spots
- used `create ` command to initiate dataset
- `--no-commit` to create (if we know that we will commit anyways later)
- parametric renames (outside of tarballs and on extracted content) for crcns pipeline
- `add_to_super="auto"` to add to super only if there is a super
- fixed a test url to db.hcp url
- request non-compressed content  so our logic of checking download by size to match header works and (ideally a TODO item to enable back, but may be later)
> BF+RF+ENH: cocktail of changes while was working on crcns/smaug

- .travis.yml
- datalad/tests/test_cmd.py
must fail!  it did and then we fixed it
> BF: added configuration to travis to test under TMPDIR with spaces, but not a symlink

- datalad/interface/common_opts.py
- datalad/interface/save.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
Check tests inside -- food for thought re subdataset treatment!
> NF: handle_dirty_dataset()

- .travis.yml
I find coveralls more annoying (all the announcements, reporting decreased coverage whenever it is actually improved, etc) and prefer codecov (browser extensions, more elaborate summary etc).
> RF: deprecate use of coveralls in favor of codecov

- datalad/distribution/add_sibling.py
- datalad/distribution/create_publication_target_sshwebserver.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/support/sshconnector.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
- datalad/utils.py
it is never enough of tests, but new ones revealing bugs are nice ;-)
> BF+ENH: fixes on the way to get --existing=reconfigure functioning as it should

- datalad/consts.py
- datalad/distribution/add_sibling.py
- datalad/distribution/create_publication_target_sshwebserver.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/interface/crawl.py
- datalad/interface/ls.py
- datalad/interface/tests/test_crawl.py
- datalad/tests/test_utils.py
- datalad/utils.py
- tools/testing/conf/apache-ssh-supervisor.conf
- tools/testing/conf/etc/apt/apt.conf.d/99apt-cacher
- tools/testing/start_website_in_docker
- tools/testing/start_website_in_docker-Dockerfile.in
`tools/testing/start_website_in_docker` script could be run to build and start a docker container which would expose http on port 8081 to localhost and ssh to 2221. so it would be easy to play/test with webfrontend and publishing more safely.
as a part of it, on elderly systems it would symlink git-annex-standalone's git into usr/local/bin/ since otherwise we can't test `datalad ls` since we want freshish git.
along the way fixed up 
- creation of hooks directory (somehow was not created somehow although repo was initialized)
- permissions to index.html
- depth first running of hooks (so all the meta information properly bubbles up upon 'reconfigure' action)
quick review/merge would be appreciated
> ENH: start_website_in_docker + fixes along the way

- datalad/distribution/install.py
if it was indeed absent and we don't care there
without this, any `install URL` invocation complaints that source was not given
> ENH: install -- do not complain about source being absent 

- datalad/interface/ls.py
- datalad/interface/tests/test_ls.py
was working to address #837 that `ls` was listing all versions for s3:// urls.  while at it moved '--all' into '--long' for datasets ls, since in --all, inline with ls of s3:// we will later report on all versions (joey already have done 'annex info' for specified treeish)
>  ENH+BF: ls --long option, otherwise list shorter listing/stats + fixed not lsing all versions without -a

- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Reason: Git disabled some optimizations (hardlinking) for local clones
when it gets a URL. Maybe we want to convert such URL, or force `clone
--local`
> TST: Show that we are needlessly being inefficient with local file URLs

- datalad/consts.py
- datalad/distribution/dataset.py
- datalad/downloaders/tests/test_http.py
- datalad/interface/tests/test_ls.py
- datalad/metadata/parsers/bids.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
- datalad/support/exceptions.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
- datalad/ui/__init__.py
- datalad/ui/dialog.py
Couldn't resist
edit1: does work correctly now:
```
$> rm -rf datasets.datalad.org; datalad search -R BIDS
No DataLad dataset found at current location
Would you like to install stock DataLad meta-dataset? (choices: yes, no): 
ERROR: '' is not among choices: ['yes', 'no']. Repeat your answer
No DataLad dataset found at current location
Would you like to install stock DataLad meta-dataset? (choices: yes, no): yes
2016-09-20 12:16:18,024 [INFO   ] Installing <Dataset path=/tmp/datasets.datalad.org> from http://datasets.datalad.org/ (install.py:372)
Dataset installed under /tmp/datasets.datalad.org.  Perform further operations using that dataset
openfmri/ds000001:
dc:conformsTo: http://docs.datalad.org/metadata.html#v0-1, http://bids.neuroimaging.io/bids_spec1.0.0.pdf
openfmri/ds000005: …
```
> ENH+NF: if no dataset found during search -- ask to install our super-dataset under ~/datalad and/or search there

- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_target_ssh.py
Make uploading webinterface optional. Allows user to alternate name of index.html if it may conflict with pre-existing index.html in dataset.
Refer issue #825 for more details
> Enh webinterface upload optional

- datalad/support/annexrepo.py
- datalad/support/exceptions.py
- datalad/support/tests/test_annexrepo.py
- datalad/utils.py
As discovered/reported in #897 we might be silently ignoring important failures of annex because it being outdated.  So we better complain out loud (ie crash) if we have outdated annex.
But this is also a precursor somewhat for providing progress output from annex get.
Since imho we better fail as early as necessary in case of oudated git-annex, I will merge this one if tests pass
> ENH: fail AnnexRepo if outdated annex (demand at least 20160808)

- datalad/cmdline/main.py
- datalad/export/__init__.py
- datalad/export/tarball.py
- datalad/export/tests/__init__.py
- datalad/export/tests/test_tarball.py
- datalad/interface/__init__.py
- datalad/interface/base.py
- datalad/tests/test_cmdline_main.py
- docs/source/cmdline.rst
To try it on something real, you can clone this: https://github.com/mih/BIDS2ISATab
Link the script into `datalad/export` under some name. Example:
````
% ls -l datalad/export/sd_bidsisatab.py
lrwxrwxrwx 1 mih mih 40 Sep 23 08:19 datalad/export/sd_bidsisatab.py -> ../../../BIDS2ISATab/bids2isatab/main.py
````
TODO:
> Draft of a plugin based `export` command (takes unknown options)

- datalad/export/tarball.py
- datalad/export/tests/test_tarball.py
- datalad/interface/ls.py
- datalad/support/gitrepo.py
- BF for var name
- use output filename as prefix for lead dir within tarball
- "fix" mtime issue by mocking time.time to match time of the last commit
- RF -- new function within GitRepo `get_committed_date`
> BF: Reproducible tarballs + few other BF/ENH

- .travis.yml
- CONTRIBUTING.md
- datalad/api.py
- datalad/cmdline/main.py
- datalad/metadata/tests/test_search.py
- datalad/tests/test_utils.py
- datalad/utils.py
If someone would work interactively with DataLad (E.g. in IPython shell), looking at all the data structures produced, or worse -- yielded, by DataLad might be to say the least inconvenient.  So it might be nice to provide a quick way to call Python API so it uses cmdline renderer. So, why not just to make such functios with '_' suffix.  So compare (and this one is actually a gentle example since returned structure manages to get formatted sensibly)
```ipython
In [2]: api.search('bids', report_matched=True)
Out[2]: <generator object __call__ at 0x7fc418404c30>
*In [3]: list(api.search('bids', report_matched=True))
Out[3]: 
[(u'openfmri/ds000001',
{u'dc:conformsTo': [u'http://docs.datalad.org/metadata.html#v0-1',
u'http://bids.neuroimaging.io/bids_spec1.0.0.pdf']}),
(u'openfmri/ds000005', …
```
> ENH: for each command with cmdline renderer have a "sibling_" in Python API

- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
otherwise BF -- do not set it manually to the path (was introduced recently) and do not double 'annex init' it.  Not sure now why (and if) we needed it there -- but tests seems to pass, so I assume that everything is kosher even with removal of the 2nd possible annex init
> BF+ENH: add-sibling - make description match target_url if provided

- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_base.py
This is implemented, but I believe they should also be ignore by `get_metadata()` -- that is not yet done.
> RF: Ignore dataset without ID on aggregate

- datalad/distribution/add.py
- datalad/distribution/create.py
- datalad/distribution/dataset.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_get.py
- datalad/interface/save.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
- datalad/tests/test_utils.py
- datalad/utils.py
Closes #964 -- use -s option to specify fields/properties to search)
Closes #912 -- use -d^ to search from the very top of current datasets hierarchy, -d/// to search central one
There were some refactoring along the way (`assert_unicode`, moved `_with_sep` into utils, etc). Overall tried to keep amount of possible conflicts to minimum with WiP work... but no guarantees ;)
Try search now with those options -- it is quite neat IMHO
couldn't resist so now we are spitting out suggestions in case none of the properties was found:
```
(git)hopa:~datalad/datalad[enh-search-fields]git
$> datalad search -d/// -slocati a
2016-09-30 21:01:16,349 [WARNING] Found no properties which matched one of the one you specified (locati).  May be you meant one among: homepage, citation, contributors, license, …
```
> ENH various enhancements to search and around it

- .travis.yml
Apparently those scenarios did not play at all, which lead to failures
on OSX buildbot within https://github.com/datalad/datalad/pull/959#issuecomment-250915262
without Travis failing at all
> BF: do not place bash regex pattern within "" for =~

- datalad/support/external_versions.py
- datalad/support/tests/test_external_versions.py
Closes #897 
picked up @mih commit from the #959 -- now comparison would work as prescribed:
```shell
hopa(precise-amd64):~/datalad/labs/haxby/raiders
$> datalad get sub011
2016-10-14 23:03:59,317 [ERROR  ] git-annex of version >= 6.20160808 is missing. Visit http://git-annex.branchable.com/install/. You have version 5.20140517.4 [annexrepo.py:_check_git_annex_version:259] (OutdatedExternalDependency) 
```
> BF: Robustify annex version detection

- .travis.yml
- CONTRIBUTING.md
- requirements-devel.txt
- requirements.txt
- setup.py
Regular requirements.txt will now attempt to install as it should without -e (but that would entail copying entire working directory).  So if you are developing -- using requirements-devel.txt which would also make sure that you have ALL needed for development requirements (including sphinx, useful nose plugins etc)
> RF+ENH: dedicated [devel] + requirements-devel.txt mode of installation 

- datalad/distribution/add_sibling.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
Fixes issues with shared SSH connections. Led to asking for credentials several times.
- Cloning and  `datalad add-sibling` didn't correctly use this mechanic
- directory used for SSH control masters now depends on config item `datalad.locations.cache`
- Deal with existing but not running control masters
- let annex know about setting a remote's url
- time out for control master: 15 minutes
Closes #826 
Closes #865 
Closes #1032 
Note: More on the topic of publishing and siblings to come in another PR. Also more testing.
> BF: SSH shared connections issues

- datalad/metadata/__init__.py
- datalad/metadata/parsers/__init__.py
- datalad/metadata/parsers/datalad_rfc822.py
- datalad/metadata/parsers/tests/test_bids.py
- datalad/metadata/parsers/tests/test_frictionless_datapackage.py
- datalad/metadata/parsers/tests/test_rfc822.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_base.py
- docs/source/metadata.rst
Which invents as little as possible. Objectives:
1. Compact
2. Suitable for hand-editing (we have two JSON-based ones already)
3. Flexible enough to be able to capture pretty much anything I could think of
Choosing Debian's RFC822 felt natural. Pretty much all these files are composed by hand (that's proof enough).
The idea is to merge the various ideas from Debian's metadata files into a single spec file (control, copyright, ...). If necessary, we could have multiple files of course, but it doesn't look like we need it (yet).
At this point, the implementation represents the minimal technical infrastructure to support this format on a demo level, and to get the discussion going.
> NF: RFC822-based meta data format targeting manual meta data entry scenarios

- datalad/distribution/add.py
- datalad/distribution/tests/test_add.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
as @agramfort pointed out -- ATM `datalad add BUNCHOFFILES` just stays silent for a while and then spits out its long list.  This PR adds a progress bar (based on file sizes, but also with total count) and exposes `--jobs` option, allowing to make checksumming faster
Resulted also in some refactorings etc ;)  Let's see now if anything got broken
> ENH+RF:  datalad add  progress indication + passing --jobs  into annex

- datalad/__main__.py
- datalad/auto.py
- datalad/tests/test_auto.py
seems to work ;)
```shell
hopa:~/proj/experiments/movie-localizers/data/studyforrest/studyforrest-data-templatetransforms
$> python -m datalad ./apply_warp.py sub-06/bold3Tp2 
[INFO   ] Activating DataLad's AutoMagicIO 
[INFO   ] Running code of ./apply_warp.py 
processing  sub-06/bold3Tp2
Failed to get annex.uuid configuration of repository origin
[INFO   ] File sub-06/bold3Tp2/brain.nii.gz has no content -- retrieving 
Failed to get annex.uuid configuration of repository origin                                                   
Failed to get annex.uuid configuration of repository origin
Failed to get annex.uuid configuration of repository origin
[INFO   ] File sub-06/bold3Tp2/in_grpbold3Tp2/subj2tmpl_warp.nii.gz has no content -- retrieving 
Failed to get annex.uuid configuration of …
```
> BF: import mock before proxying everything, proxy "exists" and test on nibabel

- datalad/crawler/pipelines/tests/test_openfmri.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/metadata/__init__.py
- datalad/metadata/aggregate.py
- datalad/metadata/parsers/aggregate.py
- datalad/metadata/parsers/tests/test_aggregate.py
- datalad/metadata/parsers/tests/test_bids.py
- datalad/metadata/parsers/tests/test_frictionless_datapackage.py
- datalad/metadata/parsers/tests/test_rfc822.py
- datalad/metadata/tests/test_base.py
- datalad/tests/utils.py
Currently `get_metadata()` is also doing half of `aggregate_metadata()`.
The plan is to have the `get` part to work the exact same way, whether
or not (some) subdatasets are installed. It will look into the given
dataset only, and not traverse *into* possible installed subdatasets.
All that is known to it, is locally aggregated meta data.
TODO:
implementation
aggregated data and go straight into a subdataset
can quickly and reliably perform a (partial) update of subdataset
meta data
This will change the way and location where decisions are made. It will
be irrelevant for `get_metadata()` whether some component actually exists.
This investigation, and the decision on how to deal with it will be left to
the aggregation stage. This will make it easier and more comprehensible to
switch to an …
> RF meta data handling to disentangle the pieces

- datalad/metadata/tests/test_base.py
This is the last remaining relevant bit from #1010 that didn't make it into master yet.
> TST: Make sure non-dataset submodules do not impact the meta data (gh-949)

- datalad/log.py
Otherwise it dumps all kinds of debugging info into "captured logging"
of nose making it difficult to work with tests using git module
now it looks like
```shell
$> nosetests -s -v datalad/distribution/tests/test_update.py:test_update_simple
FAIL
FAIL: datalad.distribution.tests.test_update.test_update_simple
File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 706, in newfunc
t(*(arg + (uri,)), **kw)
File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
return t(*(arg + …
```
> ENH: silence git logger if we are the first to "access" it

- datalad/downloaders/s3.py
Closes #1083 
I don't think we would be able to do anything about the error msg reported in 1083 and it doesn't appear on newer systems
> ENH: report progress for S3 downloads

- datalad/distribution/add.py
- datalad/distribution/tests/test_add.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- (**change in behavior**) `datalad add` was useless in pure git repositories, unless explicit `--to-git` was added, which to me made little sense. So I have changed it so it does `git add` in pure git repos, instead of returning failure
- GitRepo.add didn't return anything, at least with recent git 2.9.3 unless --verbose option is added
- parsing of the add output was not working correctly for obscure filenames with ' in them
- `datalad add` was returning (I think) incorrect results in case of paths across multiple datasets were provided, since the last lucky `ds` value was used. Since output was not really tested much -- that bug was lingering happily around.  I have added some testing
P.S. now I just need to remember what the heck I was doing that I got to this issue ;)  ah, right -- I …
> BF+RF+ENH(TST) add (GitRepo and Dataset)

- datalad/distribution/get.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/uninstall.py
- datalad/interface/tests/test_unlock.py
- datalad/interface/tests/test_utils.py
- datalad/interface/unlock.py
- datalad/interface/utils.py
For example `get` and `unlock` are highly similar in terms of what they should be doing to figure out which items to `get` or to `unlock`. Yet they use hardly the same lines of code.
Will try to identify and RF some of the common bits into more generic helpers.
Feel free to merge any time, despite possibly open TODOs. I do not intent to work on this for two months. Only low hanging fruit.
> RF: Higher-level abstraction helper for command that do thing to dataset content items

- datalad/crawler/pipelines/tests/test_fcptable.py
- datalad/ui/progressbars.py
Discovered during demos that global pbar did not behave properly.  There seems to be
a number of issues within older tqdm and fresh one addresses them.  So we just need a
fresh tqdm, but I do not think we need to hard demand it until it is present everywhere
I have submitted request to have pkg updated in debian, after we get it there and in neurodebian -- we will boost versioned dependency
Paired with a fix (workaround) for a problem resolving domains with underscores in recent requests  (https://github.com/kennethreitz/requests/issues/3683#issuecomment-261947670), fix for which is WiP
> ENH: better use recentish tqdm and then no need for custom options

- datalad/metadata/parsers/bids.py
- datalad/metadata/parsers/tests/test_bids.py
as the bible says!  well -- somewhat.
Here I read README only if original Description is not provided.  BIDS somewhat says "in addition".
So I wondered if some alternative solution should be used, e.g.
1. append content README to description even if description was provided (there are a few openfmri datasets which have both, README and description;  more datasets have no descriptions but do have README)
2. add a new field (e.g. `description-long`) to our schema to contain content of README.
What do you think @mih ?
> ENH: BIDS -- read README as the description if none provided in dataset_description.json

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_create_github.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/tests/test_update.py
- datalad/distribution/uninstall.py
- datalad/interface/__init__.py
- datalad/interface/save.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
- datalad/support/tests/test_gitrepo.py
- datalad/tests/test_utils.py
- datalad/tests/utils_testrepos.py
- datalad/utils.py
- docs/source/cmdline.rst
This PR replaces #1118 -- while built on top of it, there have been substantial changes in concept and implementation. It is unknown whether it fixes any of the bugs listed in #1118 unless there are dedicated unittests for them (but there is no clear association of tests with issues).
I want to point out the following shortcomings:
- there is no check if a subdatasets only has a local URL (e.g. ./anything), which implies that uninstall actually equals removal with no way back (no change from status quo)
- there is no check that the relevant branched are pushed to a remote before an uninstall (no change from status quo)
- there is an ugly error when annex refuses to drop content due to insufficient copies (no change from status quo)
I do not plan to work on any of those issues as of now.
> Commands: drop, uninstall, remove

- datalad/metadata/parsers/bids.py
- datalad/metadata/parsers/tests/test_bids.py
```shell
$> datalad --version                              
datalad 0.4.1.dev79
hopa:/tmp/ds000203
$> datalad aggregate-metadata --guess-native-type 
[INFO   ] aggregating meta data for <Dataset path=/tmp/ds000203> 
[ERROR  ] 'utf8' codec can't decode byte 0xf1 in position 253: invalid continuation byte [utf_8.py:decode:16] (UnicodeDecodeError) 
```
happens on saving aggregated json:
```shell
hopa:/tmp/ds000203
$> datalad --dbg aggregate-metadata --guess-native-type 
[INFO   ] aggregating meta data for <Dataset path=/tmp/ds000203> 
File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 11, in <module>
load_entry_point('datalad', 'console_scripts', 'datalad')()
File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 261, in main …
```
> Robustify handling of README while aggregating BIDS

- datalad/distribution/create.py
- datalad/distribution/tests/test_add.py
again not sure how it has happened, and which branch I was using at that moment -- master or of currently WiP+BK #1011 but result is stunning:
``` shell
$> git log -p .datalad
commit 3c8c614cf24a9d02534ddcdb8ce879e3ff501723
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Fri Oct 14 16:03:44 2016 -0400
[DATALAD] new dataset
diff --git a/.datalad/config b/.datalad/config
new file mode 100644
index 0000000..c9dce61
--- /dev/null
+++ b/.datalad/config
@@ -0,0 +1 @@
+/annex/objects/MD5E-s63--6c651a912b39c90ba19405e501bd951c
```
detected only upon
``` shell
(git)smaug:/mnt/datasets/datalad/crawl/dicoms[master]git
$> datalad aggregate-metadata --guess-native-type -r              
2016-10-15 09:26:26,923 [INFO   ] aggregating meta data for <Dataset …
```
> create --annex-version 6 (or subsequent lock) places .datalad/config under annex, not git

- .travis.yml
- datalad/interface/common_cfg.py
Addressing #1143 as agreed on in hangout.
Should add builds with V6 as default.
When we started having a look at these, should change to V6 for all builds instead of dedicated ones.
> ENH: Annex V6 default build added to Travis

- datalad/crawler/nodes/annex.py
- datalad/crawler/pipelines/simple_s3.py
- datalad/crawler/pipelines/tests/test_simple_s3.py
- datalad/tests/test_utils.py
- datalad/utils.py
@datalad/developers -- it feels like I need to adopt arguments treatment for crawler pipeline functions similar to as it is happening in cmdline -- to assure correct data types etc... I wonder how easy it would be ;)
> ENH: allow to drop all content after crawling (used in simple_s3), and assure_bool

- datalad/downloaders/s3.py
- datalad/downloaders/tests/test_s3.py
otherwise uses another vcr tape leading to failed test
since we aren't testing those ATM on travis - I will just merge it if it doesn't break anything else
> BF: do not reuse s3 bucket session in the test

- datalad/distribution/tests/test_add.py
- datalad/support/annexrepo.py
if annex v6 is used, then `git add` will pretty much do `git annex add`, so we need say explicitly to not commit to annex for that `git add` call
> add --to-git pass explicitly -o annex.largefiles=

- datalad/distribution/create_test_dataset.py
- datalad/distribution/tests/test_create_test_dataset.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
```shell
$> datalad create-test-dataset --spec 1/1 testds2
[INFO   ] Generating repo of class <class 'datalad.support.gitrepo.GitRepo'> under /tmp/testds2 
[INFO   ] Generating repo of class <class 'datalad.support.gitrepo.GitRepo'> under /tmp/testds2/d0/d1/d2/r0 
[INFO   ] <Dataset path=/tmp/testds2/d0/d1/d2/r0> was already installed from . Use `update` to obtain latest updates, or `get` or `install` with a path, not URL, to (re)fetch data and / or subdatasets 
[INFO   ] Generating repo of class <class 'datalad.support.annexrepo.AnnexRepo'> under /tmp/testds2/d0/d1/d2/r0/d0/d1/d2/r0 
[INFO   ] <Dataset path=/tmp/testds2/d0/d1/d2/r0/d0/d1/d2/r0> was already installed from . Use `update` to obtain latest updates, or `get` or `install` with a path, not URL, to (re)fetch data and / or …
```
> BF: create-test-dataset created a "dirty" dataset because of "installing" some bogus submodules

- datalad/__init__.py
- datalad/cmd.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/support/external_versions.py
- datalad/support/tests/test_external_versions.py
- datalad/tests/test_cmd.py
- datalad/tests/utils.py
So we could avoid weird bugs in elderly gits and gain more consistency
WiP since I am still thinking on how to deal with (testing) remote git, so create_sibling could make use of bundled git when testing against localhost... we could try to pass the environment variables via SendEnv option of ssh  or other ways, but I wonder if we should really...
edit 2:  I am wondering if we should then do similar detection on the remote end while establishing ssh connection(s).  That could slow things down a bit though then :-/ and pure -o SendEnv wouldn't be an acceptable  solution since requires sshd configuration to allow passing those variables (by default only locale settings are allowed to be passed).  So the only way I found to make it work is by prepending each invocation with explicit adjusted …
> RF: use bundled git (or just the git alongside with git-annex)

- datalad/distribution/update.py
Update to bring `update` more in line with the more recently refurbished commands.
> Homogenization of `update` API

- datalad/distribution/tests/test_update.py
- datalad/distribution/update.py
This needs to go in master ASAP. Tests should pass, will merge myself ASAP -- unless you beat me to it.
> BF: Make `update` usable from cmdline again (arg name mismatch)

- .travis.yml
- datalad/support/annexrepo.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
- BF/ENH: Don't close SSH connections, that were not opened by this instance of SSHManager
- Workaround: Unclear circumstances led to AnnexRepo.__del__ accessing NoneType object. Just ignore and log it.
Closes #1127
> Fixing SSH shared connection issue

- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/uninstall.py
This can easily happen when calling `drop` on a hierarchy of datasets.
Maybe this is not even worth a message (it is not an error for sure),
as git annex will silently skip files that are in Git too.
Decided to go for an INFO message.
> RF: No error when trying to drop files in plain Git repo

- datalad/distribution/create_sibling.py
- datalad/distribution/create_sibling_github.py
- datalad/distribution/tests/test_target_ssh.py
> RF: Uniform and optional --sibling-name for `create-sibling*`

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
This refurbishes `publish` in the following ways:
> RF: `publish`

- datalad/distribution/add_sibling.py
- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_target_ssh.py
- datalad/interface/common_opts.py
So far, mostly sorting checks to fail as early (and as cheap) as possible, plus some RF to use more common code. And now also various minor fixes and simplifications. Brought back previously disabled tests.
If you are happy about what you see feel free to click the merge button.
> General `create-sibling` RF and few enhancements

- datalad/interface/add_archive_content.py
- datalad/interface/tests/test_add_archive_content.py
> BF: remove all extracted files at once for delete_after to not interfer with batched processes

- datalad/__init__.py
While trying to debug remaining failures in PR #1237 , discovered we completely missed to use bundled git with GitPython.
Probably fixes these failures, since they are occuring while calling `git push` via GitPython, which then ignores `GIT_SSH_COMMAND` on Travis (that env. variable was introduced only in git 2.3), therefore wasn't calling `datalad sshrun`, but plain `ssh`, which in return led to not using bundled git on the remote end.
> BF: Use (bundled) git with GitPython, too.

- .travis.yml
- datalad/distribution/dataset.py
- datalad/distribution/uninstall.py
as NFS testing revealed -- there is an issue with some outstanding git cat-file batched processes held up by GitRepo's which belong to Datasets.  Uninstalling implies that those GitRepo's should disappear, thus as a quick solution I have introduced `Dataset.close` which for now was used only in `uninstall`.
> ENH+BF: NFS testing on travis + Dataset.close()

- datalad/distribution/publish.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
Solves the `annex copy` issue, we discussed during last hangout, when `git annex` doesn't use the provided pushurl to talk to a remote.
Implementing joey's solution.
See:
http://git-annex.branchable.com/bugs/annex_ignores_pushurl_and_uses_only_url_upon___34__copy_--to__34__
> BF/ENH: Make use of remote.<name>.annexurl

- datalad/tests/test_auto.py
we had nd80 and nd15_04 bots failing, see e.g.
http://smaug.datalad.org:8020/builders/datalad-pr-docker-dl-nd15_04/builds/2063/steps/nosetests/logs/stdio
which seems to happen under heavy loads but otherwise didn't reproduce locally etc
so to see possibly what is going on switched to use more informative helper
> ENH: use assert_array_equal to compare to possibly help troubleshooting random failures

- datalad/distribution/add.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/tests/test_update.py
- datalad/distribution/uninstall.py
- datalad/distribution/update.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
`update` is now practically a frontend for `annex sync`.
Please comment @bpoldrack @yarikoptic 
From my PoV this step is complete. There is more TODO, (#1199) but there is no need to wait for it .
> RF update (focus: single dataset operations)

- datalad/cmdline/common_args.py
- datalad/cmdline/helpers.py
- datalad/cmdline/main.py
otherwise was passing -C into condor while already staying in that directory
actually I guess I could have moved handling of -C down under handling of the pbs_runner but may be there would be advantage of respecting -C before scheduling in the runner... so let it be as now redone
> RF+BF: cmdline - remove provided value for -C before passing into condor runner

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
Instead temporarily amend the push config to push the current branch, or rather the underlying branch in case of managed branches.
We may want to have this behavior to be conditioned on an explicit switch, or to only be active when there is no push config at all. Which would help with the issue that it presently cannot handle wildcard expressions for push config.
ATM it makes sense to me to do it like this.
This is work towards a resolution of gh-1275
> RF: Do not place default push config on publish anymore

- datalad/distribution/publish.py
should fix failing test
see discussions after merge in https://github.com/datalad/datalad/pull/1308
includes an "easter egg" fix ;)
> BF/RF: instead of using -c remote..push, pass refspecs into push invocation

- datalad/consts.py
- datalad/crawler/nodes/annex.py
- datalad/crawler/nodes/tests/test_annex.py
- datalad/customremotes/base.py
- datalad/interface/add_archive_content.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/tests/utils_testrepos.py
This should be legit (confirmed with joey) since they just provide a service
to fetch stuff from e.g. archives or some data sources (like web remote).
This will be handy in cases of merging two different repositories, which had
those remotes initiated independently.  Currently it would generate multiple
special remotes then different uuids and the same name
> ENH+RF: generate our customremotes (datalad, datalad-archives) with the same UUID

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
- datalad/config.py
- datalad/tests/test_config.py
Addresses #958 
At present we have no simple way to test the few lines in `main.py`.
> General config overrides mechanism and `-c` option for the cmdline

- datalad/auto.py
since git could have messed with str encoding handlers
should resolve nd90 weird error (although would also skip some tests I guess)
> BF(workaround): safeguard import of h5py in auto 

- datalad/cmdline/tests/test_main.py
We are formatting the tested help output to the terminal size if we know it, which is the case in PY3 only.
(See datalad/cmdline/main.py:182)
Nevertheless we tested against a fixed width of 80. Therefore the test would fail on python 3 if ran in a terminal wider than 80 characters.
Changed the test to fit the actual implementation.
> BF: Don't overcomplain long lines in terminal output

- .travis.yml
- datalad/__init__.py
- datalad/downloaders/base.py
- datalad/interface/common_cfg.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/ui/__init__.py
- datalad/ui/dialog.py
- datalad/ui/progressbars.py
- datalad/ui/tests/test_dialog.py
There is still seems to be some spurious new lines, but otherwise output
seems to behave better
Example:
before:
```
$> datalad install -g -J3 sub001/anatomy
[INFO   ] Getting 1 items of dataset <Dataset path=/tmp/raiders> ...
[INFO   ] Actually getting 10 files
1 installed item is available at
<Dataset path=/tmp/raiders>
```
after:
```
$> datalad install -g -J3 sub001/anatomy
[INFO   ] Getting 1 items of dataset <Dataset path=/tmp/raiders> ...
[INFO   ] Actually getting 10 files
1 installed item is available at
<Dataset path=/tmp/raiders>
```
TODO
> ENH: tqdm - use leave=True instead of explicit clean call to avoid spurious new lines

- .travis.yml
- datalad/cmd.py
- datalad/support/tests/test_annexrepo.py
- datalad/tests/test__main__.py
I test to run nosetests without -s nowadays, and it seems (this PR tests run will show ;-) ) to work but few tests required workaround.
> BF: use swallow_output in 2 failing spots whenever nosetests ran without -s

- datalad/interface/common_cfg.py
- datalad/log.py
- datalad/tests/test_log.py
- datalad/utils.py
thought to do it for a while but never got to it... now need to troubleshoot that ssh connector business and do not want to scroll or grep through tons of logs to find relevant lines.. so it will be something like
```DATALAD_LOG_LEVEL=2 DATALAD_LOG_NAMESRE=.*ssh do_whatever ```
and only log lines from modules having anything to do with ssh should get printed ;)
> ENH+RF: _LOG_NAME, _LOG_NAMES, _LOG_NAMESRE to control what log entries to print

- datalad/distribution/tests/test_install.py
- datalad/distribution/utils.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Closes #937 
but now I wonder if we should place more safe-guards, e.g. to not perform it if previous position of the branch is not available within any remote, thus signalling that it probably has local changes, thus we shouldn't just 'loose' them.
> ENH: when installing/getting a submodule, make checkout branch to point to that commit

- datalad/distribution/install.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/tests/test_update.py
- datalad/export/tests/test_tarball.py
- datalad/interface/save.py
- datalad/interface/tests/test_save.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
- datalad/metadata/tests/test_base.py
- datalad/support/exceptions.py
- docs/examples/3rdparty_analysis_workflow.sh
BF: demo script which was apparently broken for a while   see #1374 
- fail if `save -a` is used since its behavior has changed to fulfill the promise of the least surprise
- get proper deprecation error with description instead of just behaving differently now
```
$> datalad save -a                                                                                                                
[ERROR  ] RF: all_changes option passed to the save is deprecated since version 0.5.0. Use all_updated  option where fits and/or datalad add instead. [save.py:__call__:142] (DeprecatedError) 
```
- I know that `save -a` is somewhat consistent with `git commit -a` but
-  we might want to revive `-a` operation at some point, then it would be all kosher without confusion and tears
- it is `git add -u` …
> RF+BF: save -- revive all_changes to die properly, and -a -> -u, all_changes -> all_updated

- datalad/tests/utils_testdatasets.py
actually I thought it would go down from 70 to newly measured 40 sec but apparently it is just around 10sec... still notable improvement especially since it is just a smoke test
> OPT: shave off ~10sec from test_make_studyforrest_mockup runtime by running 2 loops instead of 3

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
When I have an existing annex there seems to be no way to get its description changed.
````
>>> r=AnnexRepo('.')
>>> r.get_description()
'some'
>>> r=AnnexRepo('.', init=True, description='someother')
>>> r.get_description()
'some'
````
Calling `git annex init someother` in the cmdline has the desired effect, of course.
> Cannot change annex description

- datalad/api.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/distribution/dataset.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/utils.py
- datalad/interface/__init__.py
- datalad/interface/base.py
- datalad/interface/common_opts.py
- datalad/interface/tests/test_utils.py
- datalad/metadata/search.py
- datalad/support/gitrepo.py
- datalad/tests/utils_testdatasets.py
- docs/source/cmdline.rst
Check `datalad/distribution/tests/test_clone.py` for converted install tests that represent the scope of `clone`. Major change is dramatically reduced flexibility wrt input arguments (see #1396). This leads to about ~10% of speed up for our bread-and-butter call, i.e. install one dataset (recursive or not) from one source.
It looks like we could switch to `clone` for pretty much all use in the tests, except for the test of `install`. Even if `install` represents only a fraction of the actual runtime, we are calling it a lot, so it should make things a bit faster.
Here is a demo:
````
In [1]: %run clone_speed_demo.py
In [2]: %timeit test_clone_speed()
1 loop, best of 3: 3.63 s per loop
In [3]: %timeit test_install_speed()
1 loop, best of 3: 4.02 s per loop
In [4]: %timeit …
```
> NF: `clone` a faster `install` for most cases

- .travis.yml
we need to make testing of PRs usable again quickly, but should still strive to lighten up testing so master could pass tests again
> BF(workaround): run only subset of tests under NFS while testing PR - full in master

- datalad/distribution/add.py
- datalad/distribution/dataset.py
- datalad/interface/utils.py
There seems to be even more points to optimize but decided first to check this one
@mih -- feel free to discard (i.e. not merge) and just adjust code accordingly in the ultimate return values RF to avoid conflicts
Possibly closes #1388 
so here is timing before
```shell
$> time bash -c 's=NEW6; datalad create $s; datalad add -d . $s'
[INFO   ] Creating a new annex repo at /mnt/btrfs/datasets-quicksub/datalad/crawl/openfmri/NEW6 
Created dataset at /mnt/btrfs/datasets-quicksub/datalad/crawl/openfmri/NEW6.                                                           
Added <Dataset path=/mnt/btrfs/datasets-quicksub/datalad/crawl/openfmri/NEW6>                                                          
bash -c 's=NEW6; datalad create $s; datalad add -d . $s'  7.18s user 3.66s system 78% cpu …
```
> OPT: delay full tree traversal in sort_paths_into_subdatasets for the use case of adding a new subds

- .travis.yml
- datalad/cmdline/tests/test_formatters.py
- datalad/distribution/install.py
- docs/examples/nipype_workshop_dataset.sh
- docs/source/metadata.rst
- docs/source/usecases/index.rst
- formatters.py
- tools/testing/run_doc_examples
Just thought to formalize my notes from creating http://datasets.datalad.org/?dir=/workshops/nipype-2017/ds000114 
Also adjusted script running those tests... I am really not sure about the purpose of shunit2 magic/stubs in there, may be @mih would explain.
- Ideally should get #1428 fixed soonish and remove custom stub
- perspective 'load' #1424 command could be used to checkout into a detached branch (although I should have just based on actual version checkout... heh -- next time)
- publish still behaves flaky -- it seems that after all this it manages not to push most recent update to top dataset and requires additional 'datalad publish'... although worked just fine until I started to correct for that first issue
> DOC+ENH: write up on construction of a 'derived' dataset and adding it to larger distribution

- datalad/cmd.py
- datalad/dochelpers.py
- datalad/support/annexrepo.py
- datalad/ui/progressbars.py
hopefully with future version we could avoid it
Also
-  now it wraps update of tqdm in try/except just to avoid sporadic crash due to oh so important tqdm raising an exception ;)
- fixed up some PY3 issues with decoding/encoding json output from annex on python3.5 (as discovered while testing nipype workshop docker image with 0.5.0 under python3). That lead to absent actual progress in the progressbars under python3
- fixed use of re.split so it doesn't issue a warning (Closes #1433)
Closes #1222
> BF: skip first progress update from annex since might be "too stale"

- datalad/api.py
- datalad/cmdline/main.py
- datalad/distribution/add.py
- datalad/distribution/add_sibling.py
- datalad/distribution/create_sibling_github.py
- datalad/distribution/dataset.py
- datalad/distribution/get.py
- datalad/distribution/remove.py
- datalad/distribution/rewrite_urls.py
- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_subdataset.py
- datalad/distribution/uninstall.py
- datalad/distribution/utils.py
- datalad/dochelpers.py
- datalad/interface/__init__.py
- datalad/interface/base.py
- datalad/interface/crawl.py
- datalad/interface/ls.py
- datalad/interface/results.py
- datalad/interface/tests/test_crawl.py
- datalad/interface/utils.py
- datalad/metadata/aggregate.py
- datalad/support/annexrepo.py
- docs/examples/3rdparty_analysis_workflow.sh
- docs/source/cmdline.rst
- tools/testing/run_doc_examples
In response to #1411
This implementation is a lot faster, as it completely avoids instantiation of repositories, but wraps `git submodule` instead. Moreover, it exposes more information in a more directly accessible way.
It uses the new command API, so all transformation and filter mechanisms can be applied based on arbitrary subdataset properties.
The old `Dataset.get_subdatasets()` is left in place, as it is still used a lot in the tests. All occurrences in the actual code base are RF'ed. Use in test triggers a warning identifying the caller to
streamline further RF.
The new `subdatasets` command as advertised as a plumbing command in the docs.
Tests in `test_subdatasets.py` have been extended to near 100% coverage, only one safeguard line is missing.
TODO:
> RF+NF: Dataset.get_subdatasets() -> standalone `subdatasets`

- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/utils.py
- datalad/support/network.py
- datalad/support/tests/test_network.py
Should address #1459 
Also with this I am confessing that I have "downgraded" the version of git-annex-standalone as we ship from NeuroDebian (now it is at a revision right before it broke for us).  So travis should get all happy
I have uploaded the most recent broken version to neurodebian -devel so we could "play" with it
> RF: SSHRI should not provide string form with escaped characters

- datalad/distribution/tests/test_add_sibling.py
Saw
```
datalad.distribution.tests.test_add_sibling.test_add_sibling ... The authenticity of host 'push.it (151.80.116.111)' can't be established.
RSA key fingerprint is SHA256:216WuUohcUHLAXzVSUNM9LBIXc5pkITuxU2l6KMBufM.
Are you sure you want to continue connecting (yes/no)? 
```
which felt not right ;)
> BF: use example.com based urls in tests

- .travis.yml
- CONTRIBUTING.md
- datalad/__init__.py
- datalad/cmd.py
- datalad/consts.py
- datalad/support/annexrepo.py
- datalad/support/external_versions.py
- datalad/support/gitrepo.py
- datalad/support/sshconnector.py
- datalad/support/sshrun.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_external_versions.py
- datalad/support/tests/test_sshconnector.py
- datalad/support/tests/test_sshrun.py
- datalad/tests/test__main__.py
> RF+ENH+BF: attempts to fix up for recent git-annex changes

- datalad/crawler/pipelines/tests/test_fcptable.py
- datalad/tests/utils.py
- setup.py
> BF: to get master testable again

- datalad/api.py
- datalad/cmdline/main.py
- datalad/crawler/nodes/annex.py
- datalad/distribution/add.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_add.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/utils.py
- datalad/interface/base.py
- datalad/interface/results.py
- datalad/interface/tests/test_save.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
> Return values: last half mile

- datalad/api.py
- datalad/cmdline/main.py
- datalad/crawler/nodes/annex.py
- datalad/distribution/add.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/distribution/drop.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/tests/test_add.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/uninstall.py
- datalad/distribution/utils.py
- datalad/interface/base.py
- datalad/interface/results.py
- datalad/interface/tests/test_save.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
- datalad/tests/test_utils.py
- datalad/utils.py
> PR#1485 reborn against master, plus more fixes

- asv.conf.json
- benchmarks/benchmarks.py
Whatever I thought would be 20 minutes, resulted in hours of 
- #1512 "discovery", troubleshooting and for which here I just provided an ugly workaround here for benchmarks in question but should be properly fixed asap
- 2 commits pushed directly into master (6ca5392a1550c64c17e448527d74076586ff7455, 6ca5392a1550c64c17e448527d74076586ff7455) 
So now, you can do something like 
```shell
$> asv run --python=2.7 --dry-run --bench .*SuperdatasetsOperationsSuite.*   
· Creating environments                                                   
· Discovering benchmarks
·· Uninstalling from virtualenv-py2.7
·· Building for virtualenv-py2.7
·· Installing into virtualenv-py2.7..
· Running 10 total benchmarks (2 commits * 1 environments * 5 benchmarks)
[  0.00%] · For DataLad commit hash 6ca5392a:
[ …
```
> Benchmark basic API commands (add, install, etc)

- datalad/cmdline/main.py
- datalad/crawler/pipelines/tests/test_openfmri_collection.py
- datalad/customremotes/tests/test_archives.py
- datalad/distribution/add.py
- datalad/distribution/dataset.py
- datalad/distribution/drop.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/remove.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_create_github.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/tests/test_update.py
- datalad/distribution/uninstall.py
- datalad/interface/results.py
- datalad/interface/save.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
- datalad/metadata/tests/test_base.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
> BF+RF: little annoying things around `drop` improved

- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_subdataset.py
- docs/examples/nipype_workshop_dataset.sh
````
% time datalad subdatasets -r
datalad subdatasets -r  1,48s user 0,93s system 20% cpu 11,775 total
````
reference:
````
% time git submodule status --recursive
git submodule status --recursive  0,20s user 0,13s system 11% cpu 2,784 total
````
approach seems simple.
> OPT: recursive subdataset discovery can be made faster

- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/uninstall.py
did
```
datalad install --reckless -s raiders raiders-clone
```
so it wasn't added to that superdataset. but upon remove benign message made no sense:
```shell
$> datalad remove --nocheck raiders-clone             
[ERROR  ] Found multiple subdatasets with registered path raiders-clone:
| []
| There should be only one. [uninstall.py:__call__:405] (AssertionError) 
```
so I just made that logic conditional on being a subdataset
> BF: do not whine whenever removing a dataset which is not a subdataset

- datalad/support/gitrepo.py
to see if this would be legit (no tests broken) and possibly help to resolve the locking issue.
the point is -- we might not need to write index at that point. moreover it might be OPT since now this call makes GitPython  first read index if it wasn't read before and then write it (if I got it right)
> BF(?): do not write index explicitly in precommit

- asv.conf.json
- benchmarks/api.py
- benchmarks/common.py
- benchmarks/core.py
Now published already at http://datalad.github.io/datalad/ -- I reran them completely, so old results are gone, and should be easier to navigate.  running for more commits now
> RF: benchmarks -- shortened names and moved into separate modules

- .travis.yml
There is no information in them failing constantly, , while we know exactly why. Moreover, they make master look broken for no good reason.
> TST: Let NFS tests fail -- they just take too long

- datalad/distribution/clone.py
- datalad/distribution/get.py
This extends the already existing facility to generate candidate source
URL from a single argument to also be able to eat additional candidates
via an argument. This change enabled a tiny RF of `get` that allowed for
the removal of a loop of submodule URL candidates.
This PR also resolves the issue of intermediate error reporting
expressed in gh-1553, but not the other ideas in that issue.
> ENH: specify alternative sources for `clone`

- datalad/cmdline/main.py
- datalad/distribution/add_sibling.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/distribution/get.py
- datalad/distribution/install.py
- datalad/distribution/siblings.py
- datalad/distribution/tests/test_siblings.py
- datalad/interface/common_opts.py
- datalad/interface/utils.py
Log:
````
mih@meiner ...tasets.datalad.org/labs/haxby/raiders (git)-[master] % datalad --output-format json_pp siblings -s here
{
"action": "query-sibling",
"annex-bare": "false",
"annex-description": "mih@meiner:/tmp/datasets.datalad.org/labs/haxby/raiders",
"annex-uuid": "7203baa3-f472-4bca-b886-753e2a9da1df",
"annex-version": "5",
"available_local_disk_space": 23273848256,
"name": "HERE",
"path": "/tmp/datasets.datalad.org/labs/haxby/raiders",
"refds": "/tmp/datasets.datalad.org/labs/haxby/raiders",
"status": "ok",
"type": "sibling"
}
````
> Various little improvements of `siblings`

- datalad/__init__.py
- datalad/cmd.py
- datalad/distribution/add.py
- datalad/distribution/utils.py
- datalad/support/gitrepo.py
- datalad/support/network.py
- datalad/utils.py
Biggest pieces is to make the global SSHManager optional.
Some proof:
> Various fixes to get basic functionality running on windows

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- don't instantiate `git.Repo` if we don't need it. Thus, making creation of *`Repo` instances cheaper
- fix *`Repo.is_valid_repo` to respect .git files
- make *`Repo.get_remotes()` not using `git.Repo` by default (needed in `AnnexRepo` constructor and therefore this change is required to not intantiate `git.Repo` immediatly
> WIP: RF: lazy loading *Repo.repo

- datalad/ui/utils.py
- datalad/utils.py
Copied straight from the "terminal" of greatness:
````
D:\>datalad install ///
[INFO] Cloning dataset from 'http://datasets.datalad.org/' (trying 2 location candidate(s)) to 'D:\datasets.datalad.org'
install(ok): D:\datasets.datalad.org (dataset)
D:\>cd datasets.datalad.org
D:\datasets.datalad.org>datalad get openfmri\ds000001\sub-06\anat\sub-06_inplaneT2.nii.gz
[INFO] Cloning dataset from 'http://datasets.datalad.org/openfmri/.git' (trying 1 location candidate(s)) to 'D:\datasets.datalad.org\openfmri'
install(ok): D:\datasets.datalad.org\openfmri (dataset) [Installed subdataset in order to get D:\datasets.datalad.org\openfmri\ds000001\sub-06\anat\sub-06_inpla
neT2.nii.gz]
[INFO] Cloning dataset from 'http://datasets.datalad.org/openfmri/ds000001/.git' (trying 1 location candidate(s)) to …
```
> Completes basic data consumer functionality on Windows

- datalad/api.py
This is confounded with those functions not (yet) using the `@build_doc` decorator...
> No API function with an underscore in its name has a proper docstring in the Python API

- datalad/api.py
- datalad/distribution/create_sibling.py
- datalad/distribution/create_sibling_github.py
- datalad/distribution/create_test_dataset.py
- datalad/distribution/publish.py
- datalad/export/__init__.py
- datalad/interface/add_archive_content.py
- datalad/interface/base.py
- datalad/interface/crawl.py
- datalad/interface/crawl_init.py
- datalad/interface/download_url.py
- datalad/interface/ls.py
- datalad/interface/test.py
- datalad/interface/utils.py
- datalad/metadata/aggregate.py
- datalad/metadata/search.py
- datalad/support/sshrun.py
> Use @build_doc decorator for all commands

- datalad/support/param.py
For example we have to incorporate the implications of `action`, or `nargs` settings in `Parameter`. Example:
````
purge=Parameter(
args=('--purge',),
nargs='+',
metavar='KEY',
doc="""any metadata item with a key matching an entry in the given
list is removed from the metadata.""",
constraints=EnsureStr() | EnsureNone()),
````
which in itself is correct for the commandline API leads to this Python API docstring excerpt:
````
purge : str or None, optional
any metadata item with a key matching an entry in the given list is
removed from the metadata. Constraints: value must be a string, or
value must be `None`. [Default: None]
````
So the dtype description is accurate for a single list item, but the list itself is nowhere mentioned, just in the custom text.
We need to check situations like …
> Python API docs need more accurate type description

- datalad/distribution/siblings.py
- datalad/interface/__init__.py
- datalad/interface/annotate_paths.py
- datalad/metadata/metadata.py
- datalad/metadata/tests/test_manipulation.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
- docs/source/cmdline.rst
On the way to 1st class preferred content management we need a frontend for git annex' metadata (tagging). Here is comes. While being add it I also implemented native support for dataset-level metadata:
Changes:
More details are in the docstring of the command.
Possible TODOs (not necessarily in this PR):
> `metadata` command 

- datalad/distribution/clone.py
- datalad/distribution/tests/test_clone.py
> BF: Proper clone failure report due to insufficient permissions

- datalad/distribution/get.py
- datalad/distribution/subdatasets.py
- datalad/interface/tests/test_annotate_paths.py
- datalad/support/annexrepo.py
Docs are in the diff.
Data dependency datasets in the studyforrest collection want to marked up with this, before they come on board.
> Limit recursive install on a per-subdataset basis

- .travis.yml
- requirements-devel.txt
We wouldn't be able to release like that (we could patch debian packages for wrapt but still -- that is not a solution) but at least meanwhile we could bring tests under control until https://github.com/GrahamDumpleton/wrapt/issues/98 is resolved
> BF(workaround): use patched wrapt disabling its extensions

- datalad/distribution/dataset.py
- datalad/distribution/publish.py
- datalad/distribution/siblings.py
- datalad/distribution/tests/test_publish.py
- datalad/support/annexrepo.py
Closes #1667 -- had to fix up some assumptions in the test.  Before publish would not publish anything if there were changes only in git-annex, e.g. you just installed the dataset .  But that means you got updates to git-annex and for consistency, or to share possibly info about files you also got, publish should push git-annex branch even if there were no other changes
Closes #1669 -- caught exception and issued a descriptive warning
> BF: publish if only updates to git-annex, do not puke if remote is ignored by annex

- datalad/distribution/add.py
- datalad/distribution/create.py
- datalad/distribution/tests/test_add.py
- datalad/distribution/tests/test_create.py
- datalad/support/annexrepo.py
It became a frequent practice for me to create such a .gitattributes file nearly for many datasets
I was creating locally for practice etc.  Even though there is `no_annex` plugin, it is not really visible (now it will be in `create --help`) and ATM lacks even option for such mode. 
And once again -- I think extensibility of plugins is great but most common operations should have clear and concise options available
> ENH: create --text-to-git to establish .gitattributes so that text file to git

- COPYING
- datalad/__init__.py
- datalad/interface/test.py
- datalad/support/third/noseclasses.py
- datalad/support/third/nosetester.py
I have failed to pick out exactly how to invoke bloody nose.run so it works also outside of the code base, so decided to just copy those pieces into our code base and trim connections to NumPy so we could just still use their runner for now.
Needed so we could test 'as installed' datalad without needing numpy
might abandon it altogether so do not merge
note that anyways - `datalad test` doesn't work if datalad is built using nuitka for execution as a standalone (`--exe` mode) since nose would not be able to find datalad module
> WiP: Borrow pieces from NumPy to run the tests without needing entire numpy for that purpose

- datalad/support/annexrepo.py
- datalad/tests/test_utils.py
- datalad/utils.py
Ideally we should just use --batch mode for get, but it is N/A for copy ATM, so decided to implement this "do in groups of files" for get/copy
Closes #1683
> BF: make multiple invocations for get/copy if too many files listed

- datalad/support/annexrepo.py
This would avoid any problems with too many files specified on cmdline, and could make operation actually faster.
The only side effect might be for copy_to where it would report only X files
to be copied whenever later complaining that some (not present here) are not available
> RF: actually provide original "files" to call to annex upon get/copy

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
Demonstrating #1691, and the fix.
> TST: Add a test for publishing recursively with absent subdatasets

- docs/source/basics.rst
Hey,
I edited the API principles'  first part. There seems to be no big difference but I think the subtle changes make reading a lot easier for users being naive to the command line, git etc.
...gonna wrap my head around the "Commands install vs get" section which did not intuitively make sense to me the first time reading it. 
P.S.: I added explicit examples for using the https and ssh protocol but did not provide any real address (``datalad install ###example####``) due to sheer ignorance (e.g. available datasets)
> DOC: Basic Principles -> API Principles revised

- datalad/distribution/add.py
- datalad/distribution/remove.py
- datalad/interface/annotate_paths.py
- datalad/interface/crawl_init.py
- datalad/interface/save.py
- datalad/interface/tests/test_save.py
- datalad/interface/tests/test_utils.py
- datalad/metadata/metadata.py
- datalad/tests/utils.py
> Misc RF+ENH for `save`

- .travis.yml
The failure started to happen I believe due to precise migrating from precise to trusty.  Actually quite cool that the rest remained working as it should
This one is somewhat of a blind try
> BF: try to specify nfs mount in /etc/exportfs before installing NFS kernel server

- datalad/interface/__init__.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- docs/source/cmdline.rst
This PR does not implement support for command that do in-place modification of dataset files. This is waiting for a resolution of #1424.
Ping #1650
> Towards a resolution of #1650 (run a command and capture its impact)

- datalad/interface/annotate_paths.py
- datalad/interface/diff.py
- datalad/interface/tests/test_diff.py
Needed to make #1746 work in full.
> BF: Align behavior of `diff <path>` with `git status <path>`

- datalad/distribution/__init__.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/metadata/metadata.py
- datalad/resources/website/index.html
- datalad/resources/website/tests/test.html
- docs/datalad-metadata.rst
- docs/examples/3rdparty_analysis_workflow.sh
- docs/source/acknowledgements.rst
- docs/source/basics.rst
- docs/source/conf.py
- docs/source/config.rst
- docs/source/gettingstarted.rst
- docs/source/glossary.rst
- docs/source/index.rst
- docs/source/metadata.rst
- docs/source/related.rst
- tools/screencast_bash.rc
This /only/ changes strings and leaves the classname DataladAnnexCustomRemote untouched.
This does not take care of 'datalad' -> 'DataLad', as that will be much more
difficult to sift through (between all the commands and URLs).
> Datalad -> DataLad

- datalad/distribution/clone.py
example:
```shell
[INFO   ] Cloning http://datasets.datalad.org/labs/haxby to '/tmp/haxby' 
[DEBUG  ] Attempting to clone http://datasets.datalad.org/labs/haxby (1 out of 2 candidates) to '/tmp/haxby' 
[DEBUG  ] Git clone from http://datasets.datalad.org/labs/haxby to /tmp/haxby 
[DEBUG  ] Failed to clone from URL: http://datasets.datalad.org/labs/haxby (Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
cmdline: /usr/lib/git-annex.linux/git clone -v http://datasets.datalad.org/labs/haxby /tmp/haxby
stderr: 'Cloning into '/tmp/haxby'...
fatal: repository 'http://datasets.datalad.org/labs/haxby/' not found
' [cmd.py:wait:291]) 
[DEBUG  ] Attempting to clone http://datasets.datalad.org/labs/haxby/.git (2 out of 2 candidates) to '/tmp/haxby' 
```
> ENH: make cloning INFO message more lean (move report of # of candidates to debug)

- docs/casts/basic_search.sh
- tools/cast2asciinema
Here is an example of asciinema with the description containing the commands with links to the manpages help:  https://asciinema.org/a/vhCxdfvqqnNGDk6xQFdxwvOQh
now https://asciinema.org/~DataLad contains two asciinemas generated at two different resolutions. @aqw  do you think it would be possible easily to switch between two different asciinemas depending on desktop-vs-mobile rendering? ideally making it possible to choose one or another
edit: also now includes a basic search cast, rendered here: https://asciinema.org/a/134920 and which I will add in a second to datalad.org repo (Closes #1755)
> ENH: screencasts - generate .cmd.md file to be cut/pasted into description + possible to modify terminal size for "big" recording

- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Annex special remotes may have no URL. Don't fail when trying to fetch from such remotes. Just do nothing and log on debug level.
> ENH: Don't fail on fetch if a (special) remote doesn't provide an URL

- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
- datalad/support/tests/test_gitrepo.py
- test for using `force` with `GitRepo.push()`
- using `--force` with `publish` leads to `git push --force` in addition to existing behavior
> ENH: Allow for force pushing

- tools/cast_bash.rc
- tools/cast_live
This helper will 
- start a new xterm in a geometry/resolution which should be ok for HD video casts on e.g. youtube
- "say" in the original terminal 
- wait before typing or executing any command in the original terminal
So it is jumping between two terminals (original with "Say"ed instructions) for you and the one which you could be possibly recording (e.g. with obs)
This way original cast could be used to guide interactive session while still allowing to interact in that terminal
> NF: cast_live helper to guide interactively through casts

- datalad/distribution/siblings.py
- datalad/distribution/utils.py
- datalad/downloaders/credentials.py
- datalad/support/annexrepo.py
- datalad/ui/dialog.py
- docs/casts/boxcom.sh
> Better support for special remotes (webdav in particular)

- datalad/utils.py
That is how it is done in other places throughout the code (we should
provide a helper), so no reason to make it special here and thuse
detect correctly root within submodules and workdirs which would have
just .git file or a symlink
Closes #1803
> BF: detect git repo root by presence of .git alone

- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_subdataset.py
More work might be needed to replace other uses of config.get_value
where we do not want automatic casting to be done, but I looked around and didn't find obvious problematic places -- where we used it (also not easy to figure out since we have our own config.get_value) it seems to point to values which couldn't be that degenerate
> BF: allow submodules names be numbers and "bool" values

- datalad/distribution/create_sibling_github.py
- datalad/distribution/tests/test_create_github.py
- docs/casts/boxcom.sh
- boxcom cast -- just let ppl know what variables to defined
- create-sibling-github -- if login provided, then use it while defining github credential name, so to support multiple logins;  also include it within https urls to avoid reentry later (not yet sure about all this but at least it allowed me to use it and try with different accounts)
> ENH: boxcom cast + create-sibling-github

- datalad/distribution/publish.py
I must confess that this is a semi-blind fix since I do not really know the purpose
of type_src here, which is used only in few spots in the code.  But I saw that the
record had type_src file, and made sense to be used here
Quick review/blessing/critic would be appreciated @mih 
Closes #1813
> BF: consult also type_src before deciding that by default type is the dataset

- datalad/support/annexrepo.py
- datalad/tests/test_direct_mode.py
Fixes Travis build using `DATALAD_REPO_VERSION=`.
We need a more general solution as stated in the comment (see diff), but a quickfix might be more important right now to not obfuscate other failures.
edit Closes #1835
> BF: Don't extract an empty string from datalad.repo.version

- datalad/distribution/create_sibling.py
- datalad/distribution/publish.py
- datalad/distribution/tests/test_publish.py
- datalad/interface/annotate_paths.py
Yet another semi-blind fix on top of the previous tiny #1814 (since otherwise couldn't check) making it possible to just `publish -r --since=`.  The last commit is the trickiest since I think I violated some logic of tripple-annotating-and-diffing files whenever I do not care about files, but rather care about publishing changes to entire datasets.  I have changed to report that there is a diff if commits differ, which was the logic if no files were provided.  But the thing is that files were provided, since they were result of the first stage of annotating paths (why would we care about individual files when publishing full datasets?) and were passed below in the logic.
Another commit extended API of helpers and the interface to allow to not care about unstaged and not tracked files …
> Make publish -r --since= great again

- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_publish.py
- datalad/distribution/tests/test_subdataset.py
- datalad/distribution/tests/test_update.py
- datalad/support/tests/test_gitrepo.py
- datalad/tests/utils_testrepos.py
- requirements-devel.txt
- setup.py
sits on top of #1801 
to test even more thoroughly.
> BF+ENH: allow for submodules to have numeric or bool names

- datalad/distribution/publish.py
Quick&Dirty fix:
In my case it was a submodule which we do not even probably want to publish -- its url points to a github repository (but may be we would?), and it was not locally installed (I believe):
mridefacer in http://datasets.datalad.org/?dir=/labs/gobbini/famface/data  (also subject to not yet finished fix in #1675
ideally we need to decide on what we are doing with "such" submodules
- if their url is some remote, but they are present locally -- should we publish them? (probably so)
IIRC: `git clone` first tries to find those submodules based on supermodule url, not the url in .submodules. This way also more guarantee that this published clone would have what is needed/referenced
> BF: report impossible if target repo does not exist during publish

- datalad/__init__.py
- datalad/plugin/wtf.py
- datalad/support/external_versions.py
- datalad/support/tests/test_external_versions.py
This pull request proposes to make the `wtf` plugin more informative
Demo
```
% datalad plugin wtf
System
======
OS          : posix Linux 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02)
Distribution: debian/buster/sid
Environment
===========
GIT_EDITOR: vim
GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
PYTHONPATH: /home/mih/hacking/datalad/git
Dataset information
===================
path: /tmp/audio
repo: AnnexRepo
Metadata
--------
[no metadata]
Configuration
=============
alias.co: checkout
alias.glog: log --pretty=format:'%h %ad %s (%an)' --date=short --graph
alias.st: status
alias.wdiff: diff --color-words
alias.wshow: show --color-words
annex.backends: MD5E
annex.uuid: b76c4724-c271-437f-afa7-24e5369970fa
annex.version: 5
color.diff: auto
color.status: true
core.bare: …
```
> ENH: Improve wtf plugin with essential bits stolen from PyMVPA

- datalad/cmd.py
- datalad/crawler/dbs/files.py
- datalad/crawler/nodes/tests/test_annex.py
- datalad/customremotes/datalad.py
- datalad/distribution/dataset.py
- datalad/distribution/siblings.py
- datalad/interface/ls.py
- datalad/interface/save.py
- datalad/support/annexrepo.py
- datalad/support/exceptions.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/tests/test_cmd.py
- datalad/tests/test_utils.py
- datalad/utils.py
This pull request fixes #1865 and closes #1753
- to use `swallog_logs()` for testing purposes only
- to lower the log level used in several places
- new context manager disable_logger for suppressing possible output in critical places
> RF: dont swallow logs in actual datalad code

- datalad/cmdline/main.py
`log-level`, `pbs-runner` and `version` are global options.
> RF: Remove global options from subcommand help pages

- datalad/interface/annotate_paths.py
This pull request fixes #1880.
To be more specific:
If 'modified' was set, AnnotatePaths failed to report on unavailable paths.
Please have a look @mih . You might want to say something about the approach and the comments I left in the code.
> BF: AnnotatePaths

- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_install.py
The issue is that comcast does provide "something" for those non-existing
domains.  git even manages to clone from them, just considers repo to be empty:
```
$> /usr/lib/git-annex.linux/git clone -v http://nonexistingreallyanything.somewhere/bla /tmp/datalad_temp_test_failed_clonez8pXGR/sub
Cloning into /tmp/datalad_temp_test_failed_clonez8pXGR/sub...
warning: You appear to have cloned an empty repository.
```
So, using our own domain, we would have a better chance to have control
over the names WE do not actually have
This pull request fixes remaining parts of  #1908
> ENH(TST): use our domain (.datalad.org) instead of some random .somewhere for nonexisting url

- datalad/__init__.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Otherwise we could get dozens of tests failing due to incorrect
operations etc, so better to crash as early as needed, e.g.
while instantiating the first GitRepo
I managed to run "datalad test" in a fresh'ish docker image - ended up with FAILED (SKIP=66, errors=60, failures=20) ;-)
> ENH: crash fi git config is not yet setup with name/email

- datalad/interface/tests/test_run.py
Recent tests of master were failing in the "heavy debug" environment, triggered by the fact that we use nose without `-s` there.  I do not remember how we addressed this in other places, but clearly here we seems to need a "proper" stdout with fileno, so I just wrapped with `swallow_outputs`.  Is there is a better way @bpoldrack?
> BF(TST): swallow outputs while ds.run for the case of nose without -s

- setup.py
do not rely on current state of local affairs of having lzma to define it as a
requirement or not.  I had e.g. one installed globally.
Might fix remaining issues on linux buildbots with running tests.
On OSX need to figure out how to install liblzma-dev
> BF: specify if to request pyliblzma solely on python version

- datalad/interface/common_cfg.py
- datalad/metadata/metadata.py
- datalad/metadata/parsers/bids.py
- datalad/utils.py
This pull request fixes #1828 
> Various smallish metadata improvements

- datalad/metadata/search.py
+ Explicit "No matches" if none
This pull request fixes #1898 
Sample output:
```shell
$> datalad --output-format '{path}' search --max-nresults 3 *sub-xx*run-01*nii.gz 
[INFO   ] Query completed in 0.00225687026978 sec. No matches. 
$> datalad --output-format '{path}' search --max-nresults 3 *sub-0[12]*run-01*nii.gz 
[INFO   ] Query completed in 0.00272393226624 sec. Reporting all matches. 
/home/yoh/datalad/openfmri/ds000001/sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz
/home/yoh/datalad/openfmri/ds000001/sub-02/func/sub-02_task-balloonanalogrisktask_run-01_bold.nii.gz
$> datalad --output-format '{path}' search --max-nresults 3 *sub-0[123]*run-01*nii.gz 
[INFO   ] Query completed in 0.00285696983337 sec. Reporting max. 3 top matches. …
```
> ENH: Say "all matches" if # of returned hits < max_nresults

- datalad/auto.py
FTR: Tests under PY3 are now flooded with:
```
[WARNING] Failed proxying open with (3, 'rb', -1), {}: lstat: illegal type for path parameter [posixpath.py:lexists:171] 
[WARNING] Failed proxying open with (5, 'rb', -1), {}: lstat: illegal type for path parameter [posixpath.py:lexists:171] 
[WARNING] Failed proxying open with (3, 'rb', -1), {}: lstat: illegal type for path parameter [posixpath.py:lexists:171] 
```
but there is no functional impairment. Haven't looked into it, but it smells like we are doing something wrong.
> AutomagicIO issues under PY3

- CHANGELOG.md
- datalad/plugin/__init__.py
- datalad/plugin/export_archive.py
- datalad/plugin/export_tarball.py
- datalad/plugin/tests/export_archive.py
- datalad/plugin/tests/test_export_archive.py
- datalad/plugin/tests/test_plugins.py
- docs/source/modref.rst
Note that this is a prerequisite for #1942
> Some minor improvements of the plugins

- datalad/crawler/pipelines/tests/test_crcns.py
- datalad/distribution/siblings.py
- datalad/interface/ls.py
- datalad/interface/run.py
Was initially noted in the failing travis run of https://github.com/datalad/datalad/pull/1949
> BF: there is no .message in python3 Exception. Just use str()

- datalad/support/json_py.py
> BF(workaround): pyliblzma might throw AttributeError __exit__ unless dir first

- datalad/auto.py
- datalad/support/annexrepo.py
This pull request fixes #1948
This pull request proposes converting path names to strings prior to checking if 'annex/objects` is in path.
> Fix bytes object path issue with pandas #1948

- datalad/crawler/nodes/annex.py
- datalad/crawler/pipelines/tests/test_openfmri.py
- datalad/support/annexrepo.py
- datalad/tests/utils.py
`git_options` are ignored, `options` are respected... duplication and absent clarity in the interface.  Just patching up and adding a test
> BF: crawler needed to use now "options" instead of "git_options" apparently

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- datalad/tests/test_auto.py
> BF: "run" to respect PWD, unless ran as ds.run (then top of the dataset)

- datalad/support/json_py.py
- datalad/tests/test_auto.py
> BF(workaround): provide a decorator for LZMAFile call to do dir() first

- datalad/support/annexrepo.py
Also just reuse one if already known from previous logic
The issue was that git annex does not report in json the percent progress
if key did not have size known (eg for a fast url or youtube video).
Next git-annex version (to be tested) should report one from the file size
> BF: do not blow if percent-progress is not provided by annex

- datalad/interface/tests/test_run.py
- datalad/tests/utils.py
Current master failed in 2 master-only matrix runs.  One is due to the same absent -s
Also changed the decorator so it doesn't silently passes but raises SkipTest since that is what is happening really
> Mark some run tests as failing with nosetests without -s

- setup.py
The `aggregate-metadata` command did not work for me until I installed the `duecredit` package. Hopefully this is the right place to put the dependency in.
> Add missing dependency on 'duecredit'

- datalad/auto.py
- datalad/tests/test_auto.py
This pull request fixes #2011 
quite neat:
```shell
$> python -m datalad /usr/bin/fsleyes ~/datalad/openfmri/ds000002/sub-05/anat/sub-05_inplaneT2.nii.gz
[INFO   ] Activating DataLad's AutoMagicIO 
[INFO   ] Running code of /usr/bin/fsleyes 
[INFO   ] File /home/yoh/datalad/openfmri/ds000002/sub-05/anat/sub-05_inplaneT2.nii.gz has no content -- retrieving 
19:23:24: Debug: ScreenToClient cannot work when toplevel window is not shown                                   
19:23:24: Debug: ScreenToClient cannot work when toplevel window is not shown                                   
19:23:24: Debug: ScreenToClient cannot work when toplevel window is not shown
...
python -m datalad /usr/bin/fsleyes   6.40s user 1.62s system 71% cpu 11.146 total
```
> ENH: automagicio - proxy also isfile

- datalad/crawler/pipelines/tests/test_simple_s3.py
- datalad/downloaders/s3.py
- datalad/downloaders/tests/test_s3.py
- datalad/support/s3.py
This pull request fixes #1999
TODO which I've not yet accomplished - unicode filenames in s3. Decided to postpone for now
This pull request proposes to do automagic decision to url unquote path component if any %XX is found in it.  This would allow to be smart about quoted urls (like we are passing back and worth with annex) and straight url given as a string to download-url.  i don't think conflict is likely
> Support obscure file/key names in S3 buckets

- datalad/__init__.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/support/gitrepo.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
- datalad/tests/test_base.py
Got tired from needing to setup some fake HOME just to test datalad on a new box (well -- docker, buildd, etc).  Also IIRC it was desired to avoid side-effects of user configs.  So here we have it now -- only user name and email are known, the rest is tabula rasa.
> ENH(TST): setup a fake HOME for running tests without being affected by user config

- datalad/support/gitrepo.py
The first two commits are typo fixes for `check_git_configured`.
The last commit prevents datalad from throwing an error when
user.name/user.email are set in a config file other than ~/.gitconfig.
> Drop --global from the git config check

- datalad/support/sshconnector.py
happens e.g. if sockets became owned by root due to evil sudo.
That caused travis runs to fail, e.g.
https://travis-ci.org/datalad/datalad/jobs/315021004
> BF: also guard listing of ssh sockets for OSError

- datalad/interface/ls.py
- datalad/interface/tests/test_ls.py
Please see the commit messages.
> ls: Fix unicode output on Python 2; disable unicode for non-tty

- datalad/cmdline/main.py
% datalad create-sibling -s mddatasrc XXX:/media/data/datasets/aggdemo --as-common-datasrc XXX --target-url http://XXX/aggdemo/.git     
[INFO   ] Connecting ... 
[INFO   ] Considering to create a target dataset XXX/scratch/aggdemo at /media/data/datasets/aggdemo of XXX 
Failed to run ['ssh', '-o', 'ControlPath="XXX/.cache/datalad/sockets/e43b2233"', 'XXX', 'export "PATH=/usr/bin:$PATH"; mkdir -p /media/data/datasets/aggdemo'] under None. Exit code=1. out= err=mkdir: cannot create directory ‘/media/data/datasets/aggdemo’: Permission denied
File "/usr/bin/datalad", line 8, in <module>
main()
File "/usr/lib/python2.7/dist-packages/datalad/cmdline/main.py", line 381, in main
if hasattr(exc.stderr, 'encode')  \
UnicodeDecodeError: 'ascii' codec can't decode …
> Unicode issue in error reporting, crashes datalad

- datalad/metadata/definitions.py
- datalad/metadata/metadata.py
- datalad/metadata/parsers/audio.py
- datalad/metadata/parsers/bids.py
- datalad/metadata/parsers/image.py
- datalad/metadata/parsers/nifti1.py
- datalad/metadata/search.py
- datalad/plugin/bids2scidata.py
- datalad/plugin/tests/test_bids2scidata.py
- datalad/resources/isatab/scidata_bids_investigator.txt
- setup.py
This has been imported from https://github.com/mih/BIDS2ISATab which itself is a fork of https://github.com/INCF/BIDS2ISATab. It is functional, but not complete yet.
Changes
- majority of the old code is concerned with assembling and merging metadata from various sources -- this is already done by datalad. The only thing left todo is to sort and group metadata by file type, and to format a nice table
This is now working as intended. Future changes will have to be:
- stop relying on present `participants.tsv` file and use info from aggregated metadata -- requires conversion on metadata structure that nobody can afford right now
- implement regression test on (multiple) real datasets -- will become possible (and cheap) once our own datasets carry new aggregated metadata
> NF: Plugin that can convert BIDS metadata into ISATAB format optimized for submission to Scientific Data

- datalad/support/network.py
```
% datalad install //openfmri
[ERROR  ] Possibly incorrectly determined string <class 'datalad.support.network.DataLadRI'> correspond to //openfmri address -- it failed matching regex. Dunno how to handle. Contact developers [network.py:_str_to_fields:692] (ValueError) 
```
It should probably just say that it doesn't know how to treat this first. From this perspective an "incorrectly determined string" is an incomprehensible statement. And I also don't want to be contacted each time someone accidentally forgets the third slash ;-)
Changes:
Now looks like this:
```
% datalad install //openfmri
[ERROR  ] Cannot handle URL '//openfmri': categorized as <class 'datalad.support.network.DataLadRI'>, but does not match syntax. Did you intent to use '///'? [network.py:_str_to_fields:693] …
```
> Suboptimal error message

- datalad/auto.py
- datalad/metadata/metadata.py
- datalad/metadata/search.py
- datalad/tests/test_auto.py
It might fix the "stalling" I have reported somewhere (probably was closed since "happened on smaug")
It should make AutomagicIO of lesser burden on 'search' since before now it would query for the same files over and over again , and look for git repo for every directory etc. So now
- gets a mode to consider each path only once
- caches repos for each directory considered
- skips paths containing `/.git/` since also not expecting anything to be under annex control there
- assumes that there could be no subdataset under .datalad (for now) which helps to avoid
looking up for .git for every bloody objects/XX directory (funny part is that then it was all in vein in my case since repo is anyways is git, not annex)
- a bit improved and harmonized logging there
- potentially, at least partially …
> A variety of tuneups to AutomagicIO to avoid redoing the same queries in 'search'

- after1.txt
- after2.txt
- datalad/metadata/metadata.py
Parsers may not be prepared to deal with this situtation and crash,
taking down the entire aggregation effort.
Some parsers may be able to infer some metadata from filenames, but in
general there is no point in feeding no-content files to parsers.
In general to-be-aggregated datasets should have content.
> BF: Do not send files without content to metadata parsers

- docs/source/gettingstarted.rst
Otherwise an error would appear
```
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'[full]'"
```
This pull request fixes #
> Remove redundant space in pip command

- datalad/crawler/nodes/matches.py
This pull request fixes #2073 
Blow hard if scrapy is not available but scraping of links is requested
Isn't covered by unittests ATM AFAIK
> BF: throw MissingExternalDependency if no scrapy while trying to match links

- tools/cast2script
```
Otherwise, if $1 has a sequence like reproducible_analysis.sh's
"printf %03d", it will be formatted, leading to the script having
"printf 000" rather than the intended "printf %03d".
```
Fixes #2074.
I'll follow up with a diff of the converted `docs/casts/*.sh`.
> BF: cast2script: Don't interpret argument as printf's format

- CONTRIBUTING.md
- datalad/cmd.py
Introduced to answer the question in #2089
> DATALAD_USE_DEFAULT_GIT to override detection and use default git in the PATH

- datalad/crawler/pipelines/tests/test_crcns.py
- datalad/interface/__init__.py
- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- docs/casts/reproducible_analysis.sh
- docs/source/cmdline.rst
This pull request supersedes #2070.  The old branch name was too
narrow in scope, so that seemed to be a good indicator that it was
worth opening a new PR for.
Some of the main differences:
* The rerun functionality is now under its own command, `datalad
rerun` (Closes #2072).
* You can now specify the base for re-execution explicitly using
`--onto`.
Specifying a branch name for the re-execution and the base is no
longer coupled.  Now you can re-execute on top of HEAD with a new
branch name, or re-execute at another point but in a detached
state.
* The `--root` flag can be used to say "execute all commands in
commits reachable from REVISION" rather than "execute *the*
command in REVISION".  This has a similar behavior to
`git rebase --root`.
* The branch is rebased on top of `0.9.x` (at …
> ENH: Rerun extensions

- datalad/resources/website/assets/js/jquery.dataTables-1.10.12.js
Allows for quick(er) navigation of the site
For now I just quickly manually patched website's .js to achieve that so you could try
the only cons I am aware of would be for vimperator and alike users -- you would need to press Esc first to make shortcuts of those extensions work instead of just being in edit mode. But imho it is a small price to pay ;)
> ENH(webui): autofocus on searchbox when entering a page

- CONTRIBUTING.md
- datalad/cmd.py
- datalad/cmdline/main.py
- datalad/crawler/nodes/matches.py
- datalad/crawler/pipelines/openfmri.py
- datalad/crawler/pipelines/tests/test_crcns.py
- datalad/interface/__init__.py
- datalad/interface/base.py
- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- datalad/resources/website/assets/js/jquery.dataTables-1.10.12.js
- docs/casts/reproducible_analysis.sh
- docs/source/cmdline.rst
- tools/cast2script
This pull request merges 0.9.x into master.  There were conflicts in
test_run.py and auto.py.  I was less sure of the auto.py resolutions
(since none of the changes were mine), so I've included the conflicts
below.  In both cases, I took HEAD's variant.
```diff
diff --cc datalad/auto.py
index f6548052,e04af467..00000000
--- a/datalad/auto.py
+++ b/datalad/auto.py
@@@ -154,21 -132,13 +154,30 @@@ class AutomagicIO(object)
filearg = "name" if PY2 else "file"
if filearg not in kwargs:
-                        lgr.debug("No name/file was given, avoiding proxying")
-                        raise _EarlyExit
+                        raise _EarlyExit("no name/file was given")
file = kwargs.get(filearg)
++<<<<<<< HEAD
+
+                if isinstance(file, int):
+                    raise …
```
> Merge 0.9.x

- datalad/cmd.py
- datalad/support/annexrepo.py
- datalad/tests/heavyoutput.py
- datalad/tests/test_cmd.py
- datalad/utils.py
This pull request fixes #2116 
overall -- it came out much larger than what I hoped/expected/initially did.  But hopefully would be resilient enough to not introduce regressions
This might result in negative impact on performance while calling those batch commands (since would require creation of a file) but imho better slower but more reliable ;)
Unless immediate objections, I would like to merge it asap.  We could fix up/refactor later if needed, but "stuck" operation of datalad without any error msg isn't fun
> Store 'offline' output (typically stderr) into a file to avoid lockdowns

- datalad/customremotes/archives.py
- datalad/customremotes/base.py
- datalad/customremotes/tests/test_archives.py
- datalad/distribution/get.py
- datalad/interface/utils.py
- datalad/support/annexrepo.py
- datalad/ui/progressbars.py
This pull request fixes #??? (I thought we had an issue, yet to find it)
This pull request proposes to take advantage of the new feature in git-annex since today to be able to pass INFO level message to the git-annex, which then gets provided to us as well in --json output.  This way we could channel not only a dummy message that we need to download a tarball of size X, but also entire progress report for more progress bars appearing on the screen (for each tarball being downloaded).  ~~~It is a bit mouthfull on the screen, and not playing nicely with tqdm and probably expected sizes,  but it is better than silence of current implementation ;)~~~  Now it looks actually quite pretty, with progressbars being cleared if a log message is displayed, so the whole output is quite sensible! …
> Propagate download progress all the way from datalad-archives into the main datalad 

- datalad/metadata/metadata.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
This PR RFs the `search` command to be able to handle multiple search modes. Currently supported are:
- `autofield`: this is what used to be the new search (two-pass, autodiscover schema, files and datasets)
- `default`: this is some some ways the old search, in some ways not
The new default behavior is to works on datasets only (but it has the ability to do files as well, unlike the old command). All metadata is currently coerced into a single string using a default whoosh text analyzer. Unit tests document what kind of searches work.
Additional metadata homogenization could be supported by introducing custom mappings (e.g. for neuro* datasets, etc.). This would be necessary to support the previously available 'search by field' in the old command. The current aggregated metadata has no …
> "Old" and new search in one command

- datalad/metadata/extractors/dicom.py
This pull request fixes the dicom metadata extractor, which currently would fail with `AttributeError`, if there's a DICOMDIR file, since `dicom.read_file` returns an instance of an unexpected class in that case.
This pull request proposes to just skip for now. At some point we might want to make use of that file, 
but just ignoring it does the job to prevent unnecessary failure. 
> Fix DICOM extractor

- .github/PULL_REQUEST_TEMPLATE.md
This pull request fixes confusion I had for a while on the purpose of two edit boxes where both cannot be marked at the same time (it is either WiP or complete).  May be I have missed the point.
> Remove "This is in progress" and unmark "complete" - mutually exclusive

- setup.py
also throw a WARNING message about that to alert the user.  That description
is used anyways only for upload to pypi
This pull request fixes failing OSX builds with requirements-devel 
Please do not look @datalad/developers
> BF(workaround): Allow pandoc to be missing while pypandoc being available

- datalad/metadata/aggregate.py
- datalad/metadata/metadata.py
Should address complaint in gh-2142
@yarikoptic Should help with debugging metadata extraction crashes. Also catches a condition in which non-compliant metadata would have been processed even though it was detected and reported as broken.
> ENH: More stringent and improved error handling on metadata extraction

- datalad/metadata/metadata.py
```shell
(git)smaug:/mnt/btrfs/datasets-meta6-1/datalad/crawl[master]git
$> time datalad aggregate-metadata -r 2>&1 | tee aggregate-run1.log
[INFO] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1/datalad/crawl
[INFO] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1/datalad/crawl/abide
...
[INFO] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1/datalad/crawl/labs/haxby/attention
[INFO] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1/datalad/crawl/labs/haxby/life
[WARNING] 18 files have no content present, skipped metadata extraction for them
[ERROR] unhashable type: 'list' [metadata.py:_get_metadata:500] (TypeError)
aggregate_metadata(impossible): /mnt/btrfs/datasets-meta6-1/datalad/crawl/dicoms [No matching aggregated metadata in Dataset at …
```
> aggregate-metadata -r crashes with [ERROR] unhashable type: 'list' [metadata.py:_get_metadata:500] (TypeError)

- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Fixes #2153
cons:  GitPython does not support workdir's yet, but as such we do not support them as well anyways
> BF: use GitPython for getting information about tags, get hexsha for nonannotated tags as well

- datalad/metadata/metadata.py
- datalad/metadata/search.py
Search index construction might take a while... E.g. I have started one yesterday evening (5pm) and it is still going (after 18h, edit 1: I am pretty sure it is stuck -- it is 28th hour now) on a reasonably fast machine (smaug ;) ).  I have no clue either it is not just stuck, or when it should be complete, all I see is
```shell
(dev3) 2 11290.....................................:Fri 15 Dec 2017 05:01:52 PM EST:.
(git)smaug:/tmp/crawl[master]
$> datalad search Haxby type:dataset
[INFO   ] Building search index
[INFO   ] Scanning for metadata keys
```
I wondered, if it goes sequentially through datasets and datasets list is initially constructed (full or just top level) -- would be nice to have some kind of a progress bar with % or at least some indication of activity/progress.
> Some kind of progress bar for index construction?

- datalad/__init__.py
Whenever we use our make_tempfile and also set DATALAD_TESTS_TEMP_KEEP=1
it would be kept and not removed -- so we just need to check if it still exists
I thought that os.makedirs also does not fail if leaf dir exists, but
apparently I was wrong
> BF: check if directory does not exist while creating a temp HOME

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
- datalad/config.py
I think I entered (copy/pasted actually from the message) it correctly, didn't I?
I expected to end up at ascii.py:decode:26 (ideally) ;)
```shell
$> datalad -c datalad.runtime.raiseonerror=yes aggregate-metadata
[INFO   ] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 
[ERROR  ] Failed to get dataset metadata (bids): 'ascii' codec can't decode byte 0xc2 in position 1188: ordinal not in range(128) [ascii.py:decode:26] 
[ERROR  ] Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately) [aggregate_metadata(/mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053)] 
aggregate_metadata(error): /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053 [Metadata extraction …
```
> -c datalad.runtime.raiseonerror=yes  in command line is not passed into cfg

- datalad/customremotes/tests/test_archives.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/support/annexrepo.py
- datalad/tests/utils.py
This pull request reveals the spread of #2131 and may be then will attempt at a few fixes.  "Sing along" - contributions will be open
This pull request proposes someone to
- (unlikely here) make `get_most_obscure_filename` into a generator to produce few of those lovely ones.  We cannot have just one pointing to all the issues, although I think spaces in the middle are nearly always as bad as in the beginning (trailing ones are trickier)
- [  x?  ] as a quicker resolution to above - make prefix to obscure filename controllable from env, so we could have a matrix run with `-` as a prefix. **I already have it but do not want to push until I make sure that all of the issues are caught first -- tests are still running although buildbots are already happy**
Please have a look …
> BF: Tolerate files starting with -

- datalad/plugin/tests/test_bids2scidata.py
> BF: operate within a dedicated tempdir while invoking a plugin creating a dir

- datalad/distribution/tests/test_clone.py
- datalad/support/gitrepo.py
- causes all the ugly messages in read-only access
- not sure if needed any longer - hopefully all needed flushing was
fixed in GitPython long ago
I want to see if any tests fail for us now after this change
> RF: do not write down index every time in __del__

- datalad/cmd.py
- datalad/tests/test_cmd.py
happened on travis:
https://travis-ci.org/datalad/datalad/jobs/342143094
in python 3.4 DATALAD_REPO_VERSION=5 on 0.9.x branch
but not sure if anything but it being python3 is related:
```
ERROR: datalad.tests.test_cmd.test_runner_heavy_output(False,)
File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1225, in newfunc
func(*args, **kwargs)
File "/home/travis/build/datalad/datalad/datalad/tests/test_cmd.py", line 202, in check_runner_heavy_output
expect_stderr=True)
File …
```
> intermittent test failure: 'str' does not support the buffer interface

- datalad/interface/common_cfg.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
- datalad/plugin/bids2scidata.py
> ENH: `search`

- datalad/auto.py
- datalad/log.py
traceback might try to open some files, which causes infinite recursion
within auto -- so we just do not log msgs there and be done
might lead to a bit of overhead while logging with a traceback, but otherwise shouldn't impair
This pull request fixes #2107
> BF: do not log traceback for log msgs deep within auto

- datalad/distribution/get.py
- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_subdataset.py
- datalad/interface/tests/test_annotate_paths.py
- datalad/interface/tests/test_diff.py
we had discussion on possible other ways to get a list of submodules without invoking `git submodule status` which does additional stuff.
magit uses `git ls-files --stage` and then submodules have a leading magical tag `160000`.  There is also `--recurse-submodules` but that one is not compatible with `--stage` which directs to output those tags
the fun part is that surprisingly `ls-files` although lists all the files in the repo, still comes out as a winner even with grep attached even when there is no submodules
```shell
falkor:/srv/datasets.datalad.org/www/openfmri/ds000115
$> time bash -c 'git ls-files --stage | grep ^160000'
bash -c 'git ls-files --stage | grep ^160000'  0.00s user 0.00s system 0% cpu 0.007 total
$> time git submodule status                         
git submodule …
```
> Use lsfiles to obtain list of submodules (and maybe other info)

- datalad/distribution/get.py
- datalad/distribution/subdatasets.py
- datalad/interface/annotate_paths.py
- datalad/interface/diff.py
- datalad/interface/results.py
- datalad/interface/utils.py
- datalad/metadata/aggregate.py
Following commands used
```shell
git grep -l '\.startswith(_with_sep(' | xargs sed -i -e 's|\(\<[^ ]*\)\.startswith(_with_sep(\([^)]*\)))|path_startswith(\1, \2)|g'
git-sedi -e 's|\(\<[^ ]*\)\.startswith(_with_sep(\([^)]*\)))|path_startswith(\1, \2)|g' 
```
should be done on master as well after this merged -- there is more uses
> RF: use existing path_startswith instead of repeating pattern of .startswith(_with_sep

- datalad/support/s3.py
- datalad/tests/test_s3.py
The problem (will probably appear in other cases as well, that vcr
tapes gets "bound" in the previous test to the providers we get to reuse
in the next test, which then screws it up when both tests are ran.
I am afraid there are other places where this would reveal itself and more
systematic solution should come
This pull request fixes those reports where this test_s3.py was failing mumbling about not being able to override a cassette
> BF(TST): do not reuse the same providers in the vcr-taped test

- datalad/downloaders/base.py
- datalad/support/s3.py
```
ERROR: datalad.interface.tests.test_ls.test_ls_s3
File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 841, in newfunc
return func(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 518, in __call__
args, kwargs)
File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 105, in __call__
function, args, kwargs
File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 120, in _execute_function
return self._handle_function(fn=handle_function)
File …
```
> UI code bug somewhere

- datalad/api.py
Stumbled upon this while looking into #2085
Despite that code being seemingly unused, its removal causes my local test runs to segfault :(
> RF: API generation got much simpler, remove cruft

- datalad/distribution/tests/test_install.py
Move the assertion outside of the block so that it actually runs, and make it check the exception message rather than the string representation of unittest.case._AssertRaisesContext.
> TST: Correct a silently failing assertion

- datalad/api.py
- datalad/cmdline/helpers.py
- datalad/cmdline/main.py
- datalad/cmdline/tests/test_formatters.py
- datalad/coreapi.py
- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/interface/annotate_paths.py
- datalad/interface/ls.py
- datalad/metadata/aggregate.py
- setup_support.py
This should have no visible differences for actual cmdline use, but
the startup time for individual commands should be noticeably reduced
Here is an example:
Pre:
```
In [2]: %timeit !datalad subdatasets
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
1 loop, best of 3: 317 ms per loop
```
Post:
```
In [3]: %timeit !datalad subdatasets
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
subdataset(ok): .asv (dataset)
1 loop, best of 3: 223 ms per loop
```
> OPT: cmdline startup faster (more cruft removed)

- datalad/metadata/extractors/dicom.py
This pull request addresses #2210 (partially)
This pull request proposes to ignore DICOM files with a name starting with `PSg`, since those files (apparently created by some QC routine on Philips scanners) seem to not carry any metadata relevant for describing the image series.
This PR was supported by funds from the 
German federal state of Saxony-Anhalt and the European Regional Development 
Fund (ERDF), Project: Center for Behavioral Brain Sciences, Imaging Platform
> Ignore PSgxxxxx DICOM files during metadata extraction

- datalad/metadata/aggregate.py
Fix broken import due to recent change in `datalad.api`.
Just `unlock` for now. There are most likely more of that kind of fixes  to come.
> BF: import unlock for aggregate-metadata

- datalad/distribution/tests/test_install.py
- datalad/distribution/utils.py
- datalad/resources/website/assets/js/main.js
This pull request proposes to urlunquote paths for installation deduced from URLs, and also quote within WebUI since otherwise navigation would break. This fixed up main.js is deployed ATM at datasets.datalad.org so you could browse into http://datasets.datalad.org/?dir=/dicoms/dartmouth-phantoms/bids_test6-PD+T2w/ 
> Bf urlencode webui

- datalad/distribution/tests/test_install.py
- datalad/support/gitrepo.py
```shell
snastase$ datalad -l debug install -r -g .
...
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.install.Install'> 
[DEBUG  ] Building doc for <class 'datalad.plugin.Plugin'> 
[DEBUG  ] Install passes into get 1 items 
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] already installed [get(/Users/snastase/Work/storyteller/data)] 
get(notneeded): /Users/snastase/Work/storyteller/data (dataset) [already installed]
[DEBUG  ] Building doc for <class 'datalad.distribution.subdatasets.Subdatasets'> 
[DEBUG  ] Determined class of decorated function: <class …
```
> Fails to datalad install subdataset when dataset path has ~

- setup.py
Running `datalad test` leads to this (I guess, because we do not install the test data files):
```
ERROR: datalad.metadata.extractors.tests.test_audio.test_audio
File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 629, in newfunc
return t(*(arg + (filename,)), **kw)
File "/usr/local/lib/python3.5/dist-packages/datalad/metadata/extractors/tests/test_audio.py", line 49, in test_audio
path)
File "/usr/lib/python3.5/shutil.py", line 241, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks) …
```
> Out of source tree tests fail, files missing

- datalad/distribution/publish.py
tried to publish
```shell
$> datalad --dbg publish -r --since= --to=datalad-public --missing=inherit        
[INFO   ] Will try to create a sibling inheriting settings from <Dataset path=/mnt/btrfs/datasets/datalad/crawl/dicoms/dartmouth-phantoms> 
File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
main()
File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 356, in main
ret = cmdlineargs.func(cmdlineargs)
File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 422, in call_from_parser
ret = list(ret)
File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 411, in generator_func
result_renderer, result_xfm, _result_filter, **_kwargs):
File …
```
> one more missing import for the api?

- .travis.yml
https://pythonclock.org
Majority of all testing is done exclusively for PY2. I don't see a reason why that should be the case, other than history.
> Switch to PY3 for all exotic flavors on travis

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
- datalad/support/annexrepo.py
- datalad/support/network.py
- datalad/tests/utils.py
This covers some basic features mentioned at gh-1665.
The few things it can do:
* Data from a CSV or JSON file can be used to construct URLs and file names to be passed to 'git annex addurl'.
The field names from the data file (header names for CSV or properties for JSON) can be used as placeholders like "{participant_id}.mgz".  However, names with "!" or ":" aren't currently supported because these are interpreted as formatting flags.
* Subdatasets can be created by using "//" in the filename format string.
* fast=True will pass --fast to 'git annex addurl'.
Some of what it can't do:
* ~It doesn't yet have an option for specifying which columns should be used as metadata.~
* ~There's no support for the Content-Disposition filename.~
* There isn't a jobs flag that's passed --jobs=N to …
> [WIP] ENH: Add initial implementation of addurls plugin

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
This pull request replaces the "_lper" root and extension fields in the addurls plugin with a behavior that follows the heuristic used by git-annex.
> ENH+RF: addurls: Follow git-annex's heuristic for extensions

- datalad/distribution/tests/test_uninstall.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/tests/utils.py
This pull request fixes test assertions, that check the error message of `git-annex-drop`, which changed recently.
Please note, that #2277 for example already suffers from that in a not-allowed-to-fail-build.
> TST/BF: Adapt assertions on error message to new annex version

- datalad/crawler/nodes/annex.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
ATM this function return any dataset above a given dataset -- with `topmost=True` all the way up. However, despite the name, it does not actually check whether a "superdataset" actually knows about the original dataset as being a true subdataset (might be totally unrelated, or branch was switched, or previous version checked out, ...). As this function is a key player when saving dataset hierarchies, this behavior can lead to undesired outcomes, i.e. when a non-subdataset suddenly become one, just because somewhere upstairs another dataset is hanging around.
I think `get_superdataset()` should crosscheck by default, and get a switch to not do that when it is OK/desired.
In case you are wondering: yes, we do have a test that ensures that this "broken" behavior is maintained ;-)
> `Dataset.get_superdataset()` should be able to verify subdatasets

- setup.py
Running tests in our singularity image (an installed datalad, out of tree tests) reveals that we are not installing a resource file:
```
ERROR: datalad.plugin.tests.test_bids2scidata.test_minimal
File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 494, in newfunc
return t(*(arg + (d,)), **kw)
File "/usr/local/lib/python3.5/dist-packages/datalad/plugin/tests/test_bids2scidata.py", line 114, in test_minimal
repo_url='http://example.com',
File …
```
> bids2scidata is missing installed resource

- datalad/interface/tests/test_run.py
The Datalad Singularity image, for example, only has python3.
Re: #2287
This pull request should fix 2287, but I'm leaving out the "fixes" link in order to keep that issue open because there is a second set of unrelated errors being discussed.
> TST+BF: run: Don't assume the environment has a "python" executable

- docs/casts/simple_provenance_tracking.sh
This pull request fixes #2103.
> casts: Add more 'rerun' examples

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
This pull request fixes #2280.  It adds a `--nosave` flag to addurls so that it's possible to say `datalad run 'datalad addurls ...'`.
> ENH: --nosave flag for addurls

- datalad/distribution/tests/test_uninstall.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/json_py.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_json_py.py
- datalad/tests/test_base.py
- datalad/tests/utils.py
This pull request fixes #2272 
This pull request proposes to not fail if there is no git configuration -- just issue a warning.
The rationale is that git became even more "robust" in assigning some author name/email, and annex does some tricks too...  but if we always demand configuration -  that just complicates the simplest consumer usage.
> RF: do not raise if git is not configured -- just issue a warning

- datalad/interface/ls.py
- datalad/plugin/export_tarball.py
- datalad/plugin/tests/test_tarball.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
As pyout showed some times we were getting None for the date and it was
happening in detached head because we would just return None then since
there is no branch.
Later this function could be extended to print date of any commit, not just
the last one in the branch etc.
By default now returns "authored", not "committed" (thus rename) date since
it is the one of interest typically -- if date was altered, better be the
one specified
> RF/BF: get_commit_date to return authored date by default, handle detached head as well

- datalad/distribution/add.py
- datalad/distribution/drop.py
- datalad/distribution/get.py
- datalad/distribution/publish.py
- datalad/distribution/remove.py
- datalad/interface/annotate_paths.py
- datalad/interface/diff.py
- datalad/interface/save.py
- datalad/interface/tests/test_save.py
- datalad/interface/unlock.py
- datalad/metadata/metadata.py
This pull request fixes #2276
This pull request proposes to provide `path_src` portions of the annotated paths while doing the commit in `save`.  Also while at it in aa0143b14982438392e98eb24880fc312d13f113  I did something along the same lines -- return path_src as well in annotated2content_by_ds  if only paths are requested.  I am not sure even if that line of logic gets triggered by any test/use-case.  Running all the tests will show. Otherwise it should be ready for review etc
> BF 2276: pass path_src into commit as well (so we commit renamed files removal as well)

- datalad/support/_lru_cache2.py
- datalad/support/cache.py
- datalad/support/network.py
Since that information is persistent (type or parsing would not change through time)
and very frequently queried - having it cached would be benefitial and also avoids
logs clutter.
Instead of using our little explicit DictCache I have used lru_cache which is
built-in since 3.2, so I have added an (untested) backport from the web.  Seems to work.
Our mighty tests will show
> OPT: cache (lru_cache) calls to guess_ri_cls

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
Fixes the inappropriate error message in gh-2295. Now:
```
% datalad wrongcommand
usage: datalad [-h] [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version]
[--dbg] [--idbg] [-c KEY=VALUE]
[-f {default,json,json_pp,tailored,'<template>'}]
[--report-status {success,failure,ok,notneeded,impossible,error}]
[--report-type {dataset,file}]
[--on-failure {ignore,continue,stop}] [--cmd]
datalad: error: unrecognized arguments: wrongcommand
```
Feel free to take this further if you feel like investing time.
> BF: Prevent argparse from showing an empty list of subparsers

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
If files are being added in an active batch process, set_metadata will
silently fail (return a generator that yields no values).  This is
because the underlying git annex command has a zero-exit status but no
output.  As an example, this can be triggered by running
$ echo content >foo
$ ( echo "foo" && sleep 30 ) | git annex add --batch
in one shell and then running 'git annex metadata --json --set f=v -- foo'
in another before the first completes.
This issue was noticed when running the addurls plugin with the
--nosave option, in which case no metadata gets registered for
subdatasets.
Work around it by running precommit before setting metadata.  It's not
clear whether there are similar issues elsewhere, and in general it
might be better make the cleanup of batch processes more local …
> BF: Resolve interaction between batch commands and set_metadata

- datalad/metadata/metadata.py
The reason is an unexpected behavior change of the built-in `sorted()` for built-in types. Demo:
```
% python -c "sorted({('5.1.1', '5.1.1.0'), '0.4.11'})" && echo "happy"
happy
% python3 -c "sorted({('5.1.1', '5.1.1.0'), '0.4.11'})" && echo "happy"
File "<string>", line 1, in <module>
TypeError: '<' not supported between instances of 'tuple' and 'str'
```
I do not have an idea how to fix that.
> Metadata unique value sort broken for PY3

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
Disable annex.alwayscommit during the set_metadata calls so that, for
each dataset, there is only one metadata commit on the git-annex
branch rather than a commit per file.
By default, the metadata changes will be committed when addurls calls
save (the following block of code).  If --nosave is given, the
metadata changes will remain in .git/annex/journal until an action
outside of addurls triggers the commit.
---
> ENH: addurls: Reduce the number of metadata commits

- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
default rendering is just an "entry" (i.e. path for the file), but it still takes awhile to spit it out since according to @mih loads the full record
> option (or make it also automagicly enabled) to disable loading full metadata record for search result 

- datalad/distribution/create.py
- datalad/distribution/tests/test_create.py
If we're creating a subdataset and --nosave is given, we don't
register the subdataset with the superdataset because 'git submodule
add' doesn't make much sense if the subdataset doesn't have a commit
yet.  (It modifies the .gitmodules file but no gitlink entry is
created.)  As a consequence, 'datalad save -d. -r .' cannot be used to
save changes after creating a subdataset with --nosave.
But in most cases, there is already a commit in a subdatasets (the one
that sets the annex backend), so add the subdataset as long as it has
at least one commit.  If the subdataset is a regular git repository,
there are no commits and the previous behavior is retained.
---
> ENH: create: Consider adding subdatasets when --nosave is given

- datalad/version.py
It runs: `from datalad.version import __full_version__`, but this symbol is only created if  `if lexists(opj(projdir, '.git')):` in `version.py`.
I guess one solution would be to make `__full_version__` = `__version__` by default and only adjust it if there is a git dir.
> `wtf()` only works with git version of datalad

- datalad/interface/run.py
- datalad/interface/save.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_save.py
- datalad/tests/test_api.py
This pull request
* extends `save` to allow the message to be specified in a file (like `git commit`s `-F`)
* makes `run` dump the log message to `.git/COMMIT_EDITMSG` when a command fails.  If the user expected the command to fail, they can then save the results using `save`s `-F` argument.  `datalad rerun` will happily re-execute commands unless they fail with a different code.
---
> ENH: run: Support runs with non-zero exit codes

- datalad/metadata/extractors/__init__.py
- datalad/metadata/metadata.py
- datalad/plugin/tests/test_metadata.py
- setup.py
This makes it possible for 3rd-party packages to provide additional extractors.
> RF: Define and use entrypoints for metadata extractors (fixes gh-2356)

- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
- datalad/tests/test_utils.py
- datalad/utils.py
I bet there is a better/proper way but I could not think about one... I thought that may be `metadata` call on the superdataset could just report those aggregated unique values but I was not smart enough to figure out if that was possible.
This pull request proposes to make --show-keys more versatile and report statistics on the key values since they are known at no additional cost while listing them.  My original goal was to check what unique values for dicom fields we collected and in how many datasets.  While still waiting (for an hour now) for output of (a more informative, since provides pairs)
```shell
$> datalad -f '{metadata[dicom][Manufacturer]}: {metadata[dicom][ManufacturerModelName]}  Version(s):{metadata[dicom][SoftwareVersions]}' --report-type file search --max-nresult=0 …
```
> Make --show-keys more useful - report stats

- datalad/interface/utils.py
This is needed for some graceful handling of extension modules.
> PY2 Class name guessing logic in interface/utils.py should be able to handle datalad_ module prefix.

- datalad/interface/test.py
Without requiring a user to keep track of what extensions are installed
on a particular system.
@bpoldrack This implements your idea. The neuroimaging extensions already registers its module as tests.
> NF: `test` can pick up extension test suites and run them too

- datalad/plugin/extract_metadata.py
Could now be a simple positional arg, as the interface is not more powerful.
> `extract-metadata` command does not need to use `--file` anymore

- datalad/support/annexrepo.py
> BF: when batched checkpresentkey returns None, assume that it is absent

- datalad/distribution/dataset.py
- datalad/metadata/extractors/tests/test_image.py
- datalad/metadata/extractors/tests/test_xmp.py
- This pull request fixes yet another absent binding issue: BF: import subdatasets, so Dataset could gets its .subdatasets
- Makes tests Skipped if PIL.Image fails to import and libxmp throws some other exception, not ImportError upon import (those recent OSX problems). Fixes #2374
> BF: import subdatasets, so Dataset could gets its .subdatasets

- datalad/interface/test.py
- datalad/interface/utils.py
- datalad/metadata/aggregate.py
- datalad/metadata/extractors/__init__.py
- datalad/metadata/extractors/audio.py
- datalad/metadata/extractors/tests/test_audio.py
- datalad/metadata/extractors/tests/test_dicom.py
- datalad/metadata/metadata.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
- datalad/plugin/extract_metadata.py
- datalad/plugin/tests/test_metadata.py
- datalad/support/annexrepo.py
- datalad/tests/test_utils.py
- datalad/utils.py
- docs/source/conf.py
- docs/source/customization.rst
- setup.py
The can grow really large. Example: DICOM slice timestamps aggregated over a 2h session (24 per seconds...).
For the `dicom` extractor is makes sense to disable uniquification completely, because it produces nice `Series` metadata, but we need something for the general case.
Also, unique value keys is what `search --mode autofield` bases the index build on during the first pass, hence we have to keep those for such use cases (what keys do you know).
Apparently already a concern in #2342
> Need some clever way of limiting the output of uniquification of metadata values

- datalad/cmd.py
- datalad/tests/test_cmd.py
Another blind attempt closer to the heart of things
This pull request fixes #2301 (if does not trigger failure after a few reruns)
> BF: assure that each line returned during processing of outputs ends with \n

- .travis.yml
It hit me in the past, and I still find it suboptimal, hence this proposal:
Let's change the travis setup to run tests on the installed datalad. ATM we run the tests on the result of `setup.py build` and only after the tests ran, we try to install.
At the same time, we offer a `test` command that is designed to pick up the installed tests.
With the new extension setup things become even weirder, as they need to be installed in order for the entrypoints to have any effect.
If there is any benefit to testing the non-installed datalad over the installed one, please let me know. Otherwise, I will push this change.
> Change test setup to run *installed* datalad

- docs/source/config.rst
`DATALAD_foo__bar` maps to `datalad.foo-bar`, but we don't mention the last bit in the docs.
---
>  DOC: Say that we s/__/-/ in the environment -> config mapping

- datalad/crawler/nodes/annex.py
- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_aggregation.py
- datalad/metadata/tests/test_base.py
Mode `all` what we used to do: extract from all datasets and update in all datasets throughout the entire tree.
Now there is a mode `target` that still extracts from all datasets, but only updates the aggregated metadata in the top-level target/base/ref dataset.
The `target` mode is a more suitable default IMHO, as otherwise any user gets subdatasets modified whenever they had no metadata pre-aggregated. However, in general one likely does not want to create a diff to upstream just because we want to get metadata aggregated in a local superdataset.
Due to the change in default, all previous usage of `aggregate_metadata()` has the mode spelled out now.
>  NF: Switch to select type of metadata aggregation update (fixes gh-2378)

- datalad/interface/save.py
```shell
(git-annex)hopa:~/datalad____/openfmri/ds000001[master]sub-01/func
$> git add 1
(dev) 2 9981.....................................:Thu 30 Nov 2017 09:25:58 AM EST:.
(git-annex)hopa:~/datalad____/openfmri/ds000001[master]sub-01/func
$> datalad save -m "try to save within subdir" -S
[WARNING] given reference dataset is not a dataset [save(/home/yoh/datalad____/openfmri/ds000001/sub-01/func)] 
> /home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py(496)_process_results()
-> if result_renderer == 'default':
(Pdb) c
> /home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py(496)_process_results()
-> if result_renderer == 'default':
(Pdb) c
save(impossible): . [given reference dataset is not a dataset]
(dev) 2 9982 ->1.....................................:Thu 30 Nov …
```
> save does not work within subdirectory of a subdataset: given reference dataset is not a dataset 

- datalad/api.py
- datalad/cmdline/main.py
- datalad/interface/tests/test_unlock.py
- datalad/interface/unlock.py
- docs/source/customization.rst
was afraid that `add` etc have the same problem, but seems to be only unlock:
```shell
(git-annex)hopa:~/datalad/openfmri/ds000001[master]sub-01
$> datalad add -d .. sub-01/anat/sub-01_T1w.nii.gz           
add(ok): sub-01/anat/sub-01_T1w.nii.gz (file)                                                                         
save(notneeded): /home/yoh/datalad/openfmri/ds000001 (dataset)
add (ok: 1)
save (notneeded: 1)
$> datalad unlock -d .. sub-01/anat/sub-01_T1w.nii.gz
unlock(ok): sub-01/sub-01/anat/sub-01_T1w.nii.gz (file)
```
as you can see  -- there is sub-01/sub-01
found while fixing for #1962 , and was confused by reported unlock -- so replicated independently
> unlock reported path is incorrect if operating on ds within subdir

- datalad/support/s3.py
- datalad/tests/test_s3.py
Check whether the query already has a versionId component so that we don't construct URLs that contain multiple versionIDs.  Depending on the situation, the caller may want to update an existing versionId to the latest version, so add a flag that enables this behavior.
---
This pull request fixes #2379.
Marked WIP because I haven't  run the test_version_url tests and they're based on a [guess][0] about the latest file version.  Let's see.
[0]:  https://github.com/datalad/datalad/issues/2379#issuecomment-379085453
> BF: s3: Don't duplicate ID when getting versioned URL

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
This makes it possible to get the same content when the content
pointed to by an S3 URL has been updated.  It can also fix 404s like
in gh-2333 because "URL?versionId=null" may still be accessible.
Closes #2380.
---
> ENH: addurls: Add an option to version S3 buckets URLs

- datalad/cmdline/tests/test_main.py
- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_update.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_annotate_paths.py
- datalad/interface/tests/test_run.py
This pull request fixes #2401  (although not fully but heaviest abusers)
(attaching to an issue failed for me... next time may be)
This pull request proposes to annotate a few more tests with `@slow` and `@integration`.  They will still be executed as a part of a single matrix run dedicated to run those heavy tests, but should make the "heavy debug" run shorter.
Altogether I think that many "slow" tests are simple a victim of `@with_testrepos` -- so we exercise them in "different" (but not much so) scenarios whenever they could actually be ran on a single test repo with nearly the same or the same "testing efficiency"
> ENH: annotate a few tests for @slow and @integration

- datalad/cmd.py
- datalad/plugin/tests/test_plugins.py
for handled entries
Revealed by good old OSX that a recent fix in fe62e46955f5a428bcf72b28a0861194a59183b0
introduced breeding trailing \n in the output which should have already been handled
by the output processor. See e.g. http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/3979/steps/nosetests/logs/stdio
The problem was that even if processor returns None, i.e. the line was already handled
we would have returned a newline to outside where we would have joined them with \n.
Fix, is to pass the suffix (used only in the case of handling those manually split lines)
to add to the end of the line if there was one remaining.
It should fix OSX buildbot issue
> BF: pass newline straight into _process_one_line to avoid joining empty new lines

- datalad/distribution/dataset.py
- datalad/interface/tests/test_save.py
- datalad/tests/test_utils.py
- datalad/utils.py
```shell
(datalad) Taylors-MacBook-Pro-4:tmp taylor$  datalad create --text-no-annex demo
[INFO   ] Creating a new annex repo at /tmp/demo 
create(ok): /tmp/demo (dataset)                                                                                      
(datalad) Taylors-MacBook-Pro-4:tmp taylor$ cd demo/
(datalad) Taylors-MacBook-Pro-4:demo taylor$ datalad -l debug crawl-init --save --template=simple_with_archives url=http://example.com
...
[DEBUG  ] Assigning credentials into 18 providers 
[INFO   ] Not adding annex.largefiles=exclude=README* and exclude=LICENSE* to git annex calls because already defined to be (not(mimetype=text/*)) 
[DEBUG  ] Creating crawler configuration for template simple_with_archives under . 
[DEBUG  ] Determined class of decorated function: <class …
```
> Gets confused by symbolic links in the path

- docs/examples/3rdparty_analysis_workflow.sh
- tools/testing/run_doc_examples
I did spot it already a few times but didn't catch the pattern yet (if there is any). Currently master fails in 
repo v6 mode test : https://travis-ci.org/datalad/datalad/jobs/364610382 with 
```shell
get(notneeded): /tmp/datalad_demo_bob.TABZ/myanalysis/src/forrest_structural/sub-01/anat/sub-01_T1w.nii.gz (file) [already present]
add(ok): /tmp/datalad_demo_bob.TABZ/myanalysis/result.txt (file)
[WARNING] Workaround: Wait for [] to add to git (<AnnexRepo path=/tmp/datalad_demo_bob.TABZ/myanalysis (<class 'datalad.support.annexrepo.AnnexRepo'>)>). 
save(ok): /tmp/datalad_demo_bob.TABZ/myanalysis (dataset)
[INFO   ] Cloning /tmp/datalad_demo_bob.TABZ/myanalysis to '/tmp/datalad_demo_alice.m8JW/bobs_analysis' 
install(ok): /tmp/datalad_demo_alice.m8JW/bobs_analysis (dataset)
[INFO   ] …
```
> some times fails to annex get data (locally I think) in our example

- datalad/interface/annotate_paths.py
- datalad/interface/tests/test_save.py
I cannot add a symlink pointing to a subdataset of a dataset. But only when no reference dataset is given -- see test.
```
mih@meiner ~/courses/stats/stats1/lecture (git)-[master] % datalad --dbg add 1_intro.html reveal.js --to-git
File "/home/mih/hacking/datalad/git/bin/datalad", line 8, in <module>
main()
File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 354, in main
ret = cmdlineargs.func(cmdlineargs)
File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 427, in call_from_parser
ret = list(ret)
File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 382, in generator_func
result_renderer, result_xfm, _result_filter, **_kwargs):
File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 449, in …
```
> Symlink annotation issue; is a link to a dataset a type='dataset?

- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_aggregation.py
If I perform partial aggregation (not all subdatasets) the portion that wasn't aggregated is not only not aggregated, but wiped out.
```
(neuro-dev) mih@meiner /tmp/mytest (git)-[master] % datalad subdatasets
subdataset(ok): functional (dataset)
subdataset(ok): structural (dataset)
subdataset (ok: 2)
(neuro-dev) mih@meiner /tmp/mytest (git)-[master] % datalad metadata --get-aggregates
/tmp/mytest (dataset): aggregated
/tmp/mytest/functional (dataset): aggregated
(neuro-dev) mih@meiner /tmp/mytest (git)-[master] % datalad aggregate-metadata structural
[INFO   ] Aggregate metadata for dataset /tmp/mytest/structural 
[INFO   ] Engage metadata extractors: ['datalad_core', 'annex', 'dicom'] 
[INFO   ] Attempting to extract DICOM metadata from 386 files 
[INFO   ] Aggregate …
```
> `aggregate_metadata` is not incremental

- datalad/plugin/addurls.py
Identified observing http://datalad.github.io/datalad/#core.startup.time_help_np
This pull request helps #2405
Actually on local runs of the `asv run -E existing -b core.startup.time_help_np` I didn't spot any improvement. So may be it is not there ;-)  But I know that we did move away import of mock into the code blocks everywhere but in tests, so should be the right thing to do
Ideally we should stop mocking within codebase anyways and find better ways ;-)
> OPT: delay import of mock, which is heavy (300ms)

- datalad/customremotes/tests/test_archives.py
- datalad/customremotes/tests/test_datalad.py
- datalad/tests/utils.py
As a minimal refactoring of how those tests ran before testing both modes.
On Travis we have now dedicated matrix run to check direct, but not on
buildbots.  So I have decided to retain that sweeping.
On travis it might shave off 20-30 sec of time with this change since
would run only in "as config says" mode
> RF: @with_direct to run in one mode on travis/windows, but in both locally/buildbots

- datalad/distribution/publish.py
- datalad/support/gitrepo.py
commit 7a3c969ee4dc43d2517de9894e5b98490f03dbe7 (HEAD -> misc, gh-yarikoptic/misc)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sat Apr 14 21:01:56 2018 -0400
BF: no out/err available in exc handling - get from exception
commit 3b67db7b7c93e1ea9b2db341819279ce132bf9b1
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sat Apr 14 21:01:31 2018 -0400
BF: yet another missing import for a binding of diff
> Two litle fixes, commits are self explanatory

- datalad/interface/base.py
- datalad/interface/common_cfg.py
- datalad/interface/tests/test_base.py
There were no way to reset (override) config setting from command line using
report-status cmdline option.  Sure thing I could possible override config
setting itself (came to mind only while composing this message), but I thought
that it would make sense to have 'all' ;)
Feel free to close without merging if you see that cmdline options shouldn't be capable of overloading config settings ;)  (which is kinda a generic question, and they typically do, but may be we do not have a uniform way to say "disregard config setting, and keep default?")
> BF: 'all' to allow to override having a report_status filter from cmdline

- datalad/interface/save.py
- datalad/interface/tests/test_save.py
- datalad/tests/test_utils.py
- datalad/tests/utils.py
well -- we have `add` to add stuff, which also `saves`.  git allows for a convenient "commit ." which saves all changes in the current sub directory, so I thought that it would only make sense to call "datalad save -m msg ."... to my surprise it added all kinds of stuff which it should have not!
```shell
hopa:~
$> datalad create /tmp/repro
[INFO   ] Creating a new annex repo at /tmp/repro 
create(ok): /tmp/repro (dataset)                                                 
(dev3) 2 13324.....................................:Mon 18 Dec 2017 09:47:55 PM EST:.
hopa:~
$> cd /tmp/repro
(dev3) 2 13325.....................................:Mon 18 Dec 2017 09:47:56 PM EST:.
(git-annex)hopa:/tmp/repro[master]
$> touch 1 2 3
(dev3) 2 13326.....................................:Mon 18 Dec 2017 09:48:03 …
```
> `save` update, fix bug, test intended behavior, improve docs

- datalad/metadata/extractors/annex.py
- datalad/metadata/extractors/audio.py
- datalad/metadata/extractors/datalad_core.py
- datalad/metadata/extractors/exif.py
- datalad/metadata/extractors/image.py
- datalad/metadata/extractors/xmp.py
- datalad/metadata/metadata.py
All file metadata extractor loop over a given list of files -- ideal for progress logging.
Actually, there could be an output progress bar that tracks the extractors that already ran -- if more than one is scheduled.
> Add progress logging to any metadata extractor when #2351 is merged

- datalad/log.py
- datalad/plugin/addurls.py
This pull request
* updates addurls to use the new `log_progress` helper added in #2351
* moves addurl's progress decorator to log.py
Its purpose is to wrap a function that yields result dicts with a progress bar in order to 1) delay the display of the results while the status bar is being updated and 2) check the dict for a status of "notneeded"/"error" and display these counts in the bar's description.
It should be moved somewhere more general because it's not specific to addurls.  I chose log.py because it now uses `log_progress`.
---
> RF: addurls: Use log_progress

- datalad/distribution/tests/test_get.py
- datalad/interface/tests/test_annotate_paths.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_utils.py
- datalad/support/annexrepo.py
This pull request fixes certain cases of adding things (particularly submodules) to git in direct mode.
Note that it removes 12 `known_failure_direct_mode` markers.
> BF: Direct mode git-add

- datalad/plugin/__init__.py
- datalad/tests/test_utils.py
- datalad/utils.py
Initially (or not for someone else) was spotted in #2382 that even though tests run/fail, coverage is reported at 0%:
```
datalad/plugin/__init__.py                                   27      7    74%
datalad/plugin/add_readme.py                                 61     61     0%
datalad/plugin/addurls.py                                   332    332     0%
datalad/plugin/check_dates.py                                72     72     0%
datalad/plugin/export_archive.py                             67     67     0%
datalad/plugin/export_to_figshare.py                        137    137     0%
datalad/plugin/extract_metadata.py                           38     38     0%
datalad/plugin/no_annex.py                                   49     49     0%
datalad/plugin/wtf.py …
```
> coverage for (all) plugins code is reported at 0%

- datalad/ui/progressbars.py
- datalad/ui/tests/test_dialog.py
I am not clear now why I wanted to set it to 0sec, I guess something
did not update nicely.  I think it should be safe to set it to 100ms.
This should make progressbars smoother whenever each iteration is too
fast (e.g. during checking dates within git objects)
> ENH: do not update progressbar upon each entry - every 100ms

- datalad/support/param.py
This seems to be the intention of the original code.
A benefit of stripping whitespace here is that it avoids adding an
unnecessary period when there are trailing spaces, which can easily
happen if the string ends with "[CMD: ... CMD]".
---
> DOC: param: Strip doc before extending with a default

- datalad/cmd.py
Just spotted that for me even running a dummy `datalad run sleep 100` causes datalad to become extremely busy with something... what is it doing? probably some side effect of how subprocess is used?
```
[DEBUG  ] tracking command output underneath <Dataset path=/tmp/QA> 
[Level 9] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'status', '--debug', '-c', 'remote.origin.annex-ssh-options=-o ControlMaster=auto -S /home/yoh/.cache/datalad/sockets/23d1f58a', '--json', '--ignore-submodules=all', '--'] 
[Level 8] Finished running ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'status', '--debug', '-c', 'remote.origin.annex-ssh-options=-o ControlMaster=auto -S /home/yoh/.cache/datalad/sockets/23d1f58a', '--json', '--ignore-submodules=all', '--'] with status …
```
> datalad run causes 100% CPU utilization by datalad 

- datalad/interface/results.py
As of git-annex's 7e454ee34 (--json: multi-line notes, 2018-02-16),
the json "note" values can contain multiple lines.  (Before, only the
last line was included.)
We want to restrict a message to one line, so replace the newlines
with " ;" when translating these a note to a result message.
Fixes #2465.
---
> BF: annexjson2result: Adjust for multi-line note values

- datalad/cmdline/tests/test_main.py
- datalad/metadata/metadata.py
- datalad/metadata/tests/test_aggregation.py
- datalad/metadata/tests/test_base.py
- datalad/plugin/wtf.py
- datalad/version.py
Warning is issued under wrong conditions. Even if the queried dataset has metadata to report, the message will be issued, if the source dataset (althoug not even queried) has none.
> Inappropriate message: [WARNING] Metadata query results might be incomplete

- datalad/distribution/create.py
- datalad/distribution/tests/test_add.py
- datalad/version.py
This is no case in which this would be useful. We must prevent it.
> `add()` will put .gitignore, .gitattributes, etc in annex unless explicitly instructed not to

- datalad/customremotes/tests/test_archives.py
- datalad/distribution/add.py
- datalad/distribution/create_test_dataset.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_publish.py
- datalad/distribution/tests/test_update.py
- datalad/interface/save.py
- datalad/interface/tests/test_ls_webui.py
- datalad/interface/tests/test_run.py
- datalad/plugin/tests/test_check_dates.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/utils.py
- datalad/tests/utils.py
I am debugging in the context of #1921 and get to see the code layer again after months/years. I really think these functions should do much less than they do now. In particular, I would like to RF away the ability to `commit=True`. It makes the structure of those functions needlessly complicated, it prevents them from being usable as a generator, and (I hope) we don't need this functionality anywhere.
To be precise: we need it in oldish test code, but no real functionality uses it:
```
datalad/customremotes/tests/test_archives.py:    annex.add(fn_archive, commit=True, msg="Added tarball")
datalad/customremotes/tests/test_archives.py:    annex.add(fn_extracted, commit=True, msg="Added the load file")
datalad/customremotes/tests/test_archives.py:    annex.add('a.tar.gz', commit=True) …
```
> Kill *Repo.add(commit=True)

- .travis.yml
Provide Travis builds with extensions, executing the extension's tests to make sure we notice, when core breaks those extensions.
Please note, that datalad-container isn't available yet. I will add this one, when it's ready (i.e. when https://github.com/datalad/datalad-container/pull/3 is done)
> ENH: TRAVIS: Add integration tests for datalad extensions (Closes #2480)

- datalad/support/annexrepo.py
The reason is still unknown but it is not worth bombarding users with those
developer-oriented warnings.  We will just log them at DEBUG level
for ourselves
I thought there was an issue mentioning it but can't find
Also emailed @joeyh asking if such cases (regress in reported progress) is legit and could happen for an ok reason somehow
> RF: do not issue warnings when progressbar regresses

- datalad/distribution/siblings.py
Necessary for compatibility with git-annex 6.20180510+gitg500f7ea78-1~ndall+1
which changed error message so we identify it as AccessFailedError
I am not sure if that is the correct solution here but the entire logic is not
clear for me -- i.e. why we would allow it to happen and just issue an info
message instead of failing.  If it is to catch cases where it is a git
repo on the other end -- there should be some analysis of the stderr
> BF: handle DownloadErrors as well as CommandErrors while trying to enable special remote

- datalad/interface/test.py
I am not sure how to run tests for "everything in datalad"... e.g. in below you could see that I am installing datalad-crawler (`datalad crawl` command does become available) and expected that I could just test `datalad` module and automagically tests for `datalad.crawl` would also be executed... but nope:
```shell
$> git clone git://github.com/datalad/datalad-crawler                            
$> cd datalad-crawler 
$> virtualenv --system-site-packages venvs/dev                  
$> source venvs/dev/bin/activate
$> pip install -e .                 
$> which datalad                                                         
/tmp/datalad-crawler/venvs/dev/bin/datalad
$> python -m nose -s -v datalad 2>&1 | grep crawl
```
also now looking into .travis.yml -- seems that the only way is to just …
> entry_points in extensions -- not in effect whatsoever? (tests do not run, not available within datalad namespace)

- datalad/api.py
- datalad/cmdline/main.py
- datalad/metadata/metadata.py
loading extensions is duplicating in two places with identical log messages making it difficult to localize that code while tracing the log msgs
delaying import of `pkg_resources` is heavy and should get closer to when actually needed. Eventually we might manage to avoid loading extensions if not needed (command is decided)
> OPT: delay import of pkg_resources until use, adjust log messages to differ

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/tests/test_utils.py
- datalad/utils.py
This is a first pass at allowing inputs to be specified when calling `datalad run`.
WIP because
If a glob is given as the input value, it is expanded at the time of the run.  As an example, if '*' was used to indicate all annex files, a rerun would consider the inputs to be all of the annex files at the time of the initial run.
Expansion during the initial run seems appropriate because most of the time re-executing a command should only require those inputs.  However, it's possible that the caller would want to rerun a command that uses globs itself to get its input files, in which case files that were added after the initial run wouldn't be retrieved.
Perhaps we could also store the unexpanded inputs and add a rerun flag that says to use the unexpanded set.
Update: I'm still not sure, …
> ENH: Add --input flag

- datalad/metadata/extractors/datacite.py
- datalad/metadata/extractors/tests/test_datacite_xml.py
I think this should be underneath `.datalad/metadata/`, or even better, it should search for a file of this name in the list of files it gets to process.
> datacite extractor requires file at .datalad/meta.datacite.xml

- datalad/interface/run.py
Mention that the command is a shell command in the top-level
description rather than using the metavar so that datalad
containers-run doesn't need to override this value.
Re: https://github.com/datalad/datalad-container/pull/11#discussion_r189292367
---
> DOC: run: Rename cmd's metavar to COMMAND

- datalad/distribution/create.py
Inspired by https://github.com/datalad/datalad-container/issues/15
@kyleam
> RF: Leaner .gitattribute settings forcing content into Git

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_formatters.py
- datalad/cmdline/tests/test_main.py
- datalad/distribution/dataset.py
- datalad/interface/__init__.py
- datalad/interface/results.py
- datalad/plugin/__init__.py
- datalad/support/tests/test_sshrun.py
This pull request addresses some items in #2494 and adds sugaring like
```shell
$> time datalad instal -s /// /tmp/ds2                    
Unknown command instal.
Did you mean install or uninstall?
All known commands: add, add-archive-content, add-readme, addurls, aggregate-metadata, annotate-paths, check-dates, clean, clone, create, create-sibling, create-sibling-github, create-test-dataset, diff, download-url, drop, export-archive, export-to-figshare, extract-metadata, get, install, ls, metadata, no-annex, publish, remove, rerun, run, save, search, siblings, sshrun, subdatasets, test, uninstall, unlock, update, wtf
datalad instal -s /// /tmp/ds2  0.59s user 0.07s system 99% cpu 0.661 total
```
(in such cases I do not see a point of spiting out regular summary on options).  We could have …
> OPT: cmdline

- datalad/support/annexrepo.py
- datalad/support/tests/test_gitrepo.py
I've not uploaded most recent git-annex since it caused few other tests to fail in comparison to previous one ()
```shell
$> DATALAD_TESTS_SSH=1 python -m nose -s -v datalad.support.tests.test_gitrepo:test_git_custom_calls datalad.support.tests.test_annexrepo:test_AnnexRepo_add_unexpected_direct_mode       
datalad.support.tests.test_gitrepo.test_git_custom_calls ... FAIL
datalad.support.tests.test_annexrepo.test_AnnexRepo_add_unexpected_direct_mode ... ERROR
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180519+gitgf6f199be3-1~ndall+1 cmd:git=2.17.0 cmd:system-git=2.17.0 cmd:system-ssh=7.6p1 exifread=2.1.2 git=2.1.8 gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 msgpack=0.5.1 mutagen=1.40.0 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0 …
```
> remaining two tests to fail while using bleeding edge git-annex 6.20180519+gitgf6f199be3-1~ndall+1

- datalad/distribution/create.py
The rules below it do not say "add text files directly to git".
Closes #2466.
> DOC: Delete an incorrect comment from .datalad/.gitattributes

- datalad/support/annexrepo.py
> BF: centralize the check for "must be ran in a work tree" fatal msg from annex

- appveyor.yml
- datalad/cmdline/tests/test_main.py
- datalad/tests/utils.py
- datalad/utils.py
Summary after a long time:
This should be merged ASAP, because we are going backwards on windows and we are not aware of it.
All this does (besides few fixes) is do a basic installation on windows and run `wtf` to see if anything works.
Future changes should slowly introduce stuff that out to work to the
tests
----
and now the stuff from January....
With all the annotations of tests which fail in direct and v6 modes, may be it is feasible now to approach having testing done on windows as well, and I think appveyor would be a good free service for that purpose ;)  It could help to catch issues "spawning" from windows origins, such as the one reported in https://github.com/datalad/datalad/pull/2066
> provide basic appveyor setup

- appveyor.yml
That gives us the complete list of tests where all tests defined in a particular test module pass/skip on windows. We should make sure there is no regression, and expand the list.
Will cancel the Travis build as there are only changes to the appveyor config.
> TST+WIN: Enable more tests on Windows

- datalad/cmdline/main.py
This pull request fixes #2524
This pull request proposes to throw away (too) early failing when parsing cmdline arguments.
> BF: Don't fail too early when parsing cmdline arguments

- datalad/metadata/extractors/tests/test_base.py
(after actually testing the rest)
ATM There is PIL and libxmp failing to load on OSX test bot
and no quick resolution is in sight.  So to make it saner again
decided just to skip on OSX there
> BF(TST,workaround): allow extensions to fail to load on OSX and mark test skipped

- datalad/cmdline/main.py
argparse's abbreviation feature makes it impossible to add a subparser
long option that is a prefix of a long option from the top-level
parser.  For example, adding --report to a subparser would fail with
"datalad: error: ambiguous option: --report could match
--report-status, --report-type".
Thanks to @yarikoptic for realizing that the abbreviation feature was
the root issue.
Re: https://github.com/datalad/datalad/pull/2544#issuecomment-391563279
---
What do others think about this?  Do you think many people were using abbreviated options with datalad?  (I suppose if none of us knew about it, that'd say something.)  Are we comfortable overriding ArgumentParser's internal _get_option_tuples?
> ENH: cmdline: Disable abbreviations for long options

- datalad/support/json_py.py
> BF+ENH: delay import of lzma until used, informative mesage if undefined symbol: lzma_alone_encoder

- appveyor.yml
- datalad/__init__.py
- datalad/distribution/create_sibling.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_publish.py
- datalad/interface/tests/test_save.py
- datalad/metadata/tests/test_aggregation.py
- datalad/support/network.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
- datalad/utils.py
Biggest bits:
- Discontinue categorical refusal to do anything SSH-related on Windows
- Bunch of fixes that remove assumtions on POSIX-style path in various parts of the code/tests
- Disable a bunch of SSH-related tests on Windows that require a working SSH server on localhost, see #2559 for the path ahead
> Even more Windows tests

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
When a command is run in a dataset, the same run information is recorded in all subdatasets that have added/modified files.  Rerunning the command from a subdataset isn't supported, so check the dataset ID on rerun and, if it is different, skip or cherry pick the commit using the same logic that's used for non-run commits.
Closes #1799.
---
> ENH: run: Record dataset ID and check on rerun

- datalad/interface/base.py
- datalad/interface/download_url.py
- datalad/interface/tests/test_download_url.py
- datalad/support/annexrepo.py
* Convert `download_url` to use `eval_results`.
* Add the downloaded files to the dataset if invoked from a dataset or with `-d`.
For annex repos, this includes registering the URL.  Adding to the dataset can be disabled with `--nosave`.
* Add `--archive` flag indicates that to run `add_archive_content` on the downloaded files.
Closes #2123.
---
> ENH: download_url: Support adding downloaded file to dataset

- datalad/interface/run.py
Pass `sort_keys=True` to `json.dumps`, as intended.
Fixes #2581.
---
> BF: run: Sort keys in the run record

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
Fixes bug mentioned in  https://github.com/datalad/datalad/pull/2587#discussion_r191758806.
* Ensure that inputs and outputs are resolved correctly by `get` and `unlock`.  The issue arises when run is called from subdirectories because globbing for inputs and outputs is done relative to the pwd.
* Add helper class to deal with handling of inputs and outputs.
---
> BF: run: Fix handling of subdirectory inputs/outputs

- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_aggregation.py
This pull request fixes `aggregate-metadata` 's call to `get`, which was passing the wrong thing, resulting in not getting things and issueing a confusing warning instead ( see https://github.com/psychoinformatics-de/datalad-hirni/issues/9 for example), complaining about some `ds` git-annex couldn't find.
> BF: aggregate get metadata objects

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
This is useful when a command needs $PWD (e.g., mounting with
containers).  If it's hardcoded in the command, then that command
won't work reliably on different machines.  A more general approach is
to use a wrapper that resolves run-time values.  But many commands may
need $PWD, so let's add a placeholder to make a wrapper unnecessary in
this common, simple case.
Re: https://github.com/datalad/datalad-container/pull/35#issuecomment-393527318
---
> NF: run: Add a placeholder for the run's working directory

- datalad/support/archives.py
> BF(PY3): cannot provide bytes to patool as path since it would use its repr somewhere leading to b' prefix

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
This is working towards #2576, but
> ENH: `run` can store records in sidecar files

- datalad/interface/base.py
The module datalad/distribution/move.py was deleted in aaefa25d5 (RF:
Remove carcass, 2017-06-10).
---
> RF: Delete 'Move' from list of old-style commands

- datalad/utils.py
Discovered while building/testing for python3 on debian, with no locales installed and all LC_* pointing to C or POSIX.
For now many other problems will be concealed by not running tests with unicode strings for debian build.  Whenever automagics of python2 do some miracles, python3 logging etc just puke in various scenarios.  This one seemed to have a straight resolution
> BF(UTF8,PY3): pass utf-8 encoding to open while reading csv file

- datalad/downloaders/configs/crawdad.cfg
- datalad/downloaders/configs/crcns.cfg
- datalad/downloaders/configs/hcp.cfg
- datalad/downloaders/configs/kaggle.cfg
- datalad/downloaders/configs/nitrc.cfg
- datalad/downloaders/configs/openfmri.cfg
This pull request fixes unescaped dots in some regular expressions for URLs.
> BF: Escape dots in URL regular expressions

- datalad/metadata/metadata.py
- datalad/metadata/tests/test_base.py
I am not sure if that would be the best location but it is the location where info files are loaded (if present).
With message is for
- users who update to 0.10 while having only datasets with old aggregated metadata
- users who later fetch a dataset were metadata was agregated with newer version of datalad and no aggregated metadata present for their version of datalad
- users who do not exactly know yet the full workflow and that they need to aggregate it (I've heard already the question "but I've `git annex metadata` annotated it -- why search returns nothing?" a few times)
It could be more specific, but even without that it would be an improvement in comparison to just a silent exit.
> ENH: inform user that no aggregated metadata was found for the dataset during query

- setup.py
dependency was added in https://github.com/datalad/datalad/pull/1995 without us actually checking why it is needed... and AFAIK it shouldn't be (yet at least).  conda doesn't have it yet, so complicates packaging
> BF: no duecredit should be needed

- datalad/log.py
- datalad/metadata/metadata.py
- use iteritems not .items so stays generator for both PY2 and PY3.  I do not think that it would result in the major memory relief, but still worth using it this way
- while going through the code came to realization that all extractors manually repeat the progress logging, although whenever they are generators we could handle it centrally, thus added commented out log_progress pieces.  log messages aren't actually logged at all, I've tried to resolve it with https://github.com/yarikoptic/datalad/compare/opt-metadata...yarikoptic:opt-metadata-log?expand=1  but then it doesn't look good anyways in case of nested progresses (embedded one would print final message thus ruining the progressbar for the above), so better to leave as is
This one should be safe, so next aggregation attempt will …
> minor OPT: metadata + logging during (commented out)

- datalad/interface/tests/test_download_url.py
This pull request should fix FTBFS on 14.04
> BF(TST): do not require url in the error message if proxy is the reason

- datalad/cmdline/main.py
- datalad/distribution/tests/test_create.py
- datalad/interface/base.py
- datalad/interface/common_opts.py
- datalad/interface/run_procedure.py
- datalad/interface/tests/test_base.py
- datalad/interface/tests/test_run_procedure.py
- datalad/interface/utils.py
- datalad/plugin/tests/test_plugins.py
ATM:
```
usage: datalad
[--run-before <PROCEDURE NAME> [ARGS ...]]
[--run-after <PROCEDURE NAME> [ARGS ...]] [--cmd]
command [command-opts]
```
However, those names confuse me. `--run-after` is supposed to mean "run this after the command you are mainly executing", and `--run-before` run this before that command. But given that the primary command is the main subject, one could easily get it the other way round. `--run-after` "run the command after you ran this.
I think we need to changes this NOW. Proposal:
- `--prepare <PROCEDURE NAME> [ARGS ...]]`
- `--fixup <PROCEDURE NAME> [ARGS ...]]`
What do you think? Better names, or even better ones on you mind?
> Naming question

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
Don't show the full record when the sidecar argument is unspecified
and datalad.run.record-sidecar is true.
---
> BF: run: Make dumped message honor datalad.run.record-sidecar

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
Lots of processing happens with running code that needs to output into the dataset that `run` is invoked on. Having a dedicated placeholder for the (absolute) path (like pwd) of this dataset would help to  make run records more portable.
> Support {dspath} as additional placeholder for `run`

- .travis.yml
- CONTRIBUTING.md
- datalad/log.py
- datalad/tests/test_log.py
To chase which steps take lots of RAM... for that to work there should be log messages interspersed around the functions in question
> NF: DATALAD_LOG_VMEM  borrowed from pymvpa logger

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
This PR add the `--explicit` flag discussed in #2593.
---
https://github.com/datalad/datalad/blob/e1a58b001c5378eea3f32d3abd8fea8d32c9b241/datalad/interface/run.py#L382-L384
> run: Add --explicit flag

- datalad/downloaders/providers.py
- datalad/downloaders/tests/test_providers.py
This adds support for loading config for providers from places
other than those configs that are distributed with the datalad
distribution. In particular, it adds support for:
- dataset/.datalad/providers/
- $HOME/.config/datalad/providers/
- $HOME/.datalad/providers/
- /etc/datalad/providers/
I'm not sure if this is the most idiomatic way to do this in the datalad codebase or if there's a more centralized location, but it seems to work.
(I also cleaned up the English in the function comment and clarified it slightly.)
> Add support for loading provider configs from other locations

- datalad/downloaders/base.py
- datalad/downloaders/tests/test_http.py
Otherwise, the download fails with an uninformative error message,
either
File <path> already exists
if overwrite is false or
Not a directory: '<path>/.datalad-download-temp' -> '<path>'
if overwrite is true.
Fixes #2652.
---
> ENH: downloaders: Abort earlier when there is no file name

- datalad/auto.py
- datalad/tests/test_auto.py
So with upload of 2.3.0 nibabel all unpatched datalad builds will start to fail, so we might need a minor release sooner than later now
> BF: auto -- also proxy os.stat call which is now used by nibabel while opening files

- datalad/downloaders/configs/loris.cfg
- datalad/downloaders/credentials.py
- datalad/downloaders/http.py
- datalad/downloaders/providers.py
- datalad/downloaders/tests/test_credentials.py
- datalad/downloaders/tests/test_http.py
- datalad/support/third/loris_token_generator.py
> ENH: ad-hoc Bearer token authentication/session support for LORIS

- datalad/plugin/no_annex.py
- datalad/plugin/tests/test_plugins.py
I ran into this .gitattributes formatting bug using the no_annex plugin with a list of patterns.
```
* annex.backend=MD5E
**/.git* annex.largefiles=nothing
*.tsv annex.largefiles=nothing*.json annex.largefiles=nothing*.bvec annex.largefiles=nothing*.bval annex.largefiles=nothingREADME annex.largefiles=nothingCHANGES annex.largefiles=nothing.bidsignore annex.largefiles=nothing
```
It should be:
```
* annex.backend=MD5E
**/.git* annex.largefiles=nothing
*.tsv annex.largefiles=nothing
*.json annex.largefiles=nothing
*.bvec annex.largefiles=nothing
*.bval annex.largefiles=nothing
README annex.largefiles=nothing
CHANGES annex.largefiles=nothing
.bidsignore annex.largefiles=nothing
```
> BF: Fix missing .gitattributes newlines with no_annex plugin

- datalad/tests/test_base.py
Any target platform of ours (including Windows) can deal with paths that have forward-slashes as `os.path.sep`. That includes absolute paths with drive letters on Windows. They just have to use forward-slashes consistently and not mix and match back- and forward-slashes.
This  is just a test to verify that. But now we should move towards a consistent path handling. IMHO that requires two things:
1. stop using `os.path`, but use `posixpath` exclusively.
2. establish a layer (plus helper function) that converts any incoming path to a posix-like path, regardless of platform.
Here is a thing you are probably wondering about:
```python
>>> import posixpath
>>> p='C:/users/mike'
>>> posixpath.relpath(p, 'C:/users')
'mike'
>>> posixpath.relpath(p, 'C:/')
'users/mike'
```
> TST: Verify how much path flexibility Python has across platforms

- datalad/version.py
v0.10.0.dev1 < v0.10.0.rc3, which is the minimum required version for datalad-crawler.
I'm not entirely sure that this is the right way to fix it, but at least it lets me
install datalad-crawler against the master branch.
> Change version number so that datalad-crawler can be installed

- datalad/support/third/loris_token_generator.py
When a request is made with an incorrect username/password,
urllib.urlopen raises an HTTPError exception. Since datalad
is looking for AccessDeniedError exceptions in order to decide
whether to re-prompt for new credentials, it doesn't get caught
and there's no easy way to enter the correct credentials if
you don't get it right the first time.
This converts the implicit exception in LORIS token generator
to an AccessDeniedError.
> BF: Handle 401 errors from LORIS tokens

- datalad/interface/download_url.py
- datalad/interface/run.py
- datalad/interface/tests/test_download_url.py
- datalad/utils.py
If 'datalad download-url' is called (without -d) from a dataset's
subdirectory, the downloaded file should be stored within that
directory.  Similarly, a path specified with --path should be relative
to that directory.
Fixes #2676.
---
> BF: download_url: Download to current directory within dataset

- docs/source/config.rst
- docs/source/metadata.rst
I think we need to elaborate even more on what differs datalad metadata from git-annex metadata, but at least for now it would list pros/cons for git-annex and provide some usecases where people might want to use native one
> DOC: information on support of native git-annex metadata

- datalad/interface/run.py
'git commit -F.git/COMMIT_EDITMSG' works, but argparse expects a
space.
Fixes #2691.
> BF: run: Fix instructions for saving results after non-zero exit

- datalad/cmd.py
- datalad/cmdline/main.py
Under bash, this changes
```bash
%> datalad run ls doesntexist
[INFO   ] == Command start (output follows) =====
ls: cannot access 'doesntexist': No such file or directory
[INFO   ] == Command exit (modification check follows) =====
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -r -F.git/COMMIT_EDITMSG .'
Failed to run 'ls doesntexist' under '/tmp/dl/err'. Exit code=2. out= err=%>
```
to
```bash
%> datalad run ls doesntexist
[INFO   ] == Command start (output follows) =====
ls: cannot access 'doesntexist': No such file or directory
[INFO   ] == Command exit (modification check follows) =====
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -r …
```
> Improve CommandError rendering (particularly under 'datalad run')

- datalad/distribution/drop.py
- datalad/distribution/remove.py
- datalad/distribution/uninstall.py
Fix typos, reword, and cut arguably redundant information.  Also, drop
the mention of recursion limits because, unlike 'datalad drop',
'datalad remove' doesn't have a --recursion-limit flag.
> DOC: Revise remove's top-level description

- datalad/interface/tests/test_add_archive_content.py
- datalad/support/archives.py
- datalad/tests/test_archives.py
- Make `compress_files` work with zip files so that `with_tree` can create zip files and we can add a regression test for gh-2695.
- Fix a PY3-specific failure that occurs when `decompress_file` (and thus `add_archive_content`) is called on zip files.
Fixes #2695.
> BF: archives: Fix zip (PY2/PY3) and unzip (PY3)

- datalad/__init__.py
- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
- datalad/plugin/wtf.py
- datalad/utils.py
This pull request fixes #2643 , fixed #2700 
Ah, also while troubleshooting that git-annex compatibility issue, added to WTF output the maximal filename length in current path (yes - it just creates a bunch of files until it can't, might take awhile if on the floppy)
> BFs (workarounds) for Windows: untaint DataLadRIs, use getcwd for PWD

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
```
We fail to parse combined short options (e.g., 'datalad -ar') and
short option/value pairs with no space (e.g., 'datalad -l1 ...) as of
be49a95dd (ENH: cmdline: Disable abbreviations for long options,
2018-05-24).  That commit overrides _get_option_tuples so that it
unconditionally returns an empty list.  Unfortunately, in addition to
disabling abbreviations, that swallows combined short options.
Instead, perform the same check that ArgumentParser._get_option_tuples
does to distinguish long flags from combined short options, and only
return an empty list in the long flag case.
```
Fixes #2709.
> BF: cmdline: Restore handling of short options

- datalad/cmdline/common_args.py
- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
if user asks for `--version` I think we should just output the version. Similar behavior of the mighty git:
```shell
~datalad/datalad > git --version              
git version 2.18.0
~datalad/datalad > datalad --version
datalad 0.10.2.dev38
```
that makes it easier to cut/paste output from terminal without needing to strip stuff
> RF: show only the version, without license, upon --version

- datalad/plugin/export_archive.py
- datalad/plugin/export_to_figshare.py
- datalad/plugin/tests/test_export_archive.py
Done by allowing export-archive --filename=directorypath/ so we could
point to the directory where the tarball could be located
> ENH+BF: make it possible to export_to_figshare without cd'ing

- datalad/__init__.py
- datalad/api.py
- datalad/cmdline/main.py
- datalad/interface/base.py
This pull request closes #2718.
---
> DOC: Add command summaries to datalad.api.__doc__

- datalad/ui/__init__.py
- datalad/ui/dialog.py
- datalad/ui/progressbars.py
- datalad/ui/tests/test_base.py
- datalad/ui/tests/test_dialog.py
- datalad/utils.py
This pull request fixes #2719 
- it will not display any progress bars if ran under `ipython console` (still would work under regular `ipython` terminal) and we have no way to differentiate.
> Improve support of IPython

- datalad/interface/__init__.py
- datalad/plugin/tests/test_plugins.py
- datalad/plugin/wtf.py
The report now looks different, but is much easier to extend and work with. Besides the default human-focused rendering, our common infrastructure can also return JSON, so the output of `wtf` can now
be worked with programmatically.
Moreover, version info has been added to the extension report (gh-2734), and versions are now also reported for metadata extractors (although none of them have any yet).
Here is an example report with the default rendering (which is now in simplistic markdown):
- path: /tmp/mikey
- alias.co: checkout
- alias.glog: log --pretty=format:'%h %ad %s (%an)' --date=short --graph
- alias.st: status
- alias.wdiff: diff --color-words
- alias.wshow: show --color-words
- annex.backends: MD5E
- annex.uuid: 2400a411-ee6a-4332-b60d-af931a851496
- annex.version: 5
- …
> ENH: wtf returns structured data (fixes gh-2415, gh-2734)

- .travis.yml
The grunt tests are now consistently failing (gh-2742).  Comparing a
recently passing Travis log to the failing ones shows that the
grunt-contrib-qunit version has changed from 2.0.0 to 3.0.0.  Assuming
that this change triggered the failure, let's pin grunt-contrib-qunit
at the old version until someone provides a proper fix.
---
This is a shot in the dark.  Let's see if the tests pass.
> TST: travis: Pin grunt-contrib-qunit

- datalad/cmdline/main.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
This PR implements a number of changes for the `egrep` default search mode that should make it substantially more useful, without putting too much strain on novice users.
> NF: Field-selective search in egrep mode (fixes gh-2337)

- datalad/distribution/create.py
- datalad/plugin/no_annex.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
This pull request will fix #2743
> Improved gitattribute handling

- datalad/support/gitrepo.py
Not a proper deprecation, because we have not a single one in the code base. Feel free to make it nice.
> BF: Recreate old GitRepo.get_git_attributes() to keep old folks going

- datalad/metadata/metadata.py
Became evident in https://github.com/datalad/datalad-neuroimaging/pull/41 and was captured by its tests.
Needed to make #2753 work.
> BF: Unique value hashing could not deal with lists as values

- datalad/interface/rerun.py
- datalad/interface/tests/test_run.py
```
There are two cases where we can end up with an empty list of
results: (1) the user specifies --since='' but there are no run
commits in REVISION's history and (2) the user specifies a range
A..B (i.e., --since=A B) that doesn't have any commits.
In most cases, the downstream code will process an empty result list
fine, but, if --onto is specified, we'll fail with an index error.
Abort if we encounter an empty list to prevent the index error as well
as provide more useful feedback to the user.
```
> BF: rerun: Guard against empty result list

- datalad/interface/base.py
- datalad/interface/tests/test_base.py
Since this one might controversial and still needs tests, filing it separately from #2724:
- shortened access syntax item moved the other into a separate issue https://github.com/datalad/datalad/issues/2760
> ENH: report absent fields reported as N/A in output instead of not rendering the record at all

- datalad/support/annexrepo.py
- datalad/ui/progressbars.py
This pull request fixes https://github.com/datalad/datalad-container/issues/49
- It got even messier in there, and ideally requires some fixups on git-annex side: http://git-annex.branchable.com/todo/provide___39__file__39___in_--json-progress_record_for_addurl/
- I also disabled Total progress bar if we expect only one .  hopefully I didn't ruin something great ;-)
I guess would require manual testdriving since it is UI which we might not test very thoroughly automatically.  But on my attempts seems to be quite kosher.
> ENH progressbars for addurl

- datalad/distribution/add.py
- datalad/interface/save.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
So far this is just the result of killing some time on a flight:
After staring at the code for a while I think we should RF to make `save` use `add` and not vice versa. That should compact the code quite a bit, and make the presently observable differences in behavior go away.
> Towards add/save sanity

- .travis.yml
With Sphinx v1.7.7, Travis runs are currently failing with
/home/travis/build/datalad/datalad/docs/source/generated/cfginfo/dataset.rst:document isn't included in any toctree
This appears to be a spurious warning rather than a real issue
uncovered by the newer Sphinx.  Pin Sphinx to the previous version
until the issue is resolved.
Re: #2774
> TST: travis: Pin Sphinx to v1.7.6

- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_install.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_run.py
Should pass on that run (temporarily enabled) where we use devel annex and now test on v6
> WIP: Removing some "failing in v6" tests

- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_create_test_dataset.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_uninstall.py
- datalad/interface/tests/test_download_url.py
- datalad/interface/tests/test_run.py
- datalad/metadata/extractors/tests/test_base.py
- datalad/metadata/tests/test_aggregation.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
- datalad/plugin/export_archive.py
- datalad/plugin/tests/test_plugins.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
Disclaimer - sits on top of #2724 which I intend to merge if tests pass
This pull request fixes # ... TODO ... there might be a few
- if any is not staged - we puke
- if some staged aren't among `file(s)` - we prepare a new index file, where we reset those which aren't to be committed
- **gotcha/shortcoming** if there is a modified file, which is staged but in some previous shape (so there are newer changes in worktree), they would not get committed.  We could have analyzed index regarding either staged version is annexified or git - and then do `git add` or `git annex add` accordingly, but not sure if worth the hassle ATM.  At least this fix/behavior would get us those 95% of correct functionality in direct mode ;)
- This current "index" trick workaround could later be superseded by git …
> BFing direct mode:  "git commit file(s)" etc

- datalad/interface/tests/test_run.py
These pass following 98039ccf5 from gh-2770.
Note that gh-2782 reported that test_create_1test_dataset now passes
in direct mode, but this is because the test doesn't fail
consistently, not because it was fixed by gh-2770.
> TST: run: Unmark two tests as known direct mode failures

- datalad/downloaders/base.py
- datalad/downloaders/configs/crawdad.cfg
- datalad/downloaders/configs/providers.cfg
- datalad/downloaders/credentials.py
- datalad/downloaders/http.py
- datalad/downloaders/providers.py
- datalad/downloaders/s3.py
- datalad/downloaders/tests/test_http.py
- datalad/downloaders/tests/test_providers.py
- datalad/downloaders/tests/test_s3.py
- datalad/interface/ls.py
- datalad/support/exceptions.py
- datalad/support/s3.py
- datalad/tests/utils.py
- datalad/ui/base.py
- datalad/ui/dialog.py
- datalad/ui/tests/test_base.py
- datalad/ui/tests/test_dialog.py
> ENH+BF: S3 and downloaders: support anonymous access + interface to add new providers

- datalad/distribution/clone.py
- datalad/interface/results.py
- datalad/support/path.py
- datalad/support/tests/test_path.py
- datalad/utils.py
> ENH+BF: Do not fail reporting if curdir is gone, do not rmdir the directory upon failed clone attempt

- datalad/distribution/update.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
and later if/where needed guard other methods as well
This pull request fixes #2778
> RF(BF): @guard_BadName so we could guard every invocation of fetch

- datalad/interface/download_url.py
- datalad/interface/tests/test_download_url.py
```
Avoid the ugly "path/." and "path/./." that can happen when rel_pwd
and op.curdir are ".".
```
Closes #2802.
> ENH: download_url: Normalize reported destination path 

- datalad/distribution/tests/test_add.py
- datalad/interface/utils.py
```
Under Python 2, running the new test---where OBSCURE_FILENAME is in
the top-level rather than a subdirectory---will trigger the following
warning:
[...]/interface/utils.py:222: UnicodeWarning: Unicode equal
comparison failed to convert both arguments to Unicode -
interpreting them as being unequal
if p in targetpaths:
This happens because os.listdir returns a list of bytestrings on
Python 2, but targetpaths is a list of unicode strings.
(discover_dataset_trace_to_targets has three callers, add.py, save.py,
and aggregate.py, and they all pass a list of unicode strings for
targetpaths.)
```
This pull request fixes the issue mentioned in 48d3b09d7 (TST: run: Extend test_inputs_spaces with OBSCURE_FILENAME, 2018-09-07).
> BF(py2): Fix unicode/bytestring mismatch

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
```
Our processing of inputs and outputs is broken for paths with
spaces.  Take the inputs "foo blah.txt" and "bar.txt", and the run
$ datalad run --input="a" --input="b c" CMD
If CMD is a string (e.g., "./script {inputs}"), then the formatted run
command is ultimately "./script a b c" rather than "./script a 'b c'"
because the individual inputs aren't quoted.
On the other hand, if CMD is a list (no quotes), the list is first
converted to the string form of "./script '{inputs}'" (see 9c3a65e3d)
and ultimately "./script 'a b c'".
Quote each input and output so that paths with spaces work with the
string form.  This won't work with the list form because {inputs} is
surrounded by quotes, but at least one form will work reliably.
```
Note: This has a trivial merge conflict with #2796.
> BF: run: Escape each input/output before formatting command string

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
```
In order to resolve globbed paths within a subdataset, the subdataset
needs to be installed.  To do so, use the following procedure: install
the subdirectories returned by the longest *matched* pattern and then
glob again, stopping when no new paths are globbed.
[...]
```
This pull request fixes #2789.
>  BF: run: Support globbing in uninstalled datasets

- datalad/__init__.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_dataset.py
- datalad/interface/diff.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_diff.py
- datalad/interface/tests/test_ls_webui.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_run_procedure.py
- datalad/interface/tests/test_save.py
- datalad/support/cookies.py
- datalad/support/locking.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_path.py
- datalad/tests/test_auto.py
- datalad/tests/test_log.py
- datalad/tests/test_utils.py
- datalad/tests/utils.py
- datalad/utils.py
This is absorbed from #2791 which keeps running all the tests under windows.
Notable change is that we should start using `@known_failure_windows` for the tests which potentially should work on Windows.
> BFs and RF (Windows): more precommits etc to avoid operation on held up files/directories

- CHANGELOG.md
There are still some missing entries or at least entries that should be consider (look for `?` below) or entries that have been added to some degree but may be incomplete (look for `+*` below).  Please add or tweak as you see fit.
```
#
#
---
-  Merge branch 'bf-py37'
db6bb0dd7^-1
+  Merge pull request #2692 from kyleam/bf-run-failmsg
3108eb90b^-1
-  Merge pull request #2686 from kyleam/enh-commanderror-rendering
64f6e5bca^-1
-  Bump Singularity container version
e6750ec7f^-1
-  Merge pull request #2697 from yarikoptic/enh-cleanup
cf78c1880^-1
-  Merge pull request #2674 from kyleam/doc-revise-remove
79df5a442^-1
+  Merge pull request #2702 from kyleam/bf-archive-zip
8540bb22e^-1
+  Merge pull request #2703 from kyleam/doc-run-cmd-str
b29581e7c^-1
+* Merge pull request #2707 from …
```
> CHANGELOG.md: Start adding entries for v0.10.3

- datalad/support/gitrepo.py
with git 2.19 there is no trailing period in "did not match any file(s)"
> BF: remove trailing period while matching a mesage from git

- datalad/cmdline/tests/test_main.py
- datalad/customremotes/tests/test_archives.py
- datalad/distribution/tests/test_clone.py
- datalad/distribution/tests/test_create.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/distribution/tests/test_get.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/tests/test_publish.py
- datalad/distribution/tests/test_uninstall.py
- datalad/distribution/tests/test_update.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_diff.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_unlock.py
This follows up on the remaining V6 failues listed in https://github.com/datalad/datalad/pull/2782#issuecomment-417763061
The only remaining one is
https://github.com/datalad/datalad/blob/e8dfb0fdadbe16f24f381b963153e06831e7a4ac/datalad/support/tests/test_annexrepo.py#L1689-L1691
---
Yes, but we should wait for the latest git-annex to be uploaded to neurodebian (~released and bump our dependency~ --- not necessary the issues are limited to v6).
> TST: Remove more @known_failure_v6

- datalad/support/gitrepo.py
Lazy loading of `GitRepo.repo` may lead to instantiate GitPython's `Repo` class on destruction of `GitRepo`.
> BF: Don't trigger instantiation of git.Repo in __del__

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
Reported in https://github.com/datalad/datalad/issues/2839
Local disk space might be "unknown" so we must not blindly
convert it to int.  I wondered if we should keep original value
("unknown") but because in other place we already get it as None
by default, I thought that it would be better just to log at debug
and assign a None
This pull request fixes #2839
> BF: annex_info - be robust to "unknown" size

- CHANGELOG.md
- CONTRIBUTORS
- datalad/consts.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/interface/common_cfg.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
- datalad/support/network.py
- docs/source/basics.rst
This pull request will close https://github.com/datalad/datalad/issues/2792 by adding a configuration value, `datasets.locations.local_central_path`
- **naming** I would have called it `superdataset_root` or similar, but to be consistent I named it equivalently to the current variable `LOCAL_CENTRAL_PATH` --> `datasets.locations.local_central_path`.
- **The path defined in confs.py might still be useful for testing.** I noticed that this default is set in the confs.py, and then used in testing. Since testing may be a different use case / invocation pathway than when it's actually being used, I left it here and didn't change the imports in testing. 
- **docs** my life was very easy! The change appeared there automatically :)
Please have a look @datalad/developers and thank you in advance …
> Adding config option to set superdataset root

- .travis.yml
- datalad/support/annexrepo.py
```
The referenced issue appears to be fixed by git-annex's 10138056d (v6:
avoid accidental conversion when annex.largefiles is not configured,
2018-08-27).
```
> CLN: annexrepo: Remove V6 workaround

- datalad/distribution/install.py
Otherwise  install -g  was not triggering parallel downloads.
Kudos to the problem solver @kyleam
> BF: install default value for jobs should be "auto" not None

- datalad/support/annexrepo.py
Discovered on Windows, see https://github.com/datalad/datalad/issues/2863 ,
where error message was suggesting just getting over the maximum filename
size, but it was not it.  Accounting with at least +3 resolved the issue.
Here we do more to account for all the rest to be even safer
Fixes #2863
> BF: account for possible decorations around filenames while chunking cmdline

- datalad/metadata/tests/test_aggregation.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
`AnnexRepo.{file_has_content,is_under_annex}` get confused on unlocked files in V6. In V5, both these functions return false for unlocked files (i.e. we don't trust that the content in the working tree that replaced the symlink is unmodified). In V6, being unlocked isn't necessarily a transient state and doesn't mean that the content isn't in annex/objects, so we need a different check. This PR changes the "return false for unlocked" bit of the check to a more specific "return false if the file has unstaged modifications" in V6. The focus is on **unstaged** changes because any staged files will have already had their content added to the annex.
Commits ad8525b18 and 5dc2eb495 are the ones that actually change the checks. Most of the others fix other issues in these methods (and their …
> BF: V6: Fix file_has_content and is_under_annex for unlocked files

- datalad/plugin/wtf.py
A parsed variant of `git annex version` output. Looks like this:
```
% datalad wtf
...
- build flags: 
- Assistant
- Webapp
- Pairing
- S3(multipartupload)(storageclasses)
- WebDAV
- Inotify
- DBus
- DesktopNotify
- ConcurrentOutput
- TorrentParser
- MagicMime
- Feeds
- Testsuite
- dependency versions: 
- aws-0.19
- bloomfilter-2.0.1.0
- cryptonite-0.25
- DAV-1.3.2
- feed-1.0.0.0
- ghc-8.2.2
- http-client-0.5.12
- persistent-sqlite-2.8.1.2
- torrent-10000.1.1
- uuid-1.3.13
- yesod-1.6.0
- key/value backends: 
- SHA256E
- SHA256
- SHA512E
- SHA512
- SHA224E
- SHA224
- SHA384E
- SHA384
- SHA3_256E
- SHA3_256
- SHA3_512E
- SHA3_512
- SHA3_224E
- SHA3_224
- SHA3_384E
- SHA3_384
- SKEIN256E
- SKEIN256
- SKEIN512E
- SKEIN512
- BLAKE2B256E
- BLAKE2B256
- BLAKE2B512E
- BLAKE2B512
- BLAKE2B160E
- …
```
> ENH: Report detailed info on git-annex in `wtf` (fixes gh-2854)

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_utils.py
- datalad/distribution/utils.py
- datalad/interface/clean.py
- datalad/metadata/search.py
- datalad/support/gitrepo.py
Previously in datalad.distribution.utils, but such base functionality
should no be scattered around to prevent needless reinvention.
Kept the function static to avoid any cost of Repo instantiation,
given that this is the main usage pattern ATM.
> RF: Move get_git_dir() into GitRepo

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
This pull request fixes a failure discovered in https://github.com/datalad/datalad-container. Test was failing in https://travis-ci.org/datalad/datalad-container/jobs/436153807, because `annex-addurl` didn't report progress in the JSON report. Therefore `ProcessAnnexProgressIndicators` set the reported percentage to default to an empty string, which was then casted to a `float`, yielding a `ValueError`.
Independently on why exactly `addurl` doesn't report it (seems to just take a while for the first report to contain a field "percent-progress"), WE are setting the default to an empty string and therefore have to be able to deal with that value in the function we pass it to.
This pull request proposes to just catch the `ValueError` and return `None` in …
> BF: Don't crash on no reported percentage

- datalad/support/gitrepo.py
```
merge-base accepts any commit-ish, so technically arguments passed to
get_merge_base's are tree-ishes, but 'treeishes' is a misleading name
because merge-base doesn't accept a tree object.  For example, try
$ git merge-base HEAD^{tree} HEAD~^{tree}
```
> DOC: gitrepo: Rename get_merge_base's treeishes parameter

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_save.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_repodates.py
This eliminates some of the GitPython API calls mentioned in #2879.
-   Eliminates nearly all `repo.git.rev_parse` calls through use and extension of `GitRepo.get_hexsha` and through new `GitRepo.commit_exists`. (ece522998 explains the remaining two.)
-   Removes all `repo.git.show` calls with use of new `GitRepo.format_commit`.
-   Removes all `repo.git_dir` uses.
-   Add `GitRepo.is_ancestor` and drops `repo.git.merge_base`.
---
-   [X] This change is complete
> First batch of GitPython pruning

- datalad/support/gitrepo.py
This should complete the fix in 15573223c5e765e0e711672166b6717b6ad0382f .
Apparently hasattr would also trigger property value computation, at least according
to this traceback I was receiving if using python3:
[INFO   ] Cloning http://datasets-dev.datalad.org/openfmri/ds000002 [1 other candidates] into '/tmp/ds000002'
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore
[INFO   ] Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/ds000002 (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
[INFO   ] Traceback (most recent call last):
[INFO   ]   File /home/yoh/proj/datalad/datalad-master/datalad/support/annexrepo.py, line 365, in __del__
[INFO   ]   File /home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py, line 870, in __del__ …
> BF: do not even check with hasattr, go straight for _repo

- datalad/distribution/add.py
- datalad/distribution/get.py
- datalad/distribution/utils.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
Essential verification check was only available in `add`
> RF: Centralize submodule addition logic in GitRepo

- datalad/plugin/wtf.py
Given the uncontroversial nature of the PR, I will merge this as soon as all tests turn green.
> BF: `wtf` should not crash when no annex is around (fixes gh-2917)

- datalad/distribution/update.py
Otherwise using
update --merge --reobtain-data
would puke
> BF: missing import for late used binding of .get

- datalad/interface/run_procedure.py
- datalad/interface/tests/test_run_procedure.py
Fixes and additions to `run-procedure`:
- `run-procedure` required the `-d` parameter to discover procedures within a dataset even if called from within the dataset. That's not intuitive and I changed that. When called from within a dataset it will use it (except when passing in sth else via `-d` of course).
- BF: files that are neither executable nor end with `.py` or `.sh` but are in a configured look up location for procedures caused the command to crash. Fixed that.
- procedures can now recursively be discovered in subdatasets as well. The uppermost has highest priority
- added two configs for procedures: `datalad.procedures.NAME.call-format` and `datalad.procedures.NAME.help`. The former replaces (if given) the default, which is based on discovered file type. This allows not only for …
> ENH+BF: run-procedure

- datalad/distribution/tests/test_subdataset.py
- datalad/interface/tests/test_ls_webui.py
- datalad/interface/tests/test_run_procedure.py
- datalad/support/annexrepo.py
Otherwise we end up in a confusing state where things like "git status" unexpectedly work in a direct mode repo.
Re: #2836
> BF: annexrepo: Restore core.bare setting if custom command fails

- datalad/interface/utils.py
- datalad/tests/utils.py
Their str() is the path in it native representation.
This also adjusts test helpers that previously showed a relatively
uninformative message ("not serializable") where str() might
give some useful indication what is actually contained..
> ENH: Make core reporting ready for paths as pathlib objects

- datalad/downloaders/providers.py
The last call to it was dropped in 3514063c7 (RF: more of configs for
providers/credentials, reading and some cruel testing, 2015-11-18).
> CLN: providers: Remove unused resolve_url_to_name()

- datalad/interface/run.py
- datalad/interface/run_procedure.py
This pull request fixes two minor issues.
1. `run` might be surprisingly silent for quite some time when `get` figures what inputs it needs to get. When I was using it on a dataset with a lot of DICOMS, I noticed it looks as if it was hanging until the actual downloads started. This time was even needed if the DICOMS were actually present, suggesting that it's probably annex just checking what it needs to get, only to conclude: nothing. So, I added a message on info level here
2. `run-procedure` didn't call `run` explicitly with `return_type='generator'`. This resulted in yielding and rendering the results from `run` only after everything was done. So the `get` for inputs is done before the execution of the procedure, but it's silent and yields the result only after the output of the …
> Minor improvements on run/run-procedure

- datalad/cmdline/main.py
This pull request fixes #2938 and prob. #1321
This pull request proposes to adapt `CommandError` rendering to use its overwritten `__str()__`
> BF: Render CommandError the way it's meant to be

- datalad/support/external_versions.py
- datalad/support/keyring_.py
This pull request fixes #2959
This is potentially to overcome a not yet reproduced
https://github.com/datalad/datalad/issues/2959
which came to life with 16.0.0 version of keyring.
And this change otherwise makes sense since we typically treat env vars
as overriding what is stored in configuration
> RF(BF): credential defined in environment vars takes precedence

- datalad/distribution/tests/test_install.py
I am not sure how it went unnoticed for weeks
- detected initially while running heudiconv tests which were skipped due to inability to get the data
This test should guarantee that our datasets.datalad.org performs at least somewhat correctly
> ENH(TST): test that we can install/get from datasets.datalad.org (or its -tests brother)

- datalad/metadata/extractors/annex.py
- datalad/metadata/extractors/tests/test_base.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
- Replaces #2950 with more native placement of key record
- adjusts `AnnexRepo.get_file_key` with explicit `batch=None` option to trigger batch mode of operation
cons: with this change (and as test fixups show) now all annexed files will get some metadata record within "annex" section.  Time will show if any notable impact on size/performance
> ENH: add annex key to the extracted "annex" metadata record

- datalad/__init__.py
- datalad/tests/test_tests_utils.py
- datalad/tests/test_utils.py
- datalad/tests/utils.py
- datalad/utils.py
This pull request might help to address  #2910 but in an odd ad-hoc ugly fashion.  See description in patch/code
If we decide to adopt this at least as a temporary stop-gap measure, then  TODOs
Testing locally with smth like
```shell
$> python -c 'import os; os.chdir("/tmp"); from datalad.utils import getpwd; print(getpwd(), os.getcwd())'
[WARNING] realpath of PWD=/home/yoh/proj/datalad/datalad-master is /home/yoh/proj/datalad/datalad-master whenever os.getcwd()=/tmp. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved 
('/tmp', '/tmp')
```
> BF(workaround): switch to use os.getcwd if something odd detected with PWD env var

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
Main changes:
-   New function `prepare_inputs` to help datalad-htcondor to avoid some duplicated code.
-   `format_command` now handles custom substitutions. This fixes `rerun --script` for commands that include substitutions and helps (a little bit) with code duplication in datalad-htcondor.
-   `run_command` accepts a new argument `extra_info` that allows arbitrary information to be added to the run record.
-   `run_command` accepts a new argument `inject` that means "take the current working tree state as the result of the command" (i.e., don't prepare inputs or outputs before the command and don't execute the command) (gh-2934).
---
@mih, will `inject=True` work for you wrt datalad-htcondor?
> ENH: run_command: Support injecting a detached command

- datalad/support/annexrepo.py
- datalad/utils.py
Originally discovered by reviewing current code while at 
https://github.com/datalad/datalad/issues/1883#issuecomment-435932579
> BF: correct location for ")" + RF: use os.sysconf('SC_ARG_MAX')

- datalad/interface/base.py
- datalad/metadata/search.py
Spotted odd docstring
```
--mode {egrep,textblob,autofield}
Mode of search index structure and content. See
section SEARCH MODES for details. . [Default: None]
```
> BF: rstrip before checking if trailing period is needed

- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
Surprisingly, I ran into it only within https://github.com/datalad/datalad/pull/2898
despite all our testing with symlinked `TMPDIR`s on travis.  This time I have added
a dedicated unittest to trigger that failure.
The rationale for using realpath there is because GitRepo already realpath"ing
the path to be able to return the singleton Repo for the same path
This pull request fixes #2961
> BF(TST): realpath path before figuring out which repo it belongs to

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- Don't treat `record-sidecar=false` as true
- Handle tuple return value from `ConfigManager`
> Fixes for run's sidecar config processing

- datalad/support/annexrepo.py
- datalad/utils.py
Hit it again with current master ... not sure if this would have resolved it but it should ;)
> BF: Assume 50% safety margin for max cmdline length

- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_aggregation.py
Otherwise it causes negative side effect in --recursive mode that it would start
recursing all subdatasets.
This issue was mentioned in
https://github.com/datalad/datalad/issues/2841
Aggregation of current dataset could always be forced by providing '.' or just not providing paths.
If this PR causes some ideological breakage, it is not visible since no tests seems to get broken.
> BF(RF?): do not aggregate dataset itself if paths for aggregation provided

- datalad/interface/run.py
This is admittedly a bit clunky. An alternative way of doing this would be to RF the `add()` call into the main command class, and have a helper method deal with it. In this scenario, it could simply be overwritten in a derived class, instead of having to introduce another argument. What would you prefer @kyleam?
Why is this needed? ATM `run` performs a hard-coded `add(recursive)`, and this adds the flexibility to tailor this behavior (non-recursive add, or more than just adding).
> RF: Allow for customization of change recording in `run`

- datalad/interface/rerun.py
- datalad/interface/tests/test_run.py
```
We check that the commit specified for --onto exists when we
automatically set onto in the --onto='' case.  We should do the same
when an --onto value is explicitly given because it may not exist,
which leads to 'git checkout' failing with an unclear message:
fatal: git checkout: --detach does not take a path argument '<onto value>'
```
Fixes #3019.
> BF: rerun: Widen "onto commit exists" check

- datalad/tests/test_version.py
Decided to do this way (from binary readout) so we try our best at conversion
when we reach that precious line
This pull request fixes #3024
> BF: assure unicode CHANGELOG lines while testing the version

- datalad/interface/download_url.py
- datalad/interface/tests/test_download_url.py
When a dataset isn't explicitly specified, download_url will try to
infer one from the current directory.  However, if save is False,
there's no reason to do so.  Trying to infer the dataset in these
situations generally won't hurt, but doing so may unnecessarily
fail in the save=False case if the current directory is something
that may cause issues when used as a dataset (e.g., a git
worktree).
Note: This was prompted by a download_url test failing when ran from a
worktree (gh-3028).  The most direct solution is to use chpwd() to get
to a non-dataset directory in the cases that we call
api.download_url(dataset=None), but that wouldn't help for callers
outside the test.  Another would be to catch the repository exception
around the require_dataset() call, but I've found that, when calling …
> TST+BF: download_url: Don't try to infer dataset if save=False

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
Prevent `os.path.relpath` from converting "./input" to "input".
Fixes  #3034.
> BF: run: Preserve current directory prefix for inputs/outputs

- datalad/support/annexrepo.py
This reverts commit f5d6a6f5cecb85ab6bee5d4fe11e09ec8555d3aa.
Apparently there is some bug, I guess in git-annex, which requires either a
sleep before the commit in the test, or to apply the same procedure as we
do in v5.  As a result it also changes the effect - files do get
committed locked (as regular symlinks).
Closes #3023
Someone could/should track the issue down to proper resolution, so this is not an ideal resolution.
> Revert "This (expensive) approach is not needed in v6+"

- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
```
To let run interface wrappers (like containers-run) specify inputs
without surprising users (who did not explicitly specify those
inputs), add an "extra_inputs" argument to run_command().  There's no
reason we couldn't add it to Run.__call__ along with a command-line
switch and format field, but let's avoid doing so exposing another
user-facing option until a clear use case arises.
```
Re: datalad/datalad-container#38
>  ENH: run: Support "extra inputs"

- datalad/cmd.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
- datalad/tests/test_cmd.py
This pull request supersedes gh-3033, fixing the py2 issue there as well as other py2 unicode issues in cmd.py and run.py.
---
@mih: One of the tests added (`test_run:test_py2_unicode_command`) triggers a case where the patch from #3031 (e3d2af7e6, RF: Do not force byte-encoding of commit message) fails under Python 2.
```
ERROR: datalad.interface.tests.test_run.test_py2_unicode_command
File "/home/kyle/src/python/venvs/datalad-py2/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 596, in newfunc
return …
```
> run: Resolve some py2 unicode issues

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
An attempt to address an [issue] raised by @bpoldrack:
> ATM we happily accept datalad.repo.version = 6, while silently creating a v7 repository. This is misleading. 
[issue]: https://github.com/datalad/datalad/issues/2969#issuecomment-441051936
> ENH: annexrepo: Inform users about repo version auto-upgrades

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
This reverts commit abed6efad890eb421b4548b45de2dfabb86565ba.
As of that commit, test_annex_ssh is stalling on Travis for unclear
reasons.  Revert those changes until we figure out why.
Closes #3041.
> Revert "ENH: annexrepo: Inform users about repo version auto-upgrades"

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
* Fix an issue not caught by #3035.
* Apply patch similar to @mih's #3031, but avoid py2-compatibility issue describe [here](https://github.com/datalad/datalad/pull/3035#issue-235069639).
> run: Round 2 of py2 unicode

- datalad/support/external_versions.py
- datalad/support/tests/test_external_versions.py
```
Because ExternalVersions.__contains__ checks the cached _versions
attribute, it will return False for an item that hasn't been seen by
__getitem__.  This is misleading for cases where the __getitem__
return value isn't None.  To fix this, adjust __contains__ to use
__getitem__ instead.
```
> BF: external_versions: Make __contains__ work with non-primed items

- datalad/interface/tests/test_run_procedure.py
- datalad/resources/procedures/setup_yoda_dataset.py
Similar to the cfg_text2git new line issue (gh-2954, fixed by
eed1cacee), setup_yoda_dataset creates a malformed attribute line:
**/.git* annex.largefiles=nothingREADME.md annex.largefiles=nothing
Use GitRepo.set_gitattributes() so that new lines are properly
handled.  Don't bother checking if the attribute exists since the
procedure is documented as assuming a just-create dataset.
---
I'm a bit unsure about the fix because I don't quite get what the path handling is about here:
https://github.com/datalad/datalad/blob/5f69cfe961f91c8add6bd15db5abde5757f3d969/datalad/resources/procedures/setup_yoda_dataset.py#L66-L67
<details>
<summary>script/demo</summary>
```shell
#!/bin/sh
set -eu
tmpdir=$(mktemp -d)
datalad --proc-post setup_yoda_dataset --cmd create -d $tmpdir
cd $tmpdir
git cat-file …
```
> BF: setup_yoda_dataset: Avoid conjoined lines

- datalad/interface/rerun.py
- datalad/interface/run.py
The unexpanded form can be pretty uninformative (e.g., "python {input}").
>  ENH: run: Use expanded command for commit summary

- datalad/interface/utils.py
Now each class could provide its own idea of how results can be summarized, and override the default action counter that is sometimes rather uninformative.
Instrumental in addressing situations like https://github.com/datalad/datalad-revolution/issues/56
Let's see if it breaks anything existing. Demo PR: https://github.com/datalad/datalad-revolution/pull/57
> ENH: Add the ability for custom result summary rendering

- datalad/interface/add_archive_content.py
- datalad/interface/tests/test_add_archive_content.py
- datalad/interface/tests/test_download_url.py
Otherwise the archive's absolute path is shown in the commit message.
> ENH: download_url: Pass add_archive_content a path relative to dataset

- datalad/tests/test_utils.py
- datalad/tests/utils.py
- datalad/utils.py
This PR would be needed to facilitate testing of crawling portals with pure .gz files, e.g. https://github.com/datalad/datalad/issues/1967
additional ref: https://github.com/datalad/datalad/issues/1967
> ENH: support of .gz in create_tree and ok_file_has_content + minor RF

- datalad/distribution/add.py
- datalad/distribution/tests/test_add.py
- datalad/interface/common_opts.py
- datalad/interface/run.py
- datalad/interface/save.py
- datalad/interface/tests/test_run.py
- datalad/interface/tests/test_save.py
* Minor improvments `save`s `--message-file` handling
* Update `add` to support `--message-file`
* Update `run`s failure instructions to use `datalad add` (closes #3072)
> run: Use 'datalad add' in failure instructions

- datalad/downloaders/base.py
- datalad/downloaders/tests/test_s3.py
If access is denied and the Authenticator's requires_authentication
and allows_anonymous attributes are both True, we can hit the case
where BaseDownloader.credential is None when _enter_credentials is
called with new_provider=False.
There is nothing to update in this case, so raise the download error.
Fixes #3090.
> BF: downloaders: Add guard against unset credential object

- datalad/cmdline/main.py
- datalad/cmdline/tests/test_main.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_search.py
- datalad/utils.py
Just kept hitting the situations where a key is mistyped and I get no results, and have no clue what went wrong - either there is no hits really or I mistyped something.  Now would look like
```shell
$> datalad -f '{path}' -c datalad.search.index-egrep-documenttype=files search --mode egrep paths:.*_rec-.* bids.subject.age:10 biids.subject.race:white du                                                                     
[INFO   ] No search hits, wrong query? See 'datalad search --show-keys name' for known keys and 'datalad search --help' on how to prepare your query. Following keys were not found in available metadata: bids.subject.age, biids.subject.race, paths.  Did you mean any of these?
|         bids.subject.race
|         bids.subject.scanage
|         bids.subject.sex
| …
```
> RF+ENH: if search resulted in no hits due to wrong keys used, log an INFO msg with suggestions

- datalad/distribution/create_sibling.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/downloaders/tests/test_http.py
- datalad/tests/test_cmd.py
- datalad/tests/utils.py
1.
ENH: create-sibling --group option
When needing to create a group shared remote sibling, we need to be able
to specify which group actually should it be (if directories setup does not
enforce it).
2.
BF+RF: @skip_ decorators must not be used on generator tests
Apparently some tests were simply not ran because decorated to be skipped,
but our decorators do not work nicely with those generatorfunctions tests,
so we must use them via their functional counterparts.
Ideally those @skip_ helpers should be refactored since there is a repeating
pattern and only the check is different.  But I kept it "minimal" for now,
and made them usable as functions within tests in such cases.
There might now be test failures detected where they are still not used
appropriately
> ENH+BF(TST): create-sibling --group option

- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
ATM `GitRepo.set_gitattributes` only can add lines to `.gitattributes`. Introducing a `mode` parameter to allow for rewriting the entire thing.
> ENH: Allow to replace .gitattributes entirely

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
The command is collected with argparse's REMAINDER.  In the context of
DataLad's command-line parsing, this usually works fine but (1) has a
known issue with parsing at least one special flag, --version, and (2)
doesn't allow the command to start with an option, which is a common
situation when using runscripts with container-run.  "--" can be used
in both these cases to explicitly tell argparse that the option is a
part of the command; we just need to remove it from the command list.
Fixes datalad/datalad-container#46.
Re: #3067
> ENH: run: Strip leading "--" to allow command disambiguation

- datalad/metadata/aggregate.py
- datalad/metadata/metadata.py
- datalad/metadata/search.py
- datalad/metadata/tests/test_aggregation.py
- datalad/metadata/tests/test_base.py
...which even comes with a docstring.
Pave the way for a future support of a different aggregate metadata layout.
Ping #3110 
The only failure is a crawler test that depended on private info which is now no longer available. The Crawler PR is https://github.com/datalad/datalad-crawler/pull/31, which of course cannot run cleanly until this PR is merged (no need to keep transition code in tests IMHO).
Will merge this ASAP.
Well, as stated in https://github.com/datalad/datalad/issues/3112 a quick merge will not help to resolve this without a release of -crawler. Hence I'll keep working on this (semi-ignoring crawler for now), and either merge when its done, or when a crawler release is imminent.
> RF: Consolidate various aggregate metadata accessors into a single function

- datalad/interface/common_cfg.py
We have discussed it before, and decided to place small files directly under git.
But I was thinking about it and converging on placing all metadata under annex
control, so there is a better control over availability: we might need to remove
leaked sensitive metadata.
What do you think?
Not sure yet if any unittest would be effected
> RF: place all extracted metadata under git-annex

- datalad/distribution/tests/test_create_sibling.py
- datalad/interface/tests/test_run_procedure.py
- datalad/plugin/wtf.py
Based on local testing, three tests fail with an
InvalidGitRepositoryError when executed from within a git worktree of
the codebase: test_create_sibling.test_invalid_call,
test_run_procedure.test_invalid_call (gh-3052), and
test_run_procedure.test_procedure_discovery.
Avoid these errors by switching to a temporary, non-repo directory
before running the tests.
Re: #3029
Fixes #3052.
---
The last commit adjusts Travis so that the tests are executed from a worktree.  This is intended as a temporary check for additional failures because I don't think it's worth adding another dedicated Travis run to check for worktree testing issues.
> TST: Work around some worktree-related failures

- datalad/metadata/extractors/annex.py
It might be more useful to execute `precommit()` on a higher level, maybe at the end of aggregation...
> BF: Prevent issue with dangling batch processes

- appveyor.yml
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
Before now we were doing that only in _run_annex_command_json but the problem is present also for other commands (e.g. add) which do not use --json mode of annex, or are pure git commands (e.g. git add). _run_command_files_split(func, files, ...) helper would invoke func multiple times on batches of files, and code is refactored to use it for annex and git commands invocations.  I might have missed additional places where it should be used.                                        
Also I am not sure if it would not interfer with custom index file, and most likely would cause multiple commits instead of a single one for commit calls. But imho it would already be better than just crashing
This pull request fixes #1883
> BF/RF: Centrlize handling running commands with long files list in _run_command_files_split

- datalad/cmd.py
- datalad/distribution/tests/test_create_sibling.py
- datalad/support/gitrepo.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
This is mainly for the benefit of the ReproMan project.  There we are managing SSH resources that the user may not have configured in .ssh/config, so we need to call `create-sibling` with an SSH URL that includes port.  Without these changes, doing that results in an error like
```
stderr: 'fatal: ssh variant 'simple' does not support setting port' [cmd.py:wait:415] (GitCommandError)
```
Just for reference, here is the ssh.variant part of `man git-config`:
```
ssh.variant
By default, Git determines the command line arguments to use based on the basename of the configured SSH
command (configured using the environment variable GIT_SSH or GIT_SSH_COMMAND or the config setting
core.sshCommand). If the basename is unrecognized, Git will attempt to detect support of OpenSSH options
by first …
```
> SSH: Support URLs with ports

- datalad/support/tests/test_gitrepo.py
- datalad/tests/test_protocols.py
protocols.py distinguishes between external commands and callables.
To test the "callable" case, we create a GitRepo, assuming that this
will lead to gitpy.Repo.init() being executed through the runner.
This is problematic because it depends on internal details of GitRepo
and a reader has to dig into the GitRepo class to understand why we
expect a callable to be used.
And with -revolution, those internal details change. RevolutionGitRepo
overrides _create_empty_repo() and uses the external command 'git
init' as of 8b9d65a (ENH: Expose git-init options, create without
GitPython, 2018-10-29).  As a result, these protocol tests fail if we
substitute RevolutionGitRepo for GitRepo.
Use os.mkdir as the callable to simplify these tests and prepare for
the absorption of RevolutionGitRepo into …
> TST: protocols: Don't assume GitRepo runs a callable

- datalad/distribution/clone.py
- datalad/distribution/create.py
- datalad/distribution/dataset.py
- datalad/distribution/publish.py
- datalad/distribution/subdatasets.py
- datalad/distribution/tests/test_dataset.py
- datalad/distribution/tests/test_dataset_api.py
- datalad/distribution/tests/test_install.py
- datalad/distribution/uninstall.py
- datalad/distribution/update.py
- datalad/interface/annotate_paths.py
- datalad/interface/base.py
- datalad/interface/download_url.py
- datalad/interface/ls.py
- datalad/interface/rerun.py
- datalad/interface/run.py
- datalad/interface/run_procedure.py
- datalad/interface/tests/test_ls_webui.py
- datalad/interface/tests/test_run_procedure.py
- datalad/interface/tests/test_utils.py
- datalad/metadata/aggregate.py
- datalad/metadata/tests/test_aggregation.py
- datalad/metadata/tests/test_base.py
- datalad/metadata/tests/test_search.py
- datalad/plugin/add_readme.py
- datalad/resources/procedures/cfg_metadatatypes.py
- datalad/resources/procedures/cfg_text2git.py
- datalad/resources/procedures/setup_yoda_dataset.py
> BF/RF: automatically import needed interface submodules if Dataset.datasetmethod is not bound yet

- datalad/utils.py
it returns 2**62 number when running the package build.
Closes #3150
> BF(PY3): workaround for python3.4 on debian returning obnoxious SC_ARG_MAX

- datalad/distribution/tests/test_install.py
This makes all the appveyor runs a useless red mark - hiding away possibly new
bugs we would introduce.  So, I think it is better to disable that test on
appveyor for now
This is a temporary workaround for #3130
> BF: Stop running that failing test on appveyor - needs fix in git-annex

- datalad/interface/ls.py
- datalad/support/annexrepo.py
- datalad/support/exceptions.py
- datalad/support/tests/test_annexrepo.py
git-annex will try to merge remote's git-annex branches pretty much for any command which could potentially benefit from updated availability information present in those updated remote git-annex
branches.  But if that fails, the whole call fails, even if what we are asking does not require updated remote information.  Original whining/analysis+response from @joeyh is a year old and is at https://git-annex.branchable.com/bugs/impossible_to_perform___34__read-only__34___git_annex_info_without_write_permissions/
Use cases where we ran into it already:
-  `datalad ls -L`  of a dataset owned by someone else
-  `datalad get files`   whenever files load is already there but partition
is not writeable (singularity image, see https://github.com/poldracklab/fmriprep/issues/1500#issuecomment-4633845 …
> BF: set annex.merge-annex-branches=false for invocations not requiring updated remote information

- datalad/interface/common_cfg.py
- datalad/support/sshconnector.py
- datalad/support/sshrun.py
- datalad/support/tests/test_sshconnector.py
This enables callers to use sshrun with non-standard identity files.
For example, in the ReproMan project, we want to use DataLad commands
with an AWS EC2 instance.  In this case, the host will not be in
.ssh/config, and the key files are usually not in the default
location.
> ENH: ssh: Support specifying identity file via environment variable

- datalad/support/sshconnector.py
- datalad/support/tests/test_sshconnector.py
```
This reverts and replaces the sshconnector.py changes from
93c86517b (ENH: ssh: Support configuring an identity file,
2019-02-07).
93c86517b updated assure_initialized() to get datalad.ssh.identityfile
from its local ConfigManager instance and store that value as an
attribute for later use.  The motivation for retrieving the value in
assure_initialized() was to avoid the expense of calling
datalad.cfg.reload(force=True) with each get_connection() call.  In
turn, the motivation for using reload(force=True) was to prevent
test_ssh_custom_identity_file's patched DATALAD_SSH_IDENTITYFILE from
leaking into other tests [*].
The problem with this approach is that Python callers must set the
identity file before the first assure_initialized() call---which could
happen in …
```
> ENH: sshconnector: Get identity file with datalad.cfg.get()

- datalad/support/tests/test_annexrepo.py
While building for Debian test errored out because there were no sudo and
exception was IOError
> BF(TST): skip if windows OR root; catch any exception

- datalad/distribution/tests/test_install.py
This reverts commit 076c6a05d48a91f944c2b3842a1249671541c433.
since presumably was fixed in git-annex
see https://github.com/datalad/datalad/issues/3130 and http://git-annex.branchable.com/bugs/windows_support_totally_bitrotted/#comment-2bf69c9e5095ba74727cd1892c2d2f66
> Revert "BF(TMP): declare check_datasets_datalad_org failing on windows"

- datalad/support/archives.py
- datalad/tests/test_archives.py
- datalad/tests/test_cmd.py
It is an incomplete fix, which would still cause test failure in the crawler if no p7zip is installed in crawler due to  https://github.com/datalad/datalad/issues/3175 , but wanted to see if anything breaks here before proceeding further
> BF: fix execution of patool commands

- datalad/support/annexrepo.py
Write the temporary index file under the git directory to ensure that
the it resides on the same file system as the main index file.  See
the description of `--index-output` in `git-read-tree`s manpage.
Fixes #3181.
---
I've tested on smaug and confirmed that this patch fixes the following sequence:
```
$ echo one >one
$ git add one
$ echo two >two
$ datalad add two
```
> BF: annexrepo: Create temporary index under .git/

- datalad/metadata/aggregate.py
- datalad/metadata/metadata.py
This is an incomplete attempt to tackle the actual problem (the depth of the code stack this warning is issued at, such that it is out of touch with the calling context). But it should mitigate the issue for two
superficial scenarios.
> BF: Add switch to avoid pointless warnings (fixes gh-3185)

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/utils.py
- setup.py
I'm proposing this as the initial phase of bringing in changes from datalad-revolution.  While it's still not clear how (or even if) each -revolution interface module will be integrated or adopted in core, we're at a point where we can drop in -revolution's GitRepo, AnnexRepo, and Dataset without an issue.  And on -revolution's side, these classes should be in a stable state, so moving them to core shouldn't be problematic or slow development.
Note that this PR doesn't prevent or make it harder for us to follow the vision from #2926 and #3076 of incorporating all or at least nearly all of -revolution in the core codebase.
To bring in the changes, I took the approach of simply copying over the -revolution methods into the parent classes.  Doing it this way---rather than copying over the …
> RF: Absorb revolution's gitrepo, annexrepo, and dataset

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/support/gitrepo.py
- datalad/utils.py
> Small improvements re Dataset/*Repo handling

- CHANGELOG.md
- datalad/version.py
I see no point of adding tons of changelog entries for individual
pre-releases (not even a real RC yet). Instead, I started an 0.12.0 entry
so we can fill it up with what is to come.
I would have preferred to call this 0.12.0pre1, but setuptools insists
on "normalizing" the version to 0.12.0rc1 -- so we better use that right
away.
Once this gets a GO, I will merge it, push a tag (I don't see the need to pollute github releases, so I'll skip that), upload to pypi, point -revolution to use it as a dependency, and be done.
> Prepare for first preview release of 0.12 series

- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
> BF: Repo.dirty will not report on nested empty datasets (fixes gh-3196)

- datalad/support/third/loris_token_generator.py
The HTTPResponse object returned by urlopen under Python3 is not
compatible with json.load(!) because read() returns bytes, while json.load
is a thin wrapper around json.loads (which expects a str). This stores
the response as a str in a temporary variable and converts it to a string,
before calling json.loads directly to prevent a type error when used under
Python3 while trying to authenticate against a LORIS instance.
> BF: Fix LORIS token authenticator type with Python3

- CHANGELOG.md
- CONTRIBUTING.md
- datalad/tests/test_version.py
Post release commit must introduce a placeholder for the next Changelog entry
and adjust CONTRIBUTING.md to match the after next one so it could be simply
copy pasted next time
This pull should fix currently failing in master `test_version.py`
> BF: Fixing for the needed post-release dance with Changelog

- datalad/downloaders/base.py
When annexificator is used in a datalad-crawler pipeline, it attempts
to call get_status on the URL to see if the file has changed. get_status
attempts to use _fetch, which attempts to decode the content under Python3.
This is invalid for content that isn't utf-8, and get_status was only
trying to verify that it wasn't receiving a login or failure page or similar.
_fetch, confusingly, converts the UnicodeFormatError into a generic DownloadError
(despite the fact that the download succeeded, but conversion to a string failed.)
This teaches _fetch a "decode" parameter that toggles whether or not it should
even attempt to decode. In the case of get_status, the content is discarded,
so the decode serves no purpose as far as I can tell.
NB. fetch (without the _)'s documentation claims that it …
> Do not decode fetched content when retrieving status

- .travis.yml
```
All of the extension runs use 'NOSE_SELECTION_OP=' and
'NOSE_SELECTION="integration or usecase or slow"', restricting the
runs to tests _with_ these attributes.  This presumably wasn't the
intention because it results in very limited runs.  For example, the
crawler run executes only three tests [0].
Adjust NOSE_SELECTION_OP and NOSE_SELECTION for each extension run so
that all tests are executed.
[0]: https://travis-ci.org/datalad/datalad/jobs/503126961
```
> TST: travis: Widen selector for extension runs

- datalad/distribution/tests/test_dataset.py
- datalad/support/exceptions.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
This pull request should prevent such problematic situations as it was revealed in https://github.com/datalad/datalad/issues/3068#issuecomment-470549719 from occurring. 
This situation was probably also the origin for the situation which inspired https://github.com/datalad/datalad/issues/3139, although in that report I have come up with a minimal use case (empty git subrepo) which might have actually be a different problem.
Merge into master would conflict, and it might (or not) be wiser to just use `get_content_info` which is provided in there instead of a custom call to `ls-files`
> ENH: prevent users to create a repo in a subdir with files known to git above

- .travis.yml
a02e6da88 (TST: travis: Widen selector for extension runs, 2019-03-08)
fixed the nose selectors for the extension runs.  This included the
-revolution run, which was running only a small subset of the tests.
62164a3a7 disables the -revolution run entirely on the 0.11.x branch,
though, because -revolution requires 0.12.x.  Re-enable the
-revolution run on master.
> TST: travis: Uncomment widened revolution tests on master

- .travis.yml
- datalad/__init__.py
- datalad/cmd.py
- datalad/interface/tests/test_run.py
- datalad/support/tests/test_annexrepo.py
- datalad/tests/test_cmd.py
- datalad/tests/test_installed.py
- datalad/tests/test_tests_utils.py
- datalad/tests/utils.py
> Monkey patch nose to avoid need for -s, deprecate ignore_nose_capturing_stdout, make travis output more concise (no -s -v)

- datalad/cmd.py
- datalad/tests/test_cmd.py
We do take care about tuning up PWD while chdir etc.  But when we run
external process and set its cwd, we left PWD unchanged if was provided
in (likely) inherited and tuned environment.  This fix would change
PWD to match provided cwd, if it is known to the environment and cwd
is set.
I was not bold enough to always get an env (if not provided) and change it
there, but may be that is what we will need to end up doing at some
point.
This should resolve the failing test in
https://github.com/datalad/datalad/pull/3184
caused by underlying datalad process, which is started from a temp directory
while we provide it with a now non-matching PWD:
https://travis-ci.org/datalad/datalad/jobs/501525590#L4325
> BF: Fix PWD to match provided cwd in Runner

- setup.py
0.12.0rc1 was sdist uploaded while building package using python3. That
caused pyliblzma not being listed altogether as dependency, and thus no
longer autoinstalled.  The reason was this ad-hoc specification.  It might
have been done by me this way because of elderly Debians but it is just not
right in the Python world, so we need to have it fixed.
> BF: specify correctly dependency on pylibzma as prior python 3.3

- datalad/distribution/tests/test_dataset.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- By popular demand of our revolutionists. 
- Of no use ATM in the master itself
- Sits on top of #3218 
Feel welcome to tune naming of the "switch" to your liking.
> ENH: provide a "switch" to disable custom checks at GitRepo level while creating a new one

- datalad/metadata/search.py
If get_nohits_msg() doesn't return a message, report a generic "no
hits" so that the caller isn't left wondering what the blank message is
about.
Fixes #3195.
> ENH: search: Avoid showing an empty log message

- datalad/interface/run.py
- datalad/interface/tests/test_run.py
For some commands, it is useful to have a temporary directory.  For
example, one can be used as the source component of a Singularity or
Docker mount point.  Expose a temporary directory with the '{tmpdir}'
placeholder so that users do not need to embed $(mktemp -d) within the
command or write a command wrapper.
Re: datalad/datalad-container#50
---
As I was writing the commit message, I thought "actually, using $(mktemp -d) isn't that bad" (ignoring portability issues).  I could take or leave this PR at this point.
> ENH: run: Add 'tmpdir' placeholder

- datalad/support/gitrepo.py
Bug was originally reported at https://github.com/datalad/datalad-revolution/issues/94
but has its origin in the GitRepo method.
> BF: Report on deleted files

- datalad/support/json_py.py
- datalad/support/tests/test_json_py.py
This PR makes it a bit easier to read/write compressed JSON dumps, by softening the association stream==compressed, dump==uncompressed. Nothing amazing though.
Also a few more "tests".
Required for https://github.com/datalad/datalad-revolution/pull/84
> ENH: Uniformize API and capabilities of JSON dump and dump2stream

- datalad/support/digests.py
- datalad/support/tests/test_gitrepo.py
- datalad/utils.py
* b0d383eb - ENH(TST): cherry picked test from a BF in master
* 27b9905d - ENH: Use common checksuming code, reduce memory load
> Changes from master applicable to 0.11.x

- CONTRIBUTING.md
- datalad/distribution/dataset.py
- datalad/support/due.py
- datalad/support/due_utils.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_due_utils.py
- datalad/support/tests/test_gitrepo.py
- datalad/tests/test_utils.py
- datalad/utils.py
- setup.py
This pull request fixes #2065 - those eyes didn't let me sleep! I will blame @tyarkoni for anything to come.
- includes support for actually DueCrediting any dataset we "instantiate"
- ATM just ad-hoc extraction of metadata fields from `bids` and `datacite` (for CRCNS) records. Proper solution will need integration with extractors or some other harmonization which we do not have ATM
- Relies on changes yet to be merged/released in DueCredit: https://github.com/duecredit/duecredit/pull/144
- basic support for free text citations (so we could at least point to those datasets etc)
- access to `due.active`
With those changes and this PR, we are getting smth like:
```shell
> rm .duecredit.p; DUECREDIT_ENABLE=1 datalad ls ~/datalad/openfmri/ds000241 /home/yoh/datalad/crcns/aa-1 …
```
> ENH: duecredit support for citing datalad itself AND datasets it opens

- datalad/core/__init__.py
- datalad/core/local/__init__.py
- datalad/core/local/create.py
- datalad/core/local/run.py
- datalad/core/local/save.py
- datalad/core/local/status.py
- datalad/core/local/tests/test_create.py
- datalad/core/local/tests/test_save.py
- datalad/core/local/tests/test_status.py
- datalad/interface/__init__.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_fileinfo.py
- datalad/support/tests/test_repo_save.py
- datalad/tests/utils.py
- docs/source/cmdline.rst
This series follows #3183 and brings in the second wave of datalad-revolution bits.  It
* places the commands in the directory proposed by #3192 (I expect this will get some pushback)
* brings in the following commands:
- `rev-diff` (keeping `rev-`, for now at least) (#3190)
- `rev-status -> status` (with wrapper remaining in revolution) (#3187)
- `rev-save` (#3188)
- `rev-create` (#3189)
- `rev-run` (core's `run` still uses the `add`-based saver function for now)
* brings in the tests that were orphaned by the first wave (https://github.com/datalad/datalad/pull/3183#issuecomment-468755440)
* brings in the tests for the above commands aside from those for `rev-run` (leaving that to be done separately)
* applies @mih's patch for #3221: …
> Absorb most  of -revolution's commands

- datalad/interface/tests/test_utils.py
- datalad/interface/utils.py
Ran into it while creating a test where multiple kwargs should have been
consistently passed to subsequent invocations of metadata (as a function or
a method).  But pre-created kwargs dictionary was augmented by calling
metadata, which (as any side-effect) was quite confusing.
> BF: do not cause a side-effect on kwargs in @eval_results

- datalad/core/local/tests/test_create.py
- datalad/support/gitrepo.py
- datalad/tests/utils.py
When we pass --directory to ls-files, pass --no-empty-directory as
well so that we do not include directories that contain only excluded
files.
Fixes #3235.
> BF: gitrepo.get_content_info: Do not list empty directories

- datalad/metadata/metadata.py
Otherwise it would complain about "wrong version" when files not present at
all for the dataset being queried, but present in curdir dataset (e.g. when
querying from a super dataset).  See e.g.
https://github.com/datalad/datalad/issues/3055#issue-387483697
which shows such a message when it should not
> BF: join with ds.path when trying to see if any other metadata file is available

- .travis.yml
- appveyor.yml
- datalad/core/local/run.py
- datalad/interface/run.py
- datalad/interface/tests/test_run.py
This PR is not in its final state and will likely see a lot of churn, especially since I'm relying on appveyor for Windows feedback.  A summary will follow once things are in a state worth summarizing.
> Bring in -revolution's run tests

- datalad/plugin/wtf.py
datalad wtf did not include any information about which
version of Python is being used. This adds a section to
include the python version number and python implementation
being used to run datalad to aid in debugging.
> Add Python information to "datalad wtf" command

- datalad/auto.py
- datalad/config.py
- datalad/consts.py
- datalad/interface/ls_webui.py
- datalad/metadata/aggregate.py
- datalad/metadata/extractors/datalad_core.py
- datalad/metadata/metadata.py
- datalad/resources/procedures/cfg_metadatatypes.py
Rationale is to make them defined in a single place and be able to quickly (git grep) identify code which relies on them.  Otherwise it is quite hard since string quotes and spacing (separate lines) could vary etc.  Moreover e.g. DATASET_METADATA_FILE I believe was defined separately in multiple points.
I have not touched the tests somewhat on purpose, e.g. to make consts somewhat more constant ;)
> Rename old constant, and define/use a few new ones to avoid hardcoded copies of the paths

- benchmarks/api.py
rev- versions will now be benchmarked too if available, but by a separate dedicated benchmark.
On revisions where there is no `rev_` commands (0.11.x) we will still be able to benchmark
> RF: reincarnate benchmarking of non-rev create/add.

- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
In gh-3252, @mih says
> addurls offer a global save switch that causes any dataset modification to not be saved. This includes the initial dataset content placed in by create as well. I don't see why this would be needed, and it is off by default already.
I don't either.  @yarikoptic, this is from your d3d6610b5 (ENH: --no-save flag for addurls (TODO: tests), 2018-03-14).  Do you recall any reason why you wanted `create` to honor `--nosave`?
This PR stops propagating `--nosave` to create, and updates `addurls` to use `rev-create`.
> addurls: Don't pass --nosave to create (and use rev-create)

- CONTRIBUTING.md
- benchmarks/api.py
- benchmarks/usecases.py
- setup.py
It is also possible to profile and produce profile figure right away with
pip install gprof2dot
asv profile -v -o profile.gprof usecases.study_forrest.time_make_studyforrest_mockup
gprof2dot -f pstats profile.gprof | dot -Tpng -o profile.png && xdg-open profile.png
Here is the results of running this benchmark on my elderly laptop on 0.11.x and here:
```
$> asv compare -m hopa 0.11.x HEAD        
All benchmarks:
before           after         ratio
[930f464b]       [2ec70199]
<0.11.x>         <bm-forrest>
...
50.3±0.3s        43.7±0.4s    ~0.87  usecases.study_forrest.time_make_studyforrest_mockup [hopa/virtualenv-py2.7]
49.1±1s        43.0±0.2s    ~0.88  usecases.study_forrest.time_make_studyforrest_mockup [hopa/virtualenv-py3.4]
> BM: new benchmark based on make_studyforrest_mockup

- CONTRIBUTING.md
The crawler is in a different repo, describing the old file directory structure for it in the main repo is confusing.
> Remove reference to crawler from CONTRIBUTING.md

- datalad/support/annexrepo.py
Rational: We otherwise refuse to do anything with repos that could have an annex, but for operations like `status` this is not needed. Doing a late check will enable (more) datalad use on systems that do not have
git-annex.
@effigies wondered if it was possible to get information on a dataset without git-annex. This would be step one. It might be useful in this context to replace `AnnexRepo.get_content_annexinfo()` to not call `git-annex find/findref`, but to inspect the keys in a dataset on its own. This would make `status --annex <mode>` work without git-annex for any query mode where we would want to support this. It would also be straightforward to support a fallback that is only used when git-annex is actually not around.
> RF: Move the availability check for git-annex all the way to the end

- datalad/ui/__init__.py
As a concrete example:
```sh
tdir=$(mktemp -d)
datalad install -s ///openneuro/ds000001 $tdir/ds >$tdir/out 2>&1
```
Before this PR, that produces the following output:
```
[INFO] Cloning http://datasets.datalad.org/openneuro/ds000001 [1 other candidates] into '/tmp/tmp.KdwAWch08N/ds'
Cloning (counting objects):   0%|          | 0.00/100 [00:00<?, ?B/s]
Cloning (counting objects): 2.39kB [00:00, 36.4MB/s]                 
Cloning (compressing objects):   0%|          | 0.00/600 [00:00<?, ?B/s]
Cloning (compressing objects):   0%|          | 1.00/600 [00:00<00:00, 25.4kB/s]
[... lots more ....]
```
After this PR:
```
[INFO] Cloning http://datasets.datalad.org/openneuro/ds000001 [1 other candidates] into '/tmp/tmp.FcS5wWd4qi/ds'
[INFO] warning: Not setting branch master as its own upstream. …
```
> Don't pollute non-interactive output with progress bars

- datalad/downloaders/providers.py
- datalad/downloaders/tests/test_providers.py
When a provider has an invalid regular expression, datalad
currently provides obtuse error messages like
"bad character range [re.py_compile:251] (error)".
This catches any exceptions while compiling the re to explicitly
warn the user that there is an invalid regular expression in the
provider.
Unfortunately, there doesn't seem to be any way to provide the
path to the provider config file at this point in the code, so we
simply give the provider name.
> Provide a warning when a regex in a provider isn't valid

- datalad/tests/test_utils.py
- datalad/utils.py
> BF: check for stdin/out/err to not be closed before checking for .isatty

- datalad/core/local/create.py
- datalad/core/local/status.py
- datalad/support/gitrepo.py
Replace unconstrained `status()` call with path-constrained one. In a monster dataset with 700 subdatasets, this brings done the runtime for creating a top-level dataset from 7min to 1.5s.
Worth it...
Fixes #3293
> Speedier `rev-create`

- datalad/core/local/tests/test_save.py
- datalad/support/gitrepo.py
Calling save_() with explicit paths that do not include an untracked
directory will result in an empty list being passed as the `paths`
argument to get_content_info().  This causes get_content_info() to
operate on _all_ content and leads to any untracked subdatasets being
saved.
Avoid this behavior by checking that there are untracked directories
before passing them as paths to get_content_info().  Another option
would be to adjust get_content_info() to only fall back to all content
when paths=None, not paths=[], but that deviates from its currently
documented behavior and might affect other callers.
Fixes #3285.
> BF: gitrepo.save_: Don't save unspecified subdatasets

- datalad/metadata/tests/test_search.py
- datalad/plugin/addurls.py
- datalad/plugin/tests/test_addurls.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
Analog to function like add/add_ the normal version now just does things, whereas the _ version returns a generator that needs to be iterator over to actually perform anything. The prior behavior was
a constant source of surprise and anger.
Related to #2755
> RF: Make AnnexRepo.set_metadata() work without iteration

- datalad/core/local/tests/test_status.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_fileinfo.py
> ENH: Report 'bytesize' from plain Git, whenever ls-tree runs anyways

- datalad/interface/tests/test_run.py
116c21378 (TST: run: Swallow more test output, 2019-03-11) stopped
test_run.py from polluting the test output, but one test has been
leaking output since 3b3818cee (Merge branch 'rev-run-patches' into
rev-run-tests, 2019-03-19).
> TST: run: Swallow leaked output

- datalad/core/local/tests/test_create.py
- datalad/support/gitrepo.py
Otherwise we have incomplete identity information on all dataset components (i.e. we only have the state of a subdataset, but not its persistent ID). This is an issue during metadata extraction, where we would require subdatasets to be around in order to be able to give a full report.
We already ensure that create(force=True) does not alter a dataset's ID, so getting out of sync would require manual fiddling with DataLad's internal config. Sure be safe...
> ENH: Record a dataset's ID in a superdataset on `add/save` (fixes gh-3303)

- datalad/support/gitrepo.py
- Avoid subdataset recursion with diffstatus(`to != None`)
This will give a stellar performance boost for `rev-diff` on large dataset hierarchies, but even for a test case with an small dataset that has 10 direct (empty) subdatasets, the performance gain is ~25% already (down for 1.4s to 1s). On the the `///` dataset is goes down from 7min to 1.4s
> OPT: status/diff performance on dataset hierarchies

- appveyor.yml
If invoked directly with nose - do not include test_ files themselves in the .xml report
```
$> rm -f .coverage .coverage.xml ; python -m nose -s -v --with-cov --cover-package=datalad --cover-xml --cover-xml-file=coverage.xml datalad/tests/test_cmd.py >/dev/null 2>&1              
python -m nose -s -v --with-cov --cover-package=datalad --cover-xml   >  2>&1  4.15s user 3.01s system 113% cpu 6.328 total
(dev) 1 17826.....................................:Wed 10 Apr 2019 04:13:21 PM EDT:.
(git)hopa:~datalad/datalad-master[bf-appveyor-coverage]git
$> grep test_ coverage.xml                                                                                                                                                    
(dev) 1 17827 ->1.....................................:Wed 10 Apr 2019 …
```
> BF: appveyor - prepare coverage.xml in a separate invocation.

- datalad/distribution/create_sibling.py
- datalad/distribution/siblings.py
- datalad/distribution/tests/test_create_sibling.py
- Primary issue it resolves -- we have been installing `post-update` hook even when no web UI was asked to be published!  So if your `publish` or `create-sibling` was ... a bit slow while just hanging there without returning any output -- you might know now why. Check if `.git/hooks/post-update` is there on remote and kill it (unless you do use web ui)
- commit a4d40a607cb54a5cd4b49459496c6c64449ec666 first removes installation of the post-commit hook unless UI is set.  It also avoids running post-update hook unless it is there on remote (and executable)
- followup commit c680a405b41f0b657e7809ce1908db969cd11a6c fixes regression introduced by the previous one by enabling inheriting having hook or not from super.
- the last one 22c588227f2c735d8bd0944facb7cdbb3d4ee0d6 just for paranoid me …
> BF: do not install post-update hook if no UI, allow to reconfigure full hierarchy, no submodule update --init in hook

- datalad/core/local/status.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_fileinfo.py
- datalad/support/tests/test_repo_save.py
New mode to fully or partially disable subdataset state evaluation (which involves recursion into all present subdatasets to find potential uncommited changes), without disabling subdataset discovery and
reporting.
This addition allows for using status() unconditionally for (fast(er)) discovery operation.
This also replaces the (undocumented) argument and behavior switch 'ignore_submodules' that wasn't used in any sensible way, because it didn't actually provide sensible switching. It could only distinguish
"clever" operation and "needlessly wasteful" operation.
Performance info on the `///` dataset:
`datalad status --eval-subdataset-state commit -r  744.29s user 601.62s system 102% cpu 21:47.48 total`
Looks ridiculous, but a plain `git status` at the top-level already takes 7min. In …
> NF: status(eval_subdataset_state={'no'|'commit'|'full'}

- datalad/support/gitrepo.py
Follow up on gh-3324 by removing a stale reference to
ignore_submodules and describing the eval_submodule_state parameter in
the docstrings of diff() and status().
> DOC: gitrepo: Describe eval_submodule_state in docstrings

- datalad/distribution/create_sibling.py
- datalad/interface/base.py
- datalad/interface/run.py
- datalad/plugin/add_readme.py
- datalad/plugin/addurls.py
- datalad/plugin/check_dates.py
- datalad/plugin/export_archive.py
- datalad/plugin/export_to_figshare.py
- datalad/plugin/wtf.py
Old output:
`--eval-subdataset-state EVAL_SUBDATASET_STATE`
New output:
`--eval-subdataset-state {no|commit|full}`
This improves the docs of a range of commands, and addresses a comment by @kyleam in https://github.com/datalad/datalad/pull/3324
> DOC: Auto-set metavar for parameters with value choices

- datalad/core/local/status.py
- datalad/core/local/tests/test_status.py
- datalad/interface/tests/test_run.py
```
When status receives "." as the path, rev_resolve_path() resolves the
path to the dataset (either to the one explicitly provided as an
argument or to the one inferred from the current directory).  So,
using "." means we get the reference dataset as the path.
If a call includes an explicitly specified dataset _and_ "." as a path
argument, whether the call succeeds or fails depends on whether the
specified dataset is a subdataset.  When the reference dataset isn't a
subdataset, status queries within the dataset.  When it is a
subdataset, the call fails with a message saying the subdataset is not
underneath itself:
$ datalad status -d. .
[ERROR ] dataset containing given paths is not underneath the
reference dataset [...]
Even though the desired behavior could be achieved by dropping "." …
```
> BF: status: Provide special treatment of "." path

- datalad/metadata/extractors/xmp.py
Massive performance boost by not testing EVERY file in a dataset for XMP metadata, but instead use a file name extension based pre-filter.
This halves(!) the time to aggregate metadata for openfmri (where pretty much all datasets have this extractor enabled.
Timing in https://github.com/datalad/datalad-revolution/pull/84#issuecomment-482807116
> Make XMP extractor faster (fixes gh-3328)

- datalad/cmd.py
As "discussed" in #3319 
It could help quite a bit for any runs of `git-annex CMD --json` (not batched)
> OPT: do not bother sleeping when not output was received in the Runner processing of output

- benchmarks/api.py
- datalad/distribution/dataset.py
This has been marked as deprecated since v0.9.0.
> CLN: dataset: Drop deprecated get_subdatasets()

- CHANGELOG.md
- datalad/core/local/create.py
- datalad/core/local/save.py
- datalad/core/local/status.py
- datalad/core/local/tests/test_create.py
- datalad/core/local/tests/test_save.py
- datalad/core/local/tests/test_status.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/tests/utils.py
* Avoid `str(pathobj)` to prevent py2-encoding issues.
* Make `runner.(..., env={...})` work when env has unicode values (py2).
---
A couple of notes:
* This will very likely conflict with ongoing topics.  I'm fine leaving this until those land and then dealing with the conflicts.
* I've avoided OBSCURE_FILENAME for compatibility with older Windows, but I'm not sure that is something worth doing.  I'm happy to rewrite the tests using OBSCURE_FILENAME.
* This PR carries a change dealing with the runner.  That commit is branched off of 0.11.x so that it can be merged into that line separately, but it is needed here too.
> Consistently convert pathlib objects with text_type

- docs/casts/publish_on_github.sh
In #3318 (a4d40a607cb54a5cd4b49459496c6c64449ec666 in particular) I changed behavior
that no post-update hook  is installed by default.  And that is indeed desired since
unless it is a publicly facing via http git repository there is no need in such a hook.
BUT ATM the hook is unconfigurably melds two effects together:
- making this repo accessible via dummy git http backend (by running git update-server-info)
- and generating web listing metadata
There is no configuration to enable one but not another action in the hook.
So for this cast to still work with current functionality, we would need to enable web UI
which will establish the hook (and also install web UI index.html and all the needed JS
libraries).  In the long run I guess we should disentangle two aspects somehow and
grow the …
> BF/ENH: create-sibling with --ui true for publish_on_github cast

- datalad/distribution/get.py
- datalad/interface/common_opts.py
Because of otherwise too long of a run time I often need to use --recursion-limit
for operations such as diff while working with deep hierarchies. So I felt that it
would be nice to have a short cmdline option for it.  Another to  -R was -L (tree
uses it), but we do use -L already in elderly  datalad ls   so decided to go for -R
But if you feel that not desired/needed or different option than -R to use -- I am all ears ;)
> ENH: short -R for --recursion-limit

- datalad/support/gitrepo.py
This is used inside GitRepo.diffstatus() to implement an early-stopping strategy that yields a state label for a subdataset at the earliest sign of a modification. #3342 
Performance info:
Prep:
```
import datalad.api as dl
ds = dl.rev_create('deep')
path = ds.pathobj  
for i in range(20):       
path = path / 'down'
ds.rev_create(path)
```
followed by a
```
% touch deep/down/down/here
```
on present master
```
>>> timeit dl.Dataset('deep').status()
1 loop, best of 3: 1.16 s per loop
```
this PR
```
>>> timeit dl.Dataset('deep').status()
1 loop, best of 3: 198 ms per loop
```
> NF: GitRepo._diffstatus() internal helper for global state evaluation (fixes gh-3342)

- datalad/support/exceptions.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
for known paths from parent directory.
Decided to (start) using warnings.warn (instead of logging.warn) because
- we need to have it issued only once, not upon every init (why to flood?)
- we are expecting action on "client" side -- upgrade, so that is the recommended way
to do it according to https://docs.python.org/2/howto/logging.html#when-to-use-logging
Closes #3295
Replaces #3296
> ENH: issue a warning (using warnings.warn) if git is too old for us to check

- datalad/interface/tests/test_save.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/utils.py
This pull request fixes #3087 through comparing to the `git diff` for the files provided to the commit call, so should behave properly in case of directories etc.
- Make checks optional for the `rev-` functionality since it cares not about staged or not and about direct mode, so I guess a plain `commit(files)` should suffice in that case - probably should better be done in master upon merge
> BF: GitRepo.commit to work correctly on directory paths (Fixes #3087)

- datalad/support/gitrepo.py
... in GitRepo.get_content_info()
This can give a significant performance boost in datasets with a large
number of file, and when no homogenized file type semantics are needed
(e.g. "was there any diff?").
> ENH: Add low-level switch to prevent file type evaluation

- datalad/cmd.py
- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
This is a fragile enterprise due to the limitations of `BatchedCommand()`. When queried for a non-annexed file, git annex will error not via JSON response, but through stderr
```
{"file": "."}
git-annex: not an annexed file: .
```
which ATM is not monitored at all. I assume due to the general sadness of subprocess under PY2.
Docstrings warn about this, and there is no `batch=None` automagic because of this.
Other than that, it works.
This is needed to achieve a sensible performance of the `annex` extractor in -revolution (the behavior of the one in -core is pointless anyways), where all these limitation do not matter.
Waiting here: https://github.com/datalad/datalad-revolution/compare/enh-annex
> ENH: AnnexRepo.get_metadata(batch=True) 

- datalad/core/local/diff.py
- datalad/core/local/tests/test_diff.py
- datalad/distribution/publish.py
- datalad/interface/__init__.py
- datalad/interface/annotate_paths.py
- datalad/interface/diff.py
- datalad/interface/rerun.py
- datalad/interface/tests/test_diff.py
- datalad/interface/tests/test_run.py
```
Replace core's diff with -revolution's.  Update the few diff callers
to use the new variant, with the exception of annotate_paths.  Keep
the older diff around but hidden (not listed in an interface group and
named with an underscore) for annotate_paths.  We could update it to
use the new diff, but it's not worth the effort because it is only
used by add, create, and the save, which are on their way out.
This is copied from revolution's 38df2ddd2858fa8786b6fcca6c472ef9be8a53e8.
You can verify that there are no substantial changes by checking
datalad-revolution out at that commit, pointing $DL_REV_DIR to the
repository, and then running
% git diff --no-index -- \
$DL_REV_DIR/datalad_revolution/revdiff.py \
datalad/core/local/diff.py
% git diff --no-index -- \ …
```
> Absorb rev-diff

- datalad/core/local/status.py
Before it would say:
```
% datalad status --annex basic
5961 annex'd files (0.0/10.1 MB present/total size)
```
Now it says:
```
% datalad status --annex basic
5961 annex'd files (10.1 MB recorded total size)
```
Full output with availability check remains unchanged:
```
% datalad status --annex availability
5961 annex'd files (89.7 KB/10.1 MB present/total size)
```
> BF: Don't claim content size is zero without status --annex availablity

- CHANGELOG.md
<details>
<summary>Changes for 0.11.5</summary>
```
#
#
-  Show must go on
39e8e8b8f^-1
+* BF: do not install post-update hook if no UI, allow to reconfigure full hierarchy, no submodule update --init in hook (#3318)
ab64a6cb2^-1
+  Merge pull request #3322 from yarikoptic/opt-runner
7a945e1ce^-1
-  Merge pull request #3337 from yarikoptic/bf-cast-publish
bf661d27e^-1
+  Merge branch 'ansi-color-default' into 0.11.x
06cd09e0f^-1
+  Merge branch 'py2-runner-env' into 0.11.x
2e84cb923^-1
+  Merge pull request #3340 from yarikoptic/enh-R
49c2cd80d^-1
-  Merge branch 's3-cleanup' [#3348]
c1d479193^-1
+  Merge pull request #3347 from yarikoptic/bf-3295-2
b12a4cc5d^-1
+  Merge pull request #3106 from yarikoptic/bf-3087
514545a46^-1
```
</details>
> CHANGELOG.md: First batch for 0.11.5

- CHANGELOG.md
Closes #3386.
<details>
<summary>Changes included</summary>
```
#
#
-  Merge pull request #3239 from kyleam/rev-save-doc-typos
ace1f402d^-1
-  Show must go on AKA Post release changes to changelog
af7265d60^-1
+  Merge pull request #3238 from kyleam/status-no-empty-dir
0f0fafc30^-1
-  BM: benchmark master and 0.11.x now, forget elderly 0.[59].x
b66203983^-1
-  Merge pull request #3251 from kyleam/rev-run-tests
9f8542e8f^-1
-  Merge remote-tracking branch 'origin/0.11.x'
6c753c8d7^-1
+  Merge pull request #3255 from driusan/PythonWtf
4bc1367f2^-1
-  Merge pull request #3257 from mih/tst-coreonwin
6ba6d53b5^-1
-  Merge pull request #3252 from mih/rf-lessadd
0bb31b3cd^-1
-  Merge pull request #3260 from yarikoptic/bf-bm-norev
bde758aa9^-1
+  Merge pull request #3259 from …
```
> Add CHANGELOG entries for 0.12rc3

- datalad/interface/tests/test_save.py
- datalad/support/annexrepo.py
This PR
* fixes an issue with the partial commit workaround in AnnexRepo.commit() introduced by gh-3009.
* avoids using the temporary index in a case where it is unnecessary
<details>
<summary>Demo of the issue</summary>
```sh
#!/bin/sh
set -ex
cd $(mktemp -dt dl-XXXXXXX)
datalad create
printf '\n* annex.largefiles=(largerthan=4b)\n' >>.gitattributes
datalad add .gitattributes
printf "so big; to annex i go" >ishrink
datalad save ishrink
datalad unlock ishrink
: >ishrink
: >staged && git add staged
datalad save ishrink
git status -s
```
Without this PR, the status output is
```
TT ishrink
A  staged
```
even though ishrink was just committed and should be clean.
</details>
> Fix up index logic from gh-3009

- datalad/consts.py
- datalad/distribution/create_sibling_github.py
- datalad/distribution/tests/test_create_github.py
- datalad/distribution/tests/vcr_cassettes/github_datalad_tester.yaml
- datalad/distribution/tests/vcr_cassettes/github_datalad_tester_org.yaml
- datalad/distribution/tests/vcr_cassettes/github_yarikoptic.yaml
- datalad/downloaders/credentials.py
- datalad/downloaders/tests/test_credentials.py
- datalad/interface/common_cfg.py
- datalad/support/github_.py
- datalad/support/tests/test_github_.py
- datalad/tests/test_utils.py
- datalad/ui/base.py
- datalad/ui/dialog.py
- datalad/ui/tests/test_dialog.py
- datalad/utils.py
- setup.py
This pull request fixes #2004 , fixes #2005, and I also think it might fix #3126 if @effigies says so ;-)
This pull request proposes to do a more thorough pass over possibly available github authentication mechanisms to achieve the goal.  I have tried to maintain currently present "non standard" handling of authentication for github:
- token - we do not store those in the credentials store, but rely on it/them being present in the (git) config.  But since multiple tokens could be defined (globally, and then within a dataset), we might need to consider multiple (I somehow get 3 values with 2 unique ones)
- user/password could be provided in the command line (we don't do that for any other remote etc)
change in behavior
- provided in cmdline user/password are not stored in the credential …
> ENH/BF/RF: GitHub authentication

- .travis.yml
- setup.py
Ideally there should be no "manual" installations within CI setups, and such versioned dependencies are due to be specified in setup.py -- similar but a bit more extensive PR is coming to datalad-neuroimaging
> RF: versioned depends on sphinx within setup.py itself

- datalad/core/local/create.py
- datalad/interface/common_cfg.py
The new create() configures the annex backend based on the
datalad.repo.backend.  Document it in interface/common_cfg.py.
> DOC: common_cfg: Add entry for datalad.repo.backend

- datalad/support/sshconnector.py
- datalad/support/sshrun.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_sshconnector.py
> RF: Various little annoyances in SSH support code

- datalad/interface/common_cfg.py
- datalad/log.py
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/ui/__init__.py
- datalad/ui/dialog.py
- datalad/ui/progressbars.py
- datalad/ui/tests/test_dialog.py
Closes #3393
Adds `LogProgressBar` which logs completion (possibly partial) for the item.
<details>
<summary>Here are examples on how reporting looks like with `log` with some being interrupted or completed fully</summary>
```shell
$> sudo rm -rf QA simon ds00* face_place dartmouth-phantoms; DATALAD_UI_PROGRESSBAR=log datalad install -g ///openfmri/ds000105
[INFO   ] Cloning http://datasets.datalad.org/openfmri/ds000105 [1 other candidates] into '/tmp/ds000105' 
[INFO   ]  Cloning (counting objects) 100 objects done in 0 sec at 1880853 objects/sec 
[INFO   ]  Cloning (compressing objects) 68466 objects done in 0.001 sec at 52508176 objects/sec 
[INFO   ]  Cloning (receiving objects) 152614 objects done in 6 seconds at 25248 objects/sec 
[INFO   ]  Cloning (resolving stuff) 80063 objects …
```
> Make progress bar "backend" configurable, use the "log" one during tests

- datalad/core/local/tests/test_save.py
- datalad/support/gitrepo.py
When rev-save saves a fresh subdataset, it doesn't show any
information about adding that subdataset:
$ datalad create subds
$ datalad rev-save
add(ok): .gitmodules (file)  # <- no subdataset mentioned here...
add (ok: 1)                # <- ... or here.
save (ok: 1)
Yield a result so that the output is instead:
$ datalad rev-save
add(ok): subds (file)        # <- new entry
add(ok): .gitmodules (file)
add (ok: 2)
save (ok: 1)
The new result is consistent with the result that is yielded when
saving modified subdatasets.
> BF: gitrepo: Yield 'add' result when saving new submodule

- .travis.yml
According to https://github.com/datalad/datalad/pull/3405
we likely no longer hit it.  If we hit it again - it would also be useful
to know, possibly to test devel branch of wrapt (currently 1.11.1-4-g03e90ab)
> RF: disable wrapt workaround

- .zenodo.json
- datalad/interface/common_cfg.py
- datalad/interface/ls.py
- datalad/support/ansi_colors.py
- datalad/support/tests/test_ansi_colors.py
Checks for interactive terminal, `datalad.ui.color` configuration and `NO_COLOR` environment variable, in that order of precedence.
Closes #3404.
> NF: Add check for whether color is enabled

- datalad/distribution/create_sibling.py
- datalad/support/sshconnector.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
- datalad/support/tests/test_sshconnector.py
> On-demand SSHConnection.get/put()

- datalad/consts.py
- datalad/interface/clean.py
Found a repository which a bunch of logs on what files failed to download:
```
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000201[master]git
$> cat ./.git/annex/transfer/failed/download/d46236ce-1f9e-4216-9676-35f10fd6c553/MD5E-s131899529--67071615cc9e1041d0700547dd676ced.nii.gz
1543974478.691019986s
sub-9100/ses-1/func/sub-9100_ses-1_task-sleepiness_bold.nii.gz
```
I think it should be safe to remove them.  Cons of the approach, that removing
top level directories so not providing list of specific files, which could be
taken as pros since there could be many ;)
> ENH: clean - remove annex transfer directories

- setup.py
- colorama Windows specificity is specified via `platform_system=="Windows"`
- always demand `keyring >= 8.0`
And also simplify dependencies where there is no alternative used now:
- tqdm
If older systems with too old setuptools (debian jessie) fail to install from sources,
they might require patching away platform_system=="Windows" and python_version < "3.3"
which is already the case anyways, but while at it TODO (after dinner):
- ~~add conditioning to check for too old setuptools (not sure what version is min to support them yet) being used and avoid adding those qualifiers then. This would avoid patching e.g. for NeuroDebian backports~~ Tried, could succeed, but then it would still might require patching for liblzma so decided not to bother for now.  Note, that setuptools throws …
> BF: stop relying on setup.py runtime environment using platform.dist

- datalad/distribution/dataset.py
- datalad/distribution/tests/test_clone.py
- datalad/interface/tests/test_save.py
- datalad/support/network.py
- datalad/support/tests/test_network.py
Paths with : in them could get confused for SSHRI.  If we know that it
is a path, why to check/crash?  Original commit
86a05d0fb1a5b091676d0d430f11ae05476f18c4
which introduced that check unfortunately does not provide ANY information
on the initial problem it addresses, besides hinting possibly on it being related
to Windows
Closes #3421
> BF: revert back (remove) check for path being PathRI

- datalad/cmdline/helpers.py
- datalad/distribution/publish.py
- datalad/distribution/subdatasets.py
- datalad/dochelpers.py
- datalad/interface/base.py
- datalad/metadata/extractors/xmp.py
- datalad/plugin/export_to_figshare.py
- datalad/support/annexrepo.py
- datalad/support/archives.py
- datalad/support/constraints.py
- datalad/support/network.py
- datalad/support/param.py
- datalad/support/strings.py
- datalad/utils.py
- datalad/version.py
The Python 3.8 Travis run from gh-3406 spit out a bunch of new SyntaxWarnings.  This PR addresses those.  Hopefully it catches all of them, but I'm making these changes without running 3.8 locally, so I'll likely need to adjust after seeing what Travis says.  (The tip commit adds a temporary 3.8 run to Travis.)
Closes #3418.
> Fix warnings from py3.8 test run

- datalad/core/local/tests/test_save.py
- datalad/distribution/dataset.py
- datalad/distribution/tests/test_dataset.py
- datalad/interface/run.py
Talked about it multiple times: here it is.
Any absolute `path` given to a command is used as such. Any relative `path`is interpreted as being
relative to the CWD, **unless** an also provided `dataset` argument is a `Dataset` instance (not just a 
path to or inside a dataset).
I briefly looked into implementing this for all commands, but that seems to be a bottomless pit -- to expensive for me and for now. Instead, I implemented it for `rev_resolve_path()` that is used by all commands that already comply with the structure proposed in #3192.
km: Looks fine (and outputs come in as absolute paths, so string/instance for dataset would be the same anyway).
> New "standard" path resolution logic

- datalad/plugin/tests/test_plugins.py
- datalad/plugin/wtf.py
`-S dependencies`   is probably one of the most useful, but unfortunately it is not including concise versioning of datalad and datalad extensions, which are all heavy sections...
> ENH: wtf -S to specify which sections to query/display (by default -- all)

- datalad/distributed/__init__.py
- datalad/distributed/create_sibling_gitlab.py
- datalad/distributed/tests/test_create_sibling_gitlab.py
- datalad/interface/__init__.py
- docs/source/cmdline.rst
- docs/source/modref.rst
Initial draft of such a command with basic support for multiple GitLab remotes, access via SSH and/or HTTP, sibling creation, sibling (re-)configuration, and three essential layout modes (flat, collection, hierarchy).
> NF: `create_sibling_gitlab`

- datalad/core/local/run.py
- datalad/interface/rerun.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_annexrepo.py
- datalad/support/tests/test_gitrepo.py
This PR implements the proposal in https://github.com/datalad/datalad/issues/3342#issuecomment-495974665.
> Use `git status` for dirty and reference `datalad status` in {,re}run's dirty message

- datalad/support/gitrepo.py
Closes #3457 if we decide to go for it
> Enh bring gc back

- datalad/core/local/create.py
- datalad/core/local/tests/test_create.py
As of fc25ac55d (BF: Do not duplicate/auto-convert dataset args to
instances, 2019-05-20), EnsureDataset returns a string rather than a
dataset when given a string.  This introduced a regression in creating
and then saving a subdataset to the parent dataset from the command
line (e.g., `datalad create -d. subds`) because downstream code
expects the dataset to be a dataset instance.  Update that code to use
refds, which is the Dataset instance for the dataset argument.
Fixes #3463.
> BF: create: Restore saving behavior for --dataset

- datalad/core/local/run.py
- datalad/interface/tests/test_unlock.py
- datalad/interface/unlock.py
- datalad/interface/utils.py
- datalad/support/annexrepo.py
```
If a file without content is passed to unlock(), it yields a
result (with a status of "impossible") saying that the file doesn't
have content.  But if the files without content weren't explicitly
provided as paths (e.g., no path was given or a directory containing
the files was given as the path), then files without content lead to a
CommandError from the underlying 'git annex unlock' call.  (Or in v6+,
they lead to the pointer being unlocked which is inconsistent with the
error given when a file is explicitly specified in v6+ and also
potentially confusing to callers.)
To fix the "no paths specified, missing content" behavior, rely on the
information provided by status() to restrict the unlock calls to files
with content.  This fix raises the question of how to report files
without …
```
> BF+RF: unlock: Rewrite using status()

- datalad/core/local/tests/test_create.py
- datalad/support/gitrepo.py
Additionally check that a .git directory is not empty
> BF: More precise test for valid repo paths (fixes gh-3473)

- .travis.yml
When Travis switched its default distribution from Trusty to Xenial,
our 3.7-dev build started to error with a segfault.  The reason for
this isn't clear, but a plain 3.7 build doesn't [0] show the segfault,
so let's use that instead.
[0]: https://travis-ci.org/datalad/datalad/builds/545360524
Fixes #3477.
> TST: travis: Drop "-dev" suffix from py3.7 build

- .travis.yml
Both of these have had releases that contain the necessary
compatibility fixes.  The crawler is now the only extension that
unreleased (and unmerged) compatibility fixes (crawler PR 41).
> TST: travis: Uncomment -container build

- datalad/core/local/tests/test_run.py
- datalad/core/local/tests/test_save.py
- datalad/interface/tests/test_rerun.py
- datalad/tests/utils.py
When 203aa652a (RF: remove receive.autogc=0 and gc.auto=0 options to
git calls, 2019-05-24) was merged to master, test_py2_unicode_command
started to fail on AppVeyor.  Work around this by configuring
gc.auto=0 for that test's repository.  (This assumes gc.auto but not
receive.autogc is the culprit, since the test does not interact with a
remote.)
Another option would be to revert 203aa652a, but let's avoid doing
that until it's clear that there are more widespread issues.
Closes #3482.
> TST(appveyor): run: Disable gc.auto for erroring test

- datalad/core/local/create.py
- datalad/core/local/tests/test_create.py
* Fix subdataset `datalad create -d.` case from #3484.
* Fix dataset-path comparison check for `datalad create -d APATH APATH`.
> create: Two path handling fixes

- datalad/core/local/save.py
- datalad/core/local/tests/test_save.py
save() calls status() with the default on_failure value of "continue",
which means that---regardless of the on_failure value specified for
save()---status() always raises an IncompleteResultsError exception
when a failure occurs and then save() aborts.  Make save() call
status() with on_failure="ignore" so that the *save* caller gets to
decide what to do in the case of a failure.
Note that this results in some double reporting:
[ERROR  ] path not underneath this dataset [status(...)]
save(error): ../b [path not underneath this dataset]
But if save() were to just swallow the result so that only the log
message is shown, an on_failure value of "continue" or "stop" would
not raise an IncompleteResultsError exception or exit on the command
line with a non-zero status.
> BF: save: Honor on_failure

- .github/PULL_REQUEST_TEMPLATE.md
Draft PRs now trigger tests (gh-3480).
---
This new behavior is presumably here to stay, but we might want to wait to merge until the Travis docs or [discussion] about this get updated.
[discussion]: https://travis-ci.community/t/draft-pull-requests-not-being-built/2434/9
> DOC: PR template: Remove stale comment about Travis and drafts

- .travis.yml
* Fix logic for deciding to run upstream git tests.
* Enable ppa:git-core/ppa for the upstream git build because the Xenial image, unlike Trusty, does not include third-party apt-repositories.
Re: #3476
> TST: travis: Adjust upstream Git build for Xenial

- datalad/core/local/save.py
- datalad/core/local/tests/test_save.py
- datalad/support/gitrepo.py
```
Saving an untracked sub-repository without a commit checked out [0]
results in an ugly state: the sub-repository is _not_ added as a
submodule but its untracked files are added as blobs in the
_superdataset_.  This is not usually an issue for datasets because
these get initial commits on creation, so we documented this as a
known issue rather than introducing additional checks that would come
with a performance penalty.
The core problem is a combination of 'git submodule add' accepting a
sub-repository on an unborn branch and 'git ls-files' considering such
a sub-repository a directory rather than a repository.  Both issues
are fixed in Git 2.22.0 [1].  Update the documentation note and tests
accordingly.
[0] Usually this is just a repository without any commits, but it
could be …
```
> save: Update for "no commits" sub-repo fix in Git

- datalad/interface/download_url.py
- datalad/interface/tests/test_download_url.py
Make `download_url` follow the logic outlined in gh-3435.  This sits on top of gh-3470 because it relies on `Save` respecting `on_failure="ignore"`.
I started looking into updating `run` (the other caller of `get_dataset_pwds`) for the new path resolution logic and originally intended to roll it into this PR, but decided to do it separately because that's going to take some more thought.
Fixes #3468.
> download_url: Update path resolution logic

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
To decide if a remote is an annex special remote, we check whether
'annex-externaltype' or 'annex-webdav' is configured for the remote.
This mis-classifies nearly all internal special remotes (anything but
webdav) as an ordinary remote because those don't have
'annex-externaltype' configured.
There's no common annex- option for special remotes.  As the
definition of annex's findSpecialRemotes shows, each special remote is
expected to have at least an annex-TYPE option.  We could keep a list
of known internal special remotes and look for that or externaltype,
but the list of internal special remotes is a moving target.
findSpecialRemotes' documentation mentions that "special remotes don't
have a configured url", so let's instead identify them based on _not_
having a URL and having some …
> BF: annexrepo: Adjust overly selective is_special_annex_remote()

- datalad/interface/rerun.py
- datalad/interface/tests/test_run.py
> NF: rerun: Add --explicit flag

- datalad/support/annexrepo.py
- datalad/support/exceptions.py
Report non-json output from --json commands to replace silent failures, in particular #3513, with more informative messages.
> annexrepo: Try to avoid silent bugs when processing json output

- CHANGELOG.md
<details>
<summary>Changes from 0.11.5</summary>
```
#
#
-  Show must go on
fd857f4bc^-1
-  BF(TST): skip vcr based github tests if no network
d977cc661^-1
-  DOC: wtf: Add missing parenthesis to parameter description
78c72ec23^-1
-  DOC: adjusted 0.10.0 changelog entry to mention when --fake-dates was added
d8050c83a^-1
-  ENH(TST): adding one more condition (for nd80) to skip testing for url to be in error msg
fe772763a^-1
+  Merge pull request #3458 from yarikoptic/enh-bring-gc-back
e6fe78f15^-1
+  Merge pull request #3479 from kyleam/travis-drop-37-dev
aef2b8af8^-1
+  Merge pull request #3492 from kyleam/webui-subrepo-nocommits
23b4441d1^-1
+  Merge pull request #3494 from kyleam/xenial-upstream-git
27b9aa493^-1
+  Merge pull request #3493 from kyleam/annexrepo-status-nocommits …
```
> CHANGELOG.md: First batch for 0.11.6

- datalad/support/annexrepo.py
- datalad/support/tests/test_annexrepo.py
> UX: Don't log stderr as warning when expect_stderr was True

- datalad/local/subdatasets.py
- datalad/local/tests/test_subdataset.py
_parse_git_submodules() returns early without yielding submodules if a
dataset's path does not equal or contain a supplied path.  This is
problematic when operating recursively because, if a directory
containing more than one level of subdatasets is given, the path is
the parent---not child---of the dataset, but it should still be
included in the output.  Add this condition to
_parse_git_submodules().
Fixes #3509.
---
I'm not sure this is the best or cleanest approach, but at the very least it provides tests and additional information for gh-3509.  And, while I haven't looked at gh-3508 closely, I see it includes an optimized get_parent_paths() helper, so that may be of use here.
> BF: subdatasets: Fix recursion when path is specified

- datalad/support/json_py.py
- datalad/support/tests/test_json_py.py
Fixes gh-3523
Sadly, we still butcher unicode somewhere on the way from loading it in as metadata and spitting it out as a result.
Here is a dataset that has `run` records to obtain metadata, and has aggregated metadata that demos the butchered result: https://github.com/datalad-datasets/longnow-podcasts
> BF: Make load_stream() not stumble over U2028 and friends

- datalad/core/local/run.py
- datalad/core/local/tests/test_run.py
- datalad/distribution/add.py
- datalad/distribution/publish.py
- datalad/distribution/tests/test_add.py
- datalad/distribution/tests/test_publish.py
- datalad/plugin/no_annex.py
- datalad/plugin/tests/test_plugins.py
- datalad/utils.py
I noticed that `add -d.` was failing from the command line because the code assumes `dataset` comes in as an instance.  (It doesn't as of fc25ac55d.)  Since we've hit into similar issues (gh-3488 and gh-3471), I tried to do a more thorough pass of the commands.  (Ideally we would test the string dataset case for each command that takes a `dataset` argument, but for now I just checked with manual testing and code inspection.)  That caught issues in `publish` and `no_annex`.  And as mentioned in gh-3471, `run` also needs an update for the new path handling.
This PR addresses these "dataset now can come in as a string" issues, as well as updates `run` to follow the relative path handling described in gh-3435.
<details>
<summary>Inspected commands</summary>
gh-3488
gh-3471
unexposed and only …
> More fixes to dataset argument handling

- datalad/metadata/metadata.py
Otherwise might wait for half an hour just to blow
+ inform about all unavailable, not just the first one
> ENH: fail early if some metadata extractor is not available

- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
as e.g. reported in https://github.com/datalad/datalad-crawler/issues/47
> PY3: safeguard __del__ in Annex and Git Repo to not breed useless exceptions
