.zenodo.json
datalad/customremotes/ria_utils.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/ora_remote.py
datalad/distributed/tests/test_create_sibling_ria.py
datalad/distributed/tests/test_ria_basics.py

Add an argument to create_sibling_ria to add an alias symlink to the RIA store to refer to this dataset.
Would be great to know if the way I'm adding this functionality looks sane, it is the first time I touch the datalad code.

NF: Add alias argument to create_sibling_ria

---

datalad/customremotes/ria_utils.py
datalad/distributed/ora_remote.py

Sister PR of #5607 against master
Additionally alters the behavior of the new alias feature introduced with #5592 to use a relative path for the alias. This keep the symlinks valid when moving an entire store.

Fixes for RIA when using different push/pull URLs

---

datalad/distribution/tests/test_uninstall.py
datalad/support/tests/test_annexrepo.py

test runs of datalad/git-annex started to fail, so I spotted it.
Introduced in
[8.20210330-245-g4edde9870](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=4edde987092a3fcf8f359b14c5223ec7d458ddba)
I do not think it is worth tracking copy vs copies as only used in
the tests.

BF(TST): account for git-annex starting to "singularize" copy in drop

---

datalad/customremotes/ria_utils.py

This fixes a problem with the version check for a newly created dataset, which would perform a local test, even if the sibling is on an SSH host.
I will propose a PR against the mainline too.

BF: version test in RIA stores

---

datalad/interface/tests/test_run_procedure.py

Detected while trying to build 0.14.2 for Debian
Lead to
ERROR: datalad.interface.tests.test_run_procedure.test_name_with_underscore
File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/tests/utils.py", line 578, in _wrap_with_tree
return t(*(arg + (d,)), **kw)
File "/build/datalad-0.14.2/.pybuild/cpython3_3.9_datalad/build/datalad/interface/tests/test_run_procedure.py", line 418, in test_name_with_underscore
ds.run_procedure(spec=["print_args"])
File …

BF(TST): use sys.executable and not hardcoded "python"

---

.github/workflows/update-contributors.yml

The `update-contributors.yml` workflow has been broken since December, as strings in workflow context expressions such as "`if:`" keys must use single quotes, not double-quotes.

Fix syntax of update-contributors workflow

---

.travis.yml
datalad/__init__.py
datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py
datalad/core/distributed/tests/test_push.py
datalad/distributed/tests/test_ria.py
datalad/distribution/tests/test_get.py
datalad/distribution/tests/test_install.py
datalad/distribution/tests/test_publish.py
datalad/distribution/tests/test_update.py
datalad/interface/common_cfg.py
datalad/interface/tests/test_rerun.py
datalad/support/tests/test_annexrepo.py
datalad/support/tests/test_gitrepo.py
datalad/tests/test_testrepos.py
datalad/tests/test_utils_cached_dataset.py
datalad/tests/utils.py
datalad/tests/utils_cached_dataset.py
tools/ci/install-minimum-git.sh
tools/ci/install-upstream-git.sh

`datalad clone` and test code assume that the remote name is "origin".  Even though `datalad clone` doesn't expose the `--origin` option of `git clone`, this assumption is no longer safe because, as of Git 2.30, the default remote name for clones can be configured via `clone.defaultRemoteName`.
This is a work-in-progress series for addressing that.
---
I've executed only a subset of tests locally, so there are probably still failures to address.
Update: ~Need to fix git build first.~
https://travis-ci.com/github/datalad/datalad/builds/223108958#L1661
Passed: https://travis-ci.com/github/datalad/datalad/builds/223218195
See
https://git-annex.branchable.com/bugs/crippledfs__58___annex-init_crash_when_remote_name_is/
The main solution here is probably just to not set the custom value for …

Don't hard code "origin" as remote name

---

datalad/support/tests/test_annexrepo.py

The recently merged gh-5572 adjusted our tests and code on maint to
avoid assuming "origin" is the default remote name in a clone, but the
master-specific 417f292be7 (ENH: annexrepo.whereis: Implement
batch=True, 2021-03-25) added a test that hard codes "origin".  Update
it to use DEFAULT_REMOTE.

TST: test_whereis_batch_eqv: Don't hard code remote name

---

.codespell-ignorelines
datalad/core/local/run.py
datalad/core/local/tests/test_run.py

This PR implements the dry-run operation proposed in gh-5538 by adding a `--dry-run` flag to `run` along with a custom result renderer.  I went light on the reported details, but, if desired, I think it should be straightforward to extend this approach later with more information.
I decided to go with the name `--dry-run` because I think that's the most familiar/obvious name, though `--report` would align with `rerun`.  Also, `--report` might be a bit more natural if this option is later extended to take an optional value (e.g., to restrict or extend what is reported).
---
```
$ touch foo
$ datalad save
$ datalad run --dry-run -i 'fo*' -o out 'cat {inputs[0]} >{outputs[0]}'
Dry run information
location: /tmp/dl-vaZ53PN
expanded inputs:
['foo']
expanded outputs:
['out']
command:
cat …
```

run: Add dry run mode

---

datalad/local/addurls.py
datalad/local/copy_file.py
datalad/local/tests/test_copy_file.py
datalad/support/annexrepo.py

`addurls` and `copy-file` avoid `fromkey` on adjusted branches because `fromkey` unconditionally creates a symbolic link, but that's no longer needed as of git-annex's 4588668a1 (fromkey unlocked files support, 2021-05-03).
The main behavioral change/improvement here is that `copy-file` no longer yields an error result when the copied file doesn't have content and the destination repo is on an adjusted branch.
I've tested this locally with git-annex's e811a50e2 (2021-05-03).

Use fromkey to create unlocked files when supported

---

datalad/plugin/tests/test_plugins.py

This follows up on gh-5579.  There is now a fix on git-annex's end that addresses the original intermittent failure of `test_no_annex` (gh-5300).

test_no_annex: Update for git-annex-smudge fix

---

datalad/core/local/tests/test_save.py

git-annex's 424bef6b6 (smudge: check for known annexed inodes before
checking annex.largefiles, 2021-05-03) fixed a case where an unchanged
unlocked annexed file that does not match annex.largefiles gets sent
to git.
That change leads to a racy failure of test_partial_unlocked.  The
test unlocks a file and then configures .gitattributes so that the
file doesn't match annex.largefiles.  Before 424bef6b6, providing that
file as a pathspec to `git commit` (as `datalad save` does) results in
a commit where the file changes to being tracked by git.  With
424bef6b6, the above sometimes doesn't happen; instead the commit
includes the link to a pointer file change, and the change to being
tracked by git remains in the index.
This issue has been reported upstream.  For now, document it, and
adjust …

TST: test_partial_unlocked: Document and avoid recent git-annex failure

---

setup.py

With Sphinx 4.0.0 (released yesterday), the docs builds for maint and
master are failing (with different errors):
https://github.com/datalad/datalad/actions/runs/828244083
https://github.com/datalad/datalad/actions/runs/828227680
Hold off upgrading until the issues are resolved.

MNT: setup.py: Temporarily avoid Sphinx 4

---

datalad/core/local/tests/test_save.py

This reverts commit 501c9d0b655b6c26d49f273a81ebaab6f0a0db97.
The above commit worked around a racy test_partial_unlocked() failure
triggered by git-annex's 424bef6b6 (smudge: check for known annexed -
inodes before checking annex.largefiles, 2021-05-03).  Due to this
issue, 424bef6b6 has now been reverted and replaced by [8.20210428-95-g675556fd9](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=675556fd9)
(smudge: check for known annexed inodes before checking
annex.largefiles, 2021-05-10).

Revert "TST: test_partial_unlocked: Document and avoid recent git-annex failure"

---

datalad/customremotes/base.py
datalad/customremotes/tests/test_base.py
datalad/interface/download_url.py
datalad/interface/tests/test_download_url.py

As suggested in gh-5510, `download-url` should set up the datalad special remote if needed to avoid non-functional URLs.
It seems tricky to test this in `test_download_url`, though, assuming we don't want to hit a real endpoint.  For example, if we were to use `shub://`, patching for the initial download to point to the `serve_path_via_http` works, but then anything that involves the special remote (registering the URL, downloading it from another clone) wouldn't because that is of course in a separate process.

download-url: Set up datalad special remote if needed

---

datalad/core/local/create.py
datalad/core/local/tests/test_create.py
datalad/support/gitrepo.py

On the master branch, passing `git init` options to `create` no longer works:
```
$ datalad create . --template=/dev/null
[...]
error: unknown option `-from-cmdline-=--template=/dev/null'
```
That's fixed by the second commit.  The other two commits are minor cleanups in the area.

create, gitrepo: Restore handling of initopts list

---

datalad/local/subdatasets.py
datalad/local/tests/test_subdataset.py

I think that docstring was left from old(er) times whenever `git submodule` was
used to report the "state" of the subdatasets.  After it was replaced with
ad-hoc parsing of .gitmodules as far as I see it "state" no longer corresponds
to any of those values besides "absent", and we simply do not report any state
(as changed unittest shows) for "present" (a clear antonym to "absent")
datasets.  All those states are reported by "status" command though.  E.g.
compare:
$> datalad -f '{type} {path}: {state} {status}' --report-type dataset status -d . | grep dataset
dataset /tmp/testds3/mod-inited: clean ok
dataset /tmp/testds3/not-committed: added ok
dataset /tmp/testds3/not-mod-inited: clean ok
dataset /tmp/testds3/openneuro: clean ok
dataset /tmp/testds3/uninstalled: clean ok
to (with these …

BF(DOC)+RF: report "present" for the state of a present/installed/fulfilled (sub)dataset

---

docs/source/customization.rst
docs/source/modref.rst
setup.py

With the recent release of Sphinx v4, the doc build on master and
maint started to fail.  The failure on master was due to a bug in
Sphinx and fixed by v4.0.1.  The failure on maint is due to a warning:
docstring of datalad.support.constraints.EnsureChoice:1:duplicate
object description of datalad.support.constraints.EnsureChoice,
other instance in generated/datalad.plugin.add_readme, use
:noindex: for one of them
One our end, this is triggered by the combination of two things:
* many of the plugin modules have imports at the class level
* the documentation refers to these plugin commands via
datalad.plugin.NAME rather than datalad.api.NAME
The end result is that the plugin commands are not rendered like other
commands (e.g., no command parameters) and instead have a lot of noise
about …

DOC: Reference plugins via datalad.api

---

datalad/plugin/addurls.py
datalad/plugin/tests/test_addurls.py

As described in gh-4658, `addurls` gives a confusing error message if it can't derive fields like `_url_basename` from the provided URL field.  Check if a placeholder is a special key and give a more helpful message.

addurls: Provide better placeholder error for special keys

---

datalad/core/local/status.py
datalad/core/local/tests/test_status.py

When called with a path argument that points to a dataset and that
dataset has a parent dataset, status() checks if the original path
ends with "/".  No trailing separate indicates that the dataset as a
whole is of interest, leading to a query in the parent for that
dataset.
The above logic is confusing when `dataset` and `path` point to the
same dataset.  status() with a parent-less dataset works (and behaves
as the path argument ended with "/"), while a nested dataset fails
with
[ERROR ] dataset containing given paths is not underneath the
reference dataset [...]
3dea65a9b8 (BF: status: Provide special treatment of "." path,
2019-04-12) avoided the above error for the path="." case.  However,
the same error can be triggered by calling status() with a path
argument other than "." that …

status: Provide special treatment of "this dataset" path

---

datalad/distribution/tests/test_update.py
datalad/distribution/update.py

Tweak `update`s `fetch` call to
* avoid deprecated `kwargs`
* translate a `CommandError` to a result record
Closes #3278.
Closes #4154.

update: Honor --on-failure if fetch fails

---

datalad/plugin/tests/test_addurls.py

test_addurls_row_missing_key_fields() makes a shallow copy of the
`data` attribute (list of dictionaries) exposed to all TestAddurls
tests and then modifies one of the dictionaries to remove a key, which
of course modifies the row in TestAddurls.data.
Make a deep copy to avoid interfering with other tests.
---
As far as I know, this doesn't trigger any failures right now, but it will in an upcoming PR (against master).

BF: test_addurls: Avoid modifying shared test data

---

datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py

See #5628. We did not consider the recently introduced `push-url` of ORA
special remotes for matching against the clone URL. With this patch we
stick to the logic that tries a reconfiguration if either all known ORA
remotes failed to autoenable or none of the enabled ORA remotes have a
matching URL on record.
However, as pointed out in #5628, this only is a quick fix for a
particular usage pattern. A general solution for the reconfiguration
mess appears to be to switch to local configs only.

Fix post-clone reconfiguration for ORA remote

---

datalad/cmd.py
datalad/cmd_protocols.py
datalad/core/distributed/tests/test_clone.py
datalad/nonasyncrunner.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py
datalad/tests/test_nonasyncrunner.py
datalad/tests/test_witless_runner.py

PR for an non asyncio-based runner.
This patch implements a thread-based runner, that uses the asyncio protocol interface to communicate
process output to protocol instances. 
This change was done to support running datalad commands from processes within a concurrent.futures.ProcessPoolExecutor. This did not work reliably if the datalad command invoked subprocesses, and if asyncio-based subprocess were used. In the asyncio-based implementation processes would randomly wait forever on some synchronization primitive.
Motivation: I am creating a *pipeline*/*orchestration* command for metalad that allows a user to specify an information source element, e.g. a dataset-traverser, and a number of processing elements, e.g. a metadata-extractor and a metadata-adder, which would be run on the …

NF: implement a non asyncio-based runner

---

COPYING

inspired by #5685 
old mentions are being moved to -deprecated: https://github.com/datalad/datalad-deprecated/pull/25 where they are still (?) relevant

DOC: up-to-date COPYING

---

datalad/distributed/create_sibling_ria.py

#5679 showed, that the last remaining call to `subprocess.run` in
`create-sibling-ria` would fail w/o using `shell=True`. The issue is, that
there's nothing to ensure we run from within a sane environment.
Switch to use `WitlessRunner` in order to get the environment to run from
the same way as in every other place.
(Closes #5679)
Note: I'm aware we don't really test everything related to users/groups here. With current approach on testing RIA-related stuff (or anything happening on remote ends really), it's quite complicated and effortful to meaningfully test such aspects. I plan to look into a different setup, probably using a docker as the remote end, next week and will then care for rewriting/adding tests accordingly. For now, this change should not be objectionable even w/o a test …

BF: left-over subprocess call didn't use env

---

datalad/interface/common_cfg.py
datalad/interface/utils.py

```
% datalad x-configuration
...
datalad.ui.suppress-similar-results=True
datalad.ui.suppress-similar-results-threshold=10
...
```
```
% datalad -c datalad.ui.suppress-similar-results=off subdatasets 
...
subdataset(ok): HCP1200/993675 (dataset)
subdataset(ok): HCP1200/994273 (dataset)
subdataset(ok): HCP1200/995174 (dataset)
subdataset(ok): HCP1200/996782 (dataset)
subdataset (ok: 1113)
% datalad -c datalad.ui.suppress-similar-results=on subdatasets
subdataset(ok): HCP1200/100206 (dataset)
subdataset(ok): HCP1200/100307 (dataset)
subdataset(ok): HCP1200/100408 (dataset)
subdataset(ok): HCP1200/100610 (dataset)
subdataset(ok): HCP1200/101006 (dataset)
subdataset(ok): HCP1200/101107 (dataset)
subdataset(ok): HCP1200/101309 (dataset)
subdataset(ok): HCP1200/101410 (dataset) …
```

Make result suppression configurable

---

datalad/core/local/diff.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py
datalad/support/tests/test_fileinfo.py

This series makes
get_content_info(paths=[], ...)
different from
get_content_info(paths=None, ...)
That, in turn, makes `GitRepo.diff` and `GitRepo.status` match their documented behavior.
See gh-3292 and the second commit message for the details.

get_content_{annex,}info: Restrict full report to paths=None

---

datalad/support/annexrepo.py

get_content_annexinfo() calls _mark_content_availability() for each
file received from `git annex find{,ref}`.  This is unnecessary work
because _mark_content_availability() operates on the entire dictionary
of paths.  Delay the call until after get_content_annexinfo() has
constructed the entire dictionary from the `git annex find{,ref}`
information.

RF: get_content_annexinfo: Mark content availability just once

---

.appveyor.yml
.github/workflows/test_macos.yml
.travis.yml

master branch has its own ideas and binds to some older version
```
$> git grep datalad.installer
.appveyor.yml:  # deploy the datalad installer, override version via DATALAD_INSTALLER_VERSION
.appveyor.yml:      python -m pip install "datalad-installer%DATALAD_INSTALLER_VERSION%"
.appveyor.yml:      python -m pip install datalad-installer
.appveyor.yml:  - sh: python -m pip install datalad-installer${DATALAD_INSTALLER_VERSION:-}
```
needs yet to be addressed, decided to just go with maint for now and simplify (not versioned depends etc)

RF: just pip install datalad-installer

---

datalad/interface/tests/test_base.py
datalad/interface/utils.py

This series fixes (another) case where custom summary output was repeated.  The last commit contains the details, while the first one is just cleanup in the area.
---
Demo of the issue:
```python
import tempfile
import datalad.api as dl
ds = dl.Dataset(tempfile.mkdtemp(prefix="dl-")).create()
ds.status()
```
```
[INFO   ] Creating a new annex repo at /tmp/dl-w3q0odkp 
[INFO   ] Scanning for unlocked files (this may take some time) 
nothing to save, working tree clean
nothing to save, working tree clean
```

interface: Don't repeat custom summary for non-generator results

---

datalad/downloaders/credentials.py
datalad/downloaders/tests/test_credentials.py

Analysis and background in #5677
Closes #5677

Support credential query via config manager

---

datalad/local/addurls.py
datalad/local/tests/test_addurls.py

As mentioned in gh-4840, `addurls` doesn't provide the caller any help in troubleshooting file name collisions.  This series improves the error message and debugging output.  It also implements an option like the one suggested in gh-4840 that allows the caller to either 1) ignore collisions if the end result is the same or 2) specify that the first/last row should be used.
Closes #4840.
---
The tests in this series require the fix from PR gh-5674, which is against maint.  That PR is merged into this one.

addurls: Improve reporting and handling of file name collisions

---

.travis.yml
datalad/interface/common_cfg.py
datalad/interface/tests/test_run_procedure.py
datalad/support/annexrepo.py
datalad/tests/test_utils.py
datalad/tests/utils.py

This series of cleanups follows up on 315911ca76 (MNT: annexrepo: Bump minimum git-annex version to 8.20200309, 2021-03-18).

Cleanups related to new minimum git-annex version

---

datalad/core/distributed/push.py
datalad/core/distributed/tests/test_push.py
datalad/interface/tests/test_utils.py
datalad/interface/utils.py

gh-5660 mentions that it'd be good to see an action summary for `push` in addition to the custom summary.   The first three commits in gh-5689 _almost_ make that possible.  This draft series reworks those to show how it'd look for `push`.
---
<details>
<summary>script</summary>
```sh
set -eu
cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"
datalad create a
(
cd a
datalad create-sibling -s b ../b
echo one >one
datalad save
datalad push --to b
)
```
</details>
```
[...]
copy(ok): one (file) [to b...]                                                                                                                                                                                      
publish(ok): . (dataset) [refs/heads/git-annex->b:refs/heads/git-annex e1a64a0..aec5b08] …
```

push: render action summary too

---

datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

Closes #5702
Recently, somewhere around [8.20210428-186-g428c91606](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=428c91606b434512d1986622e751c795edf4df44)
git-annex changed its logic for doing initial scanning for
unlocked (and now locked?) files.  Now I do not observe that message
to be printed out and our tests started to fail in daily testing of
datalad/git-annex
https://github.com/datalad/git-annex/actions/runs/877176725 might be
the first one and version reported is 8.20210428+git228-g13a6bfff4
when previous green one was 8.20210428+git202-g9a5981a15
It seems that `annex init` might have got notably slower :-/ (attn
@joeyh), e.g.  our test tuned here here
python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_init_scanning_message
runs for 1.3s with …

BF: account for annex now "scanning for annexed" instead of "unlocked" files

---

datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

This resurrects and updates gh-3027, which was reverted in gh-3044 due to a stalling test.

annexrepo: Inform users about repo version auto-upgrades (try 2)

---

datalad/support/locking.py
datalad/support/tests/test_locking.py

Somewhat ad-hoc and makes an already confusing lock_if_check_fails even more so
by optionally changing its return signature. So eventually we might want
to RF this whole piece of code.  But I think it should work ok for now.
Anyways -- fasteners 0.16.x series might re-gain .acquired (see
https://github.com/harlowja/fasteners/issues/71) and we might want to see to RF
this PR properly if so instead of merging/releasing it right away.  But FWIW
Closes #5717

BF: do not use .acquired - just get state from acquire()

---

datalad/support/tests/test_annexrepo.py

probably happened at  [8.20210428-329-g7b6deb110](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7b6deb1109d315fffb2e8a856340f022ed3db249)

BF(TST): skip testing for showing "Scanning for ..." since not shown if too quick

---

datalad/local/add_readme.py
datalad/local/tests/test_add_readme.py

This improves the default template for `add-readme` using the content that @adswa created for the [DataLad Handbook](http://handbook.datalad.org/en/latest/basics/101-180-FAQ.html#how-can-i-help-others-get-started-with-a-shared-dataset).
Closes #5714

ENH: addreadme: improve default template

---

datalad/support/tests/test_annexrepo.py

I think it would still fit the purpose of the test (long lists of files) while possibly avoid annex taking too long to deal with 10,000 copies of the same file (unrealistic scenario IMHO).  We would still have 100 unique keys (not 10,000) so file system would not get tortured that heavily to populate all the `.git/annex/objects`.
Ref: https://git-annex.branchable.com/bugs/significant_performance_regression_impacting_datal/

ENH(TST): populate heavy tree with 100 unique keys (not just 1) among 10,000

---

.github/workflows/update-contributors.yml

It seems that now even github should support it if marker is in the commit
message: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
[skip ci]
not sure if my changes do not break it, I guess we will discover whenever it is merged. Meanwhile will see if [skip ci] works here

tributors: annotate commit and PR with [skip ci]

---

datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py

When a dataset is cloned into another one as a subdataset, we record the originally given URL in `.gitmodules`. This used to be a dedicated commit in addition to the one adding the new dataset as a subdataset. The former is now amended to the latter.

Reduce number of commits when cloning into a dataset

---

datalad/core/distributed/clone.py
datalad/core/distributed/push.py
datalad/core/local/create.py
datalad/core/local/diff.py
datalad/core/local/run.py
datalad/core/local/save.py
datalad/core/local/status.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/export_archive_ora.py
datalad/distribution/create_sibling.py
datalad/distribution/create_sibling_github.py
datalad/distribution/dataset.py
datalad/distribution/drop.py
datalad/distribution/install.py
datalad/distribution/publish.py
datalad/distribution/siblings.py
datalad/distribution/uninstall.py
datalad/distribution/update.py
datalad/interface/download_url.py
datalad/interface/rerun.py
datalad/interface/tests/test_annotate_paths.py
datalad/interface/unlock.py
datalad/local/copy_file.py
datalad/local/subdatasets.py
datalad/plugin/wtf.py

We had a mix, and even though "ing form was probably more prevalent, I felt that shorter
imperative form would be better, even though it would be not "for {purpose}" but
"to {purpose}" if to be displayed. (as eg in #5708)

ENH: harmonize "purpose" statements to imperative form

---

.zenodo.json
datalad/cmdline/helpers.py
datalad/interface/common_opts.py

Set and document default value "continue" for common argument --on-failure, and "default" for common argument --output-format
There was a comment that misleadingly stated for --on-failure: "no default: better be configure per-command". If this was true, we could not set or document a general default-value for --on-failure. I did not find per-command configurations, therefore I added the default value to the doc-string and as keyword argument
Fixes #4334

add --on-failure default value and document it

---

datalad/config.py
datalad/downloaders/base.py
datalad/interface/common_cfg.py

This introduces `datalad.locations.locks` to specify the location to be
used for (global) lock files. Defaults to the currently used
`<user cache dir>/locks`.
Closes #5706

Make lock file location configurable

---

datalad/distribution/create_sibling_github.py

Here's my attempt at reporting a sibling name when a GitHub sibling is created, as desired in #5711. Its not a separate key in the result, but merely added into the message, but I found that it looked quite crowded when I rendered several messages.
Here is the current look:

UX: Report the sibling name in create-sibling-github's results record

---

.appveyor.yml
.github/workflows/test_crippled.yml
.github/workflows/test_macos.yml
.github/workflows/test_win2019_disabled
.travis.yml
CONTRIBUTING.md
datalad/customremotes/base.py
datalad/dochelpers.py
datalad/interface/common_cfg.py
datalad/interface/test.py
datalad/support/exceptions.py
datalad/support/tests/test_captured_exception.py
datalad/tests/test_dochelpers.py

This is originally motivated by wanting to close #4478. So, there's a config `datalad.log.exc` now, that controls whether exceptions are "rendered" in log messages (and it's off by default).
However, once at it, I took the occasion to somewhat address our exception handling in general. When we catch and report on an exception, we pretty much always would use `exc_str` (or now `CapturedException`), providing an opportunity to let that also do the clean up of stack frame references and thereby somewhat enforcing it. Hence, decided against the proposed approach in the issue to extend the to-be-logged exception and pass it on, but introduced a class that represents the textual information about it (and its traceback) without any stack references. Remember: circular references. Furthermore, …

Introduce datalad.log.exc and disable exception logging by default

---

datalad/core/distributed/push.py
datalad/core/distributed/tests/test_push.py

This is an attempt to fix #5712. If
- a path is given, 
- but not ``--to``, 
- (a part of) the path matches a known sibling,
- and no matching files are found, 
``push`` reports "impossible" instead of "notneeded", and issues a hint to the user.
Before:
After:

Better hint when a sibling is provided without --to

---

datalad/local/add_readme.py
datalad/local/tests/test_add_readme.py

This PR sits on top of @loj's #5723, and configures the dataset to not annex the README, unless a user overrides this default with an ``--annex`` flag.
With this, it fixes #5713. The previous behavior (having a README file ~placed in Git~ annexed) can be achieved by running ``datalad add-readme --annex``.

Do not annex the README that add-readme generates

---

datalad/support/tests/test_parallel.py

so that consumers have a better chance to finish up at least some
jobs (we got assert_greater_equal(len(results), 2) failing), before
the whole thing fails and we raise right away (that is what this
portion of the test tests).
If this does not show to be a reliable workaround, since we do not
use  reraise_immediately=True  mode yet anywhere, I gues we could just
disable this portion of the test.
Closes #5746

BF(TST): parallel - take longer for producer to produce

---

paper.bib

The current bibliography item that gets rendered into the article is a bit wonky (including the publisher name, for example). I think that reclassifying this explicitly as an article may make the rendered bibliography item more conformant.

[JOSS review] Change bib classification of BIDS paper

---

.autorc
.github/workflows/release.yml
.github/workflows/test-label.yml
Makefile
docs/source/changelog.rst

Seems to need quite a bit of workarounds to get an .rst version. See diff comment in Makefile -- sphinx isn't that ready for unicode in section headings, eh heh
TODOs

BF: update changelog conversion from .md to .rst (for sphinx)

---

datalad/cmdline/main.py

This partially reverts the behavior change introduced with #5691.
It is universally not desirable to spit out empty error log message
even when exception logging is disabled by default. When this happens
in the outer shell of the cmdline interface, there is no further layer
to perform any kind of introspection. Instead, a user is left clueless
and without any information.
This change switches back to the old implementation for this outer
layer.
Fixes datalad/datalad#5761

BF: Make cmdline interface report exceptions again

---

datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py
datalad/distribution/tests/test_install.py
datalad/interface/common_cfg.py

This implements a simple feature and fix for #4822. It allows for configuring an arbitrary number of URL mapping specification. With this change one can configure datalad to transfer URLs like `https://osf.io/q8xnk/` (copied from a browser window), which do not work, but can be reliably mapped into working URLs (`osf://q8xnk` in this case) via a regular expression specification.
In the example above, this would do the trick:
```
datalad -c 'datalad.url.substitute.osf=,^https://osf.io/([^/]+)[/]*$,osf://\1' clone https://osf.io/q8xnk/
```
as usual, configuration is read from all supported places. Here is an example of a mapping rule
for GitHub
```
% datalad x-configuration
...
datalad.clone.url-substitute.github=(',https?://github.com/([^/]+)/(.*)$,\\1###\\2', ',[/\\\\]+,-', …
```

Clone URL mapping ability

---

datalad/cmd_protocols.py

This fixes #5774 
Thanks to @mih for catching the bug before the 0.15 release.
Due to a missing array dereferencing the complete hitherto buffered output data of a command execution was written into each log message that logged received data.

fix a bug in descriptor name rendering

---

setup.py

Fixes #4344
Adds `python-gitlab` to setup.py so that it does not have to be installed manually when users want to run `create-sibling-gitlab`

ENH (UX): add python-gitlab dependency

---

datalad/cmdline/tests/test_main.py
datalad/support/tests/test_external_versions.py

To partially address and provide more information to figure out details of https://github.com/datalad/datalad/issues/5785

Tests: Allow for version to contain + as a separator and provide more information for version related comparisons

---

datalad/__init__.py

A possible to encounter side-effect from using versioneer.  See
https://github.com/datalad/datalad/issues/5785
for more information.  Overall I take it to Closes #5785 
Results in
```shell
$> python -c 'import datalad'                    
[WARNING] DataLad was not installed 'properly' so its version is an uninformative '0+unknown'.
| It can happen e.g. if datalad was installed via
|   pip install https://github.com/.../archive/{commitish}.zip
| instead of
|   pip install git+https://github.com/...@{commitish} .
| We advise to re-install datalad or downstream projects might not operate correctly. 
```
I think that is good enough/better than nothing ;)
edit: fix for datalad/git-annex workflows is coming in https://github.com/datalad/git-annex/pull/72

ENH(UX,DX): inform user with a warning if version is 0+unknown

---

datalad/distribution/get.py
datalad/distribution/tests/test_get.py
datalad/distribution/tests/test_publish.py
datalad/distribution/tests/test_update.py

gh-5033 describes a situation where the installation of a sub-subdataset
fails due to the particular condition of the _checkout_ the subdataset
was cloned from. The issues originally expressed the desire for a more
in-depth exploration of possible superdatasets and their subdataset
configurations. However, the undesirable failure can also be avoided by
simply preferring the location information that is committed in each
superdataset, at all clone iterations on the way to a target subdataset.
Effectively, the change reorders the locations priorities from
1. Assumed availability within the assumed existing checkout of the
superdataset
2. Location info from .gitmodules
to
1. Location info from .gitmodules
2. Other candidates and guesses
Specifically, the following URLs will be tried by …

BF: Prefer committed subdataset location info over guesses

---

datalad/distributed/ora_remote.py

The ORA special remote's HEAD request was send w/o
`allow_redirects=True`, which defaults to False. This led CHECKPRESENT
requests to fail.
Closes #5616

BF: ORA incorrectly handled redirects

---

datalad/downloaders/credentials.py
datalad/downloaders/tests/test_credentials.py
datalad/interface/common_cfg.py

This change introduces a new configuration setting:
```
% datalad x-configuration
...
datalad.credentials.force-ask=False
...
```
It enables seamless updates of stored credentials. Importantly, users
are no longer required to learn where credentials are stored, and how to
update them in that store. It makes instructions provided in the
handbook on how to learn python `keyring` superfluous. Credential
updates are simply entered at the same place where the original
credentials were provided.
This is not a perfect solution (can get messy when there are a
number of credentials involved in a single datalad operation, and only a
single one needs updating), but it addresses a substantial usability
issue for a broad range of use cases in a straightforward manner.
Besides being compatible with the …

New config `datalad.credentials.force-ask` to force interactive credential updates

---

.appveyor.yml
.github/workflows/test_crippled.yml
.github/workflows/test_macos.yml
.github/workflows/test_win2019_disabled
.travis.yml
datalad/__init__.py

Exception logging is now disabled by default in datalad, but tests are
still making detailed assertions about what is logged how. Running them
currently requires that config to be set.
However, eventually tests need to be adjusted and enable the config
themselves, if they are making assertions about logged exceptions.
Closes #5758

Enable exception logging in test fixture

---

datalad/cmd.py
datalad/core/distributed/push.py
datalad/nonasyncrunner.py
datalad/support/gitrepo.py
datalad/tests/test_witless_runner.py

So far, a temporary file was necessary to pass input to a process's `stdin`
in `WitlessRunner` (need for `.fileno` in `subprocess.Popen`). This
enhancement adopts the subprocess `input=` implementation, and allows
for feeding input from a `str|bytes`, by writing its content to a stdin
pipe.
This enables a simplifications of the `push` implementation and reduces
the overall technical complexity of passing `stdin`.
As `WitlessRunner` presently operates the pipes in binary mode, input
must be given as bytes. However, the underlying implementation in
`run_command()` could handle strings as well, should `Popen` be
parametrized accordingly using custom arguments.
This PR include two cleanup commits that are essentially unrelated.

ENH: Supply stdin to process without a tmp file

---

datalad/distributed/create_sibling_gitlab.py
datalad/distributed/tests/test_create_sibling_gitlab.py

Before `datalad create-sibling-gitlab .` would just do nothing.
Now the root dataset is processed if a given path matches it.
Fixes datalad/datalad#5763

BF: create-sibling-gitlab: do not skip root dataset when path is given

---

datalad/downloaders/base.py
datalad/downloaders/http.py

Closes #5801  although I believe it is no longer an issue -- wikipedia seems to no longer mind any bad User-Agent (at least for me locally as of a few minutes back). But I think it would be nice/proper to provide detailed user-agent string.
See individual commits for more information

http downloaders: Provide custom informative User-Agent, do not claim to be "Authenticated access"

---

datalad/cmdline/helpers.py
datalad/cmdline/main.py
datalad/cmdline/tests/test_helpers.py
datalad/cmdline/tests/test_main.py
datalad/interface/__init__.py
datalad/interface/base.py

Decided to look into our glorious cmdline parsing setup code and to wrap my head around the logic did some minor house-keeping refactoring, primarily consisting of moving some code into helper functions to make it clear(er) what any particular code block affects/provides.  It is still ugly-ish but IMHO a bit easier to follow.
There should be no changes in functionality or timing of execution (although didn't test for timing).  
The only functionality changing commit is the one dealing with parsing of overrides.
Individual commits provide more information.

RF cmdline/main.py to make the main logic a bit more readable/succinct

---

datalad/support/exceptions.py

The new phrasing should better cover the case of an existing installation
that is nevertheless broken, and fails an import test.
Fixes datalad/datalad#5729

Adjust wording of MissingExternalDependency error

---

datalad/distribution/siblings.py
datalad/distribution/tests/test_siblings.py

This PR adds a ValueError that is raised as a validity check when a user supplies identical names for a remote sibling name and the autoenabled as_common_datasrc special remote, as done in #5621.
Fixes #5621

UX: Check argument validity of --as-common-datasrc name

---

datalad/tests/test_witless_runner.py

Stops printing of 240000 characters during witless-runner tests.

Fix log flooding during witless-runner tests

---

datalad/local/tests/test_wtf.py
datalad/local/wtf.py

This potentially closes #5731. It adds a section "branches" to the dataset report of ``datalad wtf``, and reports all branches using the format ``<branch>[@<commit>]``.
For example:
```
(handbook2) adina@muninn in ~/repos/datalad on git:ux-5731
❱ datalad wtf
- keyring: 
- active_backends: 
- SecretService Keyring
- PlaintextKeyring with no encyption v.1.0 at /home/adina/.local/share/python_keyring/keyring_pass.cfg
- config_file: /home/adina/.config/python_keyring/keyringrc.cfg
- data_root: /home/adina/.local/share/python_keyring
- full_version: 0.14.4.dev496-g61bc
- version: 0.14.4.dev496
- branches: 
- appveyor[@618f99e]
- bf-4359[@b0a4458]
- bf-flexibleclonecandidates[@73cbe11]
- bf-git-gc[@9e17649]
- doc-get[@d91c19e]
- doc-joss[@5a49c20]
- enh-addreadme[@96d0a68]
- …
```

UX: Report branch names and states in WTF report

---

datalad/cmdline/tests/test_main.py

Awhile back we did switch away from creating our own entry point
scripts, and just succumbed to all the goodness default mechanisms
give us.  We had to skip this test on debian builds, where we have
to run something like   setup.py develop  to produce those entry points
for the tests.  That added up burden etc.  So I decided we should no
longer bother with such tests, also because pkg_resources now used
just as a fall back in those produced by setuptools, so typically there
should be no big penalty in start time.
Closes #5384

RF(TST): do not test for no EASY and pkg_resources in shims

---

_datalad_build_support/setup.py

Bug introduced by myself in https://github.com/datalad/datalad/pull/5669 ,
which forbids building debian package on systems with python3 >= 3.8
where we do not (as should not) require importlib_metadata backport.

BF: import importlib.metadata not importlib_metadata whenever available

---

datalad/distributed/ora_remote.py

In a local ORA remote, ``whereis`` only reported the object key:
```
(magma) adina@cpu12 in /data/group/psyinf/processing-workflow-tutorial on git:master
❱ git annex whereis fmriprep/sub-01/anat/sub-01_desc-brain_mask.nii.gz 
whereis fmriprep/sub-01/anat/sub-01_desc-brain_mask.nii.gz (3 copies) 
c034a599-5db4-4212-8c2f-5d1bfaa0af5c -- adina@juseless:/data/group/psyinf/processing-workflow-tutorial [here]
c564c916-629f-4bb8-8113-01a3b04d7a51 -- gin [gnode]
d8807e1f-25ef-4267-a5b9-698eae068b4c -- [output-storage]
output-storage: Pv/77/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz
``` 
(reported in https://github.com/datalad/datalad/issues/4979#issuecomment-885170380).
This PR tries to fix this. 
Fixes #4979

BF: Fix reported paths in ORA remote

---

datalad/cmdline/tests/test_main.py
datalad/support/exceptions.py

When a `CommandError` bubbles up to the main entrypoint it is rendered
differently than anywhere else (calls `to_str()` with
`include_output=False`. This is done to be able to write the
`stdout|err` output of a failed command to the proper channels. However,
this also caused all information extraction from JSON records to be
disabled.
This change, makes sure that JSON records are processed even in this
case. It also RFs the exception rendering code to make it less
repr()-like.
From:
```
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to expdir --fast --json --json-error-messages --json-progress -c annex.dotfiles=true' failed with exitcode 1 under /tmp/testds
git-annex: copy: 2 failed
```
To:
```
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch …
```

BF: Report info from annex JSON error message in CommandError

---

datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ria_basics.py

URL keys contain slashes. POSIX filenames must not. However, the key string was previously used as-is for a file/dirname.
The change introduces a mapping method for problematic keys, that might need to be extended in the future.
The first two commits introduce a test, and fix another issue that was triggered by the broken handling of URL keys.
Fixes #4336
Fixes #5504
Fixes #5822

Make ORA compatible with URL keys

---

datalad/cmd.py
datalad/cmd_protocols.py
datalad/core/distributed/tests/test_clone.py
datalad/nonasyncrunner.py
datalad/support/tests/test_gitrepo.py

For the non-async Runner and its protocols.
Log levels:
- Matching log levels for start and end of an event
- High-level execution -> debug
- Process start/finish -> 8
- Threading and IO -> 5
Exemplary output at log-level 1:
```
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config'] (cwd=/tmp/some) 
[Level 8] Process 110667 started 
[Level 5] ReaderThread(<_io.FileIO name=22 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) started 
[Level 5] ReaderThread(<_io.FileIO name=22 mode='rb' closefd=True>, <queue.Queue object at 0x7faa7f55ed00>, ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/some/.datalad/config']) exiting (stream end) …
```

RF: Normalize logging (levels) for process execution

---

CITATION.cff

This was auto-generated from the DOI of the DataLad JOSS paper.
https://scholia.toolforge.org/doi/10.21105/joss.03262
->
https://scholia.toolforge.org/work/Q107394509
->
https://scholia.toolforge.org/work/Q107394509/export
CI runs are canceled.

Add citation info (for github widget)

---

datalad/tests/test_version.py

Did not do deep analysis why we did not hit this failing test before

BF(TST): no codename in CHANGELOG entries any longer

---

datalad/core/distributed/tests/test_push.py

The test helper mk_push_target creates a sibling dataset by
creating an unrelated dataset and adding it as a sibling. On
Windows, this was not straightforward, as the datasets had
unrelated histories due to the initial adjusted branch commit
in the target dataset. Until git-annex version 20210720, a git
annex sync would establish a shared history - more recent versions
of git-annex will fail to sync unrelated histories unless
--allow-unrelated-histories is set.
With this patch, the tests that started to fail on Windows in #5811 pass again.
Fixes #5811.

TST: set --allow-unrelated-histories in the mk_push_target setup for Windows

---

datalad/support/gitrepo.py
datalad/support/tests/test_gitrepo.py

Current `.gitattributes` files have this weird structure of an empty line at start and no newline at end. This looks ugly when the files are viewed in terminal.
The solution is very simple and doesn't seem to break anything.

Append (not prepend) a newline character(s) to .gitattributes for prettier appearance

---

datalad/downloaders/configs/nsidc.cfg
datalad/downloaders/http.py
datalad/downloaders/tests/test_http.py

Closes #5846
needs provider config like
```
[provider:NSIDC]
url_re = https://.*\.nsidc.org/.*
authentication_type = http_auth
credential = NSIDC
[credential:NSIDC]
type = user_password
```
attn @mankoff - might like to try. Note that since our "User-Agent" is still discriminated, you must create that provider file first since datalad will not receive 401 and thus will not prompt you to setup a provider
TODOs
- not yet sure about a more proper/long-term RF on handling various auth schemes better and automatically selecting one, see original issue for more thoughts/info

BF: http_auth - follow redirect (just 1) to re-authenticate after initial attempt

---

datalad/distribution/get.py
datalad/distribution/tests/test_get.py

This is cherry-picked from #5644 because it fixes an issue unrelated to that PR. If someone ends up with two configurations for source candidates with identical names, one would see
```
❱ datalad get HCP1200/100206                                                1 !
[ERROR  ] 'tuple' object has no attribute 'format' [get.py:_get_flexible_source_candidates_for_submodule:240] (AttributeError) 
```
With this change, a user gets a more helpful error message:
```
❱ datalad get HCP1200/100206                                                2 !
[ERROR  ] There are multiple URL templates for submodule clone candidate 'origin', but only one is allowed. Check your configuration! [get.py:_get_flexible_source_candidates_for_submodule:245] (ValueError) 
```

UX: When two or more clone URL templates are found, error out more gracefully

---

datalad/customremotes/archives.py
datalad/customremotes/tests/test_archives.py
datalad/interface/clean.py
datalad/interface/tests/test_clean.py

There are several places where temporary files could be left by datalad operations. `datalad clean` now comes with a `--dry-run` option to just report on what could be cleaned.
Furthermore, the `datalad-archives` special remote now issues an INFO message to annex when it's actually extracting an archive in order to let a user know they may want to call `datalad clean` afterwards. This should make the presence of an extraction cache less surprising to users and make them aware of the `clean` command.
The issue leading to this PR and the discussion therein is #5519, although this is not actually solving it. However, at least this is an improvement of the UX aspect of the issue.
Closes #5834

Dry run option for clean command

---

datalad/distribution/dataset.py
datalad/distribution/get.py

I have seen those reported by users, and I must confess that some of those stem from the confusing interface of `install` + RFing which lead `install`/`get` to unable to operate on arbitrary paths (#3759).  But I think that such error might come up in other use-cases as well.  So before this PR users might get:
```shell
$> datalad install git://github.com/dl-throwaway/test_gh3 dest                                   
[INFO   ] scanning for unlocked files (this may take some time)                                           
[INFO   ] Remote origin uses a protocol not supported by git-annex; setting annex-ignore                  
install(ok): /home/yoh/.tmp/test_gh3 (dataset)
[ERROR  ] No dataset found at '/home/yoh/.tmp'.  Specify a dataset to work with by providing its path via the …
```

ENH(UX): state original purpose in NoDatasetFound exception + detail it for get

---

datalad/local/addurls.py
datalad/local/tests/test_addurls.py

When `addurls` creates a subdataset, the `create` result, as shown by the default renderer, doesn't make it clear which subdataset was created:
<details>
<summary>script</summary>
```sh
set -eu
cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"
datalad create >/dev/null 2>&1
datalad -lwarning \
addurls -x '' --key='{key}' -t csv \
- '{url}' '{_url_basename:.2}//{_url_basename}' <<EOF
key,url
SHA256E-s8669--a1954d14daa74af097d5cb1c65efaadb781f1924f42e31ac6dc5af57e4a8e955.svg,http://handbook.datalad.org/en/0.12/_images/install.svg
SHA256E-s49162--13c1bcb98945af4c51082b7431de291f509d2e25edf9e14631a27bc548d9eaa1.svg,http://handbook.datalad.org/en/0.12/_images/student.svg
EOF
```
</details>
```
create(ok): . (dataset)
fromkey(ok): /tmp/dl-JhgrkS0/in/install.svg (file) [registered URL]
create(ok): …
```

addurls: Improve result displayed for subdataset creation

---

datalad/support/keyring_.py

Happened to me: a number of days ago I had to workaround a pip issue https://github.com/pypa/pip/issues/7883 for which Q&D workaround was just
to export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring .
Then I lived happily ever after (since 1-May?), probably even datalad download-url
was just reusing prior cookies etc.  But while troubleshooting earthdata
data access, I was at WTF stage that datalad kept asking for
credentials, and there were no visual feedback on a reason.
Diff is trivial and IMHO safe, so made it against `maint`

ENH(UX): warn user if keyring returned a "null" keyring

---

docs/source/basics.rst
docs/source/design/dataset_argument.rst
docs/source/design/index.rst
docs/source/glossary.rst
docs/source/index.rst

This is no revolutionary re-design. It merely moves existing information
into a standalone document -- and strips incorrect information.
This also works towards datalad/datalad#5862

DOC: Design document for the `dataset` argument

---

datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py

While extending test with SSH RIs I realized that
`(a + b if False else d) == d`, so in effect those example URLs
were tested only on Windows.  I have made it a bit more explicit so
we do not fall into this trap again.
Closes #5880
- I am really not sure yet how we haven't ran into this bug before, since cloning over ssh while resorting to a default name should be a common task.
- I think that we could further improve `_get_installationpath_from_url` to avoid any class checks.  Logic should not rely on the class, but rather on either `path` is provided IMHO.  I might submit a follow up PR against master, wanted to keep this PR to the point

BF: take path from SSHRI, test URLs not only on Windows

---

.travis.yml

Individual commits say more.  I do not expect any effect on coverage.

.travis.yml: use python -m {nose,coverage} invocations, and always show combined report

---

datalad/cmdline/tests/test_main.py

By no means I did thorough investigation but
- test currently fails on cron (and locally) if I do have 8.20200309 installed
- last change to that line/logic is from later -- so I decided to go with that one
$> git blame Remote/Helper/ExportImport.hs | grep 'use .git-annex export'
9a2c8757f3 Remote/Helper/ExportImport.hs (Joey Hess 2020-12-18 14:52:57 -0400 153) 					then giveup "remote is configured with exporttree=yes; use `git-annex export` to store content on it"
$> git describe --contains 9a2c8757f3
8.20201129~30^2~22
someone else is welcome to bisect closer if that is not the version
refs:
- prior discussion https://github.com/datalad/datalad/pull/5809#issuecomment-885585730
- Closes #5879

BF(TST): Boost version of git-annex to 8.20201129 to test an error message

---

datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ora_http.py

Restructure ORA remote's `HTTPRemoteIO` to remove special cases in ORA's code, where HTTP is treated somewhat differrent than SSH or local access.
For RIA stores, this leads to the `ria-layout-version` files being required to be served as well (which technically wasn't the case before). It also means that the request URLs now use paths for annexed objects according to the specified layout, whereas before we'd always send the same request and it was up to the server to consider its layout and deliver the right thing.
HTTP stores are validated on `annex initremote`/`annex enableremote` the same way they are when using `ssh:` or `file:` scheme URLs. Therefore, autoenabling will fail under the same conditions, making `clone`'s reconfiguration business consistent across access methods.
Closes …

Overhaul ORA remote's HTTP access to RIA stores

---

datalad/core/local/create.py

leftover from #5426 
needs datalad-metalad release IIRC

RM: deprecated no_annex Python API option

---

datalad/tests/test_nonasyncrunner.py
datalad/tests/test_witless_runner.py

This implements the suggestion made by @adswa in #5870. 'echo' is a
shell built-in, so call it with a shell.
Fixes #5870
Plus some minor changes to make other test code for the runner run on windows.

Use platform-appropriate "echo" calls in tests

---

datalad/core/distributed/push.py
datalad/support/annexrepo.py

As discussed in gh-5808 the unconditional use can lead to problematic
error reporting. @yarikoptic's verdict was to maintain the behavior, but
limit it to data transfer commands.
This change implements this move and enables this datalad-specific
default only for `get` and `copy` operations. The latter is not
implemented in `AnnexRepo.copy_to()` because this method is only used
internally in tests, partially broken (gh-5903), and was deprecated in
Apr 2021. Instead, the change is implemented directly in `push`.
Fixes datalad/datalad#5808

Limit use of default annex.retry=3 to `get` and `copy` operations

---

datalad/customremotes/ria_utils.py
datalad/customremotes/tests/test_ria_utils.py

Previously only the hostname was retained for performing, e.g. SSH-based
logins, making it required to use an appropriate SSH config.
While not using such properties in RIA URLs is advisable, silently
stripping such information is a bug. Moreover, other mechanisms such
as HTTP (or a future FTP support) may not have equivalent configuration
analogs. Using such a core helper as `verify_ria_url()` to silently
remove information seems inappropriate.
A more comprehensive test is included.
Fixes #5475

Support username, password and port specification in RIA URLs

---

datalad/distributed/create_sibling_gitlab.py

Issue
```
% datalad create-sibling-gitlab --site gitlab.com
create_sibling_gitlab(error): . (dataset) [No project path specified, and no configuration to derive one]
% datalad create-sibling-gitlab -h
Usage: datalad create-sibling-gitlab [-h] [--site SITENAME] [--project NAME/LOCATION]
[--layout {hierarchy|collection|flat}] [--dataset DATASET] [-r] [-R LEVELS]
[-s NAME] [--existing {skip|error|reconfigure}] [--access {http|ssh|ssh+http}]
[--publish-depends SIBLINGNAME] [--description DESCRIPTION] [--dryrun]
[PATH ...]
```
The error message is hinting at a missing PATH, but --project is
required instead.
This change standardizes on using the terms from the existing metavar
spec, in the docs and the error message to reduce the confusion:
```
create_sibling_gitlab(error): . (dataset) [No …
```

Clarify error message re unspecified gitlab project

---

datalad/distribution/siblings.py

`None` was declared as supported `action`, but if given, would cause a crash.
Synopsis went from
```
Usage: datalad siblings [-h] [-d DATASET] [-s NAME] [--url [URL]] [--pushurl PUSHURL] [-D DESCRIPTION] [--fetch]
[--as-common-datasrc NAME] [--publish-depends SIBLINGNAME] [--publish-by-default REFSPEC]
[--annex-wanted EXPR] [--annex-required EXPR] [--annex-group EXPR] [--annex-groupwanted EXPR]
[--inherit] [--no-annex-info] [-r] [-R LEVELS] [--version]
[ACTION]
```
to
```
Usage: datalad siblings [-h] [-d DATASET] [-s NAME] [--url [URL]] [--pushurl PUSHURL] [-D DESCRIPTION] [--fetch]
[--as-common-datasrc NAME] [--publish-depends SIBLINGNAME] [--publish-by-default REFSPEC]
[--annex-wanted EXPR] [--annex-required EXPR] [--annex-group EXPR] [--annex-groupwanted EXPR]
[--inherit] …
```

Fix argument-spec for `siblings` and improve usage synopsis

---

datalad/downloaders/tests/test_credentials.py
datalad/support/keyring_.py

Fixing bug leading to a crash: We have pairs or more in composite
credentials. If user saved some but not all of them, then upon renew whenever
we try to delete them all we would crash here since keyring cannot delete the
ones it does not yet know.  So the easiest (although adhoc due to need to match
msg) is to handle such an exception.
To get it tested, I had to use a "real" keyring's backend (so they are called),
and for that I had to RF our Keyring helper class to be capable of being
provided a keyring backend instance (or in other words -- a "keyring").  An odd
logic abit I left behind is that even though we are now explicitly asking for
what keyring will be used, so we could store/use that instance if no explicit
backend is provided, but for consistency with current behavior (since …

BF: do not crash, just skip whenever trying to delete non existing field in the underlying keyring

---

datalad/distribution/siblings.py

Before this change, siblings() would exclusively rely on result logging to
communicate with a user. While this might have been enough a few years
ago, it is now an outlier behavior.
This change simply calls the default renderer for all results that the
custom renderer cannot handle (and previously silently ignored).
Fixes datalad/datalad#5147

Render siblings()'s non-ok results with the default renderer

---

datalad/downloaders/base.py
datalad/support/locking.py
datalad/support/tests/test_locking.py

I think it could be considered to resolve #5099 - user will be given INFO level log messages (just now realized -- may be the last one at least should be a warning??? or should we have a progress bar? ;-)) with all possible information we can provide, even which processes have that lock ATM (well -- might not universally work... windows - I am talking to you).
I also decided that "heck with that locking" if we fail to get the lock within 5 minutes!  at least this way may be some processes would complete (but possibly hide the problem).
Please see individual commits for more information.  It seems to come out to be again yet another "one time use locking helper", but since we have not come up with a better way to address this locking "issue", I think it is a small price to pay ;)
- [-] I …

Download session/credentials locking -- inform user if locking is "failing" to be obtained, fail upon ~5min timeout

---

datalad/distribution/siblings.py
datalad/distribution/tests/test_siblings.py
datalad/support/gitrepo.py

The diff looks massive, but looking at individual commits should tell a simpler story.
Key changes:
- coverage boost from 77% to 90% (see below)
- `--as-common-datasrc` working again, and tested from now (fixes: #4697)
- fixed `GitRepo.remove_remote()` to issue the expected exception when trying to remove a non-existing remote (also covered by a test now)
- fix crash with invalid `dataset` argument (fixes #5626)
Individual fixes could have been PR'ed against `master`. However, this whole thing sparks no joy and I am happy to have come to this point. I do not plan on further improvements. There is more to do, even after #5913 and #5915. Importantly #5914. The changes included here should make incremental improvements simpler. But I have to detach for now.
```
DATALAD_TESTS_SSH=1 python -m …
```

Some love and fixes for `siblings`

---

datalad/support/tests/test_locking.py

Closes #5918
An alternative (or complimentary) would be to move psutil from
devel extra depends to some component of default install_requires dependencies, WDYT?
Meanwhile, addressing on datalad/git-annex by installing it: https://github.com/datalad/git-annex/pull/75

BF(TST): Skip testing for having PID listed if no psutil

---

.pre-commit-config.yaml
pyproject.toml

Add isort config to match current convention + run isort via pre-commit (if configured)

---

datalad/cmdline/helpers.py

Instead of 
```
$> datalad
error: too few arguments
usage: datalad [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version] [--dbg] [--idbg] [-c KEY=VALUE]
[-f {default,json,json_pp,tailored,'<template>'}]
[--report-status {success,failure,ok,notneeded,impossible,error}]
[--report-type {dataset,file}] [--on-failure {ignore,continue,stop}] [--cmd]
command [command-opts]
```
and being puzzled on "what next" until they realize they need to run apparently non-listed above`--help`:
```
$> datalad
error: too few arguments, run with --help to get more information.
visit: https://www.datalad.org https://docs.datalad.org https://handbook.datalad.org
usage: datalad [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version] [--dbg] [--idbg] [-c KEY=VALUE]
[-f …
```

Provide a few more hints whenever user just runs `datalad`

---

datalad/distribution/siblings.py
datalad/distribution/tests/test_siblings.py

These new properties in the result record are prefixed with `annex-`, as
are all other such annex-related properties that where reported so far.
Example
```
{
"action": "query-sibling",
"annex-archive-id": "2bc339c2-153e-4f0e-8765-0743921ca6de",
"annex-autoenable": "true",
"annex-availability": "GloballyAvailable",
"annex-cost": "200.0",
"annex-description": "[pmacs-ria-storage]",
"annex-encryption": "none",
"annex-externaltype": "ora",
"annex-name": "pmacs-ria-storage",
"annex-timestamp": "1629126840.298837171s",
"annex-type": "external",
"annex-url": "ria+ssh://humbug@juseless.inm7.de/tmp/store2",
"annex-uuid": "386e24bd-ad4f-4638-8c17-2cb94a560b56",
"name": "pmacs-ria-storage",
"path": "/tmp/some",
"refds": "/tmp/some",
"skipfetchall": "true",
"status": "ok",
"type": "sibling"
}
``` …

Let `siblings()` report on annex special remote configuration

---

datalad/interface/common_cfg.py
datalad/interface/utils.py

Previously, messages with 'impossible' and 'error' status were logged
at WARNING and ERROR level respectively (by default). gh-3754 introduced
the config switch `datalad.log.result-level` to change this behavior,
but kept the default behavior.
This change makes DEBUG-level logging the default, and keeps the
previous default accessible as a 'match-status' mode.
Rational: Logging behavior can be configured in many ways, including
making it disappear from a user's point of view. Therefore it cannot be
relied on for critical messaging of _results_. Consequently, result
renderers perform their own messaging, ultimately leading to
double-reporting of errors and warnings in many default setups (see
gh-3752). Moreover, higher-level commands may later act on non-OK
results with recovery or …

Log result record message at DEBUG level by default

---

.github/workflows/release.yml

Pass `--no-changelog` to `auto shipit` if changelog already has entry

---

datalad/utils.py

Apparently the issue observed with elderly python 3.4 (no longer
supported) on Debian system, is likely to do nothing with the
Python but some peculiarity of the system since now was observed on
CentOS conda env with Python 3.9.
Since our hardcoded limits are quite generous, and 3.4 is no longer
support anyways, I decided just to add "flexible"  check that if
returned value is a million times larger (still have a buffer of
thousand times in this particular case) -- take hardcoded value.
Closes #5943

BF: limit CMD_MAX_ARG if obnoxious value is encountered.

---

datalad/interface/utils.py

Introduced by an incomplete replacement in 3a8fd827a8bb21bee91815fe133422356aedf777
Fixes datalad/datalad#5959

BF: use `==` not `is`

---

.appveyor.yml

Each build now uses 9 jobs/workers, out of 10 available with a target runtime of ~45min.

Consolidate appveyor setup (fewer jobs, recent git-annex on linux)

---

datalad/metadata/extractors/datalad_core.py

Annotate datalad_core as not needing actual data -- just uses annex whereis

---

datalad/support/annexrepo.py

Initially observed while giving a live demo (kheh kheh -- always the best time
to find bugs) on DANDI datasets such as
http://github.com/dandisets/000029, e.g.:
(git-annex)lena:/tmp/000029[tags/0.210806.2112^0]git
$> datalad get sub-anm36996*
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
[ERROR  ]   download failed: Not Found
Total:   0%|                                                             | 0.00/20.7M [00:12<?, ? Bytes/s]
Get …

BF(UX): do not keep logging ERROR possibly present in progress records

---

datalad/interface/add_archive_content.py
datalad/interface/tests/test_add_archive_content.py
datalad/tests/test_utils.py
datalad/tests/utils.py
datalad/utils.py

If ever to be finished, closes #5929 .  For now just establishes a test to demonstrate the failure (in future - test the fix).
May be it is not worth even attempting in `maint` but rather RF add-archive-content (it is one of the oldest, doesn't have `--dataset` argument etc) in `master` and likely drop going through the datalad-archives support code (and its caching mechanism), which only sees annex'ed keys at that level.

BF?: add-archive-content on .xz and other non-.gz stream compressed files

---

datalad/support/tests/test_globbedpaths.py
datalad/support/tests/test_network.py

OBSCURE_UNICODE should be used since otherwise tests would
just keep crashing while running on file systems/environment
which do not support those fancy characters.
Initial intention here was to address some Windows fails on Vista and
other elderly systems.  https://github.com/datalad/datalad/issues/2929
If tests pass on current CI I would assume that we are past that
stone age.
Closes a part of #5942.  ~~Wanted first to see if there are side-effects~~

BF: do use OBSCURE_FILENAME instead of hardcoded unicode

---

datalad/cmdline/common_args.py
datalad/cmdline/helpers.py
datalad/cmdline/main.py
datalad/interface/base.py
docs/source/basics_cmdline.rst.in

Was deprecated with the 0.15.0 release, see gh-5956.
Fixes datalad/datalad#5962

Remove deprecated --pbs-runner cmdline option

---

datalad/distributed/tests/test_ria_basics.py
datalad/tests/test_nonasyncrunner.py

Detected while building Debian package .
Also did isort on those tests files

BF(TST): use sys.executable, mark test_ria_basics.test_url_keys as requiring network

---

datalad/nonasyncrunner.py

Even a `datalad --version` leave open file descriptors around. This
change closes all FDs after a process has exited and any
protocol-based post-processing has completed.
I am not at all confident that this should be done unconditionally,
though.
Run `PYTHONDEVMODE=1 datalad --version` to see the pre/post effect.
Closes #5965

Close file descriptors after process exit

---

datalad/distribution/dataset.py

This might be not the most elegant but the "easiest" in DX approach to resolve
this issue IMHO.  It might cause run time penalty though in small scripts which
import only a few dedicated modules, thus do not require import of the entire
API.
An alternative would be to e.g. do 2 rounds of that loop, importing datalad.api
only upon the end of the first loop if no meth is found.
Closes #5990

ENH: import datalad.api to bind extensions methods for discovery of dataset methods

---

datalad/downloaders/base.py

Observed initially by @jwodder on
https://github.com/datalad/datalad-fuse/pull/3#issuecomment-921934544
since datalad-extensions-template default workflow runs on a crippled FS.
I think it makes sense to fail regardless either it is existing file or a
(broken) symlink since the idea is not to override a (possibly annexed) file

BF: downloader - fail to download even on non-crippled FS if symlink exists

---

datalad/core/local/status.py

Matching the diff_dataset() helper.
I had this change lying around locally. it makes using status-functionality internally more convenient.

RF: Promote internal status() helper with docs, and breadth-first reporting

---

datalad/interface/base.py
datalad/interface/tests/test_base.py

Without this change, applying `@build_doc` to a class whose docstring doesn't end in a newline, like so:
```python
@build_doc
class Foo(Interface):
"""Foo all the bars"""
@staticmethod
@eval_results
def __call__():
pass
```
will result in `__call__` getting a docstring that starts out with:
```
Foo all the bars
Parameters
----------
```
and the lack of a newline between the class docstring and "Parameters" will result in Sphinx producing a warning when trying to build the documentation for the class.  This PR fixes this behavior by ensuring that, if the class docstring doesn't already end with a newline, one is added, so that there are always at least two newlines (i.e., one blank line) before the "Parameters" header.

Ensure there's a blank line between the class `__doc__` and "Parameters" in `build_doc` docstrings

---

datalad/distributed/create_sibling_gitlab.py

This harmonizes the reporting of create-sibling-gitlab and the
create-sibling-ghlike-commands slightly more, and fixes #6016.
Here is how it looks with the change:
```
(handbook2) adina@muninn in ~/repos/datalad on git:ux-6016
$ datalad create-sibling-gitlab  -d . --site jugit --project datalad3 --layout flat --access ssh         
create_sibling_gitlab(ok): . (dataset) [sibling repository 'jugit' created at https://jugit.fz-juelich.de/adswa/datalad3]
configure-sibling(ok): . (sibling)
configure-sibling (ok: 1)
create_sibling_gitlab (ok: 1)
```
which is closer to what I get when using ``create-sibling-github``:
```
$ datalad create-sibling-github new-create-sibling-command-gh4                 
create_sibling_github(ok): [sibling repository 'github' created at …
```

UX: Report GitLab weburl of freshly created projects in the result

---

datalad/distributed/create_sibling_gitlab.py
datalad/distributed/tests/test_create_sibling_gitlab.py

This tries to be a fix for #6014. It adds a safe-guard to check whether a sibling-name to-be already exists, and errors out instead of overwriting it. I believe that this should be non-controversial, as it mirrors the way the other ``create-sibling-``s work. However, the comments seem to indicate that there is something special going on with GitLab, and the tests required some larger changes. I would therefore be very grateful if @mih (who has written code I have now changed) could check my changes carefully.

BF: Do not overwrite existing sibling configurations with create-sibling-gitlab

---

datalad/log.py
datalad/tests/test_log.py
datalad/utils.py

First commit actually enhances the test to optionally (if env var set) ensure that and reporting about open files for `DATALAD_ASSERT_NO_OPEN_FILES=assert` runs. 2nd commit then fixes the underlying issue of ProgressHandler not closing the "other" handler upon close.

BF: ProgressHandler - close the other handler if was specified

---

datalad/distributed/create_sibling_ghlike.py

Simply relay the error message, if there is any.
```
datalad create-sibling-gogs --credential gogs --api https://try.gogs.io mike1
create_sibling_gogs(error): [initRepository: init repository: exit status 128 - fatal: cannot copy '/usr/share/git-core/templates/hooks/pre-applypatch.sample' to '/mnt/volume_nyc1_01/gogs-repositories/dataladtester/mike1.git/hooks/pre-applypatch.sample': No space left on device]
```
Fixes datalad/datalad#6018

Add dedicated HTTP500 error handler

---

datalad/distributed/create_sibling_gitlab.py
datalad/distributed/tests/test_create_sibling_gitlab.py

This adds a ``--dry-run`` parameter to ``create-sibling-gitlab`` to match the corresponding parameter in ``create-sibling-{github,gin,gogs,gitea}``, and deprecates the current ``--dryrun`` option.
The PR also includes a small doc fix to the URL pointing to the documentation of python gitlab

Harmonize usage of --dry-run vs --dryrun in create-sibling-gitlab

---

datalad/__init__.py

This fix seems to resolve the stall for conda builds in a docker container.
Closes #5992 (~~well -- final verdict is yet to be made, but it seems to resolve on local builds~~ yeap -- that fixed it -- all green in https://github.com/conda-forge/datalad-feedstock/pull/63, merged)

BF: start global test_http_server only if not running already

---

datalad/distribution/remove.py
datalad/local/tests/test_subdataset.py
datalad/support/gitrepo.py
datalad/support/tests/test_annexrepo.py
datalad/support/tests/test_gitrepo.py
datalad/tests/utils.py

This is the companion of https://github.com/datalad/datalad-deprecated/pull/38 and enabled moving deprecated GitRepo methods to the deprecated extension.
This will help to accelerate the forming of a more stringent core API.
Obsolete `GitRepo.*_submodule()` methods are moved to demonstrate the functionality.

Enable GitRepo method moves to -deprecated

---

.appveyor.yml
.travis.yml
tools/ci/debians_disable_outdated_ssl_cert

BF: disable outdated SSL root certificate breaking chain on older/buggy clients

---

datalad/tests/test_installed.py

Tests on travis started to fail (today?! see below) with
FAIL: datalad.tests.test_installed.test_run_datalad_help
File "/tmp/dl-miniconda-hjvqrnh_/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
File "/tmp/dl-miniconda-hjvqrnh_/lib/python3.9/site-packages/datalad/tests/utils.py", line 1168, in _wrap_assert_cwd_unchanged
raise exc_info[1]
File "/tmp/dl-miniconda-hjvqrnh_/lib/python3.9/site-packages/datalad/tests/utils.py", line 1140, in _wrap_assert_cwd_unchanged
ret = func(*args, **kwargs)
File "/tmp/dl-miniconda-hjvqrnh_/lib/python3.9/site-packages/datalad/tests/test_installed.p …

BF(TST): filter away warning from coverage from analysis of stderr of --help

---

datalad/cmd.py

Fixes datalad/datalad#6030
This is an alternative to #6031 which maintains the general direction, while avoiding the complications.

Discontinue usage of deprecated (public) helper

---

datalad/support/archives.py

Previously, windows was a declared special case in which the flag was
effectively ignored. This is confusing, and may be unjustified even.
Fixes datalad/datalad#5044

Honor datalad.runtime.use-patool if set regardless of OS (was Windows only)

---

datalad/distribution/get.py
datalad/local/subdatasets.py

Add `custom_result_renderer()` to `Subdatasets` command class as a wrapper for `default_result_renderer()`.
Now `datalad subdatasets` will actually do what it's supposed to: list all present subdatasets without suppressing the output.
Fixes #4770

BF: Don't suppress datalad subdatasets output

---

datalad/local/tests/test_subdataset.py

Just a test to make sure datalad remains compatible with subdatasets that start with a hyphen.
Checks:
- create
- clone
- save
- uninstall
- get
Inspired by #5590

TST: Add test to ensure functionality with subdatasets starting with a hyphen (-)

---

datalad/interface/annotate_paths.py
datalad/metadata/aggregate.py
datalad/metadata/metadata.py
datalad/metadata/tests/test_aggregation.py

This is the second-to-last stop to finally resolve #3368
There is only a minimal behavior change: A rather peculiar reporting
behavior, where metadata of the "nearest" available dataset is chosen
when no explicit dataset is given.
This has no practical value and would complicate this temporary fix
substantially. This whole stuff only needs to last until metalad is
fully functional.

Replace AnnotatePaths in metadata commands

---

datalad/core/distributed/tests/test_clone.py
datalad/distribution/tests/test_install.py

originally that tape was added for test_install_crcns (hence the name of the tape)
which later was commented out in 941e51ffc8c506b51678e2fe3b2bf334ff3299ab and never
brought back.  Somehow that decorator was copy/pasted into other tests.
I guess because we no longer use GitPython, no online interactions through
python http modules were made, so tape was not really used, and it did not
lead to any failures.
My attention to that was brought by failures on Windows, such as
https://github.com/datalad/git-annex/runs/4042500337?check_suite_focus=true
which also should be unrelated, thus probably would not provide any
remedy, but there remains no reason to keep those "uses" of the same vcr
tape around.

BF(TST): remove reuse of the same tape across unrelated tests

---

datalad/distribution/create_sibling.py
datalad/distribution/tests/test_create_sibling.py

This fixes #5614: I prevents an accidental recursion of one level by not evaluating subdataset states - which should not play any role for the sibling creation of the toplevel ds - only when the recursive flag is set. 
It also adds a check for concurrent occurrence of ``--since`` with ``--recursive`` - Given the description of ``--since``, I believe that it requires recursion and is thus useless if used without ``--recursive``.

BF: Don't make create-sibling recursive by default

---

datalad/interface/tests/test_download_url.py
datalad/interface/tests/test_rerun.py
datalad/support/tests/test_locking.py
datalad/tests/test_utils_cached_dataset.py

A mix of newly enabled tests because they passed on an actual Windows box, and a few adjusted tests that pass after they got a Window equivalent to a Unix command. Let's see if the CIs agree.

TST: Enable more Windows tests

---

datalad/core/local/status.py

I had some concerns due about symlinks but it seems that get_dataset_root doesn't bother much about them, so I think it should be kosher -- let's see what CI says ;-)
edit: may be I should just add a locally decorated `lru_cache(get_dataset_root)` instead of "manual" try/excepts?
edit: on a trial attempt benefit seems to be minor but present:
```shell
(git-annex)lena:~/datalad/dandi/dandisets/000026[draft]rawdata/sub-I46/ses-SPIM
$> multitime -n 5 datalad status *  # has 1100 files in that directory
```
this branch first line, master - 2nd (both are warm runs)
```
Mean        Std.Dev.    Min         Median      Max
real        0.825       0.018       0.792       0.834       0.842   
real        0.848       0.031       0.816       0.830       0.897
```

OPT: do not deduce the ds path over and over again for files in a dir

---

datalad/support/annexrepo.py

An alternative to https://github.com/datalad/datalad/pull/6133 implementation
which first forces git-annex to commit.
The use case was detected while working on https://github.com/datalad/datalad-crawler/pull/112
to accompany https://github.com/datalad/datalad/pull/6105 .
Although we could have easily "fixed" the test in datalad-crawler, I consider
the approach of going around git-annex commands to interrogate git-annex
metadata to be fragile, in particular for such a case as here: some other
command could have been ran in alwayscommit=false mode, and information in
git-annex branch might not yet reflect actual state of git-annex.  Ideally we
should avoid doing such "going around git-annex", but ATM there is no git-annex
command which would "expose" all this information.

BF: obtain information about annex special remotes also from annex journal

---

datalad/tests/test_log.py

Properly escape backslashes in some regexes

---

datalad/downloaders/tests/test_s3.py
datalad/metadata/extractors/tests/test_xmp.py
datalad/metadata/tests/test_extract_metadata.py

Closes #6141 ("maint" specific, "master" was catching all exceptions, conflicts will need to be resolved in favor of the helper)

RF+BF: use skip_if_no_module helper instead of try/except for libxmp and boto

---

datalad/tests/utils.py
tools/adhoc-httpd

This helper exposes `serve_path_via_http` via a cmdline utility that is
capable of deploying an ad-hoc instance of the same HTTP server that we
are using for internal testing (with SSL and auth, if desired).
This lowers the threshold for debugging real usage, by avoiding the need
to develop a dedicated test for a scenario. It also makes it possibly to
bypass to additional implications of a datalad test implementation, like
the fake homedir (see #6164, #6160).

New helper `tools/adhoc-httpd` to facilitate manual HTTP debugging

---

datalad/interface/results.py
docs/source/design/index.rst
docs/source/design/result_records.rst

Developers are encouraged to amend this initial document with additional information, in particular field names that are in active use.
- Fixes datalad/datalad#6054
- Fixes datalad/datalad#6171
Please suggest concrete changes/addition using the reviewing functionality of by pushing the this branch. Given the documentation-nature of this PR, I will merge this tomorrow, unless objections are expressed.

Design document on result records

---

datalad/tests/test_utils.py
datalad/utils.py

There might be more but largely orthogonal so decided to submit this short quick PR.
It is a companion to https://github.com/datalad/datalad-crawler/pull/113 which I marked for the release and just merged... https://pypi.org/project/datalad-crawler/ has 0.9.3 now
I didn't check other extensions if they use this elderly function -- will see with this PR

RM: (re)move get_func_kwargs_doc and some python2 compat code path

---

.zenodo.json
datalad/core/local/create.py
datalad/core/local/tests/test_create.py
datalad/interface/run_procedure.py
datalad/interface/tests/test_run_procedure.py

This PR changes the behaviour of `create` and `run_procedure` so that using an incorrect (unavailable) procedure name results in an error. Closes #6129 
Specifically, the following changes were made:
1. The `run_procedure` on its own was changed to raise a `ValueError` instead of reporting a result with `status='impossible'`
2. A call to `run_procedure(discover=True)` was introduced in `datalad create` before any creation takes place to check whether the requested `cfg_proc(s)` are available.
3. To avoid going through a discovery process again when the procedure is applied to a newly created dataset, results of the call described above are reused. To make it possible, a new behaviour was introduced to `run_procedure(spec, ...)` when `spec` is a dictionary.
The third change seems the most …

BF produce an error in create and run_procedure if procedure does not exist

---

datalad/interface/download_url.py
datalad/interface/tests/test_download_url.py

This should fix #6170.
In a dirty dataset, the result now looks like this:
```
❱ datalad download-url --archive https://www.fil.ion.ucl.ac.uk/spm/download/data/MoAEpilot/MoAEpilot.bids.zip
[INFO   ] Downloading 'https://www.fil.ion.ucl.ac.uk/spm/download/data/MoAEpilot/MoAEpilot.bids.zip' into '/tmp/testnew/bal/bla/bla/a/c/d/a/a/c/' 
download_url(ok): /tmp/testnew/bal/bla/bla/a/c/d/a/a/c/MoAEpilot.bids.zip (file)            
add(ok): bal/bla/bla/a/c/d/a/a/c/MoAEpilot.bids.zip (file)                                  
save(ok): . (dataset)                                                                       
add-archive-content(impossible): /tmp/testnew (dataset) [clean dataset required. Use `datalad status` to inspect unsaved changes]
add (ok: 1)
add-archive-content …
```

Yield add-archive-content results when called from download-url

---

.autorc
.github/workflows/test-label.yml
CONTRIBUTING.md

In looking through the issues closed over the weekend, I felt compelled to act on the suggestion in #5833 to prefix a common, versioning-related identifier to the PR labels for the auto-workflow.
I think there was some general agreement in the original issue, but not enough momentum to implement the change. I personally keep forgetting which labels exist, and would be in favor of having them in one group to ease discoverability. 
I'm suggesting ``semver`` as a prefix, because the corresponding test is called "Test for semver label". I'm happy to change this into anything else, though.

infra: Provide custom prefix to auto-related labels

---

datalad/cmdline/helpers.py
datalad/core/distributed/tests/test_push.py
datalad/core/local/run.py
datalad/core/local/tests/test_diff.py
datalad/core/local/tests/test_results.py
datalad/core/local/tests/test_run.py
datalad/core/local/tests/test_status.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/tests/test_create_sibling_ghlike.py
datalad/distributed/tests/test_create_sibling_ria.py
datalad/distribution/create_sibling.py
datalad/distribution/siblings.py
datalad/distribution/tests/test_get.py
datalad/distribution/tests/test_siblings.py
datalad/interface/base.py
datalad/interface/clean.py
datalad/interface/common_opts.py
datalad/interface/rerun.py
datalad/interface/run_procedure.py
datalad/interface/tests/test_base.py
datalad/interface/tests/test_utils.py
datalad/interface/utils.py
datalad/local/addurls.py
datalad/local/subdatasets.py
datalad/local/tests/test_addurls.py
datalad/local/tests/test_copy_file.py
datalad/metadata/aggregate.py
datalad/support/due_utils.py

The full story is in #6038
Concretely, this:
- documents the 'disabled' renderer mode
- strip supported for the undocumented datalad.api.result-renderer
config setting
- homogeneous documentation for `--output-format` and `result_renderer`
- rename `default[_result_renderer]` to `generic[_result_renderer` to
resolve the multi-level ambiguity of "default" for a renderer that,
ironically, is not the default. Shims for legacy code are in place,
and will likely never be removed
- replace internal usage of `output_format` with a consistent
`result_renderer` for homogeneity. Command line API is kept unchanged
though -- might be worth a follow-up discussion in a separate issue/PR
- discontinue the undocumented use of `result_renderer=None` and replaces
it with `result_renderer='disabled'`
Fixes …

Decomplexify/document result-rendering switches

---

datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py

Previously it would fail trying to determine whether the local
annex is known to remotes, but before `init` there is no local
annex.
With this change I am catching this condition and avoid the entire
investigation.
The potentially bigger issue (whether or not such a dataset should
carry an `AnnexRepo` instance, rather than `GitRepo`) is related
to #6103 and must be discussed separately.
Fixes #6180

Do not fail dropping an uninitialized AnnexRepo 

---

setup.py

which lead to a broken build with a recent docutils update.
Story in https://github.com/datalad/datalad/issues/6122
Fixes datalad/datalad#6122

Bump sphinx requirement to bypass readthedocs defaults

---

datalad/interface/results.py
datalad/interface/tests/test_results.py
datalad/support/exceptions.py

Immediate use-case is foreach since it feels worthwhile channeling
upstairs the details of the failed execution, but I can imagine
it being useful for other cases too.
WDYT?
TODO:

ENH: get_status_dict - add exit_code if CommandError

---

datalad/distribution/dataset.py
datalad/interface/base.py
datalad/interface/utils.py
datalad/support/external_versions.py
datalad/tests/test_utils.py
datalad/utils.py
requirements-devel.txt
setup.py

A quick chat with @mih inspired me to look into it.... in a nutshell (more to come if feasible):
- use `inspect.signature` instead of `inspect.getargspec` since that one manages to get args of `functools.wraps`ed functions. Source of information: https://stackoverflow.com/questions/147816/preserving-signatures-of-decorated-functions#comment68410839_147878
- ~~remaining gotcha (TEMPorarily disabled that test ) -- not yet "binding" `__doc__` to `Dataset.method` -- `@build_doc` assigns `__doc__` to `__call__` later than `@datasetmethod` is invoked. So I guess `wrapt` does some magic for `__doc__` to be always be queried for the `wrapt`ed functions.~~ -- I think I came up with a good enough workaround
- reworked `getargspec` is based on the one in #6176 but redone on top - will conflict. If …

RF: de-wrapt

---

.appveyor.yml

This is an attempt to fix #6193, but we will have to take a look at the actual runtimes with this change

TST: redistribute windows tests across workers to harmonize runtime

---

CONTRIBUTING.md
datalad/cmdline/helpers.py
datalad/downloaders/tests/test_providers.py
datalad/interface/common_cfg.py
datalad/interface/run_procedure.py
datalad/support/cookies.py
datalad/support/external_versions.py
setup.py

The original appdirs repository is unmaintained. This change replaces it
with a currently maintained fork of the project. Closes #6164, and for now replaces #6166

MNT: Replace appdirs with platformdirs

---

readthedocs.yml

This is an attempt to fix the readthedocs build failure. I've modernized our readthedocs.yml file into a modern version 2 one. The previous one was the culprit leading to the wrong requirements being installed - I hope this one may fix it.
I will kill all CIs in this PR.

INFRA: Modernize readthedocs configuration

---

datalad/tests/test_cmd.py
docs/source/design/batched_command.rst
docs/source/design/index.rst

This PR adds design documentation for  `BatchedCommand` and `BatchedAnnex`, as well as a very basic test for `BatchedCommand`. This PR is a fallout of my work on implementing  `BatchedCommand` and `BatchedAnnex` with the new generator-based runner.  Although this PR might be outdated in the next or a later release, I think it provides some value.

Document `BatchedCommand` and `BatchedAnnex`

---

datalad/distribution/get.py
datalad/distribution/tests/test_get.py

datalad-get used to overwrite possibly existing source candidate configs
in newly cloned subdatasets. While inheriting is generally fine, it
didn't take into account that postclone_cfg routines may already have
had a better idea.
"Better idea" in that I think the principle of looking up subdatasets in the same RIA store their super came from should apply at all levels recursively. Hence, when `super` came from storeA, storeA is also considered for `sub`. If it, however, turns out that `sub` ultimately came from storeB, then `subsub` should be looked for in storeB. And that's the situation where that overwrite matters AFAICT.
Closes #6159

BF: Don't overwrite subdataset source candidates

---

datalad/cmdline/tests/test_formatters.py

BF: Also catch ModuleNotFoundErrors for formatters

---

datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ora_http.py

These URL do not only have annecdotal value. In efforts like #828 incorrect URLs invalidate the result.
The fix is not pretty (due to #6089 and similar issues), but it comes with a test that hopefully indicates breakage when these are fixed.

Report correct HTTP URL for RIA store content

---

datalad/distribution/tests/test_get.py

Recent fix against `maint`  requires this adaption in `master`.

Fix test for changed create-sibling-ria interface

---

.appveyor.yml
tools/ci/appveyor_install_git-annex.bat

This is the latest build worker image available, and comes with Git
version 2.33.1, which could be useful in switching test setups to
not overwrite USERPROFILE environment variables (cc #6160)
Just a test PR to check whether everything works out of the box.

TST: Switch to Visual Studio 2022 for Appveyor Windows setup

---

datalad/cmdline/helpers.py
datalad/cmdline/tests/test_main.py
datalad/interface/__init__.py
datalad/interface/base.py

The new structure accents on the API structure proposal in #3192 
This PR concludes the recovery from the failed #6178

Cleanup interface list, introduce group sort, new group structure

---

datalad/core/distributed/tests/test_clone.py
datalad/core/local/tests/test_run.py
datalad/core/local/tests/test_save.py

Add testing of Path objects as source specification in `clone` tests
while doing so.
Towards datalad/datalad#6144

Discontinue with_testrepo usage for all core tests

---

datalad/distributed/create_sibling_gin.py
datalad/distributed/tests/test_create_sibling_ghlike.py
datalad/distributed/tests/test_create_sibling_gin.py

This change corrects and overrules a premature conclusion by git-annex on the non-availability of an annex at the GIN platform -- which is merely an effect of happening prior any branch availability on GIN.
I decided to not pursue the alternative approach from https://github.com/datalad/datalad/issues/6204#issuecomment-971869080 which could potentially be more expensive with no clear advantage.
Fixes datalad/datalad#6209

Make outcome of `create-sibling-gin` readily usable for a `push` data transfer

---

datalad/runner/nonasyncrunner.py
datalad/runner/tests/test_witless_runner.py

Closes #6106
Fragile part of the test -- we might not hit that limit may be?  Let's see what CI says. Alternative would be to mock that Popen call but that would get us away from reality.
Sure thing could be improved etc, but overall I am giving up on trying to set/control that CMD_MAX_ARG and decided just to hint (related: #6114) user on how to mediate.

ENH(UX): log a hint to use ulimit command in case of "Too long" exception

---

datalad/customremotes/__init__.py
datalad/customremotes/archives.py
datalad/customremotes/base.py
datalad/customremotes/datalad.py
datalad/distributed/ora_remote.py
datalad/downloaders/s3.py
datalad/support/exceptions.py
datalad/support/tests/test_captured_exception.py

- Prevention of multi-line messages breaking the special remote protocol
- Generalize multi-line message protection for `RemoteError` from just ORA to all special remotes
- Report on the cause for download error in the `datalad` special remote; fixes #5773 
- Introduce new helper to generator compact messages from an exception with underlying causes
- Alter ORA exception raising to report underlying causes; fixes #6231
Together this change improves from `maint` behavior:
`RuntimeError(Failed to download from any of 1 locations)`
from `master`
```
external special remote protocol error, unexpectedly received ")" (unable to parse command)
unable to use special remote due to protocol error
```
to 
`Failed to download from any of 1 locations [S3ResponseError: 403 Forbidden\n]`

Fix special remote messaging

---

.appveyor.yml

See https://git-annex.branchable.com/bugs/Windows__58___substantial_per-file_cost_for___96__add__96__/ and https://github.com/datalad/datalad/issues/5994 for the saga.
Let's see what effect it would have.
Pre:
Post:
Pretty interesting. A substantial improvement (16% overall), but not evenly across jobs (between 5% and 32%)... No idea what is happening here.
The job that saw the massive speed-up is running:
```
local/
test_add_archive_content.py
test_add_readme.py
test_addurls.py
test_check_dates.py
test_clean.py
test_copy_file.py
test_download_url.py
test_export_archive.py
test_no_annex.py
test_remove.py
test_rerun_merges.py
test_rerun.py
test_run_procedure.py
test_subdataset.py
test_unlock.py
test_wtf.py
support/
test_annexrepo.py
test_ansi_colors.py
test_cache.py …
```

TST: Enable filter.annex.process on windows to speed things up

---

datalad/distributed/create_sibling_gin.py
datalad/distributed/create_sibling_gitea.py
datalad/distributed/create_sibling_github.py
datalad/distributed/create_sibling_gitlab.py
datalad/distributed/create_sibling_gogs.py
datalad/distributed/create_sibling_ria.py
datalad/interface/base.py
docs/source/design/docstrings.rst
docs/source/design/index.rst

Prompoted by https://github.com/datalad/datalad/issues/6247#issuecomment-979218397
- Start of a design document on docstring handling and formatting (it does not document all possibilities on purpose, because some seem arcane and redundant)
- Add support for sphinx versioning directives
- Make `REFLOW` work with indented paragraphs
- Support a simpler specification for API argument alternatives
- Use versioning directives for the 0.16 set of changes to `create_sibling_g*``
Demos:
The is how the following sources look across all kinds of rendering scenarios:
```rst
.. versionchanged:: 0.16
|| REFLOW >>
The API has been aligned with the some
``create_sibling_...||create-sibling-...`` commands of other GitHub-like
services, such as GOGS, GIN, GitTea.<< REFLOW ||
.. deprecated:: 0.16
The …
```

Docstring handling upgrade

---

datalad/support/keyring_.py

Likely a typo, delete() called an uninitialized private attribute instead
of the lazy loading, protected one.
Note, that this particular bug was only recently introduced to master, so "patch" but against master.
Introduced by: 3cddd7c4ac832e89241d5b396abf47fea994fc71

BF: Keyring.delete called uninitialized attribute

---

datalad/distributed/create_sibling_ria.py

The ``res_kwargs`` were accidentally placed into the format method
instead of ``get_status_dict``, thus failing to deliver
common keys into the result record, ultimately leading
to omission of the result record in #6250.
This change should fix this, and close #6250

BF: Properly pass result kwargs into result record of create-sibling-ria

---

datalad/local/remove.py

It confused argparse, because of the new default, which led it to
believe that a value is still needed.
Fixes #6243

Fixup remove --recursive deprecation

---

datalad/tests/test_utils.py

Just spotted while staring in a stale browser tab of
https://github.com/datalad/datalad/pull/6190/files
which is now merged

ENH(TST): add some "pragma: no cover" wherever test code is not expected to run

---

datalad/core/local/run.py
datalad/support/globbedpaths.py
datalad/support/tests/test_globbedpaths.py

ENH: enable recursive glob (**) for `run`

---

datalad/__init__.py
datalad/tests/test_base.py
datalad/tests/test_config.py

System level configured git-credential helper osxkeychain on OSX hangs
if it can't find the Keyring under HOME, which we change to some bogus
dir for the tests. On OSX change the approach to make use of
GIT_CONFIG_GLOBAL instead of changing HOME if git version supports it (>= 2.32).

TST: no HOME change on OSX

---

datalad/__init__.py
datalad/core/distributed/tests/test_push.py
datalad/distributed/tests/test_ora_http.py
datalad/distribution/tests/test_get.py
datalad/local/tests/test_add_archive_content.py
datalad/tests/test_base.py
datalad/tests/test_config.py
datalad/utils.py

this change sits on top of #6251 and simply expands it to all systems with a high enough git installation (i.e., I removed the ``if not on_osx`` constraint). Things pass on locally for me both on Windows (6 more tests start to pass with this change, including the one where #6160 originally surfaces) and Debian, but let's see what breaks in the CIs.
I think that with the exception of a few tests (e.g. ``test_expanduser``) this would avoid leaking cache dirs and the like into temporary repositories during testing. :crossed_fingers:

Expand the use of GIT_CONFIG_GLOBAL to Windows

---

datalad/__init__.py
datalad/utils.py

Many small increments have led to an organic state. This makes a pass to consolidate, de-duplicate, and re-structure according to current practice -- unless counter-evidence was found.

Cleanup datalad/__init__.py

---

datalad/customremotes/ria_utils.py
datalad/distributed/ora_remote.py

Fixes #6252 which comprises two problems.
ORA remote used the uuid of the *remote* to place a file in transfer
in a tmp dir. But this actually causes transfer conflicts with
simultanous uploads of the same key from multiple clones.
This is fixed by using the `here` uuid.
The second issue is a test for existence of the transfer file, and
failing if there is one already. This prevents the first issue from
having practical relevance re data integrity. With the usage of `here`
uuids, the conflict can no longer happen, and the test is obsolete.
The fix involves import and instantiation of `AnnexRepo()`. The
additional cost for that is minimal (~10-50ms on my machine) and is only
payed once per process at PREPARE. This newly available repo API, will
enable removal of custom code from the …

Enable ORA remote to recover from an interupted upload

---

datalad/cmd.py
datalad/runner/exception.py
datalad/runner/gitrunner.py
datalad/runner/nonasyncrunner.py
datalad/runner/protocol.py
datalad/runner/runner.py
datalad/runner/runnerthreads.py
datalad/runner/tests/test_exception.py
datalad/runner/tests/test_generatormixin.py
datalad/runner/tests/test_gitrunner.py
datalad/runner/tests/test_nonasyncrunner.py
datalad/runner/tests/test_utils.py
datalad/runner/tests/test_witless_runner.py
datalad/runner/tests/utils.py
datalad/runner/utils.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py
datalad/tests/test_cmd.py
docs/source/design/batched_command.rst
docs/source/design/index.rst
docs/source/design/threaded_runner.rst

This PR provides a new threaded runner implementation that supports timeouts and generator-based subprocess-communication, Which means stdout and stderr data are available from a generator. Our standard protocol-approach is also supported with generators, i.e. every data packet from stdout and stderr is passed through an instance of `WitlessProtocol` (or a subclass), by calling `WitlessProtocol.pipe_data_received()`.
This PR:
The PR uses and demonstrates the generator-capabilities in `AnnexRepo` and in `BatchedCommand`, it:
Although there are quite a number of changes in this PR, the modifications are mainly encapsulated in the runner code and in `BatchedCommand`. Both have a slightly extended, backward compatible API. That means the new implementations are drop-in replacements.
The …

Generator-style runner with application in BatchedCommand and AnnexRepo

---

datalad/cmdline/helpers.py
datalad/customremotes/archives.py
datalad/tests/utils.py

This is an old, now duplicate, implementation of getting a repo instance
from a path (that may point into a dataset, and not at its root). This
was only used in a few spots. I replaced it with the standard approach.

Discontinue use of and deprecate get_repo_instance()

---

datalad/__init__.py
datalad/api.py
datalad/cmdline/helpers.py
datalad/cmdline/main.py
datalad/cmdline/tests/test_main.py
datalad/interface/base.py
datalad/support/tests/test_sshrun.py
docs/source/design/application_vs_library_mode.rst
docs/source/design/index.rst

This PR lays the foundation to introduce "library-mode" behavior, and to distinguish via which API datalad functionality is being accessed. These aspects are related but orthogonal.
Summary:
- Added `datalad.get_apimode()` to query for the effective API in use
- Added `datalad.enable_librarymode()` to put DataLad in lib-mode
- Added `datalad.in_librarymode()` to test for active lib-mode
- Added design document on this
This is the foundation to further tailor messaging, logging behavior, etc. None of which is planned for this PR.
Additional changes:
- Unit tests for the mode queries (limited to deviation from the default)
- Disabled Python API doc generation in lib-mode (shaves off 150ms process startup time on my machine)
- Fixes #6081

API mode indicator and library-mode enabling switch

---

datalad/core/local/status.py
datalad/local/run_procedure.py
datalad/metadata/metadata.py

Unless when assuming a default configuration (and no code changes over
time), it is not reliable to count on a result-related message to reach
a user via a logging channel vs. a result record.
Commands already *must* emit results to make outside-control possible,
and connect to features, such as result-hooks. Therefore, results have
to be considered to primary mode of reporting.
Taken together, all results must be processed, also by result renderers
-- whether or not a log message corresponding to them was also emitted.
Eventual double-reporting must be addressed by other means than
swallowing results in renderers.
This change addresses this demand for three commands, by falling back on
the generic result renderer, whenever their tailored one would have
rejected a result before.
Fixes …

Stop swallowing to-be-rendered results based on prior logging assumption

---

datalad/distribution/uninstall.py

Behavior if one were to use uninstall but forgot ``--nocheck``:
```
datalad uninstall containers                       
uninstall(error): containers (dataset) [to-be-dropped dataset has revisions that are not available at any known sibling. Use `datalad push --to ...` to push these before dropping the local dataset, or ignore via `--reckless availability`. Unique revisions: ['master']]
```
Behavior now:
```
❱ datalad uninstall containers                                              2 !
uninstall(error): containers (dataset) [to-be-dropped dataset has revisions that are not available at any known sibling. Use `datalad push --to ...` to push these before dropping the local dataset, or ignore via `--nocheck`. Unique revisions: ['master']]
```
Fixes #6259

UX: When calling uninstall without nocheck, strip hints for drops reckless parameter

---

datalad/core/local/run.py
datalad/local/rerun.py

Implements #6118 . I have 2 questions.

ENH: Add parallel jobs options for `run` and `rerun` (applies to get, save)

---

datalad/dataset/gitrepo.py
datalad/dataset/tests/test_gitrepo.py
datalad/runner/runner.py
datalad/runner/utils.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py
datalad/support/tests/test_gitrepo.py
datalad/utils.py

This PR uses a generator-based runner to, i.e. a runner with a `GeneratorMixIn`-Protocol subclass, to implement `GitRepo.call_git_items_()`.
This is a follow up to PR #6244, especially the following reviewer comment: https://github.com/datalad/datalad/pull/6244#discussion_r760831590
The interface of  `GitRepo.call_git_items_()` does not change, but results will be yielded as soon as they are available.

Generator-based GitRepo.call_git_items_()

---

.github/workflows/test_macos.yml

Use python 3.7 on Mac OS tests, since python 3.6. is no longer supported

Bump the python version used for mac os tests

---

datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

Fix an issue where a missing import would break exception handling during AnnexRepo.add_()

Add a missing import of CapturedException

---

datalad/cmdline/tests/test_main.py
datalad/customremotes/tests/test_archives.py
datalad/customremotes/tests/test_base.py
datalad/customremotes/tests/test_datalad.py
datalad/downloaders/tests/test_http.py
datalad/downloaders/tests/test_providers.py
datalad/interface/tests/test_add_archive_content.py
datalad/metadata/tests/test_search.py
datalad/support/tests/test_captured_exception.py
datalad/support/tests/test_network.py
datalad/support/tests/test_versions.py
datalad/tests/test_archives.py
datalad/tests/test_log.py

The code currently contains a number of invalid escape sequences (mostly escapes of special characters in regexes).  These result in Python emitting DeprecationWarnings, and some future Python version will instead treat them as syntax errors.  This PR fixes them.

Fix invalid escape sequences

---

datalad/distributed/create_sibling_gin.py

This is a small change. The example demonstrating how to create a sibling repo on GIN and register it as a common data source now suggests `push` as an additional step before `configure` to create git-annex branch remotely and obtain annex UUID. Otherwise, configuration would not happen properly. Addresses part of #6269

DOC: Update examples in create_sibling_gin

---

datalad/distributed/ora_remote.py

Otherwise our UI would consider session non interactive and would not
prompt for credentials etc.
Closes #5790
This replaces #5825, as I could confirm (and understand) that this change is sufficient.
`set_specialremote` as mentioned in https://github.com/datalad/datalad/pull/5825#discussion_r676778558 seems to only be relevant for progressbars, which is of no concern for ORA ATM, since we simply report to annex.
Rebased,  and filed this PR from my fork, since I can't push to @yarikoptic's.

BF: RIARemote - set UI backend to annex to make it interactive

---

datalad/interface/utils.py
datalad/support/network.py

This PR fixes issue #6275.
The PR removes the restriction of dataset parameters to locally resolvable file-URLs. This is used, for example, in the new metalad version where you can dump metadata from remote repositories.
The main difference introduced is that the decorator `eval_results` only looks for hooks in the default configuration, if the dataset parameter does not specify a locally resolvable file-URL.

Allow other URLs than local file as dataset parameter

---

datalad/local/foreach_dataset.py

This PR fixes issue #6302 
The merged `foreach_dataset` was missing the positional argument delimiter, i.e. `*`, in its argument list

BF: add positional args delimiter to `foreach_dataset`

---

datalad/core/local/run.py

This is an implementation of #2924.
In case where a run command failed in a formerly clean repo, and the repo is
left in a dirty state, log general hints to use 'git clean' and 'git reset'
at INFO level.
Closes #2924.

UX: If a clean repo is dirty after a failed run, give clean-up hints

---

CONTRIBUTING.md

Simple addition serving as a release PR.

Minor enhancement to CONTRIBUTING.md

---

datalad/runner/tests/test_nonasyncrunner.py

This PR fixes the runner timeout tests in windows. It uses "WAITFOR" instead of "TIMEOUT" since the latter does not work in non-interactive shells, e.g. in our test settings.

Fix runner timeout test in windows

---

.autorc

Just blindly (although makes sense) following suggestion of @jwodder
in https://github.com/datalad/datalad/pull/5974#issuecomment-995219083
I will add release label and merge shortly (no need to wait for CI on this)

BF: autorc - replace incorrect releaseTypes with "none"

---

datalad/dataset/gitrepo.py
datalad/dataset/tests/test_gitrepo.py
datalad/distribution/tests/test_utils.py

It now tests the common scenarios first, rather then leaving them for last.
Moreover, it introduces an explicit `resolved` flag for result path reporting, and applies it consistently when enabled -- rather than just for symlinked directories, but not files, or gitdirs specified in .git files. Searching through the code, I did not spot a case where this features is needed, nor desirable.
Fixes datalad/datalad#6321
Fixes datalad/datalad#6324

Reimplement _get_dot_git() to be more efficient

---

MANIFEST.in
setup.py

* The contents of the `datalad/test/ca/` folder are currently not included when datalad is installed; this PR fixes that.
* `datalad/metadata/tests/data/nifti1.nii.gz` is currently not included when datalad is installed; this PR fixes that.
* The `package_data` specification in `setup.py` listed a number of file extensions to include under `datalad/resources/` that are no longer present; this PR removes them.
* The package data specification is simplified so that all files under `datalad/` are included when installing datalad without needing to list all of the desired files' file extensions.

Install all data files under `datalad/`

---

datalad/distribution/get.py
datalad/distribution/tests/test_get.py

This is to address an elderly https://github.com/datalad/datalad/issues/5631
which I keep running into over and over again.  Unfortunately a more thorough
fix attempt in https://github.com/datalad/datalad/pull/5644 was not finalized.
Since I keep running into this issue over and over again leading to process
crash, I decided that a "crude" fix with issuing a warning would be
better than just crashing entirely (thus possibly leaving other many subdatasets not even be attempted to be installed).

BF(Q&D): do not crash - issue warning - if template fails to format

---

setup.py

We've lost bullet points in our docs (#6313). https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 suggests to pin the readthedocs theme and sphinx. This PR is a test to see if it would work (hopefully I can get a preview by RTD as I am opening this PR not from a fork)

Docs, infra: Attempt to fix missing bullet points by pinning Sphinx and RTD theme versions

---

datalad/core/distributed/tests/test_push.py
datalad/distribution/tests/test_install.py

Those had been failing for a while, see
https://github.com/datalad/datalad/issues/6333
https://github.com/datalad/datalad/issues/6237
ruining the baseline testing of datalad/git-annex.  Unfortunately I have no
sufficient foo or time to track them down.

BF(workaround,TST): mark two tests as @known_failure_githubci_win

---

datalad/local/download_url.py

BF: When download-url gets Pathobject as path convert it to a string

---

datalad/local/tests/test_download_url.py

compare with http_proxy set:
root@smaug:/tmp/buildd/datalad-0.15.4+git528.g4ea21cb32# http_proxy=http://127.0.0.1:9/ PYTHONPATH=$PWD bin/datalad download-url http://example.com/bogus
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
[INFO   ] Downloading 'http://example.com/bogus' into '/tmp/buildd/datalad-0.15.4+git528.g4ea21cb32/'
download_url(error): /tmp/buildd/datalad-0.15.4+git528.g4ea21cb32/ (file) [AccessFailedError(Failed to establish a new session 1 times. )]
to without (when we should do that assert):
root@smaug:/tmp/buildd/datalad-0.15.4+git528.g4ea21cb32# PYTHONPATH=$PWD bin/datalad download-url http://example.com/bogus
It is highly recommended to configure Git before using DataLad. Set both …

BF(TST): add another condition to skip under http_proxy set

---

datalad/cmdline/tests/test_main.py

Redundant copies, that is!
Actually lives in datalad/cmdline/tests/test_helpers.py

Remove two(!) copies of a test

---

.travis.yml
datalad/cmdline/helpers.py
datalad/cmdline/tests/test_main.py
datalad/support/tests/test_annexrepo.py

Fix for the failing tests in #6362 and add 3.10 testing for travis (more radical CI changes to be added to `master` after this PR gets merged into `maint` and then into `master`)

BF: python 3.10 compatibility fixes

---

.appveyor.yml
.github/workflows/test_crippled.yml
.travis.yml
CONTRIBUTING.md
datalad/cmdline/helpers.py
datalad/cmdline/tests/test_main.py
datalad/distribution/tests/test_create_sibling.py
datalad/support/network.py
datalad/support/tests/test_annexrepo.py
datalad/support/tests/test_network.py
datalad/tests/utils.py
setup.py

Sits on top of the merge of #6363 into master.

Drop python 3.6 support, remove some no longer needed kludges, merge of maint 

---

datalad/support/parallel.py
datalad/support/tests/test_parallel.py

The new runner implementation allows for threads in ProducerConsumer in python versions <= 3.7 because we
do not use asyncio any longer in the runner

Allow multiple threads in ProducerConsumer with python <= 3.7

---

datalad/cmdline/tests/test_main.py

Likely this test never failed to run (until it was ran during
Debian package build) since was always invoked within git clone
of datalad source code base.  So "clean" was able to find the dataset
to "work on".  When building a package, there were no git repository
and test failed since "clean" exited with 2 instead of 0.

BF(TST): clean command should be invoked within a dataset

---

datalad/utils.py

A blind fix which feels like "the right thing to do" without
deep analysis.  Closes #6357

BF: condition access to isatty to have stream eval to True

---

datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ora_http.py
tools/coverage-bin/git-annex-remote-ora

Commit a4b87f0c58047c9337e0cd1604f2b3eaeaae99a7 broke this
by removing to much. CHECKPRESENT and TRANSFER-RETRIEVE would
try to address a potential archive if key couldn't be
found in annex object tree.
This is wrong. In opposition to remote execution variants
(SSH and local access), HTTP is supposed to only send one request
per key - archives have to be dealt with server-side.
(Closes #6354)

BF: ORA over HTTP tried to check archive

---

datalad/distribution/get.py
datalad/distribution/install.py
datalad/distribution/tests/test_get.py
datalad/interface/base.py
datalad/metadata/aggregate.py
datalad/metadata/metadata.py

Here's an attempt at fixing #6376. It removes the Interface method ``get_refds_path()`` and replaces its remaining few usages with ``require_dataset()``. Not sure if this approach is too simplistic.

MNT/RF: Retire get_refds_path and replace its usages with require_dataset()

---

datalad/interface/__init__.py
datalad/interface/common_cfg.py
datalad/local/configuration.py
datalad/local/tests/test_configuration.py
docs/source/cmdline.rst
docs/source/modref.rst

Fixes datalad/datalad#5489
The individual commits following the first one are improvements over the extension version.
- A new `configuration`command provides an interface to manipulate and query the DataLad configuration.
- Unlike the global Python-only `datalad.cfg` or dataset-specific `Dataset.config` configuration managers, this command offers a uniform API across the Python and the command line interfaces.
- This command was previously available in the `mihextras` extension as `x-configuration`, and has been merged into the core package in an improved version. [#5489](https://github.com/datalad/datalad/pull/5489) (by @mih)
- In its default `dump` mode, the command provides an annotated list of the effective configuration after considering all configuration sources, including hints on …

Migrate configuration command from mihextras extention

---

datalad/cli/common_args.py
datalad/cli/tests/test_exec.py
datalad/interface/base.py
datalad/interface/common_opts.py
datalad/interface/utils.py
docs/source/design/cli.rst
docs/source/modref.rst

- Fixes #6377
-  The `datalad.interface.base.Interface` class, the basis of all DataLad command implementations, has been extensively documented to provide an overview of basic principles and customization possibilities (by @mih)
- `datalad.interface.common_opts.eval_default` has been deprecated. All (command-specific) defaults for common interface parameters can be read from `Interface` class attributes (by @mih)
- `datalad.interface.base.Interface` is now an abstract class [#6391](https://github.com/datalad/datalad/pull/6391) (by @mih)

Key interface documentation

---

datalad/interface/utils.py

See https://github.com/datalad/datalad/issues/6005
- Remove unused and untested `datalad.interface.utils` helpers `cls2cmdlinename` and `path_is_under`

Remove unused helpers from datalad.interface.utils

---

datalad/cli/main.py
datalad/interface/utils.py

- Restore default result rendering behavior broken by #6391. Fixes #6393
- An unused code path for result rendering was removed from the CLI `main()`
- Simplified the decision making for result rendering, and reduced code complexity.

Simplify result rendering, and fix #6393

---

.github/PULL_REQUEST_TEMPLATE.md

Re #6388 and example is available at https://github.com/datalad/datalad/pull/6394
Importantly, the changelog template focuses on what is being fixed, rather than by which PR and by whom. The latter will almost always be the proposer (available via API), and the PR number can be auto-added to any harvested changelog entry.

Update PR template with changelog template

---

datalad/support/json_py.py

- Reduce code duplication in `datalad.support.json_py`

Reduce code duplication and add documentation

---

datalad/cli/parser.py
datalad/cmdline/main.py

- Fixes #6404
- Add compact-shims for old CLI entrypoints (needed for extension doc builds)
Does not need to appear in a release changelog.

Fix fallout from CLI update

---

datalad/config.py
datalad/tests/test_config.py

- Fix a broken check for file presence in the `ConfigManager` that could have caused a crash in rare cases when a config file is removed during the process runtime. Fixes #6327
- `ConfigManager.get_from_source()` now accesses the correct information when using the documented `source='local'`, avoiding a crash. Fixes #6331
- `ConfigManager` now supports reading committed dataset configuration in bare repositories. Analog to reading `.datalad/config` from a worktree, `blob:HEAD:.datalad/config` is read (e.g., the config committed in the default branch). The support includes `reload()` change detection using the gitsha of this file. The behavior for non-bare repositories is unchanged. Fixes #6264

ConfigManager supports bare repos

---

datalad/distribution/tests/test_get.py

See https://github.com/datalad/datalad/issues/6412 for more background.
The actual reason was not discovered, but the test became slower in late Jan,
crossing the line of 30seconds.  We are marking it as slow to mitigate
false positive CI fails on PRs.

TST: mark test_source_candidate_subdataset as @slow

---

datalad/cli/parser.py

parse_known_args seems to be doing some processing which we did not
apparently needed. @mih raised concern/question on why we use protected
method and there were no comment/rationale left in the code.
I have set exit_on_error to False since we do not want to add that
error handling behavior since we did not rely on it before
Timing on my laptop on this commit
$> multitime -n 5 datalad --help-np 1>/dev/null
===> multitime results
1: datalad --help-np
Mean        Std.Dev.    Min         Median      Max
real        1.304       0.026       1.276       1.294       1.353
user        1.232       0.035       1.197       1.221       1.300
sys         0.076       0.010       0.057       0.080       0.085
and on master
$> multitime -n 5 datalad --help-np 1>/dev/null
===> multitime results
1: datalad …

RF: use parse_known_args instead of _parse_known_args

---

datalad/core/local/run.py

AFAIK, those could point to directories since otherwise such option
would not scale for many realistic scenarios.  But @djarecka mentioned
that docs explicitly mention file only, not directories, which led her
to believe that it must point to a file.
May be wording could be adjusted, I was aiming for the shortest way to express myself.  Or should we switch to use `path` instead of `file`?

DOC: run - adjust description for -i/-o to mention that it could be a directory

---

datalad/local/add_archive_content.py

This function bears a potential security risk and has been deprecated
since Python version 2.3. This change replaces its use with mkdtemp,
which creates a temporary directory in a more secure manner
As mkdtemp does not clean the temporary directory up afterwards, this
change also adds a removal of any leftover empty temporary directories.
- ``add-archive-content`` does not rely on the deprecated ``tempfile.mktemp`` anymore, but uses the more secure ``tempfile.mkdtemp``

MNT: remove deprecated mktemp from add-archive-content

---

datalad/core/local/run.py

This should have been done from the very beginning, but it was not
necessary to achieve the desired behavior due to a series of
side-effects of the complexity of determining the effective result
renderer (see #6394 for an entry point into the series of changes).
- `run` no longer let's the internal call to `save` render its results unconditionally, but the parameterization of `run` determines the effective rendering format. Fixes #6420

Prevent double-rendering of save results by run.

---

datalad/core/local/save.py
datalad/core/local/tests/test_save.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py
datalad/support/tests/test_fileinfo.py
datalad/support/tests/test_repo_save.py
datalad/tests/utils.py

This PR works towards #6076, which calls out the ``AnnexRepo``'s ``annexstatus`` method is undocumented and mostly unused with the exception of tests. 
Its remaining usecases are addressed as follows:
- A few spots (in ``save`` and ``GitRepo``) rely on the existence of this method in ``ds.repo`` to assert whether or not we're dealing with an AnnexRepo. These spots were changed to instead check for a ``uuid`` property, which should exist in AnnexRepos but not in GitRepos
- A few tests were using ``annexstatus``. Some were able to change to use ``get_content_annexinfo``. For those that didn't, I moved ``annexstatus`` into ``tests/utils`` as a new test helper ``get_annexstatus``.
- AnnexRepo's internal ``annexstatus`` is deprecated. In its place, a new test helper assists the few tests that …

MNT: Deprecate annexstatus

---

.appveyor.yml
.github/workflows/benchmarks.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml
.github/workflows/test_macos.yml
.github/workflows/test_win2019_disabled
.travis.yml
datalad/downloaders/__init__.py
datalad/downloaders/base.py
datalad/downloaders/credentials.py
datalad/downloaders/http.py
datalad/downloaders/providers.py
datalad/downloaders/tests/test_credentials.py
datalad/interface/common_cfg.py
datalad/local/gitcredential.py
datalad/local/gitcredential_datalad.py
datalad/local/tests/test_gitcredential.py
docs/source/credentials.rst
docs/source/design/credentials.rst
docs/source/index.rst
setup.py

Towards #5028
This description is updated by me (@bpoldrack), since I took over.
This implements an integration with `git-credential` in both directions:
1. A `git-credential-datalad` script that allows git to query (and store to)
Datalad's credential system, by adding it as potential backend by setting 
`credential.helper=datalad`. This credential helper will query datalad for a 
provider matching the URL in question and retrieve the linked credentials.
The other way around, storing will create such a provider config file and the 
respective credential entries via `keyring`.
2. `Gitcredential` class, that can be referred to by provider configs as the 
`type` of credential ('git'). This allows datalad to use `git-credential` 
instead of `keyring`. Credentials provided via datalad config …

git-credential interfaces (datalad's in Git and vice versa)

---

datalad/cli/helpers.py
datalad/cli/main.py
datalad/cli/parser.py
datalad/cli/tests/test_main.py

It basically inspects the incomplete argument list now, and
based on that can make more clever decisions what to load.
There are more possibilities for making things faster. For
example, we could load the extensions one by one, while searching
for unknown commands. But already now it feels great.
This change should have no impact on the full help generation. But it
breaks the interal operations needed to build manpages and docs.
This needs fixing, but was always ugly anyways.
Closes #6407 
TODO:
- The CLI help generation has been sped up, and now also supports the completion of parameter values for a fixed set of choices.

Make CLI autocompletion snappy

---

datalad/distributed/create_sibling_ria.py
datalad/local/wtf.py

By including None in the choice list. This makes for a better
documentation and enables auto-completion, provided by #6415
This accompanies https://github.com/datalad/datalad/pull/6415#issuecomment-1032559152 but it independent of it.
This does not need to show up in the changelog.

Simplify pattern 'EnsureChoice(..) | EnsureNone'

---

datalad/cli/common_args.py
datalad/core/local/run.py
datalad/core/local/tests/test_run.py

- Individual command implementations can now declare a specific "on-failure" behavior by defining `Interface.on_failure` to be one of the supported modes (stop, continue, ignore). Previously, such a modification was only possible on a per-call basis. Fixes #6426
- The `run` command changed its default "on-failure" behavior from `continue` to `stop`. This change prevents the execution of a command in case a declared input can not be obtained. Previously, only an error result was yielded (and `run` eventually yielded a non-zero exit code or an `IncompleteResultsException`), but the execution proceeded and potentially saved a dataset modification despite incomplete inputs, in case the command succeeded. This previous default behavior can still be achieved by calling `run` with the equivalent …

Enable custom "on-failure" settings and employ for `run` with `on_failure='stop'` by default

---

datalad/runner/nonasyncrunner.py

Remove an unnecessary warning from the runner in the case where `stdin` is provided, but does not fit any of our specially handled cases.
Fixes #6395 
- Fixes #6395   remove an unnecessary and misleading warning

Remove an unnecessary warning from the runner

---

datalad/core/local/run.py

- The `run` command now provides readily executable, API-specific instructions how to save the results of a command execution that failed expectedly. Fixes #2986

Tailor help message to API

---

datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

First commit is truly a BF and destined to `maint`. The 2nd addresses the limitation (we were just raising a ValueError, not even NotImplementedError) if asked to perform in batch mode on keys.  Support for that functionality was added only recently to git-annex, and since change is small, I have decided to bundle it within the same PR against `maint`. But I would be ok to split it into `master`.  Motivation -- a need for datalad-fuse development.
attn @jwodder (I will provide more context in datalad-fuse later)
- Fixes `AnnexRepo.whereis` operation in `key=True` mode whenever multiple keys are provided.
- Adds support  for batch mode operation to `AnnexRepo.whereis` in `key=True` mode (requires git-annex 8.20210903 or later)

Fix AnnexRepo.whereis key=True mode operation, and add batch mode support

---

datalad/local/addurls.py
datalad/local/tests/test_addurls.py

The constructor of `datalad.local.addurls.RegisterUrl` uses the parameter `repo` wich defaults to `None` during comparison. It should instead use the attribute `self.repo`, which is initialized to `ds.repo` if `repo` is `None`.
This PR uses `self.repo` in the constructor and adds a regression test.
This was not reported in an issue, but is definitively a bug in my opinion.

Use `self.repo` in `RegisterUrl`-constructor

---

datalad/distribution/create_sibling.py
datalad/distribution/tests/test_create_sibling.py

Two commits:
OPT: create_sibling - diff to HEAD not None (tree)
Primary motivation is very slow --since= mode of operation of create-sibling
on a heavy superdataset (see #6399).  Although it could be argued that there might be
a benefit from create-sibling to be able to create siblings for not yet committed
submodules, I think such use cases are sparse if any and thus diff"ing to the committed
state (HEAD) is actually the desired effect.
Fixes #6399 (although I did not check explicitly)
-----
RF: create-sibling --since to take "^" instead of ""
to be consistent with "push" and thus reduce cognitive load.  Old value of an
empty string will remain supported.  While at it, added a tiny bit of testing
to ensure that --since actually works out the way we expect and only deals with
that …

OPT+RF: create-sibling --since=^ -- diff to HEAD, use "^" instead of ""

---

datalad/cmd.py
datalad/local/addurls.py
datalad/support/annexrepo.py

This PR changes a warning message to a debug message. The message indicates that there is still unprocessed command-output in a BatchedCommand object, when the BatchedCommand object is closed.
This PR fixes #6431 
- Remove a warning message that does not necessarily indicate an error, but might confuse users.

Demote BatchedCommand remaining content-warning to debug message

---

datalad/core/local/run.py
datalad/interface/tests/test_utils.py
datalad/interface/utils.py

This PR salvages all commits from https://github.com/datalad/datalad/pull/5695 that are still relevant, except for https://github.com/datalad/datalad/pull/5695/commits/a5d554b70d56587eb5e0a9652ae1dbac036dac1b which is presently being debated in https://github.com/datalad/datalad/issues/6438 (as one of two options).
- Common command arguments are now uniformly and exhaustively passed to result renderers and filters for decision making. Previously, the presence of a particular argument depended on the respective API and circumstances of a command call.

Salvage parts of #5695

---

.appveyor.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml
.github/workflows/test_macos.yml
.github/workflows/test_win2019_disabled
.travis.yml
datalad/__init__.py

We should strive to avoid needing to adjust CI and packaging (which runs tests)
to introduce some new testing aspect.  All setup should be carried out in
fixtures and our fake test HOME whenever necessary.
Otherwise, I cannot even run tests locally ATM without setting up some
variables etc, or discovering what login it actually wants from me:
$> python -m nose -s -v datalad/local/tests/test_gitcredential.py
datalad.local.tests.test_gitcredential.test_credential_cycle ... create(ok): . (dataset)
add(ok): .datalad/providers/test_cycle.cfg (file)
Username for 'https://some.data.exampe.com':
no need since feature fixed here was introduced after release
Closes  #6442 (hopefully)
Replaces https://github.com/datalad/git-annex/pull/101

BF: define git config and GIT_ASKPASS in the setup_package instead of each CI

---

datalad/core/distributed/clone.py
datalad/distribution/install.py
datalad/interface/utils.py
datalad/local/download_url.py

A recent change has introduced double reporting for a number of commands (#6445). I haven't figured out why this change has suddenly happened, but this PR silences (``result_renderer='disabled'``) internal calls to ``save`` and ``get`` that should be silenced anyway.
In addition, it contains a small RF that centralizes general result renderer switches outside of a loop. Coincidentally, this RF reinstates action summaries for a few commands that had lost it (#6258)
- A number of commands stopped to double-report results (by @adswa)

BF/RF: Silence save result rendering in clone and download url

---

.appveyor.yml

Also test datalad.dataset on Mac and Win
No changelog item needed.
I canceled all other workflows.

Split Ubuntu CI run to prevent timeouts

---

datalad/core/local/run.py

This prevents double reporting of unlock.
Prior to this change, a run that unlocks a file looks like this:
```
datalad run --input api.py --output some 'cat api.py >> some'
[INFO   ] Making sure inputs are available (this may take some time)
unlock(ok): some (file)
unlock(ok): some (file)
[INFO   ] == Command start (output follows) =====
[INFO   ] == Command exit (modification check follows) =====
run(ok): /tmp/mamam (dataset) [Executed command]
add(ok): some (file)
```
With this change:
```
datalad run --input api.py --output some 'cat api.py >> some'
[INFO   ] Making sure inputs are available (this may take some time)
unlock(ok): some (file)
[INFO   ] == Command start (output follows) =====
[INFO   ] == Command exit (modification check follows) =====
run(ok): …
```

Silence result rendering in run's use of drop()

---

datalad/local/unlock.py

Add missing keyword args to internal call of Status-interface
- add `return_type` keyword arg to internal Status call in unlock

Issue #6461 work on `unlock()`

---

datalad/core/distributed/clone.py

Update after #6446, which did not set the return type explicitly as outlined in #6461.
This change specifies the return type of a save call to save .gitmodules to be a generator.
no changelog needed

MNT: use generator return_type in internal save call in clone

---

datalad/local/copy_file.py

Following #6461, this takes the output of copyfile from
```
❱ datalad copy-file input/dataset_description.json -d .
[INFO   ] Copying non-annexed file or copy into non-annex dataset: /tmp/abcd/input/dataset_description.json -> AnnexRepo(/tmp/abcd)
copy_file(ok): /tmp/abcd/input/dataset_description.json
add(ok): dataset_description.json (file)
add (ok: 1)
save (ok: 1)
add(ok): dataset_description.json (file)
add (ok: 1)
copy_file (ok: 1)
save (ok: 1)
```
to
```
datalad copy-file input/participants.json -d .
[INFO   ] Copying non-annexed file or copy into non-annex dataset: /tmp/abcd/input/participants.json -> AnnexRepo(/tmp/abcd)
copy_file(ok): /tmp/abcd/input/participants.json
add(ok): participants.json (file) …
```

MNT: Silence result rendering of copy-file's internal save() call

---

datalad/distribution/get.py

Add a missing result_renderer-spec in call to subdatasets
- disable result renderer in internal call  to subdataset in get

Unify keyword in the spirit of issue #6461

---

datalad/distribution/install.py

Re #6461.
This reduces the reporting from 
```
datalad install ///datalad
install(ok): /tmp/path/datalad (dataset)
install(ok): /tmp/path/datalad (dataset)
install(ok): /tmp/path/datalad (dataset)
```
to
```
datalad install ///datalad
install(ok): /tmp/datalad (dataset)
```
no need for a changelog

MNT: Silence internal command calls in install

---

datalad/core/local/run.py
datalad/core/local/tests/test_run.py
docs/source/design/index.rst
docs/source/design/provenance_capture.rst

Work towards
- #6401
- #2850
This adds a bunch of features to the internal `run`/`rerun` workhorse `run_command()` that are necessary to be able to implement a solution to #6401 efficiently, without reaching further into the guts of the machinery.
I will keep this open, until such a solution is fully implemented, and testable -- however, I am fairly confident at this point that this is pretty much the entire change. I am hoping to be able to add a design document on run records and `run`'s results at the very end. Reviews welcome now!
TODO:
- `run` now supports placeholders in input and output specifications. This includes all standard and custom placeholders, and enables use cases like `--inputs '{outputs}'` to conveniently declare all outputs to also be inputs for a command execution. …

`run` improvements towards #6401

---

datalad/distributed/ora_remote.py

New pattern introduced with ecd4577753d9e82cdb097d35368eadcf79e24e21
- `git-annex-remote-ora` now provides the same standardized CLI interface as other special remotes and the core package with support for help and version reporting.

Replace custom entrypoint with standard for special remotes

---

datalad/local/add_readme.py

This updates `add-readme`  according to #6461. Previously, 'datalad add-readme' resulted in double reporting that looked
like this:
```
datalad add-readme
[WARNING] Found no aggregated metadata info file /tmp/abcd/more/.datalad/metadata/aggregate_v1.json. You will likely need to either update the dataset from its original location or reaggregate metadata locally.
metadata(impossible): . (dataset) [Dataset at . contains no aggregated metadata on this path]
[WARNING] Could not obtain dataset metadata, proceeding without
add_readme(ok): /tmp/abcd/more/README.md (file)
add(ok): README.md (file)
add (ok: 1)
save (ok: 1)
add(ok): README.md (file)
add (ok: 1)
add_readme (ok: 1)
save (ok: 1)
```
With this change applied, …

MNT: Silence internal command calls' result rendering in add-readme

---

datalad/support/keyring_.py

This outdated way of specifying credentials needs to be kept while at
the same time it is not documented (only indirectly in context of HCP OA
for example). Hence, the added note is important to stumble upon on
refactoring.
Just an internal comment - no changelog here.

DOC: Add remark to old credential env vars

---

datalad/core/local/create.py
datalad/local/run_procedure.py
datalad/resources/procedures/cfg_metadatatypes.py
datalad/resources/procedures/cfg_noannex.py
datalad/resources/procedures/cfg_text2git.py
datalad/resources/procedures/cfg_yoda.py

Judging from the handbook, a ``create -c text2git`` call produced the following output in the past:
```
$ datalad create -c text2git DataLad-101
[INFO] Creating a new annex repo at /home/me/dl-101/DataLad-101 
[INFO] scanning for unlocked files (this may take some time)
[INFO] Running procedure cfg_text2git 
[INFO] == Command start (output follows) ===== 
[INFO] == Command exit (modification check follows) ===== 
create(ok): /home/me/dl-101/DataLad-101 (dataset)
```
Currently, the output looks like this:
```
datalad create -c text2git dl-101
[INFO   ] Creating a new annex repo at /tmp/dl-101 
[INFO   ] Running procedure cfg_text2git 
[INFO   ] == Command start (output follows) ===== 
add(ok): .gitattributes (file) …
```

Restore the previous result rendering of ``create -c <proc>`` and ``run-procedure``

---

datalad/cli/parser.py

This is used to support the weird parser construction mode that is
only used to construct parsers for manpage generation during extension
package documentation builds. Eventually this must all be factored
out into dedicated helpers that do this, and only only this -- instead
of being shoehorned into code that must run a quick as possible.
That being said, this fix removes this 0.16 release blocker, and makes
the broken extension package doc build work again.
Fixes datalad/datalad#6490
No entry needed, only broken in unreleased code.

Replace left-over (unused) mode label in CLI parser

---

datalad/customremotes/ria_utils.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/tests/test_create_sibling_ria.py
datalad/distributed/tests/test_ria_git_remote.py

`create-sibling-ria` and the underlying helper created a dataset's `annex/objects` directory unconditionally.
However, only having the git repositories in store with no special remote and no data whatsoever is valid and supported usecase. The existence of that (empty) directory increases the inode count per dataset, is superfluous and leads to failures of annex commands being executed directly in store. While the latter is something to generally be very careful about, there are valid usecases and with the previous behavior we'd cause annex to pointlessly fail on discovery of that dir, indicating to annex that the repo is not annex-init'ed but was apparently used with annex before.
- `create-sibling-ria` no longer creates an `annex/objects` directory in-store, when called with …

BF: No object tree in RIA w/o special remote

---

datalad/core/distributed/clone.py
datalad/support/network.py

Instead of randomly crashing, raise a uniform ValueError whenever
anything goes wrong. Include any original exception as a cause.
Re datalad/datalad#6494 this changes:
```
[ERROR  ] ValueError(invalid literal for int() with base 10: 'datalad-datasets') (ValueError)
```
to
```
[ERROR  ] ValueError(Could not determine resource identifier type for 'https://github.com:datalad-datasets/human-connectome-project-openaccess.git') (ValueError)
```
- Improve error message when an invalid URL is given to `clone`. Fixes #6494

Guard RI-type determination

---

datalad/downloaders/base.py

apparently that does not play nice with multi-threading parallelization,
where (I guess) we instantiate and reuse the same Downloader across multiple
threads, and thus reusing the lock.
Bu instantiating the lock right before using it, albeit may be adding even more runtime
overhead, we are avoiding the problems with InterProcessLock.
Closes #6483 and also see https://github.com/harlowja/fasteners/issues/91 for more
information.  Filed also https://github.com/datalad/datalad/issues/6506 which observed while troubleshooting.
~~I am yet to try it on actual original HCP use case, but~~ with this script
http://www.onerussian.com/tmp/ts-parallel-download.py
and this list of urls for our store http://www.onerussian.com/tmp/store-configs.txt
`/bin/rm -f /tmp/out/*; head -n 1000 …

BF: do not use BaseDownloader instance wide InterProcessLock - resolves stalling or errors during parallel installs

---

setup.py

https://github.com/datalad/datalad-osf/issues/123 reported a failure for
token-based authentication when elderly versions of SecretStorage were used
that could not handle empty passwords (as is the case with token-based auth).
This PR updates the minimum dependency of the ``keyring`` package to fix
this issue. ``keyring`` versions ``20.0`` or higher have dependencies to sufficiently
recent versions of SecretStorage that contain a fix for the original issue.
This dependency has not be set for quite a while because recent enough
versions of ``keyring`` were not uniformly available (see https://github.com/datalad/datalad-osf/pull/130),
but now that recent versions of the package are widely available, we can 
incorporate this fix into datalad core.
fixes #6498 and …

Set a minimum dependency on keyrings version 20.0 

---

datalad/distribution/update.py

Move `save()` call into a dedicated helper to reduce the cognitive
complexity of the monster Update.__call__() method.
In the spirit of datalad/datalad#6461
No changelog needed.

Disable internal save-result rendering in update()

---

datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ria_basics.py
datalad/tests/test_utils.py
datalad/utils.py

Fixes #6254
Previously the ORA special remote relied on whatever the store end
is set up to with respect to permissions and accepted them as is,
meaning it didn't try to obtain write permissions on the parent
directory when dropping a key from store. However, there are good
reasons to revoke write permissions in store, particularly when the
object tree is meant to be used with ephemeral clones.
Hence, do what git-annex would do in the local case: View that as
protection against direct user interaction and try to obtain permission
on drop.
- ORA special remote tries to obtain permissions when dropping a key from a RIA store rather than just failing. Thus having the same permissions in the store's object trees as one directly managed by git-annex would have, works just fine now. Fixes #6254 …

Relax permissions needed in RIA stores

---

datalad/distributed/ora_remote.py

Instead use the one that already exists in any process. Which also
already has `atexit` setup.
- ORA remote no longer uses its on `SSHManager` instance, but the standard process-wide one provided by the `datalad` module. Fixes #6523

ORA: discontinue use of duplicate SSHManager

---

datalad/distribution/dataset.py
datalad/distribution/tests/test_dataset.py
datalad/local/configuration.py

Before it claimed to raise InsufficientArgumentsError uniformly,
but actually raised NoDatasetFound or ValueError, depending
on the exact error condition.
This change consolidates and documents raising NoDatasetFound,
which seems to make most sense.
- `require_dataset()` now uniformly raises `NoDatasetFound` when no dataset was found. Implementations that catch the previously documented `InsufficientArgumentsError` or the actually raised `ValueError` will continue to work, because `NoDatasetFound` is derived from both types. Fixes #6503

require_dataset() uniformly raises NoDatasetFound

---

datalad/dataset/gitrepo.py
datalad/runner/exception.py
datalad/runner/gitrunner.py
datalad/runner/protocol.py
datalad/runner/tests/test_utils.py
datalad/runner/utils.py
datalad/support/annexrepo.py

This PR adds code to correctly handle the situation where encoded data is delivered in parts to `SubprocessProtocol.pipe_data_received()`, and where a part ends in the middle of an encoded Unicode character. The PR introduces a mix-in class that is usually used in subclasses of `WitlessProtocol`.
This fixes issue #6526 and other parts of the code that could have potentially suffered from the same problem. 
TODO:
- Fix an issue where partially delivered data lead to decoding errors ... Fixes #6526

Handle partially delivered encoded data

---

datalad/support/sshconnector.py
datalad/support/tests/test_annexrepo.py
datalad/support/tests/test_gitrepo.py
datalad/support/tests/test_sshconnector.py

As far as I can see it, the socket provides an authenticated connection,
but no persistent shell. Any command adjustments for use of a bundled
Git are per-call, and do not anyhow impact the SSH control master
process.
The `bundled` parameter of `get_connection_hash()` is ignored from now,
but kept to not break user code. Deprecation messages have been added.
- The `bundled` parameter of `get_connection_hash()` is now ignored and will be removed with a future release. Fixes #6531.

Stop including annex-bundle info in SSH connection socket name

---

datalad/interface/common_cfg.py
datalad/support/sshconnector.py

Previously, this feature was enabled unconditionally for any use of
`datalad sshrun`. We use this command as `GIT_SSH_COMMAND` and also
configure it to be used by git-annex. Consequently, it is used for
pretty much any SSH-related functionality.
This change introduces a new config switch to enable/disable this
feature, and the defaults of the underlying methods have been adjusted
to honor this switch.
As can be seen below, this has the potential to increase remote
execution performance substantially (here 500ms or 20+% for a call to
`uname`. The observed cost is per each call to `sshrun`.
```
===> multitime results
1: datalad -c datalad.ssh.try-use-annex-bundled-git=true sshrun judac.fz-juelich.de uname
Mean        Std.Dev.    Min         Median      Max
real        2.530       0.126 …
```

Make SSH remote annex bundle sensing configurable and off by default

---

datalad/support/sshconnector.py

We did this initially for non-multiplex connections, assuming that it
would not work "by-design" when the SSH process is controlled by a
process that is not directly connected to a terminal on windows.
However, explorations documented in https://github.com/datalad/datalad/issues/5829
and https://github.com/datalad/datalad/issues/6524 revealed that this is
wrong, and the reason for it appearing to not work is in the protocol
handling within `Runner`.
This patch merely removed the forceful disabling, and thereby
immediately makes `sshrun` functional on windows.
- Keyboard-interactive authentication is now possibly with non-multiplexed SSH connections (i.e., when no connection sharing is possible, due to lack of socket support, for example on Windows). Previously, it was disabled forcefully …

Stop forcefully disabling keyboard-interactive SSH auth

---

datalad/distributed/tests/test_ria_basics.py
datalad/tests/test_utils.py

failures were observed in the sudo run on cron on travis,
https://app.travis-ci.com/github/datalad/datalad/jobs/563044936
FAIL: datalad.distributed.tests.test_ria_basics.test_obtain_permission(None,)
File "/tmp/dl-miniconda-yilg0v_t/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
File "/tmp/dl-miniconda-yilg0v_t/lib/python3.9/site-packages/datalad/tests/utils.py", line 2016, in _wrap_skip_if_adjusted_branch
return func(*args, **kwargs)
File "/tmp/dl-miniconda-yilg0v_t/lib/python3.9/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
return t(*(arg + …

BF(TST): Skip 3 tests if root --  PermissionError not raised

---

datalad/support/keyring_.py

BF: account for "No such password" in addition to not found returned by keyring

---

datalad/cli/main.py

Whenever an exception reached the `main()` exception handler, it is
converted to a `CapturedException()` and `str(CapturedException)`,
plus the exception type is logged. However, the exception type
is already contained in the `__str__` output:
```
[ERROR  ] ValueError(Value or unset flag ":" missing for property [('ddd',)]) (ValueError)
```
With this change, this duplication is removed and changes the output to
```
[ERROR  ] Value or unset flag ":" missing for property [('ddd',)] (ValueError)
```
This is specifically not identical to the output of
`str(CapturedException())`, in order to maintain the previous spirit of
putting more emphasis on the user-facing message, rather than the
technicality of the specific exception name.
- Remove duplicate exception type in reporting of top-level …

Deduplicate top-level CLI exception handler output

---

.appveyor.yml
.travis.yml
tools/coverage-bin/datalad
tools/coverage-bin/sitecustomize.py

The changes here enable subprocess coverage and fix #6367. They follow different docs:
- Following https://coverage.readthedocs.io/en/latest/subprocess.html, this change sets the ``COVERAGE_PROCESS_START`` environment variable, and lets it point to the ``.coveragerc`` file.
- Following the first approach described in https://coverage.readthedocs.io/en/latest/subprocess.html, this change creates a ``sitecustomize.py`` file. As this file needs to be in the Pythonpath, I'm following https://pymotw.com/2/site/#sitecustomize to modify the ``PYTHONPATH`` accordingly
- Finally, this change changes the installation of DataLad from a system-wide installation to a local (user) installation. This is a workaround, because with a system-wide installation coverage refused to collect any coverage for …

Enable coverage for subprocesses

---

datalad/distribution/create_sibling.py
datalad/support/sshconnector.py

`quote_cmdlinearg()` uses the local platform to decide on the quoting
style, not the remote.
This change also adjusts an import to make more obvious what helper is being
used.
See datalad/datalad#6522 for details.
Not needed

Stop advertising a broken quoting solution for remote commands.

---

datalad/interface/common_cfg.py
datalad/support/sshconnector.py

This PR fixes #5829 
This PR enforces the use of the system windows ssh client (OpenSSH for Windows) in `sshconnector.py`. The reason for this restriction is that other ssh clients, namely the ssh client that is bundled with git for windows, do not properly work when called by git (see the discussions in issue #5829).
The PR introduces the new environment variable `DATALAD_WINDOWS_SSH_CLIENT` that can be set to inform `datalad` about an alternative location of the system ssh client.
Possible future improvements:
- We do not currently verify that the ssh-client is indeed the system windows ssh-client.
- This PR requires the installation of OpenSSH for Windows in order to use datalad with ssh on windows. We might want to investigate why other ssh clients do not properly work and fix the …

Enforce system ssh client usage on Windows

---

datalad/customremotes/base.py
datalad/ui/progressbars.py

(again)
This was removed (unintentionally) when the `datalad` and `-archives` special remotes were reimplemented in https://github.com/datalad/datalad/pull/6165
I only now understood (for a brief moment in time) how this actually works.
This change places a dedicated method in the `AnnexCustomRemote` base class (again) that serves as a receiver and place of documentation.
Fixes datalad/datalad#6572
Replaces #6573
Not needed

Channel progress logging by AnnexSpecialRemoteProgressBar to git-annex

---

datalad/support/annexrepo.py
datalad/tests/test_utils.py
datalad/utils.py

An alternative to https://github.com/datalad/datalad/pull/6583 avoiding
deriving another decorator for added parametrization -- we might eventually
start talking about combinatorics if decide to tune another aspect of its
behavior
Closes #6479

ENH: add "short" option to @auto_repr and use for BatchedAnnex

---

datalad/__init__.py
datalad/support/annexrepo.py

This is inspired as a possible workaround for the
https://github.com/datalad/datalad/issues/6482
which is probably sufferring from another issue, but looking
at this code, I do not see why just not to set it in the fixture.
Since it seems to workaround reliably, announcing that Fixes #6482 
The only cons I can foresee is the test scenario where in fixture
we do not prepare our home whenever GIT_HOME is set.  IIRC it
was the case in debian package building case, but if needed,
we could set those up in debian/rules.
I also foresee that tests might run a little faster since we should then avoid `git config` call(s) for every temp annex repo -- aren't we?

RF: set allowed-url/http in test HOME .git/config instead of config calls per instance

---

datalad/api.py
datalad/cli/helpers.py
datalad/interface/test.py
datalad/local/run_procedure.py
datalad/local/wtf.py
datalad/metadata/extractors/tests/test_base.py
datalad/metadata/metadata.py
datalad/support/entrypoints.py
setup.py

This approach is now an offiical part of the standard lib (since 3.10), and is available for earlier version in a provisional module and also a separate package.
This change introduces `datalad.support.entrypoints` with `iter_entrypoints()` that is now used as a uniform implementation.
As previously shown in https://github.com/datalad/datalad/issues/6584 this brings significant performance improvements for internal processing. Moreover, they translate to outward-facing speed gains. On a system with 10 extensions installed a `datalad -h` now completes in ~300ms, whereas current mainline after the CLI update needs ~650ms, and the latest release 0.15.6 needs ~1200ms -- so overall a 4x speed-up.
Importantly, the new `iter_entrypoints()` helper does not return complex entrypoint instances …

Consolidate entrypoint processing on importlib.metadata

---

.github/workflows/test_extensions.yml

This PR will disable metalad tests. Currently metalad is changing a lot and CI does not seem to respect pinned versions of required pypi packages. That leads to environements with non-working metalad installations.

disable metalad tests

---

datalad/distributed/export_to_figshare.py

This aims at standardizing result reporting/behavior over operations that
refuse to operate in dirty datasets. export-to-figshare does it similarly
to run now, and yields an impossible result. Fixes #6474.
Before:
```
datalad export-to-figshare
[ERROR  ] RuntimeError(Paranoid authors of DataLad refuse to proceed in a dirty repository) (RuntimeError)
```
Now:
```
datalad export-to-figshare
export_to_figshare(impossible): /tmp/super (dataset) [clean dataset required to export; use `datalad status` to inspect unsaved changes]
```
- When operating in a dirty dataset, `export-to-figshare` now yields and impossible result instead of raising a RunTimeError

UX: Make export-to-figshare yield an impossible result instead of a RunTimeError in dirty ds

---

datalad/api.py

Discovered during extension development.
No changelog needed. Introduced with #6591

Wrong variable name in conditional code path

---

.github/workflows/test_extensions.yml

Metalad version 0.3.0 has been released. The released version passes the datalad-metalad extension tests. The tests should therefore be enabled again.
- re-enable datalad-metalad extension tests after datalad-metalad release `0.3.0`.

Add datalad-metalad to tested extensions

---

datalad/core/local/tests/test_save.py
datalad/core/local/tests/test_status.py
datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py
datalad/support/annex_utils.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

As of annex 10.20220127 we observed several failures on macOS, which at this point is the only build with that recent an git-annex.
These failures boil down to two issues:
- One issue became apparent (actually older), where the reporting of annex commands with respect to paths that are
unknown to git or not existent at all happens in different ways. This depends on annex' internal git calls (git itself appears to be inconsistent WRT this message) as well as on the value of 'annex.skipunknown' the default of which changed in said version. This results in both styles of reporting being used and as long as we rely on parsing that output, we need to account for both.
Moreover, annex commands don't always exit non-zero when that happens, which is why we need to check stderr output when the …

Fixing test failures with recent annex

---

datalad/cli/main.py
datalad/coreapi.py
datalad/interface/common_cfg.py
datalad/support/entrypoints.py

Performance impact when this feature is unused, is negligible. Otherwise it is determined by the import time of a particular extension's `__init__.py`.
- A new configuration switch `datalad.extensions.load` can be used to load particular DataLad extension packages on startup. This enables extensions to also enhance core commands, such as teaching the `clone` command to handle additional types of URLs. To continue to use commands provided by extensions, this new configuration is not necessary. Fixes #6589

Enable loading select extensions on CLI startup or API import 

---

datalad/cmd.py

WitlessRunner created with env populated from that call, so the .run
could just use it if env is not provided to its invocation.
There is no reason to call that function twice AFAIK.

RF/OPT: do not call get_git_environ_adjusted twice for BatchedCommand

---

datalad/customremotes/__init__.py
datalad/distributed/ora_remote.py

@mih reported on the following current behavior:
> This is what it was -- not pretty, but this is 0.15
> ```
> % datalad clone https://github.com/psychoinformatics-de/studyforrest-data-phase2.git httpclone0.15
> [INFO   ] scanning for annexed files (this may take some time)                                                                                                                             
> [INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                                                                                      
> [INFO   ] https://github.com/psychoinformatics-de/studyforrest-data-phase2.git/config download failed: Not Found 
> [INFO   ] [INFO] Fetching 'http://studyforrest.ds.inm7.de/ria-layout-version' 
> [INFO   ] …
```

UX: Better message when ORA does not find store via HTTP

---

datalad/distributed/ora_remote.py

Separating reading provider configs from downloading a key, since this
was a per-key operation unnecessarily slowing down HTTP downloads.
Magically, this also enables per-key progress bars (addressing #4500 for the HTTP case). This seems to depend on the persistence of the `Provider` and/or `Downloader` instance across keys. Same call path does not work, when `Providers` are read anew from the configs on a per-key basis (as the implementation using `download_url` did).
- ORA special remote didn't show per-file progress bars when downloading over HTTP
- Removed a per-file overhead cost for ORA when downloading over HTTP

Don't use download_url in ORA

---

datalad/distribution/create_sibling.py
datalad/distribution/tests/test_create_sibling.py

Initial motivation for this change was fixing
https://github.com/datalad/datalad/issues/6596
where while specifying --since, create-sibling  did not detect needing to
create a sibling for a subdataset.  A stale (missed during #6528 OPT/RF)
comment said that value of constant_refs=True should not matter since it was
not recursive originally. But now here we do recurse and it does matter since
we migth completely skip subtree where such refs are not yet known.  Changing
to False resulted in the test failing which made me realize that sibling was
created even for not yet committed changes to submodules.  Since for push it
would really not work to push something which is not yet saved, I think the
change in behavior for create-sibling is also desired.  And it fixes #6596.
So I have "fixed" …

BF/RF: create-sibling follow diff with constant_refs=False + operate on committed subds

---

datalad/core/local/tests/test_status.py
datalad/support/annex_utils.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

Commit 7c4a5437bb35afa72e0f70e78196103144c9ec73 was wrong about when
exactly annex' default for `annex.skipunknown` changed to false.
- Fix test conditions referring to an incorrect annex version

BF: Wrong annex version tested

---

.appveyor.yml

Remove AppVeyor's world-matching default entries for gitlab.com in `known_hosts`, that led to `Remote host identification changed` with pretty much every SSH invocation.
See https://github.com/datalad/datalad/issues/6599#issuecomment-1085744290

Sanitize AppVeyor's known_hosts

---

datalad/distributed/drop.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py

This PR introduces the method `AnnexRepo._call_annex_items_()`, which returns a generator that yields the same results as `AnnexRepo._call_annex()`, but as soon as they are available. The new method is used by `datalad drop`.
Fixes #6578 
- Improve responsiveness of `datalad drop` in datasets with a large annex.

Use yielding annex record calls for `drop`

---

setup.py

Datalad now depends on entry_points taking kwargs, introduced in https://github.com/python/importlib_metadata/commit/8320adef797d5f14d9fff7b58ebc2a31a2a6a437, first released in importlib-metadata 3.6.
Apologies for ignoring your PR template, but it's unclear where this fits in your changelog set.

MNT: Require importlib-metadata >=3.6 for Python < 3.10 for entry_points taking kwargs

---

datalad/__init__.py

In particular useful while troubleshooting extensions, which would
typically reuse the same setup/teardown as of the core package.
Ran into such a desire while looking at https://github.com/mih/datalad-mihextras/issues/27

ENH: include version of datalad in tests teardown Versions: report

---

datalad/core/distributed/push.py
datalad/distributed/create_sibling_ghlike.py
datalad/tests/test_utils.py
datalad/utils.py

This commit delegates the actual data transfer in
push to a new method: _transfer_data. This is done
to simplify monkey-patching via "datalad_next", in
order to implement export to git-annex special remotes
with type webdav and exporttree enabled.
This is a first step to address issue #3127 
- factor out actual data transfer in push, in order to make it "patchable".

Factor out actual data transfer in push

---

datalad/dochelpers.py

Previously, log messages like this would appear at DEBUG level:
```
[DEBUG] parseParameters: Given "exclude_special_remotes: bool, optional
if True, don't return annex special remotes", we split into [('exclude_special_remotes', "exclude_special_remotes: bool, optional\n  if True, don't return annex special remotes")]
```
These are very verbose and large in number, making debug
output needlessly complicated to read.
Moreover, they log the outcome of a trivial operation that practically
never fails in production code, at a comparatively high level (DEBUG),
and they did it in an expensive way that actually built the log string
unconditionally of the effective log level.
This change demote the log level to the lowest possible, and uses a proper
logging pattern that avoid needless string …

Demote (to level 1 from DEBUG) and speed-up API doc logging (parseParameters)

---

datalad/distributed/create_sibling_ria.py

- Removed unsupported `None` value from constraint definition of `create_sibling_ria(existing=...)`

Remove unsupported parameter create_sibling_ria(existing=None)

---

datalad/core/distributed/clone.py
datalad/core/distributed/push.py
datalad/core/local/create.py
datalad/core/local/status.py
datalad/customremotes/base.py
datalad/dataset/gitrepo.py

Every invocation produces this INFO-level message:
```
% datalad create myds
[INFO   ] Creating a new annex repo at /tmp/myds
create(ok): /tmp/myds (dataset)
```
This is not a long-running operation. In most cases, the INFO log and the result arrive near-simultaneously.
It also duplicates DEBUG messages:
```
[INFO   ] Creating a new annex repo at /tmp/demo12
[DEBUG  ] Initialize empty Git repository at '/tmp/demo12'
[DEBUG  ] Initializing annex repository at /tmp/demo12...
```
Removed for a cleaner user experience.
Fixes #6633 
Not needed.

Remove two too prominent create() INFO log message that duplicate DEBUG log and harmonize some other log messages

---

datalad/runner/protocol.py

Closes #6645. Alternative to heavier #6647
- Get rid of `asyncio` import by defining few noops methods from asyncio.protocols.SubprocessProtocol
directly in `WitlessProtocol`.

RF: get rid of asyncio import by defining few noops from SubprocessProtocol

---

datalad/support/gitrepo.py
datalad/support/tests/test_gitrepo.py

Specifically, conflicts of branch name with branch content.
- `GitRepo.get_branch_commits_()` crashed when the given branch name also matched a file or directory in the active branch. Fixes #6650

Fix `GitRepo.get_branch_commits_()` to handle branch names conflicts with paths

---

datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py

When used with `what=(allkeys/datasets/all)` and `reckless != kill`, `drop` created a result record in which a list of error messages coming from git-annex was placed in the field named `error_messages`. This led to the generic results renderer (which expects `error_message` and/or `message` instead) not showing the error message to the user, as described in #6577.
This PR rewrites the error messages into a string under `res['error_message']` (if there are multiple messages, they are joined into one multiline string, following `annexjson2result` from `datalad.interface.results`). With that, results renderer behaves as expected.
Before (I'm mocking both note and error-messages produced by git-annex, although in the original issue the note was empty):
```
❱ datalad drop --what all -d bar …
```

Change a key-value pair in drop result record

---

datalad/distributed/ora_remote.py
datalad/support/annex_utils.py
datalad/support/annexrepo.py
datalad/support/tests/test_fileinfo.py

In #6630 I noticed wrong reporting of ``datalad status --annex all`` for https://github.com/datalad-datasets/machinelearning-books - even though all content was retrieved, only a fraction of it was reported as being locally available by DataLad. git-annex' own reports were fine, and matched file system reports.
```
adina@muninn in /tmp/machinelearning-books on git:master
❱ git annex info
trusted repositories: 0
semitrusted repositories: 8
00000000-0000-0000-0000-000000000001 -- web
00000000-0000-0000-0000-000000000002 -- bittorrent
51d4ba52-edfc-4505-bd36-21233a06f8cb -- yoh@lena:~/proj/datalad/datasets/machinelearning-books
7f1346f6-a5dd-485d-96dc-563d0a221a95 -- yoh@hopa:/tmp/mlbooks
c6bcd625-0a68-49bb-acd5-51c28e2e3073 -- yoh@hopa:~/proj/datalad/repos/mlbooks …
```

BF: Sanitize keys before checking content availability

---

.autorc
CHANGELOG.md
datalad/conftest.py
datalad/core/distributed/clone.py
datalad/core/distributed/push.py
datalad/core/local/create.py
datalad/core/local/status.py
datalad/customremotes/base.py
datalad/dataset/gitrepo.py
datalad/distributed/create_sibling_ghlike.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py
datalad/dochelpers.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py
datalad/support/tests/test_gitrepo.py
datalad/tests/test_utils.py
datalad/tests/utils.py
datalad/utils.py
docs/source/changelog.rst
docs/source/index.rst
setup.py

Just for CI, will merge locally and push

Merge maint into master, DO NOT MERGE PR

---

datalad/support/annexrepo.py

This function contains more warnings which parts of the promised API do not actually work, than actual code.
- `AnnexRepo.add_urls()` is deprecated in favor of `AnnexRepo.add_url_to_file()` or a direct call to `AnnexRepo.call_annex()`. Fixes #5153

Deprecate AnnexRepo.add_urls()

---

datalad/distributed/ora_remote.py
datalad/support/annex_utils.py
datalad/support/annexrepo.py
datalad/support/tests/test_fileinfo.py

Sanitize keys before checking content availability to ensure correct value for keys with URL or custom backend

---

datalad/local/addurls.py

- explains downstream consequences of using `--fast` option in `addurls`. closes #6680

[DOC] make --fast scarier to use

---

datalad/local/wtf.py
datalad/ui/utils.py

This PR teaches ``datalad wtf`` to report the file systems of ``TMP``, ``CWD``, and ``HOME`` as suggested in  #6294 using ``psutil``. On my Debian system, the output looks like this
```
(handbook) adina@muninn in ~/Documents
❱ datalad wtf -S system
- distribution: debian/11-updates/n/a
- encoding: 
- default: utf-8
- filesystem: utf-8
- locale.prefered: UTF-8
- filesystem: 
- /home/adina/Documents: ext4
- /tmp: ext4
- /home/adina: ext4
- max_path_length: 277
- name: Linux
- release: 5.16.0-3-amd64
- type: posix
- version: #1 SMP PREEMPT Debian 5.16.11-1 (2022-02-25)
```
On my Windows machine it looks like this:
```
C:\Users\adina\repos\datalad>datalad wtf -S system
- distribution:   10/10.0.19044/SP0/Multiprocessor Free
- encoding:
- default: utf-8
- filesystem: utf-8
- locale.prefered: …
```

NF: Teach WTF to report the filesystem of CWD, TMP, and HOME

---

datalad/support/gitrepo.py

I have to admit that I do not know how duecredit works, but I found a ``due.dcite``-marked citation in the code base pointing to Zenodo instead of the actual publication, so I changed the DOI accordingly.
Wouldn't need a Changelog

Replace Zenodo DOI with JOSS for due credit

---

.travis.yml
setup.py

On debian stable bullseye and ubuntu 22.04 we have 1.8.1 and test_completion fails.
I will add corresponding version depend also for debian/control in debian branch.

BF: require argcomplete version at least 1.12.3 to test/operate correctly

---

tox.ini

In order to provide useful information when a test fails, pytest rewrites `assert` statements in test code so that failures will show the values involved.  However, this only applies to code in test files, which, by default, are files with names of the form `test_*.py` or `*_test.py`.  This PR adds `utils_pytest.py` to the set of files considered test files so that the assertions in the assertion helpers within will be rewritten; without this change, a failing, say, `assert_equal(x, y)` will just show "`AssertionError`" but not `x` or `y`.
Note that this only affects tests run on datalad itself; other projects that use assertion helpers in `utils_pytest.py` will not benefit from assertion rewriting (unless we instead rename `utils_pytest.py`).

Ensure that assertion helpers in `utils_pytest.py` get rewritten by pytest

---

datalad/distributed/create_sibling_gitlab.py
datalad/distributed/tests/test_create_sibling_gitlab.py

When create-sibling-gitlab receives a path to a non-existing or non-dataset location, it does not provide any feedback to the user about this (#6700). This PR makes ``create-sibling-gitlab`` yield an impossible result whenever a provided path does not point to a subdataset:
```
$ datalad create-sibling-gitlab --site https://jugit.fz-juelich.de thisismyproject                    1 !
create_sibling_gitlab(impossible): thisismyproject (dataset) [No dataset found under /tmp/some/thisismyproject]
```
- When ``create-sibling-gitlab`` is called on non-existing subdatasets or paths it now returns an impossible result instead of no feedback at all

ENH: Better feedback when create-sibling-gitlab is called with non-existing path

---

datalad/local/unlock.py

An unlocking operation can take a considerable amount of
time, but doesn't provide feedback at all (see #6691).
By switching from _call_annex_records(), which processes
the full bunch of files at once, to _call_annex_records_items(),
which yields as soon as results are available, we can
construct a progress bar with a file counter around the
unlock operation.
The progress reporting is slightly complicated by the
fact that git annex' --json records for each file are
output before a final 'recording state in git' operations,
which can, if a large number of files was unlocked, add
considerably to the execution time of the command after
all files have been unlocked already and the progress bar
would be at 100%. Thus, this change adds an additional
progress update when all files are processed …

ENH: Enable progress bars for unlock, fixes #6691

---

datalad/utils.py

There are no uses of this function in core (as the comment indicated) or in any of the extensions (as determined by a quick git grep - but tests will tell if I have missed anything).
Removing it to not drag it further along with us.
closes #6432

MNT: Remove unused helper for listing sorted files

---

datalad/local/tests/test_wtf.py
datalad/local/wtf.py

When unavailble WTF sections are requested, e.g., '-S dataset'
outside of any dataset, the command errors with a KeyError
(#6711). This change catches this and reports an impossible
result for the affected section, such that the problem is
communicated orderly, and that the reporting of other sections
is not impacted
PS: Is `maint` the correct target for this?
- ``wtf`` now reports on unavailable info sections with an 'impossible' result record instead of failing with a KeyError. Fixes #6711

BF: Catch KeyErrors from unavailable WTF infos

---

datalad/support/tests/test_annexrepo.py

Needed to overcome recent git safeguard.  Test code comments provide
more information.  Closes #6708 since I do not think we should do more
for this issue -- it would be up for a user indeed to add any given
directory owned by someone else into git config
I think it should be safe just to set it without store/restore handling
since our HOME is fake and set in the session wide fixture.

BF(TST): RO operations - add test directory into git safe.directory

---

datalad/support/external_versions.py
datalad/support/tests/test_external_versions.py

Closes #6728 in the first commit fixing the parsing of a more elaborate version "identifier".
Then two subsequent commits pretty much provide two alternative ways to present 2nd version of `ssh` -- the one we actually use, which might be not the "system" one, i.e. not the one "first" in the PATH but the one we configure to use since https://github.com/datalad/datalad/pull/6553 which is on Windows is the "system" one, i.e. installed system wide and not in conda. (but not necessarily reported as `cmd:system-ssh`).
So here is how it looks for me on windows ATM:
```
(datalad) C:\Users\DataLad\PycharmProjects\datalad>datalad wtf -S dependencies
- annexremote: 1.2.1
- boto: 2.49.0
- cmd:7z: 9.20
- cmd:annex: 8.20201008-g3be4731
- cmd:bundled-git: UNKNOWN
- cmd:git: 2.34.1.windows.1
- cmd:ssh: …
```

In addition to default (system) ssh version, report configured ssh; fix ssh version parsing on Windows

---

datalad/local/unlock.py

Logs start, end, and "recording state in git' phase at INFO level,
but the messages for each and every file only at DEBUG.
This will make default logging more sensible volume-wise.
No needed.

More selective `unlock` progress reporting in noninteractive cases

---

datalad/log.py

- Remove unused and untested log helpers `NoProgressLog` and `OnlyProgressLog`. Fixes #6732

Remove unused and untested log filter helpers

---

datalad/local/add_archive_content.py

Following @mih's wisdoms from  #6734 and mirroring the approach in  #6735, this change improves the progress bars of `add-archive-content`. This includes:
- The `pbar_id` is unique for any archive (it was hard coded before)
- A dedicated setup and take-down progress bar at INFO level for noninteractive sessions
- An automatically incrementing progress bar at DEBUG level for noninteractive sessions
This mostly fixes inconveniences in the handbook build for me (endless progress bars in handbook output)
A changelog entry is not needed.

ENH: Improve add-archive-contents progressbar following #6735 & #6734

---

datalad/core/distributed/push.py
datalad/core/local/diff.py
datalad/distribution/create_sibling.py
datalad/local/copy_file.py
datalad/support/gitrepo.py

This is a maintenance change to fix #6652. It removes all remaining uses of the deprecated and unused ``eval_file_type()`` parameter, and the parameter itself. As far as I was able to grep around, only ``datalad-ukbiobank`` needs an adjustment for this change, but let's see if any unit tests break.

MNT: Remove ``eval_file_type()`` from code base

---

docs/source/design/index.rst
docs/source/design/progress_reporting.rst

- New design document on progress reporting.

Design document on progress reporting

---

datalad/local/export_archive.py
datalad/support/gitrepo.py

This change contains maintenance work on export-archive. This includes
a complete switch from os.path to Pathlib, as well as abandoning old
almost never used and @normalize_path-polluted repo methods
get_indexed_files() and is_under_annex(), and replacing them with
get_content_{annex,}info(). This allows us to simplify the logic in
the for loop over all files further.
Coincidentally, because the switch from normlize_path functions
to get_content_{annex,}info() prevents faulty path handling when
export-archive is called from subdirectories inside of datasets,
this change fixes #6741
- `export-archive` doesn't rely on `normalize_path()` methods anymore and became more robust when called from subdirectories (fixes #6741)

MNT: Modernize export-archive

---

datalad/support/gitrepo.py

Fixes #6749. Ref: original fix in #5010  which was incomplete
- I am not 100% confident and did not carry full archeological expedition on
how it could have worked ever since due to that --dry-run it was "always"
there
- 2nd call to that push comes with refspec since it is that initial --dry-run
which provides them. And that is when we should separate them out
- Unfortunately since there is no dedicated dry_run option to push,
I had to rely on matching it in git-options
- We stopped using VCR for playing out the integration tests with github,
and mocking out interactions would provide no point since we want to ensure
correct operation against github.  So I do not see an easy way to
develop a unittest, so I will leave it at this

BF: push to github - remove datalad-push-default-first config only in non-dry run to ensure we push default branch separately in next step

---

datalad/distributed/create_sibling_ria.py
datalad/distribution/utils.py

``create-sibling-ria`` has in-line code to check for datasets with matching sibling names that ``datalad-next`` refactored into a helper function for ``create_sibling_webdav`` (https://github.com/datalad/datalad-next/issues/17, https://github.com/datalad/datalad/issues/6644).
This PR adds the helper function created in ``datalad-next`` to datalad core. I went with ``datalad/distribution/utils.py`` as a location, but there might be better places for it - please chime in.
The helper is then used in ``create-sibling-ria`` instead of the previous in-line code to make the code more modular. A companion PR in datalad-next may import the helper from datalad core.
Fixes https://github.com/datalad/datalad/issues/6644
- in-line code of create-sibling-ria has been refactored to an internal helper to …

MNT: Factor out helper function used in core and next from ria functionality

---

datalad/interface/common_cfg.py
datalad/log.py
datalad/tests/test_log.py

- Documentation and behavior of traceback reporting for log messages via `DATALAD_LOG_TRACEBACK` was improved to yield a more compact report. The documentation for this feature has been clarified. Closes #6744 
- API documentation for log helpers, like `log_progress()` is now included in the renderer documentation. Fixes #6731

Polish trace back-logging and other logging aspects

---

datalad/runner/nonasyncrunner.py
datalad/runner/tests/test_threadsafety.py

This PR addresses issue #6595 
Fixes #6595 
The commits in this PR add a re-entry detection for the methode `ThreadedRunner.run()`, which is not re-entrant. It should also not be called if the protocol that was used is a subclass of `GeneratorMixIn` and the generator returned by `ThreadedRunner.run()` has not yet raised `StopIteration`.
Both cases are detected and handled by this PR. In the non-generator case, the invocations will be serialized. That means the second caller will only be allowed to enter the method if the current caller has left it. In the generator-case, a `RuntimeError` is raised. This might lead to different, new errors, but will provide deterministic detection of the re-entrance issue, that is, of issue #6595
- Prevent reentry of a runner instance. Fixes #6595

Prevent reentry of a runner instance

---

_datalad_build_support/setup.py

There are several folders in `datalad/` that contain data files but no Python source code, and we want these to be included when datalad is installed.  Currently, these folders are automatically included by the combination of `graft datalad` in `MANIFEST.in` and `include_package_data=True` in `setup.py`, but because we set `packages` in `setup()` to `find_packages()` instead of `find_namespace_packages()`, the folders themselves are not recognized by setuptools as packages.  [This combination of settings is deprecated](https://github.com/pypa/setuptools/issues/3340), and the setuptools developers recommend using `find_namespace_packages()` instead of `find_packages()` for such situations.

Properly include "data packages" in project

---

datalad/ui/progressbars.py

Spotted while comparing behavior of log_progress whenever it does
not log progress at all it logs initiation of specific actions while
we were reporting only at the end of the operation.  This way we would be reporting
also the beginning:
$> rm -rf datalad && DATALAD_UI_PROGRESSBAR=log datalad clone https://github.com/datalad/datalad.git
[INFO   ] Start Clone attempt
[INFO   ] Start Enumerating
[INFO   ]  Enumerating done in 0.000520706 sec
[INFO   ] Start Counting
[INFO   ]  Counting 174 Objects done in 0.0136135 sec at 12781 Objects/sec
[INFO   ] Start Compressing
[INFO   ]  Compressing 93 Objects done in 0.033551 sec at 2772 Objects/sec
[INFO   ] Start Receiving
[INFO   ]  Receiving 96987 Objects done in 6 seconds at 14219 Objects/sec
[INFO   ] Start Resolving
[INFO   ]  Resolving …

ENH: LogProgressBar to gain "start" reporting

---

datalad/downloaders/credentials.py

This way user can still continue and achieve the goal without the entire
datalad process crashing and have no clear way forward.  User would just
need to keep entering credential every time I guess.
Ref (not really a fix IMHO): #6759

BF(workaround to #6759): if saving credential failed, just log error and continue

---

datalad/metadata/search.py

This PR Fixes #6763 
This commit disables the result renderer in a recursive call to `Dataset.search()`. This recursive call is used when no dataset to search through is found and the default super-dataset, i.e. `///` is used.
When the result renderer in the recursive call was not disabled, each result was reported twice.
- prevent duplicated result rendering when searching on default datasets. Fixes #6763

Prevent duplicated result rendering when searching in default datasets

---

datalad/dataset/gitrepo.py
datalad/tests/test_config.py

A failure in ``datalad-ukbiobank`` (datalad/datalad-ukbiobank#82 and a misguided fix in datalad/datalad-ukbiobank#85 has revealed that a change introduced in https://github.com/datalad/datalad/pull/6278 caused final trailing newlines to be removed from the final stdout of our ``call_git`` calls. In datalad-ukb, unit tests started to fail as the contents of files that were written with `git cat-file -p <sourcebranch>:<sourcefile>` lacked the trailing newlines that the source files had.
I'm poking in the dark and PRing a WIP PR in hopes of improvements and feedback to fix this by switching back to ``_call_git()`` from ``call_git_items()``. The PR also contains half of a docstring fix @yarikoptic idenitified - input on the description of the `env` parameter (see commit) would be appreciated.

Preserve final trailing slash in ``call_git()`` output

---

setup.py

Fixes #6776 
This PR limits the allowed `chardet` version to <5.0.0, because `requests` does only support `chardet` up to version 4, and version 5.0.0. was released on pypi on 25th of June 2022
- limit chardet version to version 4 in order to fulfill `requests`-dependencies

Fix test errors caused by updated chardet v5 release

---

datalad/support/tests/test_network.py

Fixes #6163 
This PR activates the file-URL tests on windows-platforms
- run file-URL tests on windows platforms

Do not skip file-URL tests on windows

---

datalad/dataset/gitrepo.py
datalad/dataset/tests/test_gitrepo.py
datalad/runner/tests/test_utils.py
datalad/runner/utils.py
setup.py

Fixes #6766 
This PR cleans up the line end handling in GitRepo.call_git_items_() and related functions. It fixes a core issue that was discovered by @adswa and addressed in PR #6754. In addition to #6754 this PR will clean up line-end handling for more methods than `GitRepo.call_git()`. 
Once PR #6754 is merged, this PR should be rebased and merged as well.
In more detail. this PR equips LineSplitter with the capability to retain line endings in the returned lines. That allows for a precise reconstruction of the complete data by joining the lines returned from LineSplitter. 
- item based output reading is now able to recreate the complete output bit-identical

Clean up line end handling in GitRepo

---

.github/workflows/test_extensions.yml

Closes #6780.
- Upload coverage from extension tests to Codecov

Upload coverage from extension tests to Codecov

---

.github/workflows/test_extensions.yml
CHANGELOG.md
datalad/dataset/gitrepo.py
datalad/dataset/tests/test_gitrepo.py
datalad/downloaders/credentials.py
datalad/metadata/search.py
datalad/runner/nonasyncrunner.py
datalad/runner/tests/test_threadsafety.py
datalad/runner/tests/test_utils.py
datalad/runner/utils.py
datalad/support/tests/test_network.py
datalad/tests/test_config.py
docs/source/changelog.rst
setup.py

Merge commit '0.16.6-17-g9e147092b' into merge-maint
* commit '0.16.6-17-g9e147092b': (27 commits)
Upload coverage from extension tests
limit chardet version to <5.0.0
limit chardet version to <5.0.0
implement call_git with call_git_items_
refactor runner.utils tests
keep line endings intact as long as possible
add a test for call_git_items_ results
do not skip file-URL tests on windows
adapt tests to modified GitRepo.call_git-semantic
Update RST changelog
Update CHANGELOG.md
BF(workaround): skip test_ria_postclonecfg on OSX for now
prevent result rendering in recursive search-call
DOC: Finalize adjustment of the docstring for _call_git to be factually correct
refactor thread safety tests
refactor thread-safety tests
remove unnecessary assignment
fix exception recording
remove debug …

Merge commit '0.16.6-17-g9e147092b' into merge-maint

---

datalad/support/annexrepo.py
datalad/support/gitrepo.py

By moving the `Repo.precommit()` call into the actual
implementation in `GitRepo`. No change in API or functionality.
This scores a point in datalad/datalad#4595
- Consolidate `GitRepo.remove()` and `AnnexRepo.remove()` into a single implementation.

Remove superfluous `AnnexRepo.remove()` implementation

---

datalad/core/local/save.py
datalad/core/local/tests/test_save.py
datalad/support/gitrepo.py

Previously, the test for adding a gitmodules record was incomplete
and relied on the assumption that for a new subdataset the type
`dataset` was not determined by the initial `status()` inspection.
However, this is not the case, when an explicit subdataset path
with a trailing path-separator is given to `save()`.
This change amends the test condition to also test for the state
being `untracked`. In principle this alone should be a sufficient
condition. However, due to the complexity of the decision making
in the present implementation, the previous condition as also
kept as an alternative, in order to prevent unexpected side-effect.
Fixes datalad/datalad#6547
- Ensure saving a new subdataset to a superdataset yields a valid `.gitmodules` record regardless of whether and how a path …

Make sure a subdataset is saved with a complete .gitmodules record

---

datalad/core/local/tests/test_save.py
datalad/support/gitrepo.py

This change is picking up on the discussion in datalad/datalad#4967
and the stale PR datalad/datalad#5016.
Previously, annex'ed files moved with `git-mv` were repaired by
git-annex only after `datalad save` performed change detection. This
led to `save()` leaving the dataset in a non-clean state, and require
a second `save()` call.
This change prevents this outcome by specifically calling `git annex
pre-commit` on any already staged symlinks, before processing by
`save()`.
Fixes datalad/datalad#4967
- `save` now repairs annex symlinks broken by a `git-mv` operation prior recording a new dataset state. Fixes #4967

Fix broken annex symlink after git-mv before saving

---

datalad/support/tests/test_sshconnector.py

Fixes issue #6798 
This PR modifies the test `datalad.support.tests.test_sshconnector::test_ssh_copy` so that it does not longer populate a source directory by copying existing files onto themselves, thereby remove a race condition that left a source file empty.
- remove a race condition in ssh copy test

Fix a race condition in ssh copy test

---

.travis.yml
datalad/metadata/metadata.py
datalad/metadata/search.py
datalad/metadata/tests/test_search.py
setup.py

This PR extends search to use next generation metadata, if a next generation metalad extension is found.
This PR is marked as work in progress and exists to support experiments with the new metadata system. One shortcoming of this patch is that legacy and NG-metadata results are both used and not de-duplicated. Also, the mapping of NG-metadata on the expected result structure, i.e. the legacy metadata-results, is probably sub-optimal.
- use next generation metadata code in search, if it is availble

Support next generation metadata in search

---

datalad/local/tests/test_add_archive_content.py

The issue was addressed yesterday, so future version should exceed the mentioned one
I believe this workaround should bring `maint` into green state on Linux/OSX.

BF(TST): skip failing test on buggy (current) git-annex release

---

datalad/runner/tests/test_threadsafety.py
datalad/tests/utils_pytest.py

This PR addresses the test failures seen in the conda-forge feedstock:
* A remaining import of nose-based `datalad.test.utils` is updated so that nose is no longer needed during tests.
* Calling `skip_if_no_module()` and `skip_if_no_network()` at module level (as is done in `datalad/downloaders/tests/test_s3.py`) is now allowed.
I suggest releasing this in 0.17.1 soon so that a passing release can be made on conda-forge.
- Fix failing tests on conda-forge

Avoid import of nose-based tests.utils, make  skip_if_no_module() and skip_if_no_network() allowed at module level

---

datalad/tests/test_misc.py

This test was always skipped since conditioned on having numpy installed
and we no longer keep it as a dependency of any kind so on all CIs it was
skipped.  But I ran into it while testing for debian build where for
some reason numpy was installed
Actually detected while looking at fails for conda: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=533304&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

RM(TST): remove testing of datalad.test which was removed from 0.17.0

---

tox.ini

Needs to be gone for 3.12: https://github.com/datalad/datalad/issues/6307

Suppress DeprecationWarning to allow for distutils to be used

---

datalad/support/external_versions.py
datalad/support/sshconnector.py
datalad/support/tests/test_sshconnector.py
datalad/tests/utils_pytest.py

This is the work by @christian-monch in #6812 with 2 little final tune ups to get it working and robustify against case where version is None for some reason (avoid quoting). And also submitted against `maint`.
I would appreciate quite review/merge since that test kept failing all our CI runs, bringing fatigue.

Do not quote paths for ssh >= 9

---

.travis.yml
datalad/support/external_versions.py
datalad/support/sshconnector.py
datalad/support/tests/test_sshconnector.py
datalad/tests/utils_pytest.py

Yet another replacement now of #6803 and sits on top of #6826 -- I am aiming for a clean CI without needing to lookup what failed.  #6826 should be merged first

BF: use --python-match minor option in new datalad-installer release to match outside version of Python

---

datalad/conftest.py

Fixes #6835.
- Support older versions of pytest

Support older pytests

---

datalad/core/local/create.py

A comment in code review accidentally changed the return type of
an internal ``run_procdure --discover`` call within ``create`` from ``list``
to ``generator``: https://github.com/datalad/datalad/pull/6457#discussion_r809040262
When several procedures were given to ``create`` at once (described in
#6840), the loop over the generator was repeated for each procedure,
and due to chance, procedure discovery sometimes failed when the
generator was depleted at the second for loop iteration.
This change reverts this and changes the return type back to 'list'.
Fixes #6840.
- Create's internal procedure discovery sometimes failed to find available procedures when several were executes at once. An internal return type change fixed this again.  Fixes #6840

BF: Make create's check for procedures work with several again

---

datalad/runner/tests/test_witless_runner.py

This should close (unresolved) but not fix https://github.com/datalad/datalad/issues/4921
which seems to happen so far rarely on conda on 3.8 python only. If some brave soul
manages to figure it out -- great. But I would not break our knuckles to see it fixed
since seems to be very particular.  I made xfail also very particular (not over entire
test, only for 3.8 and only for the 55 output) so we do not miss any other problem

XFAIL test_runner_parametrized_protocol on python3.8 when getting duplicate output

---

.travis.yml
datalad/local/tests/test_add_archive_content.py

prompted by https://github.com/datalad/datalad/pull/6841#issuecomment-1185529529 . Still don't know why it got `0+unknown` version, let's see if repeats here

Addressing problem testing against python 3.10 on Travis (skip more annex versions)

---

datalad/support/gitrepo.py
datalad/support/tests/test_repo_save.py

This changeset brings a tests for verifying that `save()` can handle the
following type changes in a dataset:
- replace a file with a directory (that has content)
- replace a file with a (sub)dataset
- replace a directory with a (sub)dataset
- replace a subdataset with a file
`GitRepo.save_()` was fixed to detect and handle replacing a file
with a (sub)dataset.
At the moment the (rather complex case of) replacing a directory that
contains a registered subdataset with a new subdataset requires two
calls to `save()`, instead of being able bring the dataset to a clean
state in one go. This first call automatically unregisters the vanished
subdataset, and the second call registers the new one.
Fixes datalad/datalad#5418
- `save` can now handle various type changes in a dataset, such as a file …

Improved support for saving typechanges

---

datalad/local/remove.py
datalad/support/gitrepo.py
datalad/support/tests/test_repo_save.py
datalad/tests/utils_pytest.py

The previous implementation in `GitRepo._save()` used `git-rm` to
handle the staging of removed files. However, this porcelain command
also handles the actual removal of files from the working tree.
This is unnecessary here, because only items are processed that
have already found to be removed from the working tree. Therefore,
the more lightweight `update-index` is used now, and provides measurable
speed-ups. I found between 5-10% faster `datalad-save` runtimes when
removing 2k file entries from a dataset on a lightning-fast NVME drive.
Because `GitRepo` methods using the `normalize_paths` decorator are
avoided now, the speed-up should be even more substantial on slower
file systems.
This change also improves the reporting of `datalad-save` when saving
the removal of a subdataset. …

Speed up saving of removals and improve their reporting

---

datalad/cli/common_args.py
datalad/cli/helpers.py
datalad/cli/tests/test_main.py

As documented in https://github.com/datalad/datalad/issues/5653#issuecomment-1190069481 this API was lacking a method to unset configuration items, while
all other API do support this feature. This changeset adds it.
Closes #6863
This PR is targeting `maint`. IMHO this is not a new feature, but rather a missing piece in the implementation of an existing feature. It is strictly backward compatible.

Support unsetting config via `datalad -c :<name>`

---

datalad/api.py

Previously DataLad could crash if an extension entrypoint was
importable, but a declared command suit item would not.
This change now skips each individual command interface with an
error message like this:
```
% python -c 'import datalad.api as dl'
[ERROR  ] Internal error, cannot import interface 'datalad_dataverse.create_sibling_dataverse': ModuleNotFoundError(No module named 'datalad_next')
[ERROR  ] Skipping unusable command interface 'datalad_dataverse.create_sibling_dataverse.CreateSiblingDataverse' from extension 'dataverse'
```
(I have an extension installed, where one command depends on an
unavailable package).
Closes datalad/datalad#6874

Protect again failing to load a command interface from an extension

---

datalad/distribution/get.py

The confusion arises from a message that announces the installation
of a (sub)dataset, even when the dataset is already present.
This change rewords the message to be more valid in this case.
Fixes datalad/datalad#6862

Clarify confusing INFO log message from get() on dataset installation

---

datalad/distribution/create_sibling.py
datalad/support/external_versions.py
setup.py

Fixes #6307
Followed the convention of stdlib -> dependency -> currentpackage imports, but since there weren't dependency imports in these two files, I'm not positive that you follow this convention. LMK if I should change anything.
- Use `looseversion.LooseVersion` as drop-in replacement for `distutils.version.LooseVersion`

RF: Replace distutils LooseVersion with looseversion

---

docs/source/conf.py

See https://github.com/sphinx-doc/sphinx/issues/10701 for more information.
I have not checked if rendered docs are anyhow affected etc. I hope the issue
would get fixed asap since should affect lots of sphinx users
Fixes #6882

BF(DOC): workaround for #10701 of sphinx in 5.1.0

---

datalad/cmd.py
datalad/runner/runnerthreads.py

f-strings should not be used for logger since if any of the .format-ed
content contains some %, it would then be incorrectly or causing a crash
%-polated by the logger.  Although some of the "fixed" cases would be ok
(we know that it was an int etc) for consistency and to avoid needed
"is this particular use safe?" checks, better to avoid f-strings in
logger in general

BF: RF f-string uses in logger to %-interpolations

---

.travis.yml

10 is the most recent supported git annex repo version.  It should bring improvement
in some operation performance (see e.g.
https://github.com/dandi/dandisets/issues/229#issuecomment-1192971292 ). But it is not the
default version git annex would use (it uses 8), so AFAIK there is no "real life" testing
for operation of v10 annex repos.  Also we did not do full sweep of testing against python
3.10, so I made second matrix run for it, to which I also added testing against v10.  This
way we do not do full combinatorics of python version/git-annex/git-annex repo version but
at least gain 1 environment with 2 matrix runs for full tests sweep in a "most modern
environment" setting

ENH(TST): test against supported git annex repo version 10 + make it a full sweep over tests

---

datalad/support/tests/test_annexrepo.py

Originally this test was crafted when 6 was still among supported versions.
We have gone past that point now, minimal supported version of git-annex
(from 202003) supports only 8, and current ones default to 8 but support also
9 and 10.  I have RF and extended test to to remain valid "forever" and test
that we can init git-annex of any supported version

RF,ENH(TST): future proof testing of git annex version upgrade + test annex init on all supported versions

---

.github/workflows/typing.yml
tox.ini

Initiates work toward addressing https://github.com/datalad/datalad/issues/6884

ENH: introduce typing checking and GitHub workflow

---

datalad/core/distributed/push.py
datalad/core/distributed/tests/test_push.py

The documentation for declaring publication dependencies allows for two different ways to declare multiple dependencies:
1. Declaring a single config item with a list of dependencies (space-separated)
2. Declaring a config item multiple times with a single dependency each.
Previously `push()` only supported (1), while `siblings()` produced (2).
This change lets `push()` handle both scenarios.
Fixes #6867
Thanks to @LoannPeurey for the report!

Let push honor multiple publication dependencies declared via siblings 

---

.github/workflows/test_extensions.yml

This PR modifies the test_extensions-workflow to use `pytest` if the tested extension is `datalad-metalad`. The extension `datalad-metalad` recently switched from `nose` to `pytest` because `nose` does not work with python 3.10.
This should fix errors in `test (datalad-metalad)
- switch test runner for `datalad-metalad` extension from `nose` to `pytest`.

Use pytest to test datalad-metalad in test_extensions-workflow

---

datalad/runner/exception.py
datalad/runner/nonasyncrunner.py
datalad/runner/protocol.py
datalad/runner/runner.py
datalad/runner/runnerthreads.py
datalad/runner/tests/test_exception.py
datalad/runner/tests/test_nonasyncrunner.py
datalad/runner/tests/test_threadsafety.py
datalad/runner/tests/test_utils.py
datalad/runner/utils.py
setup.py
tox.ini

This PR fixes #6889 
The runner-code passes validation tests of `mypy` version `0.971`, i.e. with strict optional checking.
- fix type annotations in `datalad.runner` this resolves issue #6889

Fix runner type annotations

---

datalad/support/network.py
datalad/support/tests/test_network.py

It is #6890 by @adswa with my addition to the solution -- log at DEBUG only while guessing. See the last commit
Our own obscure paths generate filepaths that RFC 1808 on URLs
schemes mistakes to have URL parameter specifications because
they contain a semicolon (see  #6872).
Internally, when urlparse detects parameters in a URL, we warn
that those parameters will not be honored or considered at all.
In general, I find this is a nice thing to do, but annoying when
its actually not a URL with parameters. My initial thought on
how to keep the information but make it less annoying is to
demote the log level of the message from warning to debug.
Alternatively, we could do more parsing and guessing on whether
or not something a URL where parameters make sense, but that
could probably easily …

DX: Demote loglevel of message on url parameters to DEBUG while guessing RI

---

datalad/core/distributed/clone.py

came up while chatting with @AKsoo about https://github.com/datalad/datalad/issues/4598 .
That use of "op" (what does it stand for) was a "false positive" in trying to find
all uses of os.path

RF: just rename internal variable from unclear "op" to "io"

---

.travis.yml

I found those reports spit out at the end of the pytest very annoying to avoid
while searching for failed tests.  And they aren't really useful since we
- at large anyways relying on codecov reporting while combining across
different CIs and runs
- have `report` at the end upon success when submitting to codecov. So we
can look at those if desired, and they are nicly folded in their own step
If desired -- can do for other runs (appveyor etc).

ENH(TST): Disable coverage reporting on travis while running pytest

---

datalad/support/tests/test_network.py

Since paths are actually containg \ not / like on POSIX/in urls.
Prehistory:
In #6891 I have missed the fact that windows on appveyor was not happy! (on the importance of having CI green!!!!):
https://ci.appveyor.com/project/mih/datalad/builds/44287617/job/fgp764p65r1ba5oj
____________________________ test_pathri_guessing _____________________________
filename = 'C:\\DLTMP\\datalad_temp_pwl4puuu'
@with_tempfile
def test_pathri_guessing(filename=None):
with swallow_logs(new_level=logging.DEBUG) as cml:
ri = RI(f"{filename};param")
assert isinstance(ri, PathRI)
>           assert_in('ParseResults contains params', cml.out)
..\datalad\support\tests\test_network.py:229:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
first = 'ParseResults contains params', …

BF(TST): do not expect log message for guessing Path to be possibly a URL on windows

---

datalad/tests/test_archives.py

A workaround for https://github.com/datalad/datalad/issues/4101
with troubleshooting and trying various approaches done within
https://github.com/datalad/datalad/pull/6751
An ideal approach would be to check if create_tree does create a tree (and
archives with files it expect) matching the specification of the tree. Somehow
on NFS it seems to need some times a few seconds (sleep 3 before creating
archive helped according to testing in #6751) before filesystem actually reflect
creation of all files desired.
I found no robust solution which would not require "too much work" so decided
to just announce this an xfail.
For better or for worse, the loop of 100 invocations had them all PASS and none
XFAIL in https://app.travis-ci.com/github/datalad/datalad/builds/253793240 so
the effectiveness …

BF(TST,workaround): just xfail failing archives test on NFS

---

.travis.yml

The last commit from https://github.com/datalad/datalad/pull/6913
We are doing   `sudo pip install`   but that then causes versioneer to run
git, and a recent git would fail with the message like
$ sudo git "rev-parse" "--git-dir"
fatal: unsafe repository ('/home/travis/build/datalad/datalad' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /home/travis/build/datalad/datalad
The command "sudo git "rev-parse" "--git-dir"" exited with 128.
so here we do what it asks us.
Fixes https://github.com/datalad/datalad/issues/6887
Closes https://github.com/datalad/datalad/pull/6913

BF: travis - mark our directory as safe to interact with as root

---

.github/workflows/test_extensions.yml

Also adjusted condition, since anything which is != something, could be anything else
to match so no need for that hirni comparison afaik

RF extensions github action to centralize configuration for extensions etc, use pytest for crawler

---

datalad/support/tests/test_annexrepo.py

Closes #6925
or we could completely dissolve this test, although I think it might have some nominal value

BF(TST): allow for a annex repo version to upgrade if running in adjusted branches

---

.github/ISSUE_TEMPLATE/issue_template.yml
CONTRIBUTING.md
datalad/core/distributed/clone.py
datalad/distributed/create_sibling_ghlike.py
datalad/distribution/install.py
datalad/interface/common_cfg.py
datalad/local/tests/test_gitcredential.py
datalad/metadata/definitions.py
datalad/metadata/extractors/datalad_core.py
docs/design.rst
docs/source/basics.rst
docs/source/design/credentials.rst
docs/source/design/file_url_handling.rst
docs/source/design/python_imports.rst
docs/source/design/threaded_runner.rst
tools/Dockerfile.fullmaster

I noticed a "Github" in a config file while helping someone with DataLad, and it caused me to twitch enough to fix it and a few other strings I found. ;-)
This is by no means comprehensive, but I did some `grep`ing around and tried to catch all I could find.
I intentionally chose to not fix occurrences in code comments and tests.
- Github -> GitHub
- openfmri -> OpenfMRI
- s3 -> S3
- travis -> Travis CI
This also fixes "Datalad" mis-capitalizations. For this, I did fix all occurrences, to make future `grep`ing easier.
- Datalad -> DataLad
- fix capitalization of some service and software names

DOC: fix capitalization of some service names

---

datalad/local/tests/test_wtf.py
datalad/local/wtf.py

Detected while looking at https://github.com/datalad/datalad/issues/6917#issuecomment-1205048868 and it was impossible to detect that there is an underlying issue in the code since no logging and swallowing of all exceptions silently.  Added logging, and some rudimentary testing (let's see if works on windows. edit: appveyor was green, so I guess it did!).

BF+ENH(TST): fix typo in code of wtf filesystems reports

---

datalad/distributed/create_sibling_ria.py
datalad/distributed/tests/test_create_sibling_ria.py

Should be a fix and testcase for #6950.
-  When ``create-sibling-ria`` was invoked with a sibling name of a pre-existing sibling, a duplicate key in the result record caused a crashed. This was fixed.

BF: Remove duplicate key in result record

---

CONTRIBUTING.md

This moves info from https://github.com/datalad/datalad/issues/6365 into the CONTRIBUTING information for better findability and established github org teams that can be tagged. Closes  https://github.com/datalad/datalad/issues/6365
[skip ci]

DOC: move maintenance team info from issue to CONTRIBUTING

---

.codespell-ignorewords
datalad/core/local/diff.py
datalad/core/local/run.py
datalad/core/local/tests/test_diff.py
datalad/core/local/tests/test_save.py
datalad/dochelpers.py
datalad/local/add_archive_content.py
datalad/local/addurls.py
datalad/metadata/search.py
datalad/metadata/tests/test_search.py
datalad/support/due_utils.py
datalad/support/exceptions.py
datalad/tests/test_dochelpers.py
datalad/tests/test_utils.py
datalad/tests/utils_testrepos.py
datalad/utils.py

Initially lead to linting failure in https://github.com/datalad/datalad/pull/6955 . Mostly concerns with comments and other strings some of which are exposed to the user

Minor tuneups to please updated codespell

---

datalad/config.py
datalad/tests/test_config.py

Previously we ignored them in values as mandatory reasons for quoting.
This change expands the `quote_config()` helper to perform this
additional test.
Fixes datalad/datalad#6943

Acknowledge git-config comment chars

---

datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py

This is a blunt, but effective measure to prevent a data security issue,
where dropping annex keys from 'here' is actually also dropping them
from 'origin' -- thereby potentially deleting the last existing copy.
Even once a more elegant error anticipation and handling is implemented,
it should be kept for safety reasons.
Closes datalad/datalad#6948
PS: I will be working on a more elegant wrapping of this fix. But given the severity, this should be merged and released ASAP. https://github.com/datalad/datalad/issues/4750 continues to remain as a reminder.
I came to the conclusion that it might be best to remove the entire feature. I filed https://github.com/datalad/datalad/issues/6961
Spellchecker errors are addressed in https://github.com/datalad/datalad/pull/6956

Forbid drop operation from symlink'ed annex (e.g. due to being cloned with --reckless=ephemeral) to prevent data-loss

---

datalad/distribution/tests/test_create_sibling.py

Our docker image for testing of interactions over ssh still has git-annex  7.20190819+git2-g908476a9b-1~ndall+1
and that is great so we can ensure that datalad works well even with older versions  (note - current minimal
supported is 8.20200309 but upgrade to that one would not matter in this case).
We use create_sibling to create remote through ssh but on the path which is also available locally.
And then instead of always interacting with that repository remotely, we had direct interactions with it
using AnnexRepo or creating a sibling not over ssh but pointing directly to that path.  That would have lead
local git-annex possibly to upgrade it to later version of git annex repo (10 ATM) whenever remote (docker)
instance of git-annex would not know that version. And with annex version …

BF(TST): prevent auto-upgrade of "remote" test sibling, do not use local path for URL

---

datalad/tests/test_utils.py

b91b494b89 simply annotated those tests which were failing on windows to be skipped without
considering to fix them. Those tests were failing because hardcoded POSIX path separator (/).
Quick solution to have tests fixed is to use _path_ helper around those POSIX paths.
The underlying tested code AFAIK should be ok - CI is yet to prove or disprove it.
Closes #2564

BF(TST): make tests use _path_ helper for Windows "friendliness" of the tests

---

.github/workflows/test_extensions.yml

the issue is https://git-annex.branchable.com/bugs/regression__58___fails_to___39__add_.__39___if_file_was_renamed/
and should be addressed in 10.20220724+git144-gc25ade4d9-1~ndall+1, which likely would not
be released for a bit more since would trigger upgrades to v9.  To make CI green again, built
curent snapshot and uploaed to -devel of neurodebian
[skip travis]
[skip appveyor]

BF(TEMP): use git-annex from neurodebian -devel to gain fix for bug detected with datalad-crawler

---

datalad/support/gitrepo.py
datalad/support/path.py
datalad/support/tests/test_path.py

Code review of this function came up while reviewing the
https://github.com/datalad/datalad/pull/6942 and where get_parent_paths,
which was pretty much "avoided" while resolving infinite recursion of
`get_submodules_ -> get_content_info -> get_submodules_`, was re-introduced
specifically within get_submodules_ .
BF: use consistently "sep" instead of / for check within the loop, and then
os.sep to check if points to up/down folders.
ENH:
- sep became an option so we could use it also with os.sep if so desired
on paths which are not POSIXed.  By default it would remain "POSIX"
(although checks were not checking for the POSIX endings before).
- The test became parametric to test for various scenarios of using \ vs /
vs "the default" (/ - POSIX).

ENH+BF: get_parent_paths - make / into sep option and consistently use "/" as path separator

---

.travis.yml
datalad/dataset/gitrepo.py
datalad/interface/common_cfg.py
datalad/runner/gitrunner.py
datalad/runner/tests/test_gitrunner.py
datalad/support/gitrepo.py

Chunking is a kludge to workaround the problem of DataLad needing to provide a
long list of files to git/git-annex commands.  Whenever git-annex has --batch mode
which we use typically for commands which could get lots of file paths arguments, we
have not used any special means like that for git commands.  Many commands support
--pathspec-file-nul and --pathspec-from-file=FILE options to pass a list of pathspec(s)
to operate on via a FILE instead of command line.
In this PR we decide to pass via such a file in cases where more than a single
chunk is necessary.
The main change is to `GitRepo.commit` which used to resort to sequence of commits with `--amend` to establish the desired commit.
Closes #6922

ENH: GitRepo -- make use of --pathspec-from-file where possible and chunking needed

---

debian/patches/bullseye-dsc-patch
debian/patches/revert_platformdirs
debian/patches/series-bullseye

The `platformdirs` dependency (since 0.16.0) is a pain in the butt to backport to the present Debian stable release. Rather backporting chains of 2nd-level dependencies, this change reverts that move, and brings back `appdirs` on this platform.
This patch setup assume the good 'old `backport-dsc` tool and can be applied with
`backport-dsc -d bullseye -s dl11 datalad_0.17.1-2.dsc`
Where `datalad_0.17.1-2.dsc` is generated with `gbp`
```
gbp buildpackage --git-builder="dpkg-source -b ." --git-postbuild=
```
or whatever floats your boat.
The recorded (and included) run-record captures how the actual patch can be regenerated for future releases of DataLad (rather than having to fiddle with the diff directly).
Otherwise this change is entirely orthogonal to the rest of the Debian packing.

Faciliate backports to Debian bullseye

---

datalad/dataset/gitrepo.py

I am not sure though if it does capture really, although I guess it should due to
StdOutErrCapture... but that is a different story I guess.  The main point is that
there is no stderr_buffer to be seen and we subclass StdOutErrCapture which
has Capture in name for both Out and Err
@christian-monch please approach this fix "critically" since I have little to no clue on how exactly all the layers of the runner work ATM so I could be entirely wrong and stderr_buffer is right there looking into my face somehow ;-)

DOCfix: fix docstring GeneratorStdOutErrCapture to say that treats both stdout and stderr identically

---

datalad/dataset/gitrepo.py

A little more discussion at https://github.com/datalad/datalad/pull/6930 and initially
identified while working on https://github.com/datalad/datalad/pull/6932 and being
unable to get CommandError.stdout for matching while using call_git (but works
with _call_git using different code path, which does not have this git_ignore_check).
One of the two locations where this function is used has stdout=None, so this
lead to wiping out of e.stdout even if it was present.  I think it was not intentional
but @christian-monch would know better

BF: git_ignore_check do not overload possible value of stdout/err if present

---

datalad/runner/tests/test_witless_runner.py
datalad/support/tests/test_annexrepo.py

Fixes issue #4921 
This PR modifies the test `datalad.support.tests.test_witless_runner.test_parameterized_protocol()`
to only send a single character to `stdout` of the subprocess, i.e. `1`. Previously two characters were
sent, i.e. `1` and `\n`. Depending on the behavior of the stdout-pipe, the data might be split up or
delivered in toto. In the first case, which is rare, the `protocol.pipe_data_received()` will be called
twice, leading to an unexpected result.
- Fix a faulty test that made wrong assumptions about pipe-behavior. Fixes #4921

Send one character (no newline) to stdout in protocol test to guarantee a single "message" and thus a single custom value

---

docs/source/design/github_actions.rst

- Describe specifications for a DataLad GitHub Action re: #6929. These may find their way to the GitHub Action README.
[ci skip]
[appveyor skip]

Describe a DataLad GitHub Action

---

datalad/cli/parser.py
datalad/cli/tests/test_main.py

Without that using a short option for a command which is also
present on top level results in early attempt error and then no
parsers even tried, thus giving that error from the main/top parser to the user
Fixes #6814
Regression was introduced in 0b4937de63c44509001cd9c64bbeb7b24176685c ( AKA 0.16.0^2~68^2~17 )
I have not investigated possible impact on completion etc, but when tried - still worked fine.

BF: if early attempt to parse resulted in error, setup subparsers

---

datalad/cli/exec.py

If I read logic right, there should be no effect from this change whatsoever. But
in such formulation we avoid unnecessary assignment (value would be reassigned) for
the cases whenever the condition below it succeeds. So I decided to make that code
logic a bit more "kosher"

RF: call_from_parser - move code into "else" to simplify reading etc

---

datalad/config.py
datalad/tests/test_config.py

It is the resurrected #6820 but now with "Windows support". More information/references in the diff itself and individual commits.
Closes https://github.com/datalad/datalad/issues/6815

Provide "/dev/null" (b:\nul on 💾 Windows) instead of empty string as a git-repo to avoid reading local repo configuration

---

datalad/support/tests/test_parallel.py

not sure if it would help but we got fresh run to fail on windows in datalad/git-annex daily builds https://github.com/datalad/git-annex/runs/8063658048?check_suite_focus=true 
and there were fails on debian before: https://github.com/datalad/datalad/issues/5402
So let"s increase and see if reemerges

TST: test_stalling -- wait x10 not just x5 time

---

.github/workflows/add-changelog-snippet.yml
tools/ci/mkchlog-snippet.py

Part of #6918.  The workflow won't affect this PR itself, but you can see it in action in a test repository at https://github.com/datalad/temp-release-devel/pull/4.
- Add a workflow for autogenerating changelog snippets
[travis skip]
[appveyor skip]

Add workflow for autogenerating changelog snippets

---

datalad/dataset/gitrepo.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py

Similar problem was resolved previously at higher level in
http://github.com/datalad/datalad/commit/ec0243c92822f36ada5e87557eb9f5f53929c9ff
for get_content_info.  But IMHO it could and should be resolved at the
lowest/common point of invocation, that is why I added it to
_generator_call_git which is underlying most (if not all, hard to tell now ;) )
git invocations.
I also fixed a few other invocations where it was pure `if files` or `if paths`.
This commit was initially proposed as a part of the #6974 but there it failed and later I realized that approach I proposed in that PR for `get_modules_` was flawed, so this PR is dedicated to only this change (although at once across different commands/levels). Want to see if we could distill it independently.

BF: make logic more consistent for files=[] argument (which is False but not None)

---

.github/workflows/docbuild.yml
_datalad_build_support/formatters.py
changelog.d/pr-6997.md
datalad/interface/common_cfg.py

I think it is worth adding to our codebase to avoid posssible conflicts in the
patch and also to facilitate similar reproducibility in other distributions
where so would be desired.
Origin: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010318

Make the manpages build reproducible via datalad.source.epoch (to be used in Debian packaging)

---

setup.py

Ref: https://github.com/jaraco/keyring/issues/593
We better release asap to not cause the chain reaction through downstreams.  May be without yet "scriv-edited" changelogs since not fully implemented so I will not bother adding one here either.

BF: blacklist 23.9.0 of keyring as introduces regression

---

datalad/cmd.py
datalad/runner/nonasyncrunner.py
datalad/runner/runner.py
tox.ini

This PR os based on the work and discussions in PR #6899 
- Add type annotations to `cmd.py` and `runner.py`

Fix type annotations in `cmd.py` and `runner.py`

---

.autorc
.github/workflows/release.yml
changelog.d/pr-7009.md
changelog.d/scriv.ini
changelog.d/templates/entry_title.md.j2
changelog.d/templates/new_fragment.md.j2
tools/ci/mkchlog-snippet.py

Use scriv for CHANGELOG generation in release workflow

---

datalad/core/distributed/clone.py
datalad/core/distributed/clone_ephemeral.py
datalad/core/distributed/clone_ria.py
datalad/core/distributed/clone_utils.py
datalad/core/distributed/tests/test_clone.py

This change is equivalent to the commuluative effort posted at https://github.com/datalad/datalad-next/pull/99. Its description is included below.
In addition to this original changeset:
- RIA-related helper are moved into `clone_ria.py` too
- internal patches `ria` and `ephemeral` are applied via functions that can be easily patched-out, in order to turn the patches off externally -- for example when an extension starts to provide a superior replacement.
The (adjusted for filenames) description of the original PR follows:
The series provides a patch to replace `clone_dataset()` the key workhorse of datalad-core's `clone` command. The patch causes no change to any functionality, but refactors the code from large monolithic functions into significantly smaller, more comprehensible units. …

Make clone_dataset() patchable and less monolithic

---

changelog.d/pr-7028.md
datalad/cli/helpers.py
datalad/cli/tests/test_main.py

Detected while considering #7027 (note: that one is against `master`, this one -- `maint`)
I believe came up as a regression of e89ce439a3b24607e4809a664a961a678063cded and since we had no unittest. So I also added a test.
Without this fix  --help looked like
options:
-c (:name|name=value)
...
*Global options*
and nothing at the end after *Global options*.

Fix datalad --help to not have *Global options* empty and list options in "options:" section

---

changelog.d/pr-7036.md
datalad/core/local/create.py

This communicates the "nature change" of the directory (from plain to dataset) to systems like inotify.
Without this, a dataset creation in an existing, empty subdirectory would go undiscovered, unless the empty subdirectory is explicitly watched itself.
With this change, that comes at virtually no additional cost, it is sufficient to watch the parent directory if the previously empty target subdirectory.

Let `create` touch the dataset root, if not saving in parent dataset

---

setup.py

#6777 is obsolete with psf/requests#6179. Could also remove the upper limit since it seems requests wants to drop the dependency eventually (https://github.com/psf/requests/issues/6177#issuecomment-1168148782).
- Update chardet version limit to allow ver 5, matching `requests` dependencies.

Update chardet version limit from 5 to 6

---

datalad/cli/tests/test_main.py

This PR fixes the test that verifies the command group names. It basically adapts the verified command group names to the changes from 8decbdc7c63d869665c5711a21aa9e837eda6f9f. This should fix a bunch of failing tests on `master` that are run on *Travis* and *Appveyor*
- Fix an error in the command group names-test

Adapt tests to modified command group names

---

datalad/cli/tests/test_main.py
datalad/support/annexrepo.py
datalad/support/json_py.py
datalad/support/tests/test_json_py.py

Fixes issue #7034 
This PR removes `simplejson` in favor of the "builtin" `json`-module. 
Remark: this changes are also contained in PR #7014 
In addition this PR fixes the test `datalad.cli.tests.test_main.test_help_np`, by adapting the group names used in the test to the group names of the command groups.
- replace `simplejson` with `json` and remove `simplejson`

Remove `simplejson` in favor of using `json`

---

changelog.d/pr-7011.md
datalad/core/distributed/push.py

I kept getting an error like
$> datalad push
publish(impossible): . (dataset) [No push target given, and none could be auto-detected, please specify via --to]
publish (impossible: 1)
and kept tuning the .git/config to specify extra options like push-remote etc,
but nothing helped.  Only when looking at -l debug I saw that the issue has
nothing to do with default target not being given but rather with permissions
issue.  IMHO "none could be auto-detected" is although technically true that
datalad FAILS to auto-detect it, is semantically wrong since it could be
autodetected but datalad can't.  That is why I decided that in cases whenever
it is a matter of permission issue, we can report that error in full.
edit: details on how such errors were triggered were added to commit …

UX: push - provide specific error with details if push failed due to permission issue

---

changelog.d/pr-7037.md
datalad/interface/results.py

A result with an exception attached has no error message, unless one is explicitly given, even when the exception is a CapturedException and could provide a message.
This change reports such an exception-provided message in the result.

Let get_status_dict() use exception message if none is passed

---

.github/workflows/release.yml

after https://github.com/datalad/datalad/pull/7024 we got release workflow erroring out with
+ python3 tools/ci/release-comment.py datalad datalad 0.17.6 changelog.d/pr-6997.md changelog.d/pr-7009.md changelog.d/pr-7011.md changelog.d/pr-7024.md changelog.d/pr-7028.md changelog.d/pr-7036.md changelog.d/pr-7037.md changelog.d/pr-7039.md changelog.d/pr-7041.md Traceback (most recent call last): File "/home/runner/work/datalad/datalad/tools/ci/release-comment.py", line 160, in <module> main() File "/home/runner/work/datalad/datalad/tools/ci/release-comment.py", line 148, in main rc.comment_on_pr(prnum) File "/home/runner/work/datalad/datalad/tools/ci/release-comment.py", line 108, in comment_on_pr self.comment_on_issueoid( File "/home/runner/work/datalad/datalad/tools/ci/release-comment.py", …

BF: use default GITHUB_TOKEN for release workflow instead of a GITMATE one

---

.github/workflows/release.yml
tools/ci/release-comment.py

We have an odd behavior in being unable to comment on issues, and looks like if GITHUB_TOKEN was set to an empty value. Here we will error out if empty and otherwise reveal the beginning of it which by itself should not be leaking too much of a secret to do any harm.
Also print about actions being performed since now it is just silently does its deeds
[ci skip]
[appveyor skip]

Give more information about used token and performed actions

---

.github/workflows/release.yml

See #7048.
The change in this PR may or may not take effect in the workflow that is run when it is merged; to be safe, this PR should *not* be labelled with "release", and a separate "release" PR should be made after it is merged in order to test it.

Trigger release workflow on `pull_request_target`

---

changelog.d/pr-7049.md
datalad/core/distributed/push.py

Otherwise we can get KeyError and underlying code can provide records without bytesize. Reported in https://neurostars.org/t/datalad-push-causes-keyerror-bytesize-keyerror/23570 with 
datalad==0.15.4
git==2.35.0
git-annex==8.20210903
<details>
<summary>first I failed to reproduce with the following script following user report with --fast</summary> 
```shell
#!/bin/bash
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
set -eu
datalad create -f .
git annex addurl --fast --file sample3.csv https://filesamples.com/samples/document/csv/sample3.csv
datalad save sample3.csv
git remote add --fetch gin git@gin.g-node.org:/yarikoptic/test-push.git
datalad -l debug push --to gin
```
</details>
<details>
<summary>but then reproduced nicely with --relaxed</summary> 
```shell
#!/bin/bash
set -eu …
```

push: Assume 0 bytes pushed if git-annex does not provide bytesize

---

changelog.d/pr-7057.md
setup.py

This reverts commit 0f27cd5045883d814b27cb7d678449a98323f768.
Original change sounded kosher and "we agreed" with reasoning but original PR https://github.com/datalad/datalad/pull/7029 for some reason did not have Travis CI runs and now after it was merged we keep getting tests failed when submitting PRs against maint with failures like
____________________________ test_run_datalad_help _____________________________
[gw0] linux -- Python 3.8.6 /tmp/dl-miniconda-jm48jjoo/bin/python
@assert_cwd_unchanged
def test_run_datalad_help():
out, err = check_run_and_get_output("datalad --help")
ok_startswith(out, "Usage: ")
lines = [l for l in err.split(os.linesep) if ('no-data-collected' not in l) and l]
>       eq_(lines, [])
../datalad/tests/test_installed.py:47:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …

Revert "Remove chardet version upper limit" to bring back upper limit <= 5.0.0 on chardet 

---

.travis.yml
CONTRIBUTING.md
datalad/conftest.py

Although could be just once in a lifetime bug, we just got into an odd issue with an unlocked file with content being marked as modified https://git-annex.branchable.com/bugs/reports_file___34__modified__34___whenever_it_is_not/#comment-4e61c4c0f493e98f9416e09de4cfb33f which seems to boil down to have a rarely used `annex.stalldetection` set.
By adding one more env variable for TESTS we can now add such specific setting to be tested in the tests.
TODOs

DATALAD_TESTS_GITCONFIG env variable to provide custom settings for git during tests

---

.github/workflows/test_extensions.yml

Our testing started to fail for container and metalad and I believe they did get pytest based testing version released recently which caused this

Make pytest to be the default tester for extensions

---

datalad/tests/test_cmd.py

attn @christian-monch .  Proper solution is to be worked out but I think for now we should just disable that test (at least I would place that patch into conda build for now)
Ref: https://github.com/datalad/datalad/issues/6834

BF: disable testing for exit code for batched process. 

---

changelog.d/pr-7073.md
datalad/dataset/repo.py

Is of no use since we operate on path_ not path down below that block. Originally introduced in b0258db13236491c6e582a16ee4fc3129f240f87 (#3191).
Should be safe since RI which is coming next can take Path just fine:
❯ python -c 'from pathlib import Path; from datalad.support.network import RI; print(repr(RI(Path("/home"))))'
PathRI(path='/home')
❯ python -c 'from pathlib import Path; from datalad.support.network import RI; print(repr(RI("/home")))'
PathRI(path='/home')

RF: remove unused code str-ing PurePath

---

changelog.d/pr-7067.md
datalad/support/constraints.py

Just that. Feel free to reject. It was just bothering me enough that I had this change in my local deployment to help me figure what is actually happening.

Let `EnsureChoice` report the value is failed validating

---

changelog.d/pr-7075.md
datalad/dataset/repo.py
datalad/support/tests/test_parallel.py

As commented added to the comment says we might want (eventually) make locking smarter and per "id" since in principle we should be able to instantiate multiple separate instances in parallel.  Might be useful or even critical for parallel "create" and alike.  But I think such use-cases are rare so decided to KISS.  test added, so disable locking to see how things could go wrong (hint: there is more than 1 way ;) ).
Fixes #6598

BF: lock across threads check/instantiation of Flyweight instances

---

changelog.d/pr-7068.md
datalad/cmd.py
datalad/support/annexrepo.py
datalad/tests/test_cmd.py

Fixes #6834
This PR ensures that `BatchedCommand` raises a `BatchedCommandError` if the subprocesses of `BatchedCommand` exits with a non-zero value or raises a `CommandError`.
- Adapt `BatchedCommand`-tests to actual behavior. Fixes #6834
- Ensure the errors from sub-processes of `BatchedCommand` are signaled to the caller via `BatchedCommandError`-exception

Ensure that `BatchedCommandError` is raised if the subprocesses of `BatchedCommand` fails or raises a `CommandError`

---

changelog.d/pr-7072.md
datalad/core/distributed/tests/test_clone.py
datalad/support/sshconnector.py
datalad/support/sshrun.py

`datalad sshrun` explicitly calls SSH with `log_output=False` which results in the use of `NoCapture` protocol with the runner. Meaning, stdout/stderr of SSH is written out anyway already. When SSH returns, `sshrun` tried to write both to its stdout/stderr. But: It could not possibly have anything to write. That would not be an issue in and of itself, but `sshrun` is not necessarily used directly. In particular it is called by `git` (due to `GIT_SSH_COMMAND=datalad sshrun`). This resulted in a problem when apparently `git` has closed the pipe to its ssh executable (`sshrun`) already and we tried to write to it (although we really didn't even have something to write).
This ultimately led to issue datalad#6599, where the actual `ssh ... git-upload-pack` execution succeeded and returned 0, …

BF: don't write output from within sshrun

---

.github/dependabot.yml
.github/workflows/benchmarks.yml
.github/workflows/docbuild.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/shellcheck.yml
.github/workflows/test-nose.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml
.github/workflows/test_macos.yml
.github/workflows/test_win2019_disabled
.github/workflows/typing.yml
.github/workflows/update-contributors.yml
changelog.d/pr-7082.md

We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.

Update GitHub Actions action versions

---

changelog.d/pr-7002.md
datalad/core/distributed/tests/test_clone.py
datalad/tests/utils_pytest.py
datalad/utils.py

The helpers for testing result records had a couple of bugs.
Most noteably, some (e.g. `assert_status`) would pass when no result was
given at all. Therefore command calls that did not return any result
were passing assertions about the `status` field of their results.
Furthermore, most of those helpers did not properly deal with all three
"representations" of results that are (and need to be) passed to them:
1. list of dict
2. single dict
3. generator
That's because `ensure_list` is used with the incoming results, but this
turns dicts that are not encapsulated by a list into a list of their
keys rather than a single-item list of dict. Reason for that is, that a
dict is iterable.
The falsely passing helpers also hid bugs in the tests - mostly command calls (`clone`) failing to set …

Fix test helpers for results

---

.github/PULL_REQUEST_TEMPLATE.md

Since we are migrating to an automation for changelog management with scriv, suggesting to describe changelog entry in description is suboptimal
- adds yet another way to specify changelog entries (thus - confusion)
- those entries would not be used and would get forgotten
- unlike scriv entries in a file included in the diff they cannot be easily provided "suggestions" to
- duplicate listing of agreed upon sections for the 3rd time (in addition to scriv.ini and action to add changelog entries)
thus, following our discussion at meetup, this PR removes changelog template from the PR template.

PR template: remove Changelog entries, refer to scriv

---

CHANGELOG.md
changelog.d/templates/new_fragment.md.j2
docs/source/changelog.rst
tools/ci/mkchlog-snippet.py

- adjust template to use markdown for links and make them thus more concise in rendering
- remove warping (TODO: file issue within WiP action to format similarly to template)
- fix up wrapping in prior changelog
[ci skip]
[appveyor skip]

release template etc fixups

---

changelog.d/pr-7095.md
datalad/distributed/create_sibling_ria.py

The `create_sibling_ria` command used `GitRepo(repo_path, create=True)` constructor to initialise bare repositories locally, also when `existing=reconfigure` was requested. But for existing repositories, `GitRepo` does not execute `git init`, it just returns a `GitRepo` instance, so `reconfigure` was not actually handled. This commit introduces an aditional check, to make sure that `git init` is called when reconfiguring.
Partially addresses #6967 (`--existing reconfigure --shared` not working). However, another problem remains: although we now do handle the reconfiguration, calling `git annex init --bare --shared` sets the config variable `core.sharedRepository` (which would presumably affect future commits), but does not change the permissions for the already existing files in the bare …

Make sure to re-initialise git repo

---

changelog.d/pr-7088.md
datalad/core/local/tests/test_save.py
datalad/support/gitrepo.py

fixes #6843 in a crude fashion by not bothering to add 2nd entry if one already exists.
Also contains separate commit for test (was created before this fix) and OPT to avoid double call of the same _save_add_submodules.
This is really a band-aid and not fixing underlying issue which I believe is somewhere else which leads to marking an existing and known `sub/` to be 'untracked` instead of `modified` -- an issue which I believe I observed before and then it was closed since immediate effect of taking too long was addressed.  I might find it eventually again. For now want to see if this fix works and not breaks anything.

Prevent adding duplicate entries to .gitmodules

---

datalad/interface/utils.py

This is an essential function that any command execution goes through, which is responsible for result generation and handling. This change refactors the code by
This second aspect is the main motivation for this change. It lays the foundation for homogeneous validation of parameters beyond the CLI-specific (partial) validation and the custom, per-command validation that is done after a command execution has started.
The work on such a validation has started in https://github.com/datalad/datalad-next/pull/116

RF `datalad.interface.utils.eval_results()`

---

changelog.d/pr-7093.md
datalad/distribution/get.py
datalad/distribution/tests/test_get.py

Fixes #5537.
This PR prevents double yielding of an impossible get result on a path that does not exist by keeping track of impossible get results and skipping additional yields inside `_install_targetpath()`.
The issue reported this problem occurring twice:
- when called from a superdataset _without_ interim subdatasets in the problematic path installed: this is addressed by changing the `bottomup` flag to `True` in the `Subdatasets.__call__()`.
- when called from a superdataset _with_ interim subdatasets in the problematic path already installed: this addressed by tracking the paths for which `_install_targetpath()` has already been called, using the new helper function `_check_error_reported()` and the tracking dict `error_reported`
These changes were rerun locally using the example …

[BF] Prevent double yielding of impossible get result

---

changelog.d/pr-7103
datalad/distributed/create_sibling_ghlike.py

This PR adds a different error message when `create_sibling_github` is used with `dry_run`. The new error message  actually gives repository names.
The docstring for `create_sibling_ghlike` `dry_run` option said:
```
if set, no repository will be created, only tests for
name collisions will be performed, and would-be repository names
are reported for all relevant datasets
```
However, it behaved like this (dataset with one subdataset):
```
❱ datalad create-sibling-gin --recursive --dry-run -d . ProjectX
create_sibling_gin [dry-run](ok): [sibling repository 'gin' created at None]
create_sibling_gin [dry-run](ok): [sibling repository 'gin' created at None]
create_sibling_gin [dry-run] (ok: 2)
```
Now it will behave like this:
```
❱ datalad create-sibling-gin --recursive …
```

Report repository name in `create_sibling_ghlike` dry run

---

changelog.d/pr-7107.md
datalad/runner/runner.py
datalad/runner/tests/test_witless_runner.py

Fixes #7040 
This PR fixes #7040. It ensures that an environment that is provided to the subprocess contains a proper entry for `PWD`. That means, the entry contains a string that describes the path of the working directory, and not a python-representation of a Path object.

Fix `PWD` environment entry if `cwd` provided to `Runner()` or `Runner.run()` is  a `Path`-object

---

CHANGELOG.md
changelog.d/pr-7103
changelog.d/pr-7112.md
datalad/cli/tests/test_main.py
datalad/metadata/tests/test_metadata.py
docs/source/changelog.rst

Dear @datalad/developers and @datalad/contributors , please
- add .md to changelog snippets you might decide to produce/rename manually
- use `tests.utils_pytest` not `tests.utils` (old, nose version, we should look to remove it probably after some minor major release)
- (reminder to myself as well) - do not forget to `r""` raw strings with escapes (e.g. `r"\["`)

Various small fixups ran after looking post-release and trying to build Debian package

---

changelog.d/pr-7117.md
datalad/local/add_archive_content.py

Committed by Adina but taken from the patch provided by @mih in https://github.com/datalad/datalad/issues/7113

BF: Fix add-archive-contents try-finally statement by defining variable earlier

---

changelog.d/pr-7119.md
datalad/support/tests/test_parallel.py

This PR extends the time after which we believe to witness a stalling thread to at least 5 seconds. This time-span will only be exhausted if the test is failing, i.e. an executing worker is stalling (or very very slow). The duration of a passing test is usually in the range of a few dozen milliseconds.
The commit adds output processing in order to actually start of few runner-related threads and performs thread-based asynchronous data processing.
The large time limit will hopefully reduce the number of false positives greatly, though it cannot *guarantee* the absence of false positives, it just makes them unlikely, i.e. less than 1 false positive per 10e5 executions.

Improve `datalad.support.tests.test_parallel.py::test_stalling`

---

changelog.d/pr-7123.md
datalad/distributed/ora_remote.py

Probing for the existence of a ria_layout_version file internally misconstructs a ``target_ri`` variable only used for reporting the path to the file. We noticed recently that this reporting was off, duplicating paths, e.g.:
```
[INFO   ] RIA store unavailable. 
-caused by- 
file:///tmp/myriastore/tmp/myriastore/ria-layout-version not found. 
-caused by- 
[Errno 2] No such file or directory: '/tmp/myriastore/ria-layout-version'
```
This duplication should be fixed with this small change. It extracts the file name (``ria_layout_version``) and appends it to the ria store location, instead of appending the entire path to it.

Fix RIA file URL reporting in exception handling

---

changelog.d/pr-7125.md
setup.py

pytest-cov was being restricted to an old version that produces warnings when combined with the latest version of pytest.  At the same time, it's doubtful that restricting the maximum version of pytest will ever help.

Unrestrict pytest and pytest-cov versions

---

changelog.d/pr-7126.md
datalad/support/tests/test_parallel.py

Still happens in some busy environments, like recently within https://app.travis-ci.com/github/datalad/datalad/jobs/586725682 of https://github.com/datalad/datalad/pull/7118
Attn @bpoldrack who was after all the flaky tests

XFAIL a check on length of results in test_gracefull_death

---

changelog.d/pr-7130.md
datalad/conftest.py

Similarly to git-annex disallowing it by default, now git started to disallow it for local clones. In our case it should be safe since we are cloning our own repos in the tests, thus should not be subject to the malicious attempts.
Closes #7116
Some runs in appveyor already carry new `git` so let's see if they all turn green now.

BF(TST): allow for "file" protocol

---

changelog.d/pr-7133.md
datalad/distribution/dataset.py
datalad/distribution/tests/test_dataset.py

Previously this constraint allowed for strings only.
Closes #7069

Let EnsureDataset handle Path instances

---

changelog.d/pr-7132.md
datalad/support/constraints.py

More informative AltConstraint error

---

changelog.d/pr-7147.md
datalad/core/distributed/clone.py

A RIA postclone config hook tried to read a special remote UUID from a stores config file by writing the config files contents to a temporary config file, and subsequently running ``git config -f <thatfile>``. As outlined in a comment by @bpoldrack in the code, ``git config -f -`` can read from stdin:
```
echo '[core]\n\trepositoryformatversion = 0\n\tfilemode = true\n\tbare = true\n' | git config -f - core.filemode
true
```
A quick chat in the Git IRC channel hinted that this is supported by git as its a unix convention. Trial and error confirms that this patch also runs successfully in a Windows CMD. I'll rely on the tests on MacOS to check if it runs there successfully, too. By switching to a git config call with stdin as the input file, we spare the need to write a temporary RIA …

BF: read RIA config from stdin instead of temporary file

---

changelog.d/pr-7071.md
datalad/local/foreach_dataset.py
datalad/local/tests/test_foreach_dataset.py
datalad/log.py
datalad/ui/dialog.py
datalad/ui/tests/test_dialog.py
docs/source/design/progress_reporting.rst

First commit is just a helper, 2nd is the actual changes with following ATM description:
Motivation for this feature is frequent use of  `foreach-dataset  git grep PATTERN` on e.g
captured by con/tinuous logs as I did in e.g. https://github.com/datalad/datalad/issues/6848 :
$> datalad foreach-dataset "git grep 'FAILED .*test_nested_pushclone_cycle_allplatforms'  | grep cron || :"
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022 (dataset)
03/cron/20220603T193647/173dc6f/travis-14100-failed/14.txt:FAILED ../core/distributed/tests/test_push.py::test_nested_pushclone_cycle_allplatforms
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/01 (dataset)
10/cron/20220610T193717/029f839/travis-14136-failed/14.txt:FAILED ../core/distributed/tests/test_push.py::test_nested_pushclone_cycle_a …

NF: foreach-dataset --o-s relpath - capture and pass-through prefixing with path to subds

---

benchmarks/common.py
changelog.d/pr-7154.md

ls command moved to datalad-deprecated. Import from api module, not from interface.
Closes #7149

Fix ls import in benchmarks

---

datalad/core/distributed/tests/test_push.py

two core tests were disabled a year ago on windows ci - I want to briefly check if they still fail. Fixes https://github.com/datalad/datalad/issues/6333.

TST: reenable two now-passing core test on Windows CI

---

datalad/customremotes/tests/test_datalad.py

Our cron tests against git annex 8.20200309 were failing due to wrong assumption that some prior old versions MUST had it wrong, which apparently was not the case.
Addressed 1/2 of #7157

BF(TST): for older versions allow either replaced or not -

---

changelog.d/pr-7159.md
datalad/distributed/ora_remote.py
datalad/distributed/tests/test_ria_basics.py

This test asserts that the push call will fail, because of read-only mode of the ORA remote. This is what happens, but with older annex we get an `IncompleteResultsError` rather than a `CommandError`. Not sure what changed for this to happen now, but in any case: `IncompleteResultsError` would be more desireable to begin with as we get an actual error result rather than a crash + if there's something to change to get this with all annex versions, it's in `push` or at a more generic layer when calling annex. The test, however, only is about testing that annex-copy and by extension datalad-push with the ORA remote fails under these circumstances.
Hence, accept both ways of failing from within this test. The difference warrants an investigation of `push`/`Runner` or whatever is causing the …

Fix test failure with old annex

---

changelog.d/pr-7166.md
datalad/core/local/status.py
datalad/core/local/tests/test_status.py

Fixes #7032 
This change adds a short check if any file in a list of paths given to a ``datalad status --annex `` call is untracked. If it is, it is removed from the list of paths given to the annex query, as we already know that this annex call would fail. 
It does not prevent the status report of being untracked:
```
❱ datalad status --annex basic my some moreuntracked 
untracked: moreuntracked (file)
untracked: my (file)
1 annex'd file (7.0 B recorded total size)
```
If untracked paths are excluded from this query, a trace of it is left in the debug log. 
This PR also adds a small test.

BF: Prevent doomed annex calls on files we already know are untracked

---

changelog.d/pr-7161.md
datalad/local/clean.py

`clean` was an outlier in that regard.
Closes #7026

RF: Specify parameter choices uniformly

---

changelog.d/pr-7174.md
datalad/core/distributed/push.py
datalad/core/local/diff.py
datalad/core/local/status.py
datalad/customremotes/archives.py
datalad/downloaders/credentials.py
datalad/downloaders/providers.py
datalad/interface/base.py
datalad/local/wtf.py
datalad/support/annexrepo.py
datalad/support/gitrepo.py
datalad/support/network.py
datalad/support/strings.py
datalad/support/tests/test_network.py
datalad/tests/test_utils.py
datalad/utils.py

This is an attempt to fix #6566, which calls for a replacement of OrderedDicts with regular dicts to increase performance/speed. There was only one instance in ``status()`` where OrderedDict-specific functionality was used; I used a patch cooked up by @yarikoptic in #6566 as an alternative. 
Let's check if the CI is happy with this change or if it breaks something.

Use regular dicts instead of OrderedDicts for speedier operations

---

changelog.d/pr-7194.md
datalad/core/local/tests/test_diff.py

Closes #3725
It is https://github.com/datalad/datalad/pull/7191 but against maint since IMHO it is worth there

Reenable now passing test_path_diff test on Windows

---

changelog.d/pr-7188.md
datalad/distributed/export_to_figshare.py

I checked whether [this export-to-figshare bug](https://github.com/datalad/datalad/issues/4137) still reproduces. But in its current state, the command is dysfunctional, failing first in an attempt to initialize a progressbar with a pathobject as a label, and then further by giving a path object to ``repo.add()`` (which can't handle pathobjects). The command also still relied on calling ``add_archive_content`` with a deprecated ``annex`` parameter, which would eventually crash in the patch the next extension provides for ``get_allargs_as_kwargs``. This PR adds some very patchy bandaids to make it functional again. But I guess the future should bring slightly more sweeping refurbishments. It would probably also help to have proper tests for this command.

Bandaids for export-to-figshare to restore functionality

---

CONTRIBUTING.md
changelog.d/pr-7195.md
docs/source/design/index.rst
docs/source/design/testing.rst

This fixes #6679 by moving the CONTRIBUTING section on migrating downstream code from nose to pytest into a dedicated Design document in the docs.
I just moved this section because there was an explicit issue about it, but if deemed useful, this new design document could contain more test-related information from contributing, and become a more general Design doc on tests and CI - what do you think?
[skip ci]
- closes #6679

DOC: Add design document on Tests and CI

---

changelog.d/pr-7201.md
datalad/cmd.py
datalad/runner/exception.py
datalad/runner/nonasyncrunner.py
datalad/runner/runner.py
datalad/runner/tests/test_nonasyncrunner.py
datalad/runner/tests/test_threadsafety.py
datalad/runner/tests/test_witless_runner.py
datalad/tests/test_cmd.py

This PR fixes a number of issues.
The PR extends the number of concurrent runner-call scenarios beyond the current implementation, i.e. serialize synchronous (non-generator) `ThreadedRunner.run()`-calls. The scenarios now supported are:
1. Concurrently invoke `ThreadedRunner.run()` without generator, leading to serialization of invocations.
2. Concurrently invoke `ThreadedRunner.run()` with generator, leading to serialisation of invocations, i.e. later invocations return if the currently active generator is exhausted
3. Concurrently read from a generator returned by `ThreadedRunner.run()`. Any number of threads can call `send()` on a generator, results will be returned as soon as they are available. Which of the waiting threads is continued is non-deterministic. If the generator is …

Fix runner hanging, fix an error in thread handling, and serialize concurrent generator-runner invocations

---

datalad/core/distributed/tests/test_clone.py
datalad/support/gitrepo.py

This change reincarnates parts of a changeset originally proposed in #4026, which did not make it in due to Windows errors I never saw (CI logs weren't preserved), but that I suspect to originate in https://github.com/datalad/datalad/issues/7180 (Git stitching together posix and windows paths into a non-functional URL). Thus, this change sits on top of https://github.com/datalad/datalad/pull/7181, which fixes
these URLs to be fully posix. Based on those fixes, this change wrangles absolute URLs originating from relative paths back into relative paths, to keep them functional.
This change also enables an old test for this problem, marked as a known
failure.
Fixes https://github.com/datalad/datalad/issues/3538

Fix broken submodule URLs generated from relative paths

---

CONTRIBUTING.md
changelog.d/pr-7204.md

It still had outdated information about using auto. Others were asking in matrix on the location of the build logs on smaug. So I listed those paths to ease locating them.
Ideally the PR should have been against `maint` which is now default visible branch but there were changes to CONTRIBUTING.md in master to refactor testing away, so to avoid merge conflicts etc, decided to keep it in master.  Not that critical - eventually it would become `maint` ;-)

DOC: extend/fix CONTRIBUTING.md with information on testing, changelog and releasing

---

datalad/core/distributed/tests/test_push.py
datalad/distributed/tests/test_drop.py

Ref: #7184, #7185, #7197
Need to do that since there is no human force available to investigate and address them currently and we might this way miss more failures on datalad/git-annex CI setup.
- Note: that I marked them as known only for github CI, so they might resurface on appveyor whenever a new release of git-annex comes out. Then either they would need to be addressed or marked as generally known to fail on windows
- Another note: PR is against `master` since seems there is no such fails on `maint`. See e.g. https://github.com/datalad/git-annex/actions/runs/3561508598 for comparison
- I think I will not bother with changelog entry for this change

Mark some tests as known fails on github CI windows

---

docs/source/design/result_records.rst

This is a small documentation fix for an old issue I found fully dissected, but yet unaddressed:
As elaborated in detail by @mslw in #6620, the common keyname for an error message in a result record is ``error_message``. The Design document on result records however spells this key as ``error-messages``, not as ``error_message`` as understood by ``generic_result_renderer()``. This commit changes the design document to use error_message. Fixes #6620
I would appreciate a brief review by @mslw to check if I understood his issue correctly.

DOC: Use standard key name 'error_message' in result record design docs

---

changelog.d/pr-7206.md
datalad/support/network.py
datalad/support/tests/test_network.py

Fixes #7186 
The current code base treats the `path` component of `file`-URLs not according to the conventions described in the relevant standard, i.e. [RFC8089](https://www.ietf.org/rfc/rfc8089.html) in [Appendix D.2](https://www.ietf.org/rfc/rfc8089.html#appendix-D.2) and [Appendix E.2](https://www.ietf.org/rfc/rfc8089.html#appendix-E.2) (funnily enough Append E.2 defines some "nonstandard techniques for interacting with DOS- or Windows-like file paths and URIs").
As @mih pointed out, there is support for the conventions described in RFC8089 Appendix D.2 and RFC8089 Appendix E.2 in python, implemented in `nturl2path`, which is transparently used in `urllib.request.url2pathname` on Windows systems.
This PR uses `urllib.request.url2pathname` to convert the path of a file-URL to a local …

Fix localpath handling for file-URLs on different OS, especially on Windows

---

.travis.yml
datalad/tests/test_utils.py

brought up by @christian-monch , see #7177 
ATM fails in datalad-installer to install 3.11 in conda -- filed https://github.com/datalad/datalad-installer/issues/133

Switch to test against 3.11 instead of 3.10 as the latest python to test against (travis)

---

changelog.d/pr-7183.md
datalad/core/distributed/clone.py
datalad/core/distributed/tests/test_clone.py

Fixes #7182
If the source in a clone command is a windows path, the resulting ```datalad_url``` in the .gitmodules file of the superdataset contains it verbatim, including escaped backslashes. Ensuring that it is posix makes it functional, and compliant to git's url format.

BF: Ensure that datalad urls are posix

---

changelog.d/pr-7210.md
datalad/cli/main.py
datalad/support/exceptions.py
datalad/support/tests/test_captured_exception.py

Ensure the already existing `format_exception_with_cause` also works with `traceback.TracebackException` and use this to provide another format method for `CapturedException`. This is then used with unexpectedly bubbled up exceptions by the CLI.
Fixes #7163
FTR:
Actually hard to find a case where I know an exception would bubble up and actually have a `__cause__` in core.
Making one up like this: 
```
raise ValueError("something is wrong") from RuntimeError("severe problem")
```
Would now be:
```
> datalad wtf
[ERROR  ] something is wrong -caused by- severe problem 
```
Whereas 
```
raise ValueError("something is wrong") from RuntimeError
```
Would lead to 
```
> datalad wtf
[ERROR  ] something is wrong -caused by- RuntimeError
```
Rational for sparing the class name when there's a …

Let CLI report on exception causes

---

changelog.d/pr-7215.md
datalad/distributed/ora_remote.py

This delays the remote-end `cat` command until just before its output is needed, for two reasons:
1. The command output is not needed if `get` decides to use scp
2. When getting multiple files encrypted by git-annex (which would use scp, due to size not being part of the annex key), the `cat` output would remain in standard output and would be read when checking whether the *next* file exists (i.e. when trying to parse a completely different output), crashing upon `decode()`. 
Fixes #7214

Reorder commands in ORA get via SSH

---

setup.py

Superfluous quotes made type-check action fail.
No changelog intended.

Fix setup.py for type-check action

---

changelog.d/pr-7209.md
datalad/conftest.py

Trying to fix #6623 and possibly #7165 by using MemoryKeyring with this test.
@yarikoptic Provided CI is happy to begin with, could you please give it a try?

Use MemoryKeyring in test

---

.zenodo.json
changelog.d/pr-7213.md
datalad/distributed/create_sibling_ghlike.py
datalad/distributed/create_sibling_gin.py
datalad/distributed/create_sibling_gitea.py
datalad/distributed/create_sibling_github.py
datalad/distributed/create_sibling_gitlab.py
datalad/distributed/create_sibling_gogs.py

This PR makes the extra_remote_settings attribute for GitHub-like create_sibling targets configurable on a per target basis. One usecase would be to override an annex-ignore setting, which is otherwise unconditionally set. E.g. if we host a gitea server which does support git-annex at example.com, we could set:
```
[datalad "extra_remote_settings.example.com"]
annex-ignore = false
```
in e.g. ~/.gitconfig to override the default of not using git-annex with gitea.
This approach does have the issue that the settings are apparently set before first enabling the remote. This leads to spurious warnings like this when creating the sibling:
```
[INFO   ] Could not enable annex remote origin. This is expected if origin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not …
```

NF: make extra_remote_settings configurable in git config

---

changelog.d/pr-7217.md
datalad/distribution/siblings.py

`datalad-siblings` would unconditionally issue an INFO level or even WARNING level log, whenever `git annex enableremote` returned non-zero. Those messages would also say, that this may be expected with a pure git remote or an empty repository on the remote end.
The main issue here is, that datalad users may not even have any expectation and are left with a message that suggests they should. This is confusing. At best we are training users to ignore our output.
Another aspect to this is, that when used as an internal command (most notably from within `create-sibling-*`), _we_ are the ones calling and having an expectation. The user didn't even call `siblings configure` let alone `git annex enableremote`. At the same time, with `create-sibling-*` we know that there is an empty repo at the …

Don't be scary when failing to annex-enable

---

.zenodo.json
datalad/support/annexrepo.py

I didn't have git annex installed. The error was helpful, but the link has changed:
```
datalad.support.exceptions.MissingExternalDependency: No working git-annex installation of version >= 8.20200309. Visit http://handbook.datalad.org/r.html?install for instructions on how to install DataLad and git-annex
```

Bf fix installation link git annex

---

.zenodo.json
datalad/support/annexrepo.py

Reverts datalad/datalad#7223
This was merged prematurely (by me). Actual issue is with handbook/readthedocs. See https://github.com/datalad-handbook/book/pull/880.

Revert "Bf fix installation link git annex"

---

datalad/customremotes/__init__.py
datalad/customremotes/archives.py
datalad/customremotes/base.py
datalad/customremotes/main.py
datalad/customremotes/tests/test_main.py

This is refactoring our `SpecialRemote` and `AnnexCustomRemote` classes. The latter only serves as base class for the `datalad` and `datalad-archives` special remotes, whereas the former is the more general one. Hence, move functionality that isn't specific to those two.
Two minor fixes along the way:
- Implementation of availability was a bit inconsistent
- Possible failure at the outermost layer wasn't sending an ERROR message to annex, but only logging.
I don't think this needs a changelog.

RF special remote base classes

---

changelog.d/pr-7226.md
datalad/cli/interface.py
datalad/cli/tests/test_interface.py
datalad/interface/base.py
datalad/interface/tests/test_docs.py

Fixes #7225
Interface specific substitutions did not work with nested brackets (and for some reason also not crossing newlines).
Looks like those regexes were simply meant to not be greedy.

Allow for brackets in PY&CMD doc markups

---

datalad/customremotes/ria_utils.py
datalad/customremotes/tests/test_ria_utils.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/ora_remote.py
datalad/support/network.py
datalad/support/tests/test_gitrepo.py
datalad/support/tests/test_network.py
setup.py

Fixes #7212 
This PR introduces functions to convert the path component of a file-URL to local file system paths, independent from the OS.
We should probably perform a proper check of the code base to find the places in which we handle file-URL path components naively, i.e. take them verbatim as local paths. Even with automated conversion of `/` in path components to `\` on Windows-like OS, e.g. when using `Path()`, a simple approach would fail because it does not take Windows-anchor encoding into account. For example the local Windows path `C:\\Windows` might be encoded as `/c:/Windows` in the path component of a file-URL.

Clean up conversion between local file system paths and file-URL path components

---

changelog.d/pr-7230.md
datalad/support/annexrepo.py

Apparently `--copies 0` could result in up to 10 (or more) penalty of running find or findref.  
TODO

Use --include=* or --anything instead of --copies 0 to speed up get_content_annexinfo

---

changelog.d/pr-7245.md
datalad/support/constraints.py

Just a small fix for a copy-paste mistake.

DOC: fix EnsureCallable docstring

---

changelog.d/pr-7249.md
datalad/support/annexrepo.py

Specifying 10.20221212+git18 as requirement doesn't work, when the reported version of an annex build is using a different scheme. It was used because the git-annex version required isn't released yet. See issue 7248.
However, we know the scheme of annex versions (it's a date after the dot), therefore setting the required version to one day after the previous release does the trick with respect to released annex versions. Hence, we will use this only with the coming release (not a current snapshot). But that is clearly more sensible than crashing on an annex version that doesn't support it yet.
Closes #7248

BF: Fix invalid version comparison

---

changelog.d/pr-7250.md
datalad/runner/runnerthreads.py
datalad/utils.py

This is a trivial patch from datalad-next, that significantly improves performance of save,status, etc. b/c of a much too small buffer when the runner is reading output.
Closes #7190

PERF: Buffer size optimization from datalad-next

---

.github/workflows/test-nose.yml
changelog.d/pr-7260.md

New one 3.10 causes installation problems since likely simply no longer maintained/compatible. For the sake of it, fix it to test against 3.8 and in another PR against master we should deprecate/remove nose parts entirely
Closes #7259

BF(TST): use older python 3.8 in testing nose utils

---

changelog.d/pr-7263.md
setup.py

This reverts commit 09cb41ce5b5d8800d00e2ead9c8a95cc2e4e767a. Original PR which removed upper bound:
https://github.com/datalad/datalad/pull/7029
Debians now have 5.1.0, and we can't package while demanding an outdated chardet. Let's see again if we really need to limit upper version.

Revert "Revert "Remove chardet version upper limit""

---

README.md

Datalad is available directly via the package managers of a number of distributions (full list: https://repology.org/project/datalad/versions ), in addition to PyPI. I think it would be good to list the few of them which have more-or-less up-to-date versions available.
This PR creates an alphabetically ordered sub-heading for that, and moves PyPI inline with the others for consistency.
I know Debian also has somewhat up-to-date versions available, but as seen in the link above it seems to be versioned, so I'm unsure how to dynamically refer to the newest, or maybe whether we should instead refer to the unstable entry (and in that case whether to refer to NeuroDebian or just Debian). I would assume @yarikoptic knows more about this.

Display version badges of DataLad across various package distributions in README.md

---

.zenodo.json
changelog.d/pr-7265.md
datalad/distribution/create_sibling.py
datalad/distribution/tests/test_create_sibling.py

Came up in [chat](https://app.element.io/#/room/#datalad:matrix.org):
`datalad create-sibling` failed when trying to check for the existance of the sibling because of a non-fixed locale. Example:
```bash
yann in machine in ~/code/datalad 
❯ datalad create ds
[WARNING] Requested extension 'next' is not available 
create(ok): /home/yann/code/datalad/ds (dataset)
yann in machine in ~/code/datalad took 4s220ms 
❮ datalad create-sibling -d ds machine.server.de:code/datalad/ds-sibling
[WARNING] Requested extension 'next' is not available 
[INFO   ] No sibling name given. Using URL hostname 'machine.server.de' as sibling name 
[INFO   ] Connecting ... 
[INFO   ] Considering to create a target dataset /home/yann/code/datalad/ds at code/datalad/ds-sibling of machine.server.de 
CommandError: 'ssh …
```

Fix `create-sibling` for non-English SSH remotes

---

changelog.d/pr-7267.md
datalad/support/constraints.py
datalad/tests/test_constraints.py

`EnsureListOf()` and `EnsureTupleOf()` took string inputs as iterables. This PR fixes this.
(I don't understand this `scriv` thing, `scriv create` etc. all error out with unfound files, so I'll leave it to you to add this CHANGELOG label.)

Fix EnsureListOf() and EnsureTupleOf() for string inputs

---

README.md

@yarikoptic some additional fixes:
* the original badges had a lot of redundant text (like repeating the word package in each one), figured out how to remove it.
* previously the github version badge was repeated twice
* we were missing Fedora, which interestingly also ships up-to-date datalad 🥳
* the list was not sorted alphabetically

Compact badges

---

changelog.d/pr-7273.md
datalad/distribution/create_sibling.py

- supports special characters in filenames (like umlauts, etc.)
- `ls` seems to fall back to predictable `C` locale if `LC_ALL` is set to an unknown locale, so this should be safe.
- still: `create-sibling` currently fails silently if an umlaut is in the `--target-dir` and the remote `ls` doesn't handle it properly.
follow-up on PR #7265

create-sibling: Use C.UTF-8 locale instead of C

---

docs/source/conf.py

Follow up to https://github.com/datalad/datalad/pull/7014 which removed all metadata handling.  Without this change we get
❯ make -C docs html
make: Entering directory '/home/yoh/proj/datalad/datalad-maint/docs'
DATALAD_SPHINX_RUN=1 sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v6.1.3
running build_manpage
running build_cfginfo
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'build_schema'
... proceeding normally
without crashing so we missed that

sphinx: do not call build_schema

---

.codespell-ignorewords
.codespellrc
CHANGELOG.md
CONTRIBUTING.md
Makefile
changelog.d/pr-7271.md
docs/design.rst
docs/source/basics.rst
docs/source/changelog.rst
docs/source/design/drop.rst
docs/source/design/exception_handling.rst
tools/ci/install-annex.sh
tox.ini

I was codespell'ing a few other projects and got scared that we do not codespell our own DataLad because there were no `.codespellrc`.  apparently we did codespell but with custom CLI options in tox.ini and only the main package.  This PR makes codespelling more thorough, and in particular with us using scriv for changelogs - makes more sense now since we can then spellcheck those entries too (I checked using strace that codespell does open files under `changelog.d/`).

Codespell more (CHANGELOGs etc) and remove custom CLI options from tox.ini

---

datalad/distributed/ora_remote.py

Minor "fix".  I don't think it is even worth a changelog entry.
But also sending to to reconfirm that we observe fails of #7296

BF: declare string r-aw for the \. escape

---

changelog.d/pr-7280.md
datalad/distribution/get.py
datalad/distribution/tests/test_get.py
datalad/support/gitrepo.py

The `path` property was treated as a special case in `GitRepo.get_submodules_` presumably to not yield redundant information, because what is returned is a dict where the path is the key and the other properties from `.gitmodules` make up the value (another dict), prefixed with `gitmodule_`.
However, actual usage from `get` via `subdatasets` suggests, that the easiest is to just yield this "redundant" record. Once as the reported property exactly like `url`, `datalad-id` and whatever else, and in addition let the path remain the key. Throughout that chain the latter gets possibly turned into an absolute path anyway (which is not what we want to report here - it's just for internal use).
Closes #7274

BF: path from .gitmodules could not be used with source candidate template

---

changelog.d/pr-7289.md
datalad/distributed/create_sibling_ria.py
docs/source/modref.rst

This PR adds `create_sibling_ria`, `foreach_dataset`, `export_archive_ora`, and `shell_completion` to the table of contents in the Python module reference, therefore including them in the html documentation.
This required a change to section headings in the `create_sibling_ria` docstring, because sphinx napoleon extension only allows a set of predefined headings (custom ones can be added, but I thought reformatting makes more sense). I also used the opportunity to change single quotes into double backticks in said docstring, but compared to headings this isn't necessary for the docbuild.
Details in commit messages. Closes #7288

Api docs patch

---

datalad/distribution/create_sibling.py

Originally, #6839 replaced usage of distutils with Looseversion as a fix for #6307. Somehow, this one isolated import of distutils seems to have made it back. This is a quick PR to remove it.
A changelog entry shouldn't be needed for this.

MNT: remove leftover distutils import

---

changelog.d/pr-7322.md
datalad/local/tests/test_wtf.py
datalad/local/wtf.py

+  + strengthen the test for unavail section (will come handy for #7309 etc, doing here to avoid conflicts etc)
Otherwise we get
❯ python -c "import datalad.api as dl; out = dl.wtf(sections=['murkie'])"
...

Do not render (empty) WTF report on other records

---

datalad/tests/utils_pytest.py

I was trying to use the @with_tempfile test decorator, but it wasn't working using the example syntax.
@with_tempfile                                                                                                                                                                                
def test__singularity_version_nofile(path):
pass 
Fails with the following traceback:
file /home/asmacdo/devel/datalad-container/datalad_container/extractors/tests/test_metalad_container.py, line 30
@with_tempfile
def test__singularity_version_nofile(path):
E       fixture 'path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, …

Fix pytest_util with_tempfile example

---

changelog.d/pr-7331.md
datalad/core/distributed/tests/test_clone.py
datalad/distribution/tests/test_siblings.py
datalad/support/tests/test_annexrepo.py
datalad/tests/test_archives.py
datalad/tests/utils_pytest.py

since masks away possible other issues and makes it difficult to assess PRs. The issue is filed, @adswa even had a look already, hopefully gets resolved some time soon.
Ref: #7320
edit: added more tests to be "treated" in hopes to get CI green again

Skip or xfail some currently failing or stalling tests

---

changelog.d/pr-7330.md
datalad/ui/progressbars.py
setup.py

Following a todo that I stumbled upon in the progress bars code which said "Drop this and set a minimum tqdm version once Debian stable has v4.32.0", I removed a kludge for old tqdm versions and introduced a minimum tqdm version dependency, 4.32.0 (released 2019-05-13) -- current Debian stable has v4.57.0. This also allowed removing settings / workarounds relevant to old versions only. Since tqdm v4.32.0 is fairly old as of today, this change seems safe to do.

Remove reset() kludge for tqdm, add version requirement

---

changelog.d/pr-7312.md
datalad/distribution/tests/test_update.py
datalad/support/gitrepo.py

As @bpoldrack identified in
https://github.com/datalad/datalad/issues/7291#issuecomment-1456147953 the 629e575628ba8b53bf073392837c9e4b49444838 which was part of the #4650 concerning introduction of minimal git version to be 2.19.1, and not removing that condition was was combined with argument to the merge function. That commit was released within good old 0.13.4.
This change merely reintroduces "if" statement BUT unfortunately that allow_unrelated nowhere exposed in the API really, and used only once with allow_unrelated=True in some single test. So I expect some tests to fail here and most likely us needing to introduce similar option in "update" to finalize this PR.

BF: GitRepo.merge do not allow merging unrelated unconditionally

---

datalad/support/annexrepo.py

Originally implemented in datalad-next by @mih and also proposed in #6316, this change migrates a helper from datalad-next that wraps annexrepo.call_annex() with a convenience layer to return True or False depending on the success of the call. I found at least one usage in annexrepo where this helper is useful, and I suspect there are more. Fixes #6316

Adopt call_annex_success helper from next

---

changelog.d/pr-7333.md
datalad/customremotes/datalad.py

Utilize `CapturedException.format_with_cause` instead of a custom solution, potentially leading to an error message containing an uninformative `[None]`.
This would also include more than just the first-level `__cause__` (all the way down and include potential `__context__` as well)
Closes #7332
With this change the output reported in #7332 (`Failed to download from any of 2 locations [None]`) changes to:
```
[{'action': 'get',
'annexkey': 'MD5E-s994556226--ffc1353e08d640c7ba3154d963573732.nii.gz',
'error_message': 'Failed to download from any of 2 locations ["Failed to '
'acquire lock to establish download session at '
'/home/<REDACTED>.cache/datalad/locks/downloader-auth.lck '
'in 3 attempts.Check following process: PID=2946262 ' …
```

Fix datalad special remote error reporting

---

datalad/distributed/drop.py
datalad/distributed/tests/test_drop.py

This fixes #7013.
If a drop --recursive --what all --reckless kill was provided with paths
to directories, it silently skipped killing the contained subdatasets.
The problem arises when the internal resolving of paths to datasets
determines that the provided directory path belongs to the superdataset.
Instead of then recursing into the subdirectory's potential subdatasets,
drop restrained the scope of what was to be dropped to only
'filecontent' in order to limit the drop from the determined
superdataset to the provided path as an internal safety mechanism:
if paths is not None and paths != [ds.pathobj] and what == 'all':
lgr.debug('Only dropping file content for given paths in %s, '
'allthough instruction was to drop %s', ds, what)
what = 'filecontent'
This change lifts this safety …

 BF: Don't skip subds underneath paths in reckless & recursive drop

---

datalad/tests/test_tests_utils_pytest.py

May be CI version would work differently from local?
See https://github.com/datalad/datalad/issues/6846#issuecomment-1363878497 for the reference
attn @bpoldrack

ENH(TST): add a test for assert_raises since concern was raised

---

changelog.d/pr-7329.md
datalad/support/annexrepo.py

The previous assertion that there's no stderr output to be expected is
wrong. This function is calling git-annex commands, which in turn may
involve arbitrary special remotes. DataLad can not know whether there is
anything to expect on stderr and if such would indicate an error. We
should be able to rely on git-annex returning non-zero.
Closes #7328

Allow stderr for git-annex subprocess with records generator

---

changelog.d/pr-7353.md
datalad/support/tests/test_repo_save.py
datalad/tests/utils_pytest.py

While preparing unittest to demonstrate #7351 problem I found that the good old "parametric" test copied long time from revolution was actually not parametrized at all and thus pretty much causing running the same testing (with AnnexRepo) twice.  This PR in this shape just fixes that  and must not result in new failures.
As a result we do get differential timing for those two tests:
```
11.45s call     datalad/support/tests/test_repo_save.py::test_annexrepo_save_all
8.14s call     datalad/support/tests/test_repo_save.py::test_gitrepo_save_all
```
from original idential
```
13.86s call     datalad/support/tests/test_repo_save.py::test_gitrepo_save_all
13.83s call     datalad/support/tests/test_repo_save.py::test_annexrepo_save_all
```
;)

Fix testing assumption - do create pure GitRepo superdataset and test against it

---

changelog.d/pr-7337.md
datalad/cmd.py
datalad/runner/coreprotocols.py
datalad/runner/exception.py
datalad/runner/nonasyncrunner.py
datalad/runner/protocol.py
datalad/runner/runnerthreads.py
datalad/runner/tests/test_exception.py
datalad/runner/tests/test_generatormixin.py
datalad/runner/tests/test_gitrunner.py
datalad/runner/tests/test_nonasyncrunner.py
datalad/runner/tests/test_threadsafety.py
datalad/runner/tests/test_utils.py
datalad/runner/tests/test_witless_runner.py
datalad/runner/tests/utils.py
datalad/runner/utils.py

Type-annotate various things in `datalad/runner/`

---

changelog.d/pr-7301.md
datalad/config.py
datalad/distribution/dataset.py
datalad/tests/test_base.py
datalad/tests/test_config.py

The issue is described in #7299. This change set contains three commits
- one documents both aspects of the issue in a test
- one reduced the amount of manager synchronization that needs to be done by no longer handing out custom `ConfigManager` instances for `Dataset`s without a repository
- one now causes an update of the global `datalad.cfg` instance, whenever any `ConfigManager` updated the `global` configuration scope
Closes #7299

Improve uptodateness of config reports across manager instances

---

changelog.d/pr-7342.md
datalad/distribution/tests/test_siblings.py
datalad/support/external_versions.py
datalad/tests/utils_pytest.py

A fix in rsync 3.2.4 broke compatibility with older annex versions.
To make things a bit more complicated, ubuntu pulled that fix into
their rsync package for 3.1.3-8.
Adjust the test wrapper's existing skip conditions in accordingly and
reenable the test.
Closes #7320

Skip with_sameas_remote when rsync and annex are incompatible

---

changelog.d/pr-7355.md
datalad/core/local/save.py
datalad/support/tests/test_repo_save.py
datalad/tests/utils_pytest.py

Sits on top of #7353 to reuse existing testing setup. Actual fix is few character change in `save.py` and is present in the last non-changelog commit.
Closes #7351

Fix save to not force committing into git if reference dataset is pure git (not git-annex)

---

setup.py

Set minimal version of typing_extensions to be 3.10.0.0

---

datalad/core/distributed/push.py

So instead of
1: ['datasets.datalad.org'] matches a sibling name and not a path. Forgot --to?
user gets
1: datasets.datalad.org matches a sibling name and not a path. Forgot --to?

ENH: push - delist hint if there is only one value

---

datalad/core/distributed/clone_utils.py
datalad/support/annexrepo.py

This closes #7366 but also since I did announce "datalad" to be dead for ///repronim/containers, it should address currently present across the board fail of the test `test_autoenabled_remote_msg` since `datalad` remote is no longer autoenabled and user does receive a message about that. Ideally that test should be redone on some other repo to not rely on "properties" of external to it `///repronim/containers`
NB also fixed one unrelated but close by string formatting gotcha I spotted

BF: do not include (by default) dead special remotes in get_special_remotes

---

changelog.d/pr-7341.md
datalad/support/gitrepo.py
datalad/support/path.py
datalad/typing.py
setup.cfg
setup.py
tox.ini

Type-annotate `datalad/support/gitrepo.py`

---

CONTRIBUTING.md
datalad/conftest.py
datalad/interface/common_cfg.py

We hardcoded to set it to a plain text keyring in
d8d538ae77ee8740ee2ca44e2b33f99b73a4ec3c of
https://github.com/datalad/datalad/pull/7209 to completely disable possible attempt of keyring to interact with user e.g. to establish a new keyring. That was done to address #6623 which came up during debian package building.
But the need for older behavior was realized while approaching #7340 where interactions with s3 were replaced to use boto3 but to test I needed credentials, but we were just skipping the tests since credentials were not present in that fake keyring.
With this patch I could run
DATALAD_TESTS_CREDENTIALS=system python3 -m pytest -s -v datalad/downloaders/tests/test_s3.py
and see tests to interact with S3.  Test relating to NDA were failing since most likely NDA broke the …

ENH(TST): add DATALAD_TESTS_CREDENTIALS=system for known credentials to be used during tests

---

.appveyor.yml
.travis.yml
changelog.d/pr-7379.md
datalad/tests/test_s3.py

In this PR I decided to absorb all fixes to get our CI green again
1. ref: https://github.com/OpenNeuroOrg/openneuro/issues/2809   - prior one stopped allowing for ListObjectVersions
I have better "control" over what happens on DANDI bucket, and this URL we share with other projects for testing ROS3 driver, so used in other projects tests
This test started to fail Apr 28th, taints other tests failures, so should be merged asap
2. Use our mirror for .deb instead of snapshots (replaces #7381)
3. Use specific version of miniconda installer (avail with fresh 0.12.0 datalad-installer)

Fix failing testing on CI: Use sample S3 url DANDI archive, our copy of old .deb, specific miniconda installer for py 3.7

---

datalad/ui/dialog.py

To gather more forensics (now and possibly in the future) on how things work in relation to
I am not sure where the UnderAnnexUI is supposed to learn about the special remote instance.
of https://github.com/datalad/datalad/issues/7382 .  With this we get
❯ DATALAD_LOG_TRACEBACK=100 DATALAD_LOG_LEVEL=debug git annex addurl --json --json-progress s3://dandiarchive/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3 2>&1 | grep -e UI -e progress
[DEBUG] git-annex-remote-datalad:8>datalad:116>main:68>ui.__init__:86  UI set to UnderAnnexUI(out=<TextIOWrapper>, specialremote=None)
[DEBUG] git-annex-remote-datalad:8>datalad:116>main:78,53>datalad:37>customremotes.base:36>customremotes.__init__:60>dialog:349  Setting specialremote of UI UnderAnnexUI(out=<TextIOWrapper>, specialremote=None) to …

ENH: add a debug msg while setting/changing specialremote of UnderAnnexUI

---

docs/source/design/index.rst
docs/source/design/result_records.rst
docs/source/design/user_messaging.rst

This PR:
- Aims to address https://github.com/datalad/datalad/issues/6613
- Adds a design specification "User messaging: result records vs exceptions vs logging"
- This specification aims to delineate the applicable contexts for using result records,  exceptions, logging, or other types of user messaging methods.
TODOs:

DOC: Add a "User messaging" design doc

---

changelog.d/pr-7385.md
docs/source/conf.py

This is a recommended workaround for search function & flyout menu not working on Read the Docs with a combination of sphinx-6.2.1 & sphinx-rtd-theme-1.2.0. It is likely to be fixed with sphinx-rtd-theme v1.3, at which point the change can be reverted (or we can try to wait it out).
There is no additional dependency to install, since the theme already installs `sphinxcontrib.jquery`.
Fixes #7374

docs: add workaround for theme issues (search not working)

---

datalad/core/local/run.py

A support ticket documents that the documentation of the command was silent about subdatasets also being saved. This change adds a paragraph to the command description to rectify that.
https://github.com/psychoinformatics-de/knowledge-base/issues/41

Clarify treatment of subdataset modifications by `run`

---

datalad/__init__.py
datalad/config.py

DataLad warns about an undefined Git identity (user.name|email). It does that whether or not any Git identity is actually necessary or even anyhow considered. The `ConfigManager` constructor is (ab)used to trigger this warning, and a `ConfigManager` class member is used to prevent repeated warnings.
This changeset maintains the exact same behavior (warn on `datalad import`), but moves the associated code out of the `ConfigManager` class. This class is not involved in any Git repository manipulations. The warning is trigger in `datalad/__init__.py` directly, hence no protection against repeated execution is needed (Python does it automatically).

Discontinue ConfigManager abuse for Git identity warning

---

datalad/distributed/create_sibling_gitlab.py

The old link 404'ed.
Changelog should not be needed.

Fix documentation link to python-gitlab

---

.github/workflows/test_extensions.yml
changelog.d/pr-7413.md

Currently testing of datalad-next is failing (and has been for awhile) due to
AttributeError: module 'gzip' has no attribute 'BadGzipFile'
and that one was added in 3.8.  I have not researched how come appveyor with 3.7 testing in datalad-next is not running into this.  As 3.7 is about to EOL, I think it is ok to start testing downstream extensions with the next 3.8.

Boost python to 3.8 during extensions testing

---

changelog.d/pr-7412.md
docs/source/conf.py
setup.py
tox.ini

Use `sphinx_autodoc_typehints`

---

changelog.d/pr-7388.md
datalad/local/addurls.py

I was trying addurls on a file from https://gpt4all.io/models/models.json  . 
First
```
datalad  addurls -t json --key 'et:MD5-s{size}--{md5sum}' models.json 'https://gpt4all.io/models/{filename}' '{filename}'
```
was just crashing since not all records have some fields.  I could have excluded them using `-x` regex, but I thought it would be suboptimal since that would result in not recording some metadata. So I decided just to issue a warning and proceed adding all other fields which have metadata present.
Then, surprisingly the `--key` simply had no effect and no warning of any kind was issued.  It was since I used `size` instead of `filesize`.  DEBUG level message was likely there but IMHO it is too much of a user mistake to just silently ignore since IMHO it is most likely a …

ENH: minor tune up of addurls to be more tollerant and "informative"

---

changelog.d/pr-7407.md
datalad/distributed/create_sibling_gitlab.py
datalad/distributed/tests/test_create_sibling_gitlab.py

The main change is from `_repo_` to `repo`. This PR serves as a space to brainstorm an effective solution.
Closes #6681

Address gitlab API special character restrictions

---

changelog.d/pr-7418.md
datalad/core/distributed/tests/test_clone.py
datalad/interface/common_cfg.py

Otherwise we would fail to clone (git would start asking for password since there is no such repo) github repositories while including trailing / which should be perfectly fine and which git handles just fine:
❯ datalad -l debug clone https://github.com/datasets-mila/datasets--robotcar/
[DEBUG  ] Command line args 1st pass for DataLad 0.18.4+21.g560dc910e. Parsed: Namespace() Unparsed: ['clone', 'https://github.com/datasets-mila/datasets--robotcar/']
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'>
[DEBUG  ] Parsing known args among ['/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/datalad', '-l', 'debug', 'clone', 'https://github.com/datasets-mila/datasets--robotcar/']
[DEBUG  ] Determined class of decorated function: <class …

Do not map (leave as is) trailing / or \ in github URLs.

---

datalad/config.py

Instead of doing this once per config item (many), do it once per path (few). On my system with 161 config items this leads to a 6x speed-up.
Before:
```
838 µs ± 8.54 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
After:
```
142 µs ± 7.69 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
Code:
```py
>>> import subprocess; dump=subprocess.run(['git', 'config', '-z', '--list', '--show-origin'], capture_output=True, text=True).stdout; from datalad.config import parse_gitconfig_dump
>>>  timeit p=parse_gitconfig_dump(dump)
```

OPT: parse_gitconfig_dump() origin path processing

---

changelog.d/pr-7050.md
datalad/core/local/status.py

See individual commits for more info. Inspired by https://github.com/datalad/datalad/pull/7049 
- first commit - report at least correct number of annexed files
- 2nd - if relaxed file is present, takes its size from io.stat.  But may be we should move that logic into get_content_info or alike?
also thought to tune up `bytes2human` to not report odd looking float Byte sizes such as `1.0 B` instead of `1 B` but decided to not bother .

More correct summary reporting for relaxed (no size) --annex

---

.travis.yml
changelog.d/pr-7372.md
datalad/dataset/gitrepo.py
datalad/distributed/create_sibling_ria.py
datalad/distributed/export_archive_ora.py
datalad/support/annexrepo.py
datalad/support/tests/test_annexrepo.py
datalad/support/tests/test_fileinfo.py
tools/find-hanged-tests
tox.ini

we get 3
```
FAILED ../datalad/distributed/tests/test_create_sibling_ria.py::test_create_simple - datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'create-sibling-ria',
'message': 'initremote failed.\n'
'stdout: \n'
'\n'
'stderr: There is already a special remote named '
'"datastore-storage". (Use enableremote to enable an existing '
'special remote.)\n',
'path': '/tmp/datalad_temp_tree__test_create_store3j2ta_0c',
'status': 'error',
'type': 'dataset'}]
FAILED ../datalad/support/tests/test_annexrepo.py::test_AnnexRepo_always_commit - assert ' |;&%b5{}\'"<>ΔЙקم๗あ .datc _1' in '+ Fri, 21 Apr 2023 16:19:55 UTC " |;&%b5{}\'\\"<>\\316\\224\\320\\231\\327\\247\\331\\205\\340\\271\\227\\343\\201\\202 .datc _1" | …
```

Address recent changes in behavior of git-annex

---

changelog.d/pr-7443.md
datalad/support/annexrepo.py

Lead to a failure on Windows.
Apparently with core.quotepath=false we would not get simple filenames quoted, so we should decide to remove or not quotes "dynamically" on whether we find them
Closes #7440

Remove surrounding quotes in output filenames even for newer version of annex

---

changelog.d/pr-7445.md
datalad/distribution/install.py

Prompted by #7441 and might even close it if @asmacdo acdo agrees that it does.
I also changed "recommended" to "possible" in the paragraph about 'description' since I think we converged in some discussion in datalad-handbook that it is typically not recommended.
Now `--help` would look like
```shell
Usage: datalad install [-h] [-s URL-OR-PATH] [-d DATASET] [-g]
[-D DESCRIPTION] [-r] [-R LEVELS]
[--reckless [auto|ephemeral|shared-...]] [-J NJOBS]
[--branch BRANCH] [--version]
[URL-OR-PATH ...]
Install one or many datasets from remote URL(s) or local PATH source(s).
This command creates local sibling(s) of existing dataset(s) from
(remote) locations specified as URL(s) or path(s). Optional recursion into
potential subdatasets, and download of all referenced data is supported.
The new …
```

DOC: clarify description of the "install" interface to reflect its convoluted behavior

---

changelog.d/pr-7403.md
datalad/core/local/save.py
datalad/interface/results.py
datalad/support/gitrepo.py
datalad/support/tests/test_repo_save.py
docs/source/design/result_records.rst
tox.ini

I decided to start type annotating there instead of relying on numpy docstrings
Ref #6884
TODOs

Type annotate get_status_dict and note that we can pass Exception or CapturedException which is not subclass

---

changelog.d/pr-7431.md
datalad/core/local/tests/test_diff.py
datalad/core/local/tests/test_save.py
datalad/support/gitrepo.py

This PR raises the minimal Git version to 2.25. It fixes issue #7389, and removes a number of kludges that worked around certain Git versions below 2.25. I had only a few minutes on the train to look for kludges, so I think its unlikely I found them all.

Increase minimal Git version to 2.25

---

changelog.d/pr-7463.md
datalad/distribution/install.py
datalad/distribution/tests/test_install.py

Happens whenever install is invoked with a URL and --branch option. Closes #7461.
TODO:

Pass branch option into recursive call within Install - for the cases whenever install is invoked with URL(s)

---

changelog.d/pr-7439.md
datalad/cli/parser.py
datalad/local/run_procedure.py
datalad/support/external_versions.py
setup.py

Eliminate uses of `pkg_resources`

---

datalad/tests/test_archives.py

Otherwise we get such not very informative
```
FAILED ../datalad/tests/test_archives.py::test_decompress_file[None] - assert False
FAILED ../datalad/tests/test_archives.py::test_decompress_file[strip] - assert False
```

RF(TST): use straight "assert" so may be pytest would provide more context

---

changelog.d/pr-7399.md
datalad/runner/runner.py
datalad/runner/tests/test_witless_runner.py

This PR modifies `WitlessRunner._get_adjusted_env()` to honor the `copy`-parameter and perform a copy only if `copy` is `True`.
In addition, it improves the docstring of the method.

Honor the copy parameter _get_adjusted_env()

---

changelog.d/pr-7472.md
datalad/core/distributed/clone_ephemeral.py
datalad/core/distributed/tests/test_clone.py

The last commit is actual fix + test, and prior one is just RFing test to avoid duplication and then reuse common testing logic in the fix.  That fix fixes #7469

Allow for reckless=ephemeral clone using relative path for the original location

---

changelog.d/pr-7488.md
datalad/local/tests/test_add_archive_content.py

Prior one is coming from "nose support" layer which is about to be deprecated. So we were getting flood of warnings like
local/tests/test_add_archive_content.py::TestAddArchiveOptions::test_override_existing_under_git
/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/_pytest/fixtures.py:911: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
local/tests/test_add_archive_content.py::TestAddArchiveOptions::test_override_existing_under_git is using nose-specific method: `teardown(self)`
To remove this warning, rename it to `teardown_method(self)`
See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
next(it)
for a while but didn't spot them.  I think that is the only place …

RF(TST): use setup_method and teardown_method in TestAddArchiveOptions

---

benchmarks/api.py
changelog.d/pr-7502.md
tools/ci/benchmark-travis-pr.sh

Only with fresh asv 0.6.0 which started to exit with exit code 2 if any benchmark failed, we finally had to pay attention to those long failing benchmarks. We have removed the option 'revision' so long ago but first didn't mention and then just ignored. For that and time_remove I also made it into dataset method invocation since otherwise it was not finding the dataset any longer given the path to it (didn't investigate deeper).

Fix time_diff* and time_remove benchmarks to account for long RFed interfaces

---

datalad/runner/nonasyncrunner.py
docs/source/modref.rst

Fixes #7499 
This PR fixes a syntax error in a doc-string and adds some missing source files to doc-string-based HTML-documentation generation.

Fix documentation syntax, add files for doc-string parsing

---

changelog.d/pr-7500.md
docs/source/design/threaded_runner.rst

Fixes #7498 
This commit clarifies the description of the protocols that are used by the ThreadedRunner-class. It states prominently that we use the same interface as the asyncio-protocol classes, but that we do not make use of any asyncio functionality.

improve threaded-runner documentation

---

benchmarks/api.py
changelog.d/pr-7505.md

Return the `time_remove` benchmark back.
Thanks to @trexfeathers for the RTFM pointers in
https://github.com/airspeed-velocity/asv/issues/1347#issuecomment-1752652351

Inform asv that there should be no warmup runs for time_remove benchmark

---

changelog.d/pr-7471.md
datalad/core/distributed/tests/test_clone.py
datalad/tests/utils_pytest.py

We have about 15 invocations, each one would redo that check for no good reason.

Cache value of the has_symlink_capability to spare some cycles

---

.github/workflows/test_extensions.yml
tools/ci/install-singularity.sh

That script now installs also libfuse2 library needed by singularity-ce, which lead to failed installations in this repo CI.
Ideally we should establish central collection of CI tools at some point to reuse across various extensions and derivative projects. ATM we will have 3 copies of this script: here, in datalad-container and datalad-extensions.

Copy script to install singularity from datalad-container and use it in the workflow

---

changelog.d/20231025_194118_michael.hanke_bf_7507.md
datalad/distribution/update.py

The true cause of the problem is not well understood. https://github.com/datalad/datalad/issues/7507 documents that I was not able to capture the breakage in a test, despite approaching it from different angles.
Only the original reproducer documents that this patch fixes the problem. However, the involved datasets are too heavy to be used in an already overloaded test battery. Hence this fix is proposed without a corresponding test.
Closes #7507

Robustify update target detection for adjusted mode datasets

---

changelog.d/pr-7541.md
datalad/distributed/tests/test_drop.py

What matters really is that we fail and that there is "unsafe" and some message from git-annex.  In [10.20231129-18-gfd0b510573](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=fd0b5105731b17899d79cade82436320ab85cb56) git-annex changed message to become better but I do not think we should overcomplicate test ot match both messages exactly since who knows what other improvements might come later again.
Marking it for release so we bring CI of git-annex builds back into green

BF(TST): Relax matching of git-annex error message about unsafe drop, which was changed in 10.20231129-18-gfd0b510573

---

changelog.d/pr-7546.md
datalad/conftest.py

[Pytest 8.0 is coming](https://github.com/pytest-dev/pytest/releases/tag/8.0.0rc1), and one of the breaking changes is [the removal of the `py.path.local` arguments to various hooks](https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path), such as `pytest_ignore_collect()`.  This PR updates our use of that hook.

Update `pytest_ignore_collect()` for pytest 8.0

---

.github/workflows/release.yml

Ideally we should also update it using con/tributors on the list of authors etc, but that is yet to be developed in con/tributors.
For now custom version boost following instructions by @jwodder in https://github.com/datalad/release-action/issues/52

Update also version: field in CITATION.cff  upon release

---

datalad/distribution/install.py

Otherwise lead to the warning
change is so minor that I do not think it is worth a changelog

Escape the \ in a docstring

---

changelog.d/pr-7551.md
datalad/downloaders/http.py
datalad/downloaders/providers.py
datalad/downloaders/tests/test_http.py

It is pretty much the "Bearer TOKEN" method but which uses different keyword "Token".  It is e.g. the one provided by Django REST Framework. GitHub allows for both 'Bearer' and 'Token' keywords: https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28
In our case of DANDI we ran into it only now that we decided to add handling of embargoed datasets, for which we need to authenticate to access the files.  We are using Django REST Framework and insofar decision was made to retain current approach (and fix WWW-Authentication header response), instead of an alternative to allow for both  'Bearer' and 'Token' as was suggested in https://github.com/dandi/dandi-archive/pull/1830
As it is ad-hoc (nothing AFAIK in W3C standard) Authentication response I …

Add the "http_token" authentication mechanism which provides 'Authentication: Token {TOKEN}' header

---

tools/ci/install-singularity.sh

Recently (e.g., https://github.com/datalad/datalad/pull/7559), Singularity installations failed with
```
sudo dpkg -i /tmp/singularity-ce.deb
Selecting previously unselected package singularity-ce. (Reading database ... 282869 files and directories currently installed.) Preparing to unpack /tmp/singularity-ce.deb ...
Unpacking singularity-ce (4.1.1-jammy) ...
dpkg: dependency problems prevent configuration of singularity-ce:
singularity-ce depends on fuse2fs; however:
Package fuse2fs is not installed.
dpkg: error processing package singularity-ce (--install):
dependency problems - leaving unconfigured
Processing triggers for man-db (2.10.2-1) ...
```
This patch adds the missing dependency.

add singularity dependency to installation script

---

datalad/support/annexrepo.py

Since at least Git 2.39.2, the error reads:
❱ git cat-file -p git-annex:remote.log
fatal: invalid object name 'git-annex'.
This change adjusts for this in a similar way it has so far been accounted for

adjust for new error message in git cat-file

---

changelog.d/20240416_194511_michael.hanke_remote_extension.md
datalad/customremotes/main.py

The main entrypoint for annex remotes now also runs the standard extension load hook. This enables extensions to alter annex remote implementation behavior in the same way than other DataLad components.
I see no reason why this code should be an exception.

Load extensions in annex remote entrypoint

---

changelog.d/pr-7581.md
datalad/core/distributed/tests/test_push.py

This commit changes the code of `datalad.core.distributed.tests.test_push::test_force_checkdatapresent` to no longer assume identical timestamps in the local and the remote git-annex branch.
This addresses the occasional failing of  `datalad.core.distributed.tests.test_push::test_force_checkdatapresent`.

Relax condition in `test_force_checkdatapresent` to avoid flaky test failures

---

.appveyor.yml
.github/workflows/benchmarks.yml
.github/workflows/docbuild.yml
.github/workflows/lint.yml
.github/workflows/test_crippled.yml
.github/workflows/test_macos.yml
.github/workflows/typing.yml
changelog.d/pr-7585.md

This switches all tests which still used Python 3.7 to use Python 3.8 (or, in Appveyor, 3.11 - see below).
The only exception, and potentially controversial change, is Appveyor, where I went from 3.7 to 3.11 in e52e761. A move to 3.8 would sound logical, but... if I'm seeing correctly, the only difference between Ubu20P37a & Ubu20P37b versus Ubu20core & Ubu20a1 is that the former had "PY: 3.7", while the latter did not set PY at all. And if I'm reading the logs of the latest Appveyor run correctly, Ubu20core & Ubu20a1 run (implicitly?) on Python 3.8.10. I cound not find confirmation that this is the default, but it seems to be.
An alternative (for Appveyor) would be to set PY for Ubu20core & Ubu20a1 to the newest supported (3.11) and use the other two to test oldest supported (3.8). But …

Stop testing on Python 3.7

---

.github/workflows/benchmarks.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml
.github/workflows/test_macos.yml
changelog.d/pr-7601.md

With this change, if a branch is updated while any of the affected workflows are still running on the branch's previous `HEAD`, the outstanding runs are cancelled.  As a result, the runs for the updated `HEAD` will not have to wait as long for runners to become available, and resources will not be wasted on outdated code.

Cancel lengthy running workflows if a new commit is pushed

---

tools/dtime

Apparently can happen, likely due to multithreading and different threads doing their own timestamping.  Interestingly Python seems to not handle negative time delta "intuitively":
(Pdb) p t
datetime.datetime(2024, 5, 14, 19, 39, 12, 800000)
(Pdb) p prevt
datetime.datetime(2024, 5, 14, 19, 39, 12, 801000)
(Pdb) p t - prevt
datetime.timedelta(days=-1, seconds=86399, microseconds=999000)
*(Pdb) p prevt -t
datetime.timedelta(microseconds=1000)
but since python 2.7 there is "total_seconds" which is behaving as desired and anyways we need those, so we can just use and thus operate correctly also whenever crossing some days boundary (hopefully never).

BF: tools/dtime to handle log line having non-increment timestamp

---

changelog.d/pr-7603.md
datalad/support/archive_utils_patool.py

Since
https://github.com/wummel/patool/commit/de38d945c9d5bf9fd8f606d1dbeca472ce2bff27 the utility functions of patool are into separate files.
This patch handles this changes introduced in version 2.0.0 of patool which becomes the lower version required of patool.

Fix add-archive-content for patool>=2.0

---

CHANGELOG.md
CODE_OF_CONDUCT.md
changelog.d/pr-7610.md
datalad/core/local/tests/test_save.py
datalad/distributed/create_sibling_github.py
datalad/local/remove.py
datalad/local/tests/test_gitcredential.py
datalad/local/tests/test_rerun.py
datalad/support/locking.py
docs/source/changelog.rst

Ran into in the course of
- https://github.com/datalad/datalad/pull/7603

Fixup minor typos in documentation/comments using fresh codespell

---

changelog.d/pr-7619.md
datalad/support/tests/test_parallel.py

On the recent ones we had:
datalad@smaug:/mnt/datasets/datalad/ci/logs/2024$ datalad foreach-dataset -s --o-s relpath bash -c "git grep FAIL.*test_graceful.*assert\ 100"
01/25/pr/7551/8df6c0c/github-Test on macOS-4860-failed/0_test (brew).txt:2024-01-25T19:43:26.2831880Z FAILED ../tests/test_parallel.py::test_gracefull_death - assert 100 > 178
01/25/pr/7551/8df6c0c/github-Test on macOS-4860-failed/test (brew)/8_Run tests.txt:2024-01-25T19:43:26.2831150Z FAILED ../tests/test_parallel.py::test_gracefull_death - assert 100 > 178
02/13/push/maint/b8535c9/github-Test on macOS-4882-failed/1_test (snapshot).txt:2024-02-13T16:01:49.8189220Z FAILED ../tests/test_parallel.py::test_gracefull_death - assert 100 > 107
02/13/push/maint/b8535c9/github-Test on macOS-4882-failed/test (snapshot)/8_Run …

test_gracefull_death: raise test_gracefull_death  threshold to 300 from 100

---

CONTRIBUTING.md
asv.conf.json
setup.py
tools/ci/test-jobs.yml

Closes #7449 
which was already partially done in other PRs (for appveyor). This one should drop from other CIs and docs.

Replace 3.7 with 3.8 in ASV, contributing docs, and matrix for GitHub CI

---

.appveyor.yml
changelog.d/pr-7617.md

ATM our logs are filled up (for appveyor only) with that message:
datalad@smaug:/mnt/datasets/datalad/ci/logs/2024/06$ git grep -c 'channel 22: open failed: connect failed: open failed'
03/pr/7575/78ce071/appveyor-9739-success/3vrfsttokn3sww1p.txt:495
03/pr/7575/78ce071/appveyor-9739-success/v2jqxgatl4ktvapj.txt:495
...
06/push/master/4c7e73d/appveyor-9752-success/my9t8hofyi3wqtog.txt:495
06/push/master/4c7e73d/appveyor-9752-success/wiurn8jerqjjj8eb.txt:495
06/push/master/60b3a58/appveyor-9755-success/g6w8q0pa1cphp4yl.txt:495
06/push/master/60b3a58/appveyor-9755-success/onnalbjghayrae2h.txt:495
11/pr/7592/2783f73/appveyor-9757-failed/uxyukgl6ur9e3okn.txt:176
11/pr/7592/2783f73/appveyor-9757-success/5ehg7v66rwydo09w.txt:495
15/pr/7592/a221897/appveyor-9758-failed/ya8xa1wce2412jgw.txt:411 …

For appveyor ssh setup, setup MaxSessions 100 to avoid 'channel 22: open failed: connect failed: open failed'

---

.github/workflows/test.yml
datalad/support/gitrepo.py

or use `scriv create` locally and include the generated file in the pull request, see [scriv](https://scriv.readthedocs.io/)).

Address github cronjob CI runs issues: inability to build/install old git (wrong version/tag, absent build-depends)

---

README.md
changelog.d/pr-7550.md

Provided a more comprehensive overview description. The current README.md is overflowing with commas, unnecessary information, and is overall worded poorly. 
The entire README.md should be revised to read more comprehensively.
or use `scriv create` locally and include the generated file in the pull request, see [scriv](https://scriv.readthedocs.io/)).
Consider using a task list (e.g., `- [ ] add tests ...`) to indicate remaining to-do items.
Thanks for contributing!

Update README.md: improve wording

---

changelog.d/pr-7622.md
datalad/local/tests/test_wtf.py

See https://github.com/giampaolo/psutil/issues/2109 - reporting of max_path was removed
Should fix our CI which just turned red

Make test for presence of max_path in partitions not run for current psutil 6.0.0

---

.github/workflows/test.yml

should fix one of the failing cron tests. The one left would be NFS fails (#7624) .
edit: I do not think it is worth a changelog since tiny fix for CI testing only

Also apt install build-dependencies for "upstream-git" run (cron only)

---

.zenodo.json

While adding myself to the .zenodo.json file of the handbook in https://github.com/datalad-handbook/book/pull/1229 I noticed that my recorded affiliation here is outdated, since our institute was renamed starting yesterday. This is just a quick fix of that.
Hopefully the new name will stick for a while...
@adswa could you take a look here as well?

Update affiliation of Matthias Riße in .zenodo.json

---

datalad/local/tests/test_add_archive_content.py

I do not think this is the right thing to do so I filed an issue
https://git-annex.branchable.com/bugs/change_in_beh__58___addurls_creates_multiple_commits/?updated
so I would wait for Joey to reply, but otherwise we could be ready to address it here if decide that it is "ok"
Until we decide - our daily tests of git-annex would be failing regularly which could mask other regressions etc. So we might decide to accept it even if temporarily pacify the testing

Relax test to allow now for 2 commits from git-annex for addurl on archive urls

---

changelog.d/pr-7549.md
datalad/distributed/ora_remote.py

The ORA remote (more specifically, its `SSHRemoteIO.ensure_writeable` context manager) runs the `stat` command on the remote end to check file permissions. The command format and its output differ between macOS and Linux ("It doesn't even think about a windows server").
Previously, the format was chosen based on the *local* OS, which makes no sense for a command that is executed on the *remote* end. This led to situations where it was impossible to push data from Mac to Linux because the stat command errored out, and permissions were left incorrect, when moving a file from `transfer` to its desired location - see #7536 
With this change, the ORA remote will run `uname -S` on the remote end (of an SSH connection) to determine where it is operating, if it needs to. To the best of my …

Make ORA remote more aware of the remote OS when using SSH

---

datalad/distributed/tests/test_create_sibling_gitea.py

I want to reenable the gitea tests in datalad-next (https://github.com/datalad/datalad-next/issues/608). However, the demo Gitea instance moved from try.gitea.io to demo.gitea.com. I've migrated the ``dataladtester`` account, and saved the new token in the Appveyor project settings of datalad-next. Locally, tests pass with this change.

Adjust Gitea demo URL to reenable create-sibling-gitea test in datalad-next

---

changelog.d/pr-7636.md
datalad/downloaders/s3.py

This PR should fix an issue with faulty `PROGRESS` commands that were sent from the "datalad" git annex special remote. This error was reported in INM7's "data" matrix channel. Here is an excerpt from the related error messages:
```
external special remote protocol error, unexpectedly received "PROGRESS PROGRESS 69730304" (unable to parse command)
unable to use special remote due to protocol error
external special remote protocol error, unexpectedly received " 61865984" (unable to parse command)
unable to use special remote due to protocol error]
```
The PR ensures that only one thread is "in" the progress bar callback that is used in S3 downloads. IMHO the issue was `boto3.download_fileobj()` (which is used to download S3 objects) can create multiple threads. Therefore the callback might …

Allow only one thread in S3 downloader's progress report callback 

---

docs/source/conf.py

In an email to maintainers of affected projects, readthedocs advised to make configuration changes ahead of the deprecation of injecting Sphinx- related configurations during build time.
For more info, see: https://about.readthedocs.com/blog/2024/07/addons-by-default/
With this deprecation, Read the Docs will stop defining html_baseurl, and it has to be defined on its own to keep the configured canonical custom domain properly configured.
This change adds the recommended configuration change.

INFRA: Add RTD-recommended configuration ahead of deprecations

---

changelog.d/pr-7640.md
datalad/local/tests/test_add_archive_content.py

On OSX we started to fail with
```
>               assert_equal(len(commits_after),
len(commits_prior) + 2
+ self.annex.fake_dates_enabled
+ (external_versions["cmd:annex"] >= "10.20240531+git214"))
../../../../hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/datalad/local/tests/test_add_archive_content.py:610:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
first = 5, second = 6, msg = None
def assert_equal(first, second, msg=None):
if msg is None:
>           assert first == second
E           assert 5 == 6
```
eg in https://github.com/datalad/git-annex/actions/runs/10259203010/job/28383625834 and this must be related to recently fixed by Joey
- [change in beh: addurls creates multiple …

Account for the fix in git-annex behavior in test_add_delete_after_and_drop_subdir

---

changelog.d/pr-7645.md
setup.py

Closes: https://github.com/datalad/datalad/issues/7555

Declare minimal compat version of pytest to be 7.0

---

.appveyor.yml
changelog.d/pr-7649.md

Otherwise we have been failing to upload codecov reports on appveyor for awhile.
The https://cli.codecov.io/macos/latest "folder" cannot be used directly -- url there is leading to versioned codecov release so I am using that one. Pros: no surprises.
Solution found at
https://github.com/codecov/feedback/issues/141#issuecomment-1932418305
Here is how two differ:
❯ wget https://cli.codecov.io/v0.7.4/macos/codecov
...
Length: 22362720 (21M) [application/octet-stream]
Saving to: ‘codecov’
codecov                100%[=========================>]  21.33M  81.5MB/s    in 0.3s
2024-08-30 08:22:04 (81.5 MB/s) - ‘codecov’ saved [22362720/22362720]
❯ wget https://uploader.codecov.io/latest/macos/codecov
...
Length: 52719456 (50M) [application/octet-stream]
Saving to: ‘codecov.1’
codecov.1 …

BF: replace url for codecov uploader for macos to versioned one with two archs

---

.github/workflows/test-label.yml
changelog.d/pr-7590.md

I think we should retain the habit of releasing minor (or eventually next major) versions from `master` while patch fixes from `maint` (we might even keep releasing patch fixes for the prior minor I guess... but probably we shouldn't).
This way we can 'stage' for next minor release while releasing patch releases without bottleneck/force to release miors.
With this PR I want to make sure that when we do release next minor, we do include all fixes from `maint`.
As only pertinent to master branch -- I positioned it against master. Also would make it easier to check
or use `scriv create` locally and include the generated file in the pull request, see [scriv](https://scriv.readthedocs.io/)).
- Sophisticate workflow to trigger also on any other push to `master` or `maint` so it stays "up to …

Make github workflow which would ensure that PR against master would have everything from maint merged

---

changelog.d/pr-7654.md
datalad/core/local/run.py
datalad/core/local/tests/test_run.py

ATM git annex find call would leak error message from git that the path (directory) is not known to it, since git does not track directories. We obviously treat it as error and yield an "error" record. We seems took good care about handling all the other results from annex even though overall command errored out -- so it seems to be safe to just ignore such specific error message and proceed -- apparently there is no subsequent hiccups.
- Fixes #7653

BF: allow for empty output directory to be specified to run

---

docs/source/glossary.rst

This fixes a link, and a description what to find there. No changelog needed IMO

Docs: Fix glossary entry reference to the handbook on extensions

---

datalad/support/exceptions.py
datalad/support/tests/test_captured_exception.py

Inspired by https://github.com/datalad/datalad-container/issues/267
Before this change
> datalad -l debug download-url shub://datalad/datalad-container:testhelper
...
download_url(error): /home/yoh/.tmp/datalad_temp_test_container_files0tvyery_/ (file) [AccessFailedError(Failed to establish a new session 1 times. )] [Failed to establish a new session 1 times. ]
[DEBUG  ] could not perform all requested actions: IncompleteResultsError(Command did not complete successfully. 1 failed:
[{'action': 'download_url',
'error_message': 'Failed to establish a new session 1 times. ',
'exception': Failed to establish a new session 1 times.  [download_url.py:__call__:202,base.py:download:533,shub.py:access:50,shub.py:_resolve_url:39,base.py:fetch:643,shub.py:access:50,base.py:access:174,base.py:_fetch:5 …

ENH: Add information about __cause__ exception in the "exception" printout within result record and its short string version

---

changelog.d/pr-7656.md
datalad/consts.py

It was added there for compatibility in 24d463109ececaa2e9633daa7445516330f01f73 when moved deeper in hierarchy.
I think it would be best for us to avoid deeper imports in this file and thus to avoid possible circular imports observed in the past. Ref: https://github.com/datalad/datalad/issues/7393
Even though it would "break" external API, I think it is unlikely someone relies on this in extensions (I could be proven wrong), and thus I think it should be ok to release in minor release.

Remove import of GIT_SSH_COMMAND within .consts (import directly from datalad.runner.gitrunner)

---

datalad/support/gitrepo.py

Leads to such messages as
❯ datalad get . -r
[WARNING] Failed to get 'tests/data-for-tests.path', skipping this submodule
which are misleading

fix: remove unnecessary and confusing .path from error message

---

.appveyor.yml
.github/workflows/benchmarks.yml
.github/workflows/docbuild.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml
.github/workflows/typing.yml
CONTRIBUTING.md
_datalad_build_support/setup.py
asv.conf.json
changelog.d/pr-7682.md
datalad/cli/parser.py
datalad/support/parallel.py
setup.py
tools/ci/test-jobs.yml
tox.ini

Individual commits have a little more to say.
- also addresses #7678 
We should release either with this or #7679 to fix #7678 which renders extensions unusable on debian ATM.
TODOs

Drop Python 3.8

---

changelog.d/pr-7679.md
datalad/cli/parser.py

Apparently we have not been loading them upon error in early parsing. Debian has python 3.12 patched with some patches from what came after 3.14 (!) and that broke that interface.  We silently just did not even try to get those parsers in place.  With this change we would
TODOs
- ~~add a fix to actually use that new `intermixed` flag~~ -- we seems just need to drop 3.8 and stop using the protected method there -- will do separate PR!  That would also unblock testing datalad-neuroimaging which dropped 3.8 already
- In effect fixes #7678

fix: do load extension interfaces if early parsing errors out

---

changelog.d/pr-7687.md
datalad/core/local/tests/test_save.py

The whole point for that "permissions" trick was to ensure that git does not go into submodules and thus we would be "optimized" and not waste cycles where not desired.  But the very fact that it errors out points that it is not the case.
So this provides only taming down for
https://github.com/datalad/datalad/issues/7681
and for a proper solution we better first wait on what git gurus say in
https://lore.kernel.org/git/ZzyyQpJw-kxJA7IS@bilena/T/#u

test: xfail test_subsuperdataset_save on newer gits

---

tox.ini

Although we might just want to get rid of that dependency -- not developed much any longer

Ignore deprecation warning from httpretty

---

.appveyor.yml
changelog.d/pr-7692.md

"snapshot" method is installing into a temp folder and we would need to setup env var file to source etc.
I have introduced that change in recent https://github.com/datalad/datalad/pull/7682 and missed that for that original commit appveyor did fail, and subsequent commit af2bd74 CI run had only OSX brew fail which made me think appveyor is ok, but apparently it was not there at all! So I missed that failure

BF: use datalad/packages method of installing git-annex

---

datalad/support/exceptions.py
datalad/support/parallel.py
datalad/support/tests/test_captured_exception.py
datalad/support/tests/test_parallel.py
tools/ci/test-jobs.yml

Debian has 3.13 already and my attempt to build 1.1.4 for Debian has failed. Hence had to look.
Changes of `CapturedException` as minimal and likely do not capture prior difference in use of `.__str__` vs `.__qualname__`. But I do not think there is anything we could do about that now that there is no `exc_type` stored. May be @bpoldrack would find a moment to have a look. 
Meanwhile I will run this version of the patch into debian package.
TODO

Add 3.13 testing/support

---

changelog.d/pr-7710.md
tools/ci/test-jobs.yml

ATM 3.13 environment cannot install our old minimal git-annex version, try
rm -rf /tmp/test-env*; src/datalad_installer.py -E /tmp/test-env.sh miniconda --batch --path /tmp/test-env -c conda-forge -e python=3.13 git-annex=8.20201007
and I now spotted that we did custom installation for 3.12 so I guess we are doomed to do that for 3.13 as well.  Verified that
rm -rf /tmp/test-env*; src/datalad_installer.py -E /tmp/test-env.sh miniconda --batch --path /tmp/test-env -c conda-forge -e python=3.13 git-annex
worked

chore: for github tests CI - py 3.13 matrix should also (as for 3.12) use most recent available git-annex

---

.github/workflows/docbuild.yml
_datalad_build_support/setup.py
pyproject.toml

May be in the future we should just switch to a more generic exception type there if that code is still relevant at all
Closes #7722 
edit 1: oh no!  Since we never swallowed the pill to distill a single of those https://github.com/datalad/datalad-buildsupport deprecating never used https://github.com/datalad/datalad_build_support, and duplicated the code everywhere, we have the same issue in extensions! heh  ... separate issue/PRs to push
edit 2.1: oh -- it was actually here (and those few other extensions and our extensions templa) where in our attempt to "get rid of distutils" we moved from that import to be done from `distutils.errors` in 40ce29923ec1d22174b0624bd1166cd670b61a0e. 
final edit: **the verdict is to import and use `OptionError` (not `DistutilsOptionError`) from …

BF: import from distutils.errors directly if no longer in setuptools

---

_datalad_build_support/formatters.py
changelog.d/pr-7714.md

This small PR resolves the `datetime` library warnings:
```python
/home/runner/work/datalad/datalad/_datalad_build_support/formatters.py:39: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```

Resolve datetime library warnings

---

.github/workflows/benchmarks.yml
.github/workflows/test.yml
.github/workflows/test_crippled.yml
.github/workflows/test_extensions.yml

otherwise -- our CI is very red now

[DATALAD RUNCMD] Use ubuntu-22.04 until we fixup NeuroDebian APT for recent debian/ubuntu

---

CONTRIBUTING.md
changelog.d/pr-7734.md
datalad/interface/common_cfg.py

We also have handling of DATALAD_LOG_OUTPUT but it is not interfaced in common_cfg.py thus I do not mention
*Proof*:
```shell
❯ DATALAD_LOG_LEVEL=debug datalad wtf 2>&1 | head -n 2
[DEBUG] Not retro-fitting GitRepo with deprecated symbols, datalad-deprecated package not found 
[DEBUG] Command line args 1st pass for DataLad 1.1.5. Parsed: Namespace(cfg_overrides=None, change_path=None, _=False, log_level='warning', common_on_failure=None, common_report_status=None, common_report_type=None, common_result_renderer='tailored', common_debug=False, common_idebug=False, version=None) Unparsed: ['wtf'] 
❯ DATALAD_LOG_LEVEL=debug datalad wtf 2>/dev/null | head -n 2
```
and code is here https://github.com/datalad/datalad/blob/HEAD/datalad/log.py#L614

DOC: clarify in config documentation that we log to stderr not stdout

---

changelog.d/pr-7730.md
datalad/distribution/create_sibling.py

`/bin/ls` is not available on every unix system like on mine (NixOS).
This should fix the compatibility issue

Remove absolute path specification from `/bin/ls` invocation while interrogating remote path

---

datalad/local/foreach_dataset.py

The help page of "foreach-dataset" could be more accessible to non-technical people w.r.t. usage of the {ds} and {refds} placeholders. Added two common cases on how to use it and where to find more info

foreach-dataset: add common usage options of {ds} and {refds} to datalad help

---

datalad/distributed/tests/test_create_sibling_ghlike.py
datalad/distribution/tests/test_get.py

Our cron etc was failing once in a while, primarily under `sudo -E due` to this test timing out
datalad@smaug:/mnt/datasets/datalad/ci/logs/2025/09$ git grep -l 'FAILED.*test_create_sibling_ghlike.py::test_invalid_call'  | nl
1	19/cron/20250919T062703/aea09a7/github-Test-766-failed/5_test (3.9).txt
2	19/cron/20250919T062703/aea09a7/github-Test-766-failed/7_test (3.9, true, sudo -E, 0).txt
3	19/cron/20250919T062703/aea09a7/github-Test-766-failed/test (3.9)/18_Run tests.txt
4	19/cron/20250919T062703/aea09a7/github-Test-766-failed/test (3.9, true, sudo -E, 0)/18_Run tests.txt
5	25/cron/20250925T062740/aea09a7/github-Test-772-failed/6_test (3.9, true, sudo -E, 0).txt
6	25/cron/20250925T062740/aea09a7/github-Test-772-failed/test (3.9, true, sudo -E, 0)/18_Run tests.txt …

Mark test_create_sibling_ghlike::test_invalid_call and test_get_flexible_source_candidates_for_submodule as slow
